### ISSUE TITLE
Option to disable "Checking mail" notification.

### ISSUE THREAD

**Issue by Abscissa** [k9mail/k-9#1009]
Being notified that the mail accounts are being checked isn't very useful for most people. Generally people only care when they actually get new messages, not every time the server is queried. It'd be nice to be able to disable that notifiction without resorting to android's course-grained "block ALL notifications from a particular app".

**Comment by Nergal-di-Cuthah** [comment]
Its already there.  Per account settings, notifications, at the bottom "show sync"

**Comment by Abscissa** [comment]
/facepalm. I do't know how I managed to miss that all the times I've looked over the nearly two years I've been using K-9. Thanks, and pardon the noise.
