### ISSUE TITLE
K-9 w/ OpenKeychain not declaring content type encrypted

### ISSUE THREAD

**Issue by sc-perth** [k9mail/k-9#1012]
Extract from header for an e-mail sent, encrypted & signed, by K9 mail:
```
User-Agent: K-9 Mail for Android
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8
```

K-9 Mail version 5.007
OpenKeychain version 3.7
Phone model: SAMSUNG-SM-N910A (Samsung Galaxy Note 4)
Android Version: 5.1.1 (Kernel 3.10.40-5613584)

Setup: K-9 Mail handing off to OpenKeychain (using Yubikey for storage of private keys and performing the decrypt/signing operations).

Let me know if you want any more info & thanks for the awesome app!

**Comment by cketti** [comment]
K-9 Mail 5.007 only supports inline PGP which puts the encrypted data inside the text part.
A content type of `multipart/encrypted` is only used with PGP/MIME.
