### ISSUE TITLE
Android 6.0 delete mail ui jumpy

### ISSUE THREAD

**Issue by slumx** [k9mail/k-9#1025]
After upgrading to android 6.0 the mail list jumps up and down (stutters)  when I delete an email

**Comment by cketti** [comment]
See #747

**Comment by slumx** [comment]
No, that does not fix it on Android 6.0

**Comment by cketti** [comment]
I'm sorry. This doesn't seem to be a widespread issue. I don't see anyone spending time on gathering the necessary information to reproduce and fix this bug.
But it's likely the problem will disappear when we get to the UI overhaul.
