### ISSUE TITLE
Deleting on Server when not supposed to

### ISSUE THREAD

**Issue by stoptheinsanity** [k9mail/k-9#1026]
I may be misunderstanding the settings here - The following is my setup:

Android 5.1.1
I have all of my account settings 
Fetching>> Sync Server Deletions (Remove messages when deleted on server) Yes
When I Delete a Message >> Do NOT delete on Server
Erase deleted messages on server >> Manually.

If I delete all of my Inbox messages then choose to "Empty Trash" does that delete all of the messages in my Inbox on the server them empty the server trash? That seems to be happening.  There is nothing in your settings or explanations that indicate that should be happening.  I am trying to keep my phones Inbox clean, and save the messages on the server.

**Comment by cketti** [comment]
There was a bug that caused the "When I delete a message" value to be overwritten with the default. Make sure you update to K-9 Mail 5.007 and change the setting to the desired value.

**Comment by stoptheinsanity** [comment]
I am already using K-9 v5.007

On January 20, 2016 9:06:48 PM PST, cketti <notifications@github.com> wrote:
>There was a bug that caused the "When I delete a message" value to be
>overwritten with the default. Make sure you update to K-9 Mail 5.007
>and change the setting to the desired value.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1026#issuecomment-173453189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stoptheinsanity** [comment]
This is still an issue. Maybe if you told me what the exact settings should be for an IMAP email account? Also, I see no way to verify global settings or override them. What am I missing?
