### ISSUE TITLE
Android: difficulty refreshing folders while using certain wifi

### ISSUE THREAD

**Issue by archstuff** [k9mail/k-9#1031]
The application works well over mobile networks and most wifi networks but, with my home wifi, manual refresh causes the app to sit continuously in what looks like 'polling' mode. The only way out of this is to close the app and restart and this then causes a successful poll.
I, and visitors, do not experience any other wifi issues so I guess that it is something peculiar to my wifi set-up. Anyone any ideas?

Thanks.

John

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
