### ISSUE TITLE
File browser not available when selecting attachments

### ISSUE THREAD

**Issue by c5brown** [k9mail/k-9#1033]
When sending emails I cannot select files.  The options available does not in lude the file browser,  just basically photo apps.  To get around I can upload file to one drive and then select it that way,  but if in cloud no reason to send via email.  Can send link via one drive.  

If option available to share/export from an app,  can choose k9 mail and send file as attachment,  just cannot do it directly with k9 mail.  

This did not exist previously so not sure if caused by an update or something. 

Tried attaching screenshot. Nothing on this form to indicate wwhether it has been attached or not.

**Comment by cketti** [comment]
Try using another file manager. If that doesn't solve your problem please use the [mailing list](http://groups.google.com/group/k-9-mail) to ask for help.
