### ISSUE TITLE
Get rid of 8bit transport encoding

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1034]
Supporting both `quoted-printable` and `8bit` as transport encoding is adding unnecessary complexity without much gain.
Right now we use a transfer encoding of `8bit` when we compose a message. And when we connect to a SMTP server that does not support 8-bit messages we have to re-encode the message right before sending.

See also #582.

**Comment by Valodim** [comment]
So, should we ditch `setUsing7BitTransport` entirely? Or are there other scenarios where we might need the functionality, e.g. bouncing a message we didn't create ourselves to a 7bit server or something like that?

**Comment by cketti** [comment]
Yes, I'm all for removing `setUsing7BitTransport` entirely. We might want to include the functionality again at a later point. But it should be a separate class creating new Message/Part/Body instances, not living inside those classes.

**Comment by Valodim** [comment]
how about ditching `Body.setEncoding` as well in favor of `Body.createCopyWithEncoding` (or `BodyTransformHelperClassBuilderProvider.createCopyWithEncoding`)?

**Comment by Valodim** [comment]
Ok so for everything we generate, it's fairly simple: Just set encoding to 7bit for multiparts, quoted-printable for TextualBody, and base64 for (most) attachments.

What's a little more difficult is, what do we do with an attached for forwarded rfc822 message? If we want to keep that message inline, we have to be able to 7bit-reencode it.

**Comment by cketti** [comment]
I believe `Body.setEncoding()` is used during regular creation of a message, not to rewrite an existing one. So I'd hold of on modifying that one.

Re-encoding messages/message parts should be handled by a separate class. Also, I wouldn't add `is7BitClean()` to Part. It's not an interesting information outside of the re-encoding process.

Otherwise, the plan sounds good. Use `quoted-printable` and `base64` for all bodies we create.

**Comment by Valodim** [comment]
relevant info at https://en.wikipedia.org/wiki/8-bit_clean, apparently qmail and exim simply assume all MTAs handle 8bit at this point regardless of their capability announcements. djb also has a strong opinion about this ([click](http://cr.yp.to/smtp/8bitmime.html))

**Comment by cketti** [comment]
Since PR #1554 was merged we always create 7-bit messages.

Allowing arbitrary messages to be forwarded as attachment (see #1728) introduces the possibility that we send a message with 8-bit parts. Since this doesn't appear to be a problem in practice I'd say we just send the message as is, even if the SMTP server doesn't announce support for the 8BITMIME extension.
