### ISSUE TITLE
Default IMAP sent folder should be the "Sent" folder irrespective of the configured language

### ISSUE THREAD

**Issue by SR-gh** [k9mail/k-9#1036]
Maybe is it a translation issue :

When creating an account with the french version of K9mail, the default folder where are stored sent emails is "Envoyés".
Most email readers actually use the "Sent" folder but *display* a translated name for this folder in the UI : "Envoyés" or "Messages envoyés".
If they do, all email client using IMAP consequently have a common default configuration (and, for part of them, default configuration is the only configuration :( ).

I have seen that I can choose the folder to save sent emails in, but it took me time to figure out what was happening, as, in the first place, it took me time to discover that I was having a problem.

**Comment by dolohow** [comment]
:+1:

**Comment by clawoflight** [comment]
Are you sure? I have all my stuff in english now, but I vaguely remember Thunderbird with a german translation would create an actual german folder by default.

**Comment by SR-gh** [comment]
Sure of what ? I'm no IMAP expert.
But, before posting, I have checked the behaviour of Thunderbird (french version) and roundcube (Webmail).
Both use Sent (and Thunderbird does not display "Sent").
I've seen that RFC 6154 specifies extensions for this purpose. Regardless of the availability of this extension on the server, my personnal use of multiple email clients, with the same account, on different platforms, during the same period shows that it would have been easier if a language parameter on the client side have not interfered with the mail location on the server.
That's an opinion, and a request :)

**Comment by cketti** [comment]
If the server supports the LIST extension for special-use folders, K-9 Mail will use those folders.
If not, a localized name will be used by default. You can manually configure special folders later.

I don't feel like changing this. There is no standard for Sent folder naming across providers. So while "Sent" might work for you, it will not for others. Having a localized name will at least tell people what the folder is used for, even when they don't speak English.
