### ISSUE TITLE
K9 fails to connect to Exchange server

### ISSUE THREAD

**Issue by danielcra** [k9mail/k-9#1038]
Hi there,

I am trying to use K9 with an Exchange account at the popular German email provider freenet.de in order to get push mail. However, K9 v5.007 fails to connect with "Cannot not connect to server (IOException)". Will attach the ADB debug.

I am wondering if this is a duplicate of https://github.com/k9mail/k-9/issues/606.
Strange thing is that with the standard Android Email client, at least the one that comes with Android-x86 4.4, everything works fine (same provider, same settings, i.e. SSL port 443). Could it be the Android client contains code for newer Exchange servers? If that was the case can it be lifted into K9?

The standard Android Email has another severe problem so it is impossible for me to use it. But I really, really need push email. IMAP idle does not seem to work with freenet. With IMAP poll, freenet takes very long to deliver, even if you poll by hand every couple of seconds, so I really would appreciate some sort of help.

Thanks
Dan

**Comment by danielcra** [comment]
Here's the ADB debug printout:
01-26 10:11:51.235 I/k9      ( 1902): Committing preference changes
01-26 10:11:51.325 I/k9      ( 1902): Preferences commit took 90ms
01-26 10:11:53.722 I/k9      ( 1902): Committing preference changes
01-26 10:11:53.737 I/k9      ( 1902): Preferences commit took 15ms
01-26 10:13:16.562 I/k9      ( 1902): Committing preference changes
01-26 10:13:16.573 I/k9      ( 1902): Preferences commit took 11ms
01-26 10:13:20.309 I/k9      ( 1902): Running Foreground command 'getFolderUnread:john exchange:INBOX', seq = 19
01-26 10:13:20.310 I/k9      ( 1902): Foreground Command 'getFolderUnread:john exchange:INBOX' completed
01-26 10:13:30.199 I/k9      ( 1902): Committing preference changes
01-26 10:13:30.210 I/k9      ( 1902): Preferences commit took 11ms
01-26 10:13:31.784 V/k9      ( 1902): Starting uri = 'https://mailsync.freenet.de:443/Exchange/john.doe@freenet.de'
01-26 10:13:31.784 V/k9      ( 1902): url = 'https://mailsync.freenet.de:443/Exchange' length = 40, end = 'john.doe%40freenet.de' length = 26
01-26 10:13:31.784 I/k9      ( 1902): url = https://mailsync.freenet.de:443/Exchange/john.doe%40freenet.de
01-26 10:13:31.784 I/k9      ( 1902): Requesting gzipped data
01-26 10:13:32.078 E/k9      ( 1902): IOException: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:13:32.078 E/k9      ( 1902): Trace: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:813)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.authenticate(WebDavStore.java:718)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.checkSettings(WebDavStore.java:373)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
01-26 10:13:32.078 E/k9      ( 1902): Error while testing settings
01-26 10:13:32.078 E/k9      ( 1902): com.fsck.k9.mail.MessagingException: IOException
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:819)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.authenticate(WebDavStore.java:718)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.checkSettings(WebDavStore.java:373)
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
01-26 10:13:32.078 E/k9      ( 1902): Caused by: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:13:32.078 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:813)
01-26 10:13:32.078 E/k9      ( 1902):     ... 3 more
01-26 10:13:35.673 I/k9      ( 1902): Committing preference changes
01-26 10:13:35.682 I/k9      ( 1902): Preferences commit took 9ms
01-26 10:13:35.687 I/k9      ( 1902): Running Foreground command 'getFolderUnread:john exchange:INBOX', seq = 20
01-26 10:13:35.687 I/k9      ( 1902): Foreground Command 'getFolderUnread:john exchange:INBOX' completed
01-26 10:16:08.529 I/k9      ( 1902): Running Foreground command 'getFolderUnread:john exchange:INBOX', seq = 21
01-26 10:16:08.534 I/k9      ( 1902): Foreground Command 'getFolderUnread:john exchange:INBOX' completed
01-26 10:16:19.097 I/k9      ( 1902): Committing preference changes
01-26 10:16:19.107 I/k9      ( 1902): Preferences commit took 10ms
01-26 10:16:22.137 V/k9      ( 1902): Starting uri = 'https://mailsync.freenet.de:443/Exchange/john.doe@freenet.de'
01-26 10:16:22.137 V/k9      ( 1902): url = 'https://mailsync.freenet.de:443/Exchange' length = 40, end = 'john.doe%40freenet.de' length = 26
01-26 10:16:22.137 I/k9      ( 1902): url = https://mailsync.freenet.de:443/Exchange/john.doe%40freenet.de
01-26 10:16:22.137 I/k9      ( 1902): Requesting gzipped data
01-26 10:16:22.437 E/k9      ( 1902): IOException: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:16:22.437 E/k9      ( 1902): Trace: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:813)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.authenticate(WebDavStore.java:718)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.checkSettings(WebDavStore.java:373)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
01-26 10:16:22.437 E/k9      ( 1902): Error while testing settings
01-26 10:16:22.437 E/k9      ( 1902): com.fsck.k9.mail.MessagingException: IOException
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:819)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.authenticate(WebDavStore.java:718)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.checkSettings(WebDavStore.java:373)
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
01-26 10:16:22.437 E/k9      ( 1902): Caused by: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
01-26 10:16:22.437 E/k9      ( 1902):     at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:813)
01-26 10:16:22.437 E/k9      ( 1902):     ... 3 more

**Comment by cketti** [comment]
K-9 Mail only supports WebDAV, not Exchange ActiveSync (EAS).

**Comment by ro0ter** [comment]
Any plan on implementing the activesync?

**Comment by adebyrne** [comment]
Any update here, same problem re ActiveSync
Will it ever work?
Ta
