### ISSUE TITLE
Problem with K9 on Cyanogenmod 13

### ISSUE THREAD

**Issue by Daveron81** [k9mail/k-9#1043]
Hi,

Cyanogenmod 13 is having problems with K9. Application is crashing just after the startup with exception enclosed bellow:

01-27 11:06:52.754  2489  2489 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:116)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:190)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:165)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.getFactory(WebView.java:2277)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2272)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2331)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.view.View.<init>(View.java:3795)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.view.View.<init>(View.java:3898)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.view.ViewGroup.<init>(ViewGroup.java:573)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:597)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:542)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:525)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:512)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebView.<init>(WebView.java:502)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at de.cketti.library.changelog.ChangeLog.getDialog(ChangeLog.java:285)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at de.cketti.library.changelog.ChangeLog.getLogDialog(ChangeLog.java:263)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:230)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.Activity.performCreate(Activity.java:6251)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:148)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-27 11:06:52.754  2489  2489 E WebViewFactory: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:138)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:114)
01-27 11:06:52.754  2489  2489 E WebViewFactory: 	... 29 more
01-27 11:06:52.755  2489  2489 D AndroidRuntime: Shutting down VM
01-27 11:06:52.756  2489  2489 E AndroidRuntime: FATAL EXCEPTION: main
01-27 11:06:52.756  2489  2489 E AndroidRuntime: Process: com.fsck.k9, PID: 2489
01-27 11:06:52.756  2489  2489 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageList}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:218)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:165)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.getFactory(WebView.java:2277)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2272)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2331)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.view.View.<init>(View.java:3795)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.view.View.<init>(View.java:3898)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.view.ViewGroup.<init>(ViewGroup.java:573)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:597)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:542)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:525)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:512)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:502)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at de.cketti.library.changelog.ChangeLog.getDialog(ChangeLog.java:285)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at de.cketti.library.changelog.ChangeLog.getLogDialog(ChangeLog.java:263)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:230)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	... 9 more
01-27 11:06:52.756  2489  2489 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:116)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:190)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	... 28 more
01-27 11:06:52.756  2489  2489 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:138)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:114)
01-27 11:06:52.756  2489  2489 E AndroidRuntime: 	... 29 more
01-27 11:06:52.760   684  1995 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
01-27 11:06:52.830   684  1889 I OpenGLRenderer: Initialized EGL, version 1.4
01-27 11:06:53.296   684   711 W ActivityManager: Activity pause timeout for ActivityRecord{e623e35 u0 com.fsck.k9/.activity.MessageList t78 f}
01-27 11:06:53.324   684   834 E QCOM PowerHAL: Failed to acquire lock.

Im using Cyano 13 (Android 6.0.1).
Cyano version: 13.0-20160112-NIGHTLY-klte
API Level: Dragon Fruit (4)
Kernel Version: 3.4.0-gdd61626 (11 Jan 2016)

Could u send me any clues how to correct this issue? Where could i obtain missing packages and how to add them? 

Best regards, 
Konrad

**Comment by cketti** [comment]
This doesn't look like a bug in K-9 Mail. Please report it to Cyanogen.
