### ISSUE TITLE
Tap tactile tick box for message selection is too small in folder list

### ISSUE THREAD

**Issue by doublehp** [k9mail/k-9#1046]
Android 4.4.2
HTC One M8
K9 5.007

In folder listing view.

When I want to select one message, the first message I want to select, I need to tap on the small box on left on line. For following messages, I can tap anywhere in the line, near the box, or not.

The issue is that I have to tap exactly in the middle of the tick box. If I tap just above, below, or left of the box, by a few pixels, the message will open, in the read view. The graphic of the tick box is fine, but the tactile space should not be exactly matching the graphics; the tactile zone should be larger than the graphics, and selection should start when I tap any place near the box; the tactile zone should be as large as the height of the message line (this height may vary with DPI). The graphic box is centered vertically; the tactile zone should spread over the full height of line, and at least as large as the height. But maybe, the tactilke zone should (maybe, debatable) go to the left edge.

**Comment by cketti** [comment]
You're right. But the checkboxes will be removed with the design overhaul.

Currently you can select a message in the list by swiping from left to right. Subsequent messages can be selected with a single tap.
