### ISSUE TITLE
Where did my emails go?

### ISSUE THREAD

**Issue by JPBELLIS** [k9mail/k-9#1049]
I just installed the app on my Galaxy 6 edge.  Emails come in but as soon as I read them they disappear. I can't find setting to not delete them anywhere.  Is this standard for this product?  I can't imagine it is.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by JPBELLIS** [comment]
So you just tell me to post somewhere else and close my inquiry.  now
that's customer service.  the exact same type that will give you a 1 star
and a deletion
