### ISSUE TITLE
Can't place widget on home screen

### ISSUE THREAD

**Issue by JeffGillman** [k9mail/k-9#1051]
Device: Samsung Galaxy Note5 (SM-N920V), Android 5.1.1
This is a new phone for me, and I've been customizing the home screens. I've been able to work with many other widgets, as expected: press and hold on home screen, choose widgets, press and hold widget and drag to its place. However, when I try to do that with either of the K-9 widgets, it merely opens K-9, and never drops the widget on the home screen.

**Comment by cketti** [comment]
It's a configuration screen. You have to select which account should be used with the widget.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
