### ISSUE TITLE
encrypted.asc attachment

### ISSUE THREAD

**Issue by JasperWeiss** [k9mail/k-9#1054]
When receiving encrypted mails I get no text but instead I get an attachment called encrypted.asc.

**Comment by mawiegand** [comment]
What version of k-9 are you using?

**Comment by JasperWeiss** [comment]
I'm using V.5.007, the latest release on the playstore.

**Comment by JasperWeiss** [comment]
The header looks as follows:

Return-Path: <xxxxxxxxxxx>
Received: from 127.0.0.1 ([69.195.xxx.xx])        by smtp.gmail.com with ESMTPSA id xxxxxxxxxxxxxxxxxxxxxxxx        for <xxxxxxxx@gmail.com>        (version=TLSv1/SSLv3 cipher=OTHER);        
Sat, 30 Jan 2016 11:53:18 -0800 (PST)
To: xxxxxxxxxxxxxx
From: xxxxxxxxxxx <xxxxxxxxxx@gmail.com>
Subject: xxxxx
Message-ID: <xxxxxxxxxxxxx@gmail.com>
Date: Sat, 30 Jan 2016 19:53:15 +0000
MIME-Version: 1.0
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted"; boundary="smoHAeLlmbtxIHSmqN9Pq05PSNxvQuFWW"
Content-Transfer-Encoding: 8bit

Messages that I can decrypt without problems look like:

Date: Sat, 30 Jan 2016 23:31:35 +0100
From: xxxxxxxx <xxxxxxxxxxx@gmail.com>
To: "xxxxxxxx@gmail.com" <xxxxxxxx>
Subject: 
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
Message-ID: <xxxxxxxxxxxx@gmail.com>

It may have to do with the 'content-type'

**Comment by Valodim** [comment]
this is pgp/mime, which is not supported in current stable release. we're working on it.

**Comment by JasperWeiss** [comment]
@Valodim
I understand there's different formats for Pgp

Inline/PGP, S/MIME, PGP/MIME, which one would you recommend using?

**Comment by Valodim** [comment]
this is not a choice that should be made by the user, and if we get this right you should not need to know these names to use pgp in the first place. 

(on a related note, s/mime is not related at all to pgp)

**Comment by JasperWeiss** [comment]
Oh I see, inline/pgp puts the blop inside the message whereas pgp/mime keeps the pgp stuff seperate meaning clients that don't support pgp will just show an empty message rather than the blop. (Like signatures, they look ugly/weird to people unfamilliar with pgp)

Great, hope to see pgp/mime support in the feature.

**Comment by PaulWoitaschek** [comment]
Any news when this could be? I'm receiving more and more mails k9 can't decrypt and its quite a showbreaker. Especially for people new to encryption.

**Comment by JasperWeiss** [comment]
As of the latest alpha, PGP/Mime is support is present. Inline doesn't seem to work anymore though

**Comment by lnalex** [comment]
V.5.010 and not fixed yet...

**Comment by Valodim** [comment]
We know.
