### ISSUE TITLE
Add ability to move messages between local folders (POP3)

### ISSUE THREAD

**Issue by wrooot** [k9mail/k-9#1055]
It can be useful to be able to move messages between folders (e.g. in case of accidental delete of messages (move back to Inbox), or if you want to save your Sent messages (move from Sent to Inbox, then download with desktop client), etc.)

Requests on the forums:
https://groups.google.com/forum/#!topic/k-9-mail/_GHlgyELbXE
https://groups.google.com/forum/#!topic/k-9-mail/fRyQVFT9byk

**Comment by cketti** [comment]
See #648 

POP3 doesn't support uploading messages. So "move from Sent to Inbox, then download with desktop client" isn't possible.
