### ISSUE TITLE
Lack of multithreading

### ISSUE THREAD

**Issue by bobafetthotmail** [k9mail/k-9#1056]
I'm syncing folders on my quad-core phone with k-9, and I have Tinycore app that shows CPU core usage. Cyanogenmod 13, "sprout4" device (android one smartphones)

k-9 usually loads 100% a single core, gives a minor(if any) load on another and lets the other two cores remain offline (I have hotplug governor, unused cores are shut down).

The point is that while synching the app does show lag and lack of responsiveness when moving in the menu and reading e-mails in another folder/account.

While the rest of the phone is pretty fine, and can multitask without issues.

I'm suspecting that with better multi-threading the user experience can be improved.

p.s. I'm also using OpenKeychain, don't know if it is related

**Comment by cketti** [comment]
K-9 Mail uses a background thread with a low priority to synchronize messages. While the code is not perfect the UI shouldn't be affected by this per se. But what happens is that synchronizing messages will perform lots of disk operation. So all operations that need to read to of write from storage will be slower while messages are being fetched.
There's not too much we can do about that. Optimizations on that level are certainly a very low priority given all the other open issues.
