### ISSUE TITLE
Replies should send from the identity that matches the "To" address in original email

### ISSUE THREAD

**Issue by odbol** [k9mail/k-9#1064]
I have multiple identities set up that all forward to the same account. Let's call them tyler@one.com and tyler@two.com (default):

1. Receive email addressed to tyler@one.com
2. Hit "Reply All"

Actual behavior: Reply "From" address is tyler@two.com, because it's set as my default. Also, the tyler@one.com is in the recipients list, since it's a Reply All.

Expected: Reply "From" address should be the address that the original email was addressed to: tyler@one.com. Also, that address should not appear in the recipients list.

**Comment by cketti** [comment]
You have to set up tyler@one.com as identity in K-9 Mail. Otherwise the app can't know the message was sent to one of your addresses.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by alanthehat** [comment]
I'm confused by the use of "forward" & "Reply all" in the OP. 
I'm also confused about how mails to these addresses could be arriving in K-9 without being set up

**Comment by odbol** [comment]
Sorry, I will try to explain more:

I have set up both tyler@one.com and tyler@two.com as Identities in K-9. Those Identities both *receive* email on the same account (they are both email aliases to the same IMAP account). 

When I receive an email on that account addressed to tyler@two.com, and I press the "Reply" or "Reply All" buttons, it works correctly, because tyler@two.com is my default Identity. 

However, the bug is when I press the "Reply All" button on an email addressed to tyler@**one**.com, in the same IMAP account. In the reply email, the sender/from field is populated with the *default* Identity, tyler@two.com. Instead, it should populate the sender field with the tyler@**one**.com Identity (since that's who it was addressed to.)

What ends up happening is that I accidentally send personal emails from my business account, since my business account is the default. K-9 is not properly setting the sender Identity to the Identity to which the original email was addressed.

**Comment by alanthehat** [comment]
I have accounts at GMail & Yandex, both of which have alternatives after the '@' & both of which allow <username>+<arbtrary-keyword>@<server> addresses - eg me@gmail.com or me+github@googlemail.com would both reach the same user called 'me'
Is this the problem you're having?

**Comment by odbol** [comment]
@alanthehat that's great! That means you can test this for yourself and see that it is indeed a bug:

0. Assuming you already have an Identity for me@gmail.com and it's the default.
1. Set up an Identity for me+github@googlemail.com.
2. Send an email to me+github@googlemail.com
3. Once you receive that email, press "Reply All".

Expected behavior: The From/Sender Identity should be set to me+github@googlemail.com, and it should not CC that me+github@googlemail.com address.

Actual behavior: The From/Sender Identity is me@gmail.com (the default): this is the wrong sender address.

**Comment by odbol** [comment]
Ah, nevermind, I found out what was wrong: I had set up the Identity on a different account. Didn't realize Identities weren't shared between accounts.

**Comment by numericOverflow** [comment]
I'm running K-9 v5.6.00 and noticed that I have to manually select the identity that matches the sender every time, even though I have the identity setup with the associated account.  Every time I start a reply, it defaults from my primary identity and not the matching identity.  Is this a bug, or working as expected?

I expected K-9 would work like most other email programs and look at the "TO:" field, if there's a matching identity sonfigured, automatically send replies from that matching identity and override the default identity.
