### ISSUE TITLE
K9-Mail fails emailprivacytester.com Meta-refresh test - data is being leaked.

### ISSUE THREAD

**Issue by BostonEnginerd** [k9mail/k-9#1067]
### Expected behaviour
If the user receives an email from emailprivacytester.com and opens it, no information should leak to the service.

### Actual behaviour
A webpage is opened and the "meta-refresh" remote tracker is triggered. This can allow an attacker to load a malicious webpage.

The meta-refresh tag puts the following into the html <head>:
<meta http-equiv="Refresh" content="1; URL=http://TRACKING_URL/">

My result:
https://emailprivacytester.com/e72483a201897d0b

### Steps to reproduce
1. Go to emailprivacytester.com and enter your email address.
2. Open the email in K9-mail
3. Look at the test webpage on your PC and see that the meta-refresh test failed.

### Environment
K-9 Mail version: 5.107

Android version:5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
See #712

**Comment by BostonEnginerd** [comment]
Is this in the current alpha by any chance?
