### ISSUE TITLE
Add option to copy sender/recipient email addresses to clipboard

### ISSUE THREAD

**Issue by androiduser5** [k9mail/k-9#1070]
May you implement a copy funktion to the email adress? Currently there is only the possibillity to add the email to the contacts.

**Comment by Riverside14** [comment]
@cketti 
Hi,
I'm currently working on this enhancement, I've added the option to copy those addresses to clipboard via a long click and a little toast that mentions that the addresses has been copied to the clipboard, Is this suit you ?
Also, I have a little question, when there is multiple addresses to copy at the same time, for example, when there is different recipients.
For the moment, I only add a little space blank between the addresses. Do you want to add something better? (Comma, etc ...)

**Comment by Valodim** [comment]
just copying the one which the user actually long-clicked seems like the expected behavior there

**Comment by Riverside14** [comment]
Is this possible?
I'm working in the class view.MessageHeader, i create a method just like onClick()  (add the sender to contacts) 
so I just have the choice between the area "From", "To" & "cc".
Is this possible to subdivide these area for each addresses inside?

Thanks for your help

**Comment by Valodim** [comment]
I just realized I was thinking about the wrong dialogue. Sorry, never mind.

**Comment by Riverside14** [comment]
No problem, i will wait others answers ;)
