### ISSUE TITLE
Folder Poll Frequency "Never" still polls regularly

### ISSUE THREAD

**Issue by GeraldPfeifer** [k9mail/k-9#1071]
I have one account/mailbox that I only want to read occasionally in K-9 Mail, 
so I set Folder Poll Freqency (under the options for Fetching) to "Never".
 
However, it appears this account/mailbox is still checked regularly.

This is with version 5.007 on a Samsung Galaxy S4 mini.

**Comment by cketti** [comment]
Does it only appear like the account/folder is checked or are new messages actually downloaded?

**Comment by GeraldPfeifer** [comment]
New messages are actually downloaded.

In fact, new messages are downloaded in "real-time".  It appears as if instead of never polling, with this setting it is constantly polling.

**Comment by cketti** [comment]
Then Push is enabled for that folder. Make sure the Push class for that folder is set to "None" or disable Push for the account.
If you have additional questions please use the [mailing list](http://groups.google.com/group/k-9-mail).
