### ISSUE TITLE
Incompatibility with Android System WebView 49

### ISSUE THREAD

**Issue by Wandrer** [k9mail/k-9#1072]
With Android System WebView 49.0.2623.34 present in the Android System, K-9 does not show the content of mails anymore, only a blank page.

I tested this on the Samsung G900F and the Sony SGP612.

Android System WebView 48.0.2564.99 does work fine on both devices.

I'm using K-9 version 5.007.

More Information on this:
http://www.android-hilfe.de/thema/k-9-zeigt-seit-ein-paar-tagen-keine-nachrichteninhalte-mehr-an.751132/
https://code.google.com/p/chromium/issues/detail?id=552398&au_id=1498911 (post #45)

**Comment by squilter** [comment]
Same here on moto x

**Comment by arteitle** [comment]
I had the same problem with WebView 49.0.2623.34 on an LG G3 with Marshmallow. Uninstalling WebView updates back to 45.0.2454.95 fixed it.

**Comment by arteitle** [comment]
I forgot to mention that I'm using K-9 Mail 5.107.

**Comment by cketti** [comment]
Please make sure to report this issue to Google. The linked bug report is from November 2015 and is not about whatever they changed in WebView 49.0.2623.34.

**Comment by cketti** [comment]
Can you all please test if [5.008-RC1](https://github.com/k9mail/k-9/releases/tag/5.008-RC1) fixes this issue for you?

**Comment by bet** [comment]
Both reverting Webview to 48.*, and better, using k9 5.008-RC1, restored the message bodies, thanks. To clarified, I reverted Webview and that worked, and then I let play store update Webview to 49.* and then updated to the new k9 and it still worked.

**Comment by squilter** [comment]
Works

**Comment by Wandrer** [comment]
Works but Avast reports a cloud virus. I already reported back as a false alert.

**Comment by arteitle** [comment]
It works for me too.
