### ISSUE TITLE
No notifications after changing email server

### ISSUE THREAD

**Issue by crashmeplease** [k9mail/k-9#1073]
I don't receive notifications of new email after I changed my email server address of an existing account. I have used k9 well over a year with the old server without any issues.

I have tried turning off notifications and then back on again and this didn't help.

I don't really want to delete the account from k9 and set it up again as I have a lot of email that would need syncing up.

New emails appear in my inbox, there doesn't appear to be any issue when syncing email, it doesn't feel like an issue with my new email server.

**Comment by cketti** [comment]
Deleting the account and setting it up again is your only option for now. You can export the account settings and then import the settings for that account after deleting it. See [Settings Import & Export](https://github.com/k9mail/k-9/wiki/Manual-Settings-ImportExport).

I created issue #1074 to fix the underlying problem. But it's not a high priority issue.

**Comment by crashmeplease** [comment]
That worked and the re-sync wasn't too bad after all, plus I had forgot about export/import of setting, that helped a lot thanks.
