### ISSUE TITLE
Unable to access courier imap ssl server on Android 6

### ISSUE THREAD

**Issue by TheGorbag** [k9mail/k-9#1075]
I cannot fetch mail from my courier imap ssl server from k9mail on Android 6. it worked on Android 5.1. I have made no changes to the settings, which are:

Security: SSL/TLS
Port: 993
Authentication: Normal password
Auto-detect IMAP namespace

The server has 

This happened on both my Nexus 7 tablet and my Moto X play.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
