### ISSUE TITLE
K9 fails when using WiFi

### ISSUE THREAD

**Issue by Test-user12** [k9mail/k-9#1083]
The latest version 5.008 has a problem with sending and receiving emails when using WiFi.  Everything works correctly when I shut off WiFi and only use data.  Version 5.007 did not have that problem.  Please investigate and resolve this problem.  Thank you.

**Comment by cketti** [comment]
5.008 is a one line fix of a WebView issue and most definitely didn't cause this.

Please use the [mailing list](http://groups.google.com/group/k-9-mail) to ask for help with your issue.
