### ISSUE TITLE
attempting to open a .ics attachment , crashes the resident calendar.

### ISSUE THREAD

**Issue by BK-NY** [k9mail/k-9#1084]
### Expected behaviour
From an email in K9, Click open for the .ics attachment.  
(the .ics is from my office, where they generate the calendar events from an outlook office calendar).
I would than choose  "Calendar" , and than I would have have a window in the resident default calendar app with the calendar event and can work with the calendar event and save it to a particular calendar account and add alarms and such. This was working correctly for about a year.

### Actual behaviour
Now, after 1 or two K9 updates (started being a problem a few months ago IIRC)... was hoping the latest update would fix the problem, but it did not.

After clicking on "Calendar", I get an OS window that says " Unfortunately, Calendar has stopped."

### Steps to reproduce
1. Send an outlook generated .ics to an email account in K9.
2. In the email, Click "Show attachments" , than "more" if need be, than click "Open".
3. Select "Calendar".
At this point I get the OS message window " Unfortunately, Calendar has stopped. "
I am using the Calendar that comes with my phone / OS, not a 3rd party downloaded calendar.

### Environment
K-9 Mail version: 5.008

Android version: 
Galaxy 6 model SM-G920V
OS: 5.1.1
kernel 3.10.61

Account type (IMAP, POP3, WebDAV/Exchange):  POP3

**Comment by cketti** [comment]
That's most likely a problem with your calendar app, not K-9 Mail.
