### ISSUE TITLE
exported settings from v5.107 (alpha) cannot be imported into v5.007 ff

### ISSUE THREAD

**Issue by hakaz** [k9mail/k-9#1085]
Trying to import exported settings from v5.107 (alpha) into v5.007 leads to "Import failed | Failed to import any settings from primary:com.fsck.k9/settings.k9s". Reinstalling v5.107 imports fine. Any changes in export/import format?

**Comment by cketti** [comment]
The format didn't change, but the contents. I created issue #1092 to allow importing settings from newer K-9 Mail versions.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for questions or support requests.

**Comment by hakaz** [comment]
Hi,

Thx for clarification, relying on your answer I downgraded the version number in the .k9s file and imported it successfully.

Cheers, hakaz aka Harald Kastner

BTW: Why did you consider my issue a request for the mailing list rather than an issue?

﻿--
Integrale Praxis | haiden + kastner GnbR

Ing. Harald Kastner
Unternehmensberater, Dipl. Erwachsenenbildner,
Integraler Coach, Geschäftsführender Gesellschafter

A: Pappenheimgasse 39, 1200 Wien, Austria
T: +43 (0)1 334 47 08
F: +43 (0)1 334 47 17
M: +43 (0)676 391 42 00
E: harald.kastner@integralepraxis.at
W: www.integralepraxis.at - blog.integralepraxis.at
I: www.integralepraxis.at/impressum.html


-------- Original Message --------
