### ISSUE TITLE
Option to warn on no subject 

### ISSUE THREAD

**Issue by kenyoni** [k9mail/k-9#1089]
It would be nice to have an option which would pop up a warning if message being sent has no subject.  

While there may be occasions where no subject is what you want,  it is generally considered bad form.  I rarely do it,  but occasionally happens when in a rush to get the email out before I get to my stop when on public transit.  Kinda embarrassing.

**Comment by MaximeMenotti** [comment]
Hi, 
I found a solution for this issue. The last thing that I have to fix is the text message to show on the warning dialog. 

Should I add a ressource into the strings.xml files ? Should I add lines for all the langages ? 
Thanks.

**Comment by Valodim** [comment]
This seems like a case for a "warn and cancel on first click, send anyways on repeat" ui pattern.

**Comment by cketti** [comment]
I'm not yet convinced this approach delivers the best user experience. It sounds nicer than the traditional 'cancel/send anyway' dialog, but still a bit weird.

@jancborchardt Any thoughts on this?
