### ISSUE TITLE
add a per folder option to force which correspondent is displayed in message list

### ISSUE THREAD

**Issue by CantConAnHonestJohn** [k9mail/k-9#1093]
Proposal for this option:
- auto [default]
- sender
- recipient(s) (TO)
- both

Explanation:
I have a custom sent folder configured which i use with different sender addresses and it's quite annoying that the sender is displayed in the sent folder's message list instead of the recipient.

**Comment by cketti** [comment]
If the sender is one of the identities configured for this account the recipient will be displayed instead of the sender. If feel like that's enough for 99% of all users and don't see the benefit of adding yet another setting.
