### ISSUE TITLE
Starred messages filter / feature

### ISSUE THREAD

**Issue by metastork** [k9mail/k-9#1095]
Now this is not technically a bug, but more of a UX issue / feature.

The Global Settings / Show Stars option works as it should, in that it disables or enables 'stars' or 'flags' in the message list pane.

However, it also enables / disables the star icon in the folder list pane, which filters the messages to only show starred messages.

My problem with that functionality is the following: I like being able to see dozens of messages at once in the message list pane, by decreasing font-size and putting sender and subject on one line (and disabling message preview lines to 0). However, if stars are enabled, they always take up 2 lines, irrespective of the other settings.

Either of the following two fixes for this problem would be amazing to me:
1. Always retain the option in the folder list to view only starred items, or
2. Create 2 separate options to allow control of 'view stars' in list, folder view, or both,
3. Reduce the size of the star icon in the message list view so it doesn't take up so much space if message_preview = 0, 

I know it's a small niggle that might not bother many others, but I love k-9 and this would make it even better!

Great work all around in any case, A class email app!

**Comment by cketti** [comment]
This will most likely change in the future anyway. My current plan is to remove the number of starred messages from the folder list. In turn filtering messages in the message list will become easier.

**Comment by desigit** [comment]
Awesome, thanks cketti, that would be great!

**Comment by cketti** [comment]
Continued as #4330
