### ISSUE TITLE
Possible to do a progress bar for attachment downloads?

### ISSUE THREAD

**Issue by desigit** [k9mail/k-9#1096]
I'm not sure if it's technically possible due to IMAP specifications, etc, but is it possible to create a download progress bar in % or so, to enable users to see how far along a large attachment download has come?

Occasionally, when on patchy data connections, you kind of have to guess whether a large attachment is still downloading, or if it's maybe got stuck, since there's no indication if the download is continuing or has stalled.

**Comment by cketti** [comment]
Same as #999
