### ISSUE TITLE
How To Donate?

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#1099]
Hi

K9 is the most awesome email client on Android! Do you seek donations?

thx!

**Comment by polluks** [comment]
"If you feel like contributing financially, please make a donation to the local SPCA, or buy Kaiten Mail from the market."

**Comment by cketti** [comment]
We're currently not looking for financial contributions. And since Kaiten Mail is no longer actively being developed I changed the text quoted by @polluks to this:

> If you feel like contributing financially, please make a donation to [F-Droid](https://f-droid.org/about/), the repository of Free and Open Source Software (FOSS) for the Android platform.

It can be found here: https://github.com/k9mail/k-9/wiki

**Comment by edrush** [comment]
+1
