### ISSUE TITLE
Feature Request Tasker integration to fetch email

### ISSUE THREAD

**Issue by gitmatt19** [k9mail/k-9#1101]
I would like to see a feature in K-9 to allow me to use "Tasker" to check a specific account email.

Scenario is : 
Go to work attach to work wifi, Tasker recognizes we are at work based on Access point and starts periodically checking for email for just the work email account.

Same scenario at home. Let Tasker check for home email while at home.

This is allows better security as it only is trying to check my accounts in the appropriate networks and not just any ole wifi I connect too.

Also this is a great app, thanks for all the work that has been put into it.

**Comment by cketti** [comment]
If someone has concrete plans to write such a (Tasker) plugin we can talk about adding the necessary interface to K-9 Mail. Until then there are much more important issues to be taken care of.
