### ISSUE TITLE
K-9 not secure enough for gmail 

### ISSUE THREAD

**Issue by mthowell380** [k9mail/k-9#1105]
When I try to use my G-mail with K-9 Gmail rejects it for not being a secure app and would leave my gmail vulnerable 

https://gyazo.com/371aa633a7efa4be4f705cd61a5c1dd2
K-9 Mail version: 5.008

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange): gmail

**Comment by cketti** [comment]
See #655
