### ISSUE TITLE
Attachment lost, body looks strange

### ISSUE THREAD

**Issue by polluks** [k9mail/k-9#1107]
### Expected behaviour
See a PDF.

### Actual behaviour
No attachment, incomplete quoted-printable decoding (in the body are few "=20").
Google's mailer works with this mail!

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.008?
Android version:
4?
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Can you provide the message source of such an email?

**Comment by polluks** [comment]
Well, it's not my phone.
I was looking for the header but neither "User-Agent" nor "X-Mailer" were shown.

**Comment by cketti** [comment]
Well, then we just assume it's a malformed message.
Even if we wanted to, without a message to reproduce this issue there's no way to create a workaround.
