### ISSUE TITLE
It doesn´t recognize the folders created with thunderbird in my email

### ISSUE THREAD

**Issue by logos88** [k9mail/k-9#1113]
I have my gmail account organized with different folders manually created in thunderbird. For example, a 2015 folder, with home, travels, ... folders inside it. I move a lot of emails there, and they appear in the gmail.com webpage as labels. 

### Actual behaviour
This folders doesn´t appear in K9 mail, the same as the emails that are inside them are missing even with the search option. 

### Expected behaviour
The folders should appear with the emails that are inside them when you explore the folders, like drafts or sent, and the emails should be reachable when you search them with the search option.

### Environment
K-9 Mail version: 5.008 

Android version: 6.0.1 Cyanogenmod

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Go to the folder list screen and select "Refresh folder list" from the menu.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
