### ISSUE TITLE
Unified & All Messages inboxes not updating

### ISSUE THREAD

**Issue by carpe-dm** [k9mail/k-9#1114]
### Expected behaviour

When I tap Unified Inbox or All messages, I expect to see recent emails, updating dynamically
### Actual behaviour

As of Feb 19th, around 6 PM PST, I stopped seeing new emails in either Unified Inbox or All messages, and have to go to my individual mailboxes to see new mail. I have 4 mailboxes.
### Steps to reproduce
1. Start K-9 in Unified Inbox
2. Observe that no new emails have appeared, despite their presence in individual mailboxes

I have restarted the app several times. I have restarted the phone several times. I have not uninstalled the app, nor done a hard restart and restore from backup. I'd like to avoid both if possible. I've also deleted emails from all accounts.
### Environment

K-9 Mail version:5.008

Android version: 5.1 on Moto X (2013) system 222.26.7.ghost_verizon.Verizon.en.US

Account type (IMAP, POP3, WebDAV/Exchange): all IMAP

**Comment by carpe-dm** [comment]
![screenshot_2016-02-22-17-27-03](https://cloud.githubusercontent.com/assets/17410931/13238764/356b6a5e-d98a-11e5-86f6-db4ea6182425.png)
![screenshot_2016-02-22-17-27-00](https://cloud.githubusercontent.com/assets/17410931/13238765/357182c2-d98a-11e5-8dd2-d30323f5f731.png)
![screenshot_2016-02-22-17-26-54](https://cloud.githubusercontent.com/assets/17410931/13238766/3572592c-d98a-11e5-9b2c-aff9868fc96a.png)
![screenshot_2016-02-22-17-26-47](https://cloud.githubusercontent.com/assets/17410931/13238767/35780fac-d98a-11e5-9db4-e7409fb033ef.png)


Added screenshots to show contents of two mailboxes plus the unified mailbox.

**Comment by carpe-dm** [comment]
Further update: I backed up, uninstalled, reinstalled, and restored. No improvement. I do occasionally get one or two new emails to show up in Unified, but can't see a pattern as to which ones do.

**Comment by cketti** [comment]
Make sure the Inbox folders have the "Unified" flag enabled in folder settings. See https://github.com/k9mail/k-9/wiki/Manual-FolderSettings

**Comment by carpe-dm** [comment]
Thanks, I'll check, but I've been using the app for something like 4 years
and didn't change anything...

**Comment by carpe-dm** [comment]
I confirmed that the folders have the appropriate box checked. I cleared, exited, rechecked. No change. 

Dave 

On February 23, 2016 12:21:31 PM PST, cketti <notifications@github.com> wrote:
>Make sure the Inbox folders have the "Unified" flag enabled in folder
>settings. See https://github.com/k9mail/k-9/wiki/Manual-FolderSettings
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1114#issuecomment-187886302

-- 
sent from my phone

**Comment by carpe-dm** [comment]
Any ideas what's going on? At this point, the app is reality annoying to use. It's unfortunate because I really like it otherwise.

**Comment by llamathumper** [comment]
I confirm I have the same issue. Will try to post K9 version plus type of phone soon.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with a recent K-9 Mail version.
