### ISSUE TITLE
Crash on tabbing "empty trash"

### ISSUE THREAD

**Issue by sedrubal** [k9mail/k-9#1115]
### Expected behaviour

On tabbing "empty trash" the app should empty the trash in background and the ui should work fluidly.
### Actual behaviour

The app freezes completely and one have to stop it and restart it
### Steps to reproduce
1. Delete messages
2. Tab "empty trash"
### Environment
- K-9 Mail version: 5.008 (but I can't remember a version of k9mail which didn't had this issue)
- Android version: Omnirom 6.0.1
- Account type: 3 IMAP accounts

**Comment by cketti** [comment]
Does the app freeze or crash? Can you provide a debug log? https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by sedrubal** [comment]
The app freezes and sometimes Android asks, if it should stop k9 mail or if I want to wait. Sometimes it only stucks for some seconds.

A debug log is here: https://gist.github.com/sedrubal/fe97447b49e41c46ca6f

I hope this helps...

**Comment by sedrubal** [comment]
After restarting the App, the trash folder is empty btw. ;)

**Comment by cketti** [comment]
I believe this is no longer an issue.
