### ISSUE TITLE
Display *one* notification while refreshing

### ISSUE THREAD

**Issue by sedrubal** [k9mail/k-9#1116]
### Steps to reproduce
1. IMAP account with multiple folders
2. Pull to refresh messages in "unified inbox" or elsewhere
### Actual behaviour

The android notification bar escalates, because there appear notifications and the they dissapear while others appear...
### Expected behaviour

One notification should appear with a progress bar and the text should be adapted to display the folder which is currently updating if possible.
### Environment
- K-9 Mail version: 5.008 (but this issue belongs to every version I used in the recent years)
- Android version: Omnirom 6.0.1
- Account type: 3*IMAP

**Comment by IzzySoft** [comment]
May I extend this requesting to *optionally* disable those "ongoing" refresh notifications altogether (from the *Settings › Notifications* screen)?

### Actual behavior
* For each mail check (and separately for each account), there's a separate notification shown
* Smart watches sync each of them ***and keep them until manually dismissed***

### Wanted behavior (in this context)
* No "ongoing mail-check* notifications happen, so none are synced to be dismissed manually, while …
* New-mail notifications still occur and get synced to be brought to my attention

### Result
So basically, with a new option introduced, the user could decide between …

* separate "new-mail-check" notifications for each account
* one combined "new-mail-check" notification "per check interval"
* no "new-mail-check" notifications at all

This would help the case of @sedrubal as well as mine, while at the same time not affecting those who want it the way it currently is. For the latter (sometimes also called "backward compatibility"), the default could be set to reflect the current behavior (which btw can be useful for debugging as well, e.g. to see whether k-9 really checks a certain mailbox).

**Comment by sedrubal** [comment]
Ah OK :+1:

But I'd break backward compatibility and completely remove the single notifications:

 - one should use adb logcat for debugging
 - it's bad to have complicated settings (a single checkbox (show / hide notifications on refreshing mails) is much better for UX)
 - I think there is really no advantage on having multiple notifications (it's completely ugly and makes android notifications unusable while k9 mail is refreshing)

**Comment by IzzySoft** [comment]
I'm fine with the "refreshing" notifications gone for good as well. I just don't want to "rule others" by my opinion – hence my vote for options. Take a look into *Settings › Notifications*, @sedrubal – it's not really "crowded" in there. But as said, I'm fine with both variants (options or gone-for-good) as well as with using Logcat, as long as I can get rid of the "refreshing" notifications somehow :innocent:

**Comment by cketti** [comment]
@IzzySoft This is a separate issue. Also, you can already disable sync notifications under 'Account settings > Notifications > Sync notifications'.
If your smart watch doesn't remove notifications when they're canceled on the device this is most likely a bug. But I doubt it's one in K-9 Mail.

**Comment by IzzySoft** [comment]
@cketti I don't want to disable *all* k-9 notifications (that I could do in BTNotifier, the app which is responsible for my watch – it's not a Wear watch, but a cheap MTK most likely running Nucleus). So consider the smartwatch part a different thing (I agree with you it's a bit buggy, especially concerning notifications) and let's say I'm simply annoyed with the notification bar constantly "blinking" even though there is no news ;)

**Comment by cketti** [comment]
@IzzySoft: "Sync notifications" are the notifications that are displayed during synchronization. "New mail notifications" are the ones that notify of new mails.

**Comment by IzzySoft** [comment]
@cketti Ah ***there*** it is! I was looking for it in the global settings. Thanks a million! Just went through all my accounts and flipped the switch – consider my part solved so far (and maybe consider having that setting in globals as well – optionally with a warning it will overwrite this for all accounts and can be changed there per-account again).

**Comment by webash** [comment]
As there was another issue discussed in this thread, I just wanna make sure the original issue is still being considered for fixing?

**Comment by cketti** [comment]
This was fixed by #5675.
