### ISSUE TITLE
feature request: mutt style alias file

### ISSUE THREAD

**Issue by haxwithaxe** [k9mail/k-9#1122]
An alias file (not necessarily populated by k9) similar to that used by mutt would be referenced when autocompleting email addresses.

this would be a nice stepping stone to the smarter autocomplete feature requests.

love k9! gave it 5 stars on the play store.

**Comment by Valodim** [comment]
Android a "contacts provider" for managing e-mail addresses, which is a central mechanism that can be populated and queried from all apps. Using a text file of aliases would be a very not-Android thing to do here.

**Comment by haxwithaxe** [comment]
ah ok. i was hoping to avoid mucking with my google contacts. if there is a more standard way to do this then this should be closed.
