### ISSUE TITLE
Feature Request: Add an "Exit"/close/kill app', function.  For battery current drain, et cetera.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [k9mail/k-9#1123]
Issues, #1066 & #1086 & possibly others, point to a high battery drain, when in poor signal, no signal, or even in "Airplane Mode" with the radios off. 

Until a manual, or automatic method is given, to stop all sync, or "refresh" of connections, in poor/no connectivity; there should be a function to down K-9.

It might be otherwise useful, and is a good diagnostic procedure.

It would be far more convenient and quick, from within the app', and conducive to relaunching K-9, when conditions permit.

**Comment by cketti** [comment]
No. See #1078
