### ISSUE TITLE
Mails not synching

### ISSUE THREAD

**Issue by stuhlpfarrer** [k9mail/k-9#1124]
### Expected behaviour
When new mails arrive in the (IMAP) inbox, they should show up in K-9 Mail.

### Actual behaviour
New Mails do not appear. In this example there is a total of 26 mails in the inbox. Which is correctly detected by K-9 Mail. 3 of the messages are already present (and visible) in the app. However the app does not proceed to fetch the remaining 23 mails.

Debug log:

D/k9      (30364): Got untagged EXISTS with value 26 for snip:INBOX/MessagingController/conn1121390160
V/k9      (30364): SYNC: Remote message count for folder INBOX is 26
V/k9      (30364): SYNC: About to get messages 1 through 26 for folder INBOX
V/k9      (30364): conn1121390160>>> 28 UID SEARCH 1:26 NOT DELETED

V/k9      (30364): conn1121390160<<<#null# [SEARCH, 1, 3968, 5518, 5595, 5938, 5939, 5940, 5941, 5942, 5943, 5944, 5945, 5946, 5947, 5948, 5949, 5950, 5951, 5952, 5953, 5954, 5955, 5956, 5957, 5958, 5959]
V/k9      (30364): conn1121390160<<<#28# [OK, SEARCH done.]
V/k9      (30364): SYNC: Got 26 messages for folder INBOX
V/k9      (30364): LockableDatabase: Transaction ended, took 0ms / com.fsck.k9.mail.store.LocalStore$LocalFolder.destroyMessages(LocalStore.java:2442)
V/k9      (30364): Message with uid 5518 is present in the local store
V/k9      (30364): Message with uid 3968 is present in the local store
V/k9      (30364): Message with uid 1 is present in the local store
D/k9      (30364): SYNC: Have 0 unsynced messages
D/k9      (30364): SYNC: Have 0 large messages and 0 small messages out of 0 unsynced messages
D/k9      (30364): SYNC: Fetching small messages for folder INBOX
D/k9      (30364): SYNC: Done fetching small messages for folder INBOX
D/k9      (30364): SYNC: Fetching large messages for folder INBOX
D/k9      (30364): SYNC: Done fetching large messages for folder INBOX
D/k9      (30364): SYNC: About to sync flags for 3 remote messages for folder INBOX
V/k9      (30364): conn1121390160>>> 29 UID FETCH 5518,3968,1 (UID FLAGS)

V/k9      (30364): conn1121390160<<<#null# [3, FETCH, [UID, 5518, FLAGS, [\Seen]]]
V/k9      (30364): Stored uid '5518' for msgSeq 3 into map 
V/k9      (30364): conn1121390160<<<#null# [2, FETCH, [UID, 3968, FLAGS, [\Seen]]]
V/k9      (30364): Stored uid '3968' for msgSeq 2 into map 
V/k9      (30364): conn1121390160<<<#null# [1, FETCH, [UID, 1, FLAGS, [\Seen]]]
V/k9      (30364): Stored uid '1' for msgSeq 1 into map 
V/k9      (30364): conn1121390160<<<#29# [OK, FETCH completed.]
D/k9      (30364): SYNC: Synced remote messages for folder INBOX, 0 new messages

### Steps to reproduce
1. Receive new mails
2. Delete some mails
3. Try to receive more new mails

### Environment
K-9 Mail version: 5.008

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Sadly, the log doesn't contain enough information to figure out why that is. You can most likely fix this by going to the folder list, long-pressing the folder, then selecting "Clear local messages". Afterwards synchronize the folder to redownload the messages.

**Comment by stuhlpfarrer** [comment]
That does indeed fix it. Thanks for the lightning speed reply!
There is not that much prior to what I posted in the log though.

This is the rest:
V/k9      (30364): conn1121390160<<<#null# [FLAGS, [\Draft, \Answered, \Flagged, \Deleted, \Seen, \Recent]]
V/k9      (30364): conn1121390160<<<#null# [OK, [PERMANENTFLAGS, [\Draft, \Answered, \Flagged, \Deleted, \Seen]], Limited]
V/k9      (30364): conn1121390160<<<#null# [26, EXISTS]
V/k9      (30364): conn1121390160<<<#null# [0, RECENT]
V/k9      (30364): conn1121390160<<<#null# [OK, [UIDVALIDITY, 1438800268], Ok]
V/k9      (30364): conn1121390160<<<#null# [OK, [MYRIGHTS, acdilrsw], ACL]
V/k9      (30364): conn1121390160<<<#27# [OK, [READ-WRITE], Ok]

Alltough now that I visited the folder list (which I did not think of before) I also found this: 

javax.net.ssl.SSLException: Read error: ssl=0x7906d920: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:690)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:841)

But this appeared only once - and I tested the issue couple of times (represented in the logs multiple times, similar to the sample I posted).

**Comment by cketti** [comment]
Sorry, I meant our logging is not good enough to catch what went wrong in this case. I created issue #1131 to address that.
