### ISSUE TITLE
all inbox email suddenly disappeared on multiple devices

### ISSUE THREAD

**Issue by cpapost** [k9mail/k-9#1125]
### Expected behaviour
Tell us what should happen
Emails should remain on device until deleted

### Actual behaviour
Tell us what happens instead
Emails suddenly disappear

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.008

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): POP 3

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
