### ISSUE TITLE
does not save attachments to external sd card on sony z5

### ISSUE THREAD

**Issue by egnna** [k9mail/k-9#1129]
### Expected behaviour
should save attachment to storage/sdcard1/mail folder
### Actual behaviour
unable to save attacment message appears

### Steps to reproduce
1. settings / miscellaneous / save attachements to 
2. "storage/sdcard1/mail" 
3. open mail click save on attachment. error will appear

"storage/sdcard0/mail"  works

### Environment
K-9 Mail version: 5.008

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
all

**Comment by cketti** [comment]
You're most likely missing a "/" at the beginning.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by egnna** [comment]
no i don't
