### ISSUE TITLE
IOException while adding Office365 Exchange Account

### ISSUE THREAD

**Issue by DistantParadox** [k9mail/k-9#1134]
### Expected behaviour
When setting up an account for Exchange for an Office365 account, the setup should complete and add the account.

### Actual behaviour
Instead, after tapping "Next" at the "Incoming server settings" page, a message pops up that says "Cannot connect to server. (IOException)".

### Steps to reproduce
Note:  requires a Microsoft Office365 email account; the account that caused this bug in K-9 did not in the default Android email application.
1.  Manual setup when setting up a new email account
2.  Select Exchange (WebDAV)
3. Fill in details, as per the instructions [here](http://help.ic.utoronto.ca/content/85/1931/en/utmail-setup-for-android-4x.html).  In this case, I entered the exchange server to be outlook.office364.com.  It appears that there is no Domain\Username field in K-9, as there is in the tutorial, which may be of use(?)

### Environment
K-9 Mail version: 5.008

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): Exchange

**Comment by cketti** [comment]
I'm pretty sure Office365 doesn't support WebDAV. Try connecting via IMAP.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
