### ISSUE TITLE
Support for ICS attachments [enhancement]

### ISSUE THREAD

**Issue by xpavp03** [k9mail/k-9#1142]
Could you please add a support for creating calendar events from an ICS attachment?
I can currently Open or Save an attached ICS file but I cannot create an event from it.

Google Calendar has this feature so in my particular case, I can work around the lacking K9 functionality by opening the attachment in K9, choosing Google Calendar and creating the event from there.

Thanks

**Comment by philipwhiuk** [comment]
Surely the onus is on the event application to support opening ICS files here - it sounds like your "work around" is the expected behaviour to me.

**Comment by xpavp03** [comment]
Ah! Of course, you're right. I wanted to post this to my calendar's issue tracker (Business Calendar 2) and I got it all mixed up. I feel dumb. Sorry for wasting your time.

**Comment by philipwhiuk** [comment]
No worries :)
