### ISSUE TITLE
Uninstalling OpenPGP app should revert ComposeCryptoStatus to uninitialised

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1153]
### Expected behaviour
When sending email from an account that previously had a cryptography provider, the email should be sent successfully.

### Actual behaviour
"Cannot connect to crypto provider, check your settings or click crypto icon to retry!"

### Steps to reproduce
1. Install K-9
2. Install OpenPGP app
3. Add OpenPGP to an account
4. Uninstall OpenPGP
5. Try to send an email

### Environment
K-9 Mail version:

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
NB: This would be fine, if you could remove the uninstalled cryptography provider - but you can't - the setting is greyed out and it says 'No OpenPGP app installed'.

**Comment by Valodim** [comment]
You're right. Deselecting the crypto provider is what I had in mind with "Check your settings", but if that is indeed not possible with an uninstalled crypto provider that should be fixed.
