### ISSUE TITLE
No Notification any more

### ISSUE THREAD

**Issue by captain-intrepid** [k9mail/k-9#1154]
Hello,

I am using K-9 for a long time.

Since the update to 5.007 there are no notification anymore for new messages. No sound, no vibrations, no LED, no icon at the status bar. Sounds like mp3 or systemsounds tested no reaction. Even when I create a new account. I am using K - 9 with five different accounts IMAP+POP, the widgets on the screen present the right quantity of new mails. I was detecting the notification problem befor x-mas 2015 and I was waiting for the next update but not affect. I am missing the sounds very much.

Rest of the program seems to run perfectly.

Somewhere I read that deleting an account and recreate didn´t work.

I hesitate to delete the complete K-9 app. Do I have to step back to a version of 4.8xx? is it even possible?

### Environment
I am using Samsung Galaxy Note 2 (N-7100),
Android 4.1.2 not rooted,
K-9 (5.007) german language (actually updated 5.008)
Notifications 24/7

Please help.
vy73de Captain-intrepid

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
