### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Fsmart** [k9mail/k-9#1157]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.go to inbox
2.click "load up to 25 more＂   
3.close network
4.wait a minute
5.open network
6.click "load up to 25 more" No response

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Please can you fill in some more details.
