### ISSUE TITLE
Add button "Get it on F-Droid" in README.md

### ISSUE THREAD

**Issue by PanderMusubi** [k9mail/k-9#1159]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README.md file with the appropriate link to the page of your app on F-Droid. Perhaps add this button also in files of https://github.com/k9mail/k9mail.github.io

**Comment by philipwhiuk** [comment]
There's a PR k9mail/k9mail.github.io#2 on K9Mail indicating it's been removed from F-Droid. Not sure if it's still the case.

**Comment by PanderMusubi** [comment]
Nop, it is up and running. I have installed it this year from F-Droid, is maintained and works fine.

**Comment by cketti** [comment]
The README already contains a text link. I don't like the idea of adding image buttons for every app store.

I'd be fine with adding image buttons to a website. But what we currently have is both outdated and experimental.

**Comment by PanderMusubi** [comment]
I understand. However, you have already three images in your README.md and it is very common to have a "Get it on ..." button. Especially, if this repository on GitHub is also the main website of an app.

As a reference, see also:
* https://github.com/murraycu/android-galaxyzoo and https://github.com/murraycu/android-galaxyzoo/pull/29
* https://github.com/abarisain/dmix and https://github.com/abarisain/dmix/pull/804
* https://github.com/microg/android_packages_apps_UnifiedNlp and https://github.com/microg/android_packages_apps_UnifiedNlp/pull/73
