### ISSUE TITLE
Improve layout when both encryption & picture download elements are present

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1165]
We should adjust the layout when both are present so that the encryption and signing bits are next to the show pictures button instead of below it. This would make better use of the screen space.

![image](https://cloud.githubusercontent.com/assets/1316415/13631754/38004d4c-e5de-11e5-985e-8e96aa4a6bb6.png)

Device make: Huawei
Device model: Nexus 6P
Android version: 6.0.1
K9-Mail version: master

**Comment by cketti** [comment]
That's not an easy problem. We need the horizontal screen space when the message is signed and/or encrypted to display PGP status information.
To be honest, I don't really want to fix this for the next stable version. And after that we're overhauling all of the UI anyway.

**Comment by Valodim** [comment]
I have a lot of time in my schedule to work on this. First things first though, we need to get a beta out and finish the compose dialog. Until then, fixing things like this on a symptomatic level is not a particularly good use of developer time. Closing this issue for now, I'll open one for discussion when I'm working on it.
