### ISSUE TITLE
Problems with RTL (Persian,Arabic and Hebrew)

### ISSUE THREAD

**Issue by tareefq** [k9mail/k-9#1166]
### Expected behaviour
The RTL texts should be aligned from right to left and take this direction (r to l)
### Actual behaviour
The RTL texts aligned from left to right

### Steps to reproduce
1. rtls text must aligned from right to left
2. the direction must sit to: rtl
3.

### Environment
K-9 Mail version:
5.008
Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Looking at Arabic and Hebrew, we're missing a translation for 'Refreshed', which might be why 'Refreshed <Arabic/Hebrew for time period>' is displayed LTR.

I believe Android uses the W3 guidelines as a base for controlling text flow. If the line starts with LTR characters it will be left aligned. If it starts with RTL characters it'll be right aligned.

If you look at the screenshot of my app in Hebrew below, you can see it looks like we are doing it as described.

![image](https://cloud.githubusercontent.com/assets/1316415/13658086/f14896f0-e66b-11e5-95aa-ffd9ce4091bc.png)

If there's text we aren't translating (and I've found a few of those recently) then we can address those on a case by case basis.

This isn't the case for the default folders though (or for Refreshed). They just don't have translations yet.

**Comment by tareefq** [comment]
> I believe Android uses the W3 guidelines as a base for controlling text flow. If the line starts with LTR characters it will be left aligned. If it starts with RTL characters it'll be right aligned.

oh!
that's what i am looking for

thanks

**Comment by philipwhiuk** [comment]
If you want to help with the translation that would still be awesome :)

**Comment by doronbehar** [comment]
Or perhaps use [Stringlate](https://github.com/LonamiWebs/Stringlate)
