### ISSUE TITLE
WebDAV SSL implementation is unintelligible

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1177]
### Expected behaviour

Proper validation of SSL certificates similarly to IMAP
### Actual behaviour

One of the two socket factories used disables hostname verification, essentially breaking SSL.

`mSchemeSocketFactory.setHostnameVerifier(org.apache.http.conn.ssl.SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);`

```
 * TODO: find out what's going on here and document it.
 * Using two socket factories looks suspicious.
```

This is terrible. Quoting the Javadoc:

>  The ALLOW_ALL HostnameVerifier essentially turns hostname verification off. This implementation is a no-op, and never throws the SSLException. 

The code was committed in : https://github.com/k9mail/k-9/commit/8f45d76\

I'm not sure why we stopped using the TrustedSocketFactory, which seems to verify certificates correctly. Possibly the use of ALLOW_ALL_HOSTNAME_VERIFIER was a mistake (the SSL libraries are terrible for making opaque code that subtly breaks - see:
- [The Most Dangerous Code In The World](http://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html)
### Steps to reproduce

Untested. I suspect: 
1. Create an WebDAV account
2. Point to a server with a bad certificate
3. No error thrown
### Environment

K-9 Mail version: master

Android version: N/A
Account type (IMAP, POP3, WebDAV/Exchange): WebDAV
### Mitigation factors

In previous versions WebDAV is broken. Specifically, due to #1143 it will fail to sync at all often.
### Intended resolution

**Short term:** Replace argument with STRICT_HOSTNAME_VERIFIER

This may cause current WebDAV usage to fail due a badly signed certificate that is never the less expected. 

**Long term:** To resolve this I intend to rip out the WebDAVSocketFactory and replace it with non-deprecated APIs, with tests for SSL errors, following best practice as outlined in: http://developer.android.com/training/articles/security-ssl.html

**Comment by cketti** [comment]
`WebDavSocketFactory` doesn't look like code I wrote. I probably copied it from somewhere. Sadly, I can't remember doing that and have no idea what my motivation was :(

**Comment by philipwhiuk** [comment]
It looks like you copied it from the TrustedManagerSocketFactory. I just can't see the reasoning behind using separate factories yet.

**Comment by philipwhiuk** [comment]
See PR #1182 for the resolution to this.

**Comment by cketti** [comment]
Obsolete because of #4251
