### ISSUE TITLE
Add support for installation on external storage

### ISSUE THREAD

**Issue by giot8** [k9mail/k-9#1187]
Have you considered setting android:installLocation="auto" in AndroidManifest.xml to allow installation on external storage?

According to the wiki (https://github.com/k9mail/k-9/wiki/Storage), the reason for not supporting installation on external storage is:

"Since Android 2.2, the system is able to install core application files on the external storage (usually a microSD card). Unfortunately, doing so makes the application unable to work when the external storage is shared, like when your device is USB-plugged. Furthermore, Android does not restart the application when the application is brought back (on USB unplug)."

But recent versions of Android don't unmount the external storage when the storage is shared, they use MTP.

**Comment by cketti** [comment]
From http://developer.android.com/guide/topics/data/install-location.html
> When your application is installed on the external storage:
> [...]
> The .apk file is saved on the external storage, but all private user data, databases, optimized .dex files, and extracted native code are saved on the internal device memory.

Given that the APK size is ~3 MB there's not much to gain by allowing installation on external storage. I couldn't find any documentation on how devices with MTP support behave and if newer Android versions are required to use it. Still, users could remove the SD card and cause issues.
So the "advantage" is far outweighed by the disadvantages.

If you want to move your messages database, which is what can get really large, to an SD card, see issue #863.

**Comment by giot8** [comment]
I should have mentioned that I am using Android 6.0, whose implementation of App2SD (adoptable storage) stores both the .apk and private data/databases/etc on the external storage.

From https://source.android.com/devices/storage/adoptable.html

> Android has always supported external storage accessories (such as SD cards), but these accessories were historically limited to simple file storage, due to their expected impermanence and the minimal data protection offered to traditional external storage. Android 6.0 introduces the ability to adopt external storage media to act like internal storage.
> 
> [...]
> 
> Apps can be placed on adopted storage media only when the developer has indicated support through the android:installLocation attribute. New installs of supported apps are automatically placed on the storage device with the most free space, and users can move supported apps between storage devices in the Settings app. Apps moved to adopted media are remembered while the media is ejected, and return when the media is reinserted.

Not setting installLocation to either auto or preferExternal prevents Android 6.0 users from taking advantage of adoptable storage. At the same time, Android 5.1 (or earlier) users would be minimally affected by the change, because:

1) Recent versions of Android use MTP. While not required, it is strongly recomended by Google. From https://static.googleusercontent.com/media/source.android.com/en//compatibility/4.4/android-4.4-cdd.pdf

> Device implementations MAY use USB mass storage, but SHOULD use Media Transfer Protocol.

In fact most if not all phones sold with 4.4 (or newer) preinstalled support MTP.

2) Users who remove the SD card expects the apps on the SD card to be unavailable while the SD card is removed, they wouldn't see the temporary unavaibility of k9mail as unexpected behaviour.

3) With installLocation set to auto, k9mail can still be kept on the internal storage if the user wants so
