### ISSUE TITLE
Problem has returned, please see issue 1130 for previous issue and log. New info below

### ISSUE THREAD

**Issue by golferguy** [k9mail/k-9#1193]
Expected behaviour

After I open and read an email, the status should remain unread and then sync with settings to poll every 15 minutes

Actual behaviour

After I open and read an email, the status changes to read
But once the imap sync starts the status changes back to unread after polling

Steps to reproduce

1.Launch K9 
2.View list of emails and read one or more by tapping to open fully
3.Exit K9
4. Check K9 later and the previous read emails show as unread

If I read the messages on the server via outlook client on PC, the K9 client shows them as read messages, properly from that point forward

Environment

K-9 Mail version: 5.008

Android version:
Marshmellow
LG G4

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP settings but Activesync is used on servers

Note: This occurred about a week ago.
I exported settings
Deleted K9 from phone
Downloaded new version from Play store
Imported settings
K9 functioned perfectly for about a week but problem returned today.

--------------------------------------------------------------------------------------------------------------------
Problem returned on March 18, 2016

I noted in the K9mail-errors folder there are a number of emails showing with "IOException: readStringUntil(): end of stream reached"   

And 
UnknownHostException: Unable to "resolve host "imap-mail.outlook.com":Unknown error"

**Comment by philipwhiuk** [comment]
Closing and merging into original... Please don't create a second issue for the same problem.
