### ISSUE TITLE
Request: Save passwords encrypted using Android KeyStore

### ISSUE THREAD

**Issue by jonas-lundqvist** [k9mail/k-9#1200]
Currently all IMAP/POP3/SMTP/WebDAV credentials are stored in the preferences as plain text. I would like to propose to encrypt the password(s) using the Android KeyStore API for devices with Android 4.3 (API level 18) and above.

One "drawback" is of course that it will not be possible to include the passwords when importing/exporting the settings.

http://developer.android.com/training/articles/keystore.html

**Comment by jonas-lundqvist** [comment]
Another drawback (this time without quotes since I see this as a real drawback):
The device needs to be unlocked to be able decrypt the password. So if a user starts his/her phone without unlocking it no emails will be received. Only when it is unlocked K-9 will be able to decrypt the password. I have not digged through the code fully, but from this point K-9 hopefully can hold the password in memory.

**Comment by philipwhiuk** [comment]
I don't think that behaviour is necessarily something that should prevent us using the keystore. Personally I see it as a good thing that a non-unlocked device won't start using the user's credentials to perform mail retrieval. If it were related to back-up the argument is more complex (theft vs. interception of backups).

**Comment by gdt** [comment]
I think it's a feature to omit passwords in settings.   A settings file without a password isn't that sensitive, and the password is easy to reenter.   I also agree that not using the credentials on boot until unlock is makes sense.   If k-9 could only fetch mail when the phone was unlocked later, that would be a bug.

**Comment by cketti** [comment]
We need direct access to passwords to be able to support all authentication schemes. Using KeyStore in a meaningful way is not an option for K-9 Mail.

**Comment by Valodim** [comment]
not entirely true: it's possible to generate a symmetric key in the android keystore since Android M, which if hardware-backed can't be extracted so it would minimize (albeit not eliminate) the time the actual credentials are stored in ram.

check out the fourth example here: https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.html

**Comment by cketti** [comment]
Sure. But that is just a poor man's way to avoid device encryption. I don't think we should invest time to support users willing to set up a "secure" device lock but not device encryption.
Also, KeyStore was unreliable in the past. So this has the potential to cause serious support issues when used on older devices.

**Comment by Valodim** [comment]
agreed ([link related](http://doridori.github.io/android-security-the%20forgetful-keystore/#sthash.6YiOF5Lb.dpbs))
