### ISSUE TITLE
Option to remove negative feedback for encryption and signing

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1214]
### Expected behaviour
Not display 'Not encrypted' and 'Not signed' when an OpenPGP provider is configured.

### Actual behaviour
'Not Encrypted' and 'Not Signed' is displayed for the vast majority of email I get

### Steps to reproduce
1. Configure an OpenPGP provider
2. View an email not delivered with PGP

### Environment
K-9 Mail version: Current / 5.108
Android version: All
Account type (IMAP, POP3, WebDAV/Exchange): All

### Notes
Errors with the signing key / encryption should still be displayed.

**Comment by Valodim** [comment]
An option is not the way to go, but obviously the displayed status must be less intrusive.

**Comment by greenify** [comment]
Maybe you can put this into the header? And I would prefer that I as a user can choose whether I want to see a not encrypted warning for all emails. I guess for most of us out there the main mail influx is unencrypted, so it would make more sense to highlight those.

**Comment by Valodim** [comment]
We aren't really tracking any issue here other than "it's not done yet" -> closing for now
