### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by Farshh** [k9mail/k-9#1219]
### Expected behaviour
automatically synchronization 

### Actual behaviour
I use the K-9 Mail App on my Samsung Note 5. All settings are correct. I can send and receive mails.

The synchronization is set to 15 minutes. But every night the synchronization is automatically disabled again. I can´t say exactly, from what time but when I wake up every morning, I see this issue. Then I have to enable the synchronization manually.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.008

Android version: 6.0.1 (Samsung Note 5)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Caused by Doze. See #998, #857, et al.
