### ISSUE TITLE
Adding pulldown-to-refresh for all folders

### ISSUE THREAD

**Issue by timovn** [k9mail/k-9#1222]
This is more a feature request and some UX suggestions than an actual bug.
### feature request

When on an account, listing the folders, a "pull-down" action on the screen should make all the folders reload.

This behaviour is already present in a single folder view, but not on the account view.
Using this would make the button at the button of the screen for "refresh" obsolete.
### UX-suggestions

I use K9 for years now and I love it, but there are still some behaviours that bugs me.

– The search button is not on the same row than the search field (button is at the bottom of the screen and field is at the top).
– not sure is the "k9-mail" logo at the left end of the top bar is necessary (it contrasts with the other parts of the app.
– I took a while to understand that the number on the right end of the top bar was the amount of unread messages. IMHO it should have the same font/color/icon as the icon of unreaded-messages on each folders (see linked screenshot 1)
– maybe add a more visible "write new message" button (maybe like the one in gmail/google-apps)

Screenshot 1:
![screenshot1](https://cloud.githubusercontent.com/assets/4772201/14076547/d5a013da-f4e2-11e5-9fc2-5c5193501898.png)
### Environment

K-9 Mail version: 5.008
Android version: 4.4.4
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by yvecai** [comment]
The pull down behavior could be added to the main page too (refresh all accounts).

**Comment by cketti** [comment]
Obsolete due to redesign.
