### ISSUE TITLE
Original encrypted body not quoted in reply

### ISSUE THREAD

**Issue by dschuermann** [k9mail/k-9#1225]
### Expected behaviour
When replying to an encrypted email the original should be quoted.

### Actual behaviour
When replying to an encrypted email the original is not quoted.

### Steps to reproduce
1. Received an encrypted email
2. Click Reply
3. Examine displayed content.

### Environment
K-9 Mail version: ?

Android version: ?

Account type (IMAP, POP3, WebDAV/Exchange): ?

**Comment by philipwhiuk** [comment]
(Re-formatted to match issue template).

I suspect this might actually be unimplemented content but I'll let @Valodim comment.

**Comment by Valodim** [comment]
This is indeed as of yet unimplemented, because I reckon it'll be a lot easier to do once pgp/mime email viewing isn't subject to changes as it is now.

**Comment by webratte** [comment]
Hi everybody,
some news about this issue?
I think this and:
 
App crashed by typing address in the address field when composing a message #1251 

are really important things for using a mail app.

It would be great if you prefer this.

**Comment by Valodim** [comment]
Forgot to mention, this is fixed by #1501
