### ISSUE TITLE
Attach public key

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#1234]
### Expected behaviour

User should be able to attach his/her public key when composing a new email.
### Actual behaviour

User has to go to OpenKeychain, (key), advanced, share with, K-9 Mail. (Assuming the key is not uploaded to a keyserver)
### Steps to reproduce

N/A
### Environment

K-9 Mail version: 5.108

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
N/A

**Comment by philipwhiuk** [comment]
The potential enhancement I see here is for OpenKeychain to list itself as a source of files - much like the Photos app does. That would be an OpenKeychain enhancement, not a K-9 one.

What are you expecting K-9 to do here given it does not store the keys themselves.

**Comment by JasperWeiss** [comment]
It might require some work on OpenKeychain. Essentially a 'attach pub key' button would ask OpenKeychain for the public key which is then added as an attachment to the mail by K-9 mail.

**Comment by philipwhiuk** [comment]
I feel like OpenKeychain implementing itself as a content provider for files and allowing you to pick whichever you like is less cluttered. Space is already a concern.

Unless there's something different to attaching a key versus any other file I don't see the point in doing it differently.

**Comment by JasperWeiss** [comment]
Yes that'd be easier, I'll open up a new issue for OpenKeychain

**Comment by Valodim** [comment]
Actually, the key to attach is already known to k9 at the point of selection (it's configured), *and* it's indeed sort of a special case since it can be treated on receiver side as a trigger for opportunistic encryption.

**Comment by JasperWeiss** [comment]
@Valodim Would it be difficult to implement this?

**Comment by philipwhiuk** [comment]
But you need the key in a useful file format so you'd have to have more intents for that. I feel like it's better for OpenKeychain to just define itself as a file provider. Then any app can be used to distribute public keys and K-9 users can use the attachment interface like normal.

**Comment by Valodim** [comment]
there already is an ACTION_GET_KEY in the api, as this was implemented before

**Comment by philipwhiuk** [comment]
I'd envisage OpenKeychain below the 'Photos' entry in this example

![image](https://cloud.githubusercontent.com/assets/1316415/14155000/9427596e-f6b7-11e5-9207-31380aa0d2b8.png)

I just think you're adding unnecessary complexity to the cramped Compose interface when what you're actually doing is just attaching a file like normal.

**Comment by Valodim** [comment]
The workflow is only loosely related to attaching a file, since the user does not actually select a file.

**Comment by JasperWeiss** [comment]
If OpenKeychain would act as a content provider, it would be easier to share the key through other apps as well. Currently, it requires the user to dig through the 'advanced' section.
On the other hand, attaching the public key is something people often forget with PGP. So it might be better to have K-9 Mail attach the key by default when sending encrypted/signed mails.

**Comment by Asudox** [comment]
> If OpenKeychain would act as a content provider, it would be easier to share the key through other apps as well. Currently, it requires the user to dig through the 'advanced' section. On the other hand, attaching the public key is something people often forget with PGP. So it might be better to have K-9 Mail attach the key by default when sending encrypted/signed emails.

Any news on this? As far as I see, this is still not a thing in the app.
