### ISSUE TITLE
Delayed alarms sent

### ISSUE THREAD

**Issue by llweifall** [k9mail/k-9#1237]
Dear k9 developers,

I have found that AlarmManager.set(int type, long triggerAtMillis, PendingIntent operation) is used in com.fsck.k9.helper.K9AlarmManager#set(int,long,android.app.PendingIntent). According to Android API Guide Using this API on devices with SDK higher than 19, the alarm may not be sent at the exact scheduled time.

You may refer to [API guide](http://developer.android.com/intl/zh-cn/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent)) for details.
So I am suggesting if you can change the set method to setExact method, so that the alarm can be sent at the exact scheduled time.

Thank you.

**Comment by cketti** [comment]
Since you can't really specify a time when polling starts I see little benefit of keeping an exact schedule when polling. Using inexact alarms allows the system to batch alarms of multiple apps.
