### ISSUE TITLE
Add sender name to contacts

### ISSUE THREAD

**Issue by spectas** [k9mail/k-9#1238]
It would be helpful, if the "add to contacts" function would not only pass the e-mail address, but also the real name to a new contact.

Example:
If there is an e-mail in the inbox from
"Dr. Susan Miller (Veterinarian)" <mail@susan-dogs-and-cats.com>
K9 mail right now only imports
mail@susan-dogs-and-cats.com
to a new contact. To add the real name to this new contact, you would have to go the complicated way of changing back to k9 mail, copying the real name (that meany opening the mail, "show headers", copy the real name out of it), changing back to the new contact and add the real name.

![k9-screenshot](https://cloud.githubusercontent.com/assets/3306424/14171385/f259361c-f732-11e5-9f39-c86714e3b740.png)

This would help a lot,
thanks in advance!
Spectas

### Environment
K-9 Mail version:
5.008
Android version:
5.1.1 (Cyanogenmod 12.1)
Account type: IMAP + CardDAV (DAVdroid)

**Comment by philipwhiuk** [comment]
This will only work on 4.3 and above as that's when the API was introduced - before that it'll do what it does now. But it's quite do-able :)

**Comment by spectas** [comment]
Wow, thanks a lot for your commit! That was really quick!!

**Comment by spectas** [comment]
I just found out, that there is already a way. If you don't click on the sender's icon (normally the first Name of the sender's name) in the inbox or in the single mail view, but if you click in single mail view on the senders name, the sender's name plus his mail address will be passed on to the contacts app. So this function should probably be used as well, when you click on the icon.

**Comment by philipwhiuk** [comment]
The PR includes passing the name on in both cases - I searched for any use of the old API method.
