### ISSUE TITLE
Can't write mail to addresses which contain a slash

### ISSUE THREAD

**Issue by Lothloriennos** [k9mail/k-9#1255]
### Expected behaviour
Tell us what should happen
Writing mail to addresses in the form of "a/b@domain.us" should be possible according to rfc, but is not

### Actual behaviour
Tell us what happens instead
When entering a "/" in the address field K-9 crashes.

### Steps to reproduce
1. Open new mail
2. Entering "a/" in the address field (to:)
3. Crash: "Unfortunately K-9 Mail has stopped."

### Environment
K-9 Mail version: 
5.008

Android version: 
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
POP3, IMAP

**Comment by Valodim** [comment]
Hi, thanks for your report!

The compose interface was changed quite a lot since the latest release, and this issue is no longer present. This works in the current alpha release, and will be fixed when that is released as stable.

**Comment by Lothloriennos** [comment]
Hi, thanks for the reply.

That sounds great, thank you.
I assume, it will be the same for Kaiten, because that slash-issue was the
reason for not buying, so far.

Regards LL

**Comment by philipwhiuk** [comment]
See #984 re Kaiten.
