### ISSUE TITLE
attachments opening

### ISSUE THREAD

**Issue by votanak** [k9mail/k-9#1256]
### Expected behaviour
saving attachments without opening by click on "save" button

### Actual behaviour
only saving attachments by click on "save" button without opening

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:5.008

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange): Exchange

**Comment by philipwhiuk** [comment]
Sorry, it's not clear what doesn't work here. Does "Save" open the attachment or what?

**Comment by cketti** [comment]
@philipwhiuk: It does in 5.0xx when MediaScanner detects a supported file… long story.

@votanak: The behavior has already changed in the current development version. The next major stable version won't open the file after saving.
