### ISSUE TITLE
No archive folder; cannot move emails to other folders.

### ISSUE THREAD

**Issue by Rbagman** [k9mail/k-9#1257]
Hello, I do not have the option of moving emails to a folder nor an archive folder. I jave no errors and all folders are showing.

Samsung Galaxy Note 2 (GT-N7100/Android 4.4.2)

**Comment by cketti** [comment]
You failed to provide the necessary information. But it sounds like you're using a POP3 account which doesn't support that functionality.

Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
