### ISSUE TITLE
 ClassNotFoundException: com.fsck.k9.search.LocalSearch

### ISSUE THREAD

**Issue by amennini** [k9mail/k-9#1265]
### Expected behaviour
Referring to issue #1240, it happened again: k-9 crashing and hi bandwitdh usage.

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.0010

Android version: 5.0 on a Samsung S5 with original rom. No root, no mods.

Account type (IMAP, POP3, WebDAV/Exchange):IMAP
[k9-log.txt](https://github.com/k9mail/k-9/files/205975/k9-log.txt)

**Comment by philipwhiuk** [comment]
This is not related to issue #1240 and that issue is probably not the cause of your bandwidth usage, it's just an issue I saw in your log.

Certainly this log doesn't contain any exceptions from K-9.
