### ISSUE TITLE
No menu bar icons on Android TV (Philips)

### ISSUE THREAD

**Issue by quelbs** [k9mail/k-9#1269]
## Expected behaviour
I should be able to see and use the menu buttons

### Actual behaviour
On my Android TV (Philips) no menu buttons are shown, thus I cannot send new mails or replys. On Smartphone and Tablet everything works as expected.

### Steps to reproduce
1. start app and add mail account
2. No menu bar icons are visible

### Environment
K-9 Mail version: 5.010 and 5.108

Android version type (IMAP, POP3, WebDAV/Exchange):
Android TV 5.1 LMY47D

**Comment by cketti** [comment]
Android TV is out of scope. We certainly accept patches to increase support, but we won't track bugs concerning this platform.
