### ISSUE TITLE
Once Account Is Created, Cannot Go Back and Alter Its Settings

### ISSUE THREAD

**Issue by TurtleShroom** [k9mail/k-9#1270]
### Expected behavior
I want to go back to my account settings and change the incoming and outgoing servers, so that it'll recognize my E-Mail and start drawing messages in, like it should.

### Actual behavior
I cannot find a means to enter the settings and servers of my E-Mail. To do this, I have to uninstal the K-9 E-Mail App and reinstall it using the setup wizard.

### Steps to reproduce
1. Open K-9
2. Account Settings or Global Settings
3. Notice the lack of E-Mail server settings

### Environment
K-9 Mail version: Newest

Android version: Samsung Android LG GVISTA2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/Manual-accountsettings

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
