### ISSUE TITLE
k9mail not synchronize the  sub-folder in my inbox

### ISSUE THREAD

**Issue by uNouss** [k9mail/k-9#1284]
Hello all
i use k9mail Version 5.008 in my Android 4.1. i use imap protocol in k9mail.
i make filter in my webmail for range my mail in a folder. this folder is in my imbox like this 
![selection_011](https://cloud.githubusercontent.com/assets/15982321/14525604/9353e768-023e-11e6-8dbd-2e8b18af1da9.png)
but i dont have this folder in k9mail.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
