### ISSUE TITLE
Create new Identity from received mail

### ISSUE THREAD

**Issue by se4203** [k9mail/k-9#1285]
### Expected behaviour
When reading a received mail, the To: address should be clickable.
Clicking it should offer the user to add it as a new Identity in K-9.

### Environment
K-9 Mail version: 5.008

Android version: 5.1.1 (CyanogenMod 12.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
This seems like a pretty narrow use case. Most of the time that To address is going to be a mailing list. Adding this as an option is just going to add clutter to a menu that 99% isn't what you want.

We do need to improve the display of addresses - my preference is for the compose tokens we use in the beta. But I'm not sure about this option.

I'm trying to understand the use case here - is this really a common scenario for you?

**Comment by cketti** [comment]
This is the wrong behavior most of the time. Issue #935 contains better ideas on the topic.
