### ISSUE TITLE
K9 wrongly detects disabled Auto-Sync

### ISSUE THREAD

**Issue by ak131554** [k9mail/k-9#1287]
### Expected behaviour
K9 should sync my mail account every 5 minutes.

### Actual behaviour
During the night and somtimes irregularly during day, my account isn't synced. Instead it tells me that Auto-Sync had been disabled. By googling I found advices to turn Auto-Sync on in Settings > Data usage. I'm using a Samsung Galaxy S6 and there this option has been removed. The only place where I can disable Auto-Sync ist in Settings > Accounts. But this option is not disabled with me, and apart from that you only disable syncing the defined accounts in Android. But K9 is not an account.
Furthermore, there is the setting that I can enable background sync independent of Anroid's Auto-Sync option. But this doesn't work. Even if I set this option to always, it tells me that Auto-Sync had been disabled and refuses to sync my Accounts.

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Caused by doze #857 (work-around, manually whitelist K-9) or a (possibly separate issue) with 6.0.1 #970

**Comment by bam80** [comment]
>By googling I found advices to turn Auto-Sync on in Settings > Data usage. I'm using a Samsung Galaxy S6 and there this option has been removed. The only place where I can disable Auto-Sync ist in Settings > Accounts. But this option is not disabled with me, and apart from that you only disable syncing the defined accounts in Android. But K9 is not an account.

Indeed, seems we have a mess here with all these Auto-Sync Settings.
Filed an issue: https://github.com/k9mail/k-9/issues/3042
