### ISSUE TITLE
Can't reply after displaying delete, archive, move, spam buttons

### ISSUE THREAD

**Issue by jikamens** [k9mail/k-9#1291]
### Expected behaviour
Changing my settings to display the delete, archive, move, and spam buttons at the bottom of each message should not cause me to suddenly be unable to reply to messages.

### Actual behaviour
If I add enable four of those buttons in my settings, then the reply menu button disappears, and the reply, forward, etc. commands do not appear in the menu, so there is no way for me to reply to the message.

### Steps to reproduce
1. Enable delete, archive, move, spam buttons in global display settings.
2. View a message.
3. Try to reply to it.

### Environment
K-9 Mail version: 5.010

Android version: 6.0.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by zhsj** [comment]
I think you can click the button on the right (that's a `more` button). Then click `Send...`. Now you can see `Reply`, `Reply all`, `Forward`, `Share`

**Comment by jikamens** [comment]
By George, you're right. Thanks for the clarification. PEBKAC problem, apparently.
