### ISSUE TITLE
Cipher support in Android 4.4.4?

### ISSUE THREAD

**Issue by ArchangeGabriel** [k9mail/k-9#1292]
### Expected behaviour
My IMAP server (dovecot) is requiring TLS 1.2, and only exposes these ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256.

This is supposed to work on Android 4.4.4, and it works in web browser for instance.

### Actual behaviour
It does not work in K9-Mail, but apart from “Connection failed”, it’s not very helpful. On server side I have this:
`imap-login: Error: SSL: Stacked error: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher`.

So, no shared cipher, which is strange because a webserver (nginx) with the same configuration does work on this smartphone.

I’m not sure where the issue lies, because it does work on newer version of Android, but this is on a phone I actually can’t upgrade (Geeksphone Revolution).

### Environment
K-9 Mail version: 5.010

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Our cipher list is outdated. 

In master it's fine
* https://github.com/k9mail/k-9/blob/9ebf411d95a9cb1f6918016d982d8ca6467d1a8a/k9mail-library/src/main/java/com/fsck/k9/mail/ssl/DefaultTrustedSocketFactory.java#L35

In the latest release it's not:
* https://github.com/k9mail/k-9/blob/5.010/src/com/fsck/k9/net/ssl/TrustedSocketFactory.java#L32

We really ought to add the GCM ciphers to stable at minimum.

**Comment by ArchangeGabriel** [comment]
OK, so k9mail doesn’t explicitly allow those ciphers, but it works because the system supports them, so they are automatically added. The question is then why on 4.4.4 (or this specific device maybe?) this doesn’t work.

Because yes, my IMAP server use exactly the same cipher list as nginx, it has been copy-pasted from one to the other. I’ve checked that with ssl-scan and https://www.htbridge.com/ssl/, both report the exact same list:
```
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

A bit more details from ssllabs:
```
 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH secp256r1 (eq. 3072 bits RSA)   FS 	128
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp256r1 (eq. 3072 bits RSA)   FS 	256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 2048 bits   FS 	128
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 2048 bits   FS 	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH secp256r1 (eq. 3072 bits RSA)   FS 	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp256r1 (eq. 3072 bits RSA)   FS 	256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x67)   DH 2048 bits   FS 	128
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b)   DH 2048 bits   FS 	256
```

About Android connexion test:
```Android 4.4.2 	RSA 2048 (SHA256)   	TLS 1.2 	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH secp256r1  FS```

And a more global view:
https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2

So, it is supported and actually does work, at least in web browser (both default one and Firefox for Android).

**Comment by ArchangeGabriel** [comment]
Some additional information: the same system seems not to support SNI (in K9-Mail, it does in webbrowser), while it should. Definitively strange.

**Comment by philipwhiuk** [comment]
Ah... If it's a matter of SNI support that might be the problem. We don't support SNI in the latest stable release. It's been merged in and should be available in the beta I think: https://github.com/k9mail/k-9/pull/718

**Comment by ArchangeGabriel** [comment]
No, it’s not a matter of SNI, this was just a supplementary test I ran. Also, SNI is actually working in K9-Mail 5.010 on my OPO running CM13, or at least it seems. Will double check that tonight.

**Comment by almesh** [comment]
https://mobile.facebook.com/login/?_e_pi_=7%2CPAGE_ID10%2C4607042877

**Comment by ArchangeGabriel** [comment]
I can confirm that SNI is working on my OPO. So, we have:

1. OPO running Android 6.0.1, having no problems with modern ciphers and SNI.
2. GPR running Android 4.4.4, having troubles with both modern ciphers and SNI, while supposed to support those.

Both using K-9 Mail 5.010.

Could it be that newer Android version somehow automatically add support for those things (at least seems to be the case for ciphers, right?), while older one needs things to be explicitly enabled in order to work?

**Comment by philipwhiuk** [comment]
Without knowing much about Android (or the actual OS running - manufacturers often make changes with the stuff they put in/take out) it's probably possible. If SNI just worked anyway I can't imagine we'd have bothered adding code to turn it on.

**Comment by ArchangeGabriel** [comment]
OK. I will just wait for a K-9 Mail version with new ciphers and SNI enabled to retest that. ;)

**Comment by ArchangeGabriel** [comment]
Hi there. I’d like you to reopen this, I’ve been testing with the release of K-9 5.200 and the issue is still present. On server side, I see this:
```
TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
```

On client side, log:
```
K9-Mail version: 5.200
Device make: geeksphone
Device model: revolution
Android version: 4.4.4

com.fsck.k9.mail.MessagingException: IO Error
	at com.fsck.k9.mail.store.imap.ImapFolder.ioExceptionHandler(ImapFolder.java:1366)
	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:163)
	at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:114)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:845)
	at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:841)
Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa9f14210: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x9391c966:0x00000000)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:662)
	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:633)
	at com.fsck.k9.mail.store.imap.ImapConnection.setUpStreamsAndParserFromSocket(ImapConnection.java:228)
	at com.fsck.k9.mail.store.imap.ImapConnection.startTLS(ImapConnection.java:312)
	at com.fsck.k9.mail.store.imap.ImapConnection.upgradeToTls(ImapConnection.java:300)
	at com.fsck.k9.mail.store.imap.ImapConnection.upgradeToTlsIfNecessary(ImapConnection.java:284)
	at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:119)
	at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:640)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:623)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:612)
	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
	... 7 more
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa9f14210: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x9391c966:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
	... 19 more
```

I’ve stumbled upon a similar report here BTW: https://community.qualys.com/thread/14522.

**Comment by cketti** [comment]
None of these ciphers is supported by Android 4.4 (API 19). See for yourself: https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

**Comment by ArchangeGabriel** [comment]
Hum, indeed. I wonder why https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2 report them though (will ask that to them). Maybe all Android browser use a custom ssl lib?

**Comment by ArchangeGabriel** [comment]
So, if anyone come here, the answer is that ssllabs (currently) looks at WebView SSL support, which is different from that of the OS. Reason being that all web apps will use WebView.

Conclusion, there is nothing to be done regarding mail support, and Android 4.4 will be a deprecated platform when TLS1.0 goes off (expected in 2018 AFAIK).

**Comment by philipwhiuk** [comment]
If we have a large Android 4.4 user base we could always do what WebView does and package OpenSSL / BoringSSL/etc - meaning we can use later versions. We'd have to release every time it updated and there's a lot of binding work to do but I know of other apps that do it.

**Comment by ArchangeGabriel** [comment]
Do you have statistics regarding this usage? Maybe from the PlayStore, since K-9 is distributed there as well (F-Droid user here, so not in stats AFAIK).

I’m not sure that’s (currently) worth it, they are probably way more important things requiring your attention (at least for now, not supporting TLS 1.0 being an issue should only be an edge case).

**Comment by philipwhiuk** [comment]
37% of devices on the Google Play Store use 4.4 or below at time of writing. I'm not sure how that breaks down on K-9 itself (I don't have Play Store access for the K-9 app), although with 24% using 4.4 alone it's likely to be significant. 

But given the amount of work involved I agree.

**Comment by cketti** [comment]
I have no plans of packaging a TLS library unless absolutely necessary. So far I don't see the necessity.

**Comment by ArchangeGabriel** [comment]
Like I said, it’s not necessary for now, excepted for corner cases which are not worth supporting.

However, once a EOL date for TLS 1.0 & 1.1 will have been decided (it was June 30th, 2016 in PCI-DSS requirements but was moved to same day in 2018 finally, but I’m not sure about things outside of PCI-DSS scope), if they are still a lot of 4.4 and below users, it will become necessary. We might hope it won’t.

**Comment by cketti** [comment]
The PCI-DSS requirements are not relevant for most users. And those who are affected probably also use newer Android devices.

**Comment by ArchangeGabriel** [comment]
That’s why I’ve said I’m not sure for things outside of PCI-DSS scope. But once again, there is no rush here: lets wait to see how it goes in one year (both on TLS deprecation side and Android 4.4− usage of K-9) before discussing this. ;)
