### ISSUE TITLE
Attachment file size miscalculated and file corrupted

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#1296]
### Actual behaviour

I received an email with an attached pdf from a trustworthy source onto one of my IMAP accounts. Upon opening the email in k9 (5.010 from the Play store), going to "Show attachments" and then clicking on "Save" the file is downloaded to my sd card but can not be opened.and is just 3 byte in size, concretely: "<1u".

This is reproducible in the sense that taping "Save" again, downloads another file with the same content into the downloads folder with a "-2" attached to the name. Also same behavior can be observed on another device that received the same email through another IMAP account with kaitenmail.

The same attachment from the same email can be opened and save just fine on my notebook and I never had problems with other attachments with k9.
The pdf is not encoded and starts with 

```
%PDF-1.4^M%\342\343\317\323^M
294 0 obj^M<</Linearized 1/L 2369362/O 296/E 128475/N 31/T 2363366/H [ 1316 873]>>^Mendobj^M          ^Mxref^M294 51^M0000000016 00000 n^M
0000002361 00000 n^M
0000002511 00000 n^M
0000003041 00000 n^M
0000003304 00000 n^M
0000004132 00000 n^M
0000004223 00000 n^M
0000004548 00000 n^M
...
```

Finally, the displayed file sizes already differ. In k9 the size is displayed as 4.6MB, the actual size (of the non-corrupted file) however is 2369363 bytes.
### Expected behaviour

A file with the correct content is downloaded and the correct file size is displayed in k9.
### Environment

K-9 Mail version: 5.010

Android version: 4.4.2 Samsung galaxy s4 mini

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I am happy to provide further details if you tell me what would be useful for you.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the current K-9 Mail version.
