### ISSUE TITLE
Feature: Select folders to display in folder list

### ISSUE THREAD

**Issue by edrush** [k9mail/k-9#1301]
### Expected behaviour
I'd like to select the folders that I want to see in the folders list (and so, exclude other folders from my list).

### Actual behaviour
You can select groups like "All folders", "1st class folders", ...

### Steps to reproduce
1. Go to "Account settings"/"Folders" or just "Folders" when you're in an account.

### Environment
K-9 Mail version: 5.105

Android version: 4.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Sorry if this feature is already there, then I just did not find it yet. I searched your issues wit the query "folders".

**Comment by ArchangeGabriel** [comment]
As you’ve seen it by yourself, this is the “folder class” feature. You can set each folder display class and then adjust what classes are displayed.

**Comment by edrush** [comment]
Wow...great! I misunderstood the "class" label, of course it is what you say. I thought it is the level of the folder in the folders tree.

An awesome work you do - thank you so much.
