### ISSUE TITLE
Feature: Autosync selected folders

### ISSUE THREAD

**Issue by edrush** [k9mail/k-9#1302]
### Expected behaviour
I'd like to select folders that get synced automatically just like "Inbox", so that when I go to a subfolder the current 50 messages are displayed there at once (reason: I auto-filter mails into folders and always have to manually sync the folder to read current mails there).

### Actual behaviour
(It seems that) Only inboxes sync automatically.

### Environment
K-9 Mail version: 5.105

Android version: 4.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Sorry if this feature is already there, then I just did not find it yet. I searched your issues wit the query "folders".

**Comment by ArchangeGabriel** [comment]
This is the “folder class” feature too. Folders also have a “sync class”. Just set each folder class the way you want, and adjust sync settings to sync all 1st class folder for instance.

**Comment by edrush** [comment]
Great! Really, thanks a lot.

(for the misunderstanding see https://github.com/k9mail/k-9/issues/1301)
