### ISSUE TITLE
Export, import config creates new accounts rather than updating config of existing accounts

### ISSUE THREAD

**Issue by jikamens** [k9mail/k-9#1304]
### Expected behaviour
If I export my config and then re-import the same config, the re-imported config should update the settings in the existing accounts, rather than creating new accounts.

### Actual behaviour
If I export a config with two accounts in it, then re-import the config, it creates two new accounts with "(1)" after their names, rather than overlaying the settings in the imported config on top of the existing accounts.

### Steps to reproduce
1. Configure two accounts.
2. Export config.
3. Re-import config.

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
That's by design. Overwriting the settings of an existing account could lead to corrupt internal state. Properly handling this case would require lots of work. And I don't consider this an important use case.
