### ISSUE TITLE
Changing folder list font size doesn't change height of folder list items

### ISSUE THREAD

**Issue by jikamens** [k9mail/k-9#1305]
### Expected behaviour
If I make the folder list font size smaller, then the height of the individual items within the folder list should get correspondingly smaller, so that more folder names fit on the screen.

### Actual behaviour
The font gets smaller but it just leaves more whitespace around it -- the height of each entry in the list remains constant.

### Steps to reproduce
1. Observe how many folder list items fit on the screen.
2. Reduce the font size for folder list items.
3. Observe that the same number of folder list items fits on the screen.

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This won't be fixed before the UI overhaul and shouldn't be an issue afterwards.

**Comment by leafcutterant** [comment]
@cketti, may I ask what do you mean by the UI overhaul and when did it happen (if it had happened)?

I'd like to request a re-opening of this issue. I am using 5.207 and the problem persists. It provides a very uncomfortable UX for those with a lot of folders.
