### ISSUE TITLE
Need navigation buttons at bottom in tablets

### ISSUE THREAD

**Issue by kejriwals** [k9mail/k-9#1314]
### Expected behaviour
The navigation buttons (delete, next, previous, spam etc) are placed below the email in phone version of your app. It is very convenient as I can use my thumbs to quickly take actions on my mailbox. 

### Actual behaviour
But in my 8" tab, these buttons appear on top of the app screen. I hold my tab the same way like my phone, and then I can't manage my emails efficiently. In landscape mode when my tab is placed on my desk, it anyway doesn't matter where the buttons appear. But when holding it in my hands, I would like to use my thumbs like I do on my mobile phone. 

### Steps to reproduce
1. Explained above

### Environment
K-9 Mail version: 5.010

Android version: Lollipop

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We currently don't have plans to support this.
