### ISSUE TITLE
App won't notify for new emails

### ISSUE THREAD

**Issue by fabriziodicandia** [k9mail/k-9#1322]
### Expected behaviour
My phone should vibrate when a new email incomes in my K9 inbox.

### Actual behaviour
Nothing happens. I have to manually refresh the inbox to see the new emails.

### Environment
K-9 Mail version: 5.0.10

Android version: 3.4.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Please can you provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by philipwhiuk** [comment]
Without a debug log and information on the settings of the account it's likely this was due to network connection or just that the phone was only set to poll infrequently. For general troubleshooting please use https://groups.google.com/forum/#!forum/k-9-mail
