### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by JungHoonHyo** [k9mail/k-9#1324]
### Expected behaviour

It seems nothing is not synchronized method or synchronized reasons for failure.
I would like to know more information and solutions for synchronization failure.

### Actual behaviour

I was used for the first time k - 9 . It was connected to create an account and become a failed synchronization . Since then, I want to Sync I could not do anything .

### Steps to reproduce
1. enter e-mail address
2. enter passward
3. Click the next button

### Environment
K-9 Mail version: v5.010

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/#!forum/k-9-mail

**Comment by JungHoonHyo** [comment]
Sorry. It was too hasty . thank you for telling me.
