### ISSUE TITLE
la case afficher les noms des correspondants, double l'affichage du sujet

### ISSUE THREAD

**Issue by frederiiiic** [k9mail/k-9#1325]
### Expected behaviour
Dans les paramètres globaux / Affichage, je coche "Correspondants au-dessus de..."

### Actual behaviour
Le visionneur de message m'affiche deux fois le sujet du message, une fois au dessus une fois en dessous!

### Steps to reproduce
Comme indiqué en haut, je pense que ce n'est qu'un oublis.

### Environment
K-9 Mail version:
5.010
Android version:
5.1
Account type (IMAP, POP3, WebDAV/Exchange):
Gmail, IMAP.

**Comment by cketti** [comment]
If you want to be heard, you do the work: https://translate.google.com/
