### ISSUE TITLE
GPG signature unreadable answers

### ISSUE THREAD

**Issue by SecTec** [k9mail/k-9#1334]
Hi,

I'm using k9mail version 5.010 and as my OpenPGP provider Openkeychain.

The behaviour:
When I'm signing an email there is no problem, but if I get an answer from another person with my original signed text is quoted, k9mail only displays the signed part (my own email) and doesn't display the answer.

What k9 schould behave:

Display a line of text like
---start of signed part---
Signed text
---end of signed part---

Or to display a button which toggles between the original message and the only signed message.

**Comment by Valodim** [comment]
thanks for your report. this is a known problem and will be fixed in the next major release. :+1:
