### ISSUE TITLE
Unable to attach files with intent ACTION_SENDTO

### ISSUE THREAD

**Issue by subramanyamgv** [k9mail/k-9#1336]
### Expected behaviour
While sending email with intent ACTION_SENDTO, and the attachmentUri is put as extra with key Intent.EXTRA_STREAM, the K9 mail compose activity should have the file attached.

### Actual behaviour
The attachment is missing in the compose activity.

### Steps to reproduce
1. Create an emailIntent with ACTION_SENDTO
2. emailIntent.putExtra("mailto:john@doe.com")
3. emailIntent.putExtra(Intent.EXTRA_STREAM, attachmentFileUri)
4. startActivity(Intent.createChooser(emailIntent, "send mail..");

### Environment
K-9 Mail version:
5.0.10

Android version:
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by philipwhiuk** [comment]
We expect a list from SENDTO, or a single attachment from SEND. This seems to work with WhatsApp and lots of other programs.

See the code here: https://github.com/k9mail/k-9/blob/e8d04338e2e4788f72391ee8ba248613f260794c/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L701

**Comment by cketti** [comment]
`ACTION_SENDTO` doesn't support attachments. See my article [Android: Sending Email using Intents](https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f#.v3l08ibr3) on how to properly use `ACTION_SENDTO`.
If you need to send an attachment you have no choice but to use `ACTION_SEND`.

**Comment by jhass** [comment]
@philipwhiuk You might want to reconsider, doing a couple of tests it seems more clients actually support a single item in `EXTRA_STREAM` than a list. Including the latest version of GMail.
