### ISSUE TITLE
Order of visible toolbar actions

### ISSUE THREAD

**Issue by ippschi** [k9mail/k-9#1341]
Under

> Settings > Global settings > Display > Visible message actions

I can choose between the visible message actions.
- If only 'Delete' is checked, a delete button is visible in the Message view.
- If 'Delete' and 'Archive' is checked, a delete button is visible and in the context menu there is an 'Archive' option, which is fine, because there is not enough space in the toolbar.
- If only 'Archive' is checked, there is no 'Archive' button, but still only the 'Archive' option in the context menu though there is enough space in the toolbar this time.

I would like to change this small bit.
I am an Android developer and could fix this myself if this feature would be appreciated.

**Comment by KopiasCsaba** [comment]
Related #1363

**Comment by cketti** [comment]
I created a new issue proposing a more generic solution to this problem: #5300
