### ISSUE TITLE
unable to open first attachment? (ics)

### ISSUE THREAD

**Issue by CaptSpify** [k9mail/k-9#1344]
### Expected behaviour
The attachment should open up with associated application

### Actual behaviour
I get this error message: "Unable to find viewer for application/ics"

### Steps to reproduce
1. Receive attachment from Google Calendar
2. Click Open

### Environment
K-9 Mail version: 5.010 and 5.006

Android version: 6.0.1 and 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Whenever I get calendar invites from Google Calendar, it comes with two attachments: invite.ics and noname.ics

Whenever I try to open the first invite attachment, K9 says "Unable to find viewer for application/ics"
I can open the 2nd invite without a problem.

This is weird for two reasons:
1) I can open ics files fine from everywhere else.
2) I can open the 2nd ics file without a problem.

LMK if any more info is needed

**Comment by cketti** [comment]
K-9 Mail uses the MIME type in the email when asking the system to open an attachment. If no app is registered to handle that type you'll get an error message like the one you describe.

**Comment by CaptSpify** [comment]
@cketti 
try re-reading my problem.

Thanks

**Comment by cketti** [comment]
The attachments have different MIME types, hence the different behavior. Files on storage don't have MIME types and the type is derived from the extension. Hence the consistent behavior.

There are no plans to change K-9 Mail's behavior.

**Comment by philipwhiuk** [comment]
To elaborate having just tested it.

One of them is type 

`Content-Type: text/calendar; charset=UTF-8; method=REQUEST`

The other is of type:

`Content-Type: application/ics; name="invite.ics"`

With Google Calendar installed I can open both with Google Calendar.

Your calendar app is not capable of opening application/ics files but is capable of opening application/calendar files. Hence the behaviour you see.

This is actually why Google provides both.

If you want to be able to use both then you should contact your calendar app.

**Comment by CaptSpify** [comment]
@philipwhiuk 
Thanks.
Interesting, as I'm using Google Calendar as well to open these files. The reason it seems like an issue with K9, is that I can open the files from everywhere else except K9. Is there a reason K9 doesn't have an option to associate with file-extensions instead of mime-types?

**Comment by philipwhiuk** [comment]
We don't make an association at all. The association is made by the OS, not K-9. We just tell the OS what the MIME type is and what the file name is. The application that opens the file registers for certain MIME types and/or paths (which can be used to filter for an extension). 

There's literally nothing for us to do here.

**Comment by Valodim** [comment]
That's not entirely true - if we have a filename, we could guess the mimetype by extension and use it as a candidate type. I'm not sure how this is handled, but it's important to remember that a scenario where the user sees a letter.pdf attachment and it won't open because it has an incorrect mimetype is both strictly correct behavior *and* extremely frustrating to the user.

**Comment by cketti** [comment]
`master` already contains some code to fall back to deriving a MIME type from the file extension if no app was found to open the attachment using the MIME type from the email.

**Comment by CaptSpify** [comment]
@cketti Is it interesting that that isn't applying to my situation then?

I'm not saying you should change the code, it's up to you guys the direction you'd like K9 to take, but it seems to me that you were expecting it to fail-over to use the file-extension, and it didn't.

LMK if I'm mis-understanding.

**Comment by cketti** [comment]
@CaptSpify The version you're using doesn't contain this code.

**Comment by Valodim** [comment]
(relevant info here is that it will be in the next stable release)

**Comment by philipwhiuk** [comment]
I'm a bit wary about trusting file extensions, but I guess it's not any harder to fake MIME types than file extensions and it's really the receiving app's responsibility to handle bad files it's passed and assume that files it's passed may be designed to be harmful.

**Comment by Valodim** [comment]
I would have agreed about this half a year ago, but ask yourself this: For the case where both content-type and file extension are given, should the information from the content-type be used to determine the file handling over the file extension? It's easy to imagine various scenarios of abuse based on this behavior, but can you think of just a single legitimate one?

I would almost go so far as to say the Content-Type header should in general only be used for a) internal purposes (mime structuring) and b) files where it's available but handling can't be determined from file extension.
