### ISSUE TITLE
Receiving old emails as new ones.

### ISSUE THREAD

**Issue by ElderJoy** [k9mail/k-9#1345]
### Expected behaviour
Receive nd notify email only one time.

### Actual behaviour
Receive already readed emails as new. Mark them as not readed and notify about it. Can receive new email two times or re-receive month old email second time. Only that I noted, that it occurs more often when real new email comes. 

### Steps to reproduce
1. Set up account to receive emails once per minute.

### Environment
K-9 Mail version: 5.010

Android version: 4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):POP3 with SSL/TLS

**Comment by cketti** [comment]
That's because POP3 is old and not really meant to be used the way we use it. Consider switching to IMAP.

See https://code.google.com/archive/p/k9mail/issues/593

**Comment by ElderJoy** [comment]
Thank you.
