### ISSUE TITLE
Can't control cryptography auto-sign and auto-encrypt checkboxes

### ISSUE THREAD

**Issue by neildarlow** [k9mail/k-9#1346]
### Expected behaviour
I have two installs of K-9 Mail integrated with Openkeychain as the cryptography backend.

On the first system I generated an initial PGP key using Openkeychain. This key was backed-up and imported onto the second system using Openkeychain.

My problem is with controlling the Auto-sign and Auto-encrypt checkboxes located in Settings|Account|Cryptography.

You should be able to toggle these checkboxes on and off with screen taps.

### Actual behaviour
On both systems I cannot change the state of the Auto-sign and Auto-encrypt checkboxes.

On the first system (on which the key was generated) the checkboxes are greyed-out and inactive (off).
On the second system (on which the key was imported) the checkboxes are greyed-out and active (on).

### Steps to reproduce
1. Install Openkeychain and K-9 Mail
2. Generate an initial key on one Android device
3. Import the key from step (2) onto another Android device
4. Configure K-9 Mail on both devices to use Openkeychain and the key
5. Observe the functioning of the checkboxes is broken
6. In other respects signing and encryption work as expected

### Environment
K-9 Mail version: v5.010 on both systems

Android version:
System #1: Android 5.0.2 (ASUS ZenPad 10 Z300C)
System #2: Android 5.1.1 (Sony Xperia Z3 phone)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP4 (Cyrus Imap 2.4 running on FreeBSD)

**Comment by philippelatulippe** [comment]
I just tested it with the latest code, and this is fixed with the new compose screen. The sign/encrypt checkboxes are gone, as are the auto-encrypt/sign options in the settings, replaced by a lock icon next to the recipient field.
