### ISSUE TITLE
Unread Mail Button inaccessible in the folders list

### ISSUE THREAD

**Issue by allo-** [k9mail/k-9#1350]
### Expected behaviour

When scrolling the folders list and there is an "unread mails" bullet, i want to touch it and open the list of unread mails in that folder / view the unread mail.
### Actual behaviour

I touch it and the previously hidden scrollbar appears and the folder list jumps a bit up/down, but i cannot touch the colord bullet hidden behind the scrollbar
### Steps to reproduce
1. open folders list on an mail account
2. find some folder with unread mails
3. touch button
### Environment

K-9 Mail version: v5.010 (and earlier versions)

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (probably any type)

**Comment by philipwhiuk** [comment]
Yep, I see your point. Tapping just to the left of the bullet works in the mean time. I suspect we'll fix this as part of the design overhaul.

**Comment by allo-** [comment]
Hmm, on my phone it seems to be very hard or impossible to get the right point.

Are the options like moving the scrollbar to the other side? Or an option to disable it? I guess not many people are using such scroll bars on touch devices anyway, as the folder list shouldn't be THAT long for most accounts.

**Comment by philipwhiuk** [comment]
I don't think so no, sorry.

**Comment by sploinga** [comment]
Hi, I have exactly the same problem. Does anyone know of a fix or workaround ?

**Comment by allo-** [comment]
Use the global unread or read the whole mailbox. Both are not the same, but workaround to get to the mails.

**Comment by cketti** [comment]
Obsolete due to design overhaul.
