### ISSUE TITLE
bold and italic

### ISSUE THREAD

**Issue by Farshh** [k9mail/k-9#1351]
### Expected behaviour

How is it possible to write words in emails in bold or italics?
### Actual behaviour

N/A
### Steps to reproduce

1.
2.
3.
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
This is really written as a support request best directed at the email list. However... Currently K-9 doesn't support writing anything other than plain text emails so it's not possible.

**Kaiten Mail** does support RTF but as I understand it, it's not under active development and the lead developer of it @cketti has plans to migrate the functionality to K-9 in the future.

**Comment by cketti** [comment]
See #1745
