### ISSUE TITLE
Bad formatting and word wrap for mail with attachements

### ISSUE THREAD

**Issue by Em-En** [k9mail/k-9#1354]
K9 seems to not handle mails with attachements correctly. Instead of sending text message it really sends HTML with fixed size font wrapped in `pre` tag with some new lines added in incorrect places.
### Expected behaviour

Send e-mail with any attachement as plain text (in other words multipart/mixed)
### Actual behaviour

The mail is sent as HTML (multipart/alternative). Because of using `pre` tag there is no word wrap and long paragraph is displayed in one line (at least in Thunderbird). Also some extra word wrap in the middle of a word is added without clear reason.
I'm attaching four files - text only message and the same message with one attachement created by K9 and Thunderbird.
### Steps to reproduce
1. Write message with 2-3 paragraphs containing couple sentences
2. Attach any file
3. The mail will be in HTML, despite of looking like plain text. In Thunderbird every paragraph, no matter how long, will be displayed in a single line, because of used `pre` tag.

Below are the samples how the same message is rendered in Thunderbird and K9 and how K9 message is displayed in Thunderbird.

![sample](https://cloud.githubusercontent.com/assets/18569144/15055460/0a0e8032-130d-11e6-8500-f914a7be338d.png)
[K9 - Just text.txt](https://github.com/k9mail/k-9/files/251122/K9.-.Just.text.txt)
[K9 - Text with attachments.txt](https://github.com/k9mail/k-9/files/251123/K9.-.Text.with.attachments.txt)
[ThB - just text.txt](https://github.com/k9mail/k-9/files/251124/ThB.-.just.text.txt)
[ThB - Text with attachements.txt](https://github.com/k9mail/k-9/files/251125/ThB.-.Text.with.attachements.txt)
### Environment

K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by Em-En** [comment]
OK, can anyone tell me why `pre` was chosen to mimic plain text? When K-9 doesn't force line wrap in any way the result can be just like on the screenshot above - gigantic, one line paragraph which is extremely inconvinient to read. Unless, of course, user adds line breaks manually, which is also not so easy (first words in line start from upper case).

**Comment by Valodim** [comment]
I'm not sure if we ever did, but I neither found evidence in the code that `<pre>` is used to format outgoing mail in K-9, nor did I find it in test mail. Doesn't mean we can't do better for formatting though! :)
