### ISSUE TITLE
Mime-Type is application/octet-stream instead of application/vnd-com.apple.pkpass

### ISSUE THREAD

**Issue by ligi** [k9mail/k-9#1357]
### Expected behaviour

When opening a mail with attached pkpass file the mime-type with the intent should be application/vnd-com.apple.pkpass as in gmail

### Actual behaviour
The mime-type is application/octet-stream for the same mail that opens with application/vnd-com.apple.pkpass in gmail

### Steps to reproduce
1. create a mail with attached pkpass file
2. click on the attachment
3. see the mime-type (e.g. with intent-intercept)

### Environment
K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
When opening an attachment the MIME type from the email is used. If that type is `application/octet-stream` we try to find a better one using [MimeTypeMap.getMimeTypeFromExtension()](https://developer.android.com/reference/android/webkit/MimeTypeMap.html#getMimeTypeFromExtension(java.lang.String)). If that also fails we fall back to [MimeUtility.MIME_TYPE_BY_EXTENSION_MAP](https://github.com/k9mail/k-9/blob/cbbd0bc4057cb660fb1570d46419e811b9755f62/src/com/fsck/k9/mail/internet/MimeUtility.java#L46).

We can add support for `.pkpass` in `MIME_TYPE_BY_EXTENSION_MAP`. But this is fixing the problem at the wrong end. Try to send emails containing the correct MIME type. Also, try to get `.pkpass` support into the system's `MimeTypeMap`.

**Comment by ligi** [comment]
Unfortunately I am not controlling the sending end - so https://github.com/k9mail/k-9/pull/1358 is greatly appreciated

**Comment by erAck** [comment]
Lol, 8 years and still the wrong fix, though I didn't check if the map is even still used, it's legacy now https://github.com/thunderbird/thunderbird-android/blob/59e9e6c80d8d594d43f95b0a8a9c6d10b7b25e6d/legacy/core/src/main/java/com/fsck/k9/helper/MimeTypeUtil.java#L539

It should had been `application/vnd.apple.pkpass` instead, see https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/DistributingPasses.html
Just because GMail does something it doesn't mean it's correct..

**Comment by kewisch** [comment]
Fair point, legacy stuff and standards can be tricky to keep track of—though no need to twist the knife. It looks like you know your way around these. If you have some cycles to spare I'd appreciate if you could take a look and see what the best approach would be going forward, e.g. changing the mime type. A new issue with details, or a pull request, would be very welcome!

**Comment by erAck** [comment]
I only stumbled upon this while investigating what the correct mime-type for pkpass is and what K9/Thunderbird might do if a mail has Content-Type application/octet-stream instead, as PassAndroid is offered as a target for such.

Sorry if my remark came across as harsh, that was not the intention.

**Comment by cketti** [comment]
Android has [added](https://android.googlesource.com/platform/frameworks/base/+/2dbd616ff8937ce90134274fb31c616e0e10fb0f%5E%21/#F0) the `.pkpass` MIME type to their list in November 2023.

Still, we should update our list to use the proper MIME type. A pull request for that would be very welcome.

I've also reached out to a contact at Apple suggesting they should register the proper type in [IANA's media type registry](https://www.iana.org/assignments/media-types/media-types.xhtml).
