### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by JungHoonHyo** [k9mail/k-9#1359]
I am using this application a few days ago . 
Because I gives help for this application because I want to develop . 
But I could not progress forward. Please help me.

I am currently faced with the problem of synchronization. 
I do not know how to be successful in the synchronization fails. 

This problem had been solved some time , but now the issues have been raised again.
I do not know how to solve. Thank you kindly answer .

**Comment by philipwhiuk** [comment]
Unless you have an actual issue with reproduction steps, as required in the issue template, please do not raise an issue and instead ask questions on behaviour on the K-9 mailing list: https://groups.google.com/forum/#!forum/k-9-mail
