### ISSUE TITLE
Email with very large body not displayed

### ISSUE THREAD

**Issue by staples1347** [k9mail/k-9#1360]
I'm using K9Mail: 5.0.10 with Android 6.0.1 on a Samsung Galaxy S7.

When viewing an email with a very large amount of text (A server's backup log for example) and even with account settings to fetch emails of any size, k9mail is showing "No text" for the actual email content view although message preview is showing the first few lines of text.  CursorWindow also gets an error in the android log.  I've also tried clearing the local copy of the folder (it's imap account) and re-downloading but still get the same error.
Logcat output:
05-09 09:37:35.266 20962 27193 W CursorWindow: Window is full: requested allocation 1146938 bytes, free space 862497 bytes, window size 2097152 bytes
05-09 09:37:35.276 20962 20962 I InjectionManager: dispatchCreateOptionsMenu :com.fsck.k9.activity.MessageList
05-09 09:37:35.276 20962 20962 I InjectionManager: dispatchCreateOptionsMenu :com.fsck.k9.fragment.MessageViewFragment
05-09 09:37:35.276 20962 20962 I InjectionManager: dispatchPrepareOptionsMenu :com.fsck.k9.activity.MessageList
05-09 09:37:35.276 20962 20962 I InjectionManager: dispatchPrepareOptionsMenu :com.fsck.k9.fragment.MessageViewFragment
05-09 09:37:35.276 20962 27193 W CursorWindow: Window is full: requested allocation 1146938 bytes, free space 862497 bytes, window size 2097152 bytes
05-09 09:37:35.276 20962 27193 E CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 3 columns.
05-09 09:37:35.286 20962 27193 E k9      : Exception fetching message:
05-09 09:37:35.286 20962 27193 E k9      : java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
05-09 09:37:35.286 20962 27193 E k9      :      at android.database.CursorWindow.nativeGetString(Native Method)
05-09 09:37:35.286 20962 27193 E k9      :      at android.database.CursorWindow.getString(CursorWindow.java:451)
05-09 09:37:35.286 20962 27193 E k9      :      at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
05-09 09:37:35.286 20962 27193 E k9      :      at com.fsck.k9.mail.store.LocalStore$LocalFolder$7.doDbWork(LocalStore.java:1898)
05-09 09:37:35.286 20962 27193 E k9      :      at com.fsck.k9.mail.store.LocalStore$LocalFolder$7.doDbWork(LocalStore.java:1882)
05-09 09:37:35.286 20962 27193 E k9      :      at com.fsck.k9.mail.store.LockableDatabase.execute(LockableDatabase.java:283)
05-09 09:37:35.286 20962 27193 E k9      :      at com.fsck.k9.mail.store.LocalStore$LocalFolder.fetch(LocalStore.java:1882)
05-09 09:37:35.286 20962 27193 E k9      :      at com.fsck.k9.controller.MessagingController$18.run(MessagingController.java:3127)
05-09 09:37:35.286 20962 27193 E k9      :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-09 09:37:35.286 20962 27193 E k9      :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-09 09:37:35.286 20962 27193 E k9      :      at java.lang.Thread.run(Thread.java:818)

**Comment by cketti** [comment]
This should no longer be an issue.
