### ISSUE TITLE
High data usage observed

### ISSUE THREAD

**Issue by Merdique** [k9mail/k-9#1366]
### Expected behaviour

Not sucking my CPU; not downloading 2GB in 2 days without my consent.
### Actual behaviour

Since a week or so, K9 has been eating like over 85% of CPU, handset gets hot. Just received a notice from my cell carrier that K9 has downloaded/uploaded any way transferred like 2 Gigs of data in less than a week, this is totally non sense, never happened before, what the fuck is going on?
### Steps to reproduce

1.Plug the phone while off when waking up in the morning for 2 hours;
2.Unplug the phone when it's fully charged;
3.Just don't really use K9, it's there sitting in the shadow and it will suck my CPU and my data plan.
### Environment

K-9 Mail version:5.010

Android version: Jelly Bean

Account type (IMAP, POP3, WebDAV/Exchange):  Pop + Imap

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Merdique** [comment]
Hi,

Sorry, I uninstalled your app, it already cost me $35 for "over-eating" my data plan, I’m not going to install it again and risk to have to pay some more because or erratic behavior of K9.

Sorry.

On top, I’ve got ± 10 email address, so I would need to re-enter each of them manually, which would take me hours to redo all the settings for each of them (because, as an example, even if I use the same signature for all my accounts, I have to enter it on each account [what about a button "apply to all my email accounts"] and this is a real pain in my butt).

Although I will not use K9 anymore, just thought you’d like to know that I noticed this:

Package com.fsck.k9 has mismatched UID: 1000 on disk, 10305 in settings

This is in uiderrors.txt located in /data/system/

Since I uninstalled your app, I do not get anymore this freakin’ error message every reboot (every morning in my case):

UIDs on the system are inconsistent. You need to wipe your data partition or your device will be unstable.

I’m feeling lucky

I’ve been using your app for months with no issue, but having to re-create all my email accounts, and having to re-enter all my settings (which again would take me hours) is definitely NOT appealing and on top, I just risk to see the app starting again to suck both my CPU and my data plan, sorry, but I’m not willing to go there at all.

Thanks for your reply though.

Good luck.

••••••••••••••••••••••••••••••••••••••••••••••••••
On apprend beaucoup sur les gens en
observant avec quels égards ils traitent
ceux qui ne peuvent rien pour eux…
˜_*
