### ISSUE TITLE
Fewer Navigation Buttons in Tab vis-a-vis Phone

### ISSUE THREAD

**Issue by kejriwals** [k9mail/k-9#1367]
### Expected behaviour
I use K9 in both my phone and tab. In phone, I am able to get more quick navigation buttons, e.g., Previous, Next, Delete, Spam, Reply, and Menu for other options. Surprisingly, I get less options in my tab which has actually got a bigger screen and a more empty space. See the picture for comparison. If I add say, Spam in Tab, the Reply feature completely disappears.

### Actual behaviour
As per the attached picture, there should be an option to add at least two more quick buttons in Tab, e.g., I would like to have quick access to Spam and Move.

### Steps to reproduce
1. Open the Inbox and check. See the attached picture.

### Environment
K-9 Mail version: 5.010

Android version: Lollipop

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
![k9 navigation button issues](https://cloud.githubusercontent.com/assets/18576900/15136861/de7f1a46-16a2-11e6-8951-8b56522cdb3b.jpg)

**Comment by mgrant0** [comment]
I also see this on my android kitkat phone. The Reply button is missing in landscape mode where there is ample space. The Reply button is the in portrait mode with less space. In neither case do i see the 3 dot More button.

**Comment by cketti** [comment]
See #727
