### ISSUE TITLE
Replacing Contact with an email

### ISSUE THREAD

**Issue by gadiator** [k9mail/k-9#1370]
### Expected behaviour
The contact will be replaced with the email address.

### Actual behaviour
The replacement looks like com.fsck.k9.view.RecipientSelectView$Recipient@6596221

![drawonphoto _1462955567096](https://cloud.githubusercontent.com/assets/6163155/15183362/056175c0-1791-11e6-9bbd-0a700736a0ac.png)

### Steps to reproduce
1. open a recieved mail
2. answer on mail
3. click into the recievers field
4. press return some times

### Environment
K-9 Mail version: v5.108

Android version: 6.0.1; Security Patch: 1. March 2016)

Device: Nexus 5X

**Comment by philipwhiuk** [comment]
Fixed in #1204
