### ISSUE TITLE
Excess IMAP logins

### ISSUE THREAD

**Issue by alanthehat** [k9mail/k-9#1372]
### Expected behaviour

Tell us what should happen
One login per poll
### Actual behaviour

Tell us what happens instead
"more than 5" logins listed by my yandex.com every few minutes - this tripped Yandex's 'hackers' panic & locked me out
### Steps to reproduce

1.As far as I know normal usage
2.
3.
### Environment

K-9 Mail version: 5.0.1.0 F-Droid 

Android version: Samsung 5.1.1 

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Push uses multiple connections, one per folder, I'm not sure whether polling allows simultaneous connections or not - we only have a limit for pushing (the lowest limit is 10).
