### ISSUE TITLE
Emails Caching On Server

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#1374]
### Expected behaviour

After Emptying Trash, Emails should Delete from my Web Mail IMAP Server.
### Actual behaviour

In K-9, After Deleting Emails & Emptying the Trash, the Megs/Gigs Calculate Normal, but On my Web Mail IMAP Server, it Calculates as though Emails are Still In the Trash, with Much Higher Megs/Gigs.  There is No Way to Clean Out the Cache.  :--)
### Steps to reproduce
1.  Read Email;
2.  Delete Email;
3.  Empty Trash
### Environment

K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP):

**Comment by philipwhiuk** [comment]
Are the emails actually still the trash folder if you view it on webmail?

**Comment by BrotherAndrew** [comment]
Not when In The Web Mail, but Behind the Scenes.  When looking at a cPanel Breakdown, it Appears.

24K .Archive
80K .Drafts
48K .INBOX.Drafts
68K .INBOX.Sent
18M .INBOX.Trash
24K .Junk
36K .Sent
276K .Trash

**Comment by cketti** [comment]
I don't think this is a bug in K-9 Mail
