### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by OttoPh** [k9mail/k-9#1375]
### Expected behaviour
After changing to a new phone, Huawei Mate 8, K9 does not synchonize anymore. Therefore no new mails arrive and no warnings on new mail appear

### Actual behaviour
When opening K9, it states "next poll 5 hours ago"....! Although polling is set to every hour on all four accounts. Polling does start automatically when K9 is opened

### Environment
K-9 Mail version: Latest

Android version: 6.0

Account type: POP3

**Comment by philipwhiuk** [comment]
Given it's Android 6.0, this is likely caused by #998 Have you tried whitelisting K-9?

**Comment by OttoPh** [comment]
I have no idea how to whitelist K-9....

**Comment by janekx** [comment]
Same here after update to 5.108 it not push from IMAP, gioing back to 5.010 all work and after update to 5.108 again not got new mails. Android  4.4.2

**Comment by RuiBranco** [comment]
Behaviour:
I upgraded to the last version of k9 and now shows syncing disabled. Failed to show the account k9 in Android/Setting/Accounts

K-9 Mail version: Latest
Android version: 4.1.2
Account type: POP3

**Comment by OttoPh** [comment]
I guess I found it. Had to do with the doze function and whitelisting K-9 there made sync work! Thanks all for helping out.
