### ISSUE TITLE
Back button takes view to individual account inbox even though "start in unified inbox" is enabled

### ISSUE THREAD

**Issue by craftyguy** [k9mail/k-9#1377]
### Expected behaviour

When viewing a message (e.g. after tapping on the "new mail" notification to open it), hitting the back button should display the unified inbox rather than the inbox for the account from which the last-viewed email was sent to.
### Actual behaviour

Hitting the back button displays the inbox for the account which received the email, rather than the unified inbox.
### Steps to reproduce
1. enable "start in unified inbox"
2. receive new email, tap notification to view it
3. hit back button, and notice that you're not viewing the unified inbox
### Environment

K-9 Mail version:
5.108

Android version:
6.0.1 (Cyanogenmod 13)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
This will no longer be an issue after the design overhaul.
