### ISSUE TITLE
Suggestion: selection taps/marks on contact icons

### ISSUE THREAD

**Issue by dewi-ny-je** [k9mail/k-9#1391]
The setting to always show selection boxes adds a column with them on the left. It uses additional space.

I think that a solution like the one implemented by Total Commander, where the selection marks are located in the icon itself, would be better. After all the sender can be shown above the subject line in the list view and the icon is there only to show the contact picture.

By using check marks on the icons the display of contact information would require the opening of the email. I think however that selection is way more common than displaying contact info.
As long as this behaviour is implemented as replacement of the checkbox column and always active, every user can still be happy.

**Comment by Valodim** [comment]
gmail does this

**Comment by shiro** [comment]
Nine mail also does this and it feels incredibly intuitive to select multiple items without cluttering the UI IMO.
I personally use it more than long-pressing to enter select mode (in Nine).

**Comment by cketti** [comment]
Fixed by #4616
