### ISSUE TITLE
(Long?) links doesn't open when tapping in new-unread message

### ISSUE THREAD

**Issue by Myjk** [k9mail/k-9#1393]
**What steps will reproduce the problem?** 
1. Get new message(s) from server containing link(s) to phpBB/Buletin Forum 
2. Open unread message (by show all unread integrated) and try tap link(s) to open them in browser

**What do you expect to have happen?** 
Open link in default browser.

**What do you see instead?** 
Nothing happens. Link is visible as url in message body, but can not tap it, and it doesn't open in browser. Must leave this message, go to account folder, enter again into message body and then it's "tapable".

**What version of K-9 are you using?** 
5.010 but this happens from 2 years or longer

**What is your device and what version of Android are you using?**
Nexus 4, Anroid 4.4.4 (and earlier), newest (and older) Chrome browser as default

**Is your email account a POP account, Exchange Account or an IMAP account?** 
POP

_This Issue was already reported on Jun 4 2015 in v. 5.005, and as we can see below in Comment #2 it has been fixed in version 5.006 but I still have this issue sometimes. Please check this out one more time._

**Comment #1**
Posted on Jun 9, 2015 by Swift Monkey
Happens to me with Oneplus One on 5.0

**Comment #2**
Posted on Jun 10, 2015 by Swift Monkey
This has been fixed with the newest release 5.006

**Comment by philipwhiuk** [comment]
Can you provide a sample link that this occurs for. In all likelyhood this is an Android bug however as we mostly just pass the content to the native WebView component.

**Comment by Myjk** [comment]
If it's Android bug, why after leaving problematic message and enter it again everything works as it should? Sample link: http://forum.muratordom.pl/showthread.php?t=53557&goto=newpost

**Comment by Myjk** [comment]
And visualisation of this bug: https://youtu.be/VwZj777aM0M

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the current K-9 Mail version.
