### ISSUE TITLE
Unable to decrypt some messages

### ISSUE THREAD

**Issue by webratte** [k9mail/k-9#1396]
### Expected behaviour
Message should be decrypted

### Actual behaviour
K9 Mail can not find OpenPGP Content.
See also the screenshot.
Squiky Mail an Thunderbird (enigmail) do it.

I will send a Mail to philipATwhiuk.com with a CatLog and the Source of one of this Mails.
Please let me know if it helps or if I can do something else.
![screenshot_2016-05-22-12-25-07](https://cloud.githubusercontent.com/assets/6864851/15453557/c31972e8-201a-11e6-9454-1a90a584a4ee.png)

### Steps to reproduce
I have tried to reproduce it but can not find a way to do it

### Environment
K-9 Mail version:
5.108
Android version:
5.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
Kindly send the mail source to me, too (look@my.amazin.horse)

**Comment by webratte** [comment]
Done.

**Comment by Valodim** [comment]
There is no problem with the email itself, it wasn't correctly downloaded.

If you do "Clear local messages" on the folder this message is in, then refresh the messages, does this error still occur?

**Comment by webratte** [comment]
Yes, that's what I aready tried.
I also deinstalled/reinstalled K9.
It still dosn't work.
This mail is one part of a "mail thread" (three replies)
one of this mails works, two not.

**Comment by webratte** [comment]
Sorry,
I forgot to mention.
I got the Mail Source via Thunderbird.
And there was no problem with decryption.

**Comment by webratte** [comment]
I play just around a little bit.
Reboot the phone, delete all data
Now it seems to work ???!!!!
Strange
It's only the probably fixed issue #1252

If you upload the V 5.109 to Playstore Alpha chanel I would like to test it.

I think we can close this issue for now.

Feel free to reopen it if you think we should do some more tests.

Thank you
