### ISSUE TITLE
Authentication failed after update to 5.109

### ISSUE THREAD

**Issue by dingolino** [k9mail/k-9#1398]
### Expected behaviour
Tell us what should happen

login to imap google account 

### Actual behaviour
Tell us what happens instead
After update from 5.108 to 5.109 authentication is failing on 1 of my 4 accounts  (two web.de and 2 google accounts) 

The one which is failing has a quite long email adress which I am ussing as the login user name.

qwertzui.asdfghj.yxcvbnmasd@gmail.com

with 5.108 it was working.
checked the password already.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.109

Android version:
4.4
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
please try to get a debug log of an authentication process. see [here](https://github.com/k9mail/k-9/wiki/LoggingErrors)

**Comment by dingolino** [comment]
ok, solved it by removing the account and re-adding the account and enter all neccessary items - imap setting,  user name, password, etc.

Looks like that something was "mixed up" after the update.
