### ISSUE TITLE
SMTP handshake failed

### ISSUE THREAD

**Issue by nitrotm** [k9mail/k-9#1399]
### Expected behaviour
SMTP helo handshake should succeed. In particular, when the current Android hostname is not a valid public ip address, some mechanism should be used to retrieve the public ip address the device is sending from.

### Actual behaviour
Because K-9 Mail doesn't use a publicly resolvable hostname when identifying itself, some SMTP server might reject the connection.

### Steps to reproduce
1. SMTP server (e.g. postfix):

smtpd_helo_restrictions =
    reject_invalid_helo_hostname
    reject_non_fqdn_helo_hostname
    reject_unknown_helo_hostname

2. Send an email from K-9 mail on a local-area-network such as a wifi.

3. SMTP server will send back:

550 5.7.1 <SOMELOCALHOSTNAME>: Helo command rejected: Host not found;

### Environment
K-9 Mail version: 5.010

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP+SMTP

**Comment by flavorbiz** [comment]
I was having the same issue and found by changing smtp setting to STARTTLS, I was able to set up the account. Set up said Could not connect to server. 9handshake failed). Have seen on other sites the theory is something in version 6 does not like SSL/TLS

**Comment by cketti** [comment]
It's not easy for a (mobile) client to get a useful hostname/IP that it could use as argument for the EHLO command. The EHLO argument also a completely useless remnant of the times when SMTP was only used between mail servers.

In my opinion it's a mistake for an SMTP server to validate the EHLO argument on authenticated connections. The easiest way to work around this is to use port 587 for client connections and not validate the EHLO argument then.

We won't add functionality to K-9 Mail to only use publicly resolvable hostnames as EHLO argument. We will make sure the argument is syntactically correct. But that's about it.

**Comment by nitrotm** [comment]
Okay, that makes sense. Maybe you could detect this use-case (smtp setting set to ssl/tls and specific error message about hostname) to display a more user-friendly message? Such as a hint to "try with STARTTLS".
Why when I did setup the account it didn't complain after trying to authenticate with smtp server (but only when sending messages)?
Anyway, my problem is fixed thanks to flavorbiz, but maybe some other users might be confused too?

**Comment by cketti** [comment]
This error could very well also occur when using STARTTLS. It's a question of how the mail server is configured.

**Comment by cketti** [comment]
This page sums up the situation quite nicely: http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/smtp-avoid-helo.html

**Comment by nitrotm** [comment]
Interesting. The setup in question is a couple of years old.
If I remember correctly, the motivation was to reduce exposure to unwanted spam and I don't see any pointer on that topic in the article.
I agree that from the standpoint of an authenticated client it doesn't make sense to use the helo/ehlo at all since the user's credentials are enough to control who has access and not. That's probably why the starttls port is by-passing the check completely in this case.
But is there a replacement to helo/ehlo for filtering by dns when accepting mail from remote servers? Or is this server-side validation simply abandoned nowadays?

**Comment by flavorbiz** [comment]
Using 1and1, so whatever their setup is.

Bruce Roberts
330-310-9383

-----Original Message-----

**Comment by Valodim** [comment]
validating sending servers via dns is done with dmarc/spf+dkim these days

**Comment by 01BTC10** [comment]
In Postfix I had to change "reject_unknown_client_hostname" to "reject_unknown_reverse_client_hostname" so now it looks like this:
smtpd_helo_restrictions = reject_non_fqdn_helo_hostname,reject_invalid_helo_hostname,reject_unknown_reverse_client_hostname
