### ISSUE TITLE
Feature Request: Dead zone after buttons on bottom of screen

### ISSUE THREAD

**Issue by andrewc1** [k9mail/k-9#1403]
### Expected behaviour
There should be an option for a "dead space" underneath the K9 buttons so it's not right next to the bottom of the screen.

### Actual behaviour
My Samsung Galaxy S4 has buttons at the bottom of the screen. Whenever I go to press the "Back" button on the phone while in K9, I invariably hit the Create New Message button instead. Then I have to Menu -> Discard to get rid of the message I just accidentally created.

### Steps to reproduce
1. Start K9 and read a mail message
2. Try to hit "Back" on a Samsung Galaxy S4 with fat fingers.
3. You've just created a new draft!

### Environment
K-9 Mail version: 5.010

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
We'll get rid of the actions at the bottom of the screen in the redesign. But we certainly won't add an option just to add more space in certain areas.
