### ISSUE TITLE
Delete messages through notification (doesn't work, even if activated in settings)

### ISSUE THREAD

**Issue by deb10042** [k9mail/k-9#1404]
The current version of K9 (5.010) has several malfunctions/bugs in its notification function.
Could you please have a look into this section of K9 and fix these bugs in a new version?

### Expected behavior

With former versions of K9, it was possible, to delete any incoming mail directly from within its notification in the notification area, without opening K9 itself.
This is managed by
> global settings > notifications > show “delete” button > always.

### Actual behavior

My new device is a Samsung Galaxy S7, running Android 6.0.1 (Marshmallow). Here, independent of which setting I chose (“always” or “for single message notification”), it is no longer possible to directly delete incoming single mails through their notification. 

### Steps to reproduce

After several tests, I found out that the malfunction depends on the K9 **language settings** in
> global settings > display > language.

I put it together with several screenshots in the attached file.
[K9 notifications.docx](https://github.com/k9mail/k-9/files/281363/K9.notifications.docx)

If language of K9 is set to “**German**” (which is my country), there is no option for deleting mails from within their notifications.

Additional bugs when using “German” language setting:
- most often, the notifications even disappear from the notification area within 1 or 2 seconds and I have no chance to get information on incoming mails.
- if more than 1 messages have arrived in the same account, tapping on the notification always takes me to the latest incoming message, instead of going to the list of unread messages
account settings > notifications > notification opens unread messages (is active)

If language of K9 is set to “**English**”, I will be allowed to delete incoming mails from within their notifications, single mails as well as multiple mails.

Additional bug when using “English” language setting:
- if more than 1 messages have arrived in the same account, tapping on the notification always takes me to the latest incoming message, instead of going to the list of unread messages
> account settings > notifications > notification opens unread messages (is active)

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Device: Samsung Galaxy S7 (SM-G930F)

**Comment by philipwhiuk** [comment]
My guess is this is at least partially caused by Samsung's stupid handling of notifications. See: https://plus.google.com/107297237634342002591/posts/ZmfvRFVVypC for more on this

**Comment by deb10042** [comment]
Would it be possible to implement a workaround? e.g. An option to only show symbols in the notifications instead of text plus symbols?
This is very annoying, as I will constantly have to open each (spam) mail in order to be able to delete it.
Thanks!

**Comment by cketti** [comment]
The whole notification code will be different in the next major stable version. This most likely fixes everything but the display weirdness on Samsung devices. A fix for the display issue is tracked in issue #943.
