### ISSUE TITLE
Auto select identity based on X-Original-To / Delivered-To / X-Envelope-To / To / Cc

### ISSUE THREAD

**Issue by Kyoshiro-san** [k9mail/k-9#1407]
Hi,

I have a catchall domain and I use one address per service, with some I need to reply to. So I configured a few identities in K9Mail. Let's say I have configured default-id@my.domain and id2@my.domain and id1 is the default.

When I reply to a mail sent to id2@my.domain, k9mail selects default-id@my.domain as identity for the reply. I'd expect it to select id2@my.domain since mail was addressed to that email (visible in To/Cc sometimes, and always on X-Original-To in my setup).

There are multiple headers which can define the original email it was adressed to, but K9 could maybe match a few headers against the identity list ? Priority would be X-Original-To / Delivered-To / X-Envelope-To / To / Cc I suppose. Not sure if there are more potential headers doing this job.

Is it already done and I am missing something maybe ?
If not, consider this a feature request ! ^^

Thanks !
### Environment

K-9 Mail version: 5.010
Android version: 4.4.4
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
From a quick glance, this is currently based on the To and also Cc headers (see [relevant code](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/helper/IdentityHelper.java#L27)). I can't see a downside of also checking X-Original-To or Delivered-To, so we could simply add that.

**Comment by Kyoshiro-san** [comment]
Ah yes now I see it was happening on mailing list, where I don't appear in the To header.
That'd be great, thanks !

**Comment by Kyoshiro-san** [comment]
Oh yes, this would probably resolve my issue indeed ! :-)

Cheers

**Comment by icemc** [comment]
I would like to work on this

**Comment by icemc** [comment]
I would like to work on this

**Comment by vatsalsura** [comment]
@Valodim I can't actually understand the issue here. Can you please explain a bit more?

**Comment by rhari991** [comment]
Fixed by #2454

**Comment by Kyoshiro-san** [comment]
Thank you very much !
