### ISSUE TITLE
Attachment opening

### ISSUE THREAD

**Issue by votanak** [k9mail/k-9#1409]
### Expected behaviour
Don't open attachment after press on button "save"

### Actual behaviour
Attachments open after pressing on button "save"

### Steps to reproduce
1. 
2.
3.

### Environment
K-9 Mail version: 5.010

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange):
Exchange

**Comment by cketti** [comment]
This behavior will be changed in the next major stable release.
