### ISSUE TITLE
Multi-touch motionEvent drag-to-pan interferes with pinch-to-zoom in messageView 

### ISSUE THREAD

**Issue by cmeng-git** [k9mail/k-9#1412]
### Expected behaviour

Both drag-to-pan and pinch-to-move action should be able to operate simultaneously. See Gmail message view, web view on Android or earlier releases of k9 
### Actual behaviour

With 2-finger touch action, messageView support only drag-to-pan even when user does a pin-to-zoom action
### Steps to reproduce
1. In messageView, touch display with two fingers
2. Perform pin-to-zoom
3. messageView perform a drag-to-pan action instead of text zooming

To perform zoom, user must touch the screen with only one finger first to scroll locked the screen. Then with second finger touch and drag, then zoom can only happen. Both then the drag-to-pan is being disabled.
### Environment

K-9 Mail version: version 5 but probably earlier. Earlier version with database version 43 is working ok. 

Android version: KitKat

Account type (IMAP, POP3, WebDAV/Exchange): All

**Comment by cketti** [comment]
I believe this is no longer an issue.

**Comment by cmeng-git** [comment]
yes, the problem has been resolved.
