### ISSUE TITLE
Import setting using OI File Manager fails on a new device

### ISSUE THREAD

**Issue by nodje** [k9mail/k-9#1417]
### Expected behaviour
Expect to see my mail boxes configured

### Actual behaviour
msg: Failed to import any settings form settings.k9s

### Steps to reproduce
1. Export 
2. Import 
:)

### Environment
K-9 Mail version:
5.0.10 on import side 5.108 on export side
Android version:
5.0.2 on export 6.0 on import
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
K-9 Mail 5.010 can't import settings exported by newer versions of the app.

**Comment by nodje** [comment]
👍
