### ISSUE TITLE
Sync fails on Marshmallow

### ISSUE THREAD

**Issue by chillly** [k9mail/k-9#1419]
### Expected behaviour
Periodically K9 should sync folders automatically every x minutes (4 mins in my case)

### Actual behaviour
Sync becomes disabled after a period of time, usually a couple of hours. No notifications of new mail is then received. 

Is this related to Marshmallow Doze feature as some suggest (doze is off for K9 now - still stopps syncing)?

### Steps to reproduce
1. Start Phone as normal
2. Allow K9 to sync for a few hours
3. Notice that sync is disabled

### Environment
K-9 Mail version:
5.010
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by philipwhiuk** [comment]
If K-9 isn't whitelisted it's related to Doze - #857. If K-9 is whitelisted then it's still a duplicated of #970

Without a debug log this doesn't get us very far.
