### ISSUE TITLE
go to next unread message on delete

### ISSUE THREAD

**Issue by HenryMiller1** [k9mail/k-9#1421]
### Expected behaviour

When I read a message and hit delete I want it to go to the next unread message.
### Actual behaviour

When I hit delete it goes to some set of messages that I have already read.  Changing message thread settings doesn't change anything, and I can see nothing else on this subject
### Steps to reproduce
1. Have many messages in your inbox, some of which are read
2. open a new unread message
3. hit delete
4. k-9 will go to some other message, typically one already read.
### Environment

K-9 Mail version: 5.010

Android version:
6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
I believe this behaviour depends on whether you opened the view containing all messages or just unread messages. If you tap on the dot with the unread count and browse them there it will behave you want.
