### ISSUE TITLE
Share email to other apps doesn't send the header of an email

### ISSUE THREAD

**Issue by francwalter** [k9mail/k-9#1423]
### Expected behaviour
When I send an email to my printing app, or to any app, the header is missing.
Only the body is printed, but not the from, to, date and subject headers.

### Actual behaviour
k9mail just prints or sends the body of an email but not the (important) header.

### Steps to reproduce
1. I open any email and press the forward button and here I press the share submenu
2. I select my printer app (Dell Mobile Print), or any other app which can take this content
3. the preview and the print shows only the body of the mail / the shared content is only the body

### Environment
K-9 Mail version: 5.010

Android version: CM 12.1 on a Samsung Galaxy S4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP or POP3 (irrelevant)

**Comment by Valodim** [comment]
The "share" operation only shares the message body, which seems like the behavior most users would expect, and is also what other apps (messengers) generally do. A different use case would be to share/save the entire raw message, but that includes a lot of technical data (headers) and also doesn't cover your use case I think?

To cover all cases, I can imagine a dialog asking what to export, "Message Text / with Metadata / Raw Message", where the second includes typical user-faced headers (From/To/Cc/Date) in decoded format, and the latter is actual export of the email data.

**Comment by francwalter** [comment]
So this behaviour is then intended?
Then this issue is just a feature request.

The complete raw content of the email is not of need (normally) but always when I print an email on PC I want to print also from, to, date and subject. 
So maybe a setting could be done to setup  the shared data, all headers or only body.

**Comment by Valodim** [comment]
Yup. This is one of the cases where we have to be careful not to succumb to blind featurism, but this is a reasonable use case.

**Comment by cketti** [comment]
There's also a [printing API](https://developer.android.com/training/printing/index.html) in Android. Maybe we should just add support for that.
I'm not sure if there's a use case of sharing selected headers + decoded body except for printing.

**Comment by Valodim** [comment]
Makes sense. In that case, refer to #1062.

**Comment by francwalter** [comment]
I just looked into the code and found in 
_k9mail/k-9/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java:L3879_
the method **sendAlternate**
Hier I found several intents about these headers, e.g. **Intent.EXTRA_SUBJECT,** **Intents.Share.EXTRA_FROM** etc.
Maybe in k-9 all is present already and only the app does need to have the right intents to get these headers? And as the printing app doesnt use them the headers are not shown?
I am not a Android programmer to know enough about it, its just a guess.

But right, only to a printing app is seems senseful to add the headers. 
For other apps I think that gives no sense.

**Comment by francwalter** [comment]
The sendAlternate (here only the changed try-block) ould be like this:

```
                try {
                    Boolean mailWithHeaders = true;
                    Intent msg = new Intent(Intent.ACTION_SEND);
                    String quotedText = null;
                    String completeMail = "";
                    Date mailDate = message.getSentDate();
                    android.text.format.DateFormat df = new android.text.format.DateFormat();
                    String mailDateText = (String) df.format("yyyy-MM-dd hh:mm:ss", mailDate);

                    String allSenders = "";
                    String allRecipients = "";
                    String allRecipientsCc = "";

                    Part part = MimeUtility.findFirstPartByMimeType(message, "text/plain");
                    if (part == null) {
                        part = MimeUtility.findFirstPartByMimeType(message, "text/html");
                    }
                    if (part != null) {
                        quotedText = MessageExtractor.getTextFromPart(part);
                    }

                    msg.putExtra(Intent.EXTRA_SUBJECT, message.getSubject());

                    Address[] from = message.getFrom();
                    String[] senders = new String[from.length];
                    for (int i = 0; i < from.length; i++) {
                        senders[i] = from[i].toString();
                        allSenders = allSenders + "\n" + from[i].toString();
                    }
                    msg.putExtra(Intents.Share.EXTRA_FROM, senders);

                    Address[] to = message.getRecipients(RecipientType.TO);
                    String[] recipientsTo = new String[to.length];
                    for (int i = 0; i < to.length; i++) {
                        recipientsTo[i] = to[i].toString();
                        allRecipients = allRecipients + "\n" + to[i].toString();
                    }
                    msg.putExtra(Intent.EXTRA_EMAIL, recipientsTo);

                    Address[] cc = message.getRecipients(RecipientType.CC);
                    String[] recipientsCc = new String[cc.length];
                    for (int i = 0; i < cc.length; i++) {
                        recipientsCc[i] = cc[i].toString();
                        allRecipientsCc = allRecipientsCc + "\n" + cc[i].toString();
                    }
                    msg.putExtra(Intent.EXTRA_CC, recipientsCc);

                    if (mailWithHeaders) {
                        completeMail = "Gesendet am: " + mailDateText + "\n" + "Absender: " + allSenders + "\n" + "An: " + allRecipients + "\n" + "CC: " +  allRecipientsCc + "\n\n" + "Betreff: " + message.getSubject() + "\n" + "Body: " + quotedText;
                        msg.putExtra(Intent.EXTRA_TEXT, completeMail);
                    }
                    else {
                        if (quotedText != null) {
                            msg.putExtra(Intent.EXTRA_TEXT, quotedText);
                        }
                    }

                    msg.setType("text/plain");
                    context.startActivity(Intent.createChooser(msg, context.getString(R.string.send_alternate_chooser_title)));

```
with the need of a setting for **mailWithHeaders** which is here just true to test. Should be only true if this goes to a printer. Or maybe add another Share entry in the forward menu, e.g. "Share (Printer)".

**Comment by cketti** [comment]
If you want to propose code changes please open a pull request. That makes it easier to comment on the code.
However, we've established above that using the print framework is preferable to extending the Share mechanism. So the chances of an implementation of the Share approach getting merged are slim.

**Comment by francwalter** [comment]
exactly this for I dont do pull request :)

**Comment by philipwhiuk** [comment]
Wait what? You never print from Android but you opened a bug about not being able to print e-mail headers from K-9?

**Comment by francwalter** [comment]
Yes. I like it if an app is perfect.
And once I bet I want indeed to print an email even if I didn't need it since yet.
And yes, I like to dig in such problems and look into the code.
