### ISSUE TITLE
POP3: add authentication by RFC-2095 - MD5 CRAM-HMAC Request/Confirmation

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1425]
### Expected behaviour

When I configuring POP3 mailbox there is an option for "secure" authentication. I suppose it will support not only RFC-1734, but RFC-2095 too. My mailserver (mailbox) allow only this method of secure authentication. It is mandatory. So, I cannot use mail.
### Actual behaviour

Currently it supports only MD5 APOP Request/Confirmation (RFC-1734). So, I cannot use (receive) my mail using K-9. It's just cannot connect to my POP3 server with such options.
### Steps to reproduce
1. Setup mailserver and mailbox with RFC-2095 authentication method only.
2. Try to receive mail by K-9 using "secure" authentication, it will fail, because it will try to send "APOP" command, that is unsupported by server (you will receive error: "unknown command APOP")
### Environment

K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by ghsrcgh** [comment]
Two years passed - is any progress with that? :)

**Comment by cketti** [comment]
Obsolete because of #4974
