### ISSUE TITLE
Make an option "Show CC/BCC" field in options when you editing/composing new message

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1433]
### Expected behaviour
Make an option "Show CC/BCC" field in options when you editing/composing new message. Currently there is only an option "Request read confirmation". Add to menu "Show CC/BCC" fields. After taping on this, CC/BCC fields must be shown or hidden.

### Actual behaviour
Option: "Always show CC/BCC [ ]" - is not enough. Because I have no any methods to see these fields if this option is disabled, but I'm composing a new message or replying on message without CC-field in source message.

### Steps to reproduce
1. Just to create new message while "Always show CC/BCC [ ]" option is disabled.
2. Try to see CC/BCC, if you will need.

### Environment
K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
Pretty sure this has changed in the beta. You can tap a down arrow to show CC and BCC fields.

**Comment by cketti** [comment]
This issue no longer applies to the current development version.
