### ISSUE TITLE
Make option for notifications (about new mail) without details of the message - just short notification

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1435]
### Expected behaviour
Option for notifications (about new mail) to make them without details of the message - just short notification, that new mail arrived. (Short notifications for privacy purposes). (Like in AquaMail).

### Actual behaviour
Currently all details of the message are shown in the notification. I.e. anyone can read the message that I received.

### Steps to reproduce
1. Receive a mail and see notification area.

### Environment
K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
The options in the beta allow this to be configured for lock-screen notifications. Would this fix your issue?

**Comment by cketti** [comment]
Newer Android versions allow to specify what information is displayed in notifications on the lock screen. We won't add any privacy functionality beyond that.

**Comment by ghsrcgh** [comment]
But what about unlocked screen? If I do not want to guys near me to see notifications details? (I want to know about new mail arrive, but do not want to see details).
