### ISSUE TITLE
Add counter for new messages (unread) on the application's icon on the desktop

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1436]
### Expected behaviour
When new messages arrives, or there are unread messages, please show a counter for that messages on the application's icon on the desktop (like do all other apps like SMS, AquaMail, etc).

### Actual behaviour
There is no any counter on application's icon.

### Steps to reproduce
1. Receive any new message or stay some messages unread
2. Switch to desktop and see application's icon

### Environment
K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
K-9 has widgets to do this (not sure about current release, but it definitely exists on the dev branch).

**Comment by ghsrcgh** [comment]
It seems that two years passed and still nothing (as I understand).
