### ISSUE TITLE
Please allow resizing of "unread" widget, or provide 1x1 widget

### ISSUE THREAD

**Issue by nodens** [k9mail/k-9#1438]
Hi !

Apparently (at least on my LG G4 5.1 Lollipop with trebuchet as home app), the "unread" widget is always 1x2. It doesn't seem to need that much space (1x1 should be fine), and it's not possible to resize it.

It would be nice to have a resizable one, or at least 1x1 widget provided.

Cheers !

nodens

**Comment by philipwhiuk** [comment]
Fixed in the dev branch
