### ISSUE TITLE
Feature request: switch tp material theme

### ISSUE THREAD

**Issue by pyc0de** [k9mail/k-9#1440]
Great app!
Are you planning to give it a facelift?

**Comment by ocdtrekkie** [comment]
There's already two open discussions (#599 and #645) about the plans to ruin the app with Material. No need for a third.

**Comment by pyc0de** [comment]
sorry guys, didn't see this as 'ruin' plan.

**Comment by ocdtrekkie** [comment]
Just suggesting you search before you create issues. Since there's multiple talking about Material, you could've found out where the project maintainers' plans are for Material. (They are interested in Material, I am not.)

**Comment by jancborchardt** [comment]
Wow, how unwelcoming can you be to people opening issues @ocdtrekkie? And to top it off, in the comment attack people who put actual work in the app by saying they »ruin« it.

@cketti @obra @Valodim do you have a Code of Conduct? This would be quite good to keep toxic people out of such an important project and community. You are welcome to use our [Nextcloud Code of Conduct](https://nextcloud.com/community/code-of-conduct/) as a base.

**Comment by ocdtrekkie** [comment]
@jancborchardt People should do basic due diligence when opening issues, like searching for related issues. There are already MULTIPLE open issues on this topic. Given duplicate issues are regularly closed here with much less exposition than mine (see #1365), I don't see the problem.

Really, it just looks like you're trying to find a way to ban someone you disagree with.

**Comment by Valodim** [comment]
You're an obnoxious person, your opinion is misaligned with the people actually working on this project, and your overall contribution is clearly not positive. Please go away.

**Comment by pyc0de** [comment]
No problem, I should've searched for this first. I assumed that as almost all projects switched to material, k-9 is somehow ignoring it)
Cheers.

**Comment by Valodim** [comment]
The problem with material design isn't that we don't want to do it, it's that it's a *lot* of work, as in, hundreds of hours. It's not something we can just do on a weekend, it's something we have to plan and work on for months.
