### ISSUE TITLE
Missing inbox email

### ISSUE THREAD

**Issue by JvR1234** [k9mail/k-9#1445]
### Expected behaviour

I used k9 for my hotmail account. My inbox should display all new messages( up to 25).
### Actual behaviour

Since a few days there is a gap in my inbox messages (k9 mail). The inbox is showing from today up to 3th June this year, then all the next messages are from October 2008 and older.
### Steps to reproduce

1.I tried removing and installing again. Makes no difference.
2. I tried removing email on the server to make sure my inbox is not oversized.
3. Activated debug logging. Logging file will follow.
### Environment

K-9 Mail version:
V5.010

Android version:
4.4.2 (kitkat)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Please at least try to fill the form in.

And a debug log would be useful for this issue given it works normally.

**Comment by Anutrix** [comment]
Faced the same issue today. Turns out when you set the fetch email to 1000 or something, it fetches only recent one/two week and rest from over an year ago. On latest K9mail version on Play store.

Workaround was to set fetch limit as 'No limits'.

**Comment by kanlukasz** [comment]
I have the same problem as @Anutrix
