### ISSUE TITLE
Option to auto save locally decrypted gpg email (make all encrypted mails searcheable)

### ISSUE THREAD

**Issue by vsrinu26f** [k9mail/k-9#1446]
### Expected behaviour
I would like to have one option to auto decrypt mails with APG etc and save locally. (Reason: This should let me search locally all emails for some thing as we have every thing available decrypted.)
This helps secure email during transport from email providers and I don't bother much about my phone and k9 mail client security. This will be a great convenience and should help many adopt this.

### Actual behaviour
Finding to find an email using a text search thru all encrypted emails is difficult.
manually going thru each mail decrypt and see is difficult and inconvenient If I dont bother much about saving unencrypted locally in the sense that K-9 will use a encrypted container for all the mails together but all emails are saved plain text in that container.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
See #1450
