### ISSUE TITLE
Button to save decrypted locally inside k9mail on decryption of an email (make mail searcheable)

### ISSUE THREAD

**Issue by vsrinu26f** [k9mail/k-9#1447]
### Expected behaviour
I decrypt email and should be able to decide if I want to keep it that way or save it decrypted locally. when I say save it locally, I mean k9 should show the message unencrypted and should be able to find this email by text search of the content of this email.

### Actual behaviour
I decrypt an email then later time I open this email again I have to decrypt this email again. But I dont have an option to save it decrypted locally as this is not an email that needs to keep decrypted and only needs to reach me encrypted and now I dont need it encrypted anymore.

The advantage is that I can search thru emails and can find this. If this is encrypted I will not be able to search the content to find this email.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
In the past K-9 Mail saved messages in a different representation than the one on the server and it has caused a lot of issues. So we won't do that again.
I created issue #1450 to keep track of what you actually want, searching in encrypted messages.
