### ISSUE TITLE
Option to add keywords or tags to encrypted email to make them searcheable locally

### ISSUE THREAD

**Issue by vsrinu26f** [k9mail/k-9#1448]
### Expected behaviour
I would like to add some text lines to an encrypted email so that I can search and find that email.

These tags or keywords should stay locally within k9 and should be able to export/import to a text file to keep a backup and restore them later ( in case of changing phones etc.. )

users will use this feature where they still want to keep the email encrypted but ok with some metadata locally in k9 so that they can find that email later easily.

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Way too complicated. See #1450 for support of search in encrypted messages.
