### ISSUE TITLE
Ability to attach notes to inbox email

### ISSUE THREAD

**Issue by vsrinu26f** [k9mail/k-9#1451]
### Expected behaviour
Ability to attach notes to inbox emails, this notes is k9 feature and should not be sent to email servers. All notes should be exportable and importable in one go.

This can help in many ways. a simple scenario is attach a note to existing encrypted email recieved. we can search this email with text in notes.

as a todo process I can use notes to  write what I did and what is my progress etc reminders in the notes area.

I can also use notes as my own keyword or tags space.

I can just use it to enter some notes about client effectively using email as a simple CRM tool.
 
### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
K-9 Mail focuses on email. If you have a pull request for making it easier for third-party apps to integrate wit
