### ISSUE TITLE
Unable to SEND email 

### ISSUE THREAD

**Issue by 0833766747** [k9mail/k-9#1456]
### Expected behaviour
After creating new e-mail message or forward or reply to message, it should be SEND (through SMTP server)

### Actual behaviour
Messages remain in Outbox, received notification "Failed to send some messages." Detail: Negative SMTP reply: 450 4.1.2

PLEASE NOTE:
Due to my MAIL SERVICE PROVIDER being DIFFERENT from my INTERNET SERVICE PROVIDER, the problem is most probably related to the "Security Type" - nothing is working. Similar settings in Microsoft environment is using Security Type = Auto.

### Steps to reproduce
1. Setup POP3 (Receiving Server) mail account xxxxxxx@mtnloaded.co.za - working correctly!
2. Setup SMTP (Sending Server) result in error when trying to send message. SMTP server = smtp.vodamail.co.za; Security = None; Port = 25; Require sign-in = [not ticked]
3. I need to use different service providers for incoming and outgoing mail!!!! Gmail or Yahoo is not an option! I am paying both service providers for their services; I cannot change that due to existing clients.

### Environment
K-9 Mail version:
LATEST
Android version:
4.4.2
Account type (IMAP, POP3, WebDAV/Exchange):
Multiple, both POP3 and IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
