### ISSUE TITLE
HELP! - EXCESSIVE (!) data usage

### ISSUE THREAD

**Issue by BarryWoodward** [k9mail/k-9#1458]
K-9 mail has suddenly started using a colossal amount of mobile data and managed to use up ALL of my 1GB monthly allowance in 3 days flat! It never did this before - my average for a whole month has been 250MB across all the apps on my phone. I even set the data settings for the app under system settings to not use mobile data then went out this morning and it had used another 100MB anyway when I got back - even tho I've only had 40 emails! I have 4 accounts, all IMAP (one Apple @mac and 3 gmail) set to sync the last 2 months and only 32k of each email. What on earth is going on? I'm gonna have to ditch the app if I can't resolve this issue. 

Latest v5.010 on a Samsung Galaxy A3FU

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by BarryWoodward** [comment]
?? was just following orders...

On the Play website  at https://play.google.com/store/apps/details?id=com.fsck.k9&hl=en it says 

If you're having trouble with K-9, please report a bug at https://github.com/k9mail/k-9 …..

Maybe this needs updating?

Kind regards

Barry Woodward
London

**Comment by cketti** [comment]
Well, it probably is a bug in K-9 Mail. But without more information we're never going to find it. From experience I can say that it's unlikely someone who reads the bug tracker will have the energy to work with you to narrow down what could trigger the bug. A lot more people read the mailing list and someone might be able to help.
