### ISSUE TITLE
I changed gmail to allow only secure logins, & now K-9 cannot login via either ssl/tls or STARTTLS, Thunderbird can login via Oauth..

### ISSUE THREAD

**Issue by libweirdness** [k9mail/k-9#1460]
### Expected behaviour
This is in 5.010
K-9 should have maximally-secure login methods, all of them, and should try them in sequence,
from the hardest to the softest security,

and should never use an insecure login tech without
a) first exhausting all other alternatives, &
b) getting explicit permission from the user to vulnerablize their credentials that way, while logging-in, &
c) ANY change in the security-situation ( ssl becoming unrecommended, as i remember happening a few years ago, eg ), and that module being re-jigged immediately to protect us against violation as much as possible.

( i remember reading that ssl is now untrustworthy and TLS is recommended, but have no idea if the initial setup is secure in TLS, or if the problem is simply Google acting like Microsoft and disallowing standard protocols/methods as a monopoly-pushing means making its apps the only "secure" ones users can know/see/have...

I hate the gmail app, and want to use K-9,
 but having my email compromised??
 -shudder- )

### Actual behaviour
*After telling gmail to not allow any insecure logins*,
neither K-9 nor Thunderbird could login
In Thunderbird i discovered setting it to Oauth fixed things, but there are only 2 choices in K-9, neither of which works.
Account Options / Account Settings / Fetching Mail / Incoming Server
STARTTLS produces..
( NOW i discover there is an EncryptedPassword option? It was hidden under the keyboard, and the Next button i used suggested nothing under the keyboard...
..oh, well, that didnt work anyways! )
"Cannot connect to Server.
Unable to Connect"

When i try SSL/TLS, the result is
( again using the *user-set* option, which should have been automated: Encrypted Password )

Cannot connect to Server.
(Server doesnt support passwords encrypted using CRAM-MD5)

### Steps to reproduce
1. Change gmail acct to disallow insecure apps logging in
2. A few hours later discover K-9 no longer is getting gmail
3.try diff settings and discover none work.

### Environment
K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP): gmail imap

**Comment by cketti** [comment]
See issue #655.

Google calls apps that don't support OAuth "less secure". That doesn't make them insecure.

**Comment by libweirdness** [comment]
By committing K-9 to that path, instead of adding OAuth,
You make the market feel-need to abandon K-9 for security-reasons, due to Google's monopolistic move.

Gmail app isnt blocked for OAuth requirement, but K-9 is.

If Google is falsely indicating that the login methods without OAuth are insecure, 
Either adapt, or allow Google's position to indicate K-9 WONT be made secure, whether objectively-true or not.

Evolution-requirements are never fair to minorities.

If AdaptOrDie-situation mixes with an Adopted Political Position that extinguishes a species/project's viability, 
maybe having made A Statement was better than changing the world?

Pointless choice, to me...

Cheers ( deleting K-9 from my devices & telling others to continue defaulting to Maximal Security, even when some providers insist there is some technical-eror in 1 or another such policy )

**Comment by Valodim** [comment]
that's quite the attitude you have there. you did notice the "see #665"? and maybe even the" duplicate" label? we are aware of this issue and there is working code for it, it's just not done.

**Comment by libweirdness** [comment]
Having now read the other issue, it looks like Google will prevent any non-Google app from having real security...

( authority theatre instead )

I dont know what the real ranking of security of login methods is, and am obviously incompetent to comment an anything anyways.

It does look like they are now Microsofting their users.

...

As for my attitude: i hope to fuck that someone splats my brains out for having consistently MISTAKENLY tried to contribute in this world, this fucktarded life!

Cheers.

**Comment by philipwhiuk** [comment]
> Having now read the other issue, it looks like Google will prevent any non-Google app from having real security...

No, you just have to use the OAuth 2 methods to get a token. The app is then associated with your account based on the application ID. It's not overly complex, it's just a bit fiddly testing all the edge cases.
