### ISSUE TITLE
Lacking an option about notifications

### ISSUE THREAD

**Issue by Whateverman2012** [k9mail/k-9#1464]
### Expected behavior
After clicking a mail notification it should go to a corresponding account of our choice.
Either source or unified.

### Actual behavior
It goes only to source.
It may be useful to have an option in global parameters to choose the target folder once a notification is clicked

### Environment
K-9 Mail version: 5.010

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
No, we already have too many options.

I have something else in mind. But it'll be a while until we get to that.
