### ISSUE TITLE
No push for outlook account

### ISSUE THREAD

**Issue by blakkmaan** [k9mail/k-9#1470]
### Expected behavior
Get a push notification if a new mail arrives in the inbox
### Actual behavior
Nothing. 

### Steps to reproduce
1. Set up an outlook.com account as imap
2. Set up push and checked the foldersetup 
3. Set renew push connection every 6minutes
4. Send an email from another account to my outlook.com account
5. Wait but nothing happens
6. With the gmail account push works fine with same settings.

### Environment
K-9 Mail version: latest 5.010

Android version: 6.0.0

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by philipwhiuk** [comment]
outlook.com doesn't support PUSH over IMAP.
