### ISSUE TITLE
Cannot install K-9 Mail v5.109 (alpha) apk

### ISSUE THREAD

**Issue by protist** [k9mail/k-9#1474]
### Expected behavior
I should be able to install K-9 Mail v5.109 (alpha) apk.

### Actual behavior
I get a generic error: `App not installed.`

### Steps to reproduce
1. Download apk.
2. Attempt to install it.
3. Have it fail… download it a few more times just in case it was corrupted; it still fails.

### Environment
K-9 Mail version: I currently have v5.010 installed, via F-droid.

Android version: 5.1.1 (Cyanogenmod 12.1-20151117-SNAPSHOT-YOG7DAO1KI-d802)

FWIW I'm attempted to upgrade to use PGP/MIME support. The current issues are a bit vague, but there's some suggestion that it's been fixed. However, the more-recent release, 5.010 still doesn't support PGP/MIME. Does the alpha support it?

Further, my current install of K-9 was via F-droid. Do I need to uninstall this version first? I'm worried that my email and settings will be deleted if I do so.

**Comment by cketti** [comment]
You can't upgrade installations from F-Droid with our APKs due to different signatures.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by protist** [comment]
Thanks for the information. Apologies, I will post there in the future.
