### ISSUE TITLE
Selecting multiple emails, then running an action applies the action only on the last email selected...

### ISSUE THREAD

**Issue by liar666** [k9mail/k-9#1475]
### Expected behavior
Tell us what should happen
1- be in a "window" showing multiple emails
2- long "clic" on an email + Select in 'popup' menu
3- long "clic" on another email + Select
4- long clic on any email + "mark as read" (or any action)

should apply the action ("mark as read") on all selected emails...

### Actual behavior
Tell us what happens instead
Action is run only email selected at step 3...

### Environment
K-9 Mail version:
Probably latest... I don't see any entry in any K9 menus to get this information...

OK found it in Android's menus: 5.01, but remark above still relevant: this info should be easily accessible from *within* K9 

Android version: 4.4.2

**Comment by cketti** [comment]
Long-press actions only affect the one item. Use the actions in the action bar to affect all selected messages.

**Comment by liar666** [comment]
Hi, thanks for the answer.

I might be the only one, but I find this behavior quite counter-intuitive (actions on the same elements are split in two different menus)...
Also, the icons at the bottom are no very self-explained... And once clicked, they execute their action, even if the user does not know which one and it cannot be undone :{

**Comment by liar666** [comment]
Hi, thanks for the answer.

I might be the only one, but I find this behavior quite counter-intuitive (actions on the same elements are split in two different menus)...
Also, the icons at the bottom are no very self-explained... And once clicked, they execute their action, even if the user does not know which one and it cannot be undone :{
