### ISSUE TITLE
Unable to find which email has not been sent

### ISSUE THREAD

**Issue by liar666** [k9mail/k-9#1477]
### Expected behavior

Tell us what should happen
1. disconnect the phone from any internet connection
2. write & send an email
3. K9 will complain about email not being sent
4. Do not resolve the problem by lack of time
5. reconnect & use phone as usual for some time
6. reopen K9 a few days/weeks later and discover that there is still an error
7. try to find what email is the source of the error and fail by lack of information from K9's error messages
### Actual behavior

Tell us what happens instead

K9's error messages should point to the message that is the source of the error (or at least the directory that contains the erroneous message). Or, at least, clicking on the notification should point to the erroneous email
### Environment

K-9 Mail version: 5.010

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Check you Outbox folder.

**Comment by liar666** [comment]
OK found it, thanks!

I would suggest 2 improvements:
1. When clicking on the error notification in Android's top "menu", redirect the user directly to this Outbox directory
2. When an email from this Outbox directory is clicked/opened, propose an "edit" menu entry instead of forcing users to use "forward" action and manually edit a lot of stuff...

**Comment by cketti** [comment]
See #1362
