### ISSUE TITLE
Date format not recognized

### ISSUE THREAD

**Issue by chiefbrain** [k9mail/k-9#1480]
### Expected behavior
The date of the email header "Date" should be displayed.

### Actual behavior
The date when the mail was synced is shown.

### Steps to reproduce
Have a mail which date format is the following:Tue, 01 Dec 09 02:37:10 MET

### Environment
K-9 Mail version: 5.010
Android version:5.1.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Additional informations:
Mails in format Tue, 01 Dec 09 02:37:10 +0100 (MET) are working fine.
Mails on the server can be identified by `grep -LZE "^Date: .* ((\+)|(\-)){1}[0-9]{4}" * -r | xargs -0 grep "Date: "`

**Comment by cketti** [comment]
See #1356
