### ISSUE TITLE
auto-completion of email addresses

### ISSUE THREAD

**Issue by liar666** [k9mail/k-9#1481]
this is more a feature request than an issue...

would it be possible to auto complete new-email's TO/CC/BCC fields based on senders/receivers of already pulled and locally stored emails ?

Indeed, I like K9 because it allows me to send/receive emails without requiring to be linked to my device's gmail account, thus saving part of my privacy.

Also, my 'contacts' do contain only minimal infos about my friends (in case the device would be robbed and to protect their privacy against Google).

In such a context, k9 does not provided any auto completion :(

**Comment by Valodim** [comment]
This is already in the current alpha, and will be in the next stable release.

**Comment by bokkiedog** [comment]
I am running the latest alpha and can find this auto-completion from mail addresses harvested from within NO nowhere.

Could you please give precise instructions on how to access this feature that you say was enabled over a year ago?

**Comment by optimdevel** [comment]
It works with phones address book, so this is not what everyone wants.
I am finally moving away from K-9 because if this reason. :-(

**Comment by fabeit** [comment]
> 
> 
> It works with phones address book, so this is not what everyone wants.
> I am finally moving away from K-9 because if this reason. :-(

Same here, this is an incredibly useful feature.

**Comment by felagund** [comment]
Could this be reopened, please? It really is driving me crazy, I e-mail a lot of people who are not in my contact list. And the original issue has never been fixed.

**Comment by derlui** [comment]
+1
