### ISSUE TITLE
libos-compat.so

### ISSUE THREAD

**Issue by herbert777** [k9mail/k-9#1482]
Hi!
I have built K9 from source and it has been very easy since the source is very clean and well organised, thanks to you!
Then I wanted to build libos-compat.so, but its source isn t in K9's, all there is in K9 is an already compiled version.
I downloaded SafeContentResolver-0.1.0 and built it, but the resulting file is much bigger than the one you use in K9 (70 kb whereas yours is only 9 sommething kb). 
The file is built within the SafeContentResolver-v14.aar and that s probably why it s heavier, the README file says that v21 is much lighter. But, impossible to have it to build with v21...
Or maybe your file is smaller because you used only part of it for K9, with the ABI options?
The thing is that I searched and I searched and I could t find anywhere how to build that lib the K9 way.
Would you mind sharing the way you did it?
Thanks in advance!

**Comment by cketti** [comment]
Maybe you created a debug build of the library.

Building the SafeContentResolver libraries with Gradle is straight-forward: `./gradlew assembleRelease`

**Comment by herbert777** [comment]
Of course building the SafeContentResolver libraries with Gradle is straight-forward, I know how to use ./gradlew assembleRelease:-)
Anyway, I followed your advice and in V21's build.gradle I added:
buildTypes {
        release {
            minifyEnabled false
			debuggable false
			}
        }
but no libos-compat got built.
Then, again in V21's build.gradle,  I added:
	    ndk {
            moduleName "os-compat"
        }
and the libos-compat got built in v21, but she's heavier than the one you use in K9 so it's still the same because, in case it wasn't clear, the problem isn't that it doesns't build, the problem is that it builds but the resulting libos-compat.so is much heavier than the one you use in K9 (70 kb whereas yours is only 9 something kb).
