### ISSUE TITLE
[Enhancement] Improve Spam Detection and include more grainular options for spam filtering. 

### ISSUE THREAD

**Issue by mikeloeven** [k9mail/k-9#1490]
### Expected behavior
Functional spam filter with reasonable detection rates.

### Actual behavior
Substantial amounts of obvious spam and sexually explicate emails are making it into my unified inbox. 
messages of the type that are easily caught by most desktop email clients. 
marking messages as Spam does not seem to provide any benefit in terms of training or improved recognition.

### Steps to reproduce
Use an IMAP email service that lacks internal server-side spam filtering.
Mark Such Messages as Spam

### Environment
K-9 Mail version: 5.101

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by jandechent** [comment]
That would be great. Eg my mail provider (posteo.de) encrypts mails and (claims) to not scan the mails. Consequently they don't have a spam filter. Since I don't want to have my PC running all yhr time - where spamadsasin could do the job - my phone is running all the time.

**Comment by cketti** [comment]
See issue #1508
