### ISSUE TITLE
Feature request: poll when wifi connection becomes available

### ISSUE THREAD

**Issue by jan-gerard** [k9mail/k-9#1499]
### Expected behavior
When a new WiFi connection is made (from a formerly Mobile connection), poll the mailboxes (when 'Poll when connecting for push' is enabled).

### Actual behavior
Now, 'Poll when connecting for push' always polls, also when the connection changes from WiFi to Mobile. This consumes a lot of data when the WiFi connection drop regularly. From Mobile to WiFi, there is no data penalty.

### Steps to reproduce
1. Enable 'Poll when connecting for push'.
2. Connect to WiFi
3. Disable WiFi
4. K9 starts polling

### Environment
K-9 Mail version: 5.010

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
I'm all for making Push more energy-efficient. But I don't think this particular suggestion is the way to go.
