### ISSUE TITLE
'Mark all as read' action cannot be configured as the one that requires confirmation

### ISSUE THREAD

**Issue by vthriller** [k9mail/k-9#1509]
### Expected behavior
Confirmation dialog pops up.

### Actual behavior
OMG ABSOLUTELY EVERYTHING IS MARKED AS READ MY DAY IS RUUUUINED

### Steps to reproduce
1. Smash 'Mark all as read' by accident

### Environment
K-9 Mail version: 5.010

Android version: any

Account type (IMAP, POP3, WebDAV/Exchange): any

**Comment by Valodim** [comment]
Sounds reasonable. Done in #1522
