### ISSUE TITLE
Add support for message part deletion

### ISSUE THREAD

**Issue by madduck** [k9mail/k-9#1517]
At least mutt allows me to delete individual MIME message parts, e.g. large image attachments, and to store the message with a replacement note ("this image has been deleted on yyyy-mm-dd"). It would be cool if K9 let me do this too as I otherwise often have to wait to get back to mutt before I can archive a message with a huge attachment that I do not need to keep.

**Comment by cketti** [comment]
I don't consider this a common or important use case and hence don't want to include it in K-9 Mail. However, I am not opposed to our interface for third-party apps supporting creating messages. That should be enough for an app to provide the requested funtionality.
