### ISSUE TITLE
ISSUE: Puzzling behavior with creating Yahoo accounts in K-9: v5.010 and Android: v6.0.1

### ISSUE THREAD

**Issue by acaramagno** [k9mail/k-9#1531]
### Expected behavior

I have two Yahoo email accounts:

xxxxxxxxxxxxxxx@yahoo.com
xxxxxxx_xxxxxxxxx@yahoo.com

Both have the same password.

You would expect that both accounts would be created in K9-Mail.

### Actual behavior

xxxxxxxxxxxxxxx@yahoo.com

works and

xxxxxxx_xxxxxxxxx@yahoo.com

fails.

### Steps to reproduce

I created both accounts in K-9 Mail using:

INCOMING:

IMAP server: imap.mail.yahoo.com
Security: SSL/TLS
Port: 993
Username: [email name]@yahoo.com
Authentication: Normal password
Password: ***************
Auto-detect IMAP namespace: Checked
IMAP path prefi: <blank>
Show only subscribed folders: Unchecked
Use compression on network: All checked (Mobile, Wi-Fi, Other)

OUTGOING:

SMTP server: smtp.mail.yahoo.com
Security: SSL/TLS
Port: 465
Required sign-in: Checked
Username: [email name]@yahoo.com
Authentication: Normal password
Password: ***************

### Environment
K-9 Mail version: v5.010

Android version: v6.0.1 on Nexus 6P

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
