### ISSUE TITLE
unable to paste text in email body

### ISSUE THREAD

**Issue by craftyguy** [k9mail/k-9#1533]
### Expected behavior
When text has been copied to the clipboard, long pressing in the email body when composing a mail should show the option to paste.

### Actual behavior
There is no option to paste text when long pressing

### Steps to reproduce
1. Compose mail
2. Copy text either from the mail or from any other app on the device
3. Long press in the mail to paste it, no option to paste

### Environment
K-9 Mail version: 5.110

Android version: CyanogenMod 13, Android 6.01

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![screenshot_20160731-101408](https://cloud.githubusercontent.com/assets/1474209/17278070/1ccc5444-5708-11e6-85d7-26c45e6fc4dd.png)

**Comment by cketti** [comment]
Works for me. Maybe some other app is clearing your clipboard?

**Comment by craftyguy** [comment]
Sorry for the false alarm, I figured out that it was Privacy Guard in CyanogenMod that was blocking clipboard access to K9.. Sigh.
