### ISSUE TITLE
K-9 mail and letsencrypt

### ISSUE THREAD

**Issue by mikoladz** [k9mail/k-9#1534]
### Expected behavior
K-9 connects with an IMAP or SMTP server with a certificate issued by letsencrypt.org without any problems.

### Actual behavior
K-9 when trying to connect to an IMAP or SMTP server with a certificate issued by letsencrypt.org returns an invalid certificate warning and asks to accept or decline it.

### Steps to reproduce
1. Add any IMAP or SMTP server with a certificate issued by letsencrypt.org and try to connect.

### Environment
K-9 Mail version:
5.010
Android version:
5.1.1 (CM12.1)
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
Do you have an example smtp server we can connect to (no credentials required, tls happens before auth)? Probably easier this way than searching for one :)

**Comment by gdt** [comment]
I would expect the set of trust anchors to be a system configuration, not a K-9 configuration.  Do other apps accept letsencrypt-issued certs?  Is the LE CA (or more likely a parent CA) in the system trust anchor list?

**Comment by vt0r** [comment]
It is indeed a system issue if those certs show up as invalid. I've been using LE certs on my own mail server since they entered public beta. My server's hostname is mail.shellvatore.us, and you can test using port 143 for IMAP with STARTTLS.

**Comment by mikoladz** [comment]
OK, you are right, this is my fault. Before using LE's certificates I was using self signed ones and the "trust all certificates" option in another client. Then I installed LE's certificates but badly configured the server and did not notice this because of the "trust all" option. Now I have configured everything properly and all problems are gone. I am sorry for bothering and thank you for your work.

**Comment by andrixnet** [comment]
One importand detail: one must configure the email server properly with the Letsencrypt certificate AND the CA certificate. 
I've found that using stunnel to SSL pop3/imap to popa3d and imapd you must provide stunnel with the full chain cert file (file containing both your certificate and the CA certificate)
