### ISSUE TITLE
Context menu size and location changes, but not for more readability

### ISSUE THREAD

**Issue by rjkmadison** [k9mail/k-9#1544]
### Expected behavior
Long-press on message and the menu should appear in a good location and readable.
This is in a non-split screen mailbox view.

### Actual behavior
The messages closer to the top of the screen pop menus further down the screen, until it is almost unusable in the lower-right corner.

### Steps to reproduce
(see screenshots)
1. Long press on a message in the lower part of the screen. The menu appears as you'd expect.
![screenshot_20160804-072344](https://cloud.githubusercontent.com/assets/6990222/17407111/b721e560-5a2b-11e6-8ce4-774351aef63f.png)
2. Long press on a message at the top of the screen. The menu is down in the lower-right corner.
![screenshot_20160804-072405](https://cloud.githubusercontent.com/assets/6990222/17407117/bc79339c-5a2b-11e6-970f-e7c49514a860.png)
3. See the difference in the menu usability

### Environment
K-9 Mail version: 5.010

Android version: Android N Preview 5 on Nexus 5x

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We don't position the popup ourselves. This is most likely a bug in your version of Android.

**Comment by rcorre** [comment]
I'm seeing this with 5.010 on a Nexus5x with Android 7.0 (pretty sure it didn't happen with Android v6). Can K9 influence the dimensions? Should it be reported upstream?

**Comment by rcorre** [comment]
Sorry, ignore that. Just realized #1581 addresses my question.

**Comment by Ollik27** [comment]
Android 7 nathinn

Am 22.09.2016 7:25 nachm. schrieb "Ryan Roden-Corrent" <
notifications@github.com>:
