### ISSUE TITLE
Add ability to 'snooze' or 'postpone' notifications for a given new mail

### ISSUE THREAD

**Issue by craftyguy** [k9mail/k-9#1549]
This enhancement request is inspired by Google Inbox's "snooze" feature, where users can choose to snooze a new mail causing the app to hide the mail and then display it as 'new' (as if it were just received) at some user-configurable time in the future.

**Comment by cketti** [comment]
Google created a separate app for this interaction model. I don't think it can be implemented on top of a regular email client without a lot of work.
This is very very low priority at best. Closing the issue because it's unlikely we'll get to it in the next 2-3 years.

**Comment by craftyguy** [comment]
There was MUCH more to the "Inbox" app than just merely snoozing emails, so you're lying to yourself if you think they wrote it just for that one feature. Anyways, the "k-9 gods" have spoken. Womp womp.

**Comment by Valodim** [comment]
What's with the attitude? He never said Inbox was only for that feature, neither did he even disagree with you. Please be aware that you are asking people to do stuff in their free time here. And of course, you'd be welcome to implement it yourself if you care, if it's well done we would likely merge it.

**Comment by guettli** [comment]
Yes, google Inbox has many more features. But for me I just want one feature:

` +N`

Meaning this: move this mail to a subfolder for N days. After N days put it into my IMAP-inbox again.

I guess it is not very hard to implement. 

Is there a way get this done?

I would pay for it.

**Comment by Valodim** [comment]
There is some work on this in #1849

**Comment by guettli** [comment]
Just for the records. I ask myself "what is the best way to store additional data per message?".

I asked the question on StackOverflow: http://stackoverflow.com/questions/41757915/storing-additional-data-to-mail-in-imap
