### ISSUE TITLE
customize actions list in notification and message list bottom bar

### ISSUE THREAD

**Issue by wwp** [k9mail/k-9#1562]
There's already a 'show delete button' for notifications, and a 'visible message actions' but there's no real way to configure what actions/buttons are present in the notification banners and in the bottom actions panel (message view menu).
About the message list bottom bar, for instance (not in multi-selection mode), I don't care about the search or sort actions, but I do about the mark-all-read, mark-as-spam and delete actions, but K-9 mail doesn't allow customizing this. Same for the notification banners.

**Comment by cketti** [comment]
See #611 and #943
