### ISSUE TITLE
[feature suggestion] possitibility to input any checking account interval in minutes

### ISSUE THREAD

**Issue by naox** [k9mail/k-9#1563]
In k9mail you can set pop3 account to be checked every 1 or 5 or 10 or 15 ... minutes. That is very large increase. Between 1 min -> 5 minutes is 500% increase. I would like to set it to 2 or 3 minutes since 5 is too much and 1 drains battery and increases network usage too much. There is no option to do this. Please implement option to type in any interval in minutes.

**Comment by wwp** [comment]
The possibility to freely edit the refresh interval value is, to me, the best situation (w/ whatever default value you want). Boundaries could be set to [1..int limit], no need to force people to 1-day or whatever.

**Comment by cketti** [comment]
Allowing users to configure arbitrary intervals would make our code unnecessarily complex. With the power optimizations on modern Android versions the interval is more of a rough guideline anyway.
