### ISSUE TITLE
Unable to sync all messages from hotmail

### ISSUE THREAD

**Issue by Or0ph3r** [k9mail/k-9#1567]
Hi, since yesterday (15th of August) I've had trouble with k9-mail, when i went to check my mails I was unable to see them all on my hotmail mailbox. Gmail works fine.
I did not do anything particular on the app. I just didn't open it in the couple days before, but I saw the notifications (I had like 11 emails). On the morning of the 15th, I saw one notification for a new message, and when i launched k9 I only got this one, prior to that date mails won't show up.
### Expected behavior

K9 should sync my messages when I press the "load up to 25 more" button. My mailbox is full of mails, i've got at least one per day, so the list should be full with my last 25 emails.
### Actual behavior

K9 doesn't sync messages prior to 15-Aug-2016, even though in settings it's set to sync messages from "the last 2 weeks"
Worth noting: this issue is only with my hotmail account, I've got a gmail one and it works perfectly
### Steps to reproduce
1. Cleared messages from my hotmail account
2. Clicked on my hotmail account and pressed "load up to 25 more" to force sync
3. Messages sync, but not all of them

I tried clearing the local data of k-9 mail, so i reconfigured my two account (hotmail and gmail), but the issue is still there, and only still on the hotmail account.
### Environment

K-9 Mail version: 5.010

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): Hotmail, IMAP
###### 

K9log : http://pastebin.com/HzDvqSbe

I believe the issue is seen in line 2369, the search value should not return that few messages

**Comment by cketti** [comment]
"This is a private paste. If you created this paste, please login to view it."

You can attach files to Github issues by dropping them into the box that contains the text "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."

**Comment by Or0ph3r** [comment]
Sorry, did not see that as i was logged on pastebin
Here is the log :
[k9-log.txt](https://github.com/k9mail/k-9/files/453849/k9-log.txt)

**Comment by Or0ph3r** [comment]
Sorry, did not see that as I was logged on pastebin
Here it is : 
[k9-log.txt](https://github.com/k9mail/k-9/files/453850/k9-log.txt)

**Comment by cketti** [comment]
Might be caused by issue #1074.

Try deleting the account, setting it up again and never delete all of the messages in the Inbox. Chances are the UIDVALIDITY value won't change unless the folder is empty.

**Comment by unicorn622** [comment]
I also have the same problem since today. Everything between 18.08.2012 and today (29.09.2016) doesn't appear in the list. I had version v5.010 when the problem occured. Deleting the account and readding didn't solve the problem. Deinstalled the app, installed the latest alpha v5.111 and added my account: same problem. 

(I also use Thunderbird and i don't have problems with it.)

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the current K-9 Mail version.
