### ISSUE TITLE
Email with empty text

### ISSUE THREAD

**Issue by AF340** [k9mail/k-9#1569]
### Expected behavior

Email coming from orange or sfr app are empty, no text inside.
### Actual behavior

If i open the same email with my webmail, it can be read with the text, without issue.
### Steps to reproduce
1. Ask to a friend to send you an email from orange or sfr app ;)
   2.
   3.
### Environment

K-9 Mail version:last

Android version:
5.0
Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by wwp** [comment]
I do receive emails sent from Orange accounts, no problem here. I'm
afraid you'll have to me more precise, are they sending HTML or plain
text emails? Signed? How are they sending these emails, from the Orange or SFR web mailer or from another app? Attaching a sample email file would probably help.

**Comment by wwp** [comment]
I do receive emails sent from Orange accounts, no problem here. I'm
afraid you'll have to me more precise, are they sending HTML or plain
text emails? Signed? How are they sending these emails, from the Orange or SFR web mailer or from another app? Attaching a sample email file would probably help.

**Comment by AF340** [comment]
Ok, to which @ i should forward the email?

Le 20 août 2016 20:59, "Tristan C." <notifications@github.com> a écrit :

>

> I do receive emails sent from Orange accounts, no problem here. I'm
> afraid you'll have to me more precise, are they sending HTML or plain
> text emails? Signed? How are they sending these emails, from the Orange
or SFR web mailer or from another app? Attaching a sample email file would
probably help.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/k9mail/k-9/issues/1569#issuecomment-241217507>, or mute
the thread

**Comment by philipwhiuk** [comment]
If you can forward it to me (philip at whiuk dot com) as an attachment I'll take a look.

Thanks!

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the current K-9 Mail version.
