### ISSUE TITLE
Mails deleted from folders when first sync

### ISSUE THREAD

**Issue by cdancette** [k9mail/k-9#1571]
### Expected behavior

When I send a mail, it goes to the local "Sent" folder. If this folder is not synced with the server, when I sync it, it should download mails from the server and save the local mails.
### Actual behavior

When I sync the local folder, I get mails from the server, but the local mails are just deleted from my phone, and not uploaded to the server

The same happens when I deleted a mail from my inbox : It went to the Deleted folders, and when I synced the Deleted folders, my mail disappeared from my mobile, and from the server.
### Steps to reproduce
1. Ensure the Sent folders was never synced
2. Send a new mail
3. Sync the Sent folder
4. The sent mail has disappeared
### Environment

K-9 Mail version: 5.010

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
There's most likely something wrong with your server. Please record a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) when sending a message and then syncing the Sent folder.
