### ISSUE TITLE
PC app/programs

### ISSUE THREAD

**Issue by hungryfat92** [k9mail/k-9#1574]
i am loving the k9 app you have for the android phone. nmy question is do you have any plans for k9 mail access on PC for Linux/other? Sorry if the question has already been asked but i couldn't find it

**Comment by cketti** [comment]
No plans. In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for questions like these.

**Comment by hungryfat92** [comment]
Okay thank you and sorry for using the wrong contact info.
