### ISSUE TITLE
[feature suggestion] transfer mail between account

### ISSUE THREAD

**Issue by zafriryak** [k9mail/k-9#1576]
In the app I can move mail only in the same account between folders.
I thought to add a feature for moving mail between different accounts.

So my question is what are you thinking about it
if it possible because i didn't saw it in any android mail app and it is exists in outlook and ios 
if you think i can make it what do you suggest me to study first for making this feature.

Thanks in advance zafrir.

**Comment by cketti** [comment]
Same as #760
