### ISSUE TITLE
Application crashes when replying to an email

### ISSUE THREAD

**Issue by emilhuseynli** [k9mail/k-9#1578]
### Expected behavior

New editor should be opened to enter reply message.
### Actual behavior

Application crashes directly after clicking on Reply menu item.
### Steps to reproduce
1. Open arbitrary email message
2. Click on a button with an arrow on the bottom of the screen
3. Select Reply from pop-up menu
### Environment

K-9 Mail version:
5.110 (Beta)

Android version:
6.0.1 (Samsung Galaxy S5 SM-G900FD)

Account type (IMAP, POP3, WebDAV/Exchange):
Gmail IMAP

**Comment by Valodim** [comment]
This information is too general to work with. Please try to obtain a log of the crash: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by emilhuseynli** [comment]
Here is the output of logcat:  [k9-log.txt](https://github.com/k9mail/k-9/files/437881/k9-log.txt)

I think I understand now why crash occurs. Actual issue is that some emails are downloaded and/or saved unproperly on storage. And when such email is to be opened in Reply screen there's a FileNotFoundException which is not handled properly. By the way, all email examples which cause the crash are also don't display properly (only subject, body completely invisible) when I open them. And also, I can confirm, that messages with no remote content (be it plain text or html) doesn't have the issue.

**Comment by emilhuseynli** [comment]
Here are the [headers_of_sample_email.txt](https://github.com/k9mail/k-9/files/437926/headers_of_sample_email.txt)

**Comment by emilhuseynli** [comment]
Here is an update to the issue: I have set storage for an account to external (SD-card) some time ago, but now switched back to internal storage and problem doesn't exist anymore.

**Comment by Valodim** [comment]
Ah, now that is good info. Do you actually have an sd card connected to your device?

**Comment by emilhuseynli** [comment]
Well, yes, I have a physical sd card and it's connected, but.. I noticed, that even if the option 'External (SD card)' checked in the menu, app data is still stored on internal eMMC card, and not on physical removable card. With the 'Internal' menu setting, app data is stored under /data/data. This is also the case in stable release.

**Comment by philipwhiuk** [comment]
See: https://github.com/k9mail/k-9/issues/863#issuecomment-206616235

for why SD cards are so terribly supported by Android apps.

**Comment by cketti** [comment]
This might be fixed by #1686.
