### ISSUE TITLE
Integration with Tasker not working

### ISSUE THREAD

**Issue by dberlind** [k9mail/k-9#1585]
### Expected behavior
If I'm not mistaken, I should have access to some variables in Tasker that are populated from the K9 agent:

%EFROM / %ECC / %ESUBJ / %EDATE / %ETIME

### Actual behavior
None of these variables are populated after mail arrives in K9.

### Steps to reproduce
1. install K9 onto Android (nexus 6p)
2. install tasker, check "Allow External Access" in Preferences/MISC
3. create task that's triggered by a K9 notification (ie: new mail notification)
4. interrogate any of the above variables for a value
5. no values observed

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (connected to a gmail account)

Hoping someone can help!  Thanks.

**Comment by cketti** [comment]
K-9 Mail doesn't do anything special for Tasker. If something doesn't get replaced like it should it's most likely a bug in Tasker.
