### ISSUE TITLE
The "Forward" and "Reply" menu is absent in landscape mode on 5.010

### ISSUE THREAD

**Issue by didier9** [k9mail/k-9#1589]
### Expected behavior
I expect the menu to offer at least as many choices in landscape mode as it does in portrait but it does not, these options disappear when flipping the phone (a Moto-X 2nd gen with Android 5.1)

### Actual behavior
The screen rotates and everything else is at it should, but this menu icon disapears

### Steps to reproduce
1. Install v5.010
2. Create account
3. Read mail in portrait, observe the Reply/Forward menu icon, verify it works
4. Rotate the phone in landscape mode, observevtge icon goes away.

### Environment
K-9 Mail version: 5.010

Android version:5.1

I also tried on a Nexus 7 tablet with Android 5.1 and it works normally

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
See #727
