### ISSUE TITLE
Dialog is shown every time "Enable PGP/INLINE" is selected

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1595]
![screenshot_k9mail_enable_pgp_inline_dialog](https://cloud.githubusercontent.com/assets/218061/18233635/dae152b8-72ec-11e6-8a61-96b3b9d90251.png)

This gets old fast. We should display the dialog maybe 2-3 times and then assume the user knows what it's all about and not show the dialog anymore.

PS: The light area in the background is where the keyboard used to be before the dialog was displayed.

**Comment by rugk** [comment]
Maybe add a "never show me agaiN" button or checkbox?
