### ISSUE TITLE
Don't update crypto mode right away

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1598]
![screenshot_k9mail_crypto_dialog_slider_release_changes_preference_immediately](https://cloud.githubusercontent.com/assets/218061/18233762/dd7243a4-72ef-11e6-844f-e0218a9dbb0c.png)

The crypto mode changes the moment the slider is released, not when the "Proceed" button is pressed. This makes it impossible to cancel the selection by pressing the back button or dismissing the dialog by clicking somewhere outside of it.

**Comment by rugk** [comment]
Additionally IMHO a "Cancel" button would not be a bad idea either... :smiley:
