### ISSUE TITLE
Battery, storage and data issues in 5.111

### ISSUE THREAD

**Issue by BurtonG** [k9mail/k-9#1603]
### Expected behavior

I presume that as a beta tester, my app was automatically upgraded to version 5.111 on both my phone and my tablet.  My wife still has version 5.010 on her devices.
### Actual behavior

Not only does this new version not work, it is creating a REAL problem on my devices.

The app will only function for a few seconds, and then I get an error message, “Unfortunately K-9 Mail has stopped”.  This happens even when I am not using the app, constantly.  It is even preventing me from syncing my Garmin activity tracker.

It is my largest data drain, 0.02 GB in foreground, 0.43 GB in background.

Largest storage drain at 556 MB.

Largest by far drain on the battery at 59%.

The battery is draining and charging has the phone get incredibly hot.

I uninstalled the app and reinstalled it, which caused many hours of writing down ALL of the customization, then trying to re-enter everything.  Still some custom stuff has not been correctly installed, especially “signature”.

Living without email on the go is not a good situation.

Do you have a newer version moving forward, or a way to go backwards?  Would NOT want to do all of that customization again, but can’t live without email, and especially a phone that has the battery drain, and overheats when charged.

Love the app, want to help, but can we figure out a situation?  Better to text me, 301.325.9995, as my mobile email isn’t working.  Happy to load next version.  Thanks.
### Steps to reproduce
1. Happens all of the time.
   2.
   3.
### Environment

K-9 Mail version: 5.111

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange):  I use Go Daddy, and have an Exchange account.  I understand that I have to use IMAP on my K-9 Mail app, even though the Go Daddy account has gone from POP3, to IMAP, to now Exchange.  I would have to ask Go Daddy about what WebDAV is.

**Comment by Valodim** [comment]
Hi! Thanks for your feedback so far!

So first off, the new beta contains a huge amount of rewrites, and yes this of course introduces new bugs. The reason for this is that K-9 was originally optimized for high performance, in a way which makes many features (in particular pgp/mime) technically impossible. Since smartphones are no longer as slow as they were a couple of years ago when those parts were written, we needed to rewrite them.

We are aware the current beta is not as stable as it could be. That's why we have the beta channel in the first place, since we don't have the manpower (or funding) to do extensive testing ourselves.

That said, the info from your report is really not much to go on for actually solving the problems. Have you reported the crash using the play store "Report Crash" feature? If not, please do and we will try to look into it.

**Comment by BurtonG** [comment]
While this beta version has done everything else, used an incredible amount of data, storage, battery use, and caused my phone to drain its battery and die, and when recharged, the phone severely overheated, resulting in not having not only email service, but the entire phone and therefore all capabilities unavailable, it never seem to actually "crash".  So I was never presented with the opportunity to file a "crash report".  Is there another way to do so?  Do you not have the information here, regardless of how it got here, you have it now.  In order to use my phone at all, I figured out how to go to GitHub, allow non-play store downloads, disallow ALL automatic upgrading, download v5.010, and manually put in ALL customization.  I still have 5.111 on my tablet.  How can I be of help, but I do need functionality while on the go?

**Comment by Valodim** [comment]
"unfortunately, k9 mail has stopped" is a crash, and there should be a report button in the dialog

**Comment by MrsSowerberry** [comment]
I was using version 5.010 without a problem for 3-4 weeks then today I started getting this error. I have 5 accounts added, two of which are btinternet.com. Removing one of these (my main email) gets rid of the error. I tried uninstalling k9 and starting again but I cannot add this particular account - adding it results in "unfortunately, k9 mail has stopped". I reported the crash. But I'm a bit stuck without my main email. Please help.
