### ISSUE TITLE
Add support for Heads Up/Peeking Notification in Android 5+

### ISSUE THREAD

**Issue by Ketrel** [k9mail/k-9#1615]
As Android 5 made it harder to get the ticker when receiving a notification and Android 6 removed the ticker all together, there's no quick preview in K9 when a new email arrives.

(Note, referred to as Heads Up notification in Android 5 and Peeking Notifications in Android 6)
### Expected behavior

A peeking notification should appear when an email comes in, followed by the notification being left in the notification area as it is now
### Actual behavior

The notification area gains the notification, but no visual indication of its arrival (where as on Android 4 and lower, the ticker would have given a brief display of the subject and sender in the status bar as it raised the notification)
### Steps to reproduce
1. Have notifications turned on
2. Receive email which should trigger a notification
### Environment

K-9 Mail version: 5.111 Alpha

Android version:
Android 5
Android 6 (6.0.1 specifically)

Account type (IMAP, POP3, WebDAV/Exchange):
Any which support notifications of new email

**Comment by philipwhiuk** [comment]
The issue with this is that making every notification into peeking notifications would be extremely annoying for most people.

I think we probably want to develop a proper notifications settings area (using `INTENT_CATEGORY_NOTIFICATION_PREFERENCES`) as part of the design overhaul. This will allow users to set a subset of notifications which should be priority and thus show in a Heads Up fashion.

For now however, we can do a little better about telling Android what we are notifying, so I'm sending a PR for that.

**Comment by cketti** [comment]
This can be configured via Android's notification settings on Android 8.0+. I don't want to add support for this for older Android versions.
