### ISSUE TITLE
Not receiving all e-mail from POP3 account

### ISSUE THREAD

**Issue by richardgmills** [k9mail/k-9#1616]
### Expected behavior

Every e-mal on the server should appear in the Inbox.
### Actual behavior

At random, messages do not show up in the Inbox.  I have been using K9 on my Fire tablet for maybe a year or more now; and, for the past several months, I have been using it to screen my e-mail, since Windows Mail takes so much resources and occasionally crashes.  If I see something I want to reply to or click a link on, I go to WLM to open it.  However, recently, I was sent a 911 from someone wondering why I hadn't replied.  The reason: the e-mail didn't was never in my K9 Inbox, Trash, nor any other folder!  Yesterday, I received a notice that my on-line work wouldn't start till Friday at 8 a.m.  When I went in to start, I saw a message saying work had started Thursday at noon.  I opened WLM, waited for it to download dozens of e-mails, searched for the company name, and a notice telling me I could start work at noon Thursday was there.  I went back to the Fire, searched Inbox and Trash, and the message was not there.  That makes K9 mail totally useless for me.  

I don't think this has always been the case; k9 mail has been working slower and slower since one of the past couple of updates, but not downloading mail that can be found by another e-mail client is totally unacceptable.
### Steps to reproduce
1. Check mail.
2. Discover one way or another that an e-mail was never received.
3. Go to WLM and download e-mails to find it.
### Environment

K-9 Mail version: 5.000

Android version: Fire OS 5

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
Is there a reason you're running a version of K-9 from September - we release 5.001 in October and have done several releases since then?

**Comment by richardgmills** [comment]
I thought I had seen it update once or twice on its own, but maybe I was mistaken on that.  I don't see a way to update it on the app, and the store just says Open.  I am guessing when you tell me how I should be updating it, I will be replying, Duh, but I have to ask, anyhow.  ??

Also, is it possible it's been skipping e-mails since 2014?  Or just since Fire updated its OS?  Or it somehow backtracked to its previous version?

**Comment by richardgmills** [comment]
I may have figured out the answer to my initial question.  See if this makes sense:

I had my account to load 25 e-mails.  I frequently get 60 to 100 a day.  I let the polling (every minute) load new e-mails, or I pulled down the screen to set the circle rotating, or I clicked on the circle to load more.  But I never used the "Load up to 25 more" link at the bottom of the list.  Is it possible that the "missing" e-mails would have shown up if I had clicked the "Load up to 25 more" link, but the polling and refresh polls just got the next 25 *after* the last poll time?  That is, maybe there were 30 e-mails available for the first poll, and it loaded 25 of them.  If I had clicked the load-more link, it would have loaded the other 5.  But, since it or I just started the next poll, it downloaded up to 25 new since the last poll.

Does that make sense, and do you think that was the problem?  I changed the account to "download all," and the two known "missing" e-mails were loaded — but so were several hundred older ones I know K9 had seen before!  (When I saw that happening, I shut down the Fire, and deleted all the older e-mails on the server other than the two I knew the Fire hadn't seen before.)

If that is actually what caused some e-mails not to show up, then the only other question is how to update K9 on my Fire.  My Galaxy 3 phone and Acer Android tablet have version 5.010.  I don't know what the latest version is supposed to be.  ??

**Comment by philipwhiuk** [comment]
> Does that make sense, and do you think that was the problem? I changed the account to "download all," and the two known "missing" e-mails were loaded — but so were several hundred older ones I know K9 had seen before! (When I saw that happening, I shut down the Fire, and deleted all the older e-mails on the server other than the two I knew the Fire hadn't seen before.)

Yes.

The latest stable version of K-9 is 5.010.

@cketti - do we still have the ability to deploy to the Kindle app store: https://www.amazon.com/K-9-Dog-Walkers-Mail/dp/B004JK61K0/ seems to be still 5.000

**Comment by richardgmills** [comment]
Sorry for the long span before reply here.  Does that mean Amazon Fire users are stuck with 5.000?  I haven't noticed any missing e-mails since I set the account to download all of them.  But I have also been having *a lot* of trouble getting e-mails to delete!  I'll select all, deselect the ones I want to read, mark the selected ones read, and then delete them.  Sometimes (after a long wait) they delete; sometimes they don't.  Even when they do, I'll come back to the Inbox and find them all or many of them back, marked as read.  Then trying to find the unread ones I wanted to read is close to impossible.  (I often get over 100 e-mails a day, most of them asking me for money!)

I can even go to the Trash folder and select all there and delete (again waiting a long time), but they will still pop up back in the Inbox as read.  Is that something 5.0.10 might have fixed?

And getting an e-mail to display can take a long time, too; but I don't know if that's the Fire being slow or the mail app.  ??
