### ISSUE TITLE
No e-mail send possible

### ISSUE THREAD

**Issue by Raart** [k9mail/k-9#1624]
### Expected behavior
New edited e-mails to be sent

### Actual behavior
While SMTP parameters are verified during outgoing server setup, further login attempts to the server are rejected.
"com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 550 Sender address is not allowed."
It seems a wrong username is passed at this stage.
All other apps using SMTP behave correctly.
Fetching e-mails is go.

### Steps to reproduce
Edit a new message and send

### Environment
K-9 Mail version: 5.0.10 default config

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
POP3/SMTP with SSL/TLS

**Comment by Raart** [comment]
Same behaviour with k-9 v5.110 else when cleaning outbox before editing a new message.

**Comment by wwp** [comment]
Hello Raart,


On Tue, 20 Sep 2016 03:40:00 -0700 Raart <notifications@github.com> wrote:

> ### Expected behavior
> New edited e-mails to be sent
> 
> ### Actual behavior
> While SMTP parameters are verified during outgoing server setup, further login attempts to the server are rejected.
> "com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 550 Sender address is not allowed."
> It seems a wrong username is passed at this stage.
> All other apps using SMTP behave correctly.
> Fetching e-mails is go.
> 
> ### Steps to reproduce
> Edit a new message and send
> 
> ### Environment
> K-9 Mail version: 5.0.10 default config
> 
> Android version: 6.0
> 
> Account type (IMAP, POP3, WebDAV/Exchange):
> POP3/SMTP with SSL/TLS

What's the server domain if it's not private?

What credentials are configured for this account, a single username or
your full e-mail address (username@domain.com for instance)?

Did you try both forms?


Regards,

-- 
wwp

**Comment by Raart** [comment]
On 2016-09-20 13:23, Tristan C. wrote:
> Hello Raart,
>
>
> On Tue, 20 Sep 2016 03:40:00 -0700 Raart <notifications@github.com> wrote:
>
> > ### Expected behavior
> > New edited e-mails to be sent
> >
> > ### Actual behavior
> > While SMTP parameters are verified during outgoing server setup, further login attempts to the server are rejected.
> > "com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 550 Sender address is not allowed."
> > It seems a wrong username is passed at this stage.
> > All other apps using SMTP behave correctly.
> > Fetching e-mails is go.
> >
> > ### Steps to reproduce
> > Edit a new message and send
> >
> > ### Environment
> > K-9 Mail version: 5.0.10 default config
> >
> > Android version: 6.0
> >
> > Account type (IMAP, POP3, WebDAV/Exchange):
> > POP3/SMTP with SSL/TLS
>
> What's the server domain if it's not private?

SMTP server:      mail.gmx.net
POP3 server:       pop.gmx.net

>
> What credentials are configured for this account, a single username or
> your full e-mail address (username@domain.com for instance)?

The full e-mail address

>
> Did you try both forms?

I'm not aware about a second username option.

But wait..., maybe one thing to investigate on k-9 could be the fact I use two different accounts for inbound and outbound. In other words I've configured k-9 to login by POP3 service as /signupbox01/@gmx.net and as /smtp01/@gmx.net for SMTP service access (with their distinct passwords).
This for some added security reasons. The SMTP account doesn't accept inbound e-mails and the real inbound address isn't advertised in my sent e-mail headers.
I specify the address where I like to have replayed  my e-mails to from the specific addressee by selecting it from a categorized pool. If I don't like to reveal a real e-mail address I don't specify any or specify a fake one.
Actually, my system setup doesn't allow me to directly sniff what k-9 is doing but one possibility, considering this uncommon configuration, is it mismatches POP3 and SMTP login usernames/passwords  (thus the 550 error code on SMTP)...

BTW, I'm on an unrooted Elephone M3 and can't find the k-9's files nor eventual logs. Where are them in the filesystem? Do I've to root the phone to gain access to them?

Thank you in forward.


Regards

-- 

Andreas


--

**Comment by wwp** [comment]
Hello Raart,


On Tue, 20 Sep 2016 07:23:44 -0700 Raart <notifications@github.com> wrote:

> On 2016-09-20 13:23, Tristan C. wrote:
> > Hello Raart,
> >
> >
> > On Tue, 20 Sep 2016 03:40:00 -0700 Raart <notifications@github.com> wrote:
> >  
> > > ### Expected behavior
> > > New edited e-mails to be sent
> > >
> > > ### Actual behavior
> > > While SMTP parameters are verified during outgoing server setup, further login attempts to the server are rejected.
> > > "com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 550 Sender address is not allowed."
> > > It seems a wrong username is passed at this stage.
> > > All other apps using SMTP behave correctly.
> > > Fetching e-mails is go.
> > >
> > > ### Steps to reproduce
> > > Edit a new message and send
> > >
> > > ### Environment
> > > K-9 Mail version: 5.0.10 default config
> > >
> > > Android version: 6.0
> > >
> > > Account type (IMAP, POP3, WebDAV/Exchange):
> > > POP3/SMTP with SSL/TLS  
> >
> > What's the server domain if it's not private?  
> 
> SMTP server:      mail.gmx.net
> POP3 server:       pop.gmx.net
> 
> >
> > What credentials are configured for this account, a single username or
> > your full e-mail address (username@domain.com for instance)?  
> 
> The full e-mail address
> 
> >
> > Did you try both forms?  
> 
> I'm not aware about a second username option.
> 
> But wait..., maybe one thing to investigate on k-9 could be the fact I use two different accounts for inbound and outbound. In other words I've configured k-9 to login by POP3 service as /signupbox01/@gmx.net and as /smtp01/@gmx.net for SMTP service access (with their distinct passwords).
> This for some added security reasons. The SMTP account doesn't accept inbound e-mails and the real inbound address isn't advertised in my sent e-mail headers.
> I specify the address where I like to have replayed  my e-mails to from the specific addressee by selecting it from a categorized pool. If I don't like to reveal a real e-mail address I don't specify any or specify a fake one.
> Actually, my system setup doesn't allow me to directly sniff what k-9 is doing but one possibility, considering this uncommon configuration, is it mismatches POP3 and SMTP login usernames/passwords  (thus the 550 error code on SMTP)...
> 
> BTW, I'm on an unrooted Elephone M3 and can't find the k-9's files nor eventual logs. Where are them in the filesystem? Do I've to root the phone to gain access to them?
> 
> Thank you in forward.

Well, I could setup a fully functional gmx.com account here, by using
the manual setup (POP3/SMTP). I used default values everywhere BUT the
POP3 host: pop.gmx.com (it proposes pop3.gmx.com by default, which is
wrong) and the difference with what you pasted is that the SMTP host
name is smtp.gmx.com, NOT mail.gmx.com.


HTH,

-- 
wwp

**Comment by cketti** [comment]
See https://github.com/k9mail/k-9/wiki/LoggingErrors

This is more likely a configuration error than a bug in K-9 Mail. 
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by Raart** [comment]
On 2016-09-20 16:53, Tristan C. wrote:

...

> >
> > But wait..., maybe one thing to investigate on k-9 could be the fact I use two different accounts for inbound and outbound. In other words I've configured k-9 to login by POP3 service as /signupbox01/@gmx.net and as /smtp01/@gmx.net for SMTP service access (with their distinct passwords).
> > This for some added security reasons. The SMTP account doesn't accept inbound e-mails and the real inbound address isn't advertised in my sent e-mail headers.
> > I specify the address where I like to have replayed my e-mails to from the specific addressee by selecting it from a categorized pool. If I don't like to reveal a real e-mail address I don't specify any or specify a fake one.
> > Actually, my system setup doesn't allow me to directly sniff what k-9 is doing but one possibility, considering this uncommon configuration, is it mismatches POP3 and SMTP login usernames/passwords (thus the 550 error code on SMTP)...
> >
>
>
> Well, I could setup a fully functional gmx.com account here, by using
> the manual setup (POP3/SMTP). I used default values everywhere BUT the
> POP3 host: pop.gmx.com (it proposes pop3.gmx.com by default, which is
> wrong) and the difference with what you pasted is that the SMTP host
> name is smtp.gmx.com, NOT mail.gmx.com.
>
>
> HTH,
>
> -- 
> wwp

mail.gmx.net as SMTP server works well too. Try it.

Anyway, else configuring smtp.gmx.net as the SMTP server k-9 continues to refuse to send e-mails.

You have not tested the configuration I described.

I can confirm that a canonical configuration with POP3 and SMTP relying to the same account/username works well. But this is not the point.

The problem appears if SMTP is configured for a different account (username) from that configured for the POP3 service.

-- 

Andreas

OM GnuPg Key-ID is: 0x56749E48

vy 73's de IK2WQI - JN45OL

--

**Comment by wwp** [comment]
Hello Raart,


On Tue, 20 Sep 2016 23:55:03 -0700 Raart <notifications@github.com> wrote:

> On 2016-09-20 16:53, Tristan C. wrote:
> 
> ...
> 
> > >
> > > But wait..., maybe one thing to investigate on k-9 could be the fact I use two different accounts for inbound and outbound. In other words I've configured k-9 to login by POP3 service as /signupbox01/@gmx.net and as /smtp01/@gmx.net for SMTP service access (with their distinct passwords).
> > > This for some added security reasons. The SMTP account doesn't accept inbound e-mails and the real inbound address isn't advertised in my sent e-mail headers.
> > > I specify the address where I like to have replayed my e-mails to from the specific addressee by selecting it from a categorized pool. If I don't like to reveal a real e-mail address I don't specify any or specify a fake one.
> > > Actually, my system setup doesn't allow me to directly sniff what k-9 is doing but one possibility, considering this uncommon configuration, is it mismatches POP3 and SMTP login usernames/passwords (thus the 550 error code on SMTP)...
> > >  
> >
> >
> > Well, I could setup a fully functional gmx.com account here, by using
> > the manual setup (POP3/SMTP). I used default values everywhere BUT the
> > POP3 host: pop.gmx.com (it proposes pop3.gmx.com by default, which is
> > wrong) and the difference with what you pasted is that the SMTP host
> > name is smtp.gmx.com, NOT mail.gmx.com.
> >
> >
> > HTH,
> >
> > -- 
> > wwp  
> 
> mail.gmx.net as SMTP server works well too. Try it.
> 
> Anyway, else configuring smtp.gmx.net as the SMTP server k-9 continues to refuse to send e-mails.
> 
> You have not tested the configuration I described.
> 
> I can confirm that a canonical configuration with POP3 and SMTP relying to the same account/username works well. But this is not the point.
> 
> The problem appears if SMTP is configured for a different account (username) from that configured for the POP3 service.

Sorry, "if SMTP is configured for a different account (username) from
that configured for the POP3 service" works here :-) but yet again,
I'm not using the .net servers (but .com ones).

Now, curious about it, I've just set up a GMX account w/ the .net
servers you're using, and use a different account (different account,
different GMX subdomain) for sending. Fetching and sending both works.

May I suggest k-9 is not culprit here, definitely? It even sounds GMX
servers are working as expected. Either you're running from Twilight
Zone, or there's something nasty in your environment that we don't
know or it's a simple configure (user) issue. In both case we should
continue on the appropriate users mailing list, as requested by cketti.


Regards,

-- 
wwp
