### ISSUE TITLE
The button "Pause-Start" Auto Scan for the of all configured on this mode mailbox's

### ISSUE THREAD

**Issue by OminouZ** [k9mail/k-9#1626]
### Expected behavior
It should be possible, without closing the program stop the auto-scan all mailboxes and run it back through time. The button "Pause-Start".
Необходима возможность, не закрывая программу, остановить авто-проверку всех почтовых ящиков и запустить ее снова через время. Кнопка пауза-пуск.

### Actual behavior
No such possibility
Нет такой возможности

### Environment
K-9 Mail version:
5.010
Android version:
5.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, POP3

**Comment by philipwhiuk** [comment]
Sounds like a duplicate of #1610 to me.
