### ISSUE TITLE
No period insert after double space

### ISSUE THREAD

**Issue by sonnyhk9** [k9mail/k-9#1630]
### Expected behavior
Tell us what should happen
At end of sentence double space should insert a period  

### Actual behavior
Tell us what happens instead
At end of sentence double space, no period
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.0.10 Galaxy Tab2

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by wwp** [comment]
Sorry but this all depends on your keyboard settings. Here it's optional and works if configured so that a double-space produces a period. What's your keyboard app, exactly?

**Comment by sonnyhk9** [comment]
Hi,
Thanks for the response.
Just the on screen Touch keyboard that comes with the OS.

**Comment by philipwhiuk** [comment]
Closing as invalid - this is not a result of K-9's behaviour
