### ISSUE TITLE
K9 is crashing regularly on my tablet

### ISSUE THREAD

**Issue by TonyQ007** [k9mail/k-9#1632]
### Expected behavior
It should download new emails as it used to do.

### Actual behavior
It downloads from some of the accounts that are set up, but then puts up a message saying "Unfortunately, K-9 Mail has stopped."  It doesn't do it 100% of the time, but most of it.  Then it'll stop crashing for a short while and then start again.

### Steps to reproduce
1.Pull down emails to make it sync.

### Environment
K-9 Mail version: 5.010

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): K-9 is configured with 6 POP3 mail accounts all on the same server.

It is my suspicion that I had received a badly crafted email on one of the accounts that gets a lot of SPAM.  This started the problem.  I would guess that it has now corrupted something in K-9 which is causing the ongoing problems.

I have sent a report of the crash several times, including a couple just now, one of which has debugging turned on.

Your advice would be most useful - unless it can be sorted fairly quickly, I will have to switch to a different email app which would be a shame after I've used K-9 for several years and recommended it to other people.

**Comment by philipwhiuk** [comment]
If we have received a crash log from the Play Store we'll look at it. As it is, this issue doesn't really add anything because there's insufficient information (i.e. no debug log) to diagnose it based on just the issue report.
