### ISSUE TITLE
The notification buttons don't fit on the screen

### ISSUE THREAD

**Issue by marmistrz** [k9mail/k-9#1636]
### Expected behavior
The whole label are visible or no labels are displayed at all

### Actual behavior
The labels are trimmed: `De...` instead of `Delete`, `Ma...` instead of `Mark as read`, etc.

### Steps to reproduce
1. Enable delete for the notifications
2. Receive a message

### Environment
K-9 Mail version: 5.010
Android version: CM 13.0 (Marshmallow)
Account type: IMAP, gmail
Device: OnePlus 3, screen width: 1080px

**Comment by cketti** [comment]
Notification actions are rendered by the OS. You probably want to report this as a bug to your device vendor.

See also #943 for what we could do.
