### ISSUE TITLE
Bug in OS <=4.3 in class RecipientSelectView onTouchEvent

### ISSUE THREAD

**Issue by younes778** [k9mail/k-9#1638]
The class TokenImageSpan is unkwon to the systems 4.3 and under.
I fixed the bug changin the function onTouchEvent replacing the line : 
TokenImageSpan[] links = text.getSpans(offset, offset, RecipientTokenSpan.class);
with : 
RecipientTokenSpan[] links = text.getSpans(offset, offset,RecipientTokenSpan.class);

**Comment by cketti** [comment]
Thanks for the bug report. Can you please create a pull request with your fix?

**Comment by younes778** [comment]
Okey. I will.

**Comment by younes778** [comment]
done https://github.com/k9mail/k-9/pull/1640
