### ISSUE TITLE
Microsoft Exchange support

### ISSUE THREAD

**Issue by homan2017** [k9mail/k-9#1643]
### Expected behavior
K9 mail is the best email apps i've ever tried but it doesnt support Exchange version >10 which is my main email account. 
it would be my deepest appreciation if any developer can help on this. 
Thank you very much in advance.

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Duplicate of #606
