### ISSUE TITLE
intermittent problems on Wi-Fi

### ISSUE THREAD

**Issue by Disneyf1** [k9mail/k-9#1650]
Occasionally K-9 will not send out mail while connected to wi-fi. I have to disconnect from wi-fi and send over cell data, then turn wi-fi on again. 
I cannot predict when it will happen and it occurs on any wi-fi network. 

Any idea?
 Thanks

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
