### ISSUE TITLE
Close SMTP connections properly.

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1652]
### Expected behavior

SMTP connections should be properly closed when they are created in an unusable state.
### Actual behavior

I found an issue during SMTP testing. When opening a connection, if authentication fails for some reason, we don't close the connection during clean-up. 

I think this is unlikely to cause an issue, but it's possible that when setting up and testing a connection we'll be creating lots of sockets and not closing them.

I have a potential fix (and set of tests for this).
### Steps to reproduce
1. Run an SMTP server that doesn't support the requested AUTH method.
2. Get K-9 to connect to it.
3. K-9 will send EHLO, get back lack of capability and not close the connection.

See #1649 for a test environment
### Environment

K-9 Mail version: master

Android version: N/A

Account type (IMAP, POP3, WebDAV/Exchange): SMTP

**Comment by Valodim** [comment]
Ever got to commit your potential fix? :)

**Comment by philipwhiuk** [comment]
Good question. I'll check!
