### ISSUE TITLE
New Feature request: command line to execute before stablishing connections towards the e-mail server

### ISSUE THREAD

**Issue by frojasg1** [k9mail/k-9#1657]
Hello,

### Expected behavior

For me it would be very useful the application to have the possibility to store, for every account, an optional field (command line to execute before stablishing the connection towards the email server).

This field would contain a command line which would be executed before trying to connect to the email server.

In my case, this would be useful, because I am planning to use fwknop in the linux server where I will have the email server.

The fwknop functionality gives you the possibility to close all ports of your server until the server receives an appropiate combination of tcp messages. In such a case, the fwknop server would create firewall rules to open the port requested for a few seconds.

In these few seconds, the client can connect to the server because the ports are open.

fwknop2 is an application available in Android as open source code.

I suppose this fwknop2 application could be modified to have the possibility of being invoked to send the fwknop messages from the command line, and then, using the new feature just requested for k-9, open the ports before attemting to connect to the email server.

### Actual behavior
    ---------

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:           For new versions

Android version:            For all versions

Account type (IMAP, POP3, WebDAV/Exchange):           For all account types

P.D.
I suppose you are very busy with other implementations.
In this case, I could offer my services to try to program this request.
Although I am not very familiar with Android, I have quite experience programming with Java and I think I could succeed with this development.

Please, let me know what do you think about it.

Kind regards,
Fran.        ( frojasg1@hotmail.com )

EDIT: Post formatting changes only (@philipwhiuk)

**Comment by frojasg1** [comment]
I have just seen that the way for Android to launch another application is by means of an Intent class invocation.
The new feature then, should be changed, to configure a package name to be launched besides the configurationName to be launched by the fwknop2 application.
Although it is not very generic.

Another option may be to configure only the configurationName for fwknop2, and create this new feature only for launching this fwknop application from k-9.

I do not know if you would be interested in k-9 to have this feature.

**Comment by philipwhiuk** [comment]
It seems like the best strategy is for K-9 to support proxying ( #704 )

So you'd have an Android application on the phone which proxied K-9 connections, sending the appropriate `fwknop` calls as applicable.

This is broadly how Android applications support, for example, TOR.

I don't think adding specific settings to inject commands of some form is a good idea.

**Comment by frojasg1** [comment]
I think this approach is more complicated to program, but I will think how I can achieve it this way.

Thank you very much for your fast answer.

**Comment by frojasg1** [comment]
It has the advantage to hide your real IP, this is a very good point.

Is proxying currently supported by K-9 ?, I have not found it in the user's manual.

**Comment by frojasg1** [comment]
Thinking about it, may be that if you use a proxy, the fwknop command would be not effective.
The fwknop message bring the information of which IP is allowed to open a connection on the just open port of the Linux server.
I think fwknop message has an option to ask the fwknop server solve the source IP, rather than explicitly specifying it.
I suppose in that case the fwknop initial message should be sent from the same IP that the try to open the connection to the email server.
I do not know if it is possible ...

**Comment by frojasg1** [comment]
I suppose I have the possibility to adapt your open code for my needs and use it only for me.

**Comment by philipwhiuk** [comment]
Proxying is a planned enhancement - as per the ticket I linked.

**Comment by frojasg1** [comment]
I have just seen that SPA on fwknop can be used together with the tor network.
I do not know if the android versions of fwknop are compatible with it or not, but definitely if K-9 implemented proxying it would be great.

**Comment by philipwhiuk** [comment]
I'm going to close this - outside of the linked ticket there's no additional work to be done by K9 here.
