### ISSUE TITLE
better functionality for iCalendar invites - preview of the invite, automatic parsing and filtering

### ISSUE THREAD

**Issue by AHoros** [k9mail/k-9#1661]
### Expected behavior
With business email a key functionality is handling calendar invites you get from various organizations/people. Usually they come in form of mail attachments with .ics extension.

So in effect this is tightly coupled to email and it deserves dedicated handling.

Desired features:
* filter inbox by emails containing attachment with *.ics name (sometimes there is more than one attachments in one email, but if at least one of them is calendar invite that we want to highlight this email)
* preview of the invite displaying the basic details of the invite
* automatic parsing - auto-add to built-in calendar, or at least suggest auto-adding with one click confirmation

### Actual behavior
Right now you have to manually open the attachments with *.ICS extension with default MIME handler which is build-in calendar app.
This is time consuming and it easy to miss the invite.
Another downside is that such manual opening of the attachment automatically adds the meeting to calendar which is problematic when you want to reject it or it is added at some distant date making it difficult to locate/identify.
 
### Steps to reproduce
send to yourself calendar invites from:
* Android calendar
* iPhone/Apple calendar
* Microsoft Exchange calendar

### Environment
K-9 Mail version: 5.1

Android version:
5

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP and POP3

**Comment by cketti** [comment]
See #930
