### ISSUE TITLE
Notifications removed

### ISSUE THREAD

**Issue by levinuss** [k9mail/k-9#1664]
### Expected behavior

If there are multiple notifications for mails, the user expands the multiline 'compressed' notification and clicks on one of the mails, this mail should be opened in K-9 and should be removed from the notifications. The other mails should stay in the notifications.
### Actual behavior

If I open one mail from the notification bar, K-9 opens this mail but all mails are removed from the notifications.
### Steps to reproduce
1. Get multiple new mails (=notifications)
2. Expand the summarized notification to get all mails
3. Klick on one mail
### Environment

K-9 Mail version: 5.111

Android version: 7.0 (Nexus 5X)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Possibly this is an enhancement. There is a difference of opinion as to whether notifications should clear:

* On opening the app
* On viewing the unified inbox / inbox for that account
* On viewing the message itself

We may need a setting for this.

**Comment by levinus** [comment]
Yes, I am totally with you. I also think a setting would be very helpful.
