### ISSUE TITLE
K9 Mail Dark Theme 

### ISSUE THREAD

**Issue by a1exus** [k9mail/k-9#1669]
### Expected behavior
After setting theme to "Dark", I'm expected to see dark theme.

### Actual behavior
Even though theme set to "Dark", I'm seeing light theme.

### Steps to reproduce
1. K-9 Mail 5.112 @ Android 7.0 (PL:10/5/16), Nexus 6p
2. Settings -> GLOBAL -> Display - Theme = switch to Dark theme
3.

### Environment
K-9 Mail version: 5.112

Android version: 7.0 (PL:10/5/16)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
See #1666

**Comment by a1exus** [comment]
I'm unable to switch to dark theme _outside_ of message and _without_ using fixed `message theme` as well.

Is it really duplicate?

**Comment by cketti** [comment]
You're using different ways to trigger it, but it's the same bug.

**Comment by a1exus** [comment]
Ok, thanks!
