### ISSUE TITLE
Changelogs contain links to Google Code

### ISSUE THREAD

**Issue by sm4rk0** [k9mail/k-9#1670]
Links at
https://github.com/k9mail/k-9/wiki/ReleaseNotes
For example:
https://k9mail.github.io/k-9/changelog_master_branch.xml
Contain the link to:
https://code.google.com/p/k9mail/

I suppose this should be changed with
https://k9mail.github.io/k-9/
or
https://github.com/k9mail/k-9

**Comment by cketti** [comment]
Thanks. Fixed.
https://github.com/k9mail/k-9/commit/c1b2788b044d077ea6a4574f0c8df3baeddc0b94
