### ISSUE TITLE
k9-5.112-release.apk

### ISSUE THREAD

**Issue by werano** [k9mail/k-9#1674]
### Expected behavior
The View "Dark/Light"

### Actual behavior
Doesn't work

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
k9-5.112-release.apk
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
pop

**Comment by XenGi** [comment]
Maybe change the title to "changing theme dosn't work after update to 5.112".

**Comment by cketti** [comment]
See #1666
