### ISSUE TITLE
Feature request: Metro Port

### ISSUE THREAD

**Issue by mikeloeven** [k9mail/k-9#1675]
Any chance of getting a port to the windows metro framework seems like lots of apps now adays are going multi platform. I Love the simplicity of it and have been using it on my S5 for years. I would love to be able to run this on my recently refurbished tablet too cause even with the Windows 10 "tablet optimizations" The older hardware starts to smoke every time I try to use a bulky client like outlook or Thunderbird and frankly there aren't any good lightweight email apps for these devices

**Comment by cketti** [comment]
We have no plans for porting the app to any other platform.
