### ISSUE TITLE
Theme change on K9 5.112 not possible

### ISSUE THREAD

**Issue by werano** [k9mail/k-9#1676]
### Expected behavior
on 512 a theme change is not possible

### Actual behavior
the theme stays light
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 512

Android version: 6.0

 pop

**Comment by cketti** [comment]
See #1666

**Comment by werano** [comment]
i don't understand why the subjet had been closed

**Comment by werano** [comment]
sry, your comments got stuck in my spam
