### ISSUE TITLE
5.112 breaks theming

### ISSUE THREAD

**Issue by sporkwitch** [k9mail/k-9#1681]
### Expected behavior
Application theme should follow settings

### Actual behavior
Application theme is always "light"

### Steps to reproduce
Update to 5.112 with dark theme enabled previously, or change to dark theme.

Theme is set to dark, all other theme settings are set to "use app setting."

### Environment
K-9 Mail version: 5.112

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by cketti** [comment]
Fixed in 5.113
