### ISSUE TITLE
Trah Can Problem on k9-5.113

### ISSUE THREAD

**Issue by werano** [k9mail/k-9#1682]
### Expected behavior
When opening an email the trashcan icon is supposed to show up, too.

### Actual behavior
Several attempts are necessary to detect the trash symbol, and so delete the email.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 513

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): pop

**Comment by philipwhiuk** [comment]
Just the trash can or the whole bottom bar - I.e is this #1671

If it's not please provide a screenshot and a way to reproduce it.

**Comment by werano** [comment]
the complete bottom bar is missing
