### ISSUE TITLE
K-9 Mail should allow sending encrypted but unsigned e-mail

### ISSUE THREAD

**Issue by marmistrz** [k9mail/k-9#1683]
Currently, the cryptography levels are:

- never sign or encrypt
- always sign, never encrypt
- always sign, encrypt if possible
- always sign, always encrypt

It's not possible to send and encrypted but unsigned e-mail.

**Comment by philipwhiuk** [comment]
What's the expected use case? Or is it just 'because you can'?

**Comment by marmistrz** [comment]
Sending encrypted but unsigned messages can provide some form of deniability since everyone can encrypt the message with the public key.

**Comment by cketti** [comment]
This is by design. If you have very special needs K-9 Mail is probably the wrong app for you anyway.

**Comment by marmistrz** [comment]
@cketti first of all there are no other open source e-mail clients for Android which allow PGP encryption I know about.
Secondly: what's so wrong with sending encrypted unsigned e-mail?

**Comment by marmistrz** [comment]
Besides, what about option: encrypt when possible, sign when encrypting? It's a PITA to type my very long password every time I send an unencrypted message.

**Comment by marmistrz** [comment]
@cketti: can you please shed a word, justify, discuss? This is what open source projects should be like (unlike GNOME)

**Comment by marmistrz** [comment]
If anyone is looking for a workaround: 

1. write the message as usual
2. select the content 
3. select encrypt from the context menu. OpenKeychain will open, you can now encrypt the text
4. select "never sign or encrypt" in the UI
5. send 

Voila: encrypted, unsigned message. With some hassle, without PGP/MIME support, but thank @cketti for this.

You can alternatively compose the message in OpenKeychain and use the Share option. The outcome is basically the same.

**Comment by philipwhiuk** [comment]
The point of a project lead is to direct the project. If you don't like the direction a project is taken, feel free to fork it and fix it yourself. 

Being hostile to those who actually contribute (I note you have created 29 issues across GitHub projects and pushed only 1 small shell script) is not a good way of getting support for your position.

**Comment by marmistrz** [comment]
I'd really do it if I had time to maintain it. But one thing is the direction a project is taken (removing useful features) and the other is refusing any explanation **why** it is done so (why features are removed), denying any discussion. It looks like an arrogant and disrespectful attitude against the user.

Where there's discussion, people can often find a way out. Where it's missing, only anger and hostility arises. We should talk about problems and not pretend they don't exist.

**Comment by marmistrz** [comment]
Btw. I could code the feature myself (or at least a part of it since I'm quite busy) and make a pull request, but if we don't talk then it's probably going to be rejected anyway because it doesn't fit your idea for the app.

My current idea is: two sliders:
 - one for signing: [never, if encrypting, always]
 - the other for encrypting [never, if possible, always]

**Comment by marmistrz** [comment]
For reference, I attach the follow-up discussion from IRC, should someone read this issue.

```
<marmistrz> cketti, philipwhiuk: I don't understand one thing. If this were a OpenKeychain decision, then I wouldn't be able to send an unsigned encrypted message on K9 5.010 (which supports both APG and OpenKeychain)
<marmistrz> So OpenKeychain supports it.
<cketti> marmistrz: well, you weren't very clear. entering the passphrase is not handled by k-9 mail
<cketti> however, not supporting encrypted but unsigned messages is an intentional limitation of k-9 mail
<marmistrz> cketti: what's the intention behind it?
<cketti> that's because we want to make encrypting messages as easy and useful as possible
<cketti> simply encrypting them doesn't give confidence the stated sender really sent the message
<marmistrz> Infinite password caching poses a potential security risk, since the decrypted keys are kept in RAM, so I'd rather avoid it.
<marmistrz> It's true that simply encrypting does give confidence you mentioned per se but you can usually find it out by context. 
<marmistrz> And if one uses the default behavior of OpenKeychain: cache the key until screen off.
<marmistrz> then the encryption stops being as useful as secure as possible
<marmistrz> *btw. with an uncache password no one can peek through your e-mails if you gave them a phone for a while
<cketti> the goal is not to be as secure as possible. because as you found out very strong security is inconvenient
<marmistrz> Yep, there are always trade-offs. 
<marmistrz> Seeing your perspective, I'd see a possible solution.
<marmistrz> A configurable crypt-ui (the part of K9 responsible for it) 
<marmistrz> default: an easy crypt-ui, kept the way it is, it's really well suited for an average user.
<marmistrz> alternate ui, which can be turned on in the settings; currently it could be the old sign/encrypt UI as in 5.010
<marmistrz> this way we kill two birds with one stone: make the app both user-friendly and power-user-friendly
<cketti> we already have too many settings. this makes maintaining the app unnecessarily hard. we've given up on trying to make every user happy
<marmistrz> I will help with implementing a solution which would allow higher configurability of crypt settings.
<marmistrz> if we come up with some compromise
<marmistrz> another idea is: two sliders: sign: [never, if encrypting, always], encrypt: [never, if possible, always]
<marmistrz> But I'm open for anything else, as long it's configurable
<marmistrz> s/long/long as/
<cketti> feel free to implement that. i'll look at pull requests, but make no promises.
<marmistrz> btw. some of my friends use the same principle as me: if it's something really important such as bank account number - then we sign the message. If it's just sending each other funny memes: no point in the hassle
<marmistrz> you mean the two-slider version?
<marmistrz> or the double-ui version?
<cketti> pgp/mime was a highly requested feature, yet nobody was willing to implement it for years. your offer is nice. but if history is an indicator nothing will come of it. so i hope you can understand why i feel talking about what could be is not the best use of my time
<marmistrz> understood :) 
<marmistrz> thanks for discussing
<marmistrz> sorry for being rude there in the github issues, I was really fed up with the lack of communication and my words falling into void back then
<cketti> no worries. i should probably write a blog post explaining why i'm reluctant to argue design decisions with strangers. and then point to it instead of not answering
<marmistrz> yep, that's a good idea.
<marmistrz> The UI for the crypto mode dialog resides here: k9mail/src/main/java/com/fsck/k9/view/CryptoModeSelector.java
<marmistrz> am I right?
<marmistrz> Or will there be any other files of interest (UI only right now)
<cketti> CryptoSettingsDialog
<marmistrz> thanks
```

**Comment by Valodim** [comment]
The ui for signing messages has since evolved, sign-only moved into its own "mode". Fair warning in regards to the irc log (and the "two sliders" idea), I'm most likely going to veto any PR which goes in the direction of portraying encryption and signing as independent things again.
