### ISSUE TITLE
XOAUTH2 implementation for Yahoo accounts

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1698]
### Expected behavior

Yahoo accounts should be able to sign in, without enabling less secure apps.

NB: For POP3 XOAUTH2 isn't available on Yahoo. POP3 is deprecated anyway. We should probably also tell Yahoo users (notification) to migrate from POP3. 
### Actual behavior

Denied.
### Steps to reproduce
1. Configure a Yahoo account on IMAP
2. Try to login
### Environment

K-9 Mail version: master

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
### Developer notes

The work to implement some of the XOAUTH2 code is done in #1295 

However the assumption was made that it would be Google accounts. So much of token refresh code works out of the box. This isn't true for Yahoo accounts. So some work needs to be done in terms of:
1. Writing an XOAUTH2 token refresh tool for Yahoo accounts
2. Making sure we use the right method for each one

I suspect we'll have a hardcoded URL in the app somewhere for Yahoo's endpoint. But I'm speculating until I get my hands dirty again

**Comment by philipwhiuk** [comment]
Yahoo aren't being communicative on what endpoint you're supposed to hit :(

**Comment by vt0r** [comment]
@philipwhiuk - https://github.com/andris9/xoauth2/commit/ae0667f92a460751eec6ec7b618a35db5e56e6c4

Apologies in advance for nodejs, but I thought it might help anyway. :+1:

**Comment by philipwhiuk** [comment]
Thanks! There's no scope in the project creation for Mail. But I might just try without the scope and see.

As for the nodejs - unfortunately my day job is more and more JS every day so that's not a problem!

**Comment by CreeperLava** [comment]
How is progress on this issue going ? I'm having the same issue, since I disabled "less secure" apps in Yahoo. I have the feeling they're trying to make us use their app :).

**Comment by philipwhiuk** [comment]
Update on this. It doesn't work without the scope. Back in October I pinged Dylan Casey who manages Yahoo's OAuth2 infrastructure as to why. He said he'd get back to me. No word so I've asked for an update.

**Comment by Valodim** [comment]
thanks for the effort! :+1:

**Comment by natevw** [comment]
So to be clear: it's still the case that to use K-9 with Yahoo mail I will need to change the setting in my account there about "less secure apps" or whatever?

**Comment by philipwhiuk** [comment]
Apparently Sky's version of Yahoo is getting this now. It's still blocked by Yahoo not giving a damn.

**Comment by totolanister** [comment]
In yahoo account security page, you can create an "application password" to use in K9.
https://login.yahoo.com/account/security

So it seems they choose to deprecate XOAUTH2

**Comment by vdbhb59** [comment]
The app pwd stuff works.in case anyone faces issues, just clear cache, FC app and launch. It would work..

**Comment by DwayneJengSage** [comment]
Are there any instructions on how to use the "application password"? I can get one from Yahoo, but I can't figure out where to set it in K9.

**Comment by vdbhb59** [comment]
@DwayneJengSage Just use it in the password field, without any space. It will be normal password option.

**Comment by marscher** [comment]
I guess XOAUTH2 is dead by now. The application password options works like a charm.
