### ISSUE TITLE
Unable to send emails

### ISSUE THREAD

**Issue by zoff99** [k9mail/k-9#1706]
### Expected behavior
send email

### Actual behavior
i send emails, it should the spinning icon. jetzt nothing is sent, not indication of error is shown.
nothing to see in logcat

### Steps to reproduce
1. send email

### Environment
K-9 Mail version: 5.113 f-driod

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
You're on Android 6.0 so other applications can't get access to our logs.

If you have access to adb you can use that to get logs.

At minimum we will need some information about your mail provider to reproduce this.

**Comment by zoff99** [comment]
sorry 5.113 is a beta version? ok, then this was my mistake. sorry.

about the bug:
i have access to adb logcat output, but i did not see anything strange there.
my mail provider is IMAP via SSL/TLS on some hoster.
mail is not left in the outbox, it also is copied to my "sent" folder on the IMAP server ok.
it's just not sent.

**Comment by zoff99** [comment]
so suddenly this seems to work. maybe some network trouble. will close this, and reopen if it should happen again.
