### ISSUE TITLE
can not sign or encrypt pgp emails with openkeychains anymore

### ISSUE THREAD

**Issue by zoff99** [k9mail/k-9#1707]
### Expected behavior
sign or encrypt and outgoing email

### Actual behavior
says "no keys configured for signing, please check your settings"
i have not changed anything in openkeychains, or my keys!
this version of k9 is totally broken

### Steps to reproduce
1. try to send email, to address with key on file

### Environment
K-9 Mail version: 5.113 f-driod

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Again, no logs and a very limited explanation of what does happen instead. And given OpenKeychain is involved - the version for that might be useful.

Further more, given the behaviour you are critiquing is the same as the previous bug it probably was not necessary to open two.

**Comment by zoff99** [comment]
because there is just no error or crash. it does not even start the intent to unlock my keys.
give me a hint, how can i send usefull log infos?

openkeychain 4.1 (41010) -> latest from fdroid

**Comment by nuntius35** [comment]
Have you actually checked settings/account settings/cryptography/my keys if K-9 knows about your key? I recently updated via F-Droid from 5.010 to 5.113 and had to enter this key setting again.

**Comment by zoff99** [comment]
yes this fixed it.
but why do i need to do this? previous upgrades of k9 did not require this.
so it's a bug after all, i think.

thanks for the hint

**Comment by philipwhiuk** [comment]
I think the API has changed considerably between 5.010 and 5.113 - that's why. For the stable release we will probably put something in the release notes I expect.

**Comment by zoff99** [comment]
ok

**Comment by alanthehat** [comment]
I don't see this mentioned in either 'release notes' or 'changelog' that I've found on Github (both are outdated) & I didn't notice any message about it when I updated

**Comment by alanthehat** [comment]
I don't see this mentioned in either 'release notes' or 'changelog' that I've found on Github (both are outdated) & I didn't notice any message about it when I updated
