### ISSUE TITLE
Feature Request: Button "Folders" instead of "Order by" (Like in native Android app)

### ISSUE THREAD

**Issue by martin-adamek** [k9mail/k-9#1711]
I would appreciate possibility to set displaying of "show folder" button 
as one of main buttons, visible for one-tap using.

The same way, like it is in native android application.
There is "order by" button instead of it in K9mail.

I use K9 mail instead of native android mail app,
because K9 can refresh (download, sync) all folders in account,
and I use lot of folders 
(and filters, which are directing new messages into various sub-folders; 
and I need to read some sent or archived message sometimes).

So, I need to switch view between various folders very often.
And I absolutely do not use another ordering but a default newest top.

So I would like to have button "folders", as it is in default android app.
I have not found such possibility in settings.

K9mail is necessary for users with lot of folders,
so more users could appreciate that button, I think.

Thanks.

**Comment by philipwhiuk** [comment]
I'm not sure why the back arrow (top left) doesn't fulfil this purpose as it goes back to the folder list. But in any case the app needs a general design overhaul - this is just one more piece of the puzzle.

**Comment by martin-adamek** [comment]
I did not know that it is possible - when I switch the app on,
I am directly in main inbox folder (maybe by my settings, it is ideal for me),
so I did not have idea it is possible to go to the folder list by "back" button.
(Since  I came into the inbox from android home, not from folder list.)

Thanks for info, it looks as good way :)

**Comment by martin-adamek** [comment]
Although: I know now why I did not notice possibility to use "back" button:
It is not possible always. It works sometimes, and it does not work sometimes.
Because it takes me to desktop sometimes.
(I mean HW button "back";  SW button "back" in left top corner works).
Android 5, LG Wine.

**Comment by cketti** [comment]
The design overhaul will take care of this. I don't think we need an issue to remind us.
