### ISSUE TITLE
Forces sound on

### ISSUE THREAD

**Issue by KaybieRocket** [k9mail/k-9#1716]
### Expected behavior

Nothing unless there'sa new email. Then only vibrate notice when on vibrate
### Actual behavior

Turns phone sound on frequently, unless I change K9 settings to show no notifications
### Steps to reproduce

1.
2.
3.
### Environment

K-9 Mail version:

Android version:
Marshmallow on galaxy s7

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Please fill in the version.
