### ISSUE TITLE
encryption of mail attachments

### ISSUE THREAD

**Issue by damiencourousse** [k9mail/k-9#1719]
hello,

Currently using k9mail with APG on Android.
The files attached to a mail are not encrypted; only the contents of the mail is encrypted.

In other words, when attaching a file to a mail, and checking the 'encryption' check box, I would expect both the mail and its attachments to be encrypted.

regards,
Damien

### Environment
K-9 Mail version: 5.010
Android version: 5
Account type (IMAP, POP3, WebDAV/Exchange): IMAP
APG v1.1.1

**Comment by Valodim** [comment]
This is fixed on current dev branch, and released in the alpha channel. You can become an [alpha tester](https://github.com/k9mail/k-9/wiki/AlphaTester) if you want to test and help development. :)

**Comment by damiencourousse** [comment]
please re-open this issue,

Did an alpha-test with version 5.113 from the F-droid repo.
Encryption no longer works at all (mail attachment or not): in the account parameters, I see that k9-mail does not find any encryption tool :(  
APG is correctly installed and the previous version of k9-mail (5.010) was happily using APG for encryption.

best,

**Comment by cketti** [comment]
APG is no longer supported. Use OpenKeychain: https://www.openkeychain.org/

**Comment by damiencourousse** [comment]
Le 16/10/2016 à 20:23, cketti a écrit :
> APG is no longer supported. Use OpenKeychain: https://www.openkeychain.org/
> 

Thank you for your feedback.  I did a test with OpenKeychain, but I
cannot use encryption only without installing a GPG key on my device.

I would like to encrypt a mail or a file using a
public key available elsewhere, for example on a keyserver, and then the
encrypted message by mail, but without setting up a gpg key on my
android device. I don't need to be able to read a posteriori the sent
message on the android device.

The problem is that openkeychain requires that I setup a gpg key on my
android device.  I don't want to import in my Android device the gpg key
I use on my regular mail address.

I could setup a dedicated mail address for this specific use case, but I
consider that my smartphone is a disposable thing, because I could loose
it or it could be stolen.  In this case, with the gpg key used for
encryption, someone else could access the encrypted data a posteriori.

So, tell me if I am wrong, but, for this use case at least, the best
option is to encrypt data without setting up a gpg key on the android
device.  As far as I saw, this is currently not possible in k9-mail with
openkeychain.

Would you have suggestions for this kind of usage ?

thank you again,
Damien

**Comment by cketti** [comment]
Encrypting without signing is not something the new version of K-9 Mail will support.
Please use the [mailing list](http://groups.google.com/group/k-9-mail) if you wish to discuss this further.
