### ISSUE TITLE
Support for Tutanota (Open Source Mailprovider)

### ISSUE THREAD

**Issue by JohnnyCalavera** [k9mail/k-9#1722]
I'd like to see k-9 accessing my Tutanota Accounts. (https://tutanota.com)
They do not support IMAP nor POP3 because it would break their end-to-end encryption solution, but fortunately everything they do is Open Source. (https://github.com/tutao/tutanota/)
You will find a short tutorial on their github page with the title "Building and running your own Tutanota Android app" which should be really helpful for you guys =)

**Comment by cketti** [comment]
Implementing and maintaining support for obscure protocols is not the best use of our time. If someone were really determined they could implement a plugin interface to allow third party apps to supply the protocol implementation. But I don't see this happening.
