### ISSUE TITLE
Suggestion: Material Icon

### ISSUE THREAD

**Issue by moctodot** [k9mail/k-9#1723]
**Edit:**

New Icon:

![web_res](https://cloud.githubusercontent.com/assets/22890589/21390343/c17adb48-c786-11e6-87bf-c7b271a5054a.png)

Banner:

![playstore_banner](https://cloud.githubusercontent.com/assets/22890589/21390364/d83daaf4-c786-11e6-9a70-69605f53e1fe.png)

Source files: [graphics.zip](https://github.com/k9mail/k-9/files/666390/graphics.zip)

**Old post:**

I saw some pull requests about this recently so I gave it a try:

![k-9_mail_web_res](https://cloud.githubusercontent.com/assets/22890589/19442487/bfd69fa0-9489-11e6-815e-f4cca41a093e.png)

It's kind of tricky to stick with the robot dog design and this is the best I could come up with. I'd also be happy to visualize some other ideas or chnage some aspects of the icon.

If you like it say the word and I'll create a pull request with all the files ; )

**Comment by ArchangeGabriel** [comment]
From an user perspective: looks very nice. :)

**Comment by moctodot** [comment]
@ArchangeGabriel thanks 👍

**Comment by cketti** [comment]
A couple of thoughts:
* I'm not sure the aspect ratio works. Have you tried making the head not square?
* The ears don't look like antennas.
* Maybe look at other versions of K9 for further inspiration, e.g. https://upload.wikimedia.org/wikipedia/en/0/0d/K-9_hovering.jpg

**Comment by moctodot** [comment]
My issue with adding the antennas was that it doesn't really look like a dog anymore. I tried to strip it down to the most recognizable elements in order to put some focus on the email part. Maybe a different shape will help. I'll post as soon as I get something that looks decent :)

**Comment by drcouzelis** [comment]
I love your icon idea! Especially the envelope eyes. 

Consider simplifying it even more by using only the eyes and nose. Horizontal lines can be added to make it more unique and K-9 like, as can be seen here: https://goo.gl/images/kRF55v

Here is an amazing example of what I'm thinking, so you can see it in its full glory. :D 

![k-9 icon-small](https://cloud.githubusercontent.com/assets/184875/19524491/ec916ea4-95eb-11e6-88e4-9497e8143a60.png)

**Comment by Valodim** [comment]
I actually like this icon! My first thought was about the aspect ratio as well. Does that work as a square?

I don't really care about the antenna ears - in fact when cketti mentioned it, I had to check out the current k9 icon because I had never consciously perceived the antennas.

**Comment by drcouzelis** [comment]
I just realized, K-9 Mail already has a pretty mail icon - in the widget. 

![_20161025_095454](https://cloud.githubusercontent.com/assets/184875/19689499/99609fca-9a9b-11e6-8dbb-d9f1218dc203.JPG)

I think all it needs is the top half colored K-9 Red and the bottom K-9 Gray.

**Comment by ChriKn** [comment]
I find this new version great.
I allready changed the default icon to it using Nova. Thanks !

**Comment by moctodot** [comment]
How about this?
![k-9_mail_web_res2](https://cloud.githubusercontent.com/assets/22890589/20012146/52ef5e6c-a2ae-11e6-9949-95c500be676b.png)

**Comment by vt0r** [comment]
Both the first post squared version and this latest rounded version look really great to me, even if they don't have the antennae for ears. Just my $0.02

**Comment by paulle** [comment]
![mail_k9](https://cloud.githubusercontent.com/assets/4852079/20028795/6e00e152-a33b-11e6-9b50-406d4a751415.png)
I made this one for my private use.

**Comment by moctodot** [comment]
I also made a feature graphic matching the design of the icon:

![playstore_banner](https://cloud.githubusercontent.com/assets/22890589/20033436/945291ba-a3a0-11e6-8ce1-8f2c3d2f6022.png)

**Comment by Valodim** [comment]
This is really getting somewhere.

Asking for a friend, would you put the source online so others can dabble with it?

**Comment by moctodot** [comment]
Sure, here you go:

[graphics_inkscape.zip](https://github.com/k9mail/k-9/files/594803/graphics_inkscape.zip)

**Comment by bertob** [comment]
We're working on K9 for a university project, and most of the participants in our user studies complained about the icon (mostly about it being ugly and incomprehensible because it's not clear how it is related to email). In order to address these issues we tried to simplify and modernize the icon a bit.

![k9-icon](https://cloud.githubusercontent.com/assets/1908896/21718065/17e1bf8e-d415-11e6-805e-e0f94ab5e8c9.png)

This is just a concept, but if there's interest we can polish it and do a PR with all the necessary assets.
Here's a little comp to show how it would look on the homescreen:

![k9-homescreen](https://cloud.githubusercontent.com/assets/1908896/21718106/5af8d776-d415-11e6-8f5c-6ff197ae5338.png)

**Comment by cketti** [comment]
I have to admit that so far I'm not in love with any of the proposals. But I do like the work by @moctodot and bertob. Also, @Valodim pointed out to me that we don't have to find the perfect icon right away. The proposed icons are a better fit than what we currently have :)
So for the next major K-9 Mail version I'd like to go with bertob's icon. 

@bertob: We'd love to get a pull request. Please make sure the icon follows the [material design guidelines for launcher icons](https://material.io/guidelines/style/icons.html#icons-product-icons) as closely as possible, especially regarding size/padding.

Thank you to everyone who took the time to create one or more icon proposals. You are awesome!
Please keep the suggestions coming.

As a quick introduction on how to do material design icons I found the following video quite helpful: https://www.youtube.com/watch?v=GiFV-xfW9pk

**Comment by bertob** [comment]
@cketti, thanks for the video link, that was very helpful, since the official documentation is not very detailed on some things.

![icon192](https://cloud.githubusercontent.com/assets/1908896/22042978/d1a69204-dd0d-11e6-80ea-e28dcf9c94ab.png)

I have redrawn the icon and adapted it a bit, trying to follow the icon grid and the rules for shadows and highlights as closely as possible. 

![icon-grid](https://cloud.githubusercontent.com/assets/1908896/22042975/cdc4d0d8-dd0d-11e6-93b3-25116ce61d25.png)

Pull request here: #2082

**Comment by dkieffer** [comment]
Here's another concept:

![screen shot 2017-02-02 at 10 27 54 am](https://cloud.githubusercontent.com/assets/6288440/22558163/59d71e66-e932-11e6-8a33-828de590e7b0.png)

**Comment by ChriKn** [comment]
Indeed Moctodot's version is the only one I even like (simple, material, beautiful)

While changing the icon, would a "materializing" be possible for the app itself ? There is a fork on xda which does this quite well without getting to deep into changes, but play store updates are great...
Just my 2 cents.

@skieffer, how is this material ? ;)

**Comment by levinus** [comment]
A complete material design rework of the app (or the discussion of it) is already in progress. #1859

**Comment by juliakorbut** [comment]
Hey everyone! Just a heads up. I've updated and released [my 2013 redesign project](https://github.com/k9mail/k-9/issues/645) into a separate repo you can find here: https://github.com/k9mail/k-9-design

It already includes user testing, high fidelity design for all screens, color themes, icon (in all sizes and optically corrected to fit a variety of devices and wallpaper colors), etc. @moctodot + other designers in this thread - feel free to contribute to it! Right now the biggest remaining ask is a centralized style guide, documentation, and annotating existing screens.

**Comment by gcalzo** [comment]
Please go back to the previous one, current on v5.400 is really ugly!
#2998

**Comment by kq01526** [comment]
The icon from @moctodot looks much better.
