### ISSUE TITLE
Tracking Security

### ISSUE THREAD

**Issue by koksnuss** [k9mail/k-9#1724]
### Expected behavior
When reading an email in plain text it should be impossible to track a reader via html.

### Actual behavior
When reading an email in plain text k9mail actually parses/follows html <audio> tags and makes tracking possible.

### Steps to reproduce
1. go to "https://emailprivacytester.com" and send yourself a test mail
2. open up the mail in k9mail and watch the html <audio> "trigger" instantly 
3. thats it. afaik html audio tags are not importent for text content of an email

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Duplicate of #712

**Comment by koksnuss** [comment]
ok, sorry for the duplicate. do you know when this will be fixed as it is no longer an issue on github?

**Comment by philipwhiuk** [comment]
In the next stable release.
