### ISSUE TITLE
Use 'Sender' field to provide on behalf of information

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1727]
### Expected behavior

A message with a **Sender** and a **From** field that are different should show in the Message View:

`{Sender} on behalf of {From}`

In the Message List I think just {From} is reasonable (current behaviour) - this is what Outlook does.
### Actual behavior

`{From}`
### Steps to reproduce

The only example I have of this is a meeting forwarded by someone using Outlook. However the fields usage is documented in https://tools.ietf.org/html/rfc4021#page-7
### Environment

K-9 Mail version: 5.114

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by rhari991** [comment]
I'd like to work on this.
