### ISSUE TITLE
Dual signed+encrypted messages not verifiable signature

### ISSUE THREAD

**Issue by lbdroid** [k9mail/k-9#1731]
### Expected behavior
1) Messages generated by k9mail with both signing and encryption enabled can be decryped, but not verified by roundcube+enigma.
2) Messages generated by roundcube+enigma with both signing and encryption can be decrypted, but not verified by k9mail.
3) In both cases, each is able to validate the signature of self-generated messages.

### Actual behavior
Neither is able to detect the presence of the signature generated by the other.

### Steps to reproduce
In either email client, generate an encrypted and signed message, read it from the other.

### Environment
K-9 Mail version: 1.114

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
Could you send an affected message from roundcube to me? -> look@my.amazin.horse

**Comment by lbdroid** [comment]
After a bit more experimenting, its feeling like it may not be a problem on k9mail's side.
I've added a third email client into the mix, thunderbird+enigmail.
Messages passed between k9 and thunderbird in both directions work flawlessly.
Messages passed from either k9 or thunderbird to roundcube fail signature verification.
Messages from roundcube pass signature verification on thunderbird, but not k9mail.
Everything still likes its own messages.

K9 --> TB (YES)
K9 --> RC (NO)
K9 --> K9 (YES)
TB --> TB (YES)
TB --> RC (NO)
TB --> K9 (YES)
RC --> TB (YES)
RC --> K9 (NO)
RC --> RC (YES)

Every failure involves roundcube.
It appears that thunderbird+enigmail is smart enough to figure it out anyway.

If you still want to see the messages, I can send them for you, otherwise (and regardless), I'm going to file an issue with roundcube and link back to this.

**Comment by Valodim** [comment]
I suspect this is a missing crc issue in ascii armor. This came up in a different place for me recently. Did you send an rc mail to me so I can inspect?

**Comment by lbdroid** [comment]
Roundcube has confirmed a problem on their side, which is fixed in git master. Once I switched to git master, these problems all disappeared. I sent you a test email from the affected rc 1.2.2 in case it could help with robustness.

**Comment by Valodim** [comment]
So what roundcube does here is that it creates clearsigned messages, and wraps them in an encrypted mime part. This is in essence a bastard between pgp/mime and pgp/inline, combining the worst of both worlds. I wonder what they do if you add an attachment?

Either way, while it would be possible to support this for robustness' sake, I firmly believe we should make a decision not to, making sure this format dies as quickly as possible. Closing this issue, if anyone disagrees feel free to reopen.

(btw, mutt doesn't verify the signature either)
