### ISSUE TITLE
GUI Improvement: (optionally) move "+" icon from accounts lists to menu.

### ISSUE THREAD

**Issue by cogano** [k9mail/k-9#1738]
### Expected behavior

The users usually do not add new email accounts very often and therefore the "+" icon
- takes place on the screen and is prone to tapping by accident.
- is easily confused with "create message" icon.

It affects mainly users not using "merged" inbox, who prefer to access the e-mail messages separately by account.

The "+" icon in the overview of email accounts could be optionally moved to the menu list (three dots). The remaining icons might be spread equally within the given space or some new icon for other often-used function be added.
### Actual behavior

See the attached image for the current status.
![screenshot_20161020-220622](https://cloud.githubusercontent.com/assets/7862150/19576363/033221ee-9713-11e6-9b82-0d6f2742bec7.png)
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1 (Samsung Galaxy S7)

**Comment by cketti** [comment]
This will change during the design overhaul. There's no need for a dedicated issue.
