### ISSUE TITLE
Lost sent mail

### ISSUE THREAD

**Issue by jjv43** [k9mail/k-9#1740]
### Expected behavior

Tell us what should happen. Emails in sent mail folder should stay there until deleted.
### Actual behavior

Tell us what happens instead. K-9 Mail started acting erratically last night. When it stabilized and I closed and reopened it, all of the emails in the Sent and Draft folders were gone.
### Steps to reproduce

1.Can't reproduce.
2.
3.
### Environment

K-9 Mail version:5.000

Android version:Fire OS 4.5.5.2

Account type (IMAP, POP3, WebDAV/Exchange):POP3

**Comment by philipwhiuk** [comment]
Per my comment in #1616 we need to roll out the latest stable to the Amazon app store. 5.000 is out of date.

**Comment by jjv43** [comment]
Do you know when you will be updating K-9 Mail on the Amazon Kindle? We are still on version 5.000.

Thank you.

John Veltri


On October 21, 2016 5:01:15 AM EDT, Philip <notifications@github.com> wrote:
>Per my comment in #1616 we need to roll out the latest stable to the
>Amazon app store. 5.000 is out of date.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1740#issuecomment-255330619

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bluepineapplegroup** [comment]
Was there a solution to this issue? I posted 3370 for similar challenges.  Upon updating to new stable version, did lost emails repopulate?  My version shows it is most recent.
