### ISSUE TITLE
no apparent way to set composition crypto default

### ISSUE THREAD

**Issue by lbdroid** [k9mail/k-9#1743]
### Expected behavior

Ability to set custom default crypto setting, I.e. 'none', 'sign only', etc.
Preferably setting per identity.
### Actual behavior

Always defaults to 'always sign, encrypt if possible'.
### Environment

K-9 Mail version: 5.114

Android version:
Any

Account type (IMAP, POP3, WebDAV/Exchange):
any

**Comment by francwalter** [comment]
At least could it be changed to default behaviour is not encrypt, not sign?
Mostly I dont sign and encrypt, so this is a bit unhandy for daily use.
Thank

**Comment by lbdroid** [comment]
Well, this has now been quite severely broken. Not you have to take extra steps to enable SIGN THE BLOODY MESSAGE.

Look, many times you need to send data that is not security sensitive, while being able to prove who it came from. In fact, the DEFAULT crypto setting SHOULD be SIGN, but DON'T ENCRYPT.

**Comment by Valodim** [comment]
[I disagree](https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html). But I'd be interested to hear what your reasoning for signing messages by default is. I've been discussing this with various people, and there are valid cases where a user explicitly wants to sign a specific mail. I have yet to hear a good case for signing by default. From my point of view, all people who tried to argue this so far found that their argument boiled down to either "but that's what you're *supposed* to do", or "but we use it as a poor man's key exchange mechanism".

That said, a "Don't encrypt opportunistically" setting might be useful for users who don't ever want to initiate an encrypted conversation, I might add that at some point. PRs welcome, too :)

**Comment by lbdroid** [comment]
Very simple;
1) Most messages are not security sensitive. I.e., eavesdropping doesn't really cause a problem. "I'm running late, can you pick up the package from the post office?"
2) The recipient may or may not be set up to decrypt messages, even if they have a key set. I.e., some email clients that they use, like k9mail up until quite recently. Or they recently reset their phone and haven't had a chance to add back their private key. Whatever the reason, not everybody is ALWAYS in a position to be able to decrypt.
3) The message, while not security sensitive, is important enough to not have to face problem of not being able to read it.
4) The recipient SHOULD have enough information available to verify the AUTHENTICITY of the message. I.e., this message really is from who it says it is from, rather than a hacked server or spoofed message trying to trick you into picking up a box of anthrax, or tricking you into leaving the house so it can be burglarized.

**Comment by Valodim** [comment]
Have you read my blog post? I don't think you have. Regardless, in the interest of not derailing this issue, please move to the recent thread on the [moderncrypto](https://moderncrypto.org/) ml for further discussion on the usefulness of sign-only.

**Comment by lbdroid** [comment]
So you would advocate for sending messages that can't be authenticated?

**Comment by Valodim** [comment]
Yeah no, sorry, that's not a level of discourse I'm interested to have a discussion in.

**Comment by lbdroid** [comment]
Then you accept my reasoning as valid.

**Comment by francwalter** [comment]
Maybe I am wrong, but with the last alpha version 5.115 I don't have the issue anymore.
I write an email, don't touch the lock-icon and no signature is attached and not attempt to encrypt is done. Like the default before.

**Comment by lbdroid** [comment]
Current version now requires you to hit menu, then sign, then acknowledge the idiotic warning screen. That is now 3 unnecessary touches it takes to send an email instead of just 2, or it won't even sign it.

**Comment by francwalter** [comment]
With "current version" you don't mean the 5.115, do you?

**Comment by lbdroid** [comment]
Unless they posted a newer version in the last few minutes...

**Comment by francwalter** [comment]
Did you check the setting "Support signing of unencrypte.." in the Cryptographic settings of the account?

**Comment by lbdroid** [comment]
Without that, the sign option doesn't even appear in the menu.

**Comment by francwalter** [comment]
I think I misunderstanded totally. My problem was, that I dont wanted to encrypt or sign and in the last official version I was always asked to disable encryption or input my key, when I just wanted to send a normal email.
This was the problem in this issue 1743 here, I guess. Only this.
Now with 5.115 this issue has gone I think. Maybe I am wrong. But I dont need to enter any key anymore or disable encryption before sending manually each time.

You want to sign and dont want to hit many times any silly help Popup.
I think this is a different issue then the issue here. Wrong?

**Comment by lbdroid** [comment]
Well, they are at least related, in that you should be able to set a default behavior that suits your own use.

**Comment by francwalter** [comment]
Cannot you just write a little code to ommit the message when firstly displayed oncely and push a pull request?

**Comment by lbdroid** [comment]
That would only save 1 touch, not all 3.

As far as making a pull request goes, it doesn't make any sense to learn the code of every single project that you want to make a trivial change to. The understanding is that I will deal with bug and minor feature requests against projects I maintain, and in exchange, others do the same for their projects.

**Comment by Valodim** [comment]
The popup should only be displayed twice, actually. Does it show up more often than that? If so, that's a bug.

**Comment by lbdroid** [comment]
Ok, seems to be that it only displays twice, but that doesn't fix the problem, since you still have to go into the menu and manually enable signature.

**Comment by lbdroid** [comment]
There is another thing that is particularly unclear with the new changes; what happens with signatures when you have it set to "encrypt if possible"? Does it sign the message to EVERYBODY? Or does it just sign it to those for whom you can encrypt?

-- I just tested it and it seems to only sign it to those for whom you can encrypt. I would also consider THAT to be broken, since you now CANNOT set it to encrypt where possible AND sign to all... and it doesn't tell you what it is going to try. FYI: Electronic signatures satisfy requirements for signed legal documents, at least here in Ontario, Canada. https://www.ontario.ca/laws/statute/00e17#BK12 -- which means that you MUST be ABLE to sign it for *ALL*.

**Comment by philipwhiuk** [comment]
> There is another thing that is particularly unclear with the new changes; what happens with signatures when you have it set to "encrypt if possible"? Does it sign the message to EVERYBODY? Or does it just sign it to those for whom you can encrypt?

> -- I just tested it and it seems to only sign it to those for whom you can encrypt.

That would be a bug, but this is not the right issue to raise it under. I'm going to delete / snip any further comments which don't relate to the original issue in the title.

**Comment by lbdroid** [comment]
My point is, however, that the entire way this aspect of k9mail works, is
completely broken.

Look how it's implemented in roundcube/enigma. Easily set user defaults,
and easily adjust per message.

**Comment by Valodim** [comment]
I pretty much disagree with everything you've been saying in the last couple of posts. The behavior is not going to change at least for the stable, and no amount of capslock is going to convince me otherwise. I will wait for user feedback, and continue work from there.

**Comment by lbdroid** [comment]
*I am* giving you user feedback.

**Comment by artoo-git** [comment]
Now, not sure this is the same issue. How comes that in 5.200 ( but I am sure I have notice this in the precious version) messages to ppl that are in my contacts are selected with the default "encrypt if possible". That seems unnecessary work for the user to have to bump in that warning popup every bloody time. Currently I'd say 2-5% of my contacts have public keys.

**Comment by lbdroid** [comment]
Its like this; if your email is to 20 of your contacts, and one of them has a public key, it means that to the one for which it has a public key, it will encrypt it, but not the others.

Its kind of a silly feature, since if you're sending the message to JUST ONE recipient UNENCRYPTED, then the encryption state of the rest of them doesn't matter -- the message HAS been sent unencrypted and therefore you must presume no longer a secret.

The reason I argue in this thread that you should have an optional default state of ALWAYS SIGN, is because it doesn't give you a false impression of secrecy when none exists, and EVERY recipient can validate a signature (though it may in some cases require steps), regardless of whether or not they have a public key. This, in the very least, can prove to them that the message really did come from you. The fact that somebody encrypted a message to you that isn't a secret means nothing, since any hacker can get their hands on the recipient's public key -- its WHY its called a PUBLIC key.

**Comment by Valodim** [comment]
That's the point of the "if possible" part. If there's no public key, it's not possible. Can you be more specific about what warning popup are you talking about? There should be no popup when you send a mail to a person who doesn't have a public key.

**Comment by lbdroid** [comment]
So now deleting messages that correctly point out how backwards your approach to security is?

Security through hiding the truth.

**Comment by Valodim** [comment]
I'd guess that it contained flame bait in your signature capslock style and hence got deleted, but I didn't even see that post before it got deleted by someone else.

The original matter at hand (encryption defaults) is still not fully resolved, but I doubt anything productive will come out of this particular issue.
