### ISSUE TITLE
Undermanned project

### ISSUE THREAD

**Issue by davidhedlund** [k9mail/k-9#1744]
At this writing there are 350 issues open, a clear indicator that this project need more pull requests from more people to keep the project stable.

**Comment by davidhedlund** [comment]
[mylabel:help wanted](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Ahelp wanted%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by cketti** [comment]
Welcome to the world of open source.

**Comment by davidhedlund** [comment]
@cketti [mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by cketti** [comment]
Spamming the issue tracker is not helping. If you wish to contribute please do so by sending pull requests.

**Comment by davidhedlund** [comment]
@cketti Ok.
