### ISSUE TITLE
Cryptography: No OpenPGP app installed

### ISSUE THREAD

**Issue by bclermont** [k9mail/k-9#1746]
I just joined beta and now it can't see APG is installed.

If I check an account settings, the cryptography setting is grey and it display "No OpenPGP app installed".
In the non-beta version that used to works.

### Steps to reproduce
1. Install and configure APG
2. Install and configure K-9
3. Try to  configure PGP for an account

### Environment
K-9 Mail version: 5.113

Android version: 6.0.1 (CM 13)

**Comment by philipwhiuk** [comment]
APG is insecure and not supported in unstable and future releases
