### ISSUE TITLE
setup new email account programmatically

### ISSUE THREAD

**Issue by akgprcom** [k9mail/k-9#1750]
I need your help to setup new email account programmatically (map - smtp) ?

**Comment by cketti** [comment]
That's not something that is currently supported. What's your use case for this?

**Comment by akgprcom** [comment]
I have mail server and I want the client create and login to email using the app

**Comment by cketti** [comment]
I don't see how you need to programmatically create accounts in K-9 Mail for that. Sounds like you want #865.
