### ISSUE TITLE
Tor Hidden Service support

### ISSUE THREAD

**Issue by wldhx** [k9mail/k-9#1751]
### Expected behavior
Tor HS (`.onion` domains) should be usable as SMTP/IMAP/POP3 servers.

### Actual behavior
Upon entering a HS domain in the appropriate setup wizard / account settings field and saving a
>Cannot connect to server. (Unable to connect.)

window appears, though browser opens `.onion` domains fine (for reference, Orbot VPN is used for transparent torification).

I could also provide adb logs if necessary.

### Steps to reproduce
1. Enter a HS domain in setup wizard.
2. Get an error message.

Some email providers offering HSs: https://mailbox.org, http://lelantoss7bcnwbv.onion, https://riseup.net

### Environment
K-9 Mail version: 5.010 and 5.114

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): only tested with IMAP.

**Comment by philipwhiuk** [comment]
I think the best practice for this is to implement proxy support ( #704 ) and then selecting Orbot as the proxy?

If you think that'll be insufficient please provide further info.

**Comment by wldhx** [comment]
Well, I'm mostly concerned that HSs don't "just work" with transparent torification. I don't see a real need to treat `.onion` domains anyhow differently than normal ones, but #704 could work as well, right.

Interestingly, https://conversations.im also requires explicit "Connect with Tor" checkbox ticked to work with HSs; I wonder if it has anything to do with how some networking library / Android API does things - will try to dig around the code a little and see.

**Comment by wldhx** [comment]
...and apparently it does: it's just that (obviously) normal DNS servers don't resolve `.onion`, and Orbot seemingly doesn't set its own.

**Comment by wldhx** [comment]
...or it [actually does](https://github.com/n8fr8/orbot/blob/330860216a27897aa4c1dd943ea8375af78f889a/orbotservice/src/main/java/org/torproject/android/service/vpn/OrbotVpnManager.java#L345), but my phone's DNS for some reason stays as set by network.

Anyway, K-9 does the right thing by [just using std Android APIs](https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java#L185) (and getting an `UnknownHostException`), so that's out of scope - I'll have to look what Orbot's doing in more detail.

So, closing as things not "just working" is covered by ^, and explicit support by #704.

**Comment by mirsamantajbakhsh** [comment]
Check my commit. I also added a check for onion address existence in host names.

SOCKS proxy support added
#3889

Read more at:
https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/
