### ISSUE TITLE
Refactor notification code

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1754]
With Android 7.0 there's no longer a clear distinction between "device notifications" (summary) and "wear notifications" (individual messages). So we should rename the classes and identifiers we use internally.

I also want to refactor the notification code to make it less awkward to test.

**Comment by philipwhiuk** [comment]
Also the device notifications class really only seems to generate  New Mail notifications - other types of notifications are handled separately. That makes it more confusing to reason about.
