### ISSUE TITLE
"Send Later" functionality to schedule the date/time for sending an email.

### ISSUE THREAD

**Issue by KroRob** [k9mail/k-9#1756]
Please add "Send Later" functionality to schedule the date/time for sending an email.

**Comment by lbdroid** [comment]
It should notify the user clearly if the sending fails.

**Comment by leoj3n** [comment]
Personally, I miss the "undo" send feature of Gmail, but would settle for a scheduled send.

Thanks!

**Comment by cketti** [comment]
Duplicate of #688
