### ISSUE TITLE
CC and BCC button

### ISSUE THREAD

**Issue by SecTec** [k9mail/k-9#1771]
Hi,
is there a Button in v5.114 to show the CC and the BCC fields when writing an email? If no, please reimplement it as in the 5.0xx series.

**Comment by cketti** [comment]
Press the 'down' arrow next to the "To" field.

Next time please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by SecTec** [comment]
Hey,
yesterday I found the 'down' arrow...
When you have the dark theme an black arrow on black ground is a little bit hard to see...

**Comment by Valodim** [comment]
This is already fixed, the arrow has isn't adjusted to the dark theme in the current release. Will be released soon :)
