### ISSUE TITLE
More securing sharing of files in Android via Content Provider

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#1777]
At first, please forgive me if I am asking for a feature, which has already been implemented.

In Android >= 5.0 you can use a more secure way of sharing data by using [Content Providers](https://developer.android.com/guide/topics/providers/content-providers.html). With them you can give the app (& only this app), which receives the file **temporary** access permissions.
Thus this is a security enhancement.

It might however not work for older apps, which do not support these Content Providers (properly). However a quite large commercial app called [Threema](https://threema.ch) uses Content Providers in this way and so it seems that most apps seem to be compatible as otherwise users would complain, which would be very bad for a commercial app.

**Comment by philipwhiuk** [comment]
We use content providers in (at minimum) the master branch. I don't think there's more work to be done here. @cketti did some work with content resolution to fix various vulnerabilities ( https://github.com/cketti/SafeContentResolver ) 

Closing as next stable, although it might all be in the last release too.
