### ISSUE TITLE
Legacy inline PGP claims "signature made by wrong key"

### ISSUE THREAD

**Issue by ar-** [k9mail/k-9#1779]
### Expected behavior
Inline PGP should be accepted correctly (or not at all).

### Actual behavior
Inline PGP email is encrypted and signed with the same key-pair. This message will be marked with a red lock saying "signature made by wrong key". Sending the same message with a current version of K9 and using PGP/MIME and using the same key-pair shows the message green.

### Steps to reproduce
1. Use only 1 key pair. Send [encrypted and] signed email to self using the current stable version, which uses only inline PGP.
2. Use the same key-pair with v5.114 (alpha). Send a message with the same key pair again.
3. The new version marks the email send via Inline PGP (with the old version) as wrong, while only the one with MIME PGP is marked correctly.

### Environment
K-9 Mail version: v5.114 (alpha)

Android version: 4.4.4 Kernel 3.0.101

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
"Signature made by wrong key" means that the key that signed the mail did not have a user id that matched the actual sender address.

**Comment by ar-** [comment]
Oh my bad. The email was sent from the same account but with a different sending address. It actually functions correct.

Nevertheless there is an error in the current stable version. Can we assume that to be fixed, since it works correctly in the current alpha?

I just doublechecked it. The current stable version accepts signatures from invalid sending addresses when PGP/MIME is used. .... That's why this issue came up. Just misinterpreted the result.

**Comment by Valodim** [comment]
If it works in the beta, then yes it is fixed :)
