### ISSUE TITLE
K-9 Keeps loosing my account settings

### ISSUE THREAD

**Issue by jdmulloy** [k9mail/k-9#1782]
This is the second time this has happened. I open K-9 and I'm greeted with the account setup screen. As far as I can tell my account and all settings are gone. I suspect this may have happened during an app update, but I don't know when an update may have occurred or when it broke.

### Environment
K-9 Mail version: 5.010

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, Dovecot

**Comment by cketti** [comment]
See #750. Nothing we can do without more information.
