### ISSUE TITLE
WEBDAV is broken on Android Nougat with K-9 Mail v5.010 (stable)

### ISSUE THREAD

**Issue by markusb68** [k9mail/k-9#1784]
Went from Nexus 10 (Android 5.1.1 Build LMY49J) to NEXUS 9 (7.0.0 Build NRD91N, Nov 2016))
Both were routed so I used Titanium Backup and moved K-9 Mail v5.010.
I have 3 mail acounts 2x IMAP and one WEB-DAV using exchange (with a self signed cert)
The IMAP accounts are OK, but the WEBDAV account just reports Java exceptions.
Can't fetch new mails, nor can't change something in the mailserver settings.

Are there any known incompatibilities with Android 7 and webdav support?

Also tried the latest v5.114 (alpha). isn't better at all.
Setting up completely new gives the same result.
So it's not caused by using Titanium Backup. Besides I know that this config is working on Android 5.1.1

BR

Markus

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

If you wish to report a bug please make sure to set up a new account (restoring backups made on another device can cause all kind of issues) and provide a debug log. https://github.com/k9mail/k-9/wiki/LoggingErrors
