### ISSUE TITLE
Contact autocomplete doesn't work when forwarding email with attachments

### ISSUE THREAD

**Issue by agilob** [k9mail/k-9#1786]
### Steps to reproduce
1. Receive email with attachments
2. Download all attachments
3. Forward email
4. Start typing email of a contact
5. Finish typing email and accept
6. Contact name appears, but there was no autocomplete

Before sending email with attachment I sent the same without them and autocomplete worked for two recipients.

### Environment
K-9 Mail version: latest F-Droid

Android version: 4.2.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Works for me on Android 7.0. Think we are going to need a debug log to look into this.

**Comment by philipwhiuk** [comment]
Autocomplete tokens have changed completely in latest release. Please feel free to re-open if it doesn't work in 5.2x
