### ISSUE TITLE
download pic not include attachment

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#1787]
### Expected behavior
there are two pics,one is in the body and the other one is in attachment. 
I want just download only the pictures in the body, not in attachment.

### Actual behavior
download all include attachment

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by zhangxiaofan918** [comment]
@cketti sorry, I can't open the website https://groups.google.com/group/k-9-mail

**Comment by zhangxiaofan918** [comment]
solved.
