### ISSUE TITLE
specific smtp of alias

### ISSUE THREAD

**Issue by mxardre** [k9mail/k-9#1788]
Hi all and thanks very much for this nice app

I have a professionnal address link to a personnal adrdess. Basically the professionnal address forward the email to the personnal one. However to answer to the professionnal address I must go through a specific smtp which is different from the one of the personnal address.
I have created an identity with the personnal account and an alias with the professionnal account. 

Is there a way to specify the smtp of the alias?

Android version: 6.0.1

Account type IMAP:

**Comment by cketti** [comment]
See #1117
