### ISSUE TITLE
Insufficient information provided to diagnose configuration and certificate errors

### ISSUE THREAD

**Issue by ebenfield** [k9mail/k-9#1789]
### Expected behavior
K9 should connect to my email server

### Actual behaviour
K9 gives: Cannot connect to server (Unable to connect)

Initially it worked..although auto sync every minute didn't work. Googling that it at least one user reported that this problem was caused by setting up the account over wifi and was advised to set up with wifi off (yes..really !). So, I tried this, although k9 has no way of editing account settings that i can see, so I reinstalled and tried again with wifi off. Doesn't connect. Reinstall again and try over wifi again. Doesn't connect.. have tried repeatedly and I can't get it to connect. Have spent 2 hours or so with this. Connects using opera from desktop, the same connection is verified by https://www.wormly.com/test_pop3_mail_server as follows:

Resolving hostname...
Connecting...
S:+OK Dovecot ready.
C: CAPA
S:+OK
S:CAPA
S:TOP
S:UIDL
S:RESP-CODES
S:PIPELINING
S:AUTH-RESP-CODE
S:USER
S:SASL PLAIN LOGIN
S:.
C: USER ewan+telesense.co.uk
S:+OK
C: PASS XX_DELETED_XX
S:+OK Logged in.
C: QUIT
S:+OK Logging out.
POP3 test completed successfully.

Debug output:
11-11 12:50:40.085 I/k9      (26759): Loading preferences from DB into Storage
11-11 12:50:40.110 I/k9      (26759): Creating Storage database
11-11 12:50:40.126 I/k9      (26759): Preferences load took 41ms
11-11 12:50:40.126 I/k9      (26759): Preferences storage is zero-size, importing from Android-style preferences
11-11 12:50:40.127 I/k9      (26759): Committing preference changes
11-11 12:50:40.131 I/k9      (26759): Preferences commit took 4ms
11-11 12:50:40.141 I/k9      (26759): Registered: unmount receiver
11-11 12:50:40.141 I/k9      (26759): Registered: shutdown receiver
11-11 12:50:40.143 V/k9      (26759): Registering content resolver notifier
11-11 12:51:21.022 I/k9      (26759): Committing preference changes
11-11 12:51:21.040 I/k9      (26759): Preferences commit took 18ms
11-11 12:53:11.282 E/k9      (26759): Error while testing settings
11-11 12:53:11.282 E/k9      (26759): com.fsck.k9.mail.MessagingException: Unable to connect
11-11 12:53:11.282 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store$Pop3Folder.open(Pop3Store.java:396)
11-11 12:53:11.282 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store.checkSettings(Pop3Store.java:264)
11-11 12:53:11.282 E/k9      (26759): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
11-11 12:53:11.282 E/k9      (26759): Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
11-11 12:53:11.282 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
11-11 12:53:11.282 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
11-11 12:53:11.282 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
11-11 12:53:11.282 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store$Pop3Folder.open(Pop3Store.java:324)
11-11 12:53:11.282 E/k9      (26759): 	... 2 more
11-11 12:53:11.282 E/k9      (26759): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7bed948e40: Failure in SSL library, usually a protocol error
11-11 12:53:11.282 E/k9      (26759): error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0x7be36b9f76:0x00000000)
11-11 12:53:11.282 E/k9      (26759): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-11 12:53:11.282 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
11-11 12:53:11.282 E/k9      (26759): 	... 5 more
11-11 12:54:08.031 E/k9      (26759): Error while testing settings
11-11 12:54:08.031 E/k9      (26759): com.fsck.k9.mail.MessagingException: Unable to connect
11-11 12:54:08.031 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store$Pop3Folder.open(Pop3Store.java:396)
11-11 12:54:08.031 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store.checkSettings(Pop3Store.java:264)
11-11 12:54:08.031 E/k9      (26759): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)
11-11 12:54:08.031 E/k9      (26759): Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
11-11 12:54:08.031 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
11-11 12:54:08.031 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
11-11 12:54:08.031 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
11-11 12:54:08.031 E/k9      (26759): 	at com.fsck.k9.mail.store.Pop3Store$Pop3Folder.open(Pop3Store.java:324)
11-11 12:54:08.031 E/k9      (26759): 	... 2 more
11-11 12:54:08.031 E/k9      (26759): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7bd18c38c0: Failure in SSL library, usually a protocol error
11-11 12:54:08.031 E/k9      (26759): error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0x7be36b9f76:0x00000000)
11-11 12:54:08.031 E/k9      (26759): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-11 12:54:08.031 E/k9      (26759): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
11-11 12:54:08.031 E/k9      (26759): 	... 5 more

### Steps to reproduce
1. Enter 'Incoming Server Settings'
2. Click Next

### Environment
K-9 Mail version:

Android version: 7.0

Account type: Pop3

**Comment by ebenfield** [comment]
I'm confused by the certificate issue. Initially it rejected cert and I accepted manually, and it connected.

Having had the problems above it occurred to me that I could remove the accepted cert and try again. I did Security > Security > Clear Credentials and did once more see the option to manually accept the cert..however I was on wifi and wanted to try this without wifi. I quit and tried again without wifi... I've since been unable to get back to the failed certificate dialogue or anything other than the failure to connect. Debug log remains unchanged as far as I can see. 
Help gratefully received, I shall try not to waste any more time on this otherwise.

**Comment by ebenfield** [comment]
Tried on gmail with STARTTLS, it advised "Cert hostname not useable for server: telesense.co.uk"
Tried again with STARTTLS (accept all certs) and worked straight off.
So there's a cert problem.. K9 2+hours of trying... gmail < 5 mins

**Comment by philipwhiuk** [comment]
We need to spend some time improving the UX for handling TLS errors. In the debug log above I presume you used SSL/TLS?

We should probably recommend trying STARTTLS in that specific case (I've seen it when using Office 365).

In the bad certificate case I would hope we'd see a slightly different error which tells the app that it's a certificate issue.

**Comment by philipwhiuk** [comment]
As for account settings it definitely does allow you to configure connection info after setting an account up. Click on an account, settings, fetching mail.

However we have too many settings / they are badly organised. So I don't blame you for this.

**Comment by ebenfield** [comment]
Yes, I was using SSL/TLS. Wrt your comments I knew there was a cert problem after the dialogue saying there was a problem and my manual acceptance of the cert. But I expected that once I'd accepted the cert manually, that would be that. Not so....
Following manual acceptance I then had
Problem 1 - Although I could manually check and retrieve email, the auto-fetch every x minutes definitely didn't work.

As above, I then tried to (reinstall and) set up the account again with wifi off. This led to
Problem 2 - I couldn't repeat the cert approval, kept getting failed connection even though I was clearing certs with Apps > Security > Clear Credentials before reinstalling. I didn't see the option to manually accept again.

I need to get the the bottom of my own server cert problem, but as things stand I can accept certs and run with polling using both gmail and myMail but not with K9.

**Comment by ebenfield** [comment]
To use K9 I would need to know a/ How to manually accept again and b/ how to fix polling. I can't produce logs for b/ without fix for a/ of course. 
Cheers, Ewan

**Comment by ebenfield** [comment]
Ah, I can get further with STARTTLS, but password fail now.. will look into this and post further tomorrow.

**Comment by philipwhiuk** [comment]
As is, probably a mostly a duplicate of #893

But I'll leave it open because it contains a specific and slightly broader case than just certificate errors.

**Comment by childnode** [comment]
same here example STARTTLS on port 587 not selected but accidentially SSL/TLS
leads to misleading certificate error

### Environment

K-9 Mail version: 5.403

Android version: 7.1.1

Account type: SMTP STARTTLS needed

```
06-11 13:03:26.486 15101 15117 I MessagingController: Scanning folder 'K9MAIL_INTERNAL_OUTBOX' (4) for messages to send
06-11 13:03:26.487 15101 15117 I MessagingController: Send count for message K9LOCAL:f930f7b7-adfa-4b6c-a00e-7364e643497c is 2
06-11 13:03:26.513 15101 15117 V LockableDatabase: LockableDatabase: Transaction ended, took 13 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:257)
06-11 13:03:26.519 15101 15117 I MessagingController: Sending message with UID K9LOCAL:f930f7b7-adfa-4b6c-a00e-7364e643497c
06-11 13:03:26.520 15101 15117 D SmtpTransport: SMTP >>> QUIT
06-11 13:03:26.586 15101 15117 D SmtpTransport: SMTP >>> QUIT
06-11 13:03:26.598 15101 15117 E MessagingController: Failed to send message
06-11 13:03:26.598 15101 15117 E MessagingController: com.fsck.k9.mail.CertificateValidationException: Handshake failed
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.java:320)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessageTo(SmtpTransport.java:424)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.java:417)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:2607)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.controller.MessagingController$21.run(MessagingController.java:2491)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:203)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:121)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:172)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at java.lang.Thread.run(Thread.java:761)
06-11 13:03:26.598 15101 15117 E MessagingController: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.java:142)
06-11 13:03:26.598 15101 15117 E MessagingController: 	... 8 more
06-11 13:03:26.598 15101 15117 E MessagingController: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x96a71d00: Failure in SSL library, usually a protocol error
06-11 13:03:26.598 15101 15117 E MessagingController: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0xa50ce86a:0x00000000)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-11 13:03:26.598 15101 15117 E MessagingController: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
06-11 13:03:26.598 15101 15117 E MessagingController: 	... 11 more
06-11 13:03:26.614 15101 15117 V LockableDatabase: LockableDatabase: Transaction ended, took 5 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:257)
06-11 13:03:26.618 15101 15117 I MessagingController: Send count for message K9LOCAL:81e4a70b-e289-482d-b8ee-af14279730dc is 2
06-11 13:03:26.637 15101 15117 V LockableDatabase: LockableDatabase: Transaction ended, took 6 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:257)
06-11 13:03:26.640 15101 15117 I MessagingController: Sending message with UID K9LOCAL:81e4a70b-e289-482d-b8ee-af14279730dc
06-11 13:03:26.641 15101 15117 D SmtpTransport: SMTP >>> QUIT
06-11 13:03:26.696 15101 15117 D SmtpTransport: SMTP >>> QUIT
```

**Comment by molexx** [comment]
I have a similar but slightly different error connecting to IMAP using SSL on Android 8.0 (Samsung):

```
06-24 17:45:50.259 26984  2558 E MessagingControllerPush: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:434)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:690)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:652)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapConnection.setUpStreamsAndParserFromSocket(ImapConnection.java:236)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:120)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:773)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:731)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:720)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       ... 3 more
06-24 17:45:50.259 26984  2558 E MessagingControllerPush: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x71ac464b00: Failure in SSL library, usually a protocol error
06-24 17:45:50.259 26984  2558 E MessagingControllerPush: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/tls_record.c:522 0x71c832b200:0x00000001)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/handshake_client.c:889 0x71d6b720a6:0x00000000)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
06-24 17:45:50.259 26984  2558 E MessagingControllerPush:       ... 12 more
```

The GMail app can connect OK.
I'd like to use SSLLabs to get some more info but it won't test port 993.

**Comment by cketti** [comment]
See #893
