### ISSUE TITLE
Context menu of emails is too small

### ISSUE THREAD

**Issue by simonsmiley** [k9mail/k-9#1791]
The context menu that is displayed after a long press on an email is sometimes too small.

This happens because the menu is always limited in height based on where the email is. If the email is in the bottom of the screen, the menu is "rolled" upwards and fills all available space.

If however the email is in the top part, the menu is also rolled upwards and displays only one single entry. It's more or less unusable this way.

Ideally the menu would always fill the screen (or choose whether to roll up or down based on where the email is located)

I'm using a Nexus 6P, with the latest release from the google playstore.

**Comment by beckyichaos** [comment]
I would like to second this request. I am having the same issue on a new Google Pixel running 7.1.

**Comment by cketti** [comment]
Same as #1581?

**Comment by beckyichaos** [comment]
Yes, it is. Thank you. I commented on the first one I saw, but this is it as well.

On December 12, 2016 10:25:35 AM MST, cketti <notifications@github.com> wrote:
>Same as #1581?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1791#issuecomment-266493914

-- 
Sent from my Galaxy S4 with K-9 Mail. Please excuse my brevity.
