### ISSUE TITLE
Add feature to able to move message(s) from Trash to Inbox if accidentaly deleted it (them)

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1796]
### Expected behavior
Add feature to able to move message(s) from Trash to Inbox if accidentaly deleted it (them).
Using POP3 account.

### Actual behavior
You are not able to move messages (or chain of messages) from Trash to Inbox back.

### Steps to reproduce
1. POP3 account.
2. Delete one or chaing of messages

### Environment
K-9 Mail version: 5.010
Android version: 6.x
Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
It's not possible for emails to be sent to a POP3 server. So while it might be possible to move them to the Inbox on your device you couldn't get them on another device. It's just not possible with POP3 to add messages to the remote mailbox.

I've not had to study the POP3 implementation. Given that the default is to delete on download I assume that we maintain local copies of mails that aren't actually on the remote server. So it ought to be possible to move them back in theory. The 'Trash folder' isn't really a real folder in POP3 after all.

**Comment by z8k** [comment]
It's not about sending them to a POP3 server; it's about putting them back in the inbox when the all-too-easy-to-hit trash button gets pressed by accident when you're aiming for the < or > button on the toolbar. Just updating the local database to say which folder the downloaded, local copy of the message is in.

**Comment by ghsrcgh** [comment]
Yes, of course. POP3 is always locally deleted (or in case if there is option and it is set to do not delete from the server). So, it is required to just to move messages in the local database from one folder to another one folder. Because there is no any "hard-connection" with the server's messages copies. And it will solve all issue.

**Comment by ericblack44** [comment]
this makes k9 unusable IMO

**Comment by llvs** [comment]
Indeed unbelievable that it is impossible to undelete a message from Trash :dizzy_face:

**Comment by stimpy77** [comment]
This is driving me crazy. I keep fat fingering "Download full message" and accidentally deleting the message instead, this usually happens on my _most interesting_ or _important_ emails, and then the only way to get to it is by viewing it from Trash and then I **can't put it back!!** This is a POP account, the message is a local copy and not cleared from the server, so there isn't a technical reason why this **can't** be done.

**Comment by ajay-gh** [comment]
Hello cketti, 
it's fine to close a new issue with reference to an old one, but this old one is pending for 2 years, and the request is more than legitimate. I do not know of any other email client where a message cannot be moved from trash to another folder. ghsrcgh rightly points out that this is not about making changes to the POP3 server. It is about a very simple change to the local file structure. Any hope that this could be addressed soon ? 
All the best - AJ

**Comment by stimpy77** [comment]
It's also incredulous that someone went through and marked several of the on-topic comments as "spam", for which there is no recourse.

**Comment by llvs** [comment]
As it is 2020 now and the issue persists for more than three years already, is there hope that this issue will be addressed and users are able to move a message to a different folder?

**Comment by cketti** [comment]
Obsolete because of #4974
