### ISSUE TITLE
List Title garbled

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#1799]
### Expected behavior
In Inbox,the displayName and reply from text all show as garbled text like image.

### screenshot
![image](https://github.com/zhangxiaofan918/k-9/blob/master/images/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-11-17%20%E4%B8%8B%E5%8D%885.20.40.png)

### Actual behavior
show normal

### Steps to reproduce
just some user will appear it.

### Environment
K-9 Mail version:

Android version:5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
This is most likely an email that specified the wrong charset. In that case the sender's email client is to blame.
