### ISSUE TITLE
how to do download total mail at mail list

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#1801]
Before this, there are down load all mail button at mail view.But I want to down load total mail at mail list,what should I do?

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Account settings -> Fetching mail -> Fetch messages up to -> any size (no limit)

GitHub is not a support forum. This is also documented in the manual: https://k9mail.github.io/documentation/settings/account.html
