### ISSUE TITLE
Feature request: widget to disable sync

### ISSUE THREAD

**Issue by ddanesin** [k9mail/k-9#1802]
I would really appreciate a widget that can stop sync of one or all accounts.
This shoud be very useful to stop reading work email after my timeshift is finished...
and continue read my friends email!
I immagine a semaphore-like widget to keep in homepage that became red when inactive...

Thanks for this wonderful product!

Diego

**Comment by cketti** [comment]
This is not something I want to include in the app. It can probably be accomplished by a third-party app via the remote control interface already.
