### ISSUE TITLE
App screen does not fill the phone display from top to bottom 

### ISSUE THREAD

**Issue by Danelator** [k9mail/k-9#1803]
### Expected behavior
That the app would fit in the display top to bottom. 

### Actual behavior
There is a gap at the top and bottom where I can see the desktop behind the app. 

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by Danelator** [comment]
K9 5.115
Sony Z3 
Android 5.02
IMAP

**Comment by Danelator** [comment]
![_20161119_130758](https://cloud.githubusercontent.com/assets/23585603/20458551/17199780-ae5d-11e6-9af2-b9777af6daf3.JPG)

**Comment by cketti** [comment]
Looks like a problem with you device theme. This is not a K-9 Mail issue.

**Comment by Danelator** [comment]
Thank you. That was the issue.
