### ISSUE TITLE
Recurring errors after sending an email to a non-existing address

### ISSUE THREAD

**Issue by kuba-orlik** [k9mail/k-9#1810]
### Steps to reproduce
1. Send an email to a non-existing email address
2. See an error message in notification area (`ErrnoException: isConnected failed: ECON...`). // clicking on the notification opens up the "Folders" view and does not let me do anything with the failed email
3. Dismiss the notification
4. Notification appears few hours later

### Expected behavior
The errors should stop appearing

### Actual behavior
The error notifications keep appearing, days and days after the failed send attempt

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP/SMTP

**Comment by philipwhiuk** [comment]
Does the e-mail actually leave the Outbox?

Is there anything in k9mail-errors?

**Comment by kuba-orlik** [comment]
> Does the e-mail actually leave the Outbox?
I don't think so, as the email is incorrect. That's what I remember at least, as there's no way that I know of to check the body of the failing message.
> Is there anything in k9mail-errors?
No, it's empty for all accounts.

**Comment by philipwhiuk** [comment]
You should be able to delete the message from the Outbox if it's still there, to stop K-9 trying to send it.
