### ISSUE TITLE
Broken Link in docs

### ISSUE THREAD

**Issue by guettli** [k9mail/k-9#1811]
### Expected behavior
I click on the link, and I get to the matching page

### Actual behavior
404: file not found

### Steps to reproduce
1. https://k9mail.github.io/documentation/faq.html#anchor12
1. click on "developer wiki"
1. 404: file not found.
1. AFAIK this could be the correct link: https://github.com/k9mail/k-9/wiki
The broken link is: https://github.com/k9mail/wiki/

**Comment by cketti** [comment]
Fixed. https://github.com/k9mail/k9mail.github.io/commit/4b51d63d8427f38d55be97967abdd8deb8e65934

For future reference: issues with the website should be reported here: https://github.com/k9mail/k9mail.github.io/issues

**Comment by guettli** [comment]
Thank you
