### ISSUE TITLE
Pictures in the body of a message are not considered attachments

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#1812]
When I am in the mailing list, how to know the body text there is picture or not?

**Comment by narcisgarcia** [comment]
What do you mean with "the" mailing list?

**Comment by zhangxiaofan918** [comment]
@narcisgarcia `MessageListFragment.java`

**Comment by philipwhiuk** [comment]
K-9, like most mail clients does not consider images in the body of an email as an attachment. This is expected behaviour

**Comment by zhangxiaofan918** [comment]
于 2017年1月3日 GMT+08:00上午10:57:49, cketti<notifications@github.com> 写到:
