### ISSUE TITLE
Feature Request: Extend unread widget to choose any folder

### ISSUE THREAD

**Issue by helmo** [k9mail/k-9#1813]
### Expected behavior

When I add a "K-9 Unread 1x1" widget I would like to be able to select any folder.

### Actual behavior
The current version can only select an account... resulting in the unread count of the inbox.

### Environment
K-9 Mail version: v5.010

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): imap

This same behavior would be useful in #1600 which tries to show the contents of a folder in a widget. This issue is about the existing widget that just links to a folder.

**Comment by rhari991** [comment]
I'd like to work on this

**Comment by helmo** [comment]
by all means... please do.

**Comment by cketti** [comment]
Fixed by #2312

**Comment by dcolascione** [comment]
Did this feature regress? I just tried the widget and could select only the account, not the folder.
