### ISSUE TITLE
GaiException: android_getad

### ISSUE THREAD

**Issue by marteserede** [k9mail/k-9#1816]
### Expected behavior
See which emails I have in my inbox.

### Actual behavior
It says "Poll ...@...."  and then again just shows the email (in the header, below Inbox). If I then go back in the overview, below drafts and inbox, both it says "GaiException: android_getad"

### Environment
K-9 Mail version:
5.010
Android version:
6.0.1 MMB29M
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

My server settings are correct since when I put in different (wrong) settings it says unable to connect to server right away.

My device is a chinese Xiaomi Redmi 3S, which uses a special android version without google in general and google play services in particular which makes using some apps impossible (and installing google play services does not work). maybe it has something to do with that special android version?
![1982731205](https://cloud.githubusercontent.com/assets/10162138/20618253/fcc89914-b328-11e6-9061-541620264c40.jpg)

**Comment by philipwhiuk** [comment]
It'a a very cryptic message for a common problem, which is 'unable to contact server'.

Gai is 'GetAddressInfo' - basically DNS. We're showing the exception and the start of the message.

This is mainly a UI issue - our display of errors is currently very ugly.

If you go to the folder and poll for emails when you have a network connection it should be able to connect and update which will clear the meassage.

**Comment by cketti** [comment]
We can track this under #1058.
