### ISSUE TITLE
K9 looses connection to APG after update

### ISSUE THREAD

**Issue by xoir** [k9mail/k-9#1817]
I updated K9 5.010 to 5.115. I supposed the connection to APG (1.1.1) would stay untouched by the update. I was proven wrong. In the account-settings k9 is telling me now: "No OpebPGP App installed."

### Steps to reproduce
1. Install APG 1.1.1.
2. Install K9 5.115
3. Check wether APG is found by k9

### Environment
K-9 Mail version: 5.115

Android version: 6.01

Account type (IMAP, POP3, WebDAV/Exchange): differs (IMAP mostly)

**Comment by Valodim** [comment]
APG is insecure and unmaintained, and is no longer supported. Use [OpenKeychain](https://play.google.com/store/apps/details?id=org.sufficientlysecure.keychain).
