### ISSUE TITLE
Handle 'NIL' date response

### ISSUE THREAD

**Issue by jkehne** [k9mail/k-9#1819]
### Expected behavior
Refreshing a folder should make the server contents of that server appear in K-9

### Actual behavior
Synchronization runs for a few seconds, then aborts. The folder stays empty.

### Steps to reproduce
1. Navigate into "broken" folder
2. Swipe down
(I assume this problem depends on the IMAP server software. I'll be happy to help with testing.)

### Environment
K-9 Mail version: 5.115

Android version: 6.0.1 (CM13)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
Server Software: Zarafa 7.2.4

### Debug log
[k9-log.txt](https://github.com/k9mail/k-9/files/614218/k9-log.txt)
I removed email addresses and subject lines from all mails except the last one before the crash.

**Comment by philipwhiuk** [comment]
NIL is not an invalid value. It's the expected value when it's not available: https://tools.ietf.org/html/rfc3501#section-4.5

We need to check for NIL before trying to parse the date.

**Comment by Valodim** [comment]
If nil is not an invalid value, shouldn't it be handled in parseDate itself?

**Comment by philipwhiuk** [comment]
parseDate actually does the date parsing (i.e. it expects an actual date-time at that point). It's really a wrapper round SimpleDateFormat to copy with the various date formats we handle. 

I think adding it to `getDate` is fine.

**Comment by Valodim** [comment]
...to cope with the various date formats we handle.... like NIL? ;)

**Comment by philipwhiuk** [comment]
NIL's not a date format. It's basically the same as null - it's a spacer so the keys and values match up.
