### ISSUE TITLE
Inline PGP not recognized in mail when sent from Thunderbird on Windows

### ISSUE THREAD

**Issue by fbatschi** [k9mail/k-9#1823]
### Expected behavior
When an user on Windows encrypts an email with Thunderbird (newest version), Enigmail/GPG and sents it as Inline PGP, K9 Mail recognizes this mail as encrypted and opens the passphrase dialog of OpenKeychain to decrypt the message.

### Actual behavior
K9Mail does not recognize that the mail is encrypted and simply shows the encrypted mail body.

### Possible reason
It seems that additionalcharacters  "=20" are added after the "Version" header which do not appear when using other PGP Clients. K9Mail does not seem to be able to ignore or detect this. I am not sure whether this is a protocol violation on the side of Enigmail or K9Mail. This is what the source code of the encrypted mail body look like:

```
-----BEGIN PGP MESSAGE-----
Charset: utf-8
Version: GnuPG v2
=20
hQIMA0naAJOr8cb2AQ/8CwuirQ23bx4b8Hcn6w67qMOtMsxJt9vPtrGE4kzIwYVl
SbwXJC/YJa/hvaPlzN/wuz0NINTNstMT4RcLqPy6gKqg3bs7wyMSdqKge6CWaUlm
v68hMmwbvfjbJ4KKRd/IcsU4j9rmxw4aH1wh02q+2XBJmQTfdRcbCY3TOf2lUbpH
......
```

### Steps to reproduce
1. User A on Windows/Thunderbird/Enigmail sends encrypted email as inline PGP to User B with K9Mail 
2. K9Mail is unable to recognize the inline PGP in the mail body and does not show the decryption dialog

### Environment
K-9 Mail version: 5.115

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by puggan** [comment]
Is there an email-header for "Content-Transfer-Encoding" set to "quoted-printable"?

The line with "=20" are allowed to have whitespace, and "=20" is a "quoted-printable" version of space.
So if the message are flagged as quoted-printable, and if quoted-printable should be handled before the decrypt, then it look valid, but if the header is missing, or if decrypt should be handled before "quoted-printable" then its invalid.

**Comment by fbatschi** [comment]
Yes, it does have that header. 

Opening/Decrypting these kind of mails with Thunderbird and Enigmail is working fine.

It is also works, when I copy the full cyphertext from K9 Mail and paste it into OpenKeychain.
K9Mail just does not seem to recognize it as encrypted.

```
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

**Comment by Valodim** [comment]
I don't have a TB set up right now, can you send an email to me that shows this behavior? -> look@my.amazin.horse

**Comment by Valodim** [comment]
Got it. Thunderbird adds a newline before the inline markers. Pushing test cases and a fix soon. Thanks for the report!
