### ISSUE TITLE
Huge battery consumption

### ISSUE THREAD

**Issue by josegl** [k9mail/k-9#1829]
### Expected behavior
The battery consumption should be a magnitude order below the screen that it is the most battery drying source of a smartphone.
### Actual behavior
K-9 Mail has even more battery consumption that the screen by far, so much that it reduces the battery life from 4:30 h of screen use to around 3:00 hours.
### Steps to reproduce
I don't have done anything special, average usage, move email to IMAP folders, archive, delete,and so on.

### Environment
K-9 Mail version: 5.115

Android version: 6.01

Account type (IMAP, POP3, WebDAV/Exchange): 2 IMAP accounts

**Comment by philipwhiuk** [comment]
Logs would be useful here. K-9 does not normally use so much battery.

**Comment by josegl** [comment]
@philipwhiuk could you tell me please how could I log the behavior, I would like to contribute somehow. Power consumption remains very high. I use to have a lot of email every day, I handle all my subscriptions over the email and I move tons of emails through different folders, but I don't use the application so much to have a consumption that sometimes is over than the screen's. 

![screenshot_20161211-203027](https://cloud.githubusercontent.com/assets/6630934/21274712/d07e6062-c3c9-11e6-8df6-5424f7468680.png)

![screenshot_20161211-203011](https://cloud.githubusercontent.com/assets/6630934/21274724/ecd9118a-c3c9-11e6-9d27-daf77582c476.png)

**Comment by N-ik05** [comment]
Logging information can be found here https://github.com/k9mail/k-9/wiki/LoggingErrors.

I had huge battery drains like that, my problem was that my IMAP server had a timeout of 30 seconds or less. So it was reconnecting all the time.

**Comment by MarkusHLudwigsfeld** [comment]
Hi 

I recognized high battery consumption from k9 as well 
I used K9 version 5.208.
Android Version 6.0.1
Wake Lock Detector showed quite wakeup number >1500 over night.
I uninstalled k9 and there was really a big difference of battery consumption over night.

**Comment by hasufell** [comment]
Same here on Android 7, it's classified as "power-intensive app". I've just enabled debugging.

**Comment by hasufell** [comment]
I just looked at the logs and there is nothing really interesting. It only shows stuff when I *manually synced*. Auto-sync is __off__. The bits where it wastes battery are probably not logged.

https://git.io/vFfN5

**Comment by loneBruzzy** [comment]
Seems to be same issue as https://github.com/k9mail/k-9/issues/3027

Is there a way to link the issues here?

**Comment by cketti** [comment]
Not actionable.

**Comment by hasufell** [comment]
> Not actionable.

Lol what? Does that make it less of a bug? :)
