### ISSUE TITLE
Email lost when moving to different IMAP folder

### ISSUE THREAD

**Issue by nerian-vision** [k9mail/k-9#1831]
### Expected behavior

I have experienced problems moving emails from the inbox folder to a different IMAP folder. 

### Actual behavior

The mail was removed from inbox folder but didn't end up in the selected IMAP folder or any other folder. I was not a able to recover the email.

This has happened to me twice within the past two weeks after installing K9 mail on a new android phone.

### Steps to reproduce

I haven't yet found a way to reliably reproduce this bug. Both times this occurred I did the following:

* The email was open and I pressed the bottom right button  ("...")
* I selected the move option ("Umsortieren..." in the German localization)
* I selected the destination IMAP folder

Both times the email was part of an ongoing conversation with someone.

### Environment
K-9 Mail version: 5.010

Android version: 6.0 (with EMUI 4.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Can you please record a debug log when trying to move a message. Instructions here: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by nerian-vision** [comment]
Unfortunately I haven't been able to reproduce this problem again since submitting the bug report. I changed quite a few settings, not sure if any of this is related.
