### ISSUE TITLE
Older version request

### ISSUE THREAD

**Issue by stairway2heaven** [k9mail/k-9#1837]
Hi,

The project has been used as part of an experiment previously for an IEEE paper. We are currently trying to recreate the experiment but would require all the commits of version 3.902 to do so. Is there any possibility to get access to this ? Any help would be much appreciated.

**Comment by clawoflight** [comment]
This repository is very thoroughly tagged. You can find that version here:
https://github.com/k9mail/k-9/releases/tag/3.902

or simply `git checkout 3.902`

**Comment by Valodim** [comment]
That version is ancient. May I inquire what paper you are talking about?

Either way, closing this as invalid :)
