### ISSUE TITLE
Data Loss: Compose from Other App

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#1838]
### Expected behavior
Drafts started from other apps will be saved when See "saved as draft" alert. 

### Actual behavior
Draft is not saved. 

### Steps to reproduce
- In chrome browser, click an email address on a web page. 
- K9 opens compose window
- begin composing
- Switch away from message
- See "saved as draft" alert
- open K9 
- go to drafts folder. 

### Environment
K-9 Mail version:
Current as of today. 5.010?

Android version:
Will post

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by johnyradio** [comment]
Android firnware 4.1.2
Kernel 3.4.0

**Comment by cketti** [comment]
Is this still an issue with v5.201?

**Comment by johnyradio** [comment]
Yes, if sending from non-google IMAP account. 

No problem with gmail account.

**Comment by johnyradio** [comment]
Any chance this can be fixed?

Thx!

**Comment by johnyradio** [comment]
Hi, as the person who started this thread: turns out this is not an issue for me. I had an old account set as "default" account, so my drafts WERE getting saved, in the old account.
