### ISSUE TITLE
Very long time to setup connection at "Load up to 50 messages"

### ISSUE THREAD

**Issue by beta48** [k9mail/k-9#1839]
### Expected behavior
When pushing the button "Load up to 50 new mails" it is expected that K9 connects to the IMAP server and loads the messages (if there are new ones).

### Actual behavior
Since a couple of weeks, possibly after an update of all aps incl. K9: Not always but most of the time, K9 seems to struggel to connect to the IMAP server. That means that the circular icon "loading" is turning around about two minutes before mails are downloaded. My impression is, that this happens when the smartfone was idle for about one hour. If K-9 is manually shutdown during the connection attempt and then started again, it connects without problems very fast.

Some tests to locate the problem showed:
1. This is not a problem of the mobile phone provider (tested with O2 and Vodafone network cards). No change.
2. This is no general internet connection issue because:
2a. During the time where K9 was loading (circular icon), other internet access (such as weather apps) was possible, that means other apps do not have that problem.
2b. Using the Standard Android Mail app with the same IMAP box, there were no connection errors (not a problem of the Mail provider)
3. This problem seems to occur only with mobile network connection, not with WLAN connection
4. Activating Push with a refreshment period of 1h or 36 mins does not help.

### Steps to reproduce
1. Use K-9 version 5.010 on Galaxy S4 GT-I9505 Android 5.0.1
2. Setup IMAP mailbox with SSL and accept certificate
3. Deactivate all sync functions, let the smartfone be idle and the manually sny inbox after 1 hour
4. If it works the 1st time, please retry a 2nd or 3rd time. I am not sure, if the idle time is the actual problem trigger.

### Environment
K-9 Mail version: 5.010

Android version: 5.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Possibly caused by database issues similar to #1825. Hard to know without logs.
