### ISSUE TITLE
Mark deleted mails as "read"

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#1840]
This is a suggestion.

### Expected behavior
Move mail to trash **and** mark as "read".

This is how it is done by many mail programs.

### Actual behavior
Move mail to trash.

Often other programs afterwards show mails in the trash as "unread" when they were deleted by K9 mail.

### Steps to reproduce
1. Delete a mail.

**Comment by philipwhiuk** [comment]
Duplicate of #591
