### ISSUE TITLE
search hangs the app

### ISSUE THREAD

**Issue by takiainen** [k9mail/k-9#1851]
### Expected behavior
Searching emails should be pretty fast and snappy. It used to be like this.

### Actual behavior
Search takes several minutes and often just hangs the app. System says "app isn't responding". 

I'm running K9 on Android 7.1 (Nitrogen OS). My phone is Oneplus 
### Environment
K-9 Mail version:5.115

Android version: 7.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by takiainen** [comment]
Turns out this happends if I enable "Multiprocess WebView" from developer options. Once disabled the search works as expected.

**Comment by cketti** [comment]
Thanks for the update.

Pull requests to make K-9 Mail work better with "Multiprocess WebView" enabled are welcome. But we won't invest time into this.
