### ISSUE TITLE
How to delete messages permanently/disable trash folder

### ISSUE THREAD

**Issue by iminderN** [k9mail/k-9#1852]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
If you're asking a question, use the mailing list. If you're requesting a feature, fill out the issue properly.
