### ISSUE TITLE
K9 no longer works well on Amazon Fire

### ISSUE THREAD

**Issue by richardgmills** [k9mail/k-9#1855]
### Expected behavior
Deleted items should delete and stay deleted; items saved to Drafts should show up in Drafts; e-mails should open immediately, delete immediately, and return to Inbox immediately.

When I first got my Fire tablet, I recommended K9 to my cousin who has a Fire tablet, and she loved it.  Today, I mentioned losing the K9 draft, and she said she started having trouble with K9 "a long time ago" and stopped using it.  So it isn't just me nor my limited storage Fire.

### Actual behavior
I have to delete items dozens of times to get them to stay deleted; they reappear as read in both the Inbox and the Trash folders.  When I save an e-mail in progress to Drafts, it just disappears, and I have to start over.  It has started taking longer and longer for K9 to respond to anything I try to do with it, often going to black screen, returning to the Folders menu because it got stuck doing whatever I tried to get it to do, showing only the top half of the accounts screen or Inbox screen, or message screen.

### Steps to reproduce
1. Do anything on the Fire tablet.
2. Do anything on the Fire tablet.
3. Do anything on the Fire tablet.

### Environment
K-9 Mail version: 5.000 (upgrades don't seem to be available for Amazon Fire's K9)

Android version: Fire OS 5.3.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP and POP3

**Comment by philipwhiuk** [comment]
Without logs or any debug information this is just an unhelpful rant. I'm not sure if @cketti has the ability to push to the Amazon app store. If not then there's little we can do.

**Comment by richardgmills** [comment]
It wasn't a rant; it was a description of everything that has stopped working, verified by someone else who had the same problem.  The polite way to respond would be not to attack me but to tell me which logs and debug information you need and how to get them.  My description was all the things that were not working so you could know what needed to be done — either by you or by me.  Your reply was the unhelpful part — other than implying you no longer support the Amazon Fire version; in which case, you should remove it from the Amazon App store.
