### ISSUE TITLE
Imap access to outlook365 does not work properly

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#1858]
### Expected behavior
I am trying to access an outlook365 account (I have to because my work decided to outsource their IT infrastructure to the Microsoft Cloud) with K-9 via IMAP. The server settings are as follows:
server: outlook.office365.com
security: SSL/TLS
port: 993
authentication: normal password
auto detect IMAP namespace true IMAP path prefix  

I expect messages that I have marked as read to stay read and messages that I have stared to stay stared and messages whose star I have removed to remain "unstared"

### Actual behavior
Unfortunately, when I do any of the above operations (mark read, star, unstar) then the message is displayed as read, stared, unstared for a while but during one next few hours (or sometimes just minutes), read messages come back as unread, and stars disappear or reappear.

I also see the following errors for various sub-folders of the account in question:
```
K9-Mail version: 5.200-RC2
Device make: samsung
Device model: GT-I9195
Android version: 4.4.2

com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE "INBOX/Drafts"; response: #3# [BAD, User is authenticated but not connected.]
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:122)
        at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:626)
        at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:612)
        at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
        at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
        at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.openConnectionIfNecessary(ImapFolderPusher.java:330)
        at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:155)
        at java.lang.Thread.run(Thread.java:841)
```
[Here](https://github.com/mscdex/node-imap/issues/523) a similar problem was reported and a workaround could be to "limit the number of connections" as is discussed there. Would you at K-9 be willing to work on such a workaround? If not, is there anything else I could try to make outlook365 via IMAP work?

### Steps to reproduce
1. Set up an outlook365 accoun
2. Mark an unread message as read
3. Wait for it to come back as unread

### Further background
I have also tried to setup the account as an Exchange account together with the people from our IT without success.

Sending email via SMTP works without problems.

### Environment
K-9 Mail version: 5.200-RC2 (but problem already present in previous versions)

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
I use Outlook365 for the same reasons. My device doesn't have these problems.

A quick search suggests your password might well be wrong:

> The message “User is authenticated but not connected” is due to a bug in the Exchange server's IMAP implementation. If the client presents a valid user name but an invalid password, the server accepts the login, but subsequent commands fail with the aforementioned error message.

http://unix.stackexchange.com/questions/164823/user-is-authenticated-but-not-connected-after-changing-my-exchange-password

I'll leave this open because we probably will have to handle this broken bit of Exchange behaviour. :/

**Comment by cgogolin** [comment]
Yes, I am absolutely sure my password is correct. I have recreated the account several times, alone and together with a guy from the IT department.

It does allow me to send and receive emails normally, It is just the mark as (un)read and the (un)star functionality that doesn't work as expected. The [bug report](https://github.com/mscdex/node-imap/issues/523) I linked to above also observes the same error message despite the fact that the password used was verified as correct.

**Comment by cketti** [comment]
Looks like this can happen if there are too many connections to the Exchange server. https://github.com/mscdex/node-imap/issues/523#issuecomment-205012943

We know that our connection handling needs to get better. But that's not something we'll get to very soon.
