### ISSUE TITLE
Don't limit subject in message view to 3 lines

### ISSUE THREAD

**Issue by krihsna** [k9mail/k-9#1861]
5.200-rc2
ls-4001/lyf
android 5.1 aosp

if the subject is more than 3 lines occupying almost 50% of screen area, please find screenshot [z].

please implement any one of the following:

[q] remove subject on top of the e-mail.
[w] reduce the size of the subject.
[e] if you intend to keep both [ subject on top & subject w/ to & from e-mail address], please try not to occupy not more than 25% of screen area. i mean message body occupies nearly or almost 75% of screen area.
[r] introduce a button to increase the text size of e-mail body.

[z] http://m.imgur.com/TzujsMS

**Comment by philipwhiuk** [comment]
I don't understand why it's showing the subject twice. In my install we show the subject only in the bar at the top and the from address where you can see the subject again in bold.

**Comment by cketti** [comment]
@krihsna: There's already a setting under 'Global settings > Display > Font size > Messages > Subject'. Does that not work for you?

@philipwhiuk: The subject is displayed in the message header if it's too long to completely fit into the action bar.

**Comment by philipwhiuk** [comment]
Looking at the original message below it looks like it's being cut off again, albeit it after slightly more text. That's kind of lame. Maybe that text should wrap indefinitely.

**Comment by krihsna** [comment]
@cketti i have changed defaults in global settings & it is working properly. i was always concerned with account settings, i sincerely apologize for overlooking global account settings.

**Comment by cketti** [comment]
The subject may have been limited to 3 lines when the header was fixed. Now that it's scrollable I don't think the limit to 3 lines makes much sense.
