### ISSUE TITLE
Seeing Poor Performance When Connected to WIFI

### ISSUE THREAD

**Issue by Moondoggy51** [k9mail/k-9#1862]
### Expected behavior
Tell us what should happen
When my Verizon Droid Turbo phone or my  Nexus 7 is connected to a 1 GB AT& T WIFI connection any new emails arriving in my Gmail inbox should show up in my K-9 mail inbox and if a new message has arrived between polling intervals I should be able to perform a manual update and see the new email in my inbox almost immediately.

### Actual behavior
Tell us what happens instead
Frequently, new mail simply will not show up if I'm connected to WIFI despite the fact that the Gmail app from Google shows the new email in my inbox.  I can manually attempt to update my inbox and K-9 takes forever to query my inbox on the Google Server and it looks like it may be simply timing out and not connecting to the server but I have no proof of the timeout.  On the other hand, if I turn WIFI on my phone off and use my Verizon 4G connection K-9 immediately updates my mailbox with new mail.
### Steps to reproduce
1.  Turn WIFI On
2.  Send myself mail from a non-Gmail Web Email account I have and wait for email to show up in my Gmail App
3.  See if the email is also in my  K-9 Mail inbox and if not, attempt a manually update and see if the email does or does not show up.
4.  If and when the email does not show up in my K-9 Mail inbox after a manual update, turn WIFI off and switch to my Verizon 4G connection and  perform a manual update if K-9 mail does not immediately update my inbox automatically on it's own.

### Environment
K-9 Mail version:
5.010
Android version:
5.1 on my Droid Turbo and 4.4.4 on my Nexus 7
Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
There's nothing K-9 Mail does differently when connected to WiFi. Without a detailed analysis of what is going on exactly we have no idea how to improve the situation. However, this is not something that can be figured out remotely. Sorry :(
