### ISSUE TITLE
Attachment not encrypted with PGP

### ISSUE THREAD

**Issue by asterismo** [k9mail/k-9#1863]
When writing new email, attachment is not encrypted, only the text. This is a security issue.

**Comment by asterismo** [comment]
I'm using openkeychain as the pgp agent btw.

**Comment by Valodim** [comment]
Thanks for your report. What version of k-9 are you using? If you are not on the alpha channel, this is a known issue that is already fixed in an upcoming release. 

(There is a reason we have that template, btw)

**Comment by asterismo** [comment]
I'm using k-9 from Fdroid standard repository, in how long it would be upgraded in this repo? Thanks for your reply @Valodim

**Comment by cketti** [comment]
You should receive an update from F-Droid once we make an official release (soon).

**Comment by noplanman** [comment]
I think it's related to this issue:
Since the update to v5.200, K-9 doesn't decrypt an email with attachments any more.
The email text stays encrypted and the attachment can be opened.

Before the update, it was successfully decrypted, so a new bug or something must have slipped in 😕

**Comment by cketti** [comment]
@noplanman: Make sure OpenKeychain is selected as crypto provider and the correct key is configured. If it still doesn't work please open a new issue with exact steps on how to reproduce this.

**Comment by noplanman** [comment]
@cketti Seems like I'm having this issue with just one email that I received and can't seem to reproduce it 😕 
If it does happen again, I'll open a new issue.
