### ISSUE TITLE
add possibility to disable progress-notifications

### ISSUE THREAD

**Issue by ar-** [k9mail/k-9#1866]
### Expected behavior
There must be an option to deactivate the progress notifications when fetching from an IMAP server.

### Actual behavior
Progress notifications cannot be deactivated.

### Steps to reproduce
1. Don't use push
2. Update all IMAP folders every 20 minutes
3. Get notifications every 20 minutes

### Environment
K-9 Mail version: Latest trunk

Android version: all

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### Extended reason / Explanation

I'm syncing my Phone notification to a watch. There are only 2 ways to filter the notifications to the watch. 1. In Android: Notification can be blocked per app. 2. In the watch-app that syncs the notifications to the watch. Also here I can only filter by application, but not by notification type. So there must be a way to disable specific notification types in K9 (like "fetching new emails"). Obviously, the notifications ABOUT NEW EMAILS of K9 are very important to be sent to the watch, so they should not be blocked.

When using IMAP PUSH it is all good. But push has only limited support with some IMAP servers. So sometimes it is necessary to set the timer, to fetch IMAP messages every 20 minutes. Problem : **That causes the smart watch to ring and vibrate every 20 minutes several times (for each IMAP folder) with a new notification ("updating folder XXX").**

**Comment by cketti** [comment]
There's already a setting. See https://k9mail.github.io/documentation/settings/account.html#sync-notifications
