### ISSUE TITLE
Remote Sent Not Syncing

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#1870]
### Expected behavior
In K9,  mail sent on Mac should be in the K9 Sent folder. 

### Actual behavior
In K9, the mail is not in the Sent folder. 

### Steps to reproduce
1. On Mac
2. send email. 
3. Check K9

### Environment
K-9 Mail version:
5.10

Android version:
Android firmware 4.1.2, kernel 3.4.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by johnyradio** [comment]
K9 5.010

**Comment by johnyradio** [comment]
Android firmware 4.1.2, kernel 3.4.0

**Comment by cketti** [comment]
Have you tried refreshing the Sent folder in K-9 Mail?

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by johnyradio** [comment]
Yes, tried that. 
Didn't work.
