### ISSUE TITLE
SMTP - STARTTLS before AUTH

### ISSUE THREAD

**Issue by lilianm** [k9mail/k-9#1872]
### Expected behavior
Use STARTTLS when is available before login, not after

> 220 smtp.xxxx Ready
< EHLO User
> 250-OK Ready
   250-STARTTLS
   250-AUTH LOGIN
   250 AUTH=LOGIN
< STARTTLS
> 250-OK Ready
   250-AUTH LOGIN
   250 AUTH=LOGIN
< AUTH LOGIN
.....

### Actual behavior
> 220 smtp.xxxx Ready
< EHLO User
> 250-OK Ready
   250-STARTTLS
   250-AUTH LOGIN
   250 AUTH=LOGIN
< AUTH LOGIN
> 538 Encryption required

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):
SMTP

**Comment by cketti** [comment]
Make sure to set 'Security' to 'STARTTLS', not 'None'.

**Comment by Valodim** [comment]
Can't this be auto detected? Why do we allow 'none' instead of checking for starttls on connect?

**Comment by lilianm** [comment]
My setting is set to STARTTLS.
Application try to start authentification before switch to secure connection using STARTTLS command

I things it's a very strange behavior

**Comment by cketti** [comment]
@lilianm What K-9 Mail version are you using? Is it an actual protocol log or only what you believe happens based on some observation?

**Comment by lilianm** [comment]
My bad.
I do new test and it's my mobile phone provider block the port.
I saw this session in my log but i don't come from application.

My apologize for this mistake. I read the code too and it's correct
