### ISSUE TITLE
Cannot connect to outgoing SMTP server for Gmail

### ISSUE THREAD

**Issue by ahmadaamer6** [k9mail/k-9#1873]
### Expected behavior
K-9 Mail should connect to the outgoing SMTP Server (Port 465, smtp.gmail.com) for Gmail.
### Actual behavior
When connecting my Gmail Account to K-9 Mail I get an error when checking outgoing SMTP Server Settings. (Port 465, smtp.gmail.com)

### Steps to reproduce
1.Open K-9 Mail
2.Add a Gmail account to K-9 Mail

### Environment
K-9 Mail version: v5.200-RC2

Android version: 6.0.1, ZTE ZMAX PRO

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (Gmail)

PS: I checked my router and Port 465 is not being blocked. I can log into my Gmail perfectly using any other app, but K-9 Mail.

**Comment by cketti** [comment]
This is most likely a problem with your network configuration and not K-9 Mail. Connecting to Gmail works fine for thousands of other people.

Check the debug log to find out what's going wrong exactly: https://github.com/k9mail/k-9/wiki/LoggingErrors
