### ISSUE TITLE
BB7 key info not detected

### ISSUE THREAD

**Issue by iminderN** [k9mail/k-9#1882]
### Expected behavior
K9 should be able to detect the 

### Actual behavior
I am using K9 and openkeychain as my pgp key provider. everything is working fine apart from the fact that all mails sent from a bb7 device show up on k9 as 'Not signed', even when they are signed and encrypted.

### Steps to reproduce
1. send a signed and encrypted mail from a bb7 device
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):
imap exchange

**Comment by cketti** [comment]
Not enough information provided.

**Comment by Valodim** [comment]
If you have a device that can produce affected mails, feel free to send one my way at look@my.amazin.horse, I'll have a look.
