### ISSUE TITLE
Display recipient address, not name, in compose fields if "Show correspondent names" is unchecked

### ISSUE THREAD

**Issue by smithfred** [k9mail/k-9#1884]
I have "Show correspondent names" unchecked in global settings. k-9 should display the email address in the To/CC/BCC fields, not the contact name (e.g. when a recipient is auto-completed from the user's contacts). Instead it displays e.g. Bob (Other).

### Environment
K-9 Mail version: 5.200

Android version: 7

**Comment by njeyaakili** [comment]
see #1207 for a (more) detailed description of this issue.
