### ISSUE TITLE
Pinch and zoom broken

### ISSUE THREAD

**Issue by echto** [k9mail/k-9#1886]
### Expected behavior
Zoom in on message and scroll around.

### Actual behavior 
Unable to scroll around message after zooming in.

### Steps to reproduce
1. Open email
2. Zoom in on body of message
3. Try to scroll to beginning of message

### Environment
K-9 Mail version: 5.200

Android version: 7.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Works for me. Can you provide more details on your type of phone. Please also check if this is an issue with all messages or only certain types of messages (text only vs. HTML, signed/encrypted messages, etc)

**Comment by cketti** [comment]
See #1908

**Comment by echto** [comment]
Sorry, been away from my phone. Glad to see someone else reported the problem.

On December 31, 2016 10:33:51 AM PST, cketti <notifications@github.com> wrote:
>Works for me. Can you provide more details on your type of phone.
>Please also check if this is an issue with all messages or only certain
>types of messages (text only vs. HTML, signed/encrypted messages, etc)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1886#issuecomment-269877072

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kripper** [comment]
See https://github.com/thundernest/k-9/issues/5789
