### ISSUE TITLE
Required to enter password to decrypt email

### ISSUE THREAD

**Issue by krihsna** [k9mail/k-9#1888]
k-9 5.200
ls-4001/lyf
android 5.1 w/out google play services
openkeychain 4.2 beta1

i have two e-mail, each e-mail has a separate encrypted key can created using openkeychain. i am using both e-mail ids on same device.

what did i do ?
forwarded an encrypted e-mail from v***@gmx.com to KR***@yahoo.com.

what is the outcome ?
when i click the yahoo e-mail it provides me a prompt to enter yahoo encryption password to view e-mail.
if i input yahoo encryption password, i am able to view e-mail.
if i click cancel, it shows error.

what did i except ?
open the e-mail w/out providing password.

what did i do ?
manually refreshed yahoo folder.
even after manually refreshing the issue persists.

other facts:
manually upload keys every week to key servers from openkeychain.
enabled in k-9 settings: support signing of unencrypted messages.

please find the screenshot links.

screenshot links:

[z] error decrypting e-mail http://m.imgur.com/uUVacBy
[x] e-mail in bulk folder http://m.imgur.com/Qt4l7uW
[c] prompts for password http://m.imgur.com/rJEDIwe

**Comment by Valodim** [comment]
Can you describe why you expect to be able to decrypt the mail without giving your password? Or otherwise, what are the places where you expect to be asked for your password, instead of in this situation?

**Comment by krihsna** [comment]
Can you describe why you expect to be able to decrypt the mail without giving your password?

i have always assumed that by uploading to key server, the recipient will be able to read the encrypted e-mail.


Or otherwise, what are the places where you expect to be asked for your password, instead of in this situation?

to edit, add or delete name, e-mail address, duration of key, subkey.
to send an encrypted e-mail.
to create a new key.
to revoke or delete an existing key.


other:

i always expect to input password to create a key or send an encrypted e-mail.

i did use thunderbird with enigmail on debian around three  years ago, but i have never came across like this situation.

**Comment by brunnre8** [comment]
That's not how encryption works...

Uploading to a key server provides the means to send encrypted messages *to you* so only you may decrypt it.
For this you need to unlock your secret key --> provide the password

The other thing you can do is *sign* the message.

Anyone can *verify* that you send the message, although it is sent in plain text so there's no encryption
