### ISSUE TITLE
Bug: contact name shown when "Show Correspondents Name" is unchecked in Global settings 

### ISSUE THREAD

**Issue by jhoc2000** [k9mail/k-9#1892]
### Expected behavior
When an email is being composed one should see the actual email address and not the correspondent's name when "Show Correspondents Name" is unchecked in the Global settings. 

### Actual behavior
The correspondent's name is shown in the To:, CC: and BCC: inputs instead of the email address. 

### Steps to reproduce
1. Global settings, 
2. Uncheck "Show Correspondents Name", 
3. Compose an email, 
4. Choose a correspondent in the To:, CC: or BCC: fields. 

### Environment
K-9 Mail version:
5.200
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
POP

**Comment by cketti** [comment]
That setting lives under the heading "Message lists" and therefore only affects the message list. Right now there are no plans to display email addresses instead of names in the screen to compose messages.

**Comment by dabear2** [comment]
This is a significant issue IMHO for two reasons.  1.  As jhoc2000 stated, it was functionality that was present in 5.1.x and now it's been removed / broken in 5.2.x.  and 2.  Consider if you have one contact with multiple emails (I  have some up to 12 emails addresses and more).  If it only shows the contact name, then it's not possible (or very complicated) to confirm which of the 12 it was.  And worse if you want to send it to multiple email addresses to that same contact.  then everything looks the same.  If your attention is distracted while entering the addresses, you might not recall which email address it was if it only shows you the name.

Please reconsider opening this up again and fixing it / putting it back the way it was in 5.1.

**Comment by dllud** [comment]
I have just faced the issue predicted by @dabear2
While sending an email to a contact with multiple email addresses, I erroneously sent him an email to his professional address instead of the personal one. I would have avoided this mistake if the email address was visible, like before in 5.1.x and virtually all other email clients I've ever used.
