### ISSUE TITLE
attachment are at the bottom of the e-mail instead of the top

### ISSUE THREAD

**Issue by wynick1** [k9mail/k-9#1895]
### Expected behavior
Tell us what should happen 
email attachments should appear at the top of the email

### Actual behavior
Tell us what happens instead 
since the upgrade released today the attachment are at the bottom of the e-mail. if its a long email trail it's a real pain to have to scroll all the way down! Would it be possible to revert back to having the attachment at the top please?

### Steps to reproduce
1. see above
2.
3.

### Environment
K-9 Mail version: 
v5.201

Android version: 
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): 
imap

**Comment by cketti** [comment]
We'll continue to tweak the message display to try to make it easier to read messages. But it's very unlikely that we'll be reverting to the old way of displaying attachments.

Collapsing quoted text will probably help to alleviate some of your scrolling pain. See issue #763.

**Comment by wynick1** [comment]
Thanks. Is there a way of installing the previous version of k9 I had up till today? 

Best regards
 
 
David
----------------------
David Wynick
Professor of Molecular Medicine
Joint Director of Research NBT and UHBristol
C24A, Medical Sciences Building
University Walk
Bristol BS8 1TD
Tel:           0117 3311417
Fax:          0117 3312288
E-mail: d.wynick@bristol.ac.uk

**Comment by wynick1** [comment]
apologies if I am just being dense but I don't see how to "Collapse quoted text" in a long e-mail as per your post above thus allowing me to easily access the attachment that is now at the bottom of the e-mail. Is ther a button or an easy way to do this?
Tx
David
