### ISSUE TITLE
5.201 - Email Text not displayed

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#1896]
### Expected behavior
Tell us what should happen

Email Text should be displayed

### Actual behavior
Tell us what happens instead

Content/Text of Email is not being displayed.
Is it of the signaure of the mail?
As it is from a public mailing list, I attach the mail
[[opensuse-factory] updating tumbleweed - best practices.zip](https://github.com/k9mail/k-9/files/679684/opensuse-factory.updating.tumbleweed.-.best.practices.zip)

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.201

Android version: 6.01 / S7 Edge

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
This message is displayed correctly for me in 5.201. It's possible the message got mangled during the database migration to 5.200 though.. can you try redownloading the message, and see if the error persists? You can do that by going to folder view, long-clicking a folder, then selecting "Clear local messages", which will cause all messages in that folder to be downloaded again.

**Comment by coogor** [comment]
No, the message arrived after database conversion. I cleaned the local files as recommended, but result is the same (see sreenshot).
The reason why I feel the encryption/signature is the problem - on a different mail I wanted to send I got the error message 'Connection to encryption service failed. Check the settings.... '. I was unable to send the mail. Although I have APG installed, K9 says 'no openPGP App installed'
![screenshot_20161231-173208](https://cloud.githubusercontent.com/assets/5717703/21578453/88da1054-cf80-11e6-8272-d3f4fff3ff52.png)

**Comment by Valodim** [comment]
APG is unmaintained and insecure. Support was dropped in 5.200

**Comment by coogor** [comment]
Alternative?

**Comment by Valodim** [comment]
use OpenKeychain instead.

**Comment by coogor** [comment]
Thanks for the hint! I installed OpenKeyChain, and afterwards the message is displayed correct! So it seems to be a missing dependency?

**Comment by cketti** [comment]
My guess is this happens when APG was selected as crypto provider before updating to 5.2xx. We should probably point out an incompatible crypto provider to the user when the app attempts to use it.

**Comment by philipwhiuk** [comment]
I thought we considered it the same as having no crypto provider - that certainly seemed to be the intent in the code?
