### ISSUE TITLE
Special Charakters in Subject

### ISSUE THREAD

**Issue by sebi112** [k9mail/k-9#1905]
### Expected behavior
Display ä ö or ß in subject

### Actual behavior
In the new Update Special Charakters Like ß or ä ö ü are Not Displayed right in the subject Line. It Display as Questionmark. In Body it Works. Also in old Version it is working.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:newest

Android version:6.1

Account type (IMAP, POP3, WebDAV/Exchange): Imap

**Comment by cketti** [comment]
This is probably a wrongly encoded message. Can you please use another email client that shows the raw message/headers and post the Subject header line?

**Comment by sebi112** [comment]
Here ist the Line with new k9 Version:
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----- =_hCMlk5MU0dWVcwYrkwV4vQ=="
Subject: (Geb�udebrand gro�), Wiefelstede, Metjendorf, Metjendorfer Landstra�e

**Comment by sebi112** [comment]
With old Version and in Gmail App oder Outlook all is Displayed correct

**Comment by cketti** [comment]
E-Mail headers may only contain ASCII characters. Special characters need to be encoded. See https://en.wikipedia.org/wiki/MIME#Encoded-Word

Gmail and Outlook may contain special handling for broken emails. K-9 Mail does not.
