### ISSUE TITLE
Crashes due to OOM while checking incoming messages

### ISSUE THREAD

**Issue by BurtonG** [k9mail/k-9#1911]
I've had K-9 Mail working for years.  With recent update, app not working, even when app is "closed", get "Unfortunately, K-9 Mail Has Stopped".

So not only does the app not work, I have no email server, the app is draining the battery, causing the smartphone to overheat.

I have uninstalled and reinstalled the app.

Is there a way to uninstall the offensive update?  If not, is there a way to uninstall and reinstall a stable version?

**Comment by Valodim** [comment]
What version did this happen in? 5.200 or 5.201? Did you click "Report" in the "Unfortunately" dialog so we get a stack trace from where the crash happened?

**Comment by reittila** [comment]
Like BurtoG I have used K9 from the day "I bought my Samsung Galaxy S". It has been allmost flawles but now version 5.201 reads mail quite randomly mostly not at all. This began rigth after the uppgrade to 5.201.
I run my own mail server and I can see that K9 logs in normally but doesn't read tha IMAP boxes.

**Comment by cketti** [comment]
@reittila: Please create a new issue and include a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors).

**Comment by reittila** [comment]
Tried to log with aLogCat but with no success

**Comment by Valodim** [comment]
Are you using android < 4.1? We might want to remove the reference to aLogCat from the debug log wiki page, there aren't that many android devices out there where this still works (even less from people who would report issues here)...

**Comment by reittila** [comment]
I'm using Android 6.0.1

**Comment by Valodim** [comment]
alogcat no longer works with android >= 4.1. Please try logging with adb.

**Comment by reittila** [comment]
An issue with log file created

**Comment by BurtonG** [comment]
I have now uninstalled and reinstalled several versions, just so I can have email.  Got 5.01 to work, went to sleep, awoke, and 5.201 was updated automatically for me.

I have many, many emails.  They are stored on GoDaddy's exchange server.

So while the new versions might work on low volume, possibly, they aren't working for me, and my many folders and messages.

While I have an exchange server, I have always used your IMAP interface.  Since this new version has been two years in the making, does that change?  Will your app really support exchange, or I still use IMAP?

**Comment by BurtonG** [comment]
Using Android 5.1.  Have now uninstalled and reinstalled your version 5.01.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by Valodim** [comment]
Sorry about the inconvenience. However, without a debug log it's almost impossible to fix issues such as this. If you sent a report from the "Unfortunately" dialog, we'll probably fix it some time soon, otherwise we'll have to wait until it happens and someone sends us a debug log.

**Comment by BurtonG** [comment]
I got the "unfortunately" message, and requested to send a report.  Is there anything more I can do to assist you?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by Valodim** [comment]
Nope, thanks. Can you look for the report @cketti?

**Comment by cketti** [comment]
There are a couple of OOMs when downloading messages. No other crashes I can see that could happen while the app is in the background.

**Comment by BurtonG** [comment]
Issue #1191.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by BurtonG** [comment]
Sorry.  It is #1911.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by BurtonG** [comment]
Not sure what an "OOM" is.  But I have your app set to look for new incoming messages every few minutes.  It probably does that and gets an error each time.  Wheither that is in the "background" or not.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by cketti** [comment]
OOM stands for "out of memory". Try downloading fewer messages. If that doesn't work try moving some messages out of your Inbox. It's possible that K-9 Mail chokes on one of them.

I'm afraid there's not much else we can do. Maybe a debug log can give additional insights: https://github.com/k9mail/k-9/wiki/LoggingErrors
If you manage to record one, please open a new issue.

**Comment by BurtonG** [comment]
I will move messages out if the inbox.  Do I need to stay on version 5.01, or can I upgrade to 5.20?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
• Burton Goldstein º b.g. communications, inc. º 301.548.9555
• 414 Chestnut Hill Street º Gaithersburg, Maryland 20878
• Burton@BGCommunications.com º www.BGCommunications.com
• telephony º audio º video º data -- since 1983
• commercial & residential telephone systems
• (Sent from my mobile device, where there is no spell check)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


-------- Original Message --------

**Comment by cketti** [comment]
If you downloaded a lot of messages upgrading from 5.010 will take a lot of time. It'll probably be faster to uninstall, then install 5.201. You can export and import your settings as described here: https://k9mail.github.io/documentation/settings/import_export.html

**Comment by BurtonG** [comment]
I am sitting down at my computer to move messages around.

Where did you see the “OOM” reference?  In the logs that I sent to you?

By using an Exchange email client service, if I am correct, the messages are stored on their server.  Not sure what if anything is actually downloaded to my device when I open K-9 Mail.

When I set up K-9 Mail, one of the first questions is whether the account is:  POP3, IMAP, or Exchange (ABCXYZ).  I don’t remember what the conditions were on if I can use my Exchange server, or have to pretend it is an IMAP server.  Have that been changed in this new version?  Can I be Exchange, or still have to be IMAP?

Thanks.

-------------------------------------------------------------------
    Burton Goldstein º b.g. communications, inc. º 301.548.9555
      414 Chestnut Hill Street º Gaithersburg, Maryland 20878
      Burton@BGCommunications.com<mailto:Burton@BGCommunications.com> º www.BGCommunications.com<http://www.bgcommunications.com/>
          telephony º audio º video º data -- since 1983
            commercial & residential telephone systems
-------------------------------------------------------------------

**Comment by cketti** [comment]
Sorry, this is not getting us closer to fixing any bugs. 
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for general support requests.
