### ISSUE TITLE
small context menu after upgrate to Nougat

### ISSUE THREAD

**Issue by D4nielB** [k9mail/k-9#1912]
### Expected behavior
Before I upgraded my OnePlus 3 to Nougat yesterday, when long-pressing on an email, K9 would open the context menu with the options to reply, forward, archive mail etc. on the full screen.

### Actual behavior
After the upgrade, the context menu is opened only in the lower right part of the screen instead of full screen. 

### Steps to reproduce
1. long-press on an email

### Environment
K-9 Mail version:
5.010

Android version:
7.0 (Nougat)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

![studio_20170102_115119](https://cloud.githubusercontent.com/assets/14359024/21588079/4ce5e8ac-d0e3-11e6-8faf-df96ae964f3d.jpg)

**Comment by D4nielB** [comment]
Just got 5.2x version from play store, issue seems to be fixed there, context menu is big enough now.

**Comment by cketti** [comment]
See #1581
