### ISSUE TITLE
Bad key for encryption: %s

### ISSUE THREAD

**Issue by DamienCassou** [k9mail/k-9#1913]
### Expected behavior

When sending an email to a contact with an outdated encryption subkey, I should get an error message explaining what failed and on which key.

### Actual behavior

Currently, a toast appears with message "Bad key for encryption: %s" which:

- does not tell me which key has a problem
- does not tell me what the problem is

### Steps to reproduce
1. compose an email to a contact with an outdated encryption subkey
2. press the send button
3. you get a toast with "Bad key for encryption: %s"

### Environment
- K-9 Mail version: 5.200
- Android version: 6.0.1
- OpenKeychain version: 4.1 (41010)

/cc @Valodim

**Comment by philipwhiuk** [comment]
This is a bug in OpenKeychain, not K-9. 

I've raised https://github.com/open-keychain/open-keychain/issues/1977 for you.

Closing.
