### ISSUE TITLE
SSL not working properly

### ISSUE THREAD

**Issue by eric-moreau** [k9mail/k-9#1916]
### Expected behavior
I have an IMAP account set up for a long time now.
It is set to work with SSL/TLS on port 993, with password encryption.
It's always been working fine so far.

### Actual behavior
Since last software update, it is not updating anymore (not receiving new messages).
K9 doesn't give any error message...
...but my server does.

The server is the popular AltN's "MDAEMON", on the latest version (16.5.2)
The server says in its log : 
SSL error 0x80090308 The token is not valid [translated from french].
(I understand that the error number belongs to MDAEMON of course)

### Steps to reproduce
I've tried to remove encryption : then, yes, it updates correctly.

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP with SSL/TLS

Thanks for your great job anyhow !!!

Eric

**Comment by yoshimo** [comment]
From the changelog

> Added support for Server Name Indication
> Disabled support for SSLv3 protocol/ciphers and all RC4 ciphers

Does the mailserver by chance use only outdated ciphers?
If you won't mind sharing the serveradress we could look for this.

**Comment by eric-moreau** [comment]
Sure : domain is « mail.chapka.fr ».

 

E.

 

De : yoshimo [mailto:notifications@github.com] 
Envoyé : lundi 2 janvier 2017 17:17
À : k9mail/k-9 <k-9@noreply.github.com>
Cc : eric-moreau <eric.moreau@free.fr>; Author <author@noreply.github.com>
Objet : Re: [k9mail/k-9] SSL not working properly (#1916)

 

From the changelog

Added support for Server Name Indication
Disabled support for SSLv3 protocol/ciphers and all RC4 ciphers

Does the mailserver by chance use only outdated ciphers?
If you won't mind sharing the serveradress we could look for this.

**Comment by ArchangeGabriel** [comment]
Yes, that’s the issue:
https://www.htbridge.com/ssl/?id=d39e283dd508274fff11a4430422811067634dd79ff6c9c298ac1481f068331d

**Comment by ArchangeGabriel** [comment]
You should not “remove encryption” (because that means your password is sent in PLAIN TEXT, i.e. world readable) but ask your system admin to upgrade the SSL configuration of this mail server.

**Comment by eric-moreau** [comment]
yeah right... thanks both of you.
I was using the mailserver's utility to create self-signed-certificate.
Does it means I should use some other system to produce this certificate : 
- a stronger cipher...
- a "real certificate", not self-signed also ?

E.

**Comment by ArchangeGabriel** [comment]
Regarding the certificate, I advise you to look at [Let’s Encrypt](https://letsencrypt.org). They provide free trusted certificates. Self-signed certificate can work to for you depending on your use case, but then rather use a SHA256 one instead of SHA1.

Regarding ciphers/SSL configuration, I advise you to look at your mail server software documentation or support. Not sure you can get any help here regarding “the popular AltN's "MDAEMON"”…
