### ISSUE TITLE
SMTP headers not accessible for HTML mail

### ISSUE THREAD

**Issue by Pinkyatacme** [k9mail/k-9#1918]
### Expected behavior
The "show headers" option should display the full header data for all emails.

### Actual behavior
For many HTML mails, only the sending client provided headers are shown. As these are the most commonly spoofed details, this is a serious oversight.

### Steps to reproduce
1. Open an HTML formatted email
2. Select the "show headers" option
3. Observe complete lack of SMTP conversation details

### Environment
K-9 Mail version:
5.201
Android version:
5.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Press the "Download complete message" button to download all headers.
