### ISSUE TITLE
K9 + Openkeychain = no automatic decryption and encryption as attachment

### ISSUE THREAD

**Issue by sorcer1122** [k9mail/k-9#1920]
### Expected behavior
Tell us what should happen
Issue 1: I suppose K9 should automatically decrypt all incoming emails once Openkeychain has been turned on in settings and private key is provided. Decryption works fine if I copy/paste the encrypted text into Openkeychain.

Issue 2: After encryption PGP raw data should come in the body of email, not as an attachment.

### Actual behavior
Tell us what happens instead
Issue 1: K9 does not automatically decrypt incoming emails, I only see raw pgp data + there is an icon in K9 saying email is not encrypted.

Issue 2: When I encrypt emails with K9+Openkeychain, the recipient receives a blank email with two attachments named 'Unknown Name', with my encrypted message inside. 

### Steps to reproduce
Issue 1:
1. Install latest K9
2. Install latest Openkeychain and import my private key + other people's public keys
3. In K9 settings select Openkeychain as pgp provider and also my private key
4. Asked my friend to email me, got encrypted email but K9 did not automatically decrypt it.

Issue 2:

1 and 3. same as above
4. Created a new email, selected the recipient from my contacts, the lock turned green indicating there is a public key for this recipient. I taped send, it asked me to enter my password and this is it

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): irrelevant, the issue is the same with any account

**Comment by Valodim** [comment]
This is intended behavior, following the PGP/MIME standard [rfc3156](https://tools.ietf.org/html/rfc3156). This actually puts an encrypted structure in the message, rather than just having it as the text body, which shows up in clients that don't support it as an attachment.

You can get the old behavior by enabling PGP/INLINE, and this should also be used automatically if you reply to such a message. Note that PGP/INLINE is only parsed right at the top of a message.

**Comment by sorcer1122** [comment]
I have enabled PGP/INLINE but the recipient on the other side cannot decrypt it. He receives an error saying he does not have a key to decrypt it. Any idea why is this?

**Comment by falematte** [comment]
Got the same problem. How to enable this?
