### ISSUE TITLE
Can't continue past Open Keychain dialog when recipient has more than one key

### ISSUE THREAD

**Issue by peterjanes** [k9mail/k-9#1924]
### Expected behavior
When a recipient has more than one key in Open Keychain, the correct one can be selected and the message sent.

### Actual behavior
Open Keychain opens and displays the list of keys. (All are pre-selected.) Tapping "OKAY" just redisplays the list, regardless of how many keys are selected or deselected.

### Steps to reproduce
1. Configure a user in Open Keychain with more than one key.
2. Compose a message to that user.
3. Tap the send button.
4. Select zero or more keys for the user in Open Keychain and tap "OKAY".
5. Observe results.

### Environment
K-9 Mail version: 5.201

Android version: Marshmallow

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by zoff99** [comment]
add your issue here:
https://github.com/open-keychain/open-keychain/issues/1942

**Comment by peterjanes** [comment]
Thanks. Wasn't sure if it was Open Keychain itself or K9 sending me back to it.
