### ISSUE TITLE
Encrypted but unsigned e-mail (sender has no keys but friend has encryption key)

### ISSUE THREAD

**Issue by J-J-Chiarella** [k9mail/k-9#1926]
This is similar to Issue #1683 K-9 Mail should allow sending encrypted but unsigned e-mail.

I am not advocating teaching people to separate signing and encryption as the project contributors wish to avoid.

I am content with the option in settings to sign unencrypted messages (useful for votes or official public announcements).

However, there should be a way to send encrypted but unsigned e-mail. Not the option to do so, mind. I am saying that people who don't care about encrypting stuff for themselves and don't sign or have not yet set up their own private key set should be able to send encrypted unsigned mail.

Here is what I am advocating:

1. If the sender has a private key with signing and is sending to a recipient with encryption keys (and the message is set to encrypt the message with the recipient's public key), then always sign with the sender's private signing key and encrypt with the recipient's public encryption key.

2. If the sender does not have a private key with signing (only an encryption subkey) or if the sender has no private keys at all and is sending to a recipient with encryption keys (and the message is set to encrypt the message with the recipient's public key), then K-9 and OpenKeychain should say "we can't sign and encrypt because there is no private signing key, but rather than trash this message we should at least encrypt it because we can."

The current process is this:

1. If the sender has a private key with signing and is sending to a recipient with encryption keys (and the message is set to encrypt the message with the recipient's public key), then always sign with the sender's private signing key and encrypt with the recipient's public encryption key.

2. If the sender does not have a private key with signing (only an encryption subkey) or if the sender has no private keys at all and is sending to a recipient with encryption keys (and the message is set to encrypt the message with the recipient's public key), then sending will fail.

I am an advocate of signing unencrypted mail always and signing encrypted mail always if possible. However, this current situation (preventing someone from sending encrypted e-mail if that person has no key or no signing key) presents hurdles. When teaching someone how to use K-9 Mail to send encrypted mail to me, having that friend practice sending encrypted mail using my encryption public keys is the first step. Use already existing material for practice and demonstrations. Helping that friend get set up with her/his own private key and explain the signing subkey are the second and third steps.

Please bear in mind that this is my suggestion/request and not a demand. I have not contributed code and I applaud and thank your success in reaching 5.200, PGP/MIME, and new UI for cryptography.

**Comment by cketti** [comment]
It's not our goal to support every use case the OpenPGP standard allows. The goal is to allow people to use email encryption without having to be an expert. That means limiting choice. (We also know there's still a lot to do to make encryption really usable for the masses).

Feel free to fork if you need a PGP expert mode.

**Comment by J-J-Chiarella** [comment]
I'm not encouraging allow users to choose various options or offering choice.

I cannot help but feel that you did not read my post fully.

I am NOT advocating presenting choice.

I am only saying that for people who do not yet have private signing keys or any keys at all, that they can at least send encrypted e-mails.

If a signing key is detected, then use it. If no signing key is detected then send the message anyway.

Nothing about what I wrote is asking for any more choices for the user. All of what I am advocating would be transparent.

**Comment by J-J-Chiarella** [comment]
I see that early days of K-9 5.200 are something of an easy-to-use beta test. As it is there was the quick 5.201 fix.

I honestly think that allowing unsigned encrypted e-mails and then enforcing signatures once the sender has her/his own private signing key is the path of least complication and least resistance.

**Comment by cketti** [comment]
That is still having options. Now it's not a setting in K-9 Mail, but the way your key is configured. Not having a signing subkey is not something we think is useful or worth supporting.

**Comment by Valodim** [comment]
In fact, it's a proper misfeature. I'll write a blog post about that some time soon.

**Comment by J-J-Chiarella** [comment]
Correct me if I'm wrong, but it seems that the team wants users to set up OpenKeychain and get their own full keyset (private cert/encrypt/sign) made and ready-to-go before learning how to send encrypted e-mails.

If so, I think this a different ordering of learning steps between myself and the team. If anything this puts signing first. The current workflow seems that you would want users to get set up with their own key and then practice signing messages to friends and maybe signing&encrypting e-mails to themselves before collecting public encryption keys.

This would probably be better since people are more familiar with cases of signing individual messages and canary warrants. Being able to sign their own messages and to check others' messages would probably be the better first step if all encrypted messages are expected to be encrypted.

**Comment by cketti** [comment]
Make sure to read Valodim's blog post: https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html

**Comment by J-J-Chiarella** [comment]
Would the rational step for anyone wanting to make public announcements or votes etc. to then be to clear-sign a text and then copy-paste that into an e-mail?

It would avoid the "I can't open the signature.asc attachment. Why?" confusion. And semi-advanced users could continue on as is.

The biggest issue for me probably is due to the fact that I learned about asymmetric encryption in PGP before learning key-exchanges (TLS) or asymmetric signatures. Even if that's how the tech evolved, it's probably better for people to learn the tech concepts in a way more familiar to human real world learning.

I can see you've all given this great thought.

**Comment by Valodim** [comment]
From experience, it's impossible to teach people who don't have a firm technical background already about asymmetric crypto. And I think we shouldn't need to. "secure messaging happens from one key to another", that's all they need to know. No picking apart what cryptographic mechanisms yield what cryptographic properties.

It's still possible to send signed-only messages, as a special mode that can be enabled in the compose dialog. But that is not exposed to the user by default.
