### ISSUE TITLE
please make a new material design UI

### ISSUE THREAD

**Issue by Immontalis** [k9mail/k-9#1927]
Can you please make a new material design UI or otherwise would you merche my design in to k9mail?

I am an android developer if you will i can help you...

**Comment by cketti** [comment]
Please do some research before opening new issues.
https://github.com/k9mail/k-9/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20material%20design

**Comment by Immontalis** [comment]
thx @cketti why you dont make a material design? Do you need help?

**Comment by philipwhiuk** [comment]
Feel free to contribute to the development of the material design base version in one of the other open issues on the subject @Immontalis
