### ISSUE TITLE
APG not being detected or used by k9mail after upgrade

### ISSUE THREAD

**Issue by PloniAlmoni** [k9mail/k-9#1929]
### Expected behavior
PGP encryption should be available

### Actual behavior
Client does not offer encryption, claims no PGP software is installed in settings. AGP is installed and configured, and was working before the k9 upgrade with k9.

### Steps to reproduce
1. create message
2. notice there's no encryption
3. look in settings and see APG is not detected

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
APG is no longer supported.

**Comment by PloniAlmoni** [comment]
Maybe give a message to the user that APG is no longer supported, rather than merely not detecting it which looks like a bug?

**Comment by philipwhiuk** [comment]
It's mentioned in the upgrade notes on launch and in the Google Play description.
