### ISSUE TITLE
Last update (12/30/16) disabled my email

### ISSUE THREAD

**Issue by DL2017** [k9mail/k-9#1933]
Hi,

For two days after the last update my email continually said it was updating the database for my account, as though it is stuck in a loop. I had lost all of my email during that time. The screen was blank except for the sentence that my database was being updated.

This morning (1/2/17) my email was suddenly back, however, no emails have been delivered since 12/31/16 at 6:00pm (EST). I've tried synching many times and the system just hangs up. I am also unable to delete the items in my Trash (leading me to believe I've lost all functionality).

In general, since Android issued their marshmallow update about 2 years ago, it has been taking 2-3 minutes to synch my mail (all other email apps take just a few seconds). I assumed it was due to memory, but I've got about 1.2 Gb free.  Would be great if you can fix both of these issues.

I'm using a Galaxy S4 handset.

 ### Actual behavior
Tell us what happens instead
It seems to just continually search (appears to run my battery down) but has received any email.  No ability to delete emails from Trash.

### Environment
K-9 Mail version:
- v5 201

Android version:
- 5.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
- POP3

**Comment by cketti** [comment]
Please record a debug log while trying to fetch messages. https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by DL2017** [comment]
Thanks, but I'm not familiar with "debug logs."  I had logged a 1 star approval rating along with an explanation in the Google Play Store, and received a reply from K9mail.  The reply gave me a link to submit the information.  I am non-technical and have no idea what you are looking for me to send.

⁣David L 

Sent from TypeApp ​


-------- Original Message --------

**Comment by cketti** [comment]
I'm afraid in that case there's not much we can do. The easiest thing is probably to start over by uninstalling the app, then reinstalling. You can export your settings as described here: https://k9mail.github.io/documentation/settings/import_export.html
