### ISSUE TITLE
Account Storage Amount Increases Even With All Messages Deleted

### ISSUE THREAD

**Issue by lynnwr** [k9mail/k-9#1935]
### Expected behavior
Size of account message data storage should decrease with deletion of messages in account folders.

### Actual behavior
Prior to recent update to v. 5.201, size of account data storage was approx. 200kb with all messages deleted. Since update, data storage amount changes only a few KB when all new messages are deleted from inbox and trash folder. Data storage amount now showing over 700kb and rising with every new incoming message that is read and deleted. Compacting the folder has no effect or only reduces amount by 20-30kb.

### Steps to reproduce
1. Account data storage amount at 272kb.
2. New 100kb (example amount) message arrives in inbox.
3. New message read, deleted from inbox, and deleted from Trash folder.
4. Account data storage amount now at 360kb (example amount).
5. Compacting folder does not reduce data storage amount. Notification message indicates amount reduced from 360kb to 360kb.

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1 running on Samsung S7

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
See #1917

**Comment by lynnwr** [comment]
Thanks for re-opening #1917.
