### ISSUE TITLE
IMAP: Add support for delimiter value NIL in LIST response

### ISSUE THREAD

**Issue by sidamos** [k9mail/k-9#1936]
### Expected behavior
K9 should list all IMAP folders. This worked OK with version 5.0, so I guess it is a regression.

### Actual behavior
K9 only lists the standard folders and then throws an exception.

### Steps to reproduce
1. IMAP server uw-imap
2. Refresh IMAP folders
3.

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

IOException: Expected 0022 (") but got 004e (N)﻿

com.fsck.k9.mail.MessagingException: Unable to get folder list.
at com.fsck.k9.mail.store.imap.ImapStore.getPersonalNamespaces(ImapStore.java:156)
at com.fsck.k9.controller.MessagingController.refreshRemoteSynchronous(MessagingController.java:430)

From the log, it seems that it does get the folders before the error and I also do not see the actual exception in the log:
```
01-03 09:16:11.352 I/k9      (8350): Running command 'doRefreshRemote', seq = 7(foregroundpriority)
01-03 09:16:11.464 D/k9      (8350): Connecting to sidamos.de as sidamos.de/84.162.7.82
01-03 09:16:11.465 I/XiaomiFirewall(3882): firewall pkgName:com.fsck.k9, result:0x0
01-03 09:16:11.749 V/k9      (8350): conn265707776<<<#null# [OK, [CAPABILITY, IMAP4REV1, I18NLEVEL=1, LITERAL+, SASL-IR, LOGIN-REFERRALS, AUTH=PLAIN, AUTH=LOGIN], Backend.fritz.box IMAP4rev1 2007f.404 at Tue, 3 Jan 2017 09:16:08 +0100 (CET)]
01-03 09:16:11.749 D/k9      (8350): Saving [AUTH=LOGIN, LOGIN-REFERRALS, SASL-IR, IMAP4REV1, LITERAL+, I18NLEVEL=1, AUTH=PLAIN] capabilities for conn265707776
01-03 09:16:11.750 V/k9      (8350): conn265707776>>> 1 AUTHENTICATE PLAIN
01-03 09:16:11.807 V/k9      (8350): conn265707776<<<#+# []
01-03 09:16:11.875 V/k9      (8350): conn265707776<<<#1# [OK, [CAPABILITY, IMAP4REV1, I18NLEVEL=1, LITERAL+, IDLE, UIDPLUS, NAMESPACE, CHILDREN, MAILBOX-REFERRALS, BINARY, UNSELECT, ESEARCH, WITHIN, SCAN, SORT, THREAD=REFERENCES, THREAD=ORDEREDSUBJECT, MULTIAPPEND], User thomas authenticated]
01-03 09:16:11.875 D/k9      (8350): Saving [NAMESPACE, SCAN, WITHIN, BINARY, IMAP4REV1, ESEARCH, LITERAL+, MULTIAPPEND, MAILBOX-REFERRALS, IDLE, THREAD=REFERENCES, I18NLEVEL=1, SORT, UNSELECT, THREAD=ORDEREDSUBJECT, UIDPLUS, CHILDREN] capabilities for conn265707776
01-03 09:16:11.876 V/k9      (8350): conn265707776>>> 2 LIST "" "*"
01-03 09:16:11.945 V/k9      (8350): conn265707776<<<#null# [LIST, [\NoInferiors, \Marked], /, mythtv-dev]
01-03 09:16:11.945 V/k9      (8350): conn265707776<<<#null# [LIST, [\NoInferiors, \UnMarked], /, Entw&APw-rfe]
01-03 09:16:11.945 V/k9      (8350): conn265707776<<<#null# [LIST, [\NoInferiors, \UnMarked], /, eBay]

[...]

01-03 09:16:11.977 V/k9      (8350): LockableDatabase: Transaction ended, took 11ms / com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1218)
01-03 09:16:11.980 I/k9      (8350):  Command 'doRefreshRemote' completed
```

**Comment by cketti** [comment]
Looks like the response parser chokes on a line of the LIST response. Can you manually issue the command (`LIST "" "*"`) and record the full response from the server?

**Comment by sidamos** [comment]
[list.txt](https://github.com/k9mail/k-9/files/682575/list.txt)

Output attached.

Is it OK that I can not see the Exception in logcat? I only see it in the "K9mail.error" folder.

**Comment by cketti** [comment]
Thanks for the output. I'm guessing we're currently not supporting `NIL` in this line:
```
* LIST (\NoInferiors) NIL INBOX
```
I'll also check why the exception doesn't show up in logcat.

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/blob/406fd6b93d8a29b3df22fad529765024e094a2e7/k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapResponseParser.java#L197 :smile:

**Comment by sidamos** [comment]
;-)

I wonder why it worked with the previous version (5.0). I guess, this is new code.

Hopefully this will be fixed soon. 

Thanks!
