### ISSUE TITLE
APG application does not seem to be detected ("no openpgp app installed" shown)

### ISSUE THREAD

**Issue by starbuck3000** [k9mail/k-9#1937]
### Expected behavior
K-9 (latest Play Store version) installed on Nexus 6P (latest OTA firmware) usually detects the presence of the app APG (latest Play Store version) under account settings -> cryptography.

### Actual behavior
Under account settings -> cryptography -> a message "No OpenPGP app installed" is shown.

### Steps to reproduce
1. install APG and import key set for account X
2. go to "account settings" under account X in K-9
3. in "cryptography" -> selector is disabled

### Environment
K-9 Mail version: 5.201

Android version: 7.1.1 (angler-03.78)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
APG is no longer maintained by it's developer and so no longer supported. OpenKeychain is both maintained and supported and contains instructions on transferring your data.

**Comment by Valodim** [comment]
We should really show a hint about this

**Comment by starbuck3000** [comment]
Thank you for the detail, it never occurred to me that APG was abandoned :/
I installed OpenKeychain, all works perfectly now, thank you (and sorry for raising the issue).

**Comment by philipwhiuk** [comment]
@Valodim - Isn't this is in the upgrade notes you get when you launch the app? I agree we could show something on the Crypto settings page too though.

**Comment by ThatGeoGuy** [comment]
Ah! Thank you for pointing me towards this. I apologize as searching for APG / OpenPGP I didn't find it in the Github search interface. I will try to upgrade to OpenKeychain ASAP. 

Cheers, and sorry for opening #1971 without finding this.

**Comment by vchrizz** [comment]
I was googling some time wondering why cryptography does not work anymore since one or two k9updates until i found this issue here...

So, yes, a little bit larger hint for such major changes should be posted public i think.

**Comment by Valodim** [comment]
This has already been done in #2047, it's just not been released yet :+1:

**Comment by vchrizz** [comment]
Great! Thanks for pointing that out. (y)

Am 3. Februar 2017 02:25:55 MEZ schrieb Vincent Breitmoser <notifications@github.com>:
>This has already been done in #2047, it's just not been released yet
>:+1:
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1937#issuecomment-277138845

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by philipwhiuk** [comment]
Description in F-Droid is now: "Can do encryption if APG and/or OpenKeychain is installed -- depending on the version." which I guess is fair given they allow you to download old versions although the ordering is none-ideal.
