### ISSUE TITLE
App no longer goes straight to Inbox from phone notification

### ISSUE THREAD

**Issue by roccol5** [k9mail/k-9#1943]
### Expected behavior
After receiving a notification from your phone that you have new mail you tap the notification and the app goes to the Inbox so you can read your new message(s).

### Actual behavior
After receiving a notification from your phone that you have new mail you tap the notification and the app goes to the folder list for your email account.  You then have to tap the Inbox to read the new messages.

### Steps to reproduce
1. Wait for a new mail notification from your phone.
2. Tap on the notification.
3. Observe that the application does not go to the Inbox.

### Environment
K-9 Mail version:
5.201
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 and IMAP

**Comment by cketti** [comment]
See #1885
