### ISSUE TITLE
No option to disable mail recipients' photo or initial

### ISSUE THREAD

**Issue by roccol5** [k9mail/k-9#1944]
### Expected behavior
When you create, forward or reply to a message the recipient's name or email address should show.  If there are more than one recipient their names or email addresses should show too, separated by commas.

### Actual behavior
When you create, forward or reply to a message the recipient's photo shows next to their name or email address.  If they do not have a picture in your contacts list or are not in your contacts list a large initial (the first initial of their email address or name) appears next to their email address or name.  This takes up a huge amount of space, especially when you have a drop down list.  There is no option in the settings to turn this behavior off and just show plain text, comma separated with no pictures/initial and no dropdown list.

### Steps to reproduce
1. Go to an email account.
2. Create a new message.
3. Start typing in a name or email address in the To: field.
4. When you are finished with that recipient you will see their picture or a giant initial.

### Environment
K-9 Mail version:
5.201
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 and IMAP

**Comment by cketti** [comment]
There are no plans to add such a setting. See also #1892.
