### ISSUE TITLE
Get rid of drop down cc: and bcc: and return to + on top

### ISSUE THREAD

**Issue by roccol5** [k9mail/k-9#1945]
### Expected behavior
Tapping head with + next to it takes care of cc: functions

### Actual behavior
cc: functions are in drop down list under to: field now.  This takes up too much space.  Also drop down list is closed by tapping on message body.  This makes absolutely no sense.  If you must insist on using a drop down list with a down arrow then put an up arrow where the down arrow is to close the list.

### Steps to reproduce
1. Create, reply to or forward a message.
2. If you want to cc: recipients you have to use the down arrow now.
3.

### Environment
K-9 Mail version:
5.201
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 and IMAP

**Comment by cketti** [comment]
The CC and BCC fields are not drop-downs otherwise they would show up on top of what was there before. They are input fields hidden by default. Clicking the message body field will hide those CC/BCC fields which are empty, not all of them. Also the whole area is scrollable, which makes the "takes up too much space" point moot.
We have no plans to change this in the immediate future.

**Comment by Valodim** [comment]
Uuh, can you back up your claim that "this makes absolutely no sense", other than "it's not what I'm used to and I don't like change"? The behavior we have right now is the same as the GMail App.

**Comment by roccol5** [comment]
I handle change well and it's not because I don't like the change (which I actually don't but that's not why it doesn't make sense).

How does it not make sense?
I'm creating a new message.  I added a recipient and now want to cc:.  I see a down arrow next to the To: field which makes me believe that I can expand this drop down so I tap it and it does.  I then enter a cc: and either change my mind, tapped the down arrow by mistake or entered a cc: and just want to collapse the drop down again.  How do I do it?  If there's a down arrow in the To: field to expand where is the up arrow now in the To: field to collapse?  There isn't one.  So I tap the To: field thinking that that will do it (since I opened the drop down that way) and it does nothing.  So then I tap the cc: that does nothing, the bcc: that does nothing, the Subject field that does nothing, then the message body that finally collapses the drop down.  The message body has nothing to do with the control of the drop down yet it controls it. It's not consistent with logical thinking.  That's like putting an on switch but not an off switch on a stove to turn on the gas then having to open the refrigerator to turn the gas off (and there's no sticker on the stove to tell you that, you just have to find it yourself).

**Comment by roccol5** [comment]
BTW I don't use Gmail.  The interface is bad.  And you shouldn't be trying to copy everyone else anyway.

**Comment by cketti** [comment]
Just don't try to micro-manage. There's no logical reason to manually hide the fields.

**Comment by roccol5** [comment]
But aren't the cc: and bcc: fields hidden by default when you create a new message?  Yes.  So you might as well show them by default.
