### ISSUE TITLE
Emails are incorrectly considered case sensitive when looking for matching keys

### ISSUE THREAD

**Issue by SecTec** [k9mail/k-9#1962]
### I did:
I send an encrypted and signer mail to myself.

### Expected behavior
Everything should be fine with the mail and the signature.

### Actual behavior
I got a red lock icon. It said: "the mail was signed with the wrong key"

### Steps to reproduce
1. create a PGP key for the mailaddress: "Test@domain.com"
2. configure the mail account in k-9 with "test@domain.com"
3. send an encrypted mail to yourself.

### Environment
K-9 Mail version: **5.201 (F-Droid)**
Android version: **4.4.4 (CyanogenMod 11)**
Account type (IMAP, POP3, WebDAV/Exchange): **IMAP**

### Suggestion:
Convert every string with mail addresses to lowercase or uppercase and than compare them.

**Comment by Valodim** [comment]
Nice catch! This will have to be fixed in openkeychain, but comparison should definitely be case insensitive there.

**Comment by SecTec** [comment]
Should I open a issue in openkeychain?

If it is an openkeychain problem, why I encountered it first after upgrade to 5.201?

The key and account are older than the 5.xxx releases.

**Comment by Valodim** [comment]
I'll fix it in OpenKeychain, no need to open an issue. Also, previous versions simply never checked user ids, that's why this error state never came up.

**Comment by Valodim** [comment]
Fixed in OpenKeychain 4.2.1, relevant commit is [here](https://github.com/open-keychain/open-keychain/commit/d389ec21e23defe130c226582f28830cd40f115e)
