### ISSUE TITLE
Give users a clearer note why the connection fails

### ISSUE THREAD

**Issue by yoshimo** [k9mail/k-9#1963]
After the update to 5.2 many people have connection problems, most likely because their mailservers
only support weak ciphers that are no longer supported.
Some others report problems with Google which can't be weak ciphers.
I would appreciate a note that states clearly why the connection fails and maybe even encourages the user  to go to the mailserver provider and fix the problem at the rooot.

**Comment by cketti** [comment]
See #1058 and #893
