### ISSUE TITLE
can't connect to exchange 2003 by imap over ssl

### ISSUE THREAD

**Issue by plepps** [k9mail/k-9#1966]
### Expected behavior
since last update I can't connect to our old Exchange 2k3 over ssl

### Actual behavior
check connection gives me error: unable to connect 

### Steps to reproduce
1. upgrade to 5.201
2.
3.

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): imap

downgrade to 5.1 solved the problem

**Comment by cketti** [comment]
K-9 Mail 5.2xx no longer supports the insecure SSLv3. Make sure the server supports TLSv1.0 or above.

**Comment by philipwhiuk** [comment]
I've added a note to this effect in the relevant sections of documentation.
