### ISSUE TITLE
K9 5.201 on FDroid does not request permission to read APG

### ISSUE THREAD

**Issue by ThatGeoGuy** [k9mail/k-9#1971]
### Expected behavior
Cryptography should be enabled on emails. The app should detect APG as the OpenPGP provider in the account settings.

### Actual behavior
I noticed after upgrading to 5.201 on FDroid that cryptography stopped working. Going into the account settings it said "No OpenPGP provider found." After uninstalling the app, and reinstalling 5.100 and 5.201 separately (from FDroid), the latter does not ask for a permission to read keys from APG, which is likely why it doesn't detect it.

### Steps to reproduce
See above.

### Environment
K-9 Mail version: 5.201 from FDroid

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, and another IMAP over Exchange account.

**Comment by cketti** [comment]
See #1937
