### ISSUE TITLE
IMAP Drafts not saving 

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#1972]
### Expected behavior
Should save to Drafts folder. 

### Actual behavior
Email is NOT saved to Drafts folder. 

### Steps to reproduce
1. Compose a mail in K9, 
2. Close without sending,
3. Check Drafts folder. 

### Environment
K-9 Mail version:
5.021

Android version: 
Android firnware 4.1.2
Kernel 3.4.0

Account type:
IMAP

**Comment by johnyradio** [comment]
May be related to

https://github.com/k9mail/k-9/issues/1838

But different. Other issue is when email address is clicked in chrome. 

THIS issue is, email started in K9.

**Comment by philipwhiuk** [comment]
It's not going to matter how the email composition was started. Closing as duplicate
