### ISSUE TITLE
some text disapeared

### ISSUE THREAD

**Issue by larrys114** [k9mail/k-9#1973]
### Expected behavior
Tell us what should happen
I should be able to read an entire message
### Actual behavior
Tell us what happens instead
about half the text did not show up. Looked at the email with another client and it was fine.
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 
newest
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by philipwhiuk** [comment]
Can you provide the full source of this email and show a screenshot of what is displayed?

**Comment by larrys114** [comment]
-- 
Sent from my Android tablet.

**Comment by cketti** [comment]
GitHub doesn't allow attaching files via email. Please use the web interface to upload files.

**Comment by larrys114** [comment]
I have s screen shot and can try to forward a copy of the email, please tell me where the link for uploads is.
Thanks

On February 5, 2017 11:45:09 PM EST, cketti <notifications@github.com> wrote:
>GitHub doesn't allow attaching files via email. Please use the web
>interface to upload files.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1973#issuecomment-277585726

-- 
Sent from my Android...
