### ISSUE TITLE
Inline PGP Signatures on Non-encrypted mail

### ISSUE THREAD

**Issue by ThatGeoGuy** [k9mail/k-9#1974]
### Expected behavior
I'd like to be able to send and receive non-encrypted emails that use inline PGP signatures. Basically, using OpenKeychain, I don't want to send an attachment called `signature.asc`, I want a message that will look like: 

```
-----BEGIN PGP SIGNATURE-----
my message

-----END PGP SIGNATURE------
<signature>
```

### Actual behavior
You cannot use inline mode with sign-only mode. Not sure why.

### Steps to reproduce
1. Compose a new email
2. Click on the hamburger menu in the top right
3. Enable PGP/INLINE mode
4. Try to enable PGP Sign Only mode as well
5. It is unsupported

### Environment
K-9 Mail version: 5.201

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): N/A

Why was the decision made to limit the way signatures are added to the message? Is this something OpenKeychain does not support? Because as far as I can tell, K9 can decode _both_ types of email, and show that the signatures are verified, but you cannot compose mail with the above settings.

**Comment by Valodim** [comment]
Actually, this is a valid issue. It's about doing pgp/inline and sign-only at once, which are both things we support and which do make sense in tandem as much as on their own.

**Comment by ThatGeoGuy** [comment]
Hey @Valodim, thanks for re-opening this. I can understand why sign-only by default isn't supported per the reasons listed in the considerations article, but inline PGP is important to me, especially if I'm doing sign only. 

Perhaps using PGP/INLINE should be an option in the account settings, so that you can encrypt or sign only without having to open the hamburger menu twice? I suspect most people who use PGP/INLINE will want to use it consistently, rather than enable it every time, but as long as sign-only is supported with inline PGP then I don't think it'll be too much of an issue.

**Comment by Valodim** [comment]
I've been considering simply doing PGP/INLINE signatures when there are no attachments in a mail by default, which would get rid of the problem altogether. However there are good arguments for both sides here: [pro inline 1](https://github.com/mailpile/Mailpile/issues/710), [pro inline 2](https://www.mailpile.is/blog/2014-11-21_To_PGP_MIME_Or_Not.html), [pro mime](https://dkg.fifthhorseman.net/notes/inline-pgp-harmful/). Or I could just allow enabling both modes at the same time. I'll have to think about this some more.

**Comment by SecTec** [comment]
+1 for enable PGP/Inline + sign only

**Comment by Valodim** [comment]
Please don't derail issues. Also, please use github reactions for "+1 for this" type posts.

**Comment by dschuermann** [comment]
I am in favor of PGP/MIME. To the existing arguments of dkg's blog post, I'd like to add future compatibility with [memory hole](http://modernpgp.org/memoryhole/corpus/#A).

**Comment by ThatGeoGuy** [comment]
@Valodim, I've read through all those articles, and I can see why some people take the pro-MIME stance. Inline is pretty close to just using PGP separate from email (e.g. just encrypting a file), whereas PGP/MIME takes advantage of the structure of an email file before it is sent. 

I can thus see that MIME is perhaps a better option as the default, and it seems that Enigmail also defaults to using PGP/MIME, so for many users coming from that it may be understandable that the defaults are consistent, even if the underlying applications have changed. However, the pro-inline crowd (myself somewhat a part of it) does have a point regarding legacy clients, and even "newer" clients like what Google was trying to do (see that first pro-inline link). I think it might be a bit weird if users start noticing that PGP/INLINE signatures are automatic when there are no attachments, but PGP/MIME when there is. I don't think the change is particularly transparent, since from the UI perspective you wouldn't see the text inserted inline (such as what Thunderbird does when it asks you to confirm if you'd send a SIGNED but not ENCRYPTED email), and thus to some users this could maybe come off as (somewhat) malicious if they didn't expect it.

I also think that most PGP users are pretty technically savvy, at least to a degree. If you're upfront about the default being MIME, then I don't see it being a huge issue, provided they are able to change it when necessary. Thanks again for considering this issue!

**Comment by Valodim** [comment]
good point! So we'll keep both, but make them compatible I guess. Might actually be worth a setting? Not sure yet, one step after another :)

**Comment by Valodim** [comment]
Felt like doing this even though it's not a priority :)

I display the sign-only icon now with a small patch icon in sign-only + inline mode. One thing I'm missing for the UI is what happens if I click that icon - does it show the inline dialog, or the sign one? I'm inclined at the moment to have it show the sign-only one, and if the user disables that also disable pgp/inline implicitly, since it's likely those two choices made by the user were connected. Thoughts?

https://github.com/k9mail/k-9/tree/readd-clearsign

**Comment by ThatGeoGuy** [comment]
Fair point on designing for the users you want, but I think there are still external barriers to getting more users using PGP, mostly due to understanding keys and how trust works.

As for what to show, perhaps it can show a combined dialog? It seems clicking on either icon gives a list of "pros" and "cons", or rather some facts about what enabling each does. Is it possible to make a new dialog that combines the messages of both, and perhaps has a `Disable both | Cancel` button at the bottom? If you want to disable just one or the other I think it would be obvious to just do that from the hamburger menu, but perhaps three buttons at the bottom is better (`Disable Inline | Disable Sign-only | Cancel`)? Here I would worry that low-resolution screens are gonna be cramped.
