### ISSUE TITLE
imap - unable to connect

### ISSUE THREAD

**Issue by iuliandurac** [k9mail/k-9#1978]
### Expected behavior
Tell us what should happen
Everything is fine in v5.010
### Actual behavior
Tell us what happens instead
In v5.201, messages dont come in inbox at all.
In Settings-Fetching-Incoming svr - "Setup could not finish, cannot connect to svr (unable to connect), Continue + Edit details". 
I have IMAP with ssl 993, normal pass.
Smtp sent okay.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.201
Android version:
4.2.2 and 5 and 6.
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP.

**Comment by yoshimo** [comment]
Which imap server are we talking about?
It might offer only weak ciphers which have been disabled in the current release.

**Comment by iuliandurac** [comment]
Thank you for your answer.
Exchange 2007.
In this case (weak ciphers), should I stick with v5.010 ? 
Is there any other way than "do not auto-update apps" in Play Store ?

Thank you.

**Comment by N-ik05** [comment]
> Is there any other way than "do not auto-update apps" in Play Store ?
Update your exchange server

**Comment by philipwhiuk** [comment]
Working as intended. Closing issue
