### ISSUE TITLE
Imap.aol.com 

### ISSUE THREAD

**Issue by DOAKLEY8** [k9mail/k-9#1990]
Since update it keeps making me edit server info. It's always been in same,  no security, port 143, password and user name correct. Or I'll put ssl and port 993 which is correct.

It warns me about 10 times..then finally settles in, but if I leave that wifi spot, get the warning notifications over and over to edit my server settings

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.202

Android version:
SG6

Account type (IMAP, POP3, WebDAV/Exchange):
Imap.aol.com

**Comment by DOAKLEY8** [comment]
Authentication fail is what it keeps saying.  Rebooted phone to check and notification pops up non stop to edit server settings

**Comment by philipwhiuk** [comment]
I was able to create an AOL account and fetch mail fine. Could it be an issue with the Wi-Fi point you are using blocking certain ports?

**Comment by DOAKLEY8** [comment]
I've tried it on 3 different wifi's. I have it on 2 different phones as well..1 with the update..1 without the update..1 without works flawless as usual. New update once I leave or join a new wifi it makes me update authentication. I'll try uninstalling and reinstalling maybe. 



-----Original Message-----

**Comment by cketti** [comment]
The old version silently ignored authentication errors. The question is why authentication sometimes fails and sometimes doesn't.

**Comment by DOAKLEY8** [comment]
yea, it's like clock work..when I leave the house and away from wifi..it pops up warnings non stop about 8 times..when I approach new wifi..the warnings start back up. they like pop up 6-8 times..I hit continute or edit..and finally after several times it sticks and stops. 


Same thing if I reboot phone..wifi or no wifi..I get the warnings. 



-----Original Message-----

**Comment by cketti** [comment]
Please try to record a debug log when that happens: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by DOAKLEY8** [comment]
not sure if i did it right but i cut phone off..and back on and it did the same errors..see attached



-----Original Message-----

**Comment by philipwhiuk** [comment]
GitHub doesn't add attachments to issue. Please add it via the website.

**Comment by DOAKLEY8** [comment]
[bugreport.zip](https://github.com/k9mail/k-9/files/690640/bugreport.zip)

**Comment by cketti** [comment]
It's not really an authentication failure. The server denies login with the message: "Too many simultaneous connections".

Try to reduce the number of folders checked via Push.

**Comment by DOAKLEY8** [comment]
ok I changed fetching mail, push folders, "only 1st class folders" rebooted twice and seemed ok..ill check when I leave work wifi and get to home wifi and see if that did the trick. 

Assuming reducing # of folders is what i did by doing that

I'll get back to you with my response

**Comment by DOAKLEY8** [comment]
Looks like that did the trick. Thanks for all your help. Appreciate it.
