### ISSUE TITLE
Can't login securely to incoming email server after recent updates

### ISSUE THREAD

**Issue by byhamp** [k9mail/k-9#1994]
Previously was able to connect to mail.talktalk.net incoming server using SSL/TLS, 993, Normal p/w (as per provider's recommended settings).  After recent K9 updates, connection to incoming server is only possible using None, 143, Encrypted p/w.  Outgoing server smtp.talktalk.net still connects fine using STARTTLS/587/signin/Normal p/w, as before.  I have asked the provider to confirm what protocols/ciphers they are supporting.

### Expected behavior
Should be able to configure incoming server settings SSL/TLS, 993, Normal p/w, verify, and then connect to retrieve emails

### Actual behavior
Verification of incoming server settings fails with all configurations except None, 143, Encrypted p/w.  Error 'SSLProtocolException: SSL h' results if verification is ignored (ie 'continue' instead of 'edit'.

### Steps to reproduce
1.  enter incoming server config
2.  set any settings (except None, 143, Encrypted p/w)
3.  save - config will fail.
4.  if continue instead; attempting to sync emails results in SSLProtocolException: SSL h

### Environment
K-9 Mail version:
5.202
Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (talktalk.net)

**Comment by philipwhiuk** [comment]
I think the full error is probably trying to tell you that the server only supports SSLv3 which is insecure and been removed from 5.200 onwards

**Comment by cketti** [comment]
No need to ask your provider. There are tools to check yourself. For your IMAP server see https://www.htbridge.com/ssl/?id=389cc9da63df8ebce8b6c9dd8673722b2ae670fb5f9a0e97305a328e78e076e1

The server supports TLSv1.0 but only ciphers we blacklisted because they are considered not secure enough. My advice is to move to an email provider who cares more about their users' security.

**Comment by ArchangeGabriel** [comment]
@cketti Just passing by, but why did you disable the 3DES ones? I suppose fear of seeing SWEET32 coming to email world? I’m trying to get a very big mail provider to add more ciphers outside of CAMELIA/SEED/3DES one (that would be AES ones…), but sofar it looks like my arguments haven’t been well received. Wasn’t able to get their reasons for not supporting any AES cipher though.

**Comment by vt0r** [comment]
@ArchangeGabriel - the ones removed in my PR were only used for SSLv3. The TLS(1.0-1.2) variants remain:

https://github.com/k9mail/k-9/pull/669/files

**Comment by philipwhiuk** [comment]
The phone is running Android 5.0 or later which disabled 3DES by default: https://developer.android.com/about/versions/android-5.0-changes.html#ssl

We don't re-enable it.

**Comment by ArchangeGabriel** [comment]
OK, thanks both of you for your answers. :) Not sure why Google decided to disable them at that time (i.e. whether they have very specific reasons or were just doing some house cleaning), but this won’t help me further. Anyway, I’ll find a way to make them support AES ciphers.
