### ISSUE TITLE
Scrolling on folder list slow and jerky

### ISSUE THREAD

**Issue by Hawk777** [k9mail/k-9#2001]
In 5.201, scrolling up and down the folder list is often slow and jerky. Scrolling up and down the message list is quite smooth, now that I disabled getting names from contacts; it’s only the folder list that’s problematic. In versions before 5.200, this only used to happen if I was downloading messages at the same time, while it was smooth if I wasn’t doing anything. In 5.201, on the same device and same server, it’s bad even if I’m not doing anything.

**Comment by PanderMusubi** [comment]
Same here on Android 6.0.1. Last updates really decreased performance. You also have slower completion of emailaddresses from contacts?

**Comment by Hawk777** [comment]
Yes, I think so; it also takes over a second from tapping the Back soft button to returning from the message list to the folder list, something which used to be significantly faster.

**Comment by PanderMusubi** [comment]
At the moment it is so slow that I just don't bother using K-9 until this is fixed (hopefully all is well soon again). Please let me know if I need to test something to help out.

**Comment by philipwhiuk** [comment]
This might be fixed by the re-addition of table indexes in #2158 

*fingers crossed*

**Comment by Hawk777** [comment]
Fixed after upgrading from 5.203 to 5.205! Also other things that were horribly slow seem to have become fast again, like polling for messages.

**Comment by PanderMusubi** [comment]
Version 5.206 on F-Droid is extremely slow again. More people observing this regression?

**Comment by Hawk777** [comment]
Scrolling the folder list on 5.206 works just fine for me.

**Comment by Hawk777** [comment]
Scrolling the message list, going Back from a message to a message list or a message list to the folder list, polling a folder, and autocompleting an address are also still fast.

**Comment by PanderMusubi** [comment]
Odd, since a few days, slow response has disappeared. 😃
