### ISSUE TITLE
No lock screen notifcation since 5.201 update

### ISSUE THREAD

**Issue by k9foo** [k9mail/k-9#2008]
### Expected behavior
A mail icon (an envelope inside of a circle) should appear on the Moto Display lock screen when new mail arrives. It has done this for the years I've been using K-9 Mail.

### Actual behavior
There is no lock screen notification since updating to K-9 Mail 5.201 and it still doesn't work in 5.202. It is now necessary to unlock the screen to see whether there is new e-mail.

The K-9 Mail lock screen notifications began to malfunction after updating to 5.201. When new mail arrived, the Moto Display lock screen would show an empty circle instead of a mail envelope inside of a circle.  I tried uninstalling/reinstalling K-9 Mail, and now there is no Moto Display notification at all when new mail arrives (the Android visual and audio notifications still work, but it is necessary to unlock the screen to see the Android notifications).

ALL other Android apps (e.g., Calender, SMS, Voice Mail, Missed Call, etc.) display their respective notification icons on the Moto Display lock screen, so this issue is definitely related to one of the last two K-9 Mail updates and not a problem with my phone.

Exact same issue on both of our Republic Wireless Moto X 1st Gen phones. Only affects K-9 Mail notifications.

### Steps to reproduce
1. Lock phone screen (with Moto Display enabled)
2. Send an e-mail message to a K-9 Mail configured account from another device
3. When the new mail arrives on the problem device, notice there is no lock screen notification icon

### Environment
K-9 Mail version:
5.202

Android version:
5.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Phone version:
Republic Wireless Moto X 1st Gen

**Comment by cketti** [comment]
See #845
