### ISSUE TITLE
Display larger preview of image attachments

### ISSUE THREAD

**Issue by Viss** [k9mail/k-9#2009]
I review a ton of security camera footage. The pics come to me by email. This is what attached images are currently displayed like in K9:
![screenshot_20170107-125805](https://cloud.githubusercontent.com/assets/1756255/21745198/8c73fd92-d4da-11e6-85fa-6f1df7218f50.png)

It would be monumentally awesome if you guys simply changed the proportions of the same data, to behave a little more like gmails does, for the sake of being able to see more of the image. This would save folks in my boat a ton of time/clicks/taps :D

![screenshot_20170107-125756](https://cloud.githubusercontent.com/assets/1756255/21745209/df0ed11c-d4da-11e6-8e00-94872798c724.png)

Hopefully this isn't a huge, massive change. And hopefully other users will agree with it! Otherwise, perhaps an option in the settings to change how inline images are displayed?

Thanks in advance!

**Comment by oliv3** [comment]
I add images in mails with
```
Content-Type: image/jpeg; name=attachment-1.jpeg
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename=attachment-1.jpeg
```
Thunderbird correctly displays the whole image but K9 doesn't (like if Content-Disposition was "attachment"). Having the same behavior would be so nice.
Thanks for this great software, keep up the good work !

**Comment by Viss** [comment]
Yup, and the new way roundcube does it is pretty rad too, makes it really easy to see "a bunch of images that are attachments". I care more about the actual image than the metadata describing the image, and right now k9 gives more real estate to the text and not the image. 

Here are two roundcube themes that do it really well just for claritys sake...

![image](https://user-images.githubusercontent.com/1756255/78458320-4afb9e80-7665-11ea-8de8-f3ec1e0c2559.png)

![image](https://user-images.githubusercontent.com/1756255/78458338-5ea70500-7665-11ea-97f8-0e0d6e7b8aaf.png)
