### ISSUE TITLE
Missing Reply/Reply all/Forward/Share menu in lastest version

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#2017]
### Expected behavior
When reading an email, it should have a menu that gives the options to  Reply/Reply all/Forward/Share.

### Actual behavior
If from an email account I have Visible message actions with Move and Copy Checked, then there is no Reply menu.  

### Steps to reproduce
1.  Within an Inbox (pick one from any, doesn't matter)   - Settings - Global Settings - Display
2.  Tap on "Visible message actions" and select Delete - Move - Copy
3.  Read any email and the Reply / Reply all, etc. menu is gone.
4.   Go back to Visible message action and UNCHECK  Move - Copy
5.   Read any email and the reply / reply all, etc. menus is back.

### Environment
K-9 Mail version:5.202

Android version:6.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment]
With Delete/Move/Copy

<img src="https://cloud.githubusercontent.com/assets/1316415/21753011/e24659ee-d5da-11e6-8a6e-1f74d7f33b9a.png" width="200">

With Delete

<img src="https://cloud.githubusercontent.com/assets/1316415/21753012/e3e9e982-d5da-11e6-8df5-b0646bd03984.png" width="200">

The Send (Reply) Menu is the two curved arrows.

If I add all of them then the Send menu moves onto the overflow (click the 3 dots).

Have you checked the 'Send...' item isn't being put on the overflow menu on your device?

**Comment by bunnybooboo** [comment]
Reproduced on a Samsung Galaxy Tab A (SM-T555) - Marshmallow 6.0.1 Steps as above. 

Individually they're all fine and the reply icon works as expected. 
A combination of TWO OR MORE of any of these global display 'visible message actions' options reproduces bug - reply icon missing. 
All other options appear to display and work as expected.

**Comment by fjenett** [comment]
On Lenovo Phab 2 Pro i have a similar problem but the lower menu (reply, etc.) never shows up even when i change the "visible message actions". K9 version is 5.206

![screenshot_20170527-211023](https://cloud.githubusercontent.com/assets/59608/26532443/4d99dad8-4401-11e7-8feb-ae1ff86b64cc.png)

**Comment by justinacolmena** [comment]
Exact same thing happened on Hundai L500U with Android 7.0. Reinstalling K-9 mail appeared to fix it. Had to do with an email that somehow got filed into my IMAP spam folder. User profile corrupted? Something not robust enough to fix it?

**Comment by cketti** [comment]
This should no longer be an issue with the design overhaul in `master`.
