### ISSUE TITLE
Bug since 5.200: horizontal scrolling in message is choppy and slow

### ISSUE THREAD

**Issue by jmlobert** [k9mail/k-9#2028]
### Expected behavior
Horizontal scrolling inside a message used to work just fine with one finger swipe across the entire message 

### Actual behavior
Since last update, horizontal scrolling takes multiple swipes and is very choppy, almost resistant to being scrolled. Very awkward and slow. 
This may be related to the next bug that no longer allows pinch-zoom

### Steps to reproduce
1. Open mail message that exceeds screen width
2. Swipe./scroll horizontally to see the right side of the message
This is consistent

### Environment
K-9 Mail version: 5.200

Android version:
6.0.1, Google Nexus 5

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by Valodim** [comment]
Same underlying issue as #2029.

**Comment by jmlobert** [comment]
This is NOT about the pinch-zoom, it is about horizontal scrolling/swiping. Moving the screen to the right, if the message is larger than the screen. It may be related, but it is not the same. Please re-open the issue unless you know for sure that it is the same underlying technical reason. Thanks  -Jurgen On January 10, 2017 at 12:11 PM Vincent Breitmoser <notifications@github.com> wrote:Closed #2028.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Valodim** [comment]
It's about ui behavior while dragging, which is directly affected by the changes in NonLockingScrollView since events are currently not correctly handed down to the displaying web view, which is necessary both for scrolling and pinch to zoom. If this is not fixed in the next bugfix release, feel free to reopen the issue.
