### ISSUE TITLE
Issue when setup IMAP mail account

### ISSUE THREAD

**Issue by xerta555** [k9mail/k-9#2032]
### Expected behavior
Good result for IMAP setup wizard

### Actual behavior
Unable to connect to server (Command: LIST (SPECIAL-USE) "" "INBOX/*";response: #5# [BAD, Missing required argument to List])

### Steps to reproduce
1.Add new email account (the "+" symbol on main interface)
2.Set my email address & password
3.Next (button), select IMAP button, settup imap settings (verified & work on PC), click on Next button and the error appear.

### Environment
K-9 Mail version: 5.202

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
I don't see anything wrong with our use of the LIST command which the server is complaining about.  We're syntactically identical to the specification in RFC 6154 - 5.2

Is this your own email server setup?

**Comment by cketti** [comment]
No additional information provided.

**Comment by LEI** [comment]
Exact same issue with `imap.orange.fr`.

K-9 Mail version: 5.206

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Should I try to enable debug logging?

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by LEI** [comment]
Manually polling actually loaded the messages and it seems to be working fine (I configured another account with POP3 and the same email just before).

[k9-log.txt](https://pastebin.com/Ps3gU238)

**Comment by cketti** [comment]
Did you manually configure an IMAP path prefix?

**Comment by LEI** [comment]
Tried to change it to random values or "INBOX", the only think I think changed is the number in `response: #5#` (saw 3, 4...).

**Comment by cketti** [comment]
Please check "Auto-detect IMAP namespace" and record another debug log.

**Comment by LEI** [comment]
Sorry, I ran the exact settings displayed in the screenshot. I tried with auto-detection the first time.

My guess is that the error is benign, I thought it was a problem because the configuration setup failed and the inbox was empty. Maybe it would have picked up the next push anyway.
