### ISSUE TITLE
Preview display is not correct

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#2038]
### Expected behavior
The preview is displayed correctly

### Actual behavior
Preview display is not correct, multiple message preview display is the same, but their message content is not the same

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:The latest version

Android version:5.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment]
You already opened this issue. Please provide a debug log and your device on #1663
