### ISSUE TITLE
PUSH on WiFi only, scheduled poll on mobile data

### ISSUE THREAD

**Issue by catfluoride** [k9mail/k-9#2041]
Hi,

unless I'm missing something in the options, is it possible to implement a switch to allow PUSH exclusively on WiFi and a scheduled poll (with an user selected interval) when on mobile data? I ask this because of the infamous "Mobile data active" bug in latest android versions...

Thanks a lot in advance and keep up the good work!

**Comment by cketti** [comment]
See #617
