### ISSUE TITLE
K9 pinch to zoom stopped working.

### ISSUE THREAD

**Issue by FlyGuyUK** [k9mail/k-9#2042]
Help help, the pinch to zoom ability when reading emails has stopped working on K9 for Android. I rely on K9 for all my email accounts and pinch to zoom is an absolutely ESSENTIAL feature. Can anyone help???

K-9 Mail version: Latest

Android version: 5

**Comment by Valodim** [comment]
This was already reported and is fixed, will be released shortly. See #1908
