### ISSUE TITLE
Look into publishing beta versions of K-9 to the F-Droid Archive

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2043]
We currently only publish beta versions to Google Play. We should look at the process for publishing beta versions to the F-Droid Archive.

**Comment by ithink314** [comment]
Some apps have beta repositories on f-droid too. Is there any movement/thoughts/decision on this?

**Comment by cketti** [comment]
K-9 Mail 5.7xx beta versions are available on F-Droid.
