### ISSUE TITLE
Attachment is missing, no delete button in notification

### ISSUE THREAD

**Issue by atvvarna** [k9mail/k-9#2046]
Hello,
On the latest version attachments is missing. I can see the clip on the message list but not in the email.
The other bug is that delete button is missing if more then one message received.

Regards,
Alex

### Environment
K-9 Mail version: 5.202

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

* Attachments can now be found at the bottom of the message text.
* The delete action is available on individual notifications. Make sure to expand the summary notification.
