### ISSUE TITLE
NullPointerException preventing all new messages being displayed

### ISSUE THREAD

**Issue by ThatLarsGuy** [k9mail/k-9#2049]
### Expected behavior
All new messages should be displayed in my inbox

### Actual behavior
A single "bad message" arrived in my inbox on my personal IMAP server (dovecot) and was not displayed by K9.  All messages recevied *after* this bad message were also not displayed.  Going into another email client and deleting the "bad message" cause all other new messages (received after the "bad message" to now be displayed correctly.

In my folder list, the string "NullPointerException: attem" is displayed in whichever folder contains this "bad message".

### Steps to reproduce
1. I have attached the "bad message" to this issue as a .eml attachment renamed to .txt.  I've had a quick look at the headers and can't see any obvious cause for a NullPointerException.  The only changes I've made is to replace my personal email address with xxxxxxxx's.
2.If you can find a way to get the attached message into a folder on your IMAP server, I expect you will see the same bug I have experienced.
!!! NOTE that this email was SPAM and I don't advise you follow the link within it !!!

### Environment
K-9 Mail version: 5.202
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
[✈ WARNING:Private Facebook Message 12.01.2017.txt](https://github.com/k9mail/k-9/files/703900/WARNING.Private.Facebook.Message.12.01.2017.txt)

**Comment by cketti** [comment]
The message contains an invalid value for `Content-Transfer-Encoding`. We're already tracking this as #2044.
