### ISSUE TITLE
Sent IMAP Not Saved

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#2050]
Click an email address in colornote. 

Compose and send from IMAP account. 

Sent mail is NOT in sent folder. 

Any chance this can be fixed?

Thx

**Comment by johnyradio** [comment]
Same device and version as "Data Loss: Compose from Other App" #1838

**Comment by philipwhiuk** [comment]
Can you provide a debug log for this?

**Comment by johnyradio** [comment]
hi, didn't see your request above. 
in any case, it seems the drafts _were_ getting saved, in the Drafts folder of a different account. 

I fixed it. i think the fix had to do with my 'default account', but i don't recall now. 

thx!
