### ISSUE TITLE
Pinch zoom not working

### ISSUE THREAD

**Issue by pyrotechac** [k9mail/k-9#2051]
### Expected behavior
Tell us what should happen

Pinch zooming isn't working. It worked fine yesterday but after upgrading to the latest release, I've lost the capability

### Actual behavior
Tell us what happens instead

Nothing

### Steps to reproduce
1. Open an email
2. Try to pinch zoom
3.

### Environment
K-9 Mail version: 5.202

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): iMap

**Comment by Valodim** [comment]
Thanks for your report! This has already been reported, and fixed in #2025. It will be in a bugfix release soon

**Comment by kripper** [comment]
See https://github.com/thundernest/k-9/issues/5789
