### ISSUE TITLE
App slowned down, attachments at the end

### ISSUE THREAD

**Issue by luckyluke885** [k9mail/k-9#2053]
After last update, app slowned down a lot. Searching and checking email takes a few seconds, before it was much quicker.

Attachments are placed always at the end of conversation. When conversation has 50 emails I have to slide down to the end to see an attachment from last received email.

I don't like new address area, CC also. When I reply to an email which has 10 contacts, it's not possible to delete single one from the middle.

### Environment
K-9 Mail version: 5.202

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
We use this issue tracker to keep track of bugs and feature requests. For support requests please use the [mailing list](http://groups.google.com/group/k-9-mail).

* Regarding slowness see #1942.
* Regarding attachments see #1895.
* To remove a recipient click the box containing the name/address, then the "X" button.
