### ISSUE TITLE
Encrypting mail to mail not in address book fails

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#2055]
**More general example below: https://github.com/k9mail/k-9/issues/2055#issuecomment-274272755**

----

### Expected behavior
Encrypt & send mail to giorgio@maone.net.

### Actual behavior
"Private key could not be found" is displayed.

### Steps to reproduce
1. Add giorgio@maone.net (`3359 0391 70A3 CD9B 25CF 5A46 231A 83AF DA9C 2434`) to OpenKeychain.
2. Create a mail.
As you can see, the "To" indicator sees the PGP key for the mail, but the encryption indicator at the top right indicates that the mail cannot be encrypted (security slider is set to "always encrypt" here):
![encryptionerror](https://cloud.githubusercontent.com/assets/11966684/21955286/6a5e3ffe-da68-11e6-9255-21efc2e417c1.png)

I suspect this is an issue with the key (as also other PGP clients failed), but depending on what this is, you might improve the UI/UX of K9 mail as the current claim (in the error message) is proven to be wrong: There is a key for this mail.

### Environment
K-9 Mail version: v5.202

Android version: CM 13/Android 6

**Comment by Valodim** [comment]
Huh, this is very surprising. I was able to reproduce, will look into it.

**Comment by rugk** [comment]
Much more strangely Giorgio Maone afterwards mailed me his full public key and after importing this one, I could encrypt the mail.

So here the original key I used:
```-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Mailvelope v1.6.0
Comment: https://www.mailvelope.com

xsBNBE1o0bwBCADE00JP4RYSLO2HfR4BLCg0ZrtDiAqgV4Ae9pJlTDE/LXTF
4SE9dIT4NsvZaZdJ07hjCv2wngj6zkiW9nRanuVQfio1EycMoBRUgDNdv/iV
8VxPw0yTUOh/GFOQQTe7WU7x8gP0rTrPPFlM/nWr2s7uFPSkGBvMagpdJkgV
8apVB8WKigrryKbbFZNlJh3UAcnphpuWhuVJu3SYzlsvUZ+oRDSMe/4+HddD
gM1SBv5j49YjC02w/7l890n58k/712lA6KMwPsGYi5Q6JAYKd/7Iy86s7mSz
h4GiLepcKhTFi0rXfv2uJWEmno1+oOI85SzKLQWFZX+IAP0PeoKm27ERABEB
AAHNIUdpb3JnaW8gTWFvbmUgPGdpb3JnaW9AbWFvbmUubmV0PsLAeQQTAQIA
IwIbIwcLCQgHAwIBBhUIAgkKCwQWAgMBAh4BAheABQJTuBVIAAoJECMag6/a
nCQ0fd0H/2ZBNzfa442CLWRPpmKMUVr+nRYWTk6z/4jmthCWxEiQDeDlqS/o
Crh1LHm5HxkEDD751tFEwL9G6mLZaaWqAzdmabAY4zCSRxIF3l1TphsULDUF
UN1qPfOhh0YlmgSDMnq3QIuANtQWPLhfY0/inEE2PmNeSEXmJlS6ui54DQKh
HGwm59MzKtij+L1bc3OyqD1eqiQPU8yBkYFQlpHLU9coIsRABGgb3Yg9o9Pb
0JrD99LIGREDAK/Kx+0A0SnWjzMMxugJW6bdNnowOwZoxdXegFWZQObKadLS
qjsPqLPHJ+/Zc87aoA0rsOiizDxh/HfAC7Ok9OiMel3jSBeH5kbCRgQQEQgA
BgUCVYW0AwAKCRC4Qgk9xnZUMOODAKDzIiXWNG2bq5VKmJiAh1EY4yijKgCg
qMYAQZgY16rTgk/wJopGm/MWiwLCwFwEEAECAAYFAlO9qgcACgkQA89KCrPH
mmPyxAf/VGLLpaGd5SzZoD1L4OdltrmxkJBVuILXAT4Rp3Xi+ZnxXG6IhEJa
qs1t8g+UQrXPH+LUzKEDRQHIfweCmfJXYe4Ae2/kpQRv/LUpCnoBdkLLqQfP
vMbrYMl4JC46VYuYZwvjSa9IhVnLf4Tixtn0BQW8NahGShY9X7y6XOdz2Lx4
FADf79rajkI5HeZUkK6ePmN+g66+6q1f/ZauVGu3Nvpi8+rGEWnCM3uyAFsn
BaZ6oputeKlEdj0/B6kOUodnnJ8ZLH2kX45mFychVjzcULThnnIc2GkhXMK9
MFx+szYfOIgJXX6q7f9ZD8DE486UV5EROnbUjopMJtIZmg+oo8LBXAQQAQoA
BgUCU7kZCwAKCRCXaP08xIgV8hp2D/0c4bPz/9xQz7X0u9pvq4Nv+WAaBmEB
//0M3WIdZoxNvlJLhOOFU6wRUyWUooY01s/wx35VXMPHIiPOzbrAP/+XPPhG
bYgPnHoVIrBqv9VTKwo89MicZjsel9nvtL7JSsIGhll8AFy1UgAUID8jAeX1
ARg4OVURD7NHJ8zUpXzWj+yTpHf8JRMfCxw129lWBLW/rbZIQFkqBToD0Jrk
GRnJLRw/Ik5p0SzpXzuK8hIrTudRyJliHB+AqILLUQlqnBukWf5vnSXSM17W
nad/Lubyt7/YFZetCYiMf60Wjace8ScQLbqHqbojNygSnlO7RLW5CadPzFFL
Fw586E1CE45d6t0EX8qhO+7tF6FFhcR+L5l9VB6eqaqaQm57ucwlJ8NaItVG
IlfcvaAXjZ679AiQ21xIHvsXGWt20ae5ulYqjWKTKohwipIDipcOB+bUdpxd
LmCTaknbot/CPA4iEcBfY9L7H7AGYVDeSPglSoX0tkg1fJjqAe93eEblS+nq
dwUQmQ3xIcqMODsaoZ9p52DfpcCIm9dWlbwSBPmg53/VVYUjhJDhS/r7iC8n
qt0w8vNe+BvqpLW5IrbVL4JaYaoCyLUbCvtsVvk8YxSGy4syN91IXtLYKhWL
4jogghQ02+VdEUdR0FUCQovpRyYgJZ7rCW10QE7H2ll4aWgPMqHpXc0oR2lv
cmdpbyBNYW9uZSA8Zy5tYW9uZUBpbmZvcm1hY3Rpb24uY29tPsLAeAQTAQIA
IgIbIwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AFAlO4FUgACgkQIxqDr9qc
JDRF5wf/Q7x1ETgNt/D6h+GRtb9bdbFgGyYIJiyRettcPslI5nyq9KAfHJj8
yTwlzd91m8F92gyrdHoTmatGfda2iGkf9fPumRNTfDGxjjaIHMzKfOVW4wLg
vE1tijYR4WtQWUHHUDVxal70cAeeh8YnuO9lrWJkjBSJi7T/wrmIPz8qZ6EG
G8eYV73OdII342cSUtTMWURjQlmVX+kTefAxb29GXxKn0IbA/bt7cpHavnWX
GKtST81SLuvfbr3k9//YAdNZVMkkgC0+WBjbTMB301RpeCSmsjHU8RyUVSLm
HVe+WcVT2iIZh5QJQiK7GyBUhbYiGwybgYjB4FJ5RjjajoGzWMLAfgQTAQIA
KAUCTWjRvAIbIwUJCWYBgAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQ
IxqDr9qcJDRsaggAj2VKvXiTmh9P8tuJsIxq2oCL0JeMg/wsJfCP4sU593At
pkCUp/ehu0I7CSp5szQ98Sg4Vmihm2iZNyfcmlIlLNC5pACQVduoMLRm4Q6n
HH9bdgsd88oudo6+LlR9draWhMxQK/v8YN3PLGHJZXK99JXSd2ZYKD9K31yi
BZf7wrv8PUQfhF54UoGJGo4CuUGEsE2BoFcZ74nO4NQxbRHHkhEd+11BpQEL
UaWMS/rtwrcWfwdMtr7ObPvJ5a04to6u95a9GU418IGW1n1PhnQymJXIH1Gz
/Q5Fq5mAwz29noLDECtY8dvm7w7WU0k36gdMUN0R2dAGdy3eN4bKDvikxcJG
BBARCAAGBQJVhbQDAAoJELhCCT3GdlQwAKQAoMrokDSACvzrhRt/dM9eO/Tg
wEkvAJ9pmcRErO9h1M226c0VZQpF2Vk41MLAXAQQAQIABgUCUS1cMwAKCRB3
FndEyejkKIApB/0c4Ng5x9NYAvvM8IBbG10rsEJ2xqMuzPiELxk/+Er7Bu9E
bXcYt+xW7MZ4vlnlfrKpo6h4jbj42C8RPm3KgGd/NuCMn+B+u6rdwR5Jl+0H
fIN+fEZK0QY/tgLxKvUxDlP4dGfNPVXpJDLoZr49YaSDPKwfN0zstRzxrmBf
PfpuC0D7olxEnYaG88/lSb9+77/Dhm0JpNd2wYKU9vTgClQU9H6cxzrlKt5P
VzAB5f1o+Gf3F4E5/BUFZ8xgMCnTYCci5xAdD28tjs2iB/F4bIdzgVVg/w51
0a+uYWydL/3QJ9bJJEZfT1TlnFx0dJFNwq7oua3B2bHyoVWEEApmUIecwsBc
BBABAgAGBQJTvaoHAAoJEAPPSgqzx5pjFTAH/jLOcMy9siVneKr77PGvcC9P
ESeHitlTS5Y3EyiQJXhEjOp9VF3ig5HB4sWxllmgQ2GJLn8JHVR6VmziqN9M
hZCJgFjbc9O0ll2Dg0m1rYEGh2pXEAmx5LCRu4UM9kswIaFpPUeZ58RMBIg1
2DksNfKLRszj91+5aBvvlT7SPjyDLiphYKR4nYJnITOOYCgBjSKmyIse+x1b
/S5g4VbFdcqMGTHLKaVyNCcr7EXnW2VgWwWbiG8nqCNPxYa0ga/9DNL3tNC0
/iNeelqSlnLhJdK8EIJ8c1GJCXRt/Uansaiv3Vu6q4e1y999usF5OiNFuD/s
yjBq8v1WdR71LVF7IRTCwVwEEAEKAAYFAlO5GQsACgkQl2j9PMSIFfLeAhAA
rmlN+pMpNFbs/vK5kL+YlhWkkmSBCSu819EAYPupTxC+sv23tbHV1qN5hTEf
IAjtsYMJZ0ihUJ7VNvBWj7r3hriNatn5zbWd37kcaJEX9O1DUagdTBWZlD4J
dFTy02HXYcjJc7yUUvwMhw97KE+WHrB5v8K9SDxLQmAJv6PHBoIvWcUNPqAE
Z+U9XGJF+dyMKGP6Z50sqERwmR87C6oGLypM+gXZdZ3OQ9Ual/WESvj61hIb
tMg8EPBoxYplfUMfsD4z3E5TmdH7wCaB1BPyGItZ+EYn51QoNd6n0PTHdJj3
TtQb+/bDuYZqDxRpZUF3QDATy/c5cVUjTje6sXAEk3OQNoZYuC4szF7Nn7qZ
ZFRiyehLLvJLuybC60s57QNwWLjjOmMKzJ0RqHZc49Yr3EdWpyrwZR80N2lO
Kltgh4GebA0Sdj/mcDXh28r3TTiSwTvM5tJXEkk+UFTYB7nB37Z9HR9dpfIQ
DMJWiriRavFIqUeZMpq8LMxMdkEZ8cNKvfZwj++30wsJAYET42UaKcPTpVpU
dSLmLtipxeHQUlyA4CPQwI0GYWwSYHVvKfgfBwNuhujfYkbugwaiudqVaarM
eDkifLugJ4FsBrY4YVqsbSjASj2MrUCYe0Bktw8GEk4VT6DvJOdzmNt6WY5+
rj5ZNxkmeI/ojjomZsExMpXOwE0ETWjRvAEIAL25YvNhhIabB904c0srmFzQ
fQvvTYPHW4/ObvpK+EV7P5LsFJUm8+xRjxYIcKQJWIL/VWEg2M8Lo+3ZYnSr
f8p9BanuLQHP0dklrd2q+eEE0jXkExasV3XD1fMEnBTtrmYkDuAf4WEeProV
esxvrdo3dKf6P7V4kTUFbfat6Jigx14reoEGEMT+RsNkrI2bJzPHjEL0w3y3
iXBt1WSYz/tb1RBw4vuNCrCC9b00XmbgsmXyH7TPkjQM8a0EPTcwQ1ces0yD
UKyWuTSoejZGdT6LsgCp6L20R3RWkE8+zInE6PrFoa+cbQeN8qQOf+QAgrY0
DQHOgFA7IZgHCRX9FCsAEQEAAcLAZQQYAQIADwUCTWjRvAIbDAUJCWYBgAAK
CRAjGoOv2pwkNAEAB/9R/uHMeY8M86S7pVMLuZLoa0vfit7nlP/23fYmRhfW
RetpGIscCSJOGu/fyEnZJRn9y5/Wz850GUGCK+O4bRXyer1xKhMhbnylRGhm
KNymTfx6utAmcoUd6cd96ZhIWqF1CE+fSF0YETHIboQwPc1T8jXeM1G7332R
AEnLIjKlbqKTRwwLLsmL57fvPN39524KegTruuw8qp2oGW2f3HEtovixkAel
QhSR9N0wxwfOEnuSW8Yrer9WhljWBGM9D8zd/z5V8xnDKnWO/sByTyRdTkP7
nsFHdJrjONuC6IzO4Ke77NBanwizffSD6kxOppdxEVX33wW8XyInGjB3QHiN

=pGfx
-----END PGP PUBLIC KEY BLOCK-----

```

here the key he mailed me:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBE1o0bwBCADE00JP4RYSLO2HfR4BLCg0ZrtDiAqgV4Ae9pJlTDE/LXTF4SE9
dIT4NsvZaZdJ07hjCv2wngj6zkiW9nRanuVQfio1EycMoBRUgDNdv/iV8VxPw0yT
UOh/GFOQQTe7WU7x8gP0rTrPPFlM/nWr2s7uFPSkGBvMagpdJkgV8apVB8WKigrr
yKbbFZNlJh3UAcnphpuWhuVJu3SYzlsvUZ+oRDSMe/4+HddDgM1SBv5j49YjC02w
/7l890n58k/712lA6KMwPsGYi5Q6JAYKd/7Iy86s7mSzh4GiLepcKhTFi0rXfv2u
JWEmno1+oOI85SzKLQWFZX+IAP0PeoKm27ERABEBAAG0IUdpb3JnaW8gTWFvbmUg
PGdpb3JnaW9AbWFvbmUubmV0PokBOQQTAQIAIwIbIwcLCQgHAwIBBhUIAgkKCwQW
AgMBAh4BAheABQJTuBVIAAoJECMag6/anCQ0fd0H/2ZBNzfa442CLWRPpmKMUVr+
nRYWTk6z/4jmthCWxEiQDeDlqS/oCrh1LHm5HxkEDD751tFEwL9G6mLZaaWqAzdm
abAY4zCSRxIF3l1TphsULDUFUN1qPfOhh0YlmgSDMnq3QIuANtQWPLhfY0/inEE2
PmNeSEXmJlS6ui54DQKhHGwm59MzKtij+L1bc3OyqD1eqiQPU8yBkYFQlpHLU9co
IsRABGgb3Yg9o9Pb0JrD99LIGREDAK/Kx+0A0SnWjzMMxugJW6bdNnowOwZoxdXe
gFWZQObKadLSqjsPqLPHJ+/Zc87aoA0rsOiizDxh/HfAC7Ok9OiMel3jSBeH5kaJ
AhwEEAEKAAYFAlO5GQsACgkQl2j9PMSIFfIadg/9HOGz8//cUM+19Lvab6uDb/lg
GgZhAf/9DN1iHWaMTb5SS4TjhVOsEVMllKKGNNbP8Md+VVzDxyIjzs26wD//lzz4
Rm2ID5x6FSKwar/VUysKPPTInGY7HpfZ77S+yUrCBoZZfABctVIAFCA/IwHl9QEY
ODlVEQ+zRyfM1KV81o/sk6R3/CUTHwscNdvZVgS1v622SEBZKgU6A9Ca5BkZyS0c
PyJOadEs6V87ivISK07nUciZYhwfgKiCy1EJapwbpFn+b50l0jNe1p2nfy7m8re/
2BWXrQmIjH+tFo2nHvEnEC26h6m6IzcoEp5Tu0S1uQmnT8xRSxcOfOhNQhOOXerd
BF/KoTvu7RehRYXEfi+ZfVQenqmqmkJue7nMJSfDWiLVRiJX3L2gF42eu/QIkNtc
SB77FxlrdtGnubpWKo1ikyqIcIqSA4qXDgfm1HacXS5gk2pJ26LfwjwOIhHAX2PS
+x+wBmFQ3kj4JUqF9LZINXyY6gHvd3hG5Uvp6ncFEJkN8SHKjDg7GqGfaedg36XA
iJvXVpW8EgT5oOd/1VWFI4SQ4Uv6+4gvJ6rdMPLzXvgb6qS1uSK21S+CWmGqAsi1
Gwr7bFb5PGMUhsuLMjfdSF7S2CoVi+I6IIIUNNvlXRFHUdBVAkKL6UcmICWe6wlt
dEBOx9pZeGloDzKh6V20KEdpb3JnaW8gTWFvbmUgPGcubWFvbmVAaW5mb3JtYWN0
aW9uLmNvbT6JATgEEwECACICGyMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheABQJT
uBVIAAoJECMag6/anCQ0RecH/0O8dRE4Dbfw+ofhkbW/W3WxYBsmCCYskXrbXD7J
SOZ8qvSgHxyY/Mk8Jc3fdZvBfdoMq3R6E5mrRn3WtohpH/Xz7pkTU3wxsY42iBzM
ynzlVuMC4LxNbYo2EeFrUFlBx1A1cWpe9HAHnofGJ7jvZa1iZIwUiYu0/8K5iD8/
KmehBhvHmFe9znSCN+NnElLUzFlEY0JZlV/pE3nwMW9vRl8Sp9CGwP27e3KR2r51
lxirUk/NUi7r32695Pf/2AHTWVTJJIAtPlgY20zAd9NUaXgkprIx1PEclFUi5h1X
vlnFU9oiGYeUCUIiuxsgVIW2IhsMm4GIweBSeUY42o6Bs1iJARwEEAECAAYFAlEt
XDMACgkQdxZ3RMno5CiAKQf9HODYOcfTWAL7zPCAWxtdK7BCdsajLsz4hC8ZP/hK
+wbvRG13GLfsVuzGeL5Z5X6yqaOoeI24+NgvET5tyoBnfzbgjJ/gfruq3cEeSZft
B3yDfnxGStEGP7YC8Sr1MQ5T+HRnzT1V6SQy6Ga+PWGkgzysHzdM7LUc8a5gXz36
bgtA+6JcRJ2GhvPP5Um/fu+/w4ZtCaTXdsGClPb04ApUFPR+nMc65SreT1cwAeX9
aPhn9xeBOfwVBWfMYDAp02AnIucQHQ9vLY7NogfxeGyHc4FVYP8OddGvrmFsnS/9
0CfWySRGX09U5ZxcdHSRTcKu6Lmtwdmx8qFVhBAKZlCHnIkBPgQTAQIAKAUCTWjR
vAIbIwUJCWYBgAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQIxqDr9qcJDRs
aggAj2VKvXiTmh9P8tuJsIxq2oCL0JeMg/wsJfCP4sU593AtpkCUp/ehu0I7CSp5
szQ98Sg4Vmihm2iZNyfcmlIlLNC5pACQVduoMLRm4Q6nHH9bdgsd88oudo6+LlR9
draWhMxQK/v8YN3PLGHJZXK99JXSd2ZYKD9K31yiBZf7wrv8PUQfhF54UoGJGo4C
uUGEsE2BoFcZ74nO4NQxbRHHkhEd+11BpQELUaWMS/rtwrcWfwdMtr7ObPvJ5a04
to6u95a9GU418IGW1n1PhnQymJXIH1Gz/Q5Fq5mAwz29noLDECtY8dvm7w7WU0k3
6gdMUN0R2dAGdy3eN4bKDvikxYkCHAQQAQoABgUCU7kZCwAKCRCXaP08xIgV8t4C
EACuaU36kyk0Vuz+8rmQv5iWFaSSZIEJK7zX0QBg+6lPEL6y/be1sdXWo3mFMR8g
CO2xgwlnSKFQntU28FaPuveGuI1q2fnNtZ3fuRxokRf07UNRqB1MFZmUPgl0VPLT
YddhyMlzvJRS/AyHD3soT5YesHm/wr1IPEtCYAm/o8cGgi9ZxQ0+oARn5T1cYkX5
3IwoY/pnnSyoRHCZHzsLqgYvKkz6Bdl1nc5D1RqX9YRK+PrWEhu0yDwQ8GjFimV9
Qx+wPjPcTlOZ0fvAJoHUE/IYi1n4RifnVCg13qfQ9Md0mPdO1Bv79sO5hmoPFGll
QXdAMBPL9zlxVSNON7qxcASTc5A2hli4LizMXs2fuplkVGLJ6Esu8ku7JsLrSznt
A3BYuOM6YwrMnRGodlzj1ivcR1anKvBlHzQ3aU4qW2CHgZ5sDRJ2P+ZwNeHbyvdN
OJLBO8zm0lcSST5QVNgHucHftn0dH12l8hAMwlaKuJFq8UipR5kymrwszEx2QRnx
w0q99nCP77fTCwkBgRPjZRopw9OlWlR1IuYu2KnF4dBSXIDgI9DAjQZhbBJgdW8p
+B8HA26G6N9iRu6DBqK52pVpqsx4OSJ8u6AngWwGtjhhWqxtKMBKPYytQJh7QGS3
DwYSThVPoO8k53OY23pZjn6uPlk3GSZ4j+iOOiZmwTEylbkBDQRNaNG8AQgAvbli
82GEhpsH3ThzSyuYXNB9C+9Ng8dbj85u+kr4RXs/kuwUlSbz7FGPFghwpAlYgv9V
YSDYzwuj7dlidKt/yn0Fqe4tAc/R2SWt3ar54QTSNeQTFqxXdcPV8wScFO2uZiQO
4B/hYR4+uhV6zG+t2jd0p/o/tXiRNQVt9q3omKDHXit6gQYQxP5Gw2SsjZsnM8eM
QvTDfLeJcG3VZJjP+1vVEHDi+40KsIL1vTReZuCyZfIftM+SNAzxrQQ9NzBDVx6z
TINQrJa5NKh6NkZ1PouyAKnovbRHdFaQTz7MicTo+sWhr5xtB43ypA5/5ACCtjQN
Ac6AUDshmAcJFf0UKwARAQABiQEfBBgBAgAJAhsMBQJTuBVIAAoJECMag6/anCQ0
9HoH+wcdcrI9WXT/pgAWS372yYSREfAaUKxSHSfZcJ8x5bFyaVUZH3B0JUVJLYXy
/szBrbmvgVI3Fq53e1Fr/HvwwJrDQAiVZVYCBJoeniD77oocNp+SvSZX5uLrXLoU
QANPP3qse2JxNq2gF6nZIcdyrhViCW5YKgUSWeqkfNCWY0NXs51Az9V7qem7aljE
LI2pFhRVeJjlOaJW0qaBfBZzxPo1SRDzy2Uw6Crt1QwU3T9taTZcbs3PjXVtxj2m
DAzMQChjiRHj0AKTWRY28OYR7rVRf4hmpHJMhNfIZq4y/XWx8hgYqtBevXnq7/WD
drkOqoyaoEmtW17t8/zRQ1V72+E=
=bmYS
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by rugk** [comment]
The fingerprint (`3359 0391 70A3 CD9B 25CF 5A46 231A 83AF DA9C 2434`) matches for both keys, so they should be the same. However they look a bit different from having a look at the whole key. 😧
But as they have line breaks at different line lengths this is difficult to compare.

**Comment by rugk** [comment]
However only having a loook at the beginning and ending characters in the full keys I can see they are different. I thought I checked that the fingerprint always matches. 😑 (to the one he lists on [his website](https://maone.net/))

**Comment by philipwhiuk** [comment]
It's (necessarily) possible (although supposed to be impractical) to match a fingerprint without matching the key - although it shouldn't be likely for them to be similar:

xsBNBE1o0bwBCADE vs mQENBE1o0bwBC

The similarity makes me thing this is a byte-order / encoding related problem.

**Comment by rugk** [comment]
As for the issue itself I could reproduce it with another contact. I think it happens when three contact you are writing to is not in your address book, but only in OpenKeyChain.

So you enter the full address and it first **does not** get marked with any lock symbol as if there would be no public key. The encryption indicator gets red.
Now you can additionally tap on the mail address and in this case you can see and select the orange lock symbol. However after selecting they upper right lock does not change.

**Comment by rugk** [comment]
Note that when I open the (unencrypted!; see other issue) draft saved for this mail it works correctly.

**Comment by ar-** [comment]
Hi. I put the two keys from above into 2 text files and ran `gpg --with-fingerprint` and `gpg --list-packets` on them. I attach the outputs of both files here.
[a_key.txt](https://github.com/k9mail/k-9/files/707462/a_key.txt)
[b_key.txt](https://github.com/k9mail/k-9/files/707461/b_key.txt)

You can view them in a diff viewer too see what is different.

As far as I see it: the first key was created on 2011-02-26 and the second one on 2014-07-05. The newer one (the one he emailed to you) removes an expiry date in one of the sub keys. In the older one the subkey expired on 2016-02-25. That might be the reason why it doesn't work anymore right now?!

On the public key server http://pgp.mit.edu/pks/lookup?op=vindex&search=0x231A83AFDA9C2434 you can also see (in the last 2 lines) the removed expiry date.

And yes, both of them show the same fingerprint, since the same private key was used to sign these subkeys.

**Comment by rugk** [comment]
@ar- Thanks for this analysis. I think the issue is that most PGP clients only show you the main expiry date (not the one of the subkeys), so in my case it is always displayed "does not expire"/"never expires".

In any case what do you think should K9 mails behaviour be with such a key? Show an error message?

**Comment by Valodim** [comment]
One of those keys indeed has an expired subkey, which quite rightly isn't used by openkeychain anymore. However, there is also a newer signature for that subkey which doesn't have an expiry date. If OpenKeychain has both those signatures, it should do the right thing and respect the newer binding cert (without expiry), so if that one is on keyservers an update to the key should work.

We should really have better problem reporting for keys that can't be used in some way for some reason.

**Comment by rugk** [comment]
>  it should do the right thing and respect the newer binding cert (without expiry),

I think it does. At least after I imported the new key manually.
(I think it overwrote the old one)

> so if that one is on keyservers an update to the key should work.

As for this key AFAIK the new one is not on any keyserver. I'll contact the owner.

> We should really have better problem reporting for keys that can't be used in some way for some reason.

👍 Good idea.

**Comment by rugk** [comment]
So please let's forget the issue with this particular mail and concentrate on the new title: `Encrypting mail to mail not in address book fails`

I can even reproduce this by writing a mail to myself (as it is not suggested in the address book for some reason):
1. Import the PGP key of a mail address into OpenKeyChain, so PGP should be possible.
2. (Make sure you do not have this mail in your address book)
3. Create a new mail and manually enter the address into the `To` line.

What happens: The lock icon is grey with one red dot at the bottom; there are no dots right of the mail address.
What should happen: Even when manually entering the address K9 mail should check whether one can sent a mail PGP-encrypted and show all design indicators for this.

4. Now tap on the mail address in the `To` line.
[You'll see a `<Unknown receiver> /n mail@example.com 🔒`, so you actually see a lock icon as itz is supposed to be.]
5. Tap on the mail address.

What happens: Now you can see the (green) dots right of the mail address; however the security indicator at the top right does not change. The mail cannot be sent PGP-encrypted.
What should happen: At least now all security indicators should be updated.

**Comment by rugk** [comment]
So I think this is the same issue as https://github.com/k9mail/k-9/issues/1655

**Comment by dschuermann** [comment]
@rugk Yup, I think you are right. This should be the same as #1655
