### ISSUE TITLE
Cant send mail - SMTP 550

### ISSUE THREAD

**Issue by beesknees333** [k9mail/k-9#2058]
### Expected behavior
mail should be sent.

### Actual behavior
Mail stays in draft folder
Error message appears: Failed to send some messages Negative SMTP reply:550 information please s..

 I've checked with server, and all settings are correct. This started late December.

### Steps to reproduce
1. write email
2.push send
3.

### Environment
K-9 Mail version: 5.202

Android version: galaxy s6,  android 6.01, Tmobile

Account type (IMAP, POP3, WebDAV/Exchange):imap

**Comment by philipwhiuk** [comment]
One of the emails in your Outbox probably has a bad address in it so won't send.

**Comment by beesknees333** [comment]
Thank you, but no, that's not it. The only emails I am currently trying to send are to an email address that is correct (checked & rechecked).

**Comment by philipwhiuk** [comment]
We probably need a debug log then. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by beesknees333** [comment]
I'm having user error and don't seem able to create one, I've not used abd before and when I enter the prompt I get "-bash: adb: command not found" & the phone doesn't seem connected. I'm using mac osx. Perhaps I'll try uninstalling and reinstalling k-9 mail.

**Comment by beesknees333** [comment]
Is this a version of the debug log? screenshots taken from the k9mail-errors folder?
![screenshot_01](https://cloud.githubusercontent.com/assets/25135941/21967843/2649fe44-db5c-11e6-9a3b-28285872a7db.jpg)

![screenshot_02](https://cloud.githubusercontent.com/assets/25135941/21967840/1ab76594-db5c-11e6-8981-8a24d687409f.jpg)

![screenshot_04](https://cloud.githubusercontent.com/assets/25135941/21967894/dd411cd6-db5c-11e6-9746-4fb6ff0dd4c9.jpg)

**Comment by philipwhiuk** [comment]
It's not the same (you could have copied the text). The errors folder only records a stack trace, not all the logging K-9 does. In the case of that particularly error all it is saying is that the attempt to connect was refused when we tried to empty the trash.

**Comment by beesknees333** [comment]
Sorry about that, I do now see an error message in the errors folder from my server, classifying the email I was trying to send as spam, so I will follow up with them. Thank you for looking into this.

**Comment by philipwhiuk** [comment]
I'm going to close this. We've got plenty of issues about improving how we show errors - e.g. #2000
