### ISSUE TITLE
Quoted text in reply not visible with dark theme

### ISSUE THREAD

**Issue by drangor** [k9mail/k-9#2065]
### Expected behavior
Using the dark theme, the text should be visible within the quoted message.

### Actual behavior
The text appears to be black, as is the background. Only links & email addresses are just about visible as they're dark blue.

### Steps to reproduce
1. Set app to use the dark theme (and ensure composer is set to app-theme) and restart it.
2. Pick a message, and hit reply.
3. Assuming the composer is including the quoted message, the text isn't visible

### Environment
K-9 Mail version: 5.202

Android version: 4.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Work around is to use the light theme, which then has black text on a light background.

**Comment by philipwhiuk** [comment]
Fixed in #2004 - not yet released.
