### ISSUE TITLE
Newly made PGP keys are expired (K-9 & Openkeychain)

### ISSUE THREAD

**Issue by Yzord** [k9mail/k-9#2066]
### Expected behaviour
It should encrypt the message before sending

### Actual behaviour
It tells me that the key is revoked or expired while checking it on the keyservers there is nothing wrong with the keys.

### Steps to reproduce
1. Configure K-9 mail
2. Create a new key for above mail with Openkeychain, upload it to the servers
3. Get on another mailclient the pubkey and send a mail to the mailaccount signed and encrypted with the pubkey
4. Mail comes into K-9 mail and is saying "This message was signed by an expired key!"
5. Replying to that mail says "Send failed: Revoked/Expired key cannot be used for sign or encryption"

### Environment
K-9 Mail version: 5.202

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Whole story:**

I have installed K-9 mail and Openkeychain to two of my Nexus devices. Both are using their own email address.

I have setup the mailaccounts on both of them and created for each of their own address a key in Openkeychain. They are all uploaded to 2 keyservers.

After that i have imported the key of the other Nexus device into the other one and vice versa. Both are confirmed.

So i setup an email op phone A and sign it with the public key of phone B. A nice green padlock appears behind my email address and the email address of phone B is green also. So i begin to type my email. When i push send i get the following error

> Send failed: Revoked/Expired key cannot be used for sign or encryption

If i send an email from the phone B with the pub key of phone A, it shows me a green padlock next to the mail address of phone B, but an orange color of the  mail address of phone A. It send the email though, but when i look on phone A it says that

> This message was signed by an expired key!

So, my guess is that phone A has a expired key or something. But it has been newly made by Openkeychain. What can i do to make it valid?

**Comment by Valodim** [comment]
Both @dschuermann and me tried to reproduce this but failed. Can you tell me the key id of one of those keys? Or, if you just generated the secret keys for testing here, send them to me? -> `look@my.amazin.horse`

**Comment by Yzord** [comment]
Both keys are on the sks keyserver

5x (at) safe-mail.eu
6p (at) safe-mail.eu

5x has multiple keys on the server, but i know for sure i have the right key ID of it
