### ISSUE TITLE
Cannot open a PDF

### ISSUE THREAD

**Issue by thany** [k9mail/k-9#2072]
### Expected behavior
An attached PDF should open in Adobe Reader of installed.

### Actual behavior
Adobe Reader is installed. When tapping "open" for a PDF attachment, the reader opens and immediately says it can't find the file. If I save the attachment first and open it them, it works fine.

### Steps to reproduce
1. Get Adobe Reader installed
2. Get an email with PDF attachment
3. Open said attachment directly by tapping "open" next to it within K9.

### Environment
K-9 Mail version: 5.202

Android version: 6.0.1 (Galaxy S7)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by GoneUp** [comment]
Can't reproduce it on my phone. Does it work with other readers?

**Comment by thany** [comment]
I don't know, perhaps someone with an alternative reader can confirm/deny this? I don't like switching around apps that open things as default, tbh. What I could do, is check if K9 puts the file-to-open in the right spot where the PDF reader is told to find it. If I knew where to look, that is.

**Comment by cketti** [comment]
Please record a debug log when trying to open a PDF attachment. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Artabanos** [comment]
I can confirm this behavior. I receive my daily newspaper in ePub format with K9 and read them with Moon Reader pro, but the same problem exists with incoming files in pdf format. When I press "Open" in K9, the reader opens the attachment as plain text file, not as a pdf or epub file.
The reason seems to be that K9 only sends a string to the reader, eg. "85f2be64452370870d2fdb408e97b87049aa68e "without suffix like pdf or epub instead of the file name.
If I press "Save" in K9, and open the file later in Moon Reader Pro, all works as expected.

**Comment by cketti** [comment]
With `content://` URIs there's not really a file name and hence no way to get a file extension which can be used to derive the content type. Our content provider does support the [`OpenableClumns`](https://developer.android.com/reference/android/provider/OpenableColumns.html) "interface" which can be used to get the file type (and a file name).
So really this is a bug in the receiving app rather than in K-9 Mail.

Opening a saved file usually involves a `file://` URI which comes with a different set of rules. For quite some time now it is no longer the recommended way of opening content because it needlessly requires the viewer app to have the storage permission. If a viewer app only supports this mechanism it should also be considered a bug.

**Comment by Valodim** [comment]
I wonder if implementations are dumb enough to extract the file extensions of content uris?

**Comment by Artabanos** [comment]
Thanks for the advice. I suppose that there was a change in December according to content URI? Until then, the combination of K9 and "moon+ reader pro" has worked flawlessly. However,  I have tested other ePub readers and most have failed as well. Finally, I found in "FBreader" an app that could deal with content URI. Not as good as "moon+ reader pro", but at least it works.

**Comment by philipwhiuk** [comment]
@Valodim, I expect they are. Might be worth trying.

**Comment by guerda** [comment]
I have a similar problem, discovered here:  https://github.com/ligi/PassAndroid/issues/121

This is what intent-intercept gives me as information about the intent if I open a PDF from a mail

intent://com.fsck.k9.tempfileprovider/temp/f59e980f347cf805fefc71ca4f8afc777e685d5c?mime_type=pdf%2Funknown#Intent;scheme=content;type=pdf/unknown;launchFlags=0x10080000;end

ACTION: android.intent.action.VIEW
DATA: content://com.fsck.k9.tempfileprovider/temp/f59e980f347cf805fefc71ca4f8afc777e685d5c?mime_type=pdf%2Funknown
MIME: pdf/unknown
URI: intent://com.fsck.k9.tempfileprovider/temp/f59e980f347cf805fefc71ca4f8afc777e685d5c?mime_type=pdf%2Funknown#Intent;scheme=content;type=pdf/unknown;launchFlags=0x10080000;end
FLAGS:
FLAG_RECEIVER_FOREGROUND
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET

AUFRUFBARE ACTIVITIES
keine

K9-mail sends the MIME type "pdf/unknown" in the intent. If I change it to "application/pdf", then intent-intercept offers me to send it to Google PDF Viewer and muPDF and others.

**Comment by wiktor-k** [comment]
Interesting case. I see [`application/pdf`](https://github.com/k9mail/k-9/blob/master/mail/common/src/main/java/com/fsck/k9/mail/internet/MimeUtility.java#L543) being returned for files with `pdf` extension.

@guerda, does the attachment have a filename in headers? I suppose it as where would the `pdf` in `pdf/unknown` be derived from if not filename (but it's better to ask).

Also, what's the K-9 version you're using? 5.600 from Play Store or something built from `master` branch?

**Comment by guerda** [comment]
@wiktor-k In the mail header, there's no filename mentioned (not sure if that's the spot where I should look). The attachment in k-9 mail is displayed with a filename (next to Open and Save buttons).
Even if I save it on the internal storage, the Andoid files app cannot open it.
The PDF opens fine in PassDroid and on my desktop pc, too.

I use the recent version from Google Play (5.600)

**Comment by wiktor-k** [comment]
Thanks for help with debugging!

I tried 5.600 and master with a PDF that has these headers:
```
Content-Type: application/pdf;
 name="test.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="test.pdf"
```

And it works fine in both cases:

![pdf](https://user-images.githubusercontent.com/1718963/49939724-e94a7a80-fedd-11e8-87f0-b7df933c3594.jpg)

Can you check your attachment headers and post them here?

**Comment by guerda** [comment]
You're welcome. Thank you for your fast responses.
I think that's where it goes wrong:

Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="B-431047.pdf"

:(

**Comment by wiktor-k** [comment]
Interesting case, I've created an e-mail with PDF with your exact headers and it still works (`mime type = application/pdf` and apps for PDFs), again with 5.600 from Play Store. Maybe you could send me an e-mail (contact info through GitHub profile) with a dummy PDF, maybe there are some additional factors I don't see here...

By the way intent-intercept is really cool :)

**Comment by AgathoN** [comment]
I got the same issue and to add to it:
K9 also breaks the attached pdf if you just forward the mail. I often forward them when I am at work to my work address and the mails then are also broken.

**Comment by AgathoN** [comment]
Forwarding a simple Mail with PDF attachment with K9 still breaks the pdf. The receiving client cant open the perfectly fine pdf anymore.

**Comment by cketti** [comment]
K-9 Mail will use the content type from the email. If the attachment has the proper type declared (`application/pdf`) things should work fine. If the sending app used another content type, e.g. `pdf/unknown`, Android will look for apps that support content of that type and most likely won't find any.

You should be able to work around this by first saving the attachment to local storage, e.g. the Downloads folder. That will discard the content type and when you try to open the file the content type is tried to be derived from the file extension.

**Comment by guerda** [comment]
Thanks. Will it then take the original file name as new file name? In this case, the file name was always random characters
