### ISSUE TITLE
Key for encryption is case sensitive

### ISSUE THREAD

**Issue by bitkleberAST** [k9mail/k-9#2073]
When I want to send an encrypted  email I have to input the recipient email address exactly the way it is written in the identity of the public key.

K9 Mail/OpenKeychain shouln't treat different casing as different keys.

Example:
Have a key in OpenKeychain with upper and lower case characters.
Input recipient in K9 Mail without upper case characters: Mail wouldn't be encrypted.
Enter recipients address exactly as it is in the identity within the public key: Email would be encrypted. 

### Environment
K-9 Mail version:  5.202
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP but probably not relevant

**Comment by philipwhiuk** [comment]
Upstream bug - https://github.com/open-keychain/open-keychain/issues/1935
