### ISSUE TITLE
HTML email bodies not always displaying correctly

### ISSUE THREAD

**Issue by jimimaseye** [k9mail/k-9#2074]
I identified a problem in that this new version is not fully accepting of 'all things HTML'.  My example is this:

### Steps to reproduce

An email body of the following body source:

```
<table border='0'> 
<tr><td><!==><!==>Hmailserver service shutdown:</td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Spamassassin service shutdown:</td><td><!==><!==>Ok</td></tr> 
<tr><td><font color="red"><b>Spam Assassin Def Update:</td><td><font color="red"><b>Failed</td></tr> 
<tr><td><!==><!==>Spam Assassin Service startup: </td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Hmailserver service startup:</td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Zip:</td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Email Cleardown Script: </td><td><!==><!==>Ok</td></tr> 
<tr><td><br></td></tr></table>See attached log file below for details. 
```

### Expected behavior

In the OLD version used to appear correctly as

> 
> Hmailserver service shutdown:	Ok
> Spamassassin service shutdown:	Ok
> **Spam Assassin Def Update:	Failed**
> Spam Assassin Service startup: 	Ok
> Hmailserver service startup:	Ok
> Zip:	Ok
> Email Cleardown Script: 	Ok
> 
> See attached log file below for details. 

(Where the bold is actually in red text)

### Actual behaviour

However, now in the new version it appeared as:

> 
> 
> **Spam Assassin Def Update:	Failed**
> 
> 
> 
> See attached log file below for details. 

Screenshot:

![screenshot_2017-01-06-21-25-55](https://cloud.githubusercontent.com/assets/15649182/22016181/31c1b40a-dc9d-11e6-9e7a-173f449ea042.png)

Note the missing lines (compared to the correct version).

I needed to change the source to replace the **<!==>** tags with  the correct REM tags

`<!--><!-->`

to make it all appear correctly.

ie,
`<tr><td>Hmailserver service shutdown:</td><td>Ok</td></tr>
.....`

Now some could argue that **<!==>** may not be official html tags and that causes the problem (which clearly they do in this new version).  My argument to this is that if they are unofficial HTML tags then they should be ignored and no attempt to interpret them should be made and therefore not alter the display in any way.....which is exactly what happened in previous version.

**So this version is not accepting of certain HTML formatting in some way - they have broken something and I suspect that it is this same change that is causing problems with HTML emails (not necessarily with them containing <!==> tags but who can know what else this version doesnt like rightly or wrongly)**

### Environment
K-9 Mail version:  v5.202

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by openbrian** [comment]
Thanks for the thorough explanation.  As a web developer I agree <!==> is junk. Maybe those emails should remain hidden.  But you're right those tags should be ignored.  I haven't looked at the code, but does a library parse the HTML?  Maybe the bug is in the library.

**Comment by jimimaseye** [comment]
I dont know myelf (I dont read code or follow the developement of this).  I only know

a,  what caused it and
b,  non-sensical tags should be ignored rather than create havoc and
c,   it didnt happen before in v5.200 (therefore its tolerance was altered in the recent updates from December)

**Comment by philipwhiuk** [comment]
They're getting removed by the HTML sanitization process that prevents script attacks and other such rubbish. I'll check we're using the latest version of HtmlCleaner and look at the config of it.

**Comment by philipwhiuk** [comment]
Upstream bug, fixed in 2.17. I'll include the code sample as a test and update the dependency.

Thanks!

**Comment by philipwhiuk** [comment]
Filed an upstream bug against HtmlCleaner: https://sourceforge.net/p/htmlcleaner/bugs/182/

**Comment by jimimaseye** [comment]
Phil you have logged it against version 2.7.  There latest version is 2.18 (Im concerned your 'issue' will not be seen as is all others on there being back in 2015).  Shouldnt it be again the latest?

(I'll leave it with you.)

**Comment by philipwhiuk** [comment]
Eh anyway it was seen by the project author. The debate now really is to whether it's acceptable that it's rendered as decoded bad tags or stripped. 

If you set a flag on HtmlCleaner you can get it so the <!==>'s become visible and the text is shown properly. Which will look ugly, but the text is shown.

If you don't set the flag, right now it strips not only the bad tags but also the text (current K-9 stable).

Personally, I think we should probably add the flag. Frankly whatever piece of software is producing `<!==><!==>` as a spacer is doing it all wrong.

I'll submit a PR for that but keep watching the upstream issue anyway.

**Comment by jimimaseye** [comment]
Indeed.

Any idea from their changelog where the change is that occurred that meant the previous version (which simply ignored them - ie, didnt make them visible - whist continuing to show the rest of the line instead of it completely wiping out all things on the line) actually got removed?  Neither of the situations above (make visible or strip the text as well) match this scenario.
