### ISSUE TITLE
Synchronisation? is very slow

### ISSUE THREAD

**Issue by ArchangeGabriel** [k9mail/k-9#2075]
### Expected behaviour
Synchronisation should work flawlessly.

### Actual behaviour
K-9 seems to process every email in my INBOX from time to time (maybe when the IMAP IDLE connection was lost? At least it does when going out of airplane mode in the morning, or after killing the app), and is rather slow at it. I would say around 15 emails processed per second. And I have thousands of them in my INBOX (I know, that’s bad), which results in several minutes for the whole things. Also, this is blocking email retrieval for all accounts while doing this scan.

Sorry if duplicate issue, didn’t found one with this. Could be related to #2061/#2069 though.

### Steps to reproduce
1. Have a very large INBOX.
2. Reboot, kill K-9 mail, whatever makes its connection lost.
3. See K-9 starting to spin, and after sometime starting to slowly increase `yyy` in “Récup. <accountname>:Inbox yyy/xxxx” where `yyy` is the number of already processed messages and `xxxx` the number of total messages.

### Environment
K-9 Mail version: 5.201 (I think it started with 5.200)

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by jmccabe** [comment]
I'm seeing something similar. I installed K9 recently on my tablet as part of a planned move away from what is now a Mobisystems product, but syncing does take a long, long time compared to the other product, and seems to be adding significant drain on my battery. I'm not using IMAP push though, just periodic fetching. My Inbox has around 2800 messages in it at the moment.

**Comment by cketti** [comment]
Should be fixed by #2069. The fix will be included in 5.204.

**Comment by ArchangeGabriel** [comment]
@cketti As a matter of fact, I determined last night they were two issues at play:

– a first phase with K-9 starting to spin, which takes a bit of time during which memory consumption greatly increases. This is probably going to be fixed by #2069 indeed.

– a second phase where K-9 slowly increase the yyy counter of parsed? emails in the INBOX. I’ve been able to make it goes from the above stated speed of 15 parsed? emails per second to several hundreds (thus considering this part fixed) after trying the suggestion of this comment https://github.com/k9mail/k-9/issues/1942#issuecomment-277521370. So here too it seems that something went wrong in the database upgrade process.

I should have added in my opening post that K-9 was killing my battery because of this (I mean, it drained more than Pokémon GO constantly on…), and that solving the second part of the issue fixed that too. ;)

**Comment by philipwhiuk** [comment]
#2158 I expect, although without actual performance metrics it's hard to know really.
