### ISSUE TITLE
Unable to sync folder list

### ISSUE THREAD

**Issue by cadauto** [k9mail/k-9#2077]
### Expected behavior
Folder sync with server should duplicate/sync all of the folders, as specified in app. I currently have all folders set to sync, instead of specific class folders.

### Actual behavior
The only ones sync'ing are the default; inbox, outbox, sent, spam, and trash. The server has various folders which are not duplicated/sync'd on the phone.

### Steps to reproduce
1. Sync folders between phone and server
2.
3.

### Environment
K-9 mail v. 5.202
Motorola Android 6.0.1 Security Patch 9/1/16

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Most probably you are hitting server limits on how many folders can be synced with push simultaneously.  Each folder requires 1 push connection and most servers have fairly strict limits per user.

If you think this is not the case please provide a debug log.

**Comment by cadauto** [comment]
Thank you for the response. In rereading my message I don't think I explained what I wanted to say properly. I'm not even able to get a folder list from the server. Those few folders listed above are still the only ones there. It is my server at home, so I know IMAP settings have not changed. I'm able to get all of the folders using an IMAP program on a PC. This is a recent issue. I don't know if it was a k9 update or OS update that caused the problem. I was hoping someone else had the same situation occur and was able to resolve it. I will get the log file as soon as I'm able and will upload if it shows anything I can't resolve.

**Comment by cketti** [comment]
No additional information provided.
