### ISSUE TITLE
5.201: Can't resize email body anymore

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#2078]
### Expected behavior
Before 5.201, i was able to resize the email body for better readability, with the usual two finger gesture.

### Actual behavior
Since 5.201, Double tap (still) resizes email body, to a "fit in display" level, leading to unreadable small font size. No chance to resize, gesture ignored. 

Some sort of workaround is to go back to folder level an reopen email. But even then very often font size is too small.

### Steps to reproduce
1. Open Email
2. Try to resize email body with two finger gesture (because of my english I don't know if there's a more specific name for this gesture)

### Environment
K-9 Mail version: 5.201

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): doesn't matter here

**Comment by philipwhiuk** [comment]
#1886
