### ISSUE TITLE
HTML links are not detected 

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#2079]
### Expected behavior
Received emails with "reset you password" links. Concrete example for TYPO3, but had the same issue a while ago with a wordpress email. http(s) link in email body is not detected as link.

### Actual behavior
http(s) links are shown as normal text, not as link.

### Steps to reproduce
1. copy the following example text in an empty email, send, receive and open with K9

(start of email body)

Dear <user_name>,

This email was sent in response to your request to reset your password. Please click on the link below.
http://localhost:10080/typo3root/index.php?id=8&L=1&tx_felogin_pi1%5Buser%5D=1&tx_felogin_pi1%5Bforgothash%5D=1484664208%7C6c04ff23fced74b37d9ca4c737ec6a3f

For security reasons, this link is only active until 2017-01-17 14:43. If you do not visit the link before then, you will need to repeat the password reset steps.

(end of email body)

### Environment
K-9 Mail version: 5.201

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): doesn't matter here

**Comment by philipwhiuk** [comment]
Was it a HTML email or a plain-text email. We only do auto-detection on plain-text emails I think. Your issue title suggests this was a HTML email.

In any case we probably don't detect localhost - the link wouldn't work anyway unless you're running the server on your phone!

**Comment by michaelof** [comment]
Sorry, my mistake: Issue title should be "HTTP(S) links are not detected" instead of "HTML links are not detected".

Emails are pure TEXT, not HMTL.

And yes, it's because of "localhost". Tested with "example.com", works.

But FYI the "localhost" link would perfectly work WITHOUT a local server on the android device: I'm testing/debugging with a TYPO3 site and the server / the site is (currently of course) only serving on localhost. And localhost's ports are forwarded to wherever I want via a SSH port forwarding, works fine :-)

So no idea why K9 has a "logic" to filter localhost: As you see in this issue confusing at least for me, and imho unnecessary functionality. Maybe worth dropping?

**Comment by philipwhiuk** [comment]
Okay. Well we have an existing issue for better link detection. I actually mentioned localhost in the issue now I come to check:

Closing as duplicate of #1223

**Comment by Valodim** [comment]
I wonder if allowing links to localhost can be a potential security issue? Is this useful for url forging in some way? I'm not sure
