### ISSUE TITLE
Can't delete 1 email in To: after doing Reply All to an email

### ISSUE THREAD

**Issue by mordakk** [k9mail/k-9#2081]
### Expected behavior
Should be able to edit To: field and delete an email in Reply All

### Actual behavior
Can only delete an email from Reply All if it's the last email listed

### Steps to reproduce
1. Open email with multiple recipients
2. Click reply all
3. Try to delete any email besides the last one listed, you can't

### Environment
K-9 Mail version: 5.202

Android version: Marshmallow 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Click the box of the recipient you want to delete. In the popup that appears press the "X" button.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by mordakk** [comment]
With the dark theme, the X is invisible

**Comment by cketti** [comment]
Thanks for the information. I've created a new issue for this: #2083

**Comment by xaverm** [comment]
I'm sorry, but #2081 seems neither related to #2128 nor does it provide a solution to the problem:

#2128 does not report on not being able to delete a recipient.

It does report on:
i) **not being able to edit** any of the recipients within any of the TO, CC, or BCC entry field. By "editing" I mean to change eg. a letter within an email address
ii) **not being able to copy/cut/paste** recipients between the TO, CC, and BCC entry field. Actually, Android's copy/cut/paste buttons still show up, but the copy action will only produce a lower quote character

I don't understand why #2081 has anything to do with that and why in turn #2128 has been closed?
