### ISSUE TITLE
Apparent Incompatibility with Mailvelope

### ISSUE THREAD

**Issue by jtsmith0101** [k9mail/k-9#2085]
### Expected behavior
PGP messages from Mailvelope-enabled gmail addresses should decrypt after authentication.  Mailvelope to Mailvelope works just fine.  

### Actual behavior
After successful authentication challenge, I only see the encrypted PGP block.... no decrypted message

### Steps to reproduce
1.  Encrypt message using Mailvelope extension on Chrome
2.  Email to K9 client email
3.  Authenticate 

### Environment
K-9 Mail version: 5.202

Android version:  6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by philipwhiuk** [comment]
This might be because it's an odd form of PGP/INLINE. The result of doing it in the browser means there's a text/plain and text/html copy of the PGP/INLINE section. The text/html version is surrounded by `<pre>` tags, contains links and so on.

Here's a sample signed email.

[mailvelopeTest.txt](https://github.com/k9mail/k-9/files/713559/mailvelopeTest.txt)

I doubt we've ever supported this format so I consider an enhancement to do so.

**Comment by jtsmith0101** [comment]
Thanks for getting back to me Philip.

This has always worked in the past (decrypt/encrypt).  Although signed
messages were problematic.

A change has happened.  I just don't know if it is with you, them or both.

Best,

James

---Sent from my mobile device---

On Jan 18, 2017 9:07 PM, "Philip" <notifications@github.com> wrote:

This might be because it's an odd form of PGP/INLINE. The result of doing
it in the browser means there's a text/plain and text/html copy of the
PGP/INLINE section. The text/html version is surrounded by <pre> tags,
contains links and so on.

Here's a sample signed email.

mailvelopeTest.txt
<https://github.com/k9mail/k-9/files/713559/mailvelopeTest.txt>

I doubt we've ever supported this format so I consider an enhancement to do
so.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/k9mail/k-9/issues/2085#issuecomment-273434966>, or mute
the thread

**Comment by Valodim** [comment]
this should be fixed in #2036, will be out in the next release
