### ISSUE TITLE
Editing receivers is hard with PGP support

### ISSUE THREAD

**Issue by sedrubal** [k9mail/k-9#2086]
### Actual behavior
It's hard to delete and add email addresses from/into the "To", "CC" and "BCC" field when PGP support ist active (OpenPGP installed), because the keyboard hides when moving the curser by hand, arrow keys don't work for navigating to another address, there is not text but "cards" for addresses and you can't delete single characters. 

### Expected behavior
I think it would be better to convert the cards into plaintext addresses when tabbing on them.  

### Steps to reproduce
1. "Reply all" to a email so that there are multiple addresses in the to field of the new message
2. Try to remove the first recepient

### Environment
K-9 Mail version: `5.002`
Android version: `7.0.1`
Account type (IMAP, POP3, WebDAV/Exchange): `IMAP`

**Comment by Valodim** [comment]
Probably caused by #2083 and fixed by #2084

**Comment by sedrubal** [comment]
Oooh there is an <kbd>x</kbd>? Thanks :smile:
