### ISSUE TITLE
Mail encoding broken when using PGP

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#2091]
### Expected behavior
The mail text send using PGP should contain special (non-ascii)  characters like Ä ü ß

### Actual behavior
Special char are removed or broken - payload (the conent of the mail) get corrupted

### Steps to reproduce
1. receive a PGP - encoded mail 
2. answer and have non-ASCII chars inside

### Environment
K-9 Mail version:
5.202
Android version:
6.01
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
Is this for signed, or encrypted mails?

**Comment by coogor** [comment]
Encrypted mails

**Comment by Valodim** [comment]
Just tested, works for me. Was it sent from K-9, or a different client? I'm grateful that you take the time to report an issue, but please try to be more detailed in your report. Playing twenty-one questions is really not a good use of my time when I could be fixing bugs instead.

**Comment by coogor** [comment]
![screenshot_20170119-085914](https://cloud.githubusercontent.com/assets/5717703/22098300/de98efe8-de25-11e6-8a73-bebdfd42ff50.png)
Of course it was sent from K9 and not from any other client. See attached Screenshot where the recipient confirms that my mails come broken. Feel free to send me a PM to exchange keys and test

**Comment by Valodim** [comment]
Sure, we can do that -> `look@my.amazin.horse`

**Comment by coogor** [comment]
Thanks for testing this. As it works with K9 and KMail, it finally looks like an issue in the other mail client. Therefore closing.
