### ISSUE TITLE
"always show CC/BCC" doesn't

### ISSUE THREAD

**Issue by deviantollam** [k9mail/k-9#2095]
### Expected behavior
there is a setting under "sending mail" for each account's configuration called "Always show CC/BCC"

this checkbox setting can be toggled on or off

marking this box as checked would give the impression -- quite unambiguously, one would think -- that the CC and BCC fields are always to be shown beneath the TO field when composing a new message.

### Actual behavior
when composing a new message, if the checkbox is marked in the settings, the CC and BCC fields do indeed appear /at first/ beneath the TO field of the new message, however the moment someone begins trying to type in the Subject or Body of the message, these fields collapse away if they are not populated with any data or entries.

"always show" should mean what it says... ALWAYS show.

### Steps to reproduce
1. under Account Settings, go to Sending Mail settings
2. mark the checkbox for "Always show CC/BCC"
3. compose a new mail message
4. the TO, CC, and BCC fields will all be present
5. tap anywhere in the subject or body area of the new message that you are composing
6. CC and BCC fields collapse away, in direct defiance of what you wanted
7. tap small down arrow, to cause the CC and BCC fields to appear again
8. tap anywhere else
9. pull your hair out as the CC and BCC fields AGAIN disappear with seemingly no way to make them permanently remain visible.

### Environment
K-9 Mail version: 5.2x

Android version: all versions

Account type (IMAP, POP3, WebDAV/Exchange): any type

**Comment by Valodim** [comment]
This is indeed a bug, the fields should stay visible. Seems like a simple fix, want volunteers?

**Comment by cketti** [comment]
See #1965
