### ISSUE TITLE
5.203 on F-Droid signed with wrong key, forces uninstall

### ISSUE THREAD

**Issue by openbrian** [k9mail/k-9#2099]
### Expected behavior
Upgrade should happen without forcing an uninstall.

### Actual behavior
F-Droid prompts user to uninstall K-9 before installing 5.203.

### Steps to reproduce
1. Assuming you have a version before 5.293
2. Open F-Droid and upgrade K-9.
3.

### Environment
K-9 Mail version: from 5.202 to 5.203

Android version: 6, CM 13

Account type (IMAP, POP3, WebDAV/Exchange): n/a

**Comment by philipwhiuk** [comment]
I believe this is a problem with F-Droid not K-9 as they sign the builds.

**Comment by cketti** [comment]
Make sure you get the update from the same source you got the initial version from. Updates will work fine then.

**Comment by openbrian** [comment]
Thanks for explaining the signing.  I prefer F-Droid over Google Play.  Any chance Google Play detected the package and auto updated it.  F-Droid does say "Installed (from Google Play Store)".  Interesting how GP doesn't complain about a different signing key and didn't force an uninstall.

My question is, did you just start to upload K-9 to GP?
