### ISSUE TITLE
New emails not being downloaded

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#2100]
### Expected behavior
When configured to work with a particular email account, the app downloads all emails from supported POP3 services to view in the normal manner.

### Actual behavior
Results vary by email provider.
Some email providers have no problems while other major ones such as Google worked initially and some mail but then subsequently stopped receiving new messages and have not downloaded anything since even though new messages have been sent to effected accounts.  Sending mail has continued to work in all cases.

### Steps to reproduce
Original trigger of the issue unknown...
1. Set up an account in K-9
2. Download new mail
3. Depending on email provider it will either work or only download emails initially.  Sending works fine on all services regardless.

### Environment
K-9 Mail version: 5.203

Android version: 4.4.4

Account type:
Accounts are POP3 mail accounts.

**Comment by philipwhiuk** [comment]
What errors are shown? What providers work? Do you have a log of any of this.

Playing 20 questions to figure out what is going on is not very helpful. It's worth pointing out Google barely supports POP3 themselves these days.

**Comment by cketti** [comment]
No additional information provided.
