### ISSUE TITLE
Sending email to self sends emails to wrong account or nowhere

### ISSUE THREAD

**Issue by tboicey** [k9mail/k-9#2101]
Running K9 5.203 from Google Play. Google Pixel with Android 7.1.1.

I Have three accounts on K9, all are accounts on gmail but with non @gmail.com domains.

Call them:

trevor@a.com (personal, gmail with custom domain)
trevor@b.com (corporate with google apps)
trevor@c.com (another business, not used in this example)

Bug #1:

Open trevor@a.com on K9. Send email to self (trevor@a.com). Email never appears as "new" mail in either K9 or gmail web UI. Appears in "sent mail" only. This used to work on versions of K9 up until recently, suspect broken around 5.2?

Bug #2:

Open trevor@a.com on K9. Send email to self but different account (trevor@b.com). This email appears as "new" mail **IN BOTH ACCOUNTS**. It shows as Sent Mail in trevor@a.com but new mail in Inbox of both trevor@a.com and trevor@b.com.

**Comment by cketti** [comment]
That's more likely an issue with Gmail (IMAP) than with K-9 Mail.

**Comment by tboicey** [comment]
I'll leave it closed if you suggest, but this is new behaviour in recent K9.

I've used K9 forever, and I've sent myself email forever.
