### ISSUE TITLE
Opening a new mail from the notification goes to "Folders" of the account

### ISSUE THREAD

**Issue by captainepoch** [k9mail/k-9#2102]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When you receive a new email and the phone is blocked, opening the email from the notification should go to the email.

### Actual behavior
When you receive a new email and the phone is blocked, opening the email from the notification goes to the "Folders" list of the correspondant account.

### Steps to reproduce
1. Block the phone.
2. Send an email to one of the accounts you have set up.
3. Open double-touching the email.

### Environment
K-9 Mail version: 5.200, 5.202, 5.203

Android version: LG Nexus 4 7.1.1 (NitrogenOS, but it happens with official Lollipop too).

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
You didn't search.
