### ISSUE TITLE
Text in quotation when replying too small

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#2106]
After https://github.com/k9mail/k-9/issues/1930 was fixed, one issue remains: The text is white now, but way too small.
As you can see, all there other text (mail subject, content, signature) has the correct size.

Here a reply to a BugZilla mail:
![textquotationsmall](https://cloud.githubusercontent.com/assets/11966684/22175934/c3824390-dfff-11e6-9ea9-15a5dee7aa34.jpg)

**Comment by philipwhiuk** [comment]
Does zooming in not work - it does for me (and I've yet to see email which display quite that absurd difference)?

The default size is based I think on fitting the email to the window rather than any minimum font-size. That's probably not an optimal default having said that but it's rather difficult to please everyone.

**Comment by rugk** [comment]
> That's probably not an optimal default having said that but it's rather difficult to please everyone.

Yeah, not optimal. I think it does not help anyone if the mail cannot be read. 😆 

> Does zooming in not work

No. Pinch to zoom does nothing. In no part of the compose screen.

> I've yet to see email which display quite that absurd difference

Actually this absurd difference in font size (of the part of the reply with my own text and the quoted mail I am replying to) is the issue I am talking about here.

**Comment by philipwhiuk** [comment]
> Pinch to zoom does nothing. In no part of the compose screen.

In 5.203 and later the quoted section is zoom-able.

> Actually this absurd difference in font size (of the part of the reply with my own text and the quoted mail I am replying to) is the issue I am talking about here.

Yes I realise this. My point is that this exact situation is rare, setting an appropriate zoom level that will please everyone is impossible. If zoom worked for you this wouldn't be an issue I trust.

Given that despite the fact that you have raised many bugs I must continue by playing 20 questions and ask you to tell me the stuff the template originally asks for. What version of K-9 are you running.

**Comment by cketti** [comment]
If this is still a problem with a recent version of the app, please open a new issue and attach the source of an email that we can use to reproduce this bug.
