### ISSUE TITLE
Support unsigned encrypted emails

### ISSUE THREAD

**Issue by shtrom** [k9mail/k-9#2112]
> Please search to check for an existing issue.

I have, and found #1999 and #1743, but neither seem to exactly address what I want, I'm not sure whether #2087 addresses this particular issue, but it doesn't seem to be the case.

### Expected behavior
I want the ability to separately sign and encrypt emails. I like being able to encrypt by default (kuddos you guys for finally supporting opportunistic encryption with OpenKeyChain and PGP/MIME!), but I would like to disable signing by default, even if encrypted.

Being able to encrypt without signing supports confidentiality with plausible deniability, which I think is an important mode of communication.

### Actual behavior
At the moment, it seems that one can
1. Send unencrypted and unsigned emails
2. Send unencrypted and signed emails
3. Send encrypted and signed emails

The option to send encrypted but unsigned emails is missing.

### Steps to reproduce
1. Enable auto encryptions for known keys
2. Send an email for a known key
3. No option to not sign the message (except by disabling crypto entirely)
4. Any encrypted message is sent with a signature.

### Environment
K-9 Mail version: 5.203

Android version: not relevant

Account type (IMAP, POP3, WebDAV/Exchange): not relevant

**Comment by cketti** [comment]
See #1961
