### ISSUE TITLE
K-9 translations not updated

### ISSUE THREAD

**Issue by urmatej** [k9mail/k-9#2113]
Hello,

It seems that translations from transifex do not get updated. Is transifex still a valid option tu push translations?

### Environment
K-9 Mail version: all from 5.20

**Comment by urmatej** [comment]
Is there another way to send the translations?
Transifex obviouslly isn't it.

Thanks,
Matej

**Comment by cketti** [comment]
Updating translations with every minor release is not one of our priorities. It'll happen eventually.

**Comment by urmatej** [comment]
Hello cketti, no worries,
yes I do understand and accept this priority, I am just surprised this is not automatic. Some other projects I work on are. No problem.

BTW, Is there a way to test a new translation locally? Which file and where I need to replace, if it is possible.

Thanks,
Matej

**Comment by philipwhiuk** [comment]
If you are happy building the app from source, the translations are found in k9mail/values-XX/strings.xml where XX is the two-letter country code (e.g. es for Spain).

**Comment by urmatej** [comment]
Thanks,
I will try to figure out compiling, otherwise i will check the next release.
Best

Matej

Dne 08. februar 2017 00:58:35 CET, Philip <notifications@github.com> je napisal/-a:
