### ISSUE TITLE
Unread messages count on app dock icon

### ISSUE THREAD

**Issue by CreeperLava** [k9mail/k-9#2114]
I would love to be able to see the unread messages count, not only on the home screen widget already provided, but more importantly on the K9 dock icon. Like the default android app, basically.

**Comment by philipwhiuk** [comment]
This doesn't happen on stock android. Only on modified Android versions with custom launchers.

**Comment by CreeperLava** [comment]
I see, thank you for the answer. My phone is a Huawei Honor 5C, I believe the UI is called EMUI.

**Comment by jerryn70** [comment]
It  shows only the unread count of the default account. Means if I have 2 mail accounts in k9 it shows the unread count of the default account and don't shows the count of other account. Will be geart if it shows total count (unread count of account 1 + count of account 2).

And sometimes the unread count shows wrong count . At first it's shows correct count on the app icon after sometime it changes to wrong count

**Comment by jerryn70** [comment]
It shows wrong count on the app icon.  I have total 4 unread mail but the count on the app icon shows only 1

**Comment by cketti** [comment]
Some (non-stock) Android versions use the "number" from the app's notifications and display them on top of the app icon. It's not surprising this doesn't work well. Usually the number we set is the number of "new" messages, not the number of unread messages.

For me confusing numbers on the app icon on modified Android versions is not a reason to change anything in our code.
