### ISSUE TITLE
K9 crashes when opening some messages, others open ok

### ISSUE THREAD

**Issue by Tib56** [k9mail/k-9#2116]
### Expected behavior
All messages should open without causing app to crash

### Actual behavior
Opening some emails causes the app to crash.  Others open fine. No rhyme or reason to it. Size, date, sender or receiver, HTML or text format, or whether or not it contains an attachment, makes no difference.  No common connection seen between messages that would indicate a possible cause.  Refreshing folders doesn't fix it. Error message "unfortunately k9 has stopped" is displayed. Restarting app does not fix. Issue tested on different tablets and phones, and still occurs.

This makes the app untrustworthy and almost useless.

### Steps to reproduce
1. Never know which message the app is going to crash on
2.
3.

### Environment
K-9 Mail version: all recent versions

Android version: all recent versions

Account type (IMAP, POP3, WebDAV/Exchange): pop3

**Comment by philipwhiuk** [comment]
> Android version: all recent versions

You've personally tested it on all recent versions?

> K-9 Mail version: all recent versions

What are you currently running. 

We don't ask these questions for fun.

Can you provide a debug log?

**Comment by Tib56** [comment]
My Android version is 4.4.2 but it was doing it on earlier versions, too.

K9 version is 5.203. older versions were much more stable

Can't provide a debugging log. Installed ADB but can't get my PC to
communicate with the device, a Lenovo A-3500F tablet.  Installed USB
drivers but still won't communicate. Sorry

**Comment by Tib56** [comment]
K9 says it's reporting the crashes when they happen, too.

**Comment by philipwhiuk** [comment]
@cketti Have we resolved all the outstanding Google Play reported issues now?

**Comment by cketti** [comment]
@philipwhiuk: Not even close. But most are obscure crashes that are in total only reported 1-3 times.

Based on the device name it's probably issue #1899.
