### ISSUE TITLE
Cancelling Compose window not always requesting 'Save As Draft' option

### ISSUE THREAD

**Issue by jimimaseye** [k9mail/k-9#2120]
"Save As Draft" offering is inconsistent.

### Expected behavior
When browsing, for example the GALLERY on the device, and choosing a picture to 'share' through K9, a new email is generated with the photo attachment.  If the 'return'/back out button is pressed on the device, K9 prompts "Save as Draft or Discard" (allowing saving as draft).

### Actual behavior
If a fresh email is composed **from WITHIN** K9, and the  'return'/back out button is pressed, the email is unceremoniously discarded and no option to Save As Draft is offered.

### Steps to reproduce
As above

### Environment
K-9 Mail version: 5.203

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
The dialog should be displayed once you've actually entered some information. There's no point in saving an empty draft. If that doesn't work it's a bug. Then please list the exact steps to reproduce the issue.

**Comment by philipwhiuk** [comment]
Currently we aren't updating 'draftNeedsSaving' if you just add an attachment. Do you think we should @cketti ?

**Comment by cketti** [comment]
Probably. Someone could have spent a lot of time selecting the files to attach. It'd be annoying to lose that work.

**Comment by Valodim** [comment]
While we're at it, we could also check if the mail is empty at the point of saving. There is no point to saving a draft that has no subject, body and attachments.

**Comment by jimimaseye** [comment]
I confirm that it doesnt offer the Save As Draft option even after you have spent time adding attachments (especially given the ball ache that is you cannot add multiple attachments in one go).

**Comment by philipwhiuk** [comment]
Looks like this wasn't merged into the 5.2 branch. It'll make it into the next major release if not before.
