### ISSUE TITLE
Allow another identity to be marked as the Sender of emails from an identity

### ISSUE THREAD

**Issue by Friedrieck** [k9mail/k-9#2123]
I have searched for existing issues, some relate to identities (e.g. #1117 or #935), but they are not addressing my problem/need.

### Expected behavior
I would like to be able to use K9 the way I use Outlook user agent on my PC (and then be able to finally get rid off it!): in the from field, write any email address I want and have the mail sent with this address as "From:".

### Actual behavior
When I use a K9 identity, the smtp server of my mail host (one.com) rejects the mail (error 554 5.7.1), but again, it works when I use Outlook. Why?

I had a look in the headers of a successfully sent message (from Outlook UA): the From is what I typed, but the Sender is my regular email account with which I authenticate on the SMTP server. I am pretty fine with this. I would suspect K9 maybe puts my 'From' address in the 'Sender' header as well, which would cause the error, or maybe does not set it at all (I tried to see the headers of a rejected email (from K9), I haven't seen the Sender tag, but it had not been sent, so...), which would be treated the same way.
I have also spotted something strange: in the rejected email's headers, the message-ID was built with the domain of the From address, not the one of my actual SMTP account ('Sender'), maybe is it also a possible cause.

Why all this? I own my domains, and I have set up specific sub-domains for emails. I can put anything before the '@', and I will get emails sent to it (kind of catch-all, but with rules behind). That way, I don't have to actually 'create' aliases (cumbersome), I can provide an arbitrary one any time, and it will work (most of the time, name/company/website@...). I can therefore spot when one of these addresses is misused and create a rule to trash all mails received through it if needed.
However, this solution does not allow me to 'send' mails, except with the Outlook UA. I haven't found an Android UA capable of this (and I have tested a lot of them). I would just love if K9 was able to do it, either by default, or as an extra option in the identity settings.

Please confirm how K9 handles the identities: as long as there is no SMTP settings per identity (I am personally not interested in this feature), it would seem logical to me that the Sender header (and message-ID) derive from the SMTP account being used to authenticate, not from the From header coming from the identity From email address, wouldn't it?

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
SMTP accounts have only a rough relation to email addresses. and no relation to MIME headers.

In olden times you could use any mail relay you liked. However due to spam you soon had to authenticate as a legitimate network user.

That still in many cases allows people to send personal emails over, for example, a university mail server by simply authenticating with their university credentials.

With spam still a problem the rules are gradually tightened of course.

> I had a look in the headers of a successfully sent message (from Outlook UA): the From is what I typed, but the Sender is my regular email account with which I authenticate on the SMTP server.

That's a behaviour. But often you only authenticate with 'user', not 'user@email.com'. There is not necessarily 'an email address' to get from this. Nor is at all guaranteed to be related.

> I haven't seen the Sender tag, but it had not been sent, so...)

**I don't think K-9 adds a Sender.** 

The reason is that "From" is the person who wants to send the e-mail and the "Sender" is the person who sends it. In normal usage this is the same person. In such circumstances you don't add a Sender header

It sounds like your core problem is that you are trying to use a mail-relay for a purpose that's not explicitly allowed. I should point out most mail clients would render both the From address and the Sender as

Sender@domain.com on behalf of From@domain.com

**Comment by philipwhiuk** [comment]
As this is more of a support question than a bug - please feel free to direct further questions on this to the mailing list - k-9-mail@googlegroups.com

**Comment by Friedrieck** [comment]
Surprisingly enough, I don't agree. I am perfectly OK with most mail clients behaviour rendering as "Sender@domain.com on behalf of From@domain.com". Having a From header different from the Sender header is totally acceptable, that's why both exist, google it if you want to check (e.g. mails sent on behalf of...).
It is highly likely that this use case (that I am sure is not just an eccentricity of mine, but is surely shared by others), could be solved by having K9 adding the Sender header (email address linked to that SMTP setting), as an option when using identities.
I don't understand your opinion about mail forgery (and won't take it personally ;-), especially when assessing the current use of K9 Identities (no mail address validation, precisely no use of Sender header...): used with a more relaxed SMTP service than mine, it actually is an open door for mail forgery...
Adding the Sender header (maybe optionally) would clearly inform about the actual Sender, compared to the desired From.
Reading again the issue #935, I think they complement each other.
Could you please reconsider this change request, adding the Sender header when using identities, or 'typed-in' From address, to actually better inform the recipients' mail clients?
Thanks.

**Comment by philipwhiuk** [comment]
Currently all email addresses on an account are linked to same SMTP server. How do we pick which one to use?

**Comment by Friedrieck** [comment]
It could be the 'initial identity', or the one at the top of the list (as it can be changed by the user), but the better would be in the identity screen, a check box option: 'Set a different address as Sender', with a text input field. Or if we want to let the user type in any address in the From field when creating a new message (as requested in #935), then an additional field could be shown below the from, when expanding by clicking the down arrow next to the To field (that makes appear the Cc and Cci, which could also usefully includes a reply-to field for instance).

**Comment by cketti** [comment]
That's a hack. I don't want us to support this in K-9 Mail. If the mail server denies sending mails with a From address that belongs to the authenticated user that is a problem on their end. Using the Sender header as a work-around feels wrong.

**Comment by Friedrieck** [comment]
This is not a hack, this is sending 'on behalf of', nothing more, please get information about it. Actually, your current implementation of identity could be seen as a hack, as you do not check that the From is the actual Sender. Using properly the Sender header would actually improve the information provided. The mail server will validate that the Sender header is allowed. The problem is that you do not use it today.

**Comment by cketti** [comment]
Sending mail "on behalf of" and identities are different things. The former is something we do not and will not support.

**Comment by Friedrieck** [comment]
Well, this is pretty radical, I won't 'troll' here to insist indefinitely, I do think this is a missed opportunity to improve K9 with the use of valid mail headers, especially in conjunction with identities, or 'typed-in' From addresses.
I just wish I had the skills to add this functionality myself. But I will have to stick to MS Outlook just for that. What a pity.
FYI, some info about the use of From and Sender headers:
[http://stackoverflow.com/questions/4367358/whats-the-difference-between-sender-from-and-return-path
](url)
[http://stackoverflow.com/questions/2668721/mailmessage-difference-between-sender-and-from-properties](url)
[https://www.tectite.com/fmdoc/from_vs_sender.php](url)
[https://www.emailarchitect.net/easendmail/sdk/html/object_from.htm](url)
[https://www.lifewire.com/send-mail-from-a-custom-email-address-with-gmail-1172019](url)
etc.

**Comment by glenpike** [comment]
This isn't an unusual request. Thunderbird allows users to customise the 'From' address for authenticated SMTP accounts. I have a wildcard mailbox on my domain, but the SMTP user is fixed allowing me to send from any mailbox (theoretically)

**Comment by cketti** [comment]
K-9 Mail already allows you to create additional identities that can be used for different 'From' headers. This issue was about the 'Sender' header.

A 'Sender' header is intended to convey the information that someone is sending the email on behalf of someone else, e.g. a secretary (Sender) on behalf of the person they work for (From).

**Comment by glenpike** [comment]
Yes, but I don't want to create a new identity for every single mailbox address that I use (10s-100s) - they all use the same login, I just want to customise the from address every so often.

**Comment by cketti** [comment]
What you want to do and what was proposed here are two different things. For your use case see e.g. #935

**Comment by glenpike** [comment]
Ok, I see. Thanks :)

**Comment by Ozfer** [comment]
This is still a problem. We need the ability to edit the from field without having to clicks threw a lot of menus and add a million identities. Making a guess would be even better but I do not require this.

**Comment by mvanboven** [comment]
Totally agree missing this feature. Friedrieck seems so right and cketti seems subborn and is wearing blinkers.

**Comment by tgkudelski** [comment]
Absolutely agree with @glenpike  @Friedrieck @Ozfer @annaluiseblume @mvanboven etc. that having custom "From" addresses would be super helpful (I am doing this myself with Thunderbird, in part through aliases and in part with partially-catch-all addresses configured on my mail server). I dare to add that nowadays it is a very basic feature that makes email life "tolerable" without having a super-duper AI Borg spam filter. I find the lack of this feature a big, big problem for k-9 on Android.

However I'm not sure the title of this issue (and the proposed solution) are in line with what is needed. Maybe this is what @cketti is referring to and maybe we should request this feature in #935 instead.

One thing that must be clear however is that the solution mentioned by @cketti to create a different k-9 identity for every "From" address/alias is *not* what users are requesting here. We are talking of managing 100-1000 different email address, very often not pre-configured but created on the fly at the whim of the sender.

Example: let's say that I have my POP on mydomain.com and my "real" email address is myuser@mydomain.com . Now, I want to create a rule for registering accounts on different online shops, and my mail server allows me to create aliases with wildcards. Then I create an alias of myuser@ which is eshop*@ . At this point, when I register a new account on stinkyfood.com I can register as eshopstinkyfood@mydomain.com while if I want to shop on verylongsocks.com I can use on the fly eshopverylongs@mydomain.com etc, all this without touching again the configuration of my mailserver.

As other users mentioned, this has various advantages: check if there is a misuse or leak of your data and where the abuse comes from, easily severing ties with a compromised account, archiving purposes etc.

**Comment by glenpike** [comment]
"We are talking of managing 100-1000 different email address, very often not pre-configured but created on the fly at the whim of the sender.
"
Yes, this is exactly what I want. To change  From on the fly without setting anything up because all my email addresses are related to the sender in order to combat spam and filter.

Thanks 😁

On 22 February 2022 10:59:23 GMT, "Tommaso Gagliardoni (Kudelski Security)" ***@***.***> wrote:
>Absolutely agree with @glenpike  @Friedrieck @Ozfer @annaluiseblume @mvanboven etc. that having custom "From" addresses would be super helpful (I am doing this myself with Thunderbird, in part through aliases and in part with partially-catch-all addresses configured on my mail server). I dare to add that nowadays it is a very basic feature that makes email life "tolerable" without having a super-duper AI Borg spam filter. I find the lack of this feature a big, big problem for k-9 on Android.
>
>However I'm not sure the title of this issue (and the proposed solution) are in line with what is needed. Maybe this is what @cketti is referring to and maybe we should request this feature in #935 instead.
>
>One thing that must be clear however is that the solution mentioned by @cketti to create a different k-9 identity for every "From" address/alias is *not* what users are requesting here. We are talking of managing 100-1000 different email address, very often not pre-configured but created on the fly at the whim of the sender.
>
>Example: let's say that I have my POP on mydomain.com and my "real" email address is ***@***.*** . Now, I want to create a rule for registering accounts on different online shops, and my mail server allows me to create aliases with wildcards. Then I create an alias of myuser@ which is eshop*@ . At this point, when I register a new account on stinkyfood.com I can register as ***@***.*** while if I want to shop on verylongsocks.com I can use on the fly ***@***.*** etc, all this without touching again the configuration of my mailserver.
>
>As other users mentioned, this has various advantages: check if there is a misuse or leak of your data and where the abuse comes from, easily severing ties with a compromised account, archiving purposes etc.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2123#issuecomment-1047675459
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
