### ISSUE TITLE
Editing recipients is broken (starting at least with version 5.203)

### ISSUE THREAD

**Issue by xaverm** [k9mail/k-9#2128]
On the TO, CC, and BCC entry lines, one expects recipients addresses to be editable. Also, one expects recipients addresses to be copy-cut-and-pasteable between the TO, CC, and BCC entry lines. This is broken in recent versions.
Eg.:

1) Enter abd@m.n into any of TO CC or BCC
Now, try to 'correct' abd@m.n into abcd@m.n
This does not work (anymore).
It used to work in earlier versions. 

2) Reply to *all* of an email, formerly addressed to you, and at least also to ab@c.de
Now, try to cut ab@c.de from the TO recipients entry line and paste it into the BCC (or CC) entry line.
This does not work (anymore). Instead the copy action produces a lower quote character.
It used to work in earlier versions. 

### Environment
K-9 Mail version: 5.203
Android version: several
Account type: IMAP

Currently, with this loss of edibility of addresses, recipients management is awkwardly complicated. PLS reintroduce editable recipients addresses.

Thank you!

xaverm

**Comment by cketti** [comment]
See #2081

**Comment by xaverm** [comment]
I'm sorry, but #2081 seems neither related to my report nor does it provide me with a solution to the problem:

I did not report on not being able to delete a recipient.

I did report on:
i) **not being able to edit** any of the recipients within any of the TO, CC, or BCC entry field. By "editing" I mean to change eg. a letter within an email address
ii) **not being able to copy/cut/paste** recipients between the TO, CC, and BCC entry field. Actually, Android's copy/cut/paste buttons still show up, but the copy action will only produce a lower quote character

I don't understand why #2081 has anything to do with that and why in turn you closed this report?

**Comment by cketti** [comment]
You're right. I only skimmed the first post.

Those are actually two issues. Looks like #1602 and #1925

**Comment by xaverm** [comment]
Yes, indeed these two issues seem to be the same as those of my report. Let me please try to weigh in heavily for a resolution of them since they are strongly related to everyday usability of K9:

- when you add an unknown/new recipient to the TO/CC/BCC lines, it may frequently happen that you misspell and need to correct part of an address. Now, you can only erase the hole address to redo everything. That's awkward.

- when you reply to a message with several recipients, there are frequent situations in which you want to switch a recipient from (say) TO to CC status. Which is easy to achieve by copy/cut/paste. With the new version this is broken and now you need to do a lot of additional typing to work around it.

Since both functionalities were present in earlier versions, I would very much hope that they can be re-implemented without too much hassle? 

xaverm

**Comment by Valodim** [comment]
Neither of those are super difficult, but they are still in the area of a day or two's worth of work. We will get to them, but we have more pressing issues at the moment. But as always: PRs welcome.
