### ISSUE TITLE
Search slowed since ?, even slower when mobile

### ISSUE THREAD

**Issue by bauerm66048** [k9mail/k-9#2129]
Been using this on Samsung devices (now T-mobile S5 with droid 6.0.1) for years in same way: on desktop, connected to wifi, letting it work without interacting or using interface.
Can't tell exactly when search got slow, though suspect sometime over last few months.
Otherwise, Love the app!
Thanks

###Expected behavior
When I go mobile, i use the search function to find small number of inbox emails. results used to be immediate (even when using same phone).

### Actual behavior
results take a long time to return the 4-6 messages i'm asking for. the screen will display "working" clock, then go blank, sometimes finish if i wait long enough, but i mostly quit waiting after (what seems like) 30-60 seconds.
all other functions seem normal.

### Steps to reproduce
1. have 250 emails in inbox, about 6 of which would return from the 1-word search term found in "subject" field
2. be mobile, on cell data, battery-powered, nearly fully charged
3. tap search button, enter 7-character word and "go"

### Environment
K-9 Mail version:
5.203
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Is this searching on the server or on the device? If you're searching on the server on a fairly bad mobile connection it will be slow.

**Comment by bauerm66048** [comment]
the account settings, search, "enable server search" is unchecked/false.
thnx

**Comment by chrysmun** [comment]
same here,  mobile search without server,  single word query on 200 email takes more than a minute and k9 freezes and screen goes black. 

behavior started about 2 months ago. this is extremely annoying. I've started logging about 2 weeks ago,  but where is the debug log stored?

**Comment by philipwhiuk** [comment]
This might be fixed by the re-addition of table indexes in #2158 

*fingers crossed*
