### ISSUE TITLE
Allow all outgoing email to be signed by default

### ISSUE THREAD

**Issue by spirosa** [k9mail/k-9#2140]
Hi,

Prior to 5.2 it was possible for the "sign outgoing message" to be selected by default on all new messages in an account. Please can this feature be restored?

### Expected behavior
All outgoing messages are either encrypted if a key exists or signed if no key exists

### Actual behavior
The 'enable PGP sign only' menu option must be selected for each message and reply 

### Steps to reproduce
1. Compose new email in a K-9 instance with open keychain installed and a valid private key set up
2. Verify that there is no ability to automatically sign the message
3. Select 'enable PGP sign only' from the menu
4. Send the message
5. Compose a new message
6. The 'sign only' options must be selected again. 

### Environment
K-9 Mail version: 5.2

Android version: 13

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
See https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html
