### ISSUE TITLE
Unable to use PosteCert PEC on K9mail

### ISSUE THREAD

**Issue by PeopleInside** [k9mail/k-9#2149]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Actual behavior
Tell us what happens instead

I try to configure a PEC mail (Poste Cert Mail) and the working configuration on Thinderbird and bluemail is indicated here: http://postecert.poste.it/pec/configurazione.shtml

but K9mail send error message "Unable to connect" also Fastweb mail is not working with K9Mail. Fastweb mail configuration available here: https://fastweb.it/myfastpage/assistenza/guide-configurazioni/smartphone/config-android/

### Expected behavior

I expect that all works fine. >In blue mail is working fine, K9 mail is not working with Fastweb and PEC Poste Cert mail.

### Steps to reproduce
Just try to configure PosteCert or Fastweb

### Environment
K-9 Mail version:
5.203

Android version:
Android 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):

IMAP, POP 3

**Comment by cketti** [comment]
Looks like the servers only support TLS ciphers we consider insecure. Tell your email providers they need to step up their security game if they want K-9 Mail users to be able to connect to their servers.

https://www.htbridge.com/ssl/?id=a05f5eb0769f1a6a3b59b9bfdcd6bfcab5a77defe5ef0265550f9776d58ef617

https://www.htbridge.com/ssl/?id=dc958dd0c69ef7e80e70fa0ccd6cf295d53b2ea0b585e990e90504582ad6128c

**Comment by PeopleInside** [comment]
You are Amazing. My congrats to you, you are right. You are the first security email app that report this issue. Thanks!

I will inform Fastweb and PosteCert
