### ISSUE TITLE
K9 mail sends mail with no sender

### ISSUE THREAD

**Issue by Libaud** [k9mail/k-9#2153]
Hi,

Sometimes K9 mail sends mail with no sender.

In fact the sender informations does not appear in client mail software of recipients.

It is not systematic.

### Environment
K-9 Mail version:
Latest version
5.203

Android version:
6.0.1 Marshmallow

Account type (IMAP, POP3, WebDAV/Exchange):
Pop3 accounts on mutualized web server

**Comment by cketti** [comment]
1. You mean the `From` header line is missing when the message arrives at the recipient?
2. Does the message in your Sent folder contain a `From` header line?
3. Does that only happen for specific recipients?
4. Do you have more than one account set up in K-9 Mail? If so, does it happen with all of them or only with one specific account?

**Comment by Valodim** [comment]
Also, can you get the source of an email that exhibits this problem?

**Comment by cketti** [comment]
No information provided.

**Comment by kode-kristoff** [comment]
Hi, I have this problem as well. It happens with 35+ recipients. Shall I open a new issue or how shall I submit example mails? Problem exist for both Gmail account and other mail account. 
Best regards 
Kristoffer

**Comment by kode-kristoff** [comment]
Hi, I have this problem as well. It happens with 35+ recipients. Shall I open a new issue or how shall I submit example mails? Problem exist for both Gmail account and other mail account. 
Best regards 
Kristoffer

**Comment by kode-kristoff** [comment]
Hi, I have this problem as well. It happens with 35+ recipients. Shall I open a new issue or how shall I submit example mails? Problem exist for both Gmail account and other mail account. 
Best regards 
Kristoffer

**Comment by kode-kristoff** [comment]
Sorry for spamming 😊
Best regards 
Kristoffer

**Comment by bill-mcgonigle** [comment]
I have a message with source that I can share with somebody privately (so I don't post my correspondents email addrs on github) that caused a failure here (and some embarrassment).   I'm not sure if this particular bug needs to stand, though, if #822 is the actual cause.
