### ISSUE TITLE
Cannot import client p12 certificate

### ISSUE THREAD

**Issue by ipesando** [k9mail/k-9#2156]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I expect the decripted certifcate to be imported

### Actual behavior
the chosen certificate is erased
I get a window with the list of remaining certificates 

### Steps to reproduce
in setting up the incoming server i choose 
account setttings->sending mail->outgoing server
flag require sign-in
choose client certificate as authentication
then within the window I choose import
a new window with the list of certificates available on sdcard0 appears
I choose the certificate
I give the certificate pwd
the certificate contain is showed
a message says the import is ok
a window with the certificates on sdcard0 appears. 
The chosen certificate is deleted

### Environment
K-9 Mail version: 5.203

Android version: 4.2.2

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by philipwhiuk** [comment]
OpenKeychain only handles PGP/MIME.

We definitely should not delete your file so I'll look at that first.

Client certificate issues are hard to test as most email providers don't support them :(

**Comment by philipwhiuk** [comment]
We use Android's inbuilt certificate importer for this.

**Comment by cketti** [comment]
Doesn't appear to be a K-9 Mail issue.

**Comment by ipesando** [comment]
IMHO it is a K9 problem.
The reason: I had as account setting -> storage -> external storage and it did not work
I changed to -> interal storage, it worked.
Then I changed back to -> external storage and all was fine.
