### ISSUE TITLE
Bullet text missing  in message body

### ISSUE THREAD

**Issue by Vkay144** [k9mail/k-9#2165]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Bullet list should show the text in message body

### Actual behavior
Text is missing for bullets in messages being received after latest upgrade

### Steps to reproduce
1. Login
2. Check messages that hv bullets
3. Encounter text missing for bullets 

### Environment
K-9 Mail version:
5.2.0.3
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by Vkay144** [comment]
If there is an email I'd to which I can share screenshot .. let me know

**Comment by Valodim** [comment]
Is this perhaps the same issue as #2015?
