### ISSUE TITLE
crossed rectangles instead of question marks in e-mail preview

### ISSUE THREAD

**Issue by d3n1c1d3** [k9mail/k-9#2168]
Ã�Â�Ã�Â¢Ã�Â�Ã�Â�Ã�Â�Ã�Â¤

I already spotted another issue that might be related. but i want to make thinks clear, because I do not realy understand the issue on #1663 

### Expected behavior
i expect to see the same question marks in the preview like i can see them in the e-mail it self.

### Actual behavior
the mail preview has not the same characters as i see them in the e-mail itself.
all questionmarks from the e-mail content are shown in the preview a crossed rectangle.
Ã�Â�Ã�Â¢Ã�Â�Ã�Â�Ã�Â�Ã�Â¤

### Steps to reproduce
i tried i manually, but it seams that it might be a github specific problem.
so. i just hope that it is reproducable for me, after posting this issue here on github. i just have signed to all notifications in k-9.
i let you know if it is the same. so i posted the line with the wrong encoded output directly at the beginning.

![k-9-issue---2017-02-03-00 02 45](https://cloud.githubusercontent.com/assets/3397868/22575177/46a5f718-e9b4-11e6-819d-076f0d88764f.jpg)

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1 (security patch 01.05.2016)

Account type (IMAP, POP3, WebDAV/Exchange):
gmail IMAP

**Comment by d3n1c1d3** [comment]
seams that the poster does not get the issue e-mail itself.

**Comment by philipwhiuk** [comment]
The preview is rendered as a TextView whereas the email content is rendered as a WebView. This is almost certainly an Android / font decision regarding what glyph to use for an unknown character.

There's no 'correct' answer as to what glyph to use - both the crossed rectangle and ? glyph are common and may well represent the same Unicode code point just in different fonts.

**Comment by cketti** [comment]
See https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character
