### ISSUE TITLE
It stutters on weak cpu

### ISSUE THREAD

**Issue by nietonie** [k9mail/k-9#2173]
### Expected behavior
Not to stutter

### Actual behavior
version 5.203. It stutters when scrolling the screen in Unified Inbox view or any other email list view.

### Steps to reproduce
 It is about increased cpu requirement in 5.203. I rolled back to version 5.202

### Environment
K-9 Mail version:5.203

Android version: 4.01, 4.2.2 
CPU: 2* 1GHz

Account type (IMAP, POP3, WebDAV/Exchange): imap, pop3.

**Comment by cketti** [comment]
It's most likely faster after rolling back to 5.202 because the database has been recreated. Can you please upgrade to 5.203 again and check if the speed is acceptable?

**Comment by nietonie** [comment]
Now the speed is acceptable as before!

Regards,
Wojciech Borzemski

On February 6, 2017 4:33:18 AM CET, cketti <notifications@github.com> wrote:
>It's most likely faster after rolling back to 5.202 because the
>database has been recreated. Can you please upgrade to 5.203 again and
>check if the speed is acceptable?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2173#issuecomment-277579374


Pozdrawiam,
Wojciech Borzemski

**Comment by philipwhiuk** [comment]
I expect this is caused by the removal of database indexes I fixed.
