### ISSUE TITLE
'Whistleblowing' option

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2183]
Either in the encryption options or otherwise, we should add a 'whistleblowing' option. I consider this a 'slider preference' option.

This would configure the app to do the following:

* Request the OpenPGP application to create a key - this may result in an activity for basic details but would automate as much as possible
* Encrypt the email with the key associated with that email address
* Not save the e-mail to Sent Items
* Delete the OpenPGP key once it's been used.

The signing key would only be created and available during the send process.

The aim here is to 

* Support a mid level of plausible deniability. We're not interested in security services here (for that, #2139)  more the corporate case.
* Help retain the link between signing and trust
* Remove the corner case where people request encryption without signing.

**Comment by cketti** [comment]
I'm against this. There's no way we can guarantee a level of privacy anywhere close to what is required for "whistleblowing" without getting caught.

**Comment by sharpe5** [comment]
@cketti We can have some level of privacy if we send the email via Tor.

**Comment by cketti** [comment]
@sharpe5: You can do whatever you want, including stuff that might get you killed. K-9 Mail doesn't need to encourage or support that.

**Comment by Valodim** [comment]
(for the record: I'm with cketti here)

**Comment by rugk** [comment]
I too. It's silly to offer this. K9 mail should of course offer support for PGP, Tor etc. and if you use it properly you could maybe even use it for whistleblowing, but that depends on the person who uses it. This has much more to do with OpSec and so one, so from the technical point of view you cannot do much.

**Comment by sharpe5** [comment]
## What would Snowdon think of this?

We know what Snowdon would think of this: he would be horrified.

If we force everyone to sign every email they send with a fixed signature, then its simple to construct a network graph of friendships, like this:

![2](https://cloud.githubusercontent.com/assets/1290916/22854301/48376d72-f063-11e6-965b-b9aefec4ed76.jpg)

## What would North Korea think of this?

They would be utterly delighted! 

Why?
* It's [easy to extract a signing key ID from the message](http://security.stackexchange.com/questions/62916/can-i-get-a-public-key-from-pgp-signature).
* Then you can construct a network graph which links you to everyone you communicate with. 
* Then you can do a lookup query on the network graph to show who knows who.
* This works, even if the origin of the email is obscured using Tor!

Once they know who is friends with who, they can stamp out an entire organization, member by member.

As a similar example, when North Korea analyzes cellphone communications, as a first order approximation, they don't care about the content of each phone call or txt. What they care about is who called who, so they can construct a network graph of an organization. 

## Whats the solution?

Give people the option to avoid signing every message they send!

This is why people use "burner phones" in real life.

This would certainly frustrate and annoy North Korea.

**Comment by Valodim** [comment]
(deleted a message here. please don't spam our issue tracker with misinformation)
