### ISSUE TITLE
Support saving to removable storage

### ISSUE THREAD

**Issue by PthDE** [k9mail/k-9#2187]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

Upon opening an email with an attachment, notification window should appear with two buttons namely, 'Open' and 'Save'.
Touching the 'Open' button should open after offering a selection of apps that associate to the type of the file to be opened.
Touching 'Save' should result in the file being saved to the storage medium set or chosen through K-9's general and/or account settings.
The above should happen irrespective of the email account type.

### Actual behavior
Tell us what happens instead

Upon opening the email, notification window appeared for an attached video file (MP4 format). In the window were two buttons 'Open' and 'Save'.

Touching 'Open' button offered to play the file which worked fine after selecting the VLC app.

Pressing 'Save' results in a notification of short duration stating "Unable to save attachment to SD Card"

The above also happened with another example email which had a still picture (JPG format) attachment.

The above happens with an IMAP account yet not with a POP3 account.
[k9-log.txt](https://github.com/k9mail/k-9/files/752889/k9-log.txt)

### Steps to reproduce
1. Opened K-9
2. Opened a mail in an IMAP account with a video attachment (had <5MB)
3. Touched 'Save' button
4. Error message appeared for circa few seconds

### Environment
K-9 Mail version: 5.203

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Set 'Global settings > Miscellaneous > Save attachments to…' to a valid path.
See https://k9mail.github.io/documentation/settings/global.html#save-attachments-to

**Comment by PthDE** [comment]
Please, why is this regarded 'closed'.

I attach a screenshot showing the storage settings to sdcard1

Please notice that the problem occurred with an IMAP account (Gmail) and not with POP3 accounts (Web and GMX)
 
![2017_02_06_08 09 29](https://cloud.githubusercontent.com/assets/17206446/22645213/40229662-ec66-11e6-9782-c1cb535c2e59.jpg)

**Comment by philipwhiuk** [comment]
This isn't a path issue. It's an SD card issue. See comments I made on https://github.com/k9mail/k-9/issues/863#issuecomment-206616235

WRITE_EXTERNAL_STORAGE doesn't give you permission for saving to an SD card.

**Comment by PthDE** [comment]
Thank you @philipwhiuk but can SD Card access rights be different according to email account type?

As originally described, the problem of not being able to save to SD Card ()  appeared when trying to save an attachment from an email in an IMAP account (in this case to a Gmail server) yet there is no problem in saving from POP3 account emails. This surely can't suggest SD Card access rights/permissions??

**Comment by philipwhiuk** [comment]
Hmm... that would indeed be odd. Can you please record a debug log.

**Comment by PthDE** [comment]
In producing a new debug log K-9 was removed and re-installed to make all afresh so to say. That step completed without any problem. Also OI File Manager was installed replacing File Commander which was not recognised by k-9. The save to SD card problem was repeatable but irrespective of email account type. This makes much more sense and suggests original observation raising this bug report were false. The problem is appropriately fits to description in https://github.com/k9mail/k-9/issues/863#issuecomment-206616235 by philipwhiuk.

On the above basis this bug report will now be closed

Note: As this SD card issue is one for the proper functioning of many apps, a work-around will be sought to resolve it. This could require rooting the device.

**Comment by philipwhiuk** [comment]
#863 is about the database. Let's leave this one open for the simpler case of saving attachments.

**Comment by PthDE** [comment]
Many thanks.

As a work around I have amended the permissions XML file by adding 'media_rw' under the WRITE_EXTERNAL_STORAGE. K-9 (other apps too probably) now saves attachments on the external SD card storage media.

I do not like modifying access rights/permissions but have no alternative but to do so. K-9.

Presumably account storage cannot be moved to the SD card because of SD card access? I am a retired engineer and have too little knowledge to call myself a software expert of any kind.

**Comment by cketti** [comment]
I created issue #2844 for our plan to solve this in the future.
