### ISSUE TITLE
Improve colours of encryption icons for colour blindness

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2189]
### Expected behaviour
The app should be usable by people who are colour blind

### Actual behaviour

The colours are all very similar. The icons do help a little but perhaps not enough

![vc_jny6vg_sim](https://cloud.githubusercontent.com/assets/1316415/22628664/ffa353d8-ebcf-11e6-971a-ba55b902c7eb.jpg)

![vc_hnp2kr_sim](https://cloud.githubusercontent.com/assets/1316415/22628665/00ff0b00-ebd0-11e6-8330-bfadd70d7de3.jpg)

### Steps to reproduce
1. Be colour-blind or use a site like http://www.vischeck.com/vischeck/vischeckImage.php to simulate it.
2. Browse the app and receive e-mail

NB: Ideally a test tool would exist either as an overlay app or in the IDE.

### Environment
K-9 Mail version: 5.204

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by dschuermann** [comment]
Sry, but I don't really see the issue here, the icons are already distinguishable even without color. In Screenshot 1, there is even a description about each icon. In Screenshot 2, striked out means no encryption possible, and the three dots indicate the validation status of the key.

**Comment by cketti** [comment]
Newer Android versions have color correction modes for different kinds of color blindness (available in Android settings under 'Accessibility'). I don't think we should attempt to solve this on an application level.

**Comment by philipwhiuk** [comment]
Okay. It seems sensible to rely on the Android behaviour. I just tried it and it seems to work for K-9.

**Comment by rugk** [comment]
No, please reopen this issue.
At least you could - which would also be useful for non-color-blind people - use an open padlock icon for the orange and red state. Open means it is unlocked, it is (potentially) insecure. Only the green icon should be locked (aka secure).

**Comment by dschuermann** [comment]
@rugk The difference between orange and green states is indicated by the number of dots on the right side: 2 dots (orange) vs. 3 dots. So color-blind people can already differentiate.

Iconography is not easy! An open padlock is a very bad icon in general and I don't know any modern application that uses it to indicate insecurity. I even have a counterexample where it indicates "decrypted correctly":
![gpg-receive](https://cloud.githubusercontent.com/assets/321888/22629768/d128bb8e-ebec-11e6-8874-8a99d0c79697.jpg)

If you want to propose a new set of icons, please do so by including the whole set of possible states in K-9 Mail.
