### ISSUE TITLE
With many accounts the default account doesn't check mail

### ISSUE THREAD

**Issue by jmlobert** [k9mail/k-9#2191]
### Expected behavior
All accounts check mail as configured (usually between 15 minutes and twice a day)

### Actual behavior
All 12 accounts check mail as configured, EXCEPT the account defined to be the default account. I can check mail manually ad it updates correctly, but doesn't check automatically.  Problem persists when moving to new phone with different Android version (fresh install, but ported settings)

### Steps to reproduce
1. Set one account to default, assign polling frequency to 15 minutes, wait. 
2.
3.

### Environment
K-9 Mail version: 5.203, the problems tarted with 5.200

Android version: 7.1.1 (problem started with different phone and Android 6.1)

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by philipwhiuk** [comment]
My guess is this is due to the sheer number of accounts. A debug log would be useful.

**Comment by jmlobert** [comment]
It is consistent, though, and the account in question was the 3rd from top, it seems to check top down. I then moved it to the top to be the first to be checked, the issue persists. 

How do I create a debug log?
