### ISSUE TITLE
Add unit tests for LineWrapOutputStream

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2209]

**Comment by ployt0** [comment]
On it.

**Comment by danwain** [comment]
I've added a simple unit test at #2313

**Comment by danwain** [comment]
Sorry I may have been a bit over eager @ployt0 as I've just looked at your code it is more extensive. I would also agree with some of the comments that probably redesigning part of it rather than hacking in these fixes would be a better solution

**Comment by cketti** [comment]
Closing. See https://github.com/k9mail/k-9/pull/2298#issuecomment-284837655
