### ISSUE TITLE
Add unit tests for MergeCursor

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2211]

**Comment by francoismasson** [comment]
Hi, I'll try to do this issue !

**Comment by ployt0** [comment]
You beat me to it!

**Comment by sanovikov71** [comment]
Hi, I have added some unit tests for MergeCursor.
By the way, I would like to add some tests for methods moveToNext, and moveToPrevious, but I am not sure what test scenarios are better for them, and what Comparator to use.
@cketti Do you have any suggestions?

**Comment by fobo66** [comment]
You've mentioned in PR #2493 that you want to make MergeCursor obsolete over a year ago, so this issue could be closed as well as mentioned PR.
