### ISSUE TITLE
Make all keys in global_preferences.xml lowercase

### ISSUE THREAD

**Issue by dschuermann** [k9mail/k-9#2213]
Some keys in ``global_preferences.xml`` are CamelCase and others are lowercase. We should unify them to lowercase to make it clear that there is no connection to the actual keys inside the preference storage layer.

This difference was confusing me in https://github.com/k9mail/k-9/pull/2130/files/6e982690d24e7de87c2e2eeb104403e6a1e0f082..884b12a48b6d8dc3e0de37f052ae2fe19387bb2a#r100053076

**Comment by RobinBossart** [comment]
Hello, 
I would like to do this as my first contribution, is it possible?

**Comment by cketti** [comment]
@RobinBossart: Sure. Just create a pull request for it.
