### ISSUE TITLE
No way to disable empty subject line "warning"

### ISSUE THREAD

**Issue by z28cueball** [k9mail/k-9#2236]
The newest version of K9 refuses to send messages with an empty subject unless you click send a second time.  There does not appear to be an option to disable this obnoxious behavior.
While some people may desire this warning, it was never present in the past, and if CKETTI refuses to add a setting for this because there are "too many" settings already, how did he decide that the people who want this warning should get it, over the people who never wanted it? 
This is absolutely something that should be an OPTION. What is a "feature" for some people is an annoyance sufficient to make others stop using it.

**Comment by Valodim** [comment]
Please don't open duplicate issues when you are aware that one exists for your issue.

Also, reminder that this is free software, you didn't pay for anything and there is no ads, people work on this in their free time. Yelling at people who owe you nothing isn't going to earn anyone's favor.

**Comment by z28cueball** [comment]
A) I wouldn't have opened a new issue if the original issue wasn't closed.
B) i wasn't "yelling" at anyone

**Comment by sulphide3** [comment]
this used to be configurable. please restore the ability to disable this.
