### ISSUE TITLE
Support "delSp" for format=flowed

### ISSUE THREAD

**Issue by Valodim** [k9mail/k-9#2237]
When I added support for format=flowed in #1835, I missed delSp for some reason. This should be simple to add, see also rfc2646.

**Comment by vaibhavchellani** [comment]
I would like to work on this issue , if you permit,

**Comment by Valodim** [comment]
Sure, go ahead!

**Comment by AnirudhBadri** [comment]
Hello! I am new to the open source community and would like to help fix this issue. Is this currently free for me to tackle?

**Comment by vaibhavchellani** [comment]
@AnirudhBadri i have started working on it .

**Comment by YESALAM** [comment]
I have opened a Pull Request #2351
