### ISSUE TITLE
Contact nicknames not searched

### ISSUE THREAD

**Issue by kenyoni** [k9mail/k-9#2240]
### Expected behavior

When composing email, in the To:, CC:, and BCC: fields, typing in a contact's nickname should reveal contact(s) with matching nickname(s).

### Actual behavior
Typing in a contact's nickname reveals no matches.

### Steps to reproduce
1. Create a contact with a nickname
2. In k-9 email, compose a new email
3. In any of the address lines type the contact's nickname
4. Note that there are no matches

This is kinda important to me because I don't remember/know most of the real names of my Burning Man contacts, only their Playa (nick) names. (volunteer manager so have 150+ of them)  So every time I go to send them email, I have to go to my contacts app, look it up there and then send email. PITA.  There are also other social groups where this is common. (furries, for example)

### Environment
K-9 Mail version: 5.203
Android version: 7.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Starting point: `RecipientLoader.fillContactDataFromQuery()`

**Comment by daquexian** [comment]
I would like to work on this :)

**Comment by ployt0** [comment]
I've been looking at this but got distracted trying to make tests for RecipientLoader because it needs access to some sample data. I think it's harder than beginner level.

**Comment by AnirudhBadri** [comment]
Hello! I am new to the open source community (applying for GSoC). I would like to work on this enhancement. Would that be alright? If this is already being worked on by someone else, do let me know of a different beginner bug that I can fix. 
Please guide me regarding the procedure to contribute etc.

**Comment by daquexian** [comment]
@AnirudhBadri I have open a PR about this issue and the PR has been approved, so you may choose a another issue :)

**Comment by AnirudhBadri** [comment]
@daquexian, I see. Sorry about that.

**Comment by Hitekshaa** [comment]
hello, i am Hiteksha Basiya. I would like to work on this issue so can i work on this issue?

**Comment by steverA** [comment]
hint (perhaps?): ContactsContract.CommonDataKinds.Nickname

**Comment by garvitanand2** [comment]
I would like to work on this Issue

**Comment by rhari991** [comment]
@cketti This has been fixed #2264, so should be closed.
