### ISSUE TITLE
No push mail under Android 7

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#2242]
Received an OTA update to Android 7 on my S7 edge.
Since then, push mail is not working anymore.
Mail list is only updated if I trigger this manually. 
Took k9 out of the list of apps that are power monitored, but this did not affect push mail
K9 version 5.203

**Comment by beerisgood** [comment]
Works under LineageOS (Android 7.1.1) on OnePlus 2
K9 version 5.203 from F-Droid

**Comment by ozziebiker** [comment]
Yeah, same here. Update to Android 7 on Galaxy S7 (not Edge) and K-9 mail says "syncing disabled". I can briefly set it back to automatic by toggling between Global/Network/Background sync: "When auto-sync is checked" and "Always", but this doesn't last very long. By contrast, Samsung/Google finally updated their Email app to allow syncing (minimum frequency 15 mins though!). Sure this is not related to K9-mail problem, but it is a coincidence, however.

**Comment by inguin** [comment]
Same here, on a Nexus 5X with Android 7.1.1. Switching from Push to Polling doesn't help, either. I've been using K-9 on my last phone (Android 5.x, as far as I recall) for years, without issues.

**Comment by philipwhiuk** [comment]
This is caused by, or at least heavily affected by, Doze #857
