### ISSUE TITLE
Only one password for in+outgoing connection

### ISSUE THREAD

**Issue by beerisgood** [k9mail/k-9#2244]
If you create a new account and type the password, you need to enter it for both out- and incomming, Why?
No one have different passwords for that.

Also if you change the password on the provider website you need to change the new password twice in k9 which is realy annoying.

**Comment by njeyaakili** [comment]
There is no requirement that ones outgoing and incoming are even provided by the same service, much less that one authenticates the two using the same credentials. 

It might be reasonable to have a checkbox that says something like "outgoing credentials same as incoming", which if checked wouldn't prompt for outgoing setup/credentials. Short of that I think that assuming that they are the same, or one can be divined from the other, is likely to cause trouble for a range of users.

**Comment by cketti** [comment]
We certainly won't remove the ability to specify different passwords for incoming and outgoing servers. But it does make sense to optimize for the common case, i.e. having only one password.

**Comment by beerisgood** [comment]
A option would be enough, sure.

**Comment by doktorhorst** [comment]
+1 for a checkbox in server settings "outgoing credentials same as incoming".
(I just helped an older person set up their smartphone, they liked the app overall, and that was their feedback... so they don't have to enter their password twice when changing it)

**Comment by beerisgood** [comment]
I no longer use k9 and also cketti wrote everything.
Closed

**Comment by cketti** [comment]
Since @beerisgood seems to insist that this issue stays closed I created a new issue to track this feature request: #4422.

**Comment by beerisgood** [comment]
I close this issue again because no one fix it after ~3 years so i don't think it make sense to recreate it.

Anyway i'm out.
