### ISSUE TITLE
Notifications choosen language issue

### ISSUE THREAD

**Issue by carbsk** [k9mail/k-9#2245]
Hi, I have a Samsung Galaxy Note 5 with Android 6.0.1, my device language is set to Spanish and k9 mail language is set to English (because in Spanish notification delete button is hidden because "mark as read" text, is to long), the thing is that some times notification is shown correctly in English and some times is shown in spanish, I haven't figure out why.

I have a screen video recorded, try to attached here, if I can't please tell me where to send over email.

Thanks.

[tmp_22194-2017_02_16_16_12_05.mp4964100838.zip](https://github.com/k9mail/k-9/files/781786/tmp_22194-2017_02_16_16_12_05.mp4964100838.zip)

**Comment by philipwhiuk** [comment]
> because in Spanish notification delete button is hidden because "mark as read" text, is to long

Can we not just fix this translation? That seems like something we'd want to do anyway.

The fact that you can configure K9 to have a separate language has always struck me as an odd feature.

Regardless I have worked out why this happens and will submit a PR for it.

**Comment by carbsk** [comment]
Hi,
Well yes, that it'll be helpful, maybe you can make an easy fix just leaving only icons on notification buttons, everyone knows what's each button for.

Thanks.

**Comment by carbsk** [comment]
Hi, 

I was thinking that maybe if you do it like that, removing text from notifications buttons, probably you may add the other icons, just like when reading e-mail, all buttons could be reply to all (cover reply and reply to all or separete if better), forward, mark as read, move to folder, delete, I think these are the most common used. 

Thanks. 
Regards.

**Comment by Valodim** [comment]
Closing because of #2262. If the problem itself persists, it should be solved by way of a different translation string.
