### ISSUE TITLE
Can I use more than 20 email accounts?

### ISSUE THREAD

**Issue by Peterpc58** [k9mail/k-9#2251]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
When I make my 21 est email account, it will not receive the mail. 

### Actual behavior
Tell us what happens instead
noting
### Steps to reproduce
1.make a 21 or 22nd email account in K9
2.
3.

### Environment
K-9 Mail version: 5.203

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):imap

**Comment by cketti** [comment]
There's no artificial limit on the number of accounts. If it's not working then it's because of something else.
