### ISSUE TITLE
Username or password is incorrect. (Command: *sensitive*; response: #3# [NO, ALERT], Too many simultaneous connections. (Failure)]

### ISSUE THREAD

**Issue by egesezen** [k9mail/k-9#2254]
Hello,

After I upgraded my K-9 mail client to the latest version, 5.203, I have received the following notification:
_"Authentication failed.
Authentication failed for xxx. Update your server settings."_

I tapped on it to go to the settings screen. Then on the settings screen, I tapped on the "next" button.  Then I received the following message:
_"Setup could not finish
Username or password is incorrect. (Command: *sensitive*; response: #3# [NO, ALERT], Too many simultaneous connections. (Failure)]"_

What am I supposed to do? Is there a fix?

### Environment
K-9 Mail version: **5.203**

Android version: **6.0.1**

Account type: **IMAP**

Device: Moto G4

**Comment by philipwhiuk** [comment]
You have too many folders configured for Push. Each folder requires one connection.

**Comment by egesezen** [comment]
Hi,

Thank you for quick reply.  It wasn't a problem before although I had the same number of folders configured to push.  I didn't change any setting.  What has changed?

Thank you.

**Comment by philipwhiuk** [comment]
I believe that we're no longer silently ignoring some authentication errors and instead showing them.

We have an existing issue to improve how we handle various error case - see #2000

In this particular error case we should probably show you what connections are being used.

**Comment by egesezen** [comment]
Thank you. I saw those solutions offering limitation of number of folders but that actually does not solve the problem, does it? What if I need to have all folders that need push?

**Comment by philipwhiuk** [comment]
Then you need to speak to your email provider. It's an email provider enforced limit.

Most email applications will only push the Inbox and will periodically poll the others.

**Comment by egesezen** [comment]
Thank you.  My problem was not solved.
