### ISSUE TITLE
Insert <hr> element when converting from text to HTML

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2259]
When converting text to HTML replace what looks like horizontal lines drawn with ASCII characters with `<hr>`.

Examples:
```
text
---------------------------
some other text
===========================
more text
-=-=-=-=-=-=-=-=-=-=-=-=-=-
scissors below
-- >8 --
other direction
-- 8< --
end
```

I'm not quite happy with the approach in PR #473. But that's the functionality we want.

**Comment by FleetAdmiral** [comment]
Hey guys! I'd like to begin by taking up this bug (applying for GSoC!), it'd be great if someone could guide me around with it!

**Comment by Sayan98** [comment]
I'd like to work on this enhancement. At the moment I'm trying to implement it using regex.

**Comment by clawoflight** [comment]
This should be straightforward to implement with a regex.

I would definitely use TDD for this (write the unit-tests first)!

**Comment by Sayan98** [comment]
@cketti I've implemented this. Please check PR #2300 .
