### ISSUE TITLE
Ability to see IMAP keywords in message view

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2260]
### Expected behavior
Be able to see IMAP keywords

### Actual behavior
Only specific keywords are handled (e.g. Flagged). Most keywords are only visible in headers.

### Developer notes

See https://github.com/k9mail/k-9/pull/558 for starting work and design discussion. Further design discussion should be had to look at what features are required and how various clients handle these tags.

**Comment by ccoenen** [comment]
the discussion is actually in: https://github.com/k9mail/k-9/issues/769

The list of tickets is growing:

* https://code.google.com/archive/p/k9mail/issues/2532 (2010! Seven years!)
* https://code.google.com/archive/p/k9mail/issues/4101
* https://github.com/k9mail/k-9/pull/146
* https://github.com/k9mail/k-9/pull/558
* https://github.com/k9mail/k-9/issues/769

**Comment by cketti** [comment]
See #769

**Comment by daniele-athome** [comment]
You're forgetting k9mail/k9mail.github.io#57 :-)
