### ISSUE TITLE
Warnings on deprecated APIs and ignored return value can cause unexpected results

### ISSUE THREAD

**Issue by Acmine** [k9mail/k-9#2271]
Hi,

I am using Lint to detect warnings that can cause expected results in k-9. And I found the following warnings that are interesting:
1. **'setProgressBarIndeterminateVisibility(boolean)' is deprecated**
Warnings are reported on [line 148 in ChooseFolder.java](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/ChooseFolder.java#L148) in and [line 1484 in MessageList.java](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/MessageList.java#L1484).
This API has been no longer supported since API 21 and deprecated in API 24 ([doc](https://developer.android.com/reference/android/app/Activity.html#setProgressBarIndeterminateVisibility(boolean))). ProgressDialog may be used as a replacement.

2. **'android.text.format.Time' is deprecated**
The warning is reported [on line 978 in K9.java](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/K9.java#L148)
This class has been deprecated since API level 22. Several issues of this class like not thread-safe are specified in the [documentation](https://developer.android.com/reference/android/text/format/Time.html) It is better to use GregorianCalendar instead.

3. **Result of <code>File.delete()</code> is ignored**
[on line 140 in BinaryTempFileBody.java](https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/internet/BinaryTempFileBody.java#L140)
It is possible that File.delete() fails due to unexpected reasons. Ignoring the return value will keep the file always there and consumes additional disc space.

These are the interesting Lint warnings I have found. Hope this can help. :)

**Comment by philipwhiuk** [comment]
I'd rather see separate issues for each problem. However.

1. This will be fixed by the change to Material Design I expect - I don't think it's worth trying to fix now - a modal dialog isn't really appropriate here. We need a more detailed look at how we show sync in progress.
2. This is a valid issue. (Tested) PRs accepted to fix this.
3. It's a temporary file. Deletion is highly unlikely to fail and there's not a lot we can do about it if it does. We could add some logging for the failure case though (at higher than debug).

**Comment by joelowj** [comment]
Hi, if this issue is still open, I would like to work on it.

**Comment by philipwhiuk** [comment]
Go ahead @joelowj :)

**Comment by rijuldhir** [comment]
@philipwhiuk Can I work on this?

**Comment by joelowj** [comment]
Hi @rijuldhir a PR for this issue has been sent and waiting for approval.
