### ISSUE TITLE
PGP/MIME with Protected Headers ("Memory Hole")

### ISSUE THREAD

**Issue by J-J-Chiarella** [k9mail/k-9#2277]
Enhancement request:

Please implement the PGP/MIME Protected Headers known as "memory hole" as implemented in Thunderbird's Enigmail plug-in (though it may not yet be widely enabled).

It protects mail from having altered From and Subject fields most importantly.

Filing a bug so as to track its progress.

**Comment by user1831** [comment]
The Memory Hole standard is documented here:
https://modernpgp.org/memoryhole/

I think it's definitely necessary to implement this standard. Please do so!

**Comment by philipwhiuk** [comment]
> This server could not prove that it is modernpgp.org; its security certificate is from *.github.com. 

Sigh.

**Comment by ge-fa** [comment]
This gets more and more widespread use, Enigmail does ship it now enabled by default.

**Comment by Valodim** [comment]
I'm currently focusing to get Autocrypt support done. I might add simple support for encrypted subjects, though. It's not super high priority though.

**Comment by rugk** [comment]
BTW Memoryhole is also supported in Enigmail AFAIK since one or a few version(s).

**Comment by cketti** [comment]
See #3309
