### ISSUE TITLE
Failed to send some messages ; Negative SMTP reply: 501

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#2285]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

This issue has been discussed several times though not necessarily recently nor in a way to solve my particular  issue.

### Expected behavior
email should be sent

### Actual behavior
cannot send email.   when trying to send an email, this error comes up Failed to send some messages ; Negative SMTP reply: 501; sometimes with an invalid email address and sometimes with a syntax error.  I have several email accounts and it happens now on two of them only.  I send to the exact same email address, from contacts in all cases. so i cannot be typing the email address wrong.

### Steps to reproduce
1.click new email, enter recipient first few letters then select name (from contacts list)  Also tried manually typing in address not in contacts list 
2.provide a subject, some text
3.send - then error and message is moved to drafts folder.  Outbox

### Environment
K-9 Mail version:5.203

Android version:6

Account type (IMAP, POP3, WebDAV/Exchange):imap

**Comment by dabear2** [comment]
Additional information.  I was probably using BCC addresses and no TO and no CC.  when it first started - not 100% certain.  Also, when I try to send now, is says  Sending 0/2.   even though I am only sending one.  Based upon some of the other threads on this I've read, something is stuck in the "out" but the outbox is empty and I don't know what or where else to clear it from.

**Comment by cketti** [comment]
Please record a debug log while trying to send a message. https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by fobo66** [comment]
Probably, this issue can be closed, as no debug log was provided. I've tried to reproduce it on newer k-9 version (5.403), and email is actually sent.
