### ISSUE TITLE
Feature Request: Connect through orbot / tor

### ISSUE THREAD

**Issue by kittenpirate** [k9mail/k-9#2308]
There should be a toggle switch to use k-9 through orbot. When disable my cellular connection and setup the manual proxy settings of my wifi connection to localhost and port 8118, k-9 still refuses to connect through orbot. This feature would make k-9 a much better choice for secure email connections that use .onion server addresses such as riseup.net. 

### Environment
K-9 Mail version: Current

Android version: 7.1

Account type:  POP3

**Comment by cketti** [comment]
See #980

**Comment by mirsamantajbakhsh** [comment]
Check out my commit.

Socks proxy added.
#3889 

Read more at:
https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/
