### ISSUE TITLE
Replace instances of new Date().getTime() with System.currentTimeMillis()

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2316]
What the title says. `new Date().getTime()` is just a complicated way of using `System.currentTimeMillis()`.

**Comment by hardik1997** [comment]
I want to work on this issue.

**Comment by montimaj** [comment]
Shouldn't new Date().getTime() be replaced by SystemClock.elapsedRealTime() as in https://github.com/k9mail/k-9/issues/2318?

**Comment by cketti** [comment]
@montimaj: No, please read e.g. the `SystemClock` documentation to learn why they are different. Then you have to consider the context of the code to decide when to use one over the other.
