### ISSUE TITLE
Use SystemClock.elapsedRealtime() to measure durations

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2318]
There are a couple of places where we measure the duration of an operation. In those cases we should use `SystemClock.elapsedRealtime()` rather than `System.currentTimeMillis()` to get accurate numbers.

**Comment by hardik1997** [comment]
I would like to work on this issue.

**Comment by ployt0** [comment]
Only 9 minutes ago! Where was I this evening?

**Comment by PokerFace8** [comment]
I have issued PR #2324  which replaces instances of New Date().getTime() with System.currentTimeMillis() . If that is merged onto master, then maybe we could work with this one?

**Comment by philipwhiuk** [comment]
This isn't a just find and replace request folks. Many usages of currentTimeMillis are valid. We're only talking about code that is using it for elapsed duration - time between two events. Not occasions where we need an actual date time to be stored.

**Comment by bilaltashfeen** [comment]
what are the two events for which we are measureing the time duration?

**Comment by vatsalsura** [comment]
I think I understood the problem. We have to replace all the instances of System.currentTimeMillis() which measure time duration between two events with SystemClock.elapsedRealTime(), but not the one's which require current time for storage and notifications. If I am correct can I work on this issue?

**Comment by cketti** [comment]
@vatsalsura: There's already an open pull request for this that looks like it gets the job done.

**Comment by asifali1234** [comment]
Is this issue still open. If it is I would like to contribute. 
Thank you.

**Comment by divsidhu-26** [comment]
@cketti you have mentioned in the pull request that it does not exactly fulfill the task so does that make this issue open?
I had like to contribute in case it is.....
Thank You

**Comment by vatsalsura** [comment]
@Valodim @cketti @philipwhiuk Please review PR #2389

**Comment by nik1010** [comment]
can i submit still ???

**Comment by vatsalsura** [comment]
@nik1010 A pull request is already open #2389

**Comment by Jagruti1010** [comment]
@Valodim @cketti @philipwhiuk  Please review PR #2412

**Comment by Jagruti1010** [comment]
what does The Travis CI build failed means @philipwhiuk @cketti @vatsalsura

**Comment by cketti** [comment]
@Jagruti1010: The labels and comments should make it clear enough that this issue is already being worked on. Problems related to a pull request should be discussed there, not in the issue it is trying to fix.

**Comment by Jagruti1010** [comment]
Please review PR #2415

**Comment by vatsalsura** [comment]
@cketti Time to close this issue now.
