### ISSUE TITLE
Add support for X-Priority header

### ISSUE THREAD

**Issue by bilaltashfeen** [k9mail/k-9#2329]
Hi

this is only a feature request, not an issue.

There could be an alert generation. its like if when sender send mail from k-9mail. if thats an important email. so sender may mark it important. This mark activate the alert on the recipent screen. its like recipent may recive the mail but didn't check it. so alert generate after 5 seconds.this alert tells the recipent that there is an important email. you have to seen it. that might be an interesting thing.

K-9 Mail version: 5.010

Android version: Kitkat api 15+ 

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thanks.

Bilal

**Comment by philipwhiuk** [comment]
Microsoft Outlook has had this feature for years: https://support.office.com/en-gb/article/Mark-an-email-message-as-important-private-or-sensitive-f480dcea-59a9-48da-b7ed-3b3e0ab27a62

I presume it uses flags. There's an issue for supporting custom flags already. This will relate to that.

**Comment by cketti** [comment]
We certainly don't want that the sender of an email can instruct the recipient's client to generate an alert/notification. That'll be abused by spammers which in turn makes it useless for everyone else.

We could, however, display a visual indicator for "important" messages.
Looks like the `X-Priority` header is used for this.

**Comment by Valodim** [comment]
I would still be weary of this, it might turn out to be a [misfeature](http://blog.alex.org.uk/2013/06/10/rant-why-your-email-is-not-high-priority-after-all/). Then again, it seems fine in outlook so why not. A simple red exclamation point in front of the subject would probably be enough of an indicator.

Step 1: Include a flag in the database about this property. That should be easy to do.

**Comment by riuscita** [comment]
Hello! I am new to the open source community (applying for GSoC). I would like to work on this enhancement. Would that be alright? I agree with Valodim. After the mail is marked as important , indicating it with red exclamation will on recipients subject will nicer. 
I am working now in including a flag in the database.

**Comment by NGimhana** [comment]
Hello! I am new to the open source community (applying for GSoC). I would like to work on this enhancement. Would that be alright? I agree with Valodim. After the mail is marked as important , indicating it with red exclamation will on recipients subject will nicer.
I am working now in including a flag in the database.

**Comment by Subhankar29** [comment]
@cketti Can I claim this issue. I was looking an issue to claim and I think this issue is what I really want to work.

**Comment by NGimhana** [comment]
I am currently working on it @Subhankar29

**Comment by punkstorm28** [comment]
Hi,
I have implemented the feature and sent a pull request,
Please let me know if I could upon improve it.
Thank you.

**Comment by theGeekyLad** [comment]
I'd like to work on this. Kindly let me know if I may proceed!

**Comment by philipwhiuk** [comment]
There's already a PR in progress.

**Comment by philipwhiuk** [comment]
Might as well close this as @cketti rejected the functionality which I completed in #2728
