### ISSUE TITLE
No user detail

### ISSUE THREAD

**Issue by bilaltashfeen** [k9mail/k-9#2333]
No proper user profile is here. just sending and recieveing the mails is the main priority.
No proper user interface attraction
### Expected behavior
Proper user detail with profile picture and username and other details that are necessary

### Actual behavior
no detail just give email and password. and with extra difficult things. that a simple non technical user may not understand the things.

### Steps to reproduce
1.creating user profile class which shows at first in the start where user put his/her details.
2.changeing the layouts design and color. focusing the font size.
3.system decide which port is suitable for sending the mail.

### Environment
K-9 Mail version: 5.0.10

Android version: kitkat api level 15 or further

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Sorry, I don't understand what you're trying to tell us.
