### ISSUE TITLE
Support SMTP Pipelining

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2338]
RFC 2920 - SMTP Pipelining

Many email servers (e.g. gmail, Live) etc support SMTP command pipelining. This allows for optimisation of SMTP network traffic

### Expected behaviour

We should change the behaviour of `sendMessageTo` to use pipelining to reduce round-trip-delay when we receive the PIPELINING extension.

### Actual behaviour

Regardless of PIPELINING extension status we always wait for each response

### Developer notes

The hard part here will be implementing SMTP command handle for asynchronous responses. Likely a queue of outstanding responses will need to be maintained.

There's ample opportunity for testing here - the SmtpTransportTest code allows you to provide dummy responses from an SMTP Server. There should be tests written for:

* Using pipelining when it is enabled
* Ensuring pipelining is not tried when it is not enabled
* Ensuring that we wait for all responses to pipelined operations before considering the message sent
* Ensuring that we handle failures to one or more pipelined operations properly (and still read the remaining pipeline responses)

The RFC contains examples for much of these: https://tools.ietf.org/html/rfc2920

### Steps to reproduce
1. Enable verbose logging
2. Send an email to Gmail or another server that supports PIPELINING
3. Analyse the traffic

**Comment by rhari991** [comment]
@philipwhiuk Are you working on this ?

**Comment by philipwhiuk** [comment]
Nope. It's reasonably complex though as the SMTP architecture right now is very synchronous.
