### ISSUE TITLE
Support SMTP ENHANCEDSTATUSCODES

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2339]
The error messages we get back from SMTP are often hard for a user to interpret and analyse.

Gmail (potentially other providers too) supports RFC 2034 which provides enhanced status codes (defined in RFC 1893)

K-9 should detect this extension and better parse the error messages it gets as a result. 

This issue can just be about handling the extension codes and better managing the structured data we send back to the front-end in an exception.

Making better use of that data is a separate issue (likely in concert with the Design Overhaul).

In all likelyhood this probably means converting:

`535-5.7.1 Username and Password not accepted. Learn more at`
`535 5.7.1 http://support.google.com/mail/bin/answer.py?answer=14257 hx9sm5317360pbc.68`

    new SmtpFailureException(
          ResponseType.PermanentFailure,
          SubResponseType.SecurityOrPolicy, 
          Outcome.DeliveryNotAuthorized,
          "Username and Password not accepted. Learn more at http://support.google.com/mail/bin/answer.py?answer=14257 hx9sm5317360pbc.68")

The outcome of this individual issue will be the user seeing the proper message:

> Username and Password not accepted. Learn more at http://support.google.com/mail/bin/answer.py?answer=14257 hx9sm5317360pbc.68

Then a future issue can use the ResponseType structured data to display better notifications.

It should be fairly easy to test this given the existing test harness set up for `SmtpTransport`

**Comment by Valodim** [comment]
This is done with #2344, right?

**Comment by philipwhiuk** [comment]
Yep.
