### ISSUE TITLE
https://k9mail.github.io/documentation/settings/account_settings.html is 404, missing.

### ISSUE THREAD

**Issue by Techwolf** [k9mail/k-9#2341]
The docs is missing https://k9mail.github.io/documentation/settings/account_settings.html is 404, missing. The server is returning a 404 error.

**Comment by philipwhiuk** [comment]
The correct link is: https://k9mail.github.io/documentation/settings/account.html

I've changed all the broken links on the website pointing to the old page. (https://github.com/k9mail/k9mail.github.io/commit/54f9e4f47eb7871764dc8d56c1910445e2baa9d5 et al)
