### ISSUE TITLE
Cannot decrypt initial email 

### ISSUE THREAD

**Issue by scrfix** [k9mail/k-9#2349]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K9 should decrypt email 

### Actual behavior
When I open this person's email open keychain opens, asks me for my password but the email is not decrypted. 

I have open keychain installed and selected as cryptography. This had been working up until I updated to 5.203.  If he  seems me a reply chain then when it is in part of a conversation it will decrypt but it will give me a red lock with 3 red dots.  I saw comments in another bug report from a month ago where someone else had this same issue. https://github.com/k9mail/k-9/issues/2147
The comment by richfirst sounds like what is happening to me. 

### Steps to reproduce
1. Someone seems an encrypted email 
2. Open email 
3. Enter password for open keychain 
4. No decryption 

### Environment
K-9 Mail version: 5.203

Android version: 
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
Pop account

**Comment by Valodim** [comment]
You'll need to be more precise for its to figure out the problem here. It's there an error message?

**Comment by scrfix** [comment]
There is no error message.  Is it advised to load screenshots and share them say, through Google Drive or Imgur?  If there is no safety risk there I will photoshop them so any sensitive data is removed (email address, etc) and then upload them so you can see what I am talking about.

Just to be more precise, for the last 6 months I have used K-9 with OpenKeyChain and it has worked perfectly.  I updated to 5.203 and all of a sudden for 1 individual; Nali Ahmed, I can no longer decrypt his initial email through K-9.  If we send an email chain back and forth (reply, reply, reply) then it will decrypt his subsequent emails but give me the red lock with 3 dots.

Here is the email I wrote to the openkeychain mailing list that I have not received a reply on yet.  However, I believe this to be a K-9 issue because I can decrypt the email if I copy and paste the encryption to openkeychain.

Hello,

This is my first time using a mailing list. I can send screen shots of everything if you would like. (Not sure if a mailing list can handle attachments) I know a little bit about encryption but I am no expert.  I would still classify myself as a beginner so please keep any answers non-technical and explain in detail.

1. I have an android phone with openkeychain K-9 email installed.
2. In K-9 email I have openkeychain selected as the OpenPGP app in the Cryptography option 3. In openkeychain I have my contact selected with his key confirmed.  It says Linked System Contact as well.
4. This particular contact has multiple keys.  I have the correct key installed.

The issue:
When I open up his initial email in K-9, OpenKeyChain comes up like it's supposed to and asks me to put my password in.  I do this.  It acts like it is decrypting the email however the email is not decrypted. The lock is gray and there are no 3 dots next to the lock.  I can copy and paste the encryption to the openkeychain app and it will decrypt it and I can then read it.  This is a pain in the ass.

Subsequently, if I write him an email and then he replies back to me the decryption process works.  However, the lock is red and the 3 dots next to the lock are red.  When I tap on the red lock it says, the email was encrypted but not signed. There is no signature, this message may have been intercepted.

When I write him an email it automatically shows a green lock in K-9 with 3 green dots next to the lock and he can successfully decrypt the email without an issue.

Troubleshooting Steps:
I have uninstalled, reinstalled both K-9 and OpenKeychain.  I have deleted his key and re-imported his key and verified that I have the correct key.
I have linked up his contact in OpenKeychain to ensure that his key is correctly connected to my contact in my contact list.
Decrypting his emails on my computer works perfectly.  It is only using the K-9 app and the openkeychain to decrypt his emails that doesn't work properly.
I was able to decrypt his email for the last 6 months and then all of a sudden I wasn't able to decrypt his emails any further from my phone after I updated to 5.203.

I don't understand what is happening nor how to correct this issue.  I hope that someone reads this and can assist.

Thanks,

Wayne Leiser, I.T. Director
B2B I.T. Solutions
941-923-6280
www.b2b-its.com
M – F: 9am – 5pm EST

**Comment by scrfix** [comment]
No other suggestions, replies or answers?

**Comment by Valodim** [comment]
Hi, sorry for the late reply. When the mail isn't decrypted, I'm assuming what is displayed is something like "BEGIN PGP ENCRYPTED MESSAGE ..."?

This seems to be an issue of an encryption format we don't handle correctly. Can you ask the person whose mails are affected in this way to send an email to me? -> `look@my.amazin.horse`, pgp `0xdeadfa11`. that would be super helpful.

**Comment by Valodim** [comment]
Closing due to age and missing input. Please reopen if the issue persists.

**Comment by scrfix** [comment]
Never even seen you write back. I gave up and went to Mail Droid instead.  I haven't utilized the encryption feature yet on this but it does support it.


Wayne


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
