### ISSUE TITLE
Alternative dark theme

### ISSUE THREAD

**Issue by antigonos44** [k9mail/k-9#2353]
Currently the dark theme uses a Holo grey gradient as a background.

 It would be great for an amoled friendlier option with a true black background to be available

**Comment by Midhun07** [comment]
I would like to work on this topic.

**Comment by philipwhiuk** [comment]
Introducing a new theme makes for a lot more manual testing. Given that we are trying to move towards Material design which will involve re-doing the themes substantially I think it's not worth the effort of adding a new 'Night' theme at this point.

**Comment by juliakorbut** [comment]
Hey! This, along with a bunch of other items, was solved in the redesign posted recently:
https://github.com/k9mail/k-9-design

Specifically here: https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Account%20Colors%20and%20Themes.png

**Comment by juliakorbut** [comment]
@antigonos44 @philipwhiuk 

Hey! This was a pretty popular request in the [K-9 user study](https://uxquestionnaire.typeform.com/to/SHacN5/). A dark theme, along with a bunch of other items, was included in the new K-9 design repo:
https://github.com/k9mail/k-9-design

You can see all colorways, in both light and dark theme, here: https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Account%20Colors%20and%20Themes.png

**Comment by philipwhiuk** [comment]
From your concepts it looks like you still have two themes. I don't have an issue with the current Dark theme becoming a properly black theme in the re-design.

**Comment by juliakorbut** [comment]
There's a dark theme and a light theme, and then a color you could assign per account. So if you have the dark theme and a red colored account, you'd see a dark+red look for that account!

**Comment by AllanWang** [comment]
Since the Material overhaul is bound to happen, adding attribute color customization will be arduous but relatively straightforward. I'm a themer who's come here from Google's SoC and this sounds like an interesting topic to take on.

**Comment by juliakorbut** [comment]
@AllanWang If you'd like to take a look or contribute more themes, the Sketch files can be found here: https://github.com/k9mail/k-9-design

**Comment by AllanWang** [comment]
@juliakorbut yes I saw the design repo. Adding more themes color wise shouldn't be a big issue now. If you are interested in a mock up build that brings some of those designs to life, I'd be interested in that

**Comment by juliakorbut** [comment]
@AllanWang Feel free to just open the design files and tinker with them! I'd be interested in any contribution or vision you might have.

**Comment by ChildishGiant** [comment]
https://github.com/k9mail/k-9-design is down. Also is there any update on the move towards material design?

**Comment by cketti** [comment]
Continued as #4318
