### ISSUE TITLE
Double tap back button to exit from application

### ISSUE THREAD

**Issue by vatsalsura** [k9mail/k-9#2358]
It is a very common feature in many applications that when a user taps back button to exit, a Toast comes up with a message similar to "Please tap back again to exit". It is a feature request and I don't see a downside on adding this to the k9mail. Instead if the user tapped the back button by mistake, the user will have a second chance to really exit the application.

### Expected behavior
When user taps back button to exit from application a Toast comes up with a message "Please tap back again to exit"

### Actual behavior
When user taps the back button the from Messages page (and other pages which will exit the application), the application exits.

**Comment by philipwhiuk** [comment]
I find this very annoying in apps. It's not about improving the user experience on any of these apps. It's about keeping you in the app and stopping you efficiently use your phone.

If you lost data when you exited the app that would be different. But (except for bugs) you don't.

This would have to be an option and I'd rather it defaulted to being disabled.

**Comment by cketti** [comment]
Maybe common, but not a platform recommendation.
The cost of restarting the app after "accidentally" exiting is not high. So I don't see a reason to implement this.
