### ISSUE TITLE
FR: Share only email title date from

### ISSUE THREAD

**Issue by gerroon** [k9mail/k-9#2359]
Hi

I use email sharing (passing content to othr apps) with other apps alot but one issue I have is that it shares the whole body of email and if the whole body is a long email then it is a mess given that it also shares the html code. For instance I share an email to my tasks apps to keep track of it and in most cases the title and the date of email etc is enough information for such tasks. And given that most apps wont be able to render html inside the whole email body looks like a mess in the apps. 

My feature request is for having one more share item where it says "share basic" and the other would be "share all/advanced" this way the user can decide what kind of email content he wants to share with other apps.

Or the other solution would be some kind of settings that dictaces how much info should be passed to the other apps. 

One solution would be to not to send any html and makse sure only rendered text passed along, if none of the ideas above is implementable.

thanks

**Comment by cketti** [comment]
I'd rather not add complexity to the share feature. You could write an app that acts as a share target, strips everything from the text that you don't want, then re-shares (maybe directly to the note taking app).

**Comment by gerroon** [comment]
I am not a dev so I cant do that but thanks for the follow up.

**Comment by Mvishnu9** [comment]
@gerroon It might be better to switch to a tasks app that automatically converts emails forwarded to a designated email address into tasks in that app (with the subject line of an email becoming the task name, the body of the email becoming task notes and even the attachments of the email become task attachments). 
http://www.makeuseof.com/tag/9-instant-ways-turn-emails-tasks/
