### ISSUE TITLE
failed to send some messages: SocketException

### ISSUE THREAD

**Issue by chadwickblane** [k9mail/k-9#2363]
I could not sort out how to search issues on mobile.  

### Expected behavior
check and send email

### Actual behavior
works once then always a socket exception error

### Steps to reproduce
1. k9
2. 2 circle button
3. wait

### Environment
K-9 Mail version: 5.205

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): tls/ssl, imap

Both imaps accounts live on DreamHost.com 

I do not use android sync, nor do i autopoll folders.  I am starting to wonder if i should find a [new] vps dedicated to email. I am so done with "free" webmail

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
