### ISSUE TITLE
Unexpected behavior while navigating from Folders activity to Accounts activity

### ISSUE THREAD

**Issue by vatsalsura** [k9mail/k-9#2365]
While navigating from the Folders activity to the Accounts activity, if we use the button provided on the top-left corner to navigate through the folders activity to accounts activity it will work as expected. But here's the catch. It won't navigate to the accounts activity on tapping the back button of your smartphone. It will kill the application. The back button unexpected behavior happens only when tapping it first before going to Accounts activity. Detailed steps to reproduce this are given below.

### Expected behavior
On tapping back button for first time also it should navigate to the Accounts activity.

### Actual behavior
On tapping back button of your smartphone before using the on screen button provided in the application, it will close the application.

### Steps to reproduce
1. Launch the application and goto folders page.
![Folders activity](https://cloud.githubusercontent.com/assets/10852939/23765194/685b8e62-0526-11e7-9d68-1e303636146a.png)
2. Tap the back button of your smartphone and it will close the application.
3. Now relaunch the application and again follow the step-1 and this time instead press the back button provided on the top-left corner of the screen(Left side of Folders) to goto Accounts activity.
![Accounts activity](https://cloud.githubusercontent.com/assets/10852939/23765248/952c877a-0526-11e7-84da-12f7c185911b.png)
4. Now click on the account and get back to Inbox activity.
![Inbox](https://cloud.githubusercontent.com/assets/10852939/23765275/add4ee7a-0526-11e7-9491-c74bda6c2748.png)
5. Now again follow step 1-2. This time on tapping the back button of your smartphone you will be redirected to the Accounts activity instead of closing the application.
6. Now you can tap back button or click on provided button any number of times from Folders activity, it won't kill the application. Now close the application and relaunch again and tapping back button will close the application again. But if you follow steps 1-3-4 first then this won't happen.

### Environment
K-9 Mail version: 5.115

Android version: 5.1.1

**Comment by vatsalsura** [comment]
@philipwhiuk @cketti Can I send a PR for this issue as I have already solved this issue?

**Comment by cketti** [comment]
This may be unexpected, but it's not a bug. The back button goes to the previously displayed screen, the up button (top left corner of the screen) navigates up in the navigation hierarchy.
This will change during the design overhaul, precisely because it's confusing.

**Comment by vatsalsura** [comment]
@cketti then why close the issue? Why not add Design Overhaul milestone to it?

**Comment by cketti** [comment]
We will change the navigation hierarchy of the app so this will no longer be an issue. Not implement the change you suggested.
