### ISSUE TITLE
Avoiding editText getting focus automatically when AccountSetupIncoming and AccountSetupOutgoing activities start

### ISSUE THREAD

**Issue by karsai1993** [k9mail/k-9#2367]
Expected behavior:
The activities start without focus on editText. The user is capable of deciding on which editText he/she would like to modify so there is a need any editText to get focus automatically.

Actual behavior:
When the activities start, the first focuable editText gets the focus automatically. The related editTexts are the followings (in case of all acount types): mServerView(id: account_server), mPortView(id: account_port), mUsernameView(id: account_username), mPasswordView(id: account_password). In case of WebDAV/Exchange account type, there are additional ones (occuring in AccountSetupIncoming): mWebdavPathPrefixView (id: webdav_path_prefix), mWebdavAuthPathView(id: webdav_auth_path), mWebdavMailboxPathView(id: webdav_mailbox_path).

Steps to reproduce
1. Start the setup wizard
2. Reach AccountSetupIncoming and/or AccountSetupOutgoing activities 

Environment:
K-9 Mail version: 5.115

Android version: all

Account type (IMAP, POP3, WebDAV/Exchange): all

**Comment by cketti** [comment]
The current behavior is the platform default. Changing it in the way you suggested makes us needlessly different from other apps. It probably also makes the app much harder or even impossible to use with accessibility services.

So we're not going to change this.

**Comment by karsai1993** [comment]
I understand. In my pull request(#2368), there is solution of another issue(#2373). Should I delete the changes for this issue(#2367) and commit only the changes related to that issue(#2373)?
