### ISSUE TITLE
Handling editText hint text in AccountSetupNames activity

### ISSUE THREAD

**Issue by karsai1993** [k9mail/k-9#2373]
Expected behavior:
The hint text information should be readable in case of both mName and mDescription editTexts in landscape and portrait mode, too.

Actual behavior:
In portrait mode, some character of the hint text cannot be shown in case of both mName and mDescription editTexts because it is too long.

Solution idea:
In case of mName, the hint text would be Give the account a name... and the text which is in the brackets (optional) would be the text of a TextView right below the mName EditText. The mDescription EditText would be implemented according to the same logic.

Steps to reproduce
1. Start the setup wizard
2. Reach AccountSetupNames activity

Environment:
K-9 Mail version: 5.115

Android version: all

Account type (IMAP, POP3, WebDAV/Exchange): all

**Comment by rijuldhir** [comment]
If this issue is still open. I would like to work on it

**Comment by karsai1993** [comment]
I have already solved it, now I am waiting for an answer from an administrator if it is worth being merged into k-9 master. After it I can modify the pull request (#2368) containing my solution for this issue. Modification is required because two issue solution are involved and the other one is closed because there is no need for that.

**Comment by cketti** [comment]
We'll change the UI as part of #1818. I don't see a reason to change this minor thing now.
