### ISSUE TITLE
Upload emails back to empty server

### ISSUE THREAD

**Issue by Alukardd** [k9mail/k-9#2374]
Hello.

Is there way to upload all messages from K9-Mail 5.203 back to new empty IMAP server?
I lost my IMAP server managed by Dovecot and now left only one copy of all my email — K9-Mail.

I checked flag not to delete local message deleted on server.
I create new folder called BACKUP. And tried to copy(move tried too) message from Inbox to BACKUP folder, but K9-Mail doesn't upload it to server as I expected it.

I'm very want to restore all this messages on server.

Thanks.

p.s. I had some idea to write X_REMOTE_COPY_STARTED flag to ALL messages in my .db and restart K9-Mail (I have root on my phone), but I see that 4 messages in my DB already has this flag but they weren't uploaded to server.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by Alukardd** [comment]
https://groups.google.com/d/msg/k-9-mail/xjNz0PXZfD8/k4DFkxbrCgAJ
