### ISSUE TITLE
Non technical person can't create his/her account

### ISSUE THREAD

**Issue by bilaltashfeen** [k9mail/k-9#2378]
for setting up new account pre req is there should be my account at gmail or ymail or any mail. than that account should link with k-9 mail. the mails that i send from k-9mail are secured.
Let me suppose that i am a person having not enough knowledge about tech things than how i know what type of account i have? is it IMAP or POP3 or WebDAV.
### Expected behavior
when user signup it should signup no details required where his/her account is IMAP POP3 or WebDAV. 
### Actual behavior
If i put my email address and password and try to registered my account not registered even my address and password is correct. than i should enter manual settings. and where i found three types. i don't know what was my account type.?

### Environment
K-9 Mail version: 5.115

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): all

**Comment by cketti** [comment]
See #865
