### ISSUE TITLE
No popup and Confirmation while Deleting, Spam any Email

### ISSUE THREAD

**Issue by meghalagrawal** [k9mail/k-9#2384]
### Expected behavior
When deleting an Email either from list or from inside an Email there should be a popup saying are you sure you want to Delete the Email ??
Asking Delete or Cancle to User will reduce chances of Accidental Deletion of Email.

### Actual behavior
When we are deleting an Email its not asking for Confirmation and its deleting it directly.

### Steps to reproduce

1.Need to check why ConfirmationDialogFragment is not being shown while deleting.
2. Fix the issue that is causing it as its not even shown while moving to Spam.

### Environment
K-9 Mail version:
5.203

Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
All

**Comment by meghalagrawal** [comment]
Can you please assign it to me ?

I will do this within 2 days.

**Comment by cketti** [comment]
This can already be enabled via a setting. See https://k9mail.github.io/documentation/settings/global.html#interactionconfirm-actions

**Comment by meghalagrawal** [comment]
By default this setting should be turned on then.

**Comment by cketti** [comment]
I disagree. Confirmation dialogs are quite disruptive. A better solution is to support Undo. And we have an issue for that: #624

**Comment by meghalagrawal** [comment]
Okay Thanks.

Can I work on Issue #624 ?? Can you assign the task to me?
