### ISSUE TITLE
Switch to OkHttp for WebDAV

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2397]
Currently we are using a deprecated form of the Apache HTTP library. In addition to being fairly cumbersome to test it's hard to use and not maintained in Android.

We should switch to using OkHttp for this. It's an Android standard HTTP library and should reduce much of the work we currently have to do ourselves.

In order to replace it you will need to test the code against a WebDAV server (ideally Exchange) - the unit tests passing is not sufficient for this size of change (and we don't have any true HTTP-based end-to-end tests in the same way we have for IMAP).

**Comment by rhari991** [comment]
I'd like to work on this.

**Comment by cketti** [comment]
We can use [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) to write tests for `WebDavStore` before switching to OkHttp.

**Comment by cketti** [comment]
This is no longer necessary. See #4251.
