### ISSUE TITLE
Long titles in settings screen doesn't show completely

### ISSUE THREAD

**Issue by daquexian** [k9mail/k-9#2398]
### Expected behavior
Titles in settings screen shows completely

### Actual behavior
Long titles in settings screen doesn't show completely on my Nexus 5. It may confuse users.
![photo6219621937991231426](https://cloud.githubusercontent.com/assets/11607199/24025738/5fed31d6-0a8a-11e7-9b09-140cf19e3055.jpg)

### Steps to reproduce
1. Go to Settings -> Global settings -> Privaxy
2. Notice that long titles don't show completely

### Environment
K-9 Mail version: 5.203

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Fixed in #2400
