### ISSUE TITLE
[RFH] INBOX Message filters

### ISSUE THREAD

**Issue by alexander-alzate** [k9mail/k-9#2401]
It would be great to have message filters which perform some basic actions on messages after being synced from the server. 

I use to redirect (move) messages to different folders based on the subject, the sender, the mailing list, etc. In *GNOME Evolution* actions like deleting, flagging, tagging should be performed to.

**Comment by philipwhiuk** [comment]
Duplicate of #1763 

We don't write that boilerplate you deleted for fun. Search first.
