### ISSUE TITLE
Mark IMAP messages as "cache"

### ISSUE THREAD

**Issue by ildar** [k9mail/k-9#2402]
For the right backup.

**Comment by philipwhiuk** [comment]
Can you please describe this in more detail.

**Comment by ildar** [comment]
Usually backup apps skip the app data marked as "cache".
Also a user may want to drop (some|all) messages to free up some space (as
those are on the IMAP server anyway).
I think K-9 IMAP messages are quite close to "cache" term. What do you
think?

**Comment by philipwhiuk** [comment]
We store emails in a database, not in files, so there's no way to switch to use the cache.

We don't store every email anyway and this is all customisable on a per account basis. You can also configure accounts not to delete server emails if you delete the one on the client.

So there's nothing really to do here.
