### ISSUE TITLE
Highlight account you are browsing

### ISSUE THREAD

**Issue by ANDREW007CZ** [k9mail/k-9#2408]
### Expected behavior
Very grounding thing: To see email adress you are seeing (in folders view or inbox)!! There is only color distinction what makes it hard if you have 5+ email accounts to recognise and remember.

### Actual behavior
You open inbox and dont see what you opened..

### Environment
K-9 Mail version: 5.203

Android version: 4.2.1 (tablet)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
This makes sense. I think the main reason it's not been done already is we've not done much testing and design work for tablets. Feel free to suggest other tablet related improvements :)

**Comment by PokerFace8** [comment]
@philipwhiuk We can already see the (optional) account name in the inbox and folders. I checked for  the given android version and the given K-9 mail version and the name of the account comes up on the top of the activity.
![image](https://cloud.githubusercontent.com/assets/13000443/24885875/96a9b3e6-1e6e-11e7-85e2-ed332a62f908.png)
![image](https://cloud.githubusercontent.com/assets/13000443/24885887/a6e441ea-1e6e-11e7-8d16-b3d513e6ff6b.png)

**Comment by philipwhiuk** [comment]
I mis-read this issue - it's not really related to tablets - you just want the account name somewhere (e.g. Work - Inbox, instead of 'Inbox')
