### ISSUE TITLE
New feature proposal: Home button

### ISSUE THREAD

**Issue by ANDREW007CZ** [k9mail/k-9#2409]
### Expected behavior
Always have a button that returns you to default home screen (where you see your accounts). I mean when you are seeing inbox/sent..whatever, you always can go back just with one-tap button.

### Actual behavior
There is no such button.

### Environment
K-9 Mail version: 5.203

Android version: 4.2.1 (tablet)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by juliakorbut** [comment]
Would this feature still be needed in this case?
https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Entire%20App.png

This is a redesigned version of K-9 with a better interface.

**Comment by philipwhiuk** [comment]
As is, I don't see this as useful. K-9 doesn't really have a Home Screen right now - where the app opens on start is settings dependent. And as @juliakorbut says, long term we want to rework the App so it'll no longer really be relevant.

**Comment by ANDREW007CZ** [comment]
Well, it spare multiple taps you need to do when you want return and choose another email to browse. So I would call it rather useful. So called Homescreen could be the one which opens when apps opens.
