### ISSUE TITLE
Show new mail instead of unread mail (notification)

### ISSUE THREAD

**Issue by ProfPh** [k9mail/k-9#2411]
Hello,

If I have K9mail check for new messages every 60 mins, it comes back every 60 mins saying 100 unread messages. I would have thought the expected/desired behaviour is to say 1 new message (since last sync) or don't notify if 0 new messages since last sync.

Is this an option that I'm not seeing in K9 or is it not a feature?

**Comment by cketti** [comment]
This is not a discussion forum. If you want to report what you believe is a bug please fill in the information we ask for in the issue template.
