### ISSUE TITLE
"Database upgrading" Forever!!!

### ISSUE THREAD

**Issue by zenny** [k9mail/k-9#2416]
The k9mail client does not go beyond "Database upgrading" screen even after a day! This is similar to https://github.com/k9mail/k-9/issues/1947 but still prevalent in v5.205 and also v5.206 after upgrading k9mail from fdroid repo.

### Expected behavior
Should display the email list in the k9mail client

### Actual behavior
After an update of the k9mail client, it stops working with only displaying "Database updating..." forever. Screenshot at http://picpaste.com/geeDAaIT.png

### Steps to reproduce
1. Upgrade to v5.205 or v5.206 of k9mail client from fdroid repo

### Environment
K-9 Mail version: v5.205 and v5.206

Android version:

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
It's a duplicate. We didn't close it because it's not fixed.

Closing this.
