### ISSUE TITLE
Can not place K-9 Mail Unread Widget to the shortcut area of the home screen

### ISSUE THREAD

**Issue by dvschuetz** [k9mail/k-9#2418]
### Expected behavior
The shortcut area should allow the Unread Count Widget (envelope) to be placed there, like it works with the K-9 Mail Widget (dog).

### Actual behavior
The shortcut area does never allow the Unread Count Widget to be placed,

### Steps to reproduce
I tried it two ways:
1. Zoom home screen smaller
2. Choose "widgets"
3. Open the K-9 Mail folder, choose the envelope-widget 
4. Drag it to shortcut area, let it fall
#### Steps to reproduce 2nd option:
After placing the widget on the home screen already:
1. Zoom home screen smaller
2. Choose the widget from home screen
3. Drag it to shortcut area, let it fall

### Environment
K-9 Mail version: 5.203 and 5.206
Samsung Galaxy S5 SM-G900F
Android version: 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange): all IMAP

I have read [Can't place widget on home screen](https://github.com/k9mail/k-9/issues/1051) and [Widget cannot be placed on homescreen in Android 5.1.1](https://github.com/k9mail/k-9/issues/912)

**Comment by cketti** [comment]
That's because it's a widget not a shortcut. Those are different things. Shortcuts are static, widgets support dynamic content.
Not being able to place widgets in all places a shortcut can be used is a limitation of your launcher, not a bug in K-9 Mail.
