### ISSUE TITLE
Vulnerability in securely logging in and Delay In Incoming Messages

### ISSUE THREAD

**Issue by SatyarthV** [k9mail/k-9#2419]
### Expected behavior
Should Have logged in securely ,
Takes forever to connect to server for incoming messages

### Actual behavior
What happens instead - my gmail id tells me someone else is trying to gain access into my access and also when I select the option that "I approve " it tells me that it would leave my account vulnerable .

Inbox displays that there may be up to 25 new messages but none are being showed 

### Steps to reproduce
1. Login in to the app using gmail and then visit your gmail-inbox

1. Logged into the app and went to inbox 
(I am attaching screenshots to show what troubles I have faced)

### Environment
K-9 Mail version:

Android version:6.0.1

Account type : IMAP
![screenshot_2](https://cloud.githubusercontent.com/assets/22681330/24150919/b08d5b64-0e60-11e7-8252-cc8a69835d3d.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/22681330/24150920/b095ba52-0e60-11e7-9609-f0e7a7759d6c.png)

**Comment by philipwhiuk** [comment]
Have you tried using an application specific password as the Google help suggests?

This is all part of Gmail's attempt to detecting people logging into your account from different locations - which is inevitably tripped when you switch networks.

Long term fix is #1295

**Comment by cketti** [comment]
Closing this issue because I don't think it adds anything important compared to the other issues we have for the "Gmail situation"
