### ISSUE TITLE
Attach the Attachment to the top instead to the bottom

### ISSUE THREAD

**Issue by Sommergoldhaehnchen** [k9mail/k-9#2420]
When opening an encrypted mail - don't know whether this is the same behaviour as normal unencrypted mails - the attachment is at the very bottom of the mail. Uncomely in large mails.
Maybe you can put the attachments to the top?

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
See #2067.
