### ISSUE TITLE
Setup process should not continue if authentication fails

### ISSUE THREAD

**Issue by karsai1993** [k9mail/k-9#2424]
**Expected behavior**
The setup process should not be able to be continued if the account authentication fails. As the username of password is not correct, there is no point in perfoming the setup because the account would not be working.

**Actual behavior**
The setup process can be made to continue if the authentication fails.

**Steps to reproduce**
1. Start to create a new account
2. Type wrong username or password
3. Click next
4. Choose POP3
5. Click next

**Environment**
K-9 Mail version: 5.115

Android version: all

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Screenshot**
![1](https://cloud.githubusercontent.com/assets/15123875/24224658/971d4836-0f5c-11e7-962b-12011a40bc23.png)

**Comment by karsai1993** [comment]
The button of "Tovább" (it means: Continue) should be disabled when the authentication fails to force the user to modify her/his settings. I would like to work on it.

**Comment by Valodim** [comment]
This whole workflow is likely going to be revamped with the related gsoc task soon, I don't think there is much point to changing details like this now.

**Comment by sharad-paghadal** [comment]
I'm having same issue. Please provide resolution step for it.

**Comment by sharad-paghadal** [comment]
@karsai1993  does your issue fix?

**Comment by karsai1993** [comment]
Hi @sharad-paghadal.
I wanted to fix this but @Valodim said that it would be solved in a gsoc task. I do not know if it has really been solved. But based on your comment, it has not.
