### ISSUE TITLE
Request post-auth capabilities if not provided them in the OK AUTH response

### ISSUE THREAD

**Issue by jeLee6gi** [k9mail/k-9#2431]
### Expected behavior
Emails are pushed to my phone, because the IMAP server supports it.

### Actual behavior
Emails aren't pushed to my phone.

When I connect with openssl I see the following:

```
openssl s_client -crlf -connect imap.uni-stuttgart.de:993
* OK [CAPABILITY IMAP4 IMAP4REV1 LITERAL+] perdition ready on mail-proxy.tik.uni-stuttgart.de 00029957
a login ******** *************************
a OK You are so in
a capability
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN XAOL-OPTION NAMESPACE QUOTA IDLE
a OK CAPABILITY Completed
```

The perdition proxy does not announce IDLE, but after login the capability is announced. Does K9 check for capabilites after login?

### Steps to reproduce
1. Add email account from imap.uni-stuttgart.de
2. Don't receive emails via push

### Environment
K-9 Mail version: 5.206
Android version: 7.1.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
No currently we don't.

We currently handle the following:

```
openssl s_client -crlf -connect imap.uni-stuttgart.de:993
* OK [CAPABILITY IMAP4 IMAP4REV1 LITERAL+] perdition r.....
a login ******** *************************
a OK [IMAP4rev1 LITERAL+ CHILDREN XAOL-OPTION NAMESPACE QUOTA IDLE] You are so in
```

but we don't ask for post-auth capabilities specifically.

@cketti do you think we should separate pre and post-auth capabilities and request post-auth if we don't get them in the post-auth OK response?

**Comment by cketti** [comment]
Being spec-compliant sounds good :)
