### ISSUE TITLE
how to change helo

### ISSUE THREAD

**Issue by treakiandroid** [k9mail/k-9#2436]
i dont see why it is nessesary to include the local ip address of my device into an unencrypted mail header that goes around the world while being monitored by all its *** players, its more an security risc then anything good. Think of the dalec who could kill my sweet robot dog just because its (or hes i am not quite sure) sending its exact locations in all messages ;)... So could you add an option to change the string send as helo by k9mail to something else?

tuan

**Comment by cketti** [comment]
Duplicate of #2793
