### ISSUE TITLE
Next-/previous-buttons in E-Mail view no longer work properly (since Update 5.206)

### ISSUE THREAD

**Issue by Hilmic** [k9mail/k-9#2446]
### Expected behavior
K-9 Mail should show the next respectively the previous message if the next-/previous-button in the E-Mail view are pressed (as in the previous versions of K-9 Mail).

### Actual behavior
Since the latest update which has been released a few days ago, the next-/previous-buttons on the bottom in an opened E-Mail stopped working correctly.
For example I've got 3 unread messages as well as 2 already read emails in my inbox listed in this order:

Message #1: Unread
Message #2: Unread
Message #3: Unread
Message #4: Read
Message #5: Read

If I open message #2 and press the "previous" button, K-9 Mail opens E-Mail #4 instead of E-Mail #1.
If I press "next" on message #2, E-Mail #4 is opened instead of E-Mail #3.
In the current version, I have to go back to the overview of all E-Mails and then select the next unread E-Mail manually.
Before the update, I could go through all unread mails comfortably by using the next-/previous-Button.

### Steps to reproduce
1. Mark some E-Mails in your inbox as unread and be sure to have some unread E-Mails.
2. Open up an unread E-Mail and click either the next- or previous-button
3. K-9 Mail jumps to the first already read E-Mail instead of going to the actual next / previous E-Nail.

### Environment
K-9 Mail version:
5.206

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
I believe this is no longer an issue.
