### ISSUE TITLE
Emailing web page doesn't include page title in subject

### ISSUE THREAD

**Issue by Mike20878** [k9mail/k-9#2450]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When I share a web page through K-9 I expect that the subject header will be populated with the page title.  For instance, emailing this page should have a subject of "New Issue - k9mail/k-9."

### Actual behavior
The subject header is blank.

### Steps to reproduce
1. Open web page in Chrome.
2. Share article, select K-9 Mail.
3.

### Environment
K-9 Mail version: 5.206

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
Works for me...

**Comment by huzaifaiftikhar** [comment]
Hi,
I have successfully built K-9 on my local system. 
I would like to work on this issue as a part of "one patch" rule. Can I get any starting pointers ?

**Comment by huzaifaiftikhar** [comment]
Hi,
I have successfully built K-9 on my local system.
I would like to work on this issue as a part of "one patch" rule. Can I get any starting point as a help to fix this?

**Comment by philipwhiuk** [comment]
@huzaifaiftikhar First - have you replicated the bug?

If you can then I would look at whether the subject is getting fetched here: 

https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L527

to start with.

**Comment by huzaifaiftikhar** [comment]
@philipwhiuk The bug isn't replicated. It works for me and the Page Title automatically becomes the subject. I have tested on chrome as well as firefox, hence the subject is being fetched through EXTRA_SUBJECT.
Android : 5.0.2
Chrome : 55.0.2883.91
Firefox : 52.0.2 
K-9 Mail : 5.206

**Comment by cketti** [comment]
Doesn't seem to be a K-9 Mail issue. Issue closed for now.

We'll reopen once specific instructions on how to reproduce the issue are provided.

**Comment by Mike20878** [comment]
I was finally able to reproduce it and isolate the area where it doesn't work.  When I search using the Google search bar and open a page, sharing the page doesn't populate the subject field.  It works from the Chrome browser.
[K-9 Screenshot.pdf](https://github.com/k9mail/k-9/files/886253/K-9.Screenshot.pdf)

**Comment by philipwhiuk** [comment]
I don't think this a bug in K-9.
