### ISSUE TITLE
Update openpgpapi lib

### ISSUE THREAD

**Issue by iminderN** [k9mail/k-9#2452]
The version of openpgpapi is 9, how can I update that to the latest one i.e. 12?

**Comment by philipwhiuk** [comment]
The openpgp-api used by K-9 is embedded as part of a release.

I think updating the version in K-9 will be a case of simply copying across the new code (we don't change it, but we copy it in as it's not currently published in Maven and Git submodules are painful) and then testing various code paths that might have changed.

I would expect/hope that we'll upgrade before we do another release.

cc @Valodim

**Comment by iminderN** [comment]
I brought this up because I noticed when encrypting emails, the pgp block is almost double the block generated when using Openkeychain's encrypt text feature. I am assuming both K9 and Openkeychain use Openpgpapi to encrypt/decrypt data and the PGP block for Openkeychain is smaller because they are using the most recent version of Openpgpapi

**Comment by philipwhiuk** [comment]
Are you compare PGP/MIME to Encrypt Text or PGP/INLINE. 

PGP/MIME encrypts more of the message headers and content type (and more complex emails like HTML emails with plain text alternatives, as well as regular attachments) so will be bigger. K-9 uses PGP/MIME by default.

If the PGP/INLINE looks bigger it's probably an encoding issue.

I don't think the new version is more efficient: https://github.com/open-keychain/openpgp-api/blob/master/CHANGELOG.md

**Comment by iminderN** [comment]
No, I am talking about PGP/INLINE.
