### ISSUE TITLE
Auto Synchronization does not work after phone change with export/import of settings

### ISSUE THREAD

**Issue by freica** [k9mail/k-9#2457]
### Expected behavior
New incomming e-mails should be displayed at the notificationbar of the phone, if K9 is running in Background.

### Actual behavior
New eMails are synchronized only if I start the UI of K9

### Steps to reproduce
I changed my phone from S5 mini (same android version) to Huawei Y 6 II compact. Therefore I made a export of the whole K9 Settings and an import to the new phone.
Since this thime the Problem started. 
All Settings are unchanged, synchronization is still activ.
Manual synchronization is running well.

### Environment
K-9 Mail version: 5.206

Android version: 5.1

Account type (2 different IMAP accounts):

**Comment by philipwhiuk** [comment]
Please provide a debug log

**Comment by freica** [comment]
[k9-log.zip](https://github.com/k9mail/k-9/files/876893/k9-log.zip)
Please see my debug log here.

**Comment by philipwhiuk** [comment]
There's nothing from k9 in those logs - either debug logging wasn't enabled or the log wasn't for the right period. You've closed the issue so I'm assuming it's no longer a problem.

**Comment by freica** [comment]
Sorry, I think I have pressed the wrong button and so closed the issue, but it was not proposed.
I am a windows developer and not very kind with Linux/Android Debugging.
But I enabled the logging at afternoon and captured it at the evening by the commandline
adb logcat -d -v time k9:V '*:S' AndroidRuntime:E > k9-log.txt
What should I do?

**Comment by freica** [comment]
I am also suprised about the running state of K9. I see it in die "Task-Manager", but it's not listed in the "Active-List" of apps, it's also not listed as battery-consumer.

**Comment by freica** [comment]
What can I do to help you find the Problem?

**Comment by FrankEular** [comment]
See https://github.com/k9mail/k-9/wiki/LoggingErrors, Step 1.

German: Einstellungen -> Fehlersuchvorgang -> Fehlersuchprotokollierung akti...

**Comment by freica** [comment]
I found the cause by myself. If the phone uses the EMUI UserInterface (Huawei,...) you have to activate the K9-App manually that it can run, also if the Display is deactivated.
Now the synchronization runs well.
