### ISSUE TITLE
Issue with login in

### ISSUE THREAD

**Issue by MLPJ** [k9mail/k-9#2459]
### Expected behavior
Logging in to the email account

### Actual behavior
Shows a username or password incorrect error
I checked the password for many times. It may be because of spaces in the password too.

### Steps to reproduce
1.Logging to a gmail account with a password with spaces. Through k9

### Environment
K-9 Mail version:

Android version:4.4.2

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
