### ISSUE TITLE
Unable to connect to SMTP-server

### ISSUE THREAD

**Issue by spacebug0** [k9mail/k-9#2461]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K9 should connect to my smtp server

### Actual behavior
K9 says "Unable to connect to server ()"

### Steps to reproduce
1. Make an account with type IMAP
2. Choose SMTP server "smtp.fsdata.se"
3. Choose STARTTLS, port 587, normal login
4. Press Next

### Environment
K-9 Mail version: 5.206

Android version: 6.0.1 (CyanogenMod on Sony Xperia Z5 Compact)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

### Other
The same settings work great in the standard Android app "Mail".

**Comment by philipwhiuk** [comment]
It would be useful to see an Android debug log given there is no helpful error message. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by spacebug0** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/883595/k9-log.txt)

**Comment by philipwhiuk** [comment]
Can you do one while you check the SMTP connection please (Account settings -> Sending email -> Outgoing settings) :)

**Comment by spacebug0** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/883702/k9-log.txt)

Now I think is there

**Comment by philipwhiuk** [comment]
Yep! Thanks. I'll try and fix it :)

**Comment by philipwhiuk** [comment]
I think the reason you can't connect is that your server only supports insecure ciphers which K-9 doesn't support. Testing with `openssl s_client` reveals the best supported option is `RC4-MD5` - which has been removed from browsers for over a year.

We don't get told this - we just get told the server closed the secure connection but the error message could be better.

**Comment by philipwhiuk** [comment]
We don't get told why the connection was closed by other side.

One thing we could do is make another connection with weak SSL certs enabled and if that's accepted inform the user. That's quite a bit of work though.

**Comment by ekke107** [comment]
Here the same issue. Android 7.0; k9-Mail latest version 5.206

The same settings work in AquaMail. They also work in Thunderbird (on my PC)

k9-log.txt shortened:

[k9-log-4.txt](https://github.com/k9mail/k-9/files/913854/k9-log-4.txt)

.

**Comment by spacebug0** [comment]
I have contacted my email provider and they will upgrade the ciphers for their servers.


"openssl s_client -connect smtp.fsdata.se:587 -starttls smtp" shows
SSL-Session:
    Protocol  : TLSv1
    Cipher    : **RC4-MD5**



"openssl s_client -connect smtp.fsdata.se:587 -starttls smtp | openssl x509 -text" shows
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            21:86:b8:03:4b:dc:69:cc:46:4e:dd:26:e0:d8:8f:1e
    Signature Algorithm: **sha1WithRSAEncryption**

**Comment by HeinrichGit** [comment]
Version 5.304

Same problem with the following connection options:

SSL-Session:
    Protocol  : **TLSv1.2**
    Cipher    : **ECDHE-RSA-AES256-GCM-SHA384**
Signature Algorithm: **sha256WithRSAEncryption**

**Comment by cketti** [comment]
We use the TLS implementation of the platform. So for most of these instances there's nothing we can do besides better error messages. For that we have issue #893.

**Comment by HeinrichGit** [comment]
@cketti I didnt understand your answer ... At least it sounds to me, its the mail provider`s fault... But if so, why do other applications are able to connect to this provider w/o problems ?!?

**Comment by spacebug0** [comment]
@HeinrichGit Programs does not have to use the platform TLS implementation. They can use their own (I guess).

Also, not using a good chiper is a bad idea (even tough probably better than using not SSL/TLS at all).

Tell your email provider to upgrade their chifers. I did and they listened to me and fixed it.
