### ISSUE TITLE
inclusion of simple security features

### ISSUE THREAD

**Issue by Biswajee** [k9mail/k-9#2465]
Keeping in view of the interests of the end-users,it would be great to work upon simple tools that would enhance email experience. Like inclusion of a link scanner to scan for potentially harmful links. Another tool will be scanning for malware within archives using signature matching.A string search algorithm may be used to match keywords in mails for unwanted mails (and ask for a permission) before they are opened by end-user. These are simple tools but will be of great help for a better client experience. We may take help from open source antivirus engines such as Clamav to accomplish our task.

### Expected behaviour
Decrease in online frauds.
Decrease in mail bombing like activities and associated attacks by hackers.
Better user experience.

**Comment by philipwhiuk** [comment]
I think this is best covered by #1508
