### ISSUE TITLE
Add option to clear account passwords

### ISSUE THREAD

**Issue by ian-kelling** [k9mail/k-9#2469]
Similar to  #677, but much much simpler. Right now, to clear account passwords, you need to

1. click account settings
2. click fetching mail
3. click incoming server
4. click password field
5. delete all the text
6. input a single random character
7. click next
8. wait for authentication failure
9. click ok
10. click back
11. click sending mail
12. repeat steps 4-10.

...

19. Done!

Instead of all these steps, there should be an account option similar to the existing one "clear messages", which does "clear messages & passwords", or "clear passwords", which mostly just automates the steps above.

This would go a long way toward making it easier to use k9 with greater security like webmail: log in, check mail, log out, now mail is securely not stored or accessible from the device.

**Comment by cketti** [comment]
That's not a use case we want to support. I also closed #677.

**Comment by ian-kelling** [comment]
Fine, but I just want to say why I think it's a good use case: My email is the key to reset the password to every online account I have (banking, etc) and see personal communications going back years. The rest of my phone has some communication & browsing history, for not nearly as far back, thats about it. It's a completely different level of importance, and supporting the ability to use a password for email beyond "type it once and store it forever because it's got a horribly UI for clearing it" seems like an obviously good thing.

Also: https://github.com/k9mail/k-9-design says "It welcomes tinkering, customizing, and adapting the app to anyone’s needs.", this doesn't feel like some completely esoteric thing that "anyone" would never want.

**Comment by ken-bell** [comment]
The request to not store passwords (#677) is something I also want.

Would you please clarify why you don't want to support this very typical use case?

In #677 you wrote: 

> I've since reconsidered and don't think it's worth having this feature anymore. The OS is a far better security boundary than K-9 Mail could ever be. Encrypt your device. Set up a lock screen password. Don't give away your unlocked phone.

You are not considering the case of shoulder-surfing lock screen passwords or of SIM fraud in which someone claims to have lost their phone and demands a new activated SIM with your phone number -- often with some sort of forged photo ID if doing this in-store.

I want to open the mail app, sign in with my password, do what I need to do, and sign out.

Other than the lack of this important option, K-9 is perfect!

Thanks.  - Ken

**Comment by philipwhiuk** [comment]
Not storing passwords is very different from being able to logout. I'm not too opposed personally to a 'logout' function that clears all the account data and disables the account until you login again. It would be like a newly imported account. We can just delete the account preferences and database.

That said, it needs some thought where it would go in the new UI - in the old one we could just add another option to the ugly context menu. I don't want to block the new UI on this kind of feature.

And there's a bunch of testing and edge cases to check.

**Comment by ken-bell** [comment]
Hi Philip,

How about if "logout" simply deleted the stored passwords (without deleting all of the other account information)?  That would go a long way towards securing the account when it's not being used by the authorized owner.

And maybe a configuration option to do this automatically when the app is closed?

Thanks!
Ken

**Comment by philipwhiuk** [comment]
> How about if "logout" simply deleted the stored passwords (without deleting all of the other account information)? That would go a long way towards securing the account when it's not being used by the authorized owner.

We could keep the local content I guess. We'd have to introduce a 'disabled' status for sync - otherwise you'll get lots of 'authentication failure' errors.

> And maybe a configuration option to do this automatically when the app is closed?

Again, not doing this because of what I said above. Android doesn't provide you a guarantee you will get to execute code between your application going into the background and it being killed. So any attempt to do this will either be really overzealous or unreliable.

https://stackoverflow.com/questions/19560171/how-to-call-a-method-when-an-android-app-is-closed-or-loses-focus

It's not trivial whatever you do. And personally I have other stuff to work on for now (Initial work for Subfolders, EWS and IMAP namespaces is my current project). But there is a method that can work

**Comment by ken-bell** [comment]
I see, it looks like the problem with doing something "on exit" is that Android apps don't really have an exit method (which strikes me as a frustrating situation).  Thanks for the link.  - Ken
