### ISSUE TITLE
Add actionbar to Preference Screens

### ISSUE THREAD

**Issue by allepage** [k9mail/k-9#2478]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When we go in the parameter, what ever the correction or change that we made in the setup, we should be able thereafter to go back to the previous screens until we reach our emails.

### Actual behavior
For example, imagine that we select account parameters. From that screen, we have general parameters, emails reading, files, storage and so on.  But we dont have the arrow on the left up conner in order to go back the previous screen.

To exit from this screen i have to restart my cell.  When I select your software, I am back in the email screen.

is it possible to correct this problem

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
In most cases the phone's back button should do what you want. But it should be consistent with other screens anyway..

I don't know how this will work in the Material Design. I'll leave it open for now.

**Comment by allepage** [comment]
You are right!  It should be consistent with the previous screen. So we should have a back arrow on the left corner to go back to the previous screen.
  And yes, I found the back button on my phone and it works.
  Regards,
  
  Alain LePage
  
   ---------- Message d origine ----------
   De : Philip <notifications@github.com>
   Daté : 4 avril 2017 à 03:59
   
   
   In most cases the phone's back button should do what you want. But it should be consistent with other screens anyway..
   I don't know how this will work in the Material Design. I'll leave it open for now.
