### ISSUE TITLE
Unable to connect to smtp server (SSL problem)

### ISSUE THREAD

**Issue by tobycheese** [k9mail/k-9#2488]
K9 is unable to connect to my smtp server:
 - Server runs postfix with an SSL cert from letsencrypt
 - Connection is made over SSL with plain text password via submission port
 - Settings are fine, other MUAs can connect and send mail
 - Imap works, with the same settings (ssl, plaintext password)
 - All I can gather from the log is that the problem is SSL-related, but nothing more that would help

[k9-log.txt](https://github.com/k9mail/k-9/files/907061/k9-log.txt)

K-9 Mail version: 5.206

Android version: 7.0

**Comment by philipwhiuk** [comment]
Try START TLS instead of SSL/TLS

**Comment by tobycheese** [comment]
Thanks, that worked! In retrospect, it's obvious to me that I should have tried STARTTLS, because when I telnet to 587, the server answers with a plaintext response. But how did you know? Did the log tell you? Thanks.

**Comment by ArchangeGabriel** [comment]
Port 587 is for STARTTLS. SSL/TLS, when enabled, is on port 465.

**Comment by philipwhiuk** [comment]
I've seen the error line before when trying with Office 365 ( #1757 ). I assume it's that the response packet on the SMTP port matches a specific Boring SSL protocol error message.
