### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by safetygenie** [k9mail/k-9#2489]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue
Did the update ysterday on my droid. Now k9 doesnt work...i keep getting authentication errors for every accouny. It claims my passwords are invalid. I msde no othet chhanges except updating.

### Expected behavior
Tell us what should happen
It shiuld bloody wrlm WORK when I log in
### Actual behavior
Tell us what happens instead
It dont WORK
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Please use the mailing list if you are not willing to provide reasonable information.
