### ISSUE TITLE
Mark All As Read in Notification

### ISSUE THREAD

**Issue by JimSym** [k9mail/k-9#2491]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Please show Mark All as Read in Notification when there is more than one email

### Actual behavior
Mark as Read has disappeared.  It was present in previous versions/earlier version of Android

### Steps to reproduce
Receive more than one email on an account
View Notification

### Environment
K-9 Mail version: 5.206

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): POP

**Comment by daquexian** [comment]
I think it is limited by Android N :P No way to show a global "Mark All As Read" button in a bundled notification.

**Comment by JimSym** [comment]
OK, thanks.  That’s a shame……………..
