### ISSUE TITLE
Truncated Notification Sound

### ISSUE THREAD

**Issue by jgpa** [k9mail/k-9#2492]
New to nougat, coming from KK S3.

Notification Sound often times is clipped to about 1/4 second. Full notification is close to 1 second.

It does this about 75% of the time.

**Comment by lobstaj** [comment]
I've noticed something which might be related. Our jenkins server sometimes sends me multiple mails virtually at the same time. When I receive such a bunch (quite often 3), my device's screen wakes up, I see the notification, the vibration works, but I don't get any notification sound. This seems to happen only when I receive multiple mails virtually at once. I suspect that receiving the second mail while the first mail's notification has just started cancels the notification sound.

Could it be that you get a copy of the same mail in a different folder and that that clips your notification sound? Does your notification stay there when the sound is clipped?

For me the notification stays there, and the led is blinking correctly, so in my case this is not related to disappearing notifications.

Using Android 7.1.1 btw.

**Comment by cketti** [comment]
Probably an Android bug.
