### ISSUE TITLE
Add proper dir and align attributes when using RTL languages

### ISSUE THREAD

**Issue by sha-265** [k9mail/k-9#2506]
### Expected behavior
When sending an email with RTL languages (Hebrew, Arabic, etc), the dir and text-align HTML attributes should be "right" in the content's element.

### Actual behavior
There is no dir and text-align HTML attributes in the content's element, and the text aligned by the email client default settings. In the composing editor the text appears fine, from right to left, but only on the composer level, and not in the HTML level.

Composing is working as expected in RTL languages:
![screenshot_20170419-193815](https://cloud.githubusercontent.com/assets/4103710/25191681/0f66bb6e-2539-11e7-8fbb-ae9a59b7488a.png)

But when reading content display is wrong:
![screenshot_20170419-194123](https://cloud.githubusercontent.com/assets/4103710/25191819/7bdf1764-2539-11e7-9076-215f5124d642.png)

### Steps to reproduce
1. Compose new email with RTL language content.
2. Send the email.
3. Open the email in any other email client, that the default text alignment and direction is left.

### Environment
K-9 Mail version: 5.207

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by pshem** [comment]
Fennec(Firefox for Android) update log to version 53.0(released today) shows adding support for this. Can MPL-licensed code be merged? This might save work

**Comment by doronbehar** [comment]
Confirmed.

**Comment by iriman** [comment]
Yes, please do a fix for this. I come here to report this and saw that it's already reported.
My language is Persian and have this issue with Persian emails or any other right-to-left language.

**Comment by philipwhiuk** [comment]
I think just adding `dir=auto` to the content should fix this for the common case. I don't think we need to change the text alignment as well (in-fact I think you shouldn't).

**Comment by sha-265** [comment]
@philipwhiuk why not? RTL languages should be aligned to right.

**Comment by philipwhiuk** [comment]
dir=auto will do that on its own. It aligns the characters based on the first dominant character in the content. It's the best you can do for arbitrary text which is what we have to deal with in K-9.

Providing explicit text alignment means having a preference for the user and then all the text that's written in a different language will appear wrong.

See https://www.w3.org/International/questions/qa-html-dir#unknowndirection

**Comment by sha-265** [comment]
You are right. I think some browsers just recently start using auto alignment, when using `dir=auto`. Because I had [some issue](https://github.com/WhisperSystems/Signal-Desktop/pull/846/commits/8d413757fe91893a772edce9257ae1b9fea5b18f#diff-cbe249338c0d2874aa2f71e5335598b8R294) with this not long ago, and I had to add `text-align: -webkit-auto` property to a Chrome app to solve this issue.

**Comment by philipwhiuk** [comment]
I just tested in my browser with `<p dir="auto" style="text-align: $prop;">אבגABC.</p>`.
If you set the text-align (e.g. to `left`) it'll override. Both `start` and `-webkit-auto` work fine. I think I'm happy as is.
