### ISSUE TITLE
Poll doesn't work in the latest version

### ISSUE THREAD

**Issue by FrankEular** [k9mail/k-9#2513]
The poll frequency (of my outlook account, IMAP) is set to "Every 12 hours". It is always shown that "Next poll in 11 hours". This is an issue of latest versions. There weren't similar issues in older versions, but I cannot tell from which version the issue appeared.

I discovered the issue when I access the mailbox and find that the new mails of outlook don't come for a week.
[k9-log.txt](https://github.com/k9mail/k-9/files/962367/k9-log.txt)

### Steps to reproduce
1. Set the poll frequency to be "Every 12 hours";
2. Set background sync to be "Always".
3.

### Environment
K-9 Mail version:
5.207

Android version:
6.0.1 (cm13.0-SNAPSHOT-ZNH5YAO21N)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by AJ1980** [comment]
Same behavior in Meizu M5 with Android 6. Only manual poll is working. Automatic poll every 5-10 min does not work.

**Comment by spuljko** [comment]
Same on Galaxy S5, but only over WiFi. When it connects to edge it works ok. Working ok on Acer tablet in same network.

**Comment by mahibi** [comment]
i had the same issue. Additionally on the main screen there was mistakenly the message that sync was deactivated ("Synchronisation deaktiviert") in case of the minutes to the next poll.
However after changing sync interval from one value to another it suddenly seems to work again now. It shows the time to the next sync and polling works fine.

OneplusOne
Android: 7.1.2 Lineage (14.1-20170724-NIGHTLY-bacon)
Kmail: 5.207
Account Type: IMAP
