### ISSUE TITLE
Unable to re-sync emails modified by other clients.

### ISSUE THREAD

**Issue by ochurlaud** [k9mail/k-9#2522]
When the header X-Bogosity is set (see https://fossies.org/linux/bogofilter/GETTING.STARTED for exemples), the email is not shown by k9mail.

### Expected behavior
That this header is there or not shouldn't change the fact that my email is visible

### Actual behavior
If the header X-Bogosity is set, the mail cannot be seen in the App

### Environment
K-9 Mail version: 5.206

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Can you provide the source of a message that doesn't show up?

**Comment by ochurlaud** [comment]
does the header contain private thing? I'm reluctant to publish it there....

**Comment by ochurlaud** [comment]
after removing on my other client the problematic header on all emails, I could not find them.

After some searching, it seems that the problem is more likely close to the #1642.

My client changed the headers from the newest email to the last one. On K9Mail, the first email retrieved is my oldest. Therefore, I cannot use it to retrieve newer emails as I would need to first synchronize all my emails....

I haven't found a way to change this date (or whatever changed) on the remote server, though it would be great to do so as well..
