### ISSUE TITLE
email removed from server when downloaded on phone

### ISSUE THREAD

**Issue by eliot123** [k9mail/k-9#2525]
### Expected behavior
emails should stay on server

### Actual behavior
they are deleted when I fetch

### Steps to reproduce
1.fetch emails
2.
3.

### Environment
K-9 Mail version: I don't know how to tell

Android version:  6.0

Account type (IMAP, POP3, WebDAV/Exchange):  don't know how to tell

**Comment by 0xf10e** [comment]
You're probably using POP3 then, because that's just how this protocol works.

Open your accounts inbox, go to Settings -> Account Settings -> Fetching mail -> incoming server.
If the first entry is "IMAP server" it's IMAP, for POP3 it's probably "POP3 Server".

I'm not sure how to get your mails back on the 
server from within K9 though…

**Comment by eliot123** [comment]
It is a pop3 server but I don't believe
      that is how the protocol works.  There ought to be an option as
      there is in Outlook.  the default should be to leave the messages
      on the server.  I used to use gmail and I believe that it left
      messages on the server
      
      4. Because
          the Leave a copy of messages on the server
          check box isn't selected in Outlook on your home computer, a
          command is sent from Outlook to the POP3 mail server
          instructing it to delete downloaded messages.
          No other copy of Outlook can download these messages
          from the POP3 mail server.
      Read
          POP3 email messages on multiple computers - Outlook
      
      
      
      On 5/4/2017 3:45 AM, Florian Ermisch wrote:
    
    
      You're probably using POP3 then, because that's just how this
        protocol works.
      Open your accounts inbox, go to Settings -> Account Settings
        -> Fetching mail -> incoming server.
        If the first entry is "IMAP server" it's IMAP, for POP3 it's
        probably "POP3 Server".
      I'm not sure how to get your mails back on the
        server from within K9 though…
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/k9mail/k-9","title":"k9mail/k-9","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/k9mail/k-9"}},"updates":{"snippets":[{"icon":"PERSON","message":"@0xf10e in #2525: You're probably using POP3 then, because that's just how this protocol works.\n\nOpen your accounts inbox, go to Settings -\u003e Account Settings -\u003e Fetching mail -\u003e incoming server.\nIf the first entry is \"IMAP server\" it's IMAP, for POP3 it's probably \"POP3 Server\".\n\nI'm not sure how to get your mails back on the \nserver from within K9 though… "}],"action":{"name":"View Issue","url":"https://github.com/k9mail/k-9/issues/2525#issuecomment-299117533"}}}
    
    
    
    -- 
Elliot M. Cramer
PO 428
Chapel Hill, NC 27514

919-942-2503

Professor Emeritus
Department of Psychology
University of North Carolina at Chapel Hill

ecramer@alum.mit.edu

Websites  
http://www.ourpaws.info/cramer
http://www.friendsofocas.org
  

	
        
		Virus-free. www.avast.com

**Comment by philipwhiuk** [comment]
There's an option in the settings for POP3 to leave messages on the server.

**Comment by eliot123** [comment]
On May 4, 2017 11:36:42 AM EDT, Philip <notifications@github.com> wrote:
>There's an option in the settings for POP3 to leave messages on the
>server.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2525#issuecomment-299223063

Where? All I see in settings is to remove from server when deleted. They are getting deleted from the server when the headings are loaded
-- 
Elliot M. Cramer 919-942-2503

**Comment by 0xf10e** [comment]
Which _is_ the default behavior for POP clients:
"Although most POP clients have an option to leave mail on server after download, e-mail clients using POP generally connect, retrieve all messages, store them on the user's PC as new messages, delete them from the server, and then disconnect."
[Wikipedia: Post Office Protocol](https://en.wikipedia.org/wiki/Post_Office_Protocol)

Even when Gmail still supports POP3 their server sure won't behave like a traditional POP3 server.

**Comment by eliot123** [comment]
On 5/4/2017 12:28 PM, Florian Ermisch
      wrote:
    
    
      Which is the default behavior for POP clients:
        "Although most POP clients have an option to
          leave mail on server after download, e-mail clients
        using POP generally connect, retrieve all messages, store them
        on the user's PC as new messages, delete them from the server,
        and then disconnect."
        Wikipedia: Post Office Protocol
      Even when Gmail still supports POP3 their server sure won't
        behave like a traditional POP3 server.
      —
    
     It's unfortunate that K-9 doesn't have this
      option;  obviously this is a choice that should be left to the
      user.  I really like K-9 otherwise but this is a downer.  The
      options that it does have to remove from server after deleting
      have no effect since they are already removed - a serious design
      flaw
     
  

	
        
		Virus-free. www.avast.com
