### ISSUE TITLE
Drafts Not Sync'ing Correctly: "IOException: readStringUnti"

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#2526]
### Expected behavior
New draft should be available in Draft folder on a different email client. 

### Actual behavior
- The draft is visible on other client, but the subject and body are empty. 
- If i sync K9, the subject and body remain empty on other client. 
- In K9 folder list, Drafts and Inbox both say "IOException: readStringUnti"

### Steps to reproduce
1. Compose email in K9.
2. Save as Draft. 
3. Sync K9. 
4. Navigate to Draft folder on other email client. 

### Environment
K-9 Mail version:
5.206

Android version:
5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Need a log to diagnose this.

**Comment by johnyradio** [comment]
Log attached. 
Seeing same error on Sent folder-- Sent messages are saved in Sent folder, visible locally, but not visible in Sent folder in other email clients. 
[k9-log.txt](https://github.com/k9mail/k-9/files/988477/k9-log.txt)

**Comment by philipwhiuk** [comment]
The log doesn't show any attempt to sync Drafts / Inbox so it's not of much use.

```
05-09 18:50:06.756 D/k9      ( 7050): Storing response #null# [5887, EXISTS] for later processing
...
05-09 18:50:06.765 D/k9      ( 7050): Got untagged EXISTS with value 5887 for <<>>/Thread-722/conn1124061064
```

is interesting but I'm not sure it's relevant.

**Comment by DFrostByte** [comment]
I posted this in the IRC channel a few hours ago:

> I'm using K-9 Mail version 5.207. Using an IMAP account, when I save a message to 'Drafts', which is set as a first class folder, the message doesn't upload/sync to my mail server. If I try to sync manually, the message disappears as though it's because the message doesn't exist on the server, it shouldn't be local either.

I don't have any messages in the error log.
