### ISSUE TITLE
Showing wrong folder when tapping on notification

### ISSUE THREAD

**Issue by doublehp** [k9mail/k-9#2528]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Show folder content

### Actual behavior
Sometimes, when I tap on notification in Android bar, K9 opens in some folder like Inbox, and shows messages from an other folder, like Work or any other folder from the account.

### Steps to reproduce
Random.

I would say it happenes more often when notification mentions several messages, than when telling about only one.

NB: I asked K9 to sync several Imap folders.

It seems to happen more frequently if several sync have been done between generation of android notification, and tap on notification; not sure if reading messages from an other MUA impacts.

It's a regression; it started around last christmass; never happened before mid 2016.

### Environment
K-9 Mail version:
5.206

Android version:
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by doublehp** [comment]
http://picpaste.com/2017-04-20_05-39-17_Screenshot_2017-04-20-07-39-16-UIyD9uLS.png

Here, it's saying Inbox on the top.

The listing contains mixed messages from several folders.  My messages are sorted by Gmail upon arrival. First one with title DansTonChat is stored in subfolder .DTC; most other messages where body starts with AUJOURDHUI are stored in .VDM.

In this view, K9 is showing recent messages; they all seem new and fresh, and showing them is not an issue by itself.

Issues are:
- K9 claims it's showing messages from Inbox
- it's showing in the same view messages from different folders without stating it

When tracking the bug, search for what happens when there are new messages in several different folders. Not sure if a new messages should be in inbox or not. Not sure if these messages must be new at the time of notification generation, or arrrived in a sync that happened after notification.

I have set K9 to sync many folders but notify me only about inbox.

**Comment by cketti** [comment]
See #5565
