### ISSUE TITLE
Feature Request: SMS integration option

### ISSUE THREAD

**Issue by sebastiannielsen** [k9mail/k-9#2529]
The K9 app should allow as a opt-in, to integrate with SMS/messaging.
So it "replaces the default SMS app on phone".

Also another feature, related to this, is two options, one to select to:
"Send everything as Email"
"Default"

And following (Both greyed out when "Default" is set on above option):
"Suffix to use when sending SMS as Email" [inputbox]
Account to use for sending SMS: [select popup that lists all IMAP/POP3 accounts configured]

In the inputbox for suffix, you can write anything, that will be added as suffix when sending a message to a receiver that does only contain digits and +.

So if I write ".sms@api.some_sms_corporation.com" as "Suffix to use when sending SMS as Email", and have "Send everything as Email" selected.
If I then compose a message to lets say 0707555555, then it would transmit the message to 0707555555.sms@api.some_sms_corporation.com via the selected email account.

(But suffix can also be left blank if your mail provider has builtin SMS functionality, like "RCPT TO: <0707555555> would send a SMS to 0707555555")

(If receiver contains anything other than digits and +, it should be considered a email message and be sent as-is)

If "Default" is selected, receiver that does only contain digits and + should be considered SMS, and be sent via SIM card. Subject line is then ignored. cc and bcc is considered a multi-receiver SMS.

Regardless of option, if its the default message app, it should receive all SMS messages in a special inbox called "SMS". Sent messages should only appear in inbox "SMS" if you have "Default" selected, else any sent messages should land in the "Sent" box of the chosen IMAP/POP3 account.

**Comment by cketti** [comment]
We're focusing on writing a decent email client. Support for SMS is not something we want to add to the app.
