### ISSUE TITLE
K-9 Setup Could Not Finish

### ISSUE THREAD

**Issue by MichaelGeister** [k9mail/k-9#2531]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Setting up k9mail should connect to the SMTP server.

### Actual behavior
This message appeared:

Setup could not finish
Cannot connect to server.
(Unable to open connection to SMTP
server.)

I could receive emails, but not send them.
[k9-log.txt](https://github.com/k9mail/k-9/files/991256/k9-log.txt)

### Steps to reproduce
1. Download k9mail from the playstore
2. Open it
3.

### Environment
K-9 Mail version:  5.206

Android version:  7.1.2 on Nexus 6P

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by philipwhiuk** [comment]
There's also errors showing it had problems connecting to an IMAP server. I suggest trying on a network with a better internet connection. There is no evidence this is anything other than a normal connectivity issue.

**Comment by fractalbob** [comment]
I'm having the same issue (cannot connect to either the IMAP server or SMTP), but on K-9 Mail built from scratch using the latest source from GitHub. I'm trying to connect to my Gmail account, after setting less secure apps to On.
