### ISSUE TITLE
omit /Exchange in mailboxpath

### ISSUE THREAD

**Issue by Flappes** [k9mail/k-9#2532]
### Expected behavior
i need to connect via activesync over scalixserver instead of exchangeserver. 
which uses root folder instead of /exchange. Setting own Mailbox-path with "mbpath" results in requests going to acctivesync.example.com/exchange/mbpath. /Exchange should be ommited.

### Actual behavior
ActiveSync-Account always wants to connect to activesync.example.com/exchange instead of activesync.example.com

### Steps to reproduce
1.create new Exchange Account with mailbox, which has to be connected via activesync.example.com with SSL/TLS.

### Environment
K-9 Mail version:
latest
Android version:
6.01
Account type (IMAP, POP3, WebDAV/Exchange):
WebDAV/Exchange

**Comment by philipwhiuk** [comment]
The path is the following format:

https://mail.domain.com/Exchange/alias/Inbox

This is formed of

root + OWA path + mailboxAlias + folder

In your case you need to set the OWA path to "/" to prevent us adding the "/Exchange" default.
