### ISSUE TITLE
Make it compatible with Detla Chat, add an option to disable new mail notification for specific senders

### ISSUE THREAD

**Issue by mario98** [k9mail/k-9#2534]
Maybe you have heard of a messenger called [Detla Chat](https://delta.chat/). It does chat over the e-mail infrastructure. I.e. it's like a mail client, but in the form of a messenger application. Lots of people already use it, and it will probably become more and more popular once more features are implemented (like encryption).

Now the problem is the following:
Detla Chat gives me a notification if I received a message form specific senders (white list). This is the desired behavior.
However, at the same time I also get a notification from k-9 mail. 
My request is to add an option to blacklist specific senders so that we don't get a new mail notification for them. That's it.

Would be really cool if you could implement this.

**Comment by cketti** [comment]
See #1144
