### ISSUE TITLE
Adding Information to documentation

### ISSUE THREAD

**Issue by user9209** [k9mail/k-9#2536]
Hallo,

I would ask you to insert a short text at

https://k9mail.github.io/documentation/settings/import_export.html

providing this feature:

#2535 

Like this
> Export Info:
>You can add your password by using &lt;password&gt;VALUE&lt;/password&gt; in the &lt;incoming-server&gt; and &lt;outgoing-server&gt; section to import including the passwords.

Thanks in Advance

Also thank you for the great work on K-9 Mail

**Comment by cketti** [comment]
No. Storing passwords in plain text in potentially world-accessible files is not something we want to encourage.

**Comment by user9209** [comment]
OK, if you change our mind you can ask for a pull request:

https://github.com/user9209/k9mail.github.io/commit/faf7e41161acf6b2e3a3aadeee8f80dcd77283c9
