### ISSUE TITLE
Failed to export settings

### ISSUE THREAD

**Issue by phillc54** [k9mail/k-9#2537]
Try to export settings

### Expected behavior
settings are exported to a file in com.fsk.k9

### Actual behavior
Error message:
Export failed
Failed to export settings

### Steps to reproduce
1. tap **Settings Import & Export**
2. tap **Export settings and accounts**

### Environment
K-9 Mail version: 5.206

Android version: 5.0.2

Account type (IMAP): There a 4 different accounts

### Notes

A zero byte file is placed in com.fsk.k9 named settings.k9s

I enabled debugging as per <https://github.com/k9mail/k-9/wiki/LoggingErrors>

k9-log.txt consists of:
--------- beginning of system
--------- beginning of main

I have gone to each accounts incoming server and outgoing server and tapped **Next**
as suggested here: <https://github.com/k9mail/k-9/issues/1100>

**Comment by ployt0** [comment]
I just exported, uninstalled Version 5.207, reinstalled Version 5.207, then successfully imported. I am using Android 7.1.2

**Comment by phillc54** [comment]
Well, I exported settings from another device, imported them to this device and then I was able to export them from this device.
I guess this means I had an error somewhere in the settings.
Why didn't the debug log show anything?
