### ISSUE TITLE
From field missing in email reading mode

### ISSUE THREAD

**Issue by davidhedlund** [k9mail/k-9#2539]
### Expected behavior
I expect to be able to read who I receive my emails like I do before I click on them. The sender is showed on the email list but when I click on them they should also show it like this for example: **From: anyone@anyone.org**

### Actual behavior
The From field is not added as an overview.

### Steps to reproduce
1. Click on any email
2. You'll notice that the Title and To field are showed, but not a From field

### Environment
K-9 Mail version: 5.207

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
In the message list we display From. In the email we will display both Sender and From in the next release.

See: #1727

**Comment by davidhedlund** [comment]
@philipwhiuk Thank you.
