### ISSUE TITLE
widget has to be set up at each reboot

### ISSUE THREAD

**Issue by Coeur-Noir** [k9mail/k-9#2541]
Widget = the one which gives a launcher for all mail accounts.

### Expected behavior
Should remain in a working state through boot and reboot

### Actual behavior
Have to set it all up each time phone is rebooted.

### Steps to reproduce
1. Install widget on your phone screen
2. Set it up, play with it fine, then shut down your phone.
3. On reboot, widget's icon has changed and no longer works.

### Environment
K-9 Mail version: 5.206

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by cketti** [comment]
Sounds like a problem with your phone rather than K-9 Mail.

**Comment by Coeur-Noir** [comment]
...because ???

It's the account widget, icon is white letter shaped.

Issue still there.
