### ISSUE TITLE
Support for Global Address List (GAL), possibly via EWS or ActiveSync?

### ISSUE THREAD

**Issue by derekatkins** [k9mail/k-9#2542]
K-9 does not support EWS or ActiveSync, and as a result does not have access to an Exchange Global Address List (GAL).  This can make it very annoying when trying to send email to co-workers.

### Expected behavior
K-9 should be able to look up contacts in the GAL

### Actual behavior
Only local contacts (in a contact database) are accessed

### Steps to reproduce
1. Setup a systemwide exchange account and sync contacts (e.g. office365)
2. Setup K-9 to access that email account (for office365 you must use IMAP)
3. Notice how gmail could access the GAL for office365 but K-9 cannot

### Environment
K-9 Mail version: 5.206

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): Technically IMAP, but it's an Exchange Server (Office365)

**Comment by philipwhiuk** [comment]
See also #606 which covers just the email side of this.
