### ISSUE TITLE
Can't poll or clear Deleted Items

### ISSUE THREAD

**Issue by kantarjiev** [k9mail/k-9#2548]
### Expected behavior
Polling Deleted Items should eventually terminate

### Actual behavior
The app is and remains unresponsive. Deleted Items is very large on the device but empty on the server.

### Steps to reproduce
1. Make a big Deleted Items
2.try to sync of clear local messages
3.profit

### Environment
5.206

Android version:
6
Account type (IMAP, POP3, WebDAV/Exchange):
Imap3

**Comment by cketti** [comment]
During sync K-9 Mail will delete all downloaded messages in the local Trash folder if the remote folder is empty. Depending on the number of messages this can take quite some time.

You didn't provide any specific information like number of messages in the Trash folder, database size, how long you have waited, what device you're using… That makes it impossible to tell whether the behavior you're seeing is to be expected or maybe a bug.

**Comment by kantarjiev** [comment]
I don't know where the database lives or how to tell how big it is. I was
waiting hours... Happy to try to provide more info.

**Comment by kantarjiev** [comment]
Oh, thousands of messages in the local folder, apparently back to January
of this year. None in the folder on the server.

Android says I'm using 250mb of data.

**Comment by cketti** [comment]
Enable 'Global settings > Display > Show account size', then navigate to the accounts screen. The storage occupied by an account will be displayed below the account name.

**Comment by kantarjiev** [comment]
Got it. 210 MB.

**Comment by kantarjiev** [comment]
Things were pretty much completely broken, so I used "Recreate data". It
took a while, but now the usage is down to 2.5MB, and things seem to be
working fine again.

**Comment by philipwhiuk** [comment]
Closing because we have no real performance targets here - if you make the folder big enough, yes it will take a while.
