### ISSUE TITLE
Icon notification still present after all messages read....

### ISSUE THREAD

**Issue by luc-chivas** [k9mail/k-9#2551]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by huste** [comment]
I think, what the main author wanted to say is, this:
* I have an IMAP account
* When new messages appear, the new mail notifcation is shown.
* When I mark the messages as read on *another* client, the message count in the laucher icon is updated. As well as the status of the messages in the message list.
* But the new message notification still lingers in the notification bar.

**Comment by luc-chivas** [comment]
Same with pop3 account... 

Le 11 août 2017 08:36:39 GMT+02:00, huste <notifications@github.com> a écrit :
>I think, what the main author wanted to say is, this:
>* I have an IMAP account
>* When new messages appear, the new mail notifcation is shown.
>* When I mark the messages as read on *another* client, the message
>count in the laucher icon is updated. As well as the status of the
>messages in the message list.
>* But the new message notification still lingers in the notification
>bar.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2551#issuecomment-321740682

Luc
+33 6 73396660 

Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by cketti** [comment]
Most likely caused by the same underlying issue as #1921
