### ISSUE TITLE
Share any email to a new Calendar Invite into Google Calendar app and others

### ISSUE THREAD

**Issue by christianmenkens** [k9mail/k-9#2555]
There should be a Share option that takes the whole email including history and all headers and moves it over to a Calendar event, appointment, invite into Google Calendar and other apps that can receive.

Optional, Ideally parsing some date and time from email text/thread, but maybe also google can do that.

**Comment by VinTz1** [comment]
I'll add something, of the mail contains an ICS event, it should be possible to add it to the calendar as well.

**Comment by philipwhiuk** [comment]
Please don't raise additional requests in the same issue. In any case that's already covered by #930.

Regarding the export to calendar for an email without a part, that's​ long been debated.

There's no obvious format for how other applications would receive the content. We've talked about a plug-in like architecture or separate apps before but honestly I've never seen a solution that I liked.

**Comment by CyberScooby** [comment]
I really miss this feature as well. For me though, it is not sharing with the calendar but rather with a kickass todo app called DGT GTD & To-Do List [[https://play.google.com/store/apps/details?id=com.dg.gtd.android.lite](https://play.google.com/store/apps/details?id=com.dg.gtd.android.lite)]

For instance I can go into my android browser and share a link to DGT. This allows me to create a task with the link details auto-populated (page title as the task title & link as the task notes). It would be great if I could do that with emails as well. The email subject could be filled into the task title & the body of the email would be the Notes attached to the task. At a bare min, having the subject would be better than the current nothing as I could use it to lookup the original email.

**Comment by therges** [comment]
I would like to vote for this too

**Comment by vaughanl** [comment]
Why is this closed? I'd like this too. Currently it is possible to share an email to other apps e.g. I can create a task in my Tasks app via the Share function or send the email via a messaging app in the same way. What I cannot do is create a calendar event. I don't need any fancy parsing to try and determine the date and time for the event. I'm happy do fill those details in myself. But copying the subject of an email, switching to the calendar app, creating the event, pasting the subject as the event name, switching back to the email, copying the body, switching back to the event and pasting in the description is a right royal pain in the behind.

**Comment by jayb-g** [comment]
> I'll add something, of the mail contains an ICS event, it should be possible to add it to the calendar as well.

Or as Google, Outlook and probably other calendars does it, automatically add it to default calendar on device based on certain conditions as (maybe)laid out in the standard RFC2445 such as if receiver is the organizer/participant
