### ISSUE TITLE
Still on F-droid?

### ISSUE THREAD

**Issue by grumpygeek** [k9mail/k-9#2557]
Is this app still hosted on Fdroid?  It's still listed but will not install on my phone.  Has been like that for about 2 weeks at least.

**Comment by VinTz1** [comment]
I've just test it, it install properly from F-droid

**Comment by cketti** [comment]
In general please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests. In this case the F-Droid forum might be the appropriate venue.
