### ISSUE TITLE
if supportlists HTML not rendered

### ISSUE THREAD

**Issue by ANEast** [k9mail/k-9#2559]
This bug relates to the rendering of 
`<p class=3D"MsoNormal" style=3D"mso-margin-top-alt:0cm;margin-right:0cm;mar=
gin-bottom:0cm;margin-left:72.0pt;margin-bottom:.0001pt;text-indent:-18.0pt=
;mso-list:l1 level1 lfo5">
<![if !supportLists]><span style=3D"font-family:Symbol;color:#1F497D"><span=
 style=3D"mso-list:Ignore">-<span style=3D"font:7.0pt &quot;Times New Roman=
&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style=3D"color:#1F497D">List item<o:p=></o:p></span></p>`

### Expected behavior
The display of the HTML message should either display a list or a hyphenated pseudo list, as directed by the HTML.  This is correctly rendered in other clients.

### Actual behavior
The rendering of the above is 
`<![if !supportLists]>-  <![endif]>List item`

### Steps to reproduce
1. Emails received with above encoding

### Environment
K-9 Mail version: 5.206

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Fixed by Jsoup changes in next release. Closing.
