### ISSUE TITLE
Adress Book

### ISSUE THREAD

**Issue by werano** [k9mail/k-9#2560]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
An inbuilt adressbook would be an advantage.

### Actual behavior
Tell us what happens instead
None available
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.207

Android version: 6+

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
> An inbuilt adressbook would be an advantage.

For what reason?

It's a lot of work to allow Contacts to exist outside of Android Contacts.

Even if we implemented a separate Contacts database we'd end up writing more code to sync between the two.

I don't see many practical benefits for this.

**Comment by werano** [comment]
I got your point. It just would be comfortable for me. 
thanks for your work

**Comment by pixelipo** [comment]
What's your problem with using the default Android address book?

**Comment by werano** [comment]
i don't find a link in the K9 app connecting the address book.

**Comment by pixelipo** [comment]
Just start typing into the "To" field and suggestions from your Android address book will pop up. That should solve your issue

**Comment by werano** [comment]
i don't use/have an addressbook just for emails. Only my telephone contacts where i don't store email addresses until now.

**Comment by frothfrenzy** [comment]
I actually left a comment recently regarding this in the K9 Google Group, and I'd argue it is a useful thing to have.

Sometimes I can't remember the addresses I'd like to send to and/or have to send to a bunch of them. Opening the address list in the stock e-mail app and selecting the recipients is a fast and very intuitive solution to do so. Apart for that, though, the stock app fails in almost everything else (hence K-9).

Of course, if it's time-consuming to code this, one can easily survive without it. It would be nice to have it, so I would humbly request that you at least consider it in the future if enough people report it.

**Comment by pixelipo** [comment]
@frothfrenzy I'm pretty sure this is never going to be implemented. I'm surprised it hasn't been closed already.

Your usecase seem to be a bit different than the original poster's one, but still when you are composing new email, "To" field is automatically filled up with possible matches from your default contacts list.

**Comment by frothfrenzy** [comment]
@pixelipo Yes, this is how I use it at a moment, works great for what it is. Though I would always prefer if there was a browsable list in addition to it, either by filtering mail addresses from existing contacts or having an address book of its own.

In any case, thank you for the response.

**Comment by pixelipo** [comment]
That would be a useful feature, however, it sounds more like something a contacts app should do

**Comment by ueen** [comment]
My issue is, that I have very few emails in my adressnook, it would be great if all email adresses I send emails to or received from would be suggested in the To field. I think that's also what the others meant. This it's common behavior in eg Outlook

**Comment by ychaouche** [comment]
+1. At least automatically collect addresses.
