### ISSUE TITLE
Exported Settings: filename should contain additional info (export data)

### ISSUE THREAD

**Issue by yafp** [k9mail/k-9#2562]
### Expected behavior
The export file of the k9 settings should contain the export data (should be easy to implement and adds additional helpful info)

Example:
- k9_settings_export_20170520.k9s
- k9_settings_export_20170601.k9s

### Actual behavior
Current export settings are following a numbers name schema if i get it right

Current names:
- settings-5.k9s
- settings-6.k9s

### Steps to reproduce
1. Export settings

### Environment
K-9 Mail version: 5.206

Android version: 7.1.2

Account type: IMAP

**Comment by philipwhiuk** [comment]
You mean the date?

We'd probably still want the suffix (I believe Android does that automatically).

But it seems like useful and non harmful change to do this.

**Comment by yafp** [comment]
yes - adding export-date to the filename would be great

**Comment by clawoflight** [comment]
I would like to work on this. 
Is there anything I should be aware of? Are you using any non-stdlib calendar library?

Thanks for the `beginner` label btw, that's very helpful for people to get into contributing code! :)

**Comment by palashshah** [comment]
Hey @yafp I would like to work on it. Please guide me through the basic steps so that I can solve the issue. :)

**Comment by yafp** [comment]
@palashshah 
hi, what informations you you need? Keep in mind that @clawoflight already mentioned he is willing to work on it- so please speak with him as well ;)

**Comment by harisriaz17** [comment]
Hey @yafp, can you tell me the sub-directory in which the export file of the k9 settings is located, so that I can start working on it too, and hopefully push a commit before the others :)

**Comment by clawoflight** [comment]
Dude, you think this is a race? 
FWIW, I have a patch ready, but I didn't get around to setting up the emulator for testing yet. 

On July 18, 2017 9:03:04 PM GMT+02:00, Haris Riaz <notifications@github.com> wrote:
>Hey @yafp, can you tell me the sub-directory in which the export file
>of the k9 settings is located, so that I can start working on it too,
>and hopefully push a commit before the others :)

-- 
GPG fingerprint: 871F 1047 7DB3 DDED 5FC4 47B2 26C7 E577 EF96 7808

**Comment by harisriaz17** [comment]
No, but Gsoc IS a competition, and I intend to do my best to get selected. Kudos to you if your patch works, and you get it committed before me, because I'm still trying to understand their code base before I push anything.

**Comment by cketti** [comment]
@harisriaz17: You're a bit late. The student application deadline was April 3.
See also: https://k9mail.github.io/2017/05/05/Google-Summer-of-Code-2017-Projects.html

This issue should require only small changes to the code. Figuring out what to change is part of the learning process. If we wrote down detailed instructions you wouldn't learn anything and we might as well do it ourselves.

**Comment by harisriaz17** [comment]
Oh okay thanks for the feedback. Btw I know this years GSoc process is over, I was talking about next year's (2018),if this organization participates. :D

**Comment by clawoflight** [comment]
This can be closed now that the PR is merged.
Sorry, I forgot to put the magic phrase in the commit :)
