### ISSUE TITLE
OutOfMemoryError opening emails

### ISSUE THREAD

**Issue by bayang** [k9mail/k-9#2563]
Hi !
When I try to open some long html mails (but no attachments, no inline pictures etc... Just text) nothing happens, I just get empty white mails.
So I checked the logs and I saw that reading those mails causes OOM. (log file is attached with this issue)

### Expected behavior
The body of the mail should appear

### Actual behavior
Blank/empty content
OOM.

### Environment
K-9 Mail version: 5.207 

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): gmail IMAP

[k9-log (copy).3.txt](https://github.com/k9mail/k-9/files/1044620/k9-log.copy.3.txt)

Thanks

**Comment by fobo66** [comment]
Crash was caused by `org.htmlcleaner.Serializer#getAsString`, which was replaced by Jsoup already (commit 268189c1b097a058cf8e5da621f760871fa58d58).

I guess, it's needed to check this again, because it looks like this issue is irrelevant anymore. I'll try to check it on K-9 5.403.

**Comment by cketti** [comment]
I believe this is no longer an issue.
