### ISSUE TITLE
French Translation issue

### ISSUE THREAD

**Issue by luc-chivas** [k9mail/k-9#2564]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Should see " Vider la corbeille"
### Actual behavior
Tell us what happens instead
Display "Vidage de la corbeille"
### Steps to reproduce
1. Go to folder list 
2. Select ....
3. 

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Please use Transifex to contribute translations.

**Comment by luc-chivas** [comment]
Hello Philip, how use it..?

Le 2 juin 2017 12:47:04 GMT+02:00, Philip <notifications@github.com> a écrit :
>Please use Transifex to contribute translations.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2564#issuecomment-305753794

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by philipwhiuk** [comment]
Register here: https://www.transifex.com/k-9/k9mail/

**Comment by luc-chivas** [comment]
How it works ??

 

Luc

+33 6 73 39 66 60

 



 

De : Philip [mailto:notifications@github.com] 
Envoyé : jeudi 8 juin 2017 10:06
À : k9mail/k-9 <k-9@noreply.github.com>
Cc : luc-chivas <lucky@magic.fr>; Author <author@noreply.github.com>
Objet : Re: [k9mail/k-9] French Translation issue (#2564)

 

Register here: https://www.transifex.com/k-9/k9mail/
