### ISSUE TITLE
DNS issue with K9

### ISSUE THREAD

**Issue by darose** [k9mail/k-9#2565]
K-9 seems to be caching DNS lookups, which is causing an issue when I use it on my internal network.

I operate an email server out of my home network.  It is reachable from both outside my network (my router port forwards incoming connections to the email server) and inside my network (by connecting directly to the server's internal IP address).

K-9 is able to access the server when outside my network (e.g., when on my cell carrier's LTE networks).  But when I'm inside my network, K-9 isn't able to access the server - it can not send or receive messages.

The reason has to do with DNS.  I access my server via a DNS name.  I use a dynamic DNS service so that externally my DNS name is associated with the external IP of my router.  Internally, however (i.e., behind my router) I operate my own DNS server, and so in my internal DNS I associate that DNS name to the private IP address of the mail server.

The net effect should be:
* Outside my network the DNS name points to my router, which port forwards to my server.
* Inside my network the DNS name points directly to my server.

So in either case, network access to that DNS name should go to the server.  However, that's not what's happening with K-9.

External access works fine.  But inside my network, K-9 seems to be ignoring my internal DNS server.  Instead it seems to be looking up my DNS name against an external DNS server - or perhaps it's just looking up the DNS name in some internal cache. Whatever the cause may be, the result is that K-9 resolves the DNS name to *external* IP address of my network, and then tries to connect to that external address - even though it is inside my firewall and should be connecting to the internal address.  And since the external IP address is the address of my router, not my mail server, K-9 tries to open connections to my router to send & receive email, and (obviously) fails.  The net result is that K-9 can't send/receive messages to/from my email server when I'm on my home wifi network.

Note that this problem only happens with the K-9 mail app on my phone.  When I use other apps (e.g., the UC Web browser) on my internal network they are able to successfully resolve the DNS name to the internal address, and so can successfully make connections to the server.

### Expected behavior
* When I try to send/receive messages to/from my email server while on my home network, K-9 should do a DNS lookup that gives it the internal address of my home email server, and so it should be able to successfully send or receive.

### Actual behavior
* When I try to send/receive messages to/from my email server while on my home network, K-9 either does a DNS lookup that gives it the *external* address of my home email server, or reads the external address from some DNS cache, and so is not able to successfully send or receive.

### Steps to reproduce
1.  Connect to my home wifi network.
2.  Try to send an email through K-9.  It fails ("cannot connect exception")
3.  Turn off wifi on my phone, and try again to send.  It succeeds.

### Environment
K-9 Mail version:
5.206

Android version:
7.1.2

Account type (IMAP, POP3, WebDAV/Exchange):
Both IMAP and SMTP

**Comment by cketti** [comment]
K-9 Mail goes out of its way to not cache DNS responses. See https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java#L176

However, it's possible this no longer works with Android 7.1 and K-9 Mail is getting a cached result from the OS. A debug log contains information on which IP address is used to connect to a server. This should allow you to narrow down the list of possible causes. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by darose** [comment]
Will do when I get home.

BTW, not sure if it's relevant, but it doesn't look like the SMTP module is performing the same DNS cache disabling.

https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.java

**Comment by lbdroid** [comment]
It sounds to me like you've come up with a hack to hide a configuration error on your router. You should NOT need to use a private internal IP address to access your mail server from the "inside" of your local network. Take a look at your firewall configuration.

**Comment by darose** [comment]
Not sure I see how this is a hack.  My mail server has a different private and public IP address.  That's not uncommon - nearly every machine that's reachable on the public internet does.  So when I do a DNS lookup internally I get the private address; when I do it externally I get the public one.

**Comment by lbdroid** [comment]
Its a hack because you should still be using your PUBLIC ip address from within your private network.

**Comment by darose** [comment]
Not sure I understand why.  Do you have a link to something that supports that "you should"?

**Comment by lbdroid** [comment]
Why? BECAUSE IT IS EASIER than making up a crazy hack.

**Comment by darose** [comment]
There's no crazy hack.  There's an internal DNS server and an external DNS server, like millions of other systems have.  And you're really not providing links to any facts to back up what you're suggesting

**Comment by lbdroid** [comment]
I don't need to provide a link, you can use google yourself. You need to go learn HOW DNS WORKS.

Its fine to put a DNS server on the inside, but its purpose is not to provide different responses to what are provided by an outside DNS server. The purposes of an internal DNS server are generally;
1) To CACHE responses,
2) To provide DNS for internal IP addresses (think along the lines of "tom.local").

**Comment by darose** [comment]
Let's ignore the fact that I actually *do* know how DNS works, and also ignore the fact that k9 actually has a bug here because it's caching its DNS lookups when it shouldn't be.

So let's step through the issue.  I have a domain name pointing to an external IP address.  My router port forwards to my mail server.  Fine, that all works when I'm outside my network.

Now I'm inside my network.  The domain name still points to the external IP address - the address of my router.  But, since we're inside the network, the router doesn't port forward internal traffic.  (Most routers don't.)  So K9 tries to open IMAP/SMTP connections to my router - and fails, because the router isn't a mail server.  (This is exactly the situation that I filed the bug about.)

So if, as you assert, getting K9 to work properly and not cache its DNS entries so that it gets the correct IP address, is the wrong/hacky solution here, then what would you suggest is the "correct" fix?

**Comment by njeyaakili** [comment]
What @darose has set up is generally referred to as a "split-horizon" DNS. He is using separate DNS servers for this, rather than configuring a single server to respond differently depending on the source of the request. The server setup approach taken depends on ones environment. This is very common and highly recommended in various contexts for security as well as networking efficiency reasons. 

That said, while I don't have my email set up that way currently (mail server is now external to my network), as of a couple releases of back I have never run into this type of caching issue with K-9. The caution is to make certain that your devices, when internal, aren't getting pointed to external DNS servers, e.g., by a router or access point configuration. I assume you have, but use a DNS tool on the mobile device to confirm that you're getting back the correct A-record.

**Comment by lbdroid** [comment]
@njeyaakili It doesn't make sense in HIS context, since he is using it as a hack to work around a configuration error on his router.

@darose it isn't k9mail that is caching DNS. It is the OPERATING SYSTEM, which is doing EXACTLY what it is supposed to do -- cache the DNS responses until the TTL expires, and ONLY THEN go back and refresh them.

**Comment by darose** [comment]
I'm fairly certain that k9 is what's doing the caching, *not* the operating system.  How do I know?

1) k9 is the only app that exhibits this behavior.  I have a similar situation with my web server & browser app.  My web server runs on the same machine as my mail server.  When I use my browser app to connect to my web server by dns name, get the same page whether I'm inside or outside of my network.  If this were an operating system issue, then when I'm inside my network my web browser would do a DNS lookup, resolve it to the IP of my router, and try to connect to the web server running on the router.  (Which would be the router's internal admin tool.)  That doesn't happen.

2) A TTL would *eventually* expire (after 1 hour maybe?) at which point the device would do a DNS refresh, and K9 would suddenly magically start being able to connect to my server.  That doesn't happen.

3) When I first started researching this problem, I opened a DNS app on my device and did a lookup to see if it was getting the external IP or internal IP.  It was getting the internal, while K9 is somehow still getting the external.

It's very typical that when you join a new network, that that network pushes a DNS server IP to your device (which gets added to your resolv.conf) and is then used for subsequent DNS lookups.  This happens when you join a VPN, and it also happens when (as in my case) you join a new wifi network.  It seems odd to me that DNS caching would outlive a major system networking change like that.

Anyway, why don't we all stop trying to speculate what we think is happening here.  (Myself included.)  When I have a moment I'll grab a log from my device and then we'll have some factual information as to what's actually occurring.

**Comment by cketti** [comment]
Closing because no further information was provided.

**Comment by nabber00** [comment]
It seems like this might actually be a more generic sync issue like those documented in #3167 or #2357

**Comment by darose** [comment]
This issue is gone now.  For the record (and future reference), I think what might have happened here is that there's both a ipv6 and an ipv4 address for my email server, and k9 was trying to connect to the ipv6 address first (and failing), and then later somehow switching to use the ipv4 address (and succeeding).
