### ISSUE TITLE
No windowed mode on Galaxy Note (10.1, 2014)

### ISSUE THREAD

**Issue by KalWardin** [k9mail/k-9#2570]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Being able to create a resizable window in order to share the screen with other apps (multitasking).

### Actual behavior
K9 opens up maximised instead, thus minimising other apps currently on screen

### Steps to reproduce
1. Open up an app
2. Pull up the multitasking panel (long-press the return button)
3. Tap K9 

### Environment
K-9 Mail version: latest

Android version: 5

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by lbdroid** [comment]
Tell Samsung to update your system to Android 7. k9mail will work in both split screen and floating window modes that are implemented using the GENUINE multi-display modes built into Android. I doubt that anybody is all that eager to work on implementation for a samsung hack.

**Comment by KalWardin** [comment]
Virtually every decent app I’ve used to date has supported that mode. K9 is obviously an outsider ;)

**Comment by philipwhiuk** [comment]
I don't see much harm in supporting it as long as it's relatively isolated and maintainable.

I'm going to tag this as help wanted as you need a Samsung phone to work on this and I assume none of the active devs have one.

For reference we already have an issue regarding Android multiwindow support - it's a matter of testing and bumping the target API (which means updating various bits and prices) - it works right now but you get a warning.

**Comment by lbdroid** [comment]
@philipwhiuk Samsung has abandoned their proprietary multi-window mode and is now using AOSP. OP is using android 5, which is already ancient history. Supporting this isn't worth one single line of code.

**Comment by philipwhiuk** [comment]
We still support Android 4.4 I believe (API 19). Android 5 was released in November 2014. It's not ancient history. I think it's more than reasonable to add 1 line of code for this.

**Comment by lbdroid** [comment]
It isn't android 4 or 5. Its SAMSUNG. A bastardized fork of android.

**Comment by philipwhiuk** [comment]
"Samsung and LG now account for 78 percent of all Android sales in the US | Android Central"

Yeah, just Samsung, no big deal.

**Comment by lbdroid** [comment]
Ok, waste time on crap, knock yourself out.
