### ISSUE TITLE
Threads expandable collapsable view 

### ISSUE THREAD

**Issue by Aasaqt** [k9mail/k-9#2573]
Hey

I am trying to achieve the thread expandable and collapsible view in the main MessageListView. I have done the basics.
I am stuck where messageLoaderCallbacks give the data after some time and thus is not shown in list but when i scroll the list gets populate with the messageView.

Can you suggest some work around how can i achieve this in one go?

**Comment by philipwhiuk** [comment]
Is this for an existing issue?

It's hard to understand what you're trying to achieve tbh.
