### ISSUE TITLE
Intermittently slowness for mailbox refreshing

### ISSUE THREAD

**Issue by perfprobe** [k9mail/k-9#2575]
Dear developers, 

We are applying our performance diagnosis tool [PerfProbe](https://github.com/perfprobe/PerfProbe) to debug the delay for mailbox refreshing in K9 mail app and observe that sometimes the refreshing time increases by 4~5 seconds (on average around 2 second to refresh in my setup). Through its system-wide profiling and tracing, PerfProbe discovers that the source of extra delay results from longer execution time in com/android/org/conscrypt/NativeCrypto.SSL_read API calls (for example, one invoked by com/fsck/k9/mail/store/imap/ImapFolder.open -> com/fsck/k9/mail/store/imap/ImapConnection.open -> com/fsck/k9/mail/store/imap/ImapConnection.authenticate -> com/fsck/k9/mail/store/imap/ImapConnection.saslAuthPlain), possibly caused by longer waiting time for server-side responses. We validate the root cause by enabling the debug messages in K9 and find that an existing IMAP connection seems to be disconnected occasionally, which results in this extra delay for setting up a new connection with the IMAP server during mailbox refreshing (mainly contributed in the authentication phase).

We hope the findings from our tool can be helpful for your debugging. We are also interested in helping improving the performance of this interaction. To maintain the responsiveness of mailbox refreshing, we are wondering if there is any way to keep the IMAP connection persistent for a long time, which may help maintain consistent responsiveness for mailbox refreshing. Thank you very much for your attention and clarification! 

Related issues: [1839](https://github.com/k9mail/k-9/issues/1839), [2075](https://github.com/k9mail/k-9/issues/2075), [1942](https://github.com/k9mail/k-9/issues/1942)

### Expected behavior
Consistent mailbox refreshing time (~2second)

### Actual behavior
Mailbox refreshing time increases by 4~5 seconds 

### Steps to reproduce
1. Enter a mail box (hotmail in my case)
2. Click the refresh button
3. Wait for the mail syncing to be done

### Environment
K-9 Mail version: 5.206 from Google Play
Android version: Android 4.4.4 
Device: Nexus 4
Account type (IMAP, POP3, WebDAV/Exchange): IMAP
Incoming server settings: 
     IMAP server: map-mail.outlook.com 
     Security: SSL/TLS
     Authentication: Normal password

**Comment by philipwhiuk** [comment]
The only way to prevent a server from closing an IMAP connection is by entering IDLE mode which not all servers support.

**Comment by Indigian** [comment]
How long should it take to check 22 accounts for new emails?
Mine takes a long long time over some accounts sometimes.

**Comment by philipwhiuk** [comment]
The main reason for that is that we don't check accounts in parallel because it makes synch more complex. Fairly sure we already have an issue for that .

**Comment by Indigian** [comment]
It takes minutes to check my 22 accounts.
Seems to take most time checking drafts?

**Comment by philipwhiuk** [comment]
Realistically that's probably just because Drafts is the first folder alphabetically.
