### ISSUE TITLE
Tap View signer to search email

### ISSUE THREAD

**Issue by tigerwoods2k17** [k9mail/k-9#2578]
When we tap "View Signer" in the dialog showing the encryption status, the user is taken to Openkeychain to search for the send using the key id. How can I change it email instead of key id? 

I cant seem to find the intent which sends the extra "EXTRA_KEY_ID", as this is the string thats getting sent to Openkeychain

**Comment by philipwhiuk** [comment]
From reading the code OpenKeychain provides the Intent that then get's called by us to request the data. So it's like a callback.

How this works is as follows:

We request decryption:
We are returned a CryptoResultAnnotation
The CryptoResultAnnotation contains an Intent
We call that here: https://github.com/k9mail/k-9/blob/231b46f27839f599d95ef3f62cd66f4a20e0e62e/k9mail/src/main/java/com/fsck/k9/ui/messageview/MessageCryptoPresenter.java#L228
That launches OpenKeychain.

So you'd have to modify the intent that open keychain provides us.

I can only assume that this is this intent: https://github.com/open-keychain/open-keychain/blob/b328c9785382857afdcdd1010b29fcb3476a0687/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPendingIntentFactory.java#L103

**Comment by tigerwoods2k17** [comment]
Going through the code I did find these but need someone to explain how exactly it was working.

Thanks!

**Comment by cketti** [comment]
Feel free to ask specific questions via these communication channels: https://github.com/k9mail/k-9#communication
