### ISSUE TITLE
Randomly unable to authenticate to one of my three IMAP accounts

### ISSUE THREAD

**Issue by galexmay** [k9mail/k-9#2583]
### Expected behavior
I should be able to download my emails

### Actual behavior
Randomly I get an authentication error that might last a minute or an hour or sometimes longer
The error message is "Username or password incorrect. (Command: *sensitive*; response: #3# [NO, LOGIN failed.])
I am not changing the username or password. After a while, the error goes away, but can come back several times a day.
When I get the error, I get no email download.
[k9-log.txt](https://github.com/k9mail/k-9/files/1073043/k9-log.txt)

### Steps to reproduce
Random

### Environment
K-9 Mail version: 5.206

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
This is something you'll have to take up with your email provider - we aren't doing anything wrong and 'LOGIN failed.' is all we get back.

**Comment by galexmay** [comment]
The provider says I have to take it up with you because the fact that other
apps are able to connect shows they are doing nothing wrong.
Very helpful all round!
I have just given up on K9

**Comment by lionslair** [comment]
Same issue here. However if i send myself test emails from another account they are coming through.

Not happening on other devices just my device running Android 7.1.1

**Comment by philipwhiuk** [comment]
The most likely cause is they limit the number of connections you can make and you are hitting that limit.

The provider knows why they are failing your login. We don't. They are the only people who can help here.

**Comment by ChickyChill** [comment]
I experience the same Problems. today, all of my 5 accounts on 3 different providers gave out that message. When the Provider has a Problem with the authentification, I usually receive a note while logging in on a browser or with another Programm... only in k9 this happens. sometimes i have to delete accounts, and create them new, so that it works again...

**Comment by kp625544** [comment]
Any solution anyone figured out?
