### ISSUE TITLE
Minor issue: redundant new lines while rendering

### ISSUE THREAD

**Issue by FrankEular** [k9mail/k-9#2584]
I see many redundant new lines ("\n") when copying the content of an email to the clipboard and paste it to somewhere else. This will be annoying when the width of the place I paste is different from that of K-9 Mail, because these new lines are used to render the text to accommodate the width of K-9 Mail.

### Steps to reproduce
1. Open an email (of plain text)
2. Copy the content to the clipboard
3. Paste into another place.

### Environment
K-9 Mail version: 5.207

Android version: Marshmallow

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
I believe this is due to the way we retrieve emails, but I may be wrong.

**Comment by cketti** [comment]
We don't insert newlines for display. They are likely present in the original message.
