### ISSUE TITLE
K9 mail regularily forgets settings and accounts

### ISSUE THREAD

**Issue by martinbrylski** [k9mail/k-9#2586]
### Expected behavior
Never ever forget accounts and settings.

### Actual behavior
From time to time K9 mail forgets settings and accounts.

### Steps to reproduce
1. Configure k9 mail properly
2. Use it several days and weeks
3. Bam! Data forgotten

### Environment
K-9 Mail version: current from playstore (5.206)

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange):
3 times imap

**Comment by philipwhiuk** [comment]
#750 - we have no idea why this occurs and aren't likely to unless someone can provide relevant device logs.

**Comment by martinbrylski** [comment]
1. No information given how to provide logs.
2. No necessitiy shown that further feedback is welcome, just closed issue.
3. No further interest in any collaboration shown.

Big fail, dude.

**Comment by philipwhiuk** [comment]
1. As mentioned multiple times in the Wiki and I believe the README: https://github.com/k9mail/k-9/wiki/LoggingErrors
2. All of that is in the linked issue you clearly didn't visit. This is a duplicate that's the only reason I closed it.
3. If we didn't accept collaboration we wouldn't allow pull requests.

**Comment by martinbrylski** [comment]
Ah, thank you. I missed the Logging Wiki Page.

I will see if I can provide the necessary information. Technically its ok, I'm also android developer.
