### ISSUE TITLE
[FR] send mail transport alternative to SMTP: MAPI

### ISSUE THREAD

**Issue by ildar** [k9mail/k-9#2587]
I use K-9 for corporate mail. Unfortunately SMTP here is unreliable and main transport is M$ Exchange/Outlook/MAPI :(
I wonder if it's possible to make K-9 send mail using MAPI? A couple of ideas comes to mind:
1. If it's possible trough the "Exchange account" of Android.
2. Implement MAPI transport in K-9
3. Maybe some 3rd party adapter like openchange running locally on Android.

**Comment by philipwhiuk** [comment]
A brief looks suggests this would involve writing a MAPI implementation from scratch as most of the existing implementations rely on the host Windows OS rather than a ground up protocol implementation. I think it's unlikely to be honest but if someone wants to work on it...

**Comment by ildar** [comment]
I hoped that Exchange thing every Android has would take this part, though
I really don't know anything about it.
As for the implementation "from scratch" I started using
http://davmail.sourceforge.net/ right today which provides the pure Java
adapter for my desktop MUA.

**Comment by ildar** [comment]
any more info needed?
