### ISSUE TITLE
improper message order in German localization

### ISSUE THREAD

**Issue by sdicke** [k9mail/k-9#2591]
### Expected behavior
The messages in the inbox should be sorted by date, the newest ones on the top.

### Actual behavior
The messages are sorted by date, the newest ones on the top, but if there are older messages, they are sorted above the newest ones sometimes. I use a German localization. Example: 

14. Juni
14. Juni
14:58
14:53

### Steps to reproduce
1. Open inbox folder filled with received messages

### Environment
K-9 Mail version: 5.207

Android version: 5.0.1

Account type: IMAP

**Comment by philipwhiuk** [comment]
I doubt this is a translation issue. I suspect it's related to either the timestamp in the header of that message or a UID ordering issue.

**Comment by sdicke** [comment]
I found the problem, I selected sorting by attachment. Obviously I do not receive much messages with attachments and so I tough it would be an failure in the by date sorting.
