### ISSUE TITLE
Inbox empty after I updated app

### ISSUE THREAD

**Issue by LostEVERYTHING** [k9mail/k-9#2593]
I had about one hundred messages "saved" in my inbox. I had deleted these messages from the server. When I updated to the latest version of K-9 my inbox is now empty. I didn't expect to loose any messages. All of my settings were saved and K-9 will download new messages. I used play store to install the update.
How do I get these messages back?

### Environment: Living room
K-9 Mail version: Updated from 5.007 to 5.206

Android version: 4.2.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by robertc** [comment]
Similar thing happened to me today, opened app to find all mail accounts gone. Seems to happen every 3 to 4 months.
