### ISSUE TITLE
Emails not displaying properly - Only top half!

### ISSUE THREAD

**Issue by sadsplace** [k9mail/k-9#2596]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
An email should open and display properly!

### Actual behavior
Tell us what happens instead
I get the top half of an email "wobbling" then solid, but no bottom half of the email. Sometimes if you close the email then reopen a few times it does display, but mostly not.

### Steps to reproduce
1. Open email, top half wobbles then solid, but no bottom half.
2.
3.

### Environment
K-9 Mail version:
5.206

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Every email? Or just a specific one. If it's just one then the source of the email would be useful

**Comment by sadsplace** [comment]
No, it seems to be a number of different sources which aren't related (By business anyway, don't know about format).
It's weird, when you open the email, the portion displayed kind of flickers or wobbles, you can occasionally see some of the rest of the message body but then usually ends up with half of the message.

**Comment by sadsplace** [comment]
If the email is mainly text, then it opens fine.
I have just opened one fine which wouldn't open properly earlier. Closed it then it only showed half again.
I just tried to video it but you can't see the flickering.
The tablet works fine for every other app, this only started happening seemingly after one of the recent updates.
