### ISSUE TITLE
Data is not synchronized

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#2597]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When I delete a message in a deleted folder of k9, the web page should also delete the message.

### Actual behavior
But the result is that message not delete

there is some warning log：
Attempt to interrupt null mConnection to stop pushing on folderPusher...

### Environment
K-9 Mail version:The latest version

Android version:Each version exists

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by Clszczepanski** [comment]
I am having a similar issue. I am getting several "cannot connect to host" errors in my K-9mail Errors folder. Along with "push disabled". It's causing the app to notify me of the same messages repeatedly, even though they are already read
