### ISSUE TITLE
Inobx sorted by time mail was fetched to phone and not received on server

### ISSUE THREAD

**Issue by mattncsu** [k9mail/k-9#2599]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Messages will be displayed in the order they were received by the mail server.

### Actual behavior
I've noticed that thanks to the doze issue that when emails do come in, they all have the same time stamp in the inbox.  Say I do a manual sync at 4PM, all the messages retrieved will say they were received at 4PM regardless of email header data. If I open the message, the proper time is displayed in the header area.

### Steps to reproduce
1.Pause syncing
2. Wait for new mail to arrive
3.Sync

### Environment
K-9 Mail version: latest (sorry don't have phone on me currently)

Android version: Nougat on Samsung Galaxy S7 (vzw)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by mattncsu** [comment]
Here are screenshots from my phone and desktop webmail showing the difference in time stamps:

![screenshot_20170630-105320](https://user-images.githubusercontent.com/24309552/27741793-4fb18f36-5d84-11e7-85c7-99c511ba94e7.png)
![webmail](https://user-images.githubusercontent.com/24309552/27741710-041b20dc-5d84-11e7-98c3-d1b4be361281.png)
The expected behavior is that K9 would match webmail.

**Comment by philipwhiuk** [comment]
I suspect this is because the emails are not being provided with valid headers so we can't parse the Recieved date-time.

**Comment by mattncsu** [comment]
On close comparison, the trouble emails are missing a "date" entry in the header. Would it be possible to extract the date from one od the "received from" entries when the date field is not present?

**Comment by philipwhiuk** [comment]
Yeah, it's the `Date:` header I was thinking of.

We could do. It's a bit ugly (the format of Received headers is standardised but probably ignored a lot). The `Date:` is really the sending time after all. I'm interested to know what other clients do. 

In reality though this is a bug for the clients sending you emails. While not strictly mandatory it's pretty poor not to send a date header. For spam it's kind of unsurprising but that Camera email generator really should do better.

**Comment by mattncsu** [comment]
I just dusted off my copy of Outlook and it reports `Sent: None` when the email is opened but places it in the right position on the email list.  It appears to extracting the date from the 'Received'  header (not sure if its using first or last because they are all within 1s of each other) and rounding to the nearest minute.  I'll file a bug report with the camera manufacturer not that I expect them to issue a firmware update. 

Found a similar [issue ](https://bugzilla.mozilla.org/show_bug.cgi?id=266434)reported a decade ago on Thunderbird

**Comment by glawrence** [comment]
I have just come across this issue as K-9 was driving me mad showing the time the mail landed on my phone and not the server. I can see that the "Date: " header is missing but Microsoft Outlook on Android manages to parse the "Received: " header and show that date just fine, as does my webmail client. I appreciate it is not ideal to parse another header but so many things with e-mail are not ideal! My view is this is letting K-9 down, it certainly put me off and had me start searching for another client.

This leaves with me with options:
- find another client
- fix the e-mails, they are sent from my own code
- help fix K-9

The best thing is we fix K-9, however I would need some help with that! So, I am going to look at my code that sends the e-mails now.

**Comment by philipwhiuk** [comment]
Yeah, if you're not providing an RFC compliant format we aren't going to fix K-9 to handle that for your email.

Firstly because there's a limit to the number of format we can handle.

e.g. you can't reliably handle: 21/7/2018 and 7/21/2018

Secondly because it's silly to change email parsing for everything just for one user's self generated email.

**Comment by glawrence** [comment]
It is however interesting that whilst Date is mandatory, or at least that is how I understand [RFC 2822](https://tools.ietf.org/html/rfc2822.html#section-3.6) that other e-mail clients handle its absence just fine. So, however correct K-9 might be, it looks like the odd one out and hence wrong, it was certainly more than enough to put me off!

I have added the Date header to my Python (it is not set by default!) and now it works nicely. However if you are open to a PR and some help guiding me then I am happy to try and make K-9 parse the "Received" header

**Comment by mattncsu** [comment]
As owner of some network cameras that send notification emails without a
date field, I'd also be interested in this enhancement to better treat
non-RFC compliant emails.

**Comment by cketti** [comment]
See #1356
