### ISSUE TITLE
K9Mail crash often when I delete a message from threaded messages

### ISSUE THREAD

**Issue by Paviluf** [k9mail/k-9#2604]
Hello,

### Expected behavior
K9Mail doesn't crash when I delete a message from threaded messages.

### Actual behavior
K9Mail crash often when I delete a message from threaded messages.

### Steps to reproduce
1. Delete a message from threaded messages.
2. K9Mail crash

### Environment
K-9 Mail version: 5.207

Here is a log : 
[2017-06-27-06-02-44.txt](https://github.com/k9mail/k-9/files/1104182/2017-06-27-06-02-44.txt)

Android version: 4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thanks !

**Comment by Paviluf** [comment]
Maybe somewhat related to this one https://github.com/k9mail/k-9/issues/1494 because I think the crash happen when I delete the last message from a threaded group.

**Comment by Paviluf** [comment]
A workaround is to disable threaded messages.

**Comment by TKLCZ** [comment]
https://github.com/k9mail/k-9/issues/3325
This is not duplicate od this issue because I don't use threads.
The crash occurence depends on number of e-mails in  a folder (more than 2500).

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.7xx.
