### ISSUE TITLE
Authentication failed for xxx@xxx.xxx. Update your server settings

### ISSUE THREAD

**Issue by TrentSC** [k9mail/k-9#2609]
[Running Android 7.0 on a stock unrooted Samsung Galaxy S7 Edge (SM-G935F) with K-9 Mail Version 5.206]

I've been using this app for a couple of years without any issues to run a total of 7 email accounts (six G Suite, one gmail and one Outlook, one hotmail, all IMAP).  In the past couple of days my primary G Suite account has been failing with the notification "Authentication failed for xxx@xxx.xxx. Update your server settings".  

When I click on the notification I go through the K-9 password and server settings reconfirmation but the problem recurs after a few minutes.  However, some email does appear to be getting through, so this is an intermittent error.

I've checked and reset the email account password in G Suite and confirmed that I can collect emails via www.gmail.com and on other Android/Windows platforms.  The password is correct and the account settings mirror exactly those in the other G Suite accounts, which are behaving correctly.

I've also removed the account, rebooted the phone and re-added the account and received the same error.  I've also Gone into www.gmail.com and signed out of all other web sessions.  The G Suite settings are enabled for less secure apps.  Oh, and I ran teh Recreate Data option in K-9.

Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K-9 should collect mail

### Actual behavior
I get an intermittent authentication error on one of my email accounts

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.206

Android version: Android 7.0 on a stock unrooted Samsung Galaxy S7 Edge (SM-G935F)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by rancidfrog** [comment]
This happens a lot when travelling. I keep needing to connect from browser and authenticate using recovery methods. It is annoying that whenever you check email from another country to keep having to do this. It is probably a google/mail server problem. Not sure of a kind of fix, though.

**Comment by philipwhiuk** [comment]
#655 is the solution

Using an app specific password is the best you can do for now.

Given that it's G-Suite locking you out I'm not convinced there's much we can do here.
