### ISSUE TITLE
Crash on delete

### ISSUE THREAD

**Issue by GeneralFox** [k9mail/k-9#2612]
Please search to check for 
### Expected behavior
Email should be deleted and app should be working

### Actual behavior
After click on delete the app close. 

### Steps to reproduce
1. Select an email 
2. Click on basket

3. Alternatively press the mail and from contestual menu click on delete

### Environment
K-9 Mail version:
5.207
Android version:
6.0.1 OxygenOS 3.5.8
Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by philipwhiuk** [comment]
Debug logs would be awesome here.

**Comment by Segelflugpilot** [comment]
I have created some logs (i take the option in the settings) But which log i have to update?

**Comment by cketti** [comment]
Please see https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Segelflugpilot** [comment]
Maybe it is caused because of xposed. I will watch it

**Comment by cketti** [comment]
Closing this issue. Feel free to open a new issue if you can reproduce this on a stock ROM without xposed and can provide a debug log.
