### ISSUE TITLE
Add a possibility to configure SOCKS proxy for each one account

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#2619]
Please add a possibility to configure SOCKS proxy for each one account. Not a common settings for all accounts, but for a each one, like it done in Mozilla Thunderbird, for example.

**Comment by philipwhiuk** [comment]
Please follow the issue template instructions and search first

#980

**Comment by mirsamantajbakhsh** [comment]
Check my commit. But my contribution is in global settings for all accounts.

SOCKS proxy support added
#3889

**Comment by mirsamantajbakhsh** [comment]
https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/
