### ISSUE TITLE
When forwarding an email with a reply-to set, that should be included

### ISSUE THREAD

**Issue by andrewducker** [k9mail/k-9#2622]
### Expected behavior
When I forward an email with a reply-to set that should be included in the email.

### Actual behavior
The reply-to information is lost unless I go into the headers and copy/paste it out, which is frustrating and tricky.

### Steps to reproduce
1. Receive an email from a blogging site which allows reply-via-email using unique reply-to addresses
2. Forward the email to my work email, so I can reply on a computer with a proper keyboard
3. Have to copy/paste the reply-to address into the forwarded email.
4. Sadness

### Environment
K-9 Mail version: 5.206

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by andrewducker** [comment]
For instance, comments on Dreamwidth come from "null@dreamwidth.org" but you reply to a unique address such as "27209-61366-1037020-4959964-67ac5721f825c017972189e89508bd8a9c3e887e402602908035c5b5f6a5e15b@comments.dreamwidth.org" (from a known email address) to reply as yourself.

**Comment by philipwhiuk** [comment]
Forwarding does not normally preserve the From header either.

If you Reply we extract the Reply-To header correctly.

This seems like a very odd use case I'm not sure we want to support.

I suggest you use Reply which will pull out the email address for you and then you can put it wherever you like.

This is the expected behaviour.

**Comment by philipwhiuk** [comment]
The better solution here is for us to implement moving messages between accounts. Then you don't have to forward it yourself (which is ultimately the cause of your frustration - Forward is for sending an email to someone it was not originally sent to).

**Comment by andrewducker** [comment]
I'd want it in the header text of the forwarded email. (Along with the original sender, etc that's already there)

And as I'm forwarding it to myself at work, and can't get to my work email via k9 the proposed solution doesn't work.

**Comment by philipwhiuk** [comment]
I don't think it's correct to put the old Reply-To in an email when doing Forward.

I think we have an existing issue for Forward-As-Attachment which would forward the entire email including the Reply-To header.
