### ISSUE TITLE
Per-account customisation of sounds, vibration and LED lighting

### ISSUE THREAD

**Issue by NovaViper** [k9mail/k-9#2623]
Hi there. I notice one major issue about this app that I'd like to add: the ability to customization the vibration patterns, LED settings, and sound settings for each of my inboxes. Particularly the vibration, since I have other apps that have this same vibration pattern. Would appreciate if this was added! Thanks

**Comment by DFrostByte** [comment]
These settings already exist: Either long press an account then select _Account Settings_ or open the account and select _Settings_ -> _Account Settings_ from the menu. From there, adjust your settings under _Notifications_.

Based on version 5.207

**Comment by NovaViper** [comment]
@DFrostByte It doesn't let me create custom vibration patterns though. There's another feature I'd like to add and that's having the ability to set custom colors for the entire app

**Comment by cketti** [comment]
Fully custom vibration patterns is not something we plan to add to K-9 Mail.

An app like this might do the trick: https://play.google.com/store/apps/details?id=com.wbouvy.vibrationcontrol
