### ISSUE TITLE
Failure to send SMTP email

### ISSUE THREAD

**Issue by osascruz** [k9mail/k-9#2624]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Recently , I am able to receive emails, but can't send any

### Actual behavior
Sending icon keeps turning, mail is never sent.  I need to kill the app.

### Steps to reproduce
1. my personal mail server uses the following settings : 
     port 587 
     security none
    require sign in
  username/password   
2.  setup is identical to my thunderbird app on my laptop and it has no issues
3.

### Environment
K-9 Mail version:  5.206

Android version:   version 7.1

Account type (IMAP, POP3, WebDAV/Exchange):  POP3

**Comment by philipwhiuk** [comment]
What is the error message?

**Comment by AEaut** [comment]
> ( @philipwhiuk ) What is the error message?

> ( @osascruz ) Sending icon keeps turning ... I need to kill the app.

**Comment by AEaut** [comment]
@osascruz 
is that in whatever network (wifi, 3G/4G ?)
are there perhaps any special characters in your smtp password?
