### ISSUE TITLE
Something should be done about the following two things

### ISSUE THREAD

**Issue by Zero3K** [k9mail/k-9#2630]
Those two things are the high amount of Issues and Branches. Please take a look and see if the issues are valid or not and if the stale Branches could be integrated into the main Branch or not.

**Comment by xenithorb** [comment]
What two things?

**Comment by Zero3K** [comment]
I just mentioned it in my 1st post.

**Comment by cketti** [comment]
I'm sorry the way we spend our spare time doesn't result in a project that meets your standards.

**Comment by Zero3K** [comment]
Its okay. I still like the program you all have made. I hope that my actual suggestion gets implemented soon.
