### ISSUE TITLE
Punycode domain zone

### ISSUE THREAD

**Issue by lexlis** [k9mail/k-9#2632]
Please add the ability to work with domain zones located in the zone ".рф" (example 
 user@деловые-сети.рф). Now it is impossible to send a letter to a box with such a domain, it is also not possible to configure a program to work with a box in such a zone. See international domain names. https://mothereff.in/punycode

**Comment by cketti** [comment]
If it's only the domain name that is using non-ASCII characters you could send a message to `user@xn----ctbfebbvt1a7am7h.xn--p1ai`.

Still, I created issue #2633 for proper support of internationalized email.
