### ISSUE TITLE
Notifications disappear touching 1st notification

### ISSUE THREAD

**Issue by nailyk-fr** [k9mail/k-9#2641]
> Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

I tried a search but too much opened issues and my english is too bad. 

### Expected behavior
Touching 1st or other notification should not produce different result. 

### Actual behavior
While touching the upper notification they all disappear. 

### Steps to reproduce
1. Send 3 mails to a synchronized account
2. With N (lineage 14.1) (am just discovering it maybe issue is not k9) swipe to 'increase' notifications to get one message per notification instead one notification for all message. 
3. As you sent 3 mail, 3 notification should be displayed, touch the bottom one, k9 open, notification still exist for the 2 other pending mails
4. Do the same steps again but touch the upper notification, 
5. The remaining notifications disappear. 

### Environment
K-9 Mail version: 5.207 (F-Droid)
Android version: lineage-14.1-20170726-nailyk-z3dual

**Comment by philipwhiuk** [comment]
I'm reluctant to spend too much time on this unless it's reported on a stable Android build.

**Comment by nailyk-fr** [comment]
Problem seems to be solved and newer android (with new notification way).
