### ISSUE TITLE
Email order mixed up in all folders

### ISSUE THREAD

**Issue by mcost** [k9mail/k-9#2642]
I have a problem which I am not sure it is related. It has happened suddenly after upgrading K9mail a couple of releases back.

The behaviour is extremely annoying and it is putting me off K9mail altogether as it is making it unusable at least for me.

What happens is the following:

a) I send an email
b) I go into the sent folder (which hasn't been syncronized for a while)
c) The email I just sent is at the top of the sent folder (rightly so)
d) I click on the email, but I get a completely different email that was sent perhaps a few days back
e) Even if I force refresh the folder, the problem stays there, the emails are all mixed up.

Phone: Xiaomi Redmi Note 4. Android 6. Running on IMAP

K9 Mail version: 5.206

**Comment by dmcdivitt** [comment]
This has happened to me a few times. What I do is clear all messages from the account and reset it. If IMAP they can all be pulled back in again. Don't know what to do if POP3, but the account needs to be reset.

**Comment by mcost** [comment]
I did try removing the account together and even cleaning all the k9 data without success.. The problem soon comes back. 


On 17 August 2017 04:56:10 BST, dmcdivitt <notifications@github.com> wrote:
>This has happened to me a few times. What I do is clear all messages
>from the account and reset it. If IMAP they can all be pulled back in
>again. Don't know what to do if POP3, but the account needs to be
>reset.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2642#issuecomment-322962492

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
