### ISSUE TITLE
Play store version stuck at 5.206

### ISSUE THREAD

**Issue by n-6** [k9mail/k-9#2646]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
The Google Play store version should be the latest - 5.207.

### Actual behavior
The Google Play store version appears to be stuck at 5.206 for some users.

### Steps to reproduce
1.  Open https://play.google.com/store/apps/details?id=com.fsck.k9
2. Look in additional info section
3. Version is listed as 5.206. This is the same version installed on my Android devices and I am unable to force an upgrade to 5.207 through the Play Store.

### Environment
K-9 Mail version: 5.206

Android version: 7.0

A quick IRC chat with Khaytsus indicates that they are seeing 5.207.  However, I am not the only person seeing the version stuck at 5.206.  See https://android.stackexchange.com/questions/174070/google-play-store-dont-show-latest-update-for-k-9-mail.

Here is a copy-and-paste from https://play.google.com/store/apps/details?id=com.fsck.k9 on my Mac:

ADDITIONAL INFORMATION

Updated
22 March 2017
 
Installs
5,000,000 - 10,000,000
 
Current Version
5.206

**Comment by cketti** [comment]
Thanks. 5.207 was only released for alpha testers. I pushed that version to the release channel just now.

**Comment by n-6** [comment]
Fix confirmed. Google Play just notified me of the update and I've upgraded to 5.207 through the Play Store.
Thanks!
