### ISSUE TITLE
Yahoo Changed there Servers

### ISSUE THREAD

**Issue by TheTechGuy100** [k9mail/k-9#2653]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
with the current information on the site, should be able to connect to yahoo email

### Actual behavior
Due to yahoo changing there server it fails with current information provided 

### Steps to reproduce
1. go to https://k9mail.github.io/documentation/accounts/providerSettings.html
2. go to Yahoo, Yahoo supports IMAP only for fetching e-mail:
3. Follow instructions

Email not setting up because yahoo changed there server address 

Current information
IMAP Server: imap.mail.yahoo.com
    Port: 993
    Requires SSL: Yes
    Email address: Your full email address (name@domain.com)
    Password: Your account's password

Correct Information

IMAP Server: andriod.imap.mail.yahoo.com
    Port: 993
    Requires SSL: Yes
    Email address: Your full email address (name@domain.com)
    Password: Your account's password

Current information

SMTP
    Server: smtp.mail.yahoo.com
    Port: 465 or 587
    Requires SSL: Yes
    Requires authentication: Yes
    Same password as incoming: Yes

Correct Information

SMTP
    Server: andriod.smtp.mail.yahoo.com
    Port: 465 or 587
    Requires SSL: Yes
    Requires authentication: Yes
    Same password as incoming: Yes

### Environment
K-9 Mail version:5.207

Android version:7.0

Account type IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment]
https://help.yahoo.com/kb/SLN4075.html disagrees.

**Comment by njeyaakili** [comment]
Additionally, the "android." hostname addresses indicated above do not currently exist in DNS, so not possible to use them even if they were documented.

**Comment by TheTechGuy100** [comment]
What I can say on the matter is that I came to this conclusion after attempting to get my yahoo email connected to the app and it not working with the instructions provided, after working hard on this and making that small change "andriod" it worked like a champ.

**Comment by njeyaakili** [comment]
Checking again, "android.imap.mail.yahoo.com" and "android.smtp ..." are [now] in the DNS. I thought I had tried the (correct) spelling "android." last night but it is possible that I only did copy/paste so only used your (incorrect) spelling "andriod." 

The android.imap. and straight imap. versions point to the same yahoo machines, so it shouldn't matter which you use.

The android.smtp. and smtp. names (currently) point to different IPnumbers, so it is possible that you could get different interactions.

While I found references to the "android." names in  yahoo.com user forums, in my quick searching, I only found the versions without the "android." on yahoo.com documentation pages.

So, I think that this should work with or without the "android.", certainly in the case of the "imap" entry as with and without "android." points to the same yahoo machines.

**Comment by TheTechGuy100** [comment]
sounds great, love the app and happy I got my yahoo working with it again, I see the spelling error and edited it

**Comment by AlxMxlA** [comment]
Correct Information

SMTP
Server: android.smtp.mail.yahoo.com
Port: 465 or 587
Requires SSL: Yes
Requires authentication: Yes
Same password as incoming: Yes

These settings don't give the chance to send mail.

Android 6.0.1
K-9 Mail version:5.207
