### ISSUE TITLE
com.movit.platform.mail.util.log.MailException:com.fsck.k9.mail.AuthenticationFailedException: Command: *sensitive*; response: #3# [NO, LOGIN failed.]

### ISSUE THREAD

**Issue by freeyob** [k9mail/k-9#2654]
com.movit.platform.mail.util.log.MailException:com.fsck.k9.mail.AuthenticationFailedException: Command: *sensitive*; response: #3# [NO, LOGIN failed.]
Android version:
Android 7.0,level 24
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
That's not from our app. I suggest you contact the developer. Also we'd need a lot more details. On the face of it it looks like you have the wrong password.
