### ISSUE TITLE
Move buttons back to the bottom

### ISSUE THREAD

**Issue by madduck** [k9mail/k-9#2655]
I really liked the usability of having the buttons for folders and messages at the bottom of the screen. They're now at the top, and it makes one-handed use a bit harder, I find.

![buttons](https://user-images.githubusercontent.com/195073/28916289-08d5f0e2-7842-11e7-86b0-08b742b3bc40.png)

Would it be possible to make it configurable how the UI is structured?

### Environment
K-9 Mail version: 5.207 (F-Droid)

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
There's a major re-design planned which renders this entire issue moot: https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Entire%20App.png
