### ISSUE TITLE
Mixed Languages when NOT in system default language

### ISSUE THREAD

**Issue by AEaut** [k9mail/k-9#2656]
### Expected behavior
display e.g. "Next poll in 3 minutes"

### Actual behavior
displays e.g. "Next poll in 3 Minuten"
consisting of

- "Next poll" as language as set in Global (K-9) configuration (here: English)
- "in 3 Minuten" which is the system default language (here: German).

additionally, sometimes information about when the next polling will be executed is replaced by information about when the last polling has been executed, see issue #1141

![screenshot_2017-07-31-22-33-38 1](https://user-images.githubusercontent.com/30443941/28923449-6cf6de3a-785e-11e7-8bf9-db21803a1b05.png)

![screenshot_2017-07-31-22-29-47 1](https://user-images.githubusercontent.com/30443941/28923463-77553570-785e-11e7-9436-69ecdfce4892.png)

Occurs in accounts list + in folders lists (in any of the accounts).

Unlike the "past next poll issue #1141", which can temporarily be pseudofixed by closing and re-opening the app, this language-mix-thing is persistent.

### Steps to reproduce
1. Set a different than system language in Global configuration
2. Close and reopen app
3. Look at "next poll in..." information at any accounts or folders list view

### Environment
K-9 Mail version: 5.207

Android version: 4.4.2 kitkat

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by philipwhiuk** [comment]
The language issue will be 'fixed' by #2304 in the next release. #1141 covers the fact it's talking about times in the past.
