### ISSUE TITLE
Auto reply function

### ISSUE THREAD

**Issue by tigerwoods2k17** [k9mail/k-9#2658]
I dont know if this has already been requested or not, but how about having the auto reply feature? Exchange server(for example) supports it, can we enable using K9?

**Comment by philipwhiuk** [comment]
We'd need to support EWS or EAS - #606 and then implement the functionality.

In theory it's possible to modify the message in WebDAV but it's not recommended: https://blogs.msdn.microsoft.com/webdav_101/2012/10/22/how-to-get-oof-text-from-exchange-2003-using-webdav/ and there's no way to enable/disable it
