### ISSUE TITLE
Suggestion: rename "None" folder class to "Default"

### ISSUE THREAD

**Issue by grothesque** [k9mail/k-9#2660]
In K9 mail, folders can be assigned the following classes: "None" (the default), "1st" and "2nd".  It is then possible to configure whether something (e.g. polling) applies to

* "All"
* "Only 1st Class folders"
* "1st and 2nd Class folders"
* "All except 2nd CLass folders"
* "None"

Here, the last choice means not to poll any folders.

This nomenclature is more confusing than necessary, since "None" has two meaning: "no folders" and "no class assigned".  A user could easily think that choosing "None" for polling means to poll the folders whose class is "None".

This problem could be resolved easily by renaming the "None" class to the "Default" class.  This would be only an UI text modification that does not change at all how the application behaves.

**Comment by philipwhiuk** [comment]
"No Class" would be better.

I don't know what you think Default would imply.

**Comment by grothesque** [comment]
"default" would be simply the class that gets assigned by default.  What it means depends already today on how the user configures the account.  I'm proposing a rename, that does not change the behavior of the program at all.

It's a purely philosophical question whether folders that belong neither to "1st" nor to "2nd" class, do not belong to any class, or do belong to some third class.

IMHO using "none" both for "do not use any folder" and for folders tha belong to "no class" is confusing.

I think it's simpler to imagine that a folder *always* belongs to some class, either the "default" one, or "1st" or "2nd".

Then setting "poll folders" to "none" will be clear.

**Comment by philipwhiuk** [comment]
> "default" would be simply the class that gets assigned by default. What it means depends already today on how the user configures the account. I'm proposing a rename, that does not change the behavior of the program at all.

There is no Class assigned by default. If you look at the code, the meaning quickly changes to "No Class" from None

Let me explain:

Sync Setting: 1st Class
Folder 'A' Poll Sync Class: No Class (Currently 'None')

Easy to see folder A does not get polled.

Sync Setting: 1st Class
Folder 'A' Poll Sync Class: Default (Currently 'None')

Impossible to know if Folder A is polled - it won't be.

**Comment by grothesque** [comment]
Fine, "No class" is good.  I agree that someone could think that "default" means either "1st" or "2nd".  Another solution would be thus "0th class", but "no class" is better.

However, observe how you yourself mention a "sync setting" that doesn't exist.  You probably refer to the option "poll folders".  There's also no "poll sync class", just a "sync class".

**Comment by cketti** [comment]
Related: #2669
