### ISSUE TITLE
UI: clarify the meaning of class for "poll folders"

### ISSUE THREAD

**Issue by grothesque** [k9mail/k-9#2661]
In "account settings" -> "fetching mail" there is an option "Poll folders".  It can take values like "1st and 2nd Class folders" but it is not at all clear to which class this applies.  I suppose it must be the "sync class", but this is not obvious from the UI, nor from the documentation.

**Comment by philipwhiuk** [comment]
Polling is a form of sync per my comment on the other issue. I think this is mainly you not knowing what polling is honestly.
