### ISSUE TITLE
UI: clarify "sync" vs "poll"

### ISSUE THREAD

**Issue by grothesque** [k9mail/k-9#2662]
Currently, it is not at all clear how "sync" and "poll" relate to each other.  Is "sync" just a manual "poll", i.e. when the "check mail" button is pressed (It [doesn't seem so](https://groups.google.com/d/msg/k-9-mail/mdIvuYMtIlo/B9Oc5zWXM1QJ))?  If not, what is it and when does it happen?  What's the meaning of the "sync class" of a folder?  The [documentation](https://k9mail.github.io/documentation/folders.html) tells that it's the "class for synchronization purposes" but doesn't say what synchronization is.

**Comment by philipwhiuk** [comment]
Polling is a form of sync, as is manual and push. It's not complex.

**Comment by grothesque** [comment]
It's not clear to me who has been using email for 20 years and programming for 25.

So "sync" is an umbrella term for poll, push & manual check?  What is then the meaning of "sync class" given that there is also a "push class"?  Is the "sync class" only used with the "poll folders" account option?  If yes, it should be perhaps better called "poll class"?  If not, what are the other uses?

**Comment by philipwhiuk** [comment]
I believe Sync Class refers to what happens during both Poll Sync and Manual Sync, but I'll have to check the actual code.

**Comment by grothesque** [comment]
Then, if (as it seems) the account setting "poll folders" determines not only the "automatic polling" but also the "manual check", perhaps it would be clearer to rename it to "sync folders"?  However, since as you said push is also a form of sync, I think it would be clearer to keep "poll folders" and rename "sync class" to "poll class".  After all, the "manual check" is nothing else than a manually initiated poll (or isn't it?).

Thanks for discussing these issues with me.  I think that careful naming of the configuration options is crucial for clarity.
