### ISSUE TITLE
"Failed to send" notification could have "try again" button

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#2672]
It would be useful if the "Failed to send some messages" notification had a "try again" button. In virtually all cases the cause for this notification to appear is a flaky internet connection. It is the quite cumbersome to first tap the notification, which takes one to the account screen, then choose "send messages" from the overflow menu. Alternatively one could think of a option to make k9 try at least a given number of times with some delay to send messages and only then show the notification.

**Comment by philipwhiuk** [comment]
I believe it's supposed to leave the message in the Outbox and try periodically...

**Comment by cgogolin** [comment]
It does, but apparently I was never paciente enough to notice this.

I sent a message to myself with all radios off to trigger the notification. Despite beeing constantly on mobile data and connected to wifi most of the time with sync enabled, it took a little over one hour for k9 to automatically send the message again.

Maybe the timeout could be made a bit shorter or customizable?

Irrespective of that, there are situations where one wants to manually trigger a resend event, such as before leaving an area with wifi when trying to send emails with large attachments. In that case such a button would still be useful.

**Comment by philipwhiuk** [comment]
Performing a manual sync should attempt to send emails in the outbox.
