### ISSUE TITLE
App Theme Customization

### ISSUE THREAD

**Issue by NovaViper** [k9mail/k-9#2674]
Hi there. I have this one feature that would make the app experience feel more personal and customizable: the ability to customize the overall colors of the app (i.e. make the app have a more material dark theme by setting a HTML/RUB color code that is specially used for material). Would highly appreciate if this was added, Thanks!

**Comment by philipwhiuk** [comment]
We have an ongoing design project. Have you see: https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Account%20Colors%20and%20Themes.jpg ?

**Comment by NovaViper** [comment]
Sorry for not responding! And no, I didn't realize that this was already in the works. Thanks for telling me!

**Comment by cketti** [comment]
Extensive support for customizing the colors, i.e. beyond using the account color more prominently, is not planned.
