### ISSUE TITLE
Perform post-action sync more intelligently

### ISSUE THREAD

**Issue by purefct** [k9mail/k-9#2679]
I'm having difficulty figuring out a few things ...

I think this issues is covered under #857, which is unresolved
https://github.com/k9mail/k-9/issues/857#issuecomment-313555123
I'm changing from Samsung Galaxy S5 phone to S8+, and Samsung Galaxy Tab S2 to S3. The S5 uses Android 6, the other 3 are using Android 7. K-9 appears to function as expected on my S5 yet not on the other 3 devices ... I suspect my problems on my old S2 began when it upgraded to Android 7. The basic issue is that I'm not receiving my Push, I don't think Pull is working,  yet periodically I do see my new mail, just not all new mail (some accounts receive updates, other accounts do not, the receive vs do not receive is inconsistent). I see the Synching Disabled status on the 3 devices using Android 7. I have verified the K-9 Global Network setting is set to Sync Always, and I have the Android Battery optimization set to never put K-9 to sleep, and today I enabled all Permissions for K-9 (although the few I enabled did not appear to be permissions which would prevent synching). I'll watch to see if the Permissions makes a difference.

FYI, I exported my settings from my S5 and imported them into the app for my new devices, so I shouldn't have any settings variations. I did notice that my accounts were not in the same order, so that is one setting which did not transfer.

I am tweaking push/poll settings. I also would like to understand Sync and using the Empty Trash command.  Do I understand correctly the following?
- When using the Empty Trash command from the account menu, does this also trigger Poll, Push, or Both? I can see that using Empty Trash refreshes my Inbox, however I would like to avoid triggering Poll as my folders configuration is extensive. I Push about 6 folders per account, most are empty or have little activity, 30 folders total, 5 of which are very active (Inbox). I Poll about 120 folders which contain at least 1,000 emails. I have Refresh Idle set to 24 min, and Poll set to 12 hrs.
- When I use the Sync command, does it trigger Push, Poll, or both? Same issue/goal as mentioned for using the Trash command.
- If I increase the Refresh Idle, how much battery consumption do I reduce, and will this result in not receiving email immediately? It sounds like decreasing Refresh Idle doesnt solve the Android v7 Syncing Disabled issue, plus i am loathe to do this. I did it three years ago and K9 ate up my battery.
- I set my accounts to Poll ALL folders every 12 hours. While I set all my non Push folders to 2nd class, sometimes I forget to set 1st class vs 2nd class on a new folder when I create it. On my old phones I was polling every 1 hour and I am attempting to reduce battery consumption.
- In the folder settings, I see Folder Display Class, Folder Sync Class, and Folder Push Class. However, over in Account Settings for Fetch I only see options to set folder classes for Push and Poll. There is no folder class for Sync, and no explanation whether Sync is only Poll, or if it includes Push.  I would like to be able to  manually sync only Poll folders some times, and only Push folders on other times.

**Comment by philipwhiuk** [comment]
This isn't the first question on sync behaviour, I think I'll write something on the website...

**Comment by purefct** [comment]
Thanks for the clarification, I'll look forward to the Doze solution!  

I can't be certain what happens when I use the Empty Trash command. I notice that after I use it, my Inbox appears to refresh. Since I am not certain what may or may not have changed in the other folders (Other than Trash and Inbox), and usually no other folder has changes (except maybe Sent, if I can remember to watch it) I simply wanted to verify if the Empty Trash command did something different than the Sync command. OK so Sync causes an account-wide Poll of subscribed folders, I'll refrain from using it since Polling every 12 hrs is sufficient for the folders I Poll. 

Maybe Empty Trash causes the account to be properly active and thus the Push gets triggered? You are thinking there is no Poll nor Sync triggered by the Empty Trash command? That would be fine, I like to ensure my Trash folder is empty and if it triggers a Push because I made the account active, that will suffice until the Doze issue is resolved :)
