### ISSUE TITLE
Add option to disable "encrypted but not signed" warning

### ISSUE THREAD

**Issue by dkess** [k9mail/k-9#2681]
I use a mail service that encrypts incoming plaintext mail with my public key. Since this service doesn't sign the mail, I get an annoying "security warning" message saying that the email was encrypted but not signed, which I have to manually dismiss. This is bad UI design-- I would much prefer an indicator in the corner that warns against this. Alternatively, an option could be added to disable showing this warning.

![screenshot_20170814-123147](https://user-images.githubusercontent.com/749522/29288382-63d3fbe8-80ed-11e7-93a3-903533c105eb.png)

**Comment by philipwhiuk** [comment]
Duplicate of #2286
