### ISSUE TITLE
Error decrypting base64 email

### ISSUE THREAD

**Issue by knoy** [k9mail/k-9#2688]
Hello,

As you may know BlackBerry is a popular choice for mobile phones sending PGP email. However K-9 Mail seems unable to decrypt the email from many BlackBerry devices. K-9 Mail can process the email but doesn't detect it as a PGP-encrypted message and simply shows an 'unencrypted' email with the body being a base64-encoded string. When manually decoded the string is revealed to be a properly-formatted ASCII-armored PGP message.

I've posted an example email here demonstrating the problem:

```
Return-Path: <sender@blackberryserver.com>
Delivered-To: recipient@linuxserver.com
Received: from [127.0.0.1] (localhost [127.0.0.1])
        (using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
        (No client certificate requested)
        by linuxserver.com (Postfix) with ESMTPS id 63CF25C0505
        for <recipient@linuxserver.com>; Fri,  4 Mar 2016 13:12:41 -0800 (PST)/
Received: from [127.0.0.1] (localhost [127.0.0.1])
 BESX-MX01.besx.local ([123.123.123.123]) with mapi id
 14.03.0266.001; Fri, 4 Mar 2016 13:11:38 -0800/
From: Sender <sender@blackberryserver.com>
To: "'recipient@linuxserver.com'" <recipient@linuxserver.com>
Subject:
Thread-Index: AdF2WnBiFOdwF3uXTvC0LnZSWM9zjQ==
Date: Fri, 4 Mar 2016 21:11:37 +0000
Message-ID: <8D3319D2415C5B4E926FB84072925041527BB61E@BESX-MX01.besx.local>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
MIME-Version: 1.0

DQotLS0tLUJFR0lOIFBHUCBNRVNTQUdFLS0tLS0NClZlcnNpb246IFJlc2VhcmNoIEluIE1vdGlv
biAxLjANCg0Kd2NGTUEvT2l3MlV2aEZGR0FSQUFpQzdnaGZHNUIrRXBtNEpOcFpsS1pwbzNjQ3hW
[... base64 encoded message removed for confidentiality .. ]
```

The body of the message I've truncated is a plain-text base64 encoded string that when decoded is a properly formatted ASCII-armored PGP message.

If you have any questions please let me know I'd be happy to help.

Cheers,
Kelaghn

**Comment by Valodim** [comment]
Thanks for the detailed bug report! I'll look into it

**Comment by nuntius35** [comment]
Possibly same as [#2479](https://github.com/k9mail/k-9/issues/2479)?

**Comment by knoy** [comment]
Not the same issue at all. No encryption error is being shown, K9 simply fails to decode the message at all and renders it as a block of base64 text

**Comment by Valodim** [comment]
I looked into the code, and I do think that base64 encoded pgp/inline *should* work.

I tested your case as follows: I took a pgp/inline mail with content-type text/plain, added a `Content-Transfer-Encoding: base64` header, and base64 encoded the body. This was decrypted correctly. I then replaced the entire header with the one you pasted here (leaving the b64 body untouched), and that too, worked. I noticed there is an extra newline at the beginning of the b64 encoded data you pasted above, so I added that and it still decrypted correctly.

There must be something going on in the base64 encoded body, or something else entirely. Can you send a full email like this to me? Either write a new one in the affected way, or just forward including the b64 (I won't be able to decrypt it, obviously :) )

Thanks for the thorough bug report! :+1:

**Comment by cketti** [comment]
Requested information missing. We'll re-open this issue once a message exhibiting the problem is provided.
