### ISSUE TITLE
Gmail sign : password error..less secure apps alert

### ISSUE THREAD

**Issue by k9bala** [k9mail/k-9#2691]
I noted its already reported by peoples

Is there any fix is going to be provided by k9mail dev team other than app pasword enabled in gmail.

Thx.

**Comment by cketti** [comment]
This is bug tracker, not a discussion forum. Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by Valodim** [comment]
(related note, xoauth2 is already in the works. sorry for the delay)
