### ISSUE TITLE
Sending mail fails with Android 8.0 (certificate errors)

### ISSUE THREAD

**Issue by akpm00** [k9mail/k-9#2723]
Attempting to send mail is failing since upgrading my Pixel to Android 8.0 (Oreo).

I get notifications with "Failed to send some messages SSLHandshakeException: Connection closed by peer" and "Certificate error for linux-foundation  Check your server settings".

I freshly installed K-@ mail and it's doing the same thing.

SMTP server: mail.linuxfoundation.org
Security: STARTTLS
Port: 587
Require Sign-in: Y
Username: ....
Authentication: Normal password

### Environment
K-9 Mail version: 5.207

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP (but receive works OK)

**Comment by philipwhiuk** [comment]
Oreo removed SSLv3 and a whole bunch of ciphers. `mail.linuxfoundation.org` closes the connection because there's no common cipher you both support.

Specifically for example if you connect using:

`openssl s_client -connect mail.linuxfoundation.org:25 -starttls smtp`

You find the server prefers (and so believes is it's best cipher) 

```
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
```

Android calls this: `TLS_DHE_RSA_WITH_AES_256_CBC_SHA`

And it is present in API v9-25.

In v26 DHE ciphers have been removed in favour of ECDHE.

`mail.linuxfoundation.org` should upgrade the server to support newer ciphers.

**Comment by philipwhiuk** [comment]
The annoying thing is we don't get told why the connection closes - there's no dialog in TLS to say 'I don't support any of your ciphers'. So it's going to be really difficult to display a better message - we can add 'Server closed connection' but that doesn't really help much.

**Comment by ArchangeGabriel** [comment]
@philipwhiuk Do you know where I can found ciphers list per Android version, and especially supported EC for ECDHE ciphers?

**Comment by philipwhiuk** [comment]
@ArchangeGabriel https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

**Comment by ArchangeGabriel** [comment]
@philipwhiuk Thanks, but this is not exactly what I’m looking for (as a matter of fact I’m aware of this page and should have mentioned that). I would have liked a version stating the cipher list for each Android version (a bit like SSL Labs does —https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=6.0&key=129 and https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=7.0&key=139 for instance—, except they do it for WebView which does not have the same things as Android). Of course this can be calculated from this page, but if someone had done it before that would be great. ;)

Also, I’m especially interested in EC curves (and x25519 above anything else), and I can’t find any information on whether Oreo changed anything w.r.t. that (my most accurate/up-to-date information is https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0).

**Comment by mricon** [comment]
To record this here for others -- if you have postfix 2.6 or 2.7, make sure you turn on ECDHE support by setting `smtpd_tls_eecdh_grade = strong` in your main.cf. Otherwise smtpd will never list ECDHE even if there is support for it in openssl.
