### ISSUE TITLE
Migrations should not depend on the Account/LocalStore/Folder/Message classes

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#2730]
`MigrationTo55` (and possibly others) currently uses the `LocalStore` to fetch folders to fetch messages to build the full text search system. This is broken because it means you can't modify the structure of (for example) the folders table - if you do, `MigrationTo55` will fail because the `LocalStore` (which uses the post-migrated structure) will try to run on the pre-migrated structure. 

It's more leg work (and may involve some code duplication), but migrations should really avoid using any `Local` classes. In fact the `MigrationsHelper` probably should be deleted and anything that uses it reworked.

### Expected behavior
I can modify the Local Store SQL statements and add a migration step to update the structure

### Actual behavior
The migration fails on MigrationTo55

**Comment by philipwhiuk** [comment]
I've more or less unpicked some of this for my changes. But I'm not sure I'll cover it all.

**Comment by Valodim** [comment]
For the case of building the FTS table, it probably makes more sense to have a "rebuild all FTS" mechanism that just always works on the current db structure. Nothing in the migration will depend on presence of the FTS tables, and this is a task that should be done in the background anyways.

**Comment by cketti** [comment]
With the removal of some old migrations (#4648) we're now in a much better state. Migrations only reference `Account`, which shouldn't be much of a problem. If we remove a property from `Account` we can probably also remove or simplify any migrations that accessed this property.
