### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by mboyden** [k9mail/k-9#2732]
Enhancement Request: Full(er) Rich Text Editing

### Expected behavior
I would love to have a more full-featured Rich-Text editor, ala the paid version of K-@ Mail (which is of course based on K-9, my go to generally). 

### Actual behavior
I can't do much formatting beyond basic text formatting. No lists, headings, blockquote, tables or other such.

### Steps to reproduce
Use the editor and try and cut and past a list or similar. It doesn't hold the formatting. Interestingly the app shows text formatted and sent quite well, just not in the editing section.

### Environment
K-9 Mail version: 5.207 Latest (but in all versions)

Android version: 7.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP and POP3

**Comment by philipwhiuk** [comment]
Duplicate of #1745
