### ISSUE TITLE
[5.207] Sent mail appears in both Sent and Trash folders, sometimes doubled

### ISSUE THREAD

**Issue by rancidfrog** [k9mail/k-9#2736]
I was checking 'Sent' folder and I have 2 recently sent mails appearing twice. Also, checked on server (outlook website), and indeed 2 copies of both mail appears.
So it appears that mail has been sent twice, will make sure with recipient and update.
In addition, sent mail also appears in 'Trash' folder.

So, there is a couple of issues with sending mail and drafts.

IMAP: imap-mail.outlook.com 
SMTP: smtp-mail.outlook.com

- All sent mail appears in 'Sent' folder and 'Trash' folder.
Which might mean it saves mail, sends mail, moving/creating a copy in Sent folder, and then deletes a copy which creates a copy in Trash folder?
Sent mail should only be in Sent folder not in both Sent and Trash folder.
- Some mail are being sent twice, (2 copies in Sent folder, 1 copy in Trash)
This might be linked to Drafts or when switching out of app and back to compose, somewhere along the line 2 links to mail are being created and sent?      

UPDATE:
For some reason I have some sent mail appearing twice in Sent folder and twice in Trash folder.
After refreshing trash folder some of the sent mail now are appearing twice in Trash as well.
Syncing with server issue?
Strange, I never noticed this issue before.
I used to use primarily pop3 and I do not think I came across this.
Now, even drafts appear twice in Trash after being deleted.
- I tested it by creating a mail draft. 
- Refreshing Draft folder
- Deleting mail draft
- refresh Trash folder
- deleted draft now appears twice in Trash folder
So, is it a server syncing issue?
 
I think it is a server syncing issue. After mail is sent, a copy is moved to both Sent folder and Trash folder locally (still an issue). And when you refresh folders, somehow it does not realize message is same locally and server, so downloads recently synced message again?

EDIT:
This issue might be related to #2705

Still happens on latest 5.300 pre-release:
![](https://i.imgur.com/a17XErL.png)

**Comment by rancidfrog** [comment]
Is there a way to disable sent mail from being copied to both trash and sent folders?

**Comment by rancidfrog** [comment]
Any updates on sent mails appearing twice on sent folder?

**Comment by rancidfrog** [comment]
Strange it happens on outlook account but not in gmail account.

**Comment by rancidfrog** [comment]
This is due to Outlook changing Message ID.
Scouring, I might have found something useful:
https://stackoverflow.com/a/19359193
```
I had a similar problem when I used Amazon SES as my SMTP server, It over-rode my Javamail Message-ID and replaced it with its own. A short and simple solution would be to send a randomly generated UID in the reference header ( Reference header is not usually over-written by most Email service providers) :-

Something like this : email.setHeader("References", reference);where reference header is like this : reference = UUID.randomUUID().toString()+"@email.abcd.com"

For more detail on Reference header, see this : http://cr.yp.to/immhf/thread.html


```
 https://stackoverflow.com/questions/19320086/how-to-match-replied-emails-to-the-sent-invitationsjava-mail

The added reference might be in body, though:
https://stackoverflow.com/a/19380017 

But,
More of a workaround outlooks negligence than a fix  
Using reference, dev can make sure message was sent. Therefore, there is no need to copy message again to sent folder, as you can check against reference for message.

**Comment by cketti** [comment]
See #2261 and #3598
