### ISSUE TITLE
Predictive text while entering addresses

### ISSUE THREAD

**Issue by Grey-1** [k9mail/k-9#2740]
Up to a few days ago, when I entered an address in a destination field (such a To:), predictive text was active. Now it no longer works. It is turned on and it works fine when entering the message itself and even the Subject line, but not for addresses. 

### Environment
K-9 Mail version: 5.208

Android version: 7.0 Build NRD90M G930W8VLU2BQH1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
WFM. Have you fiddled around with your Contacts app / permissions at all - we populate the autocomplete based on contacts.

**Comment by Grey-1** [comment]
Sorry, I should have mentioned that. Extracting appropriate entries from contacts works just fine. It is only predictive text that fails (that is the line of typically three options directly above the keyboard (or at least, that is where it shows up on my phone).

I've attached two screen shots, one entering a string into the To line. An entry from Contacts is displayed, but no predictive text. The second is entering this same screen into the Subject line with several predictive text offers. Up until a week or two ago, predictive text did work on the To line.

![entering to](https://user-images.githubusercontent.com/19366838/30303623-5336e4f2-9737-11e7-889a-3a3e627eb4cb.png)
![entering subject](https://user-images.githubusercontent.com/19366838/30303622-5336ba7c-9737-11e7-93ea-b67f48209252.png)

**Comment by cketti** [comment]
That's the standard behavior for input fields that take email addresses. It's the same in e.g. the Gmail app.

**Comment by Grey-1** [comment]
But that is was not the behavior several days ago. I only added that contact entry when predictive text stopped offering it as an option.

**Comment by philipwhiuk** [comment]
I wonder if it's possible to look for normal autocomplete options and add them to the list...
