### ISSUE TITLE
Reply icon missing in email view

### ISSUE THREAD

**Issue by janru** [k9mail/k-9#2742]
### Expected behavior
In full screen single email view, there should be a reply icon.

### Actual behavior
With so called setting "display size"  (dpi of screen) set to small (everything gets smaller) there is no reply icon as you can see on the screenshot.
![img_20170908_103803](https://user-images.githubusercontent.com/5803281/30203264-d6517270-9481-11e7-905b-1a5a0948c4dd.jpg)

### Steps to reproduce
1. Set display size to small (possible with lineageos) 
2. view email
3. there is no reply icon
4. set display size to normal, the icon appears

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
The action moves to the overflow menu because there's deemed not enough space.

The plan is to rework the screen anyway (you can see the current plan in https://github.com/k9mail/k-9-design/ ).
