### ISSUE TITLE
add a config option to control whether or not prompt to include a copy of the message(s) being replied to.

### ISSUE THREAD

**Issue by 257** [k9mail/k-9#2759]
### Expected behavior
add config option akin to what mutt has here:
http://www.mutt.org/doc/manual/#include

### Actual behavior
feature missing

### Steps to reproduce
N/A

### Environment
K-9 Mail version: * versions

Android version: * versions

Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by philipwhiuk** [comment]
Account Settings -> Sending mail -> Quote message when replying.

**Comment by 257** [comment]
not the same, the one you're pointing out is a doubleoption, mutt's is a quadoption. for example, if set to ask-yes, it will _ask_ on every rely whether or not to include the original message but also by default will include. so the doubleoption in k9 is just yes/no options; this ticket is for ask-yes/ask-no. see here for more explanation of what quadoption is:
[mutt-users archive](https://www.mail-archive.com/mutt-users@mutt.org/msg01994.html)
