### ISSUE TITLE
Problems sending some messages via SMTP

### ISSUE THREAD

**Issue by roybatty2019** [k9mail/k-9#2760]
An important customer (my wife!) has an issue when sending some messages from K-9.

She is using a Samsung Tablet with the latest version (no newer version available via the Google Play store) of K-9. (If necessary I can get exact version info. for K-9 / Android when I am back at home - on a business trip.)

Newly composed messages are sent to a Postfix SMTP server. Usually this works perfectly, however occasionally a message remains in the outbox and is not sent. There is no obvious feedback from K-9 as to why.

On investigation it appears that the issue often occurs when the message has a large number of recipients i.e. in the To or Cc fields. Messages that are sent to just a few recipients (e.g. 2 .. 5) are generally sent without any problem.

I don't see any configuration setting (e.g. anti spam/UCE) on the Postfix server side that would cause this. 

What I have noticed in the log messages is that for these failed messages, Postfix considers the SMTP session to have terminated abnormally. When a session ends abnormally, Postfix logs some additional status/statistics information. For example:
`Sep 11 18:28:26 dna postfix/submission/smtpd[14316]: disconnect from p2E545E40.dip0.t-ipconnect.de[46.84.94.64] ehlo=2 starttls=1 auth=1 mail=1 rcpt=17/18 quit=1 unknown=0/1 commands=23/25
Sep 11 18:28:49 dna postfix/submission/smtpd[14316]: disconnect from p2E545E40.dip0.t-ipconnect.de[46.84.94.64] ehlo=2 starttls=1 auth=1 mail=1 rcpt=21/22 quit=1 unknown=0/1 commands=27/29
Sep 11 18:32:43 dna postfix/submission/smtpd[23066]: disconnect from p2E545E40.dip0.t-ipconnect.de[46.84.94.64] ehlo=2 starttls=1 auth=1 mail=1 rcpt=21/22 quit=1 unknown=0/1 commands=27/29
Sep 11 18:34:34 dna postfix/submission/smtpd[19958]: disconnect from p2E545E40.dip0.t-ipconnect.de[46.84.94.64] ehlo=2 starttls=1 auth=1 mail=1 rcpt=21/22 quit=1 unknown=0/1 commands=27/29
`
The "action=X/Y" counts indicate something abnormal happened: "X" is the count of good commands/actions, while "Y" is the total count. I noticed that in each instance there are two bad commands, one bad recipient and one unknown action. Could it be that longer recipient/to/cc lists/arguments are getting truncated or corrupted? Or is it possible that one of the recipient addresses sent by K-9 is misinterpreted as a command by Postfix?

The recipients addresses are selected from the devices contacts database via the K-9 UI and are apparently considered OK by K-9 at the time the message is being composed. 

FYI, normal (successful) sessions are logged as follows:
`Sep 12 00:54:17 dna postfix/submission/smtpd[8327]: disconnect from p2E545E40.dip0.t-ipconnect.de[46.84.94.64] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Sep 12 09:20:48 dna postfix/submission/smtpd[14362]: disconnect from p2E545FEE.dip0.t-ipconnect.de[46.84.95.238] ehlo=2 starttls=1 auth=1 mail=1 rcpt=16 data=1 quit=1 commands=23
Sep 12 21:13:43 dna postfix/submission/smtpd[27650]: disconnect from p2E545FEE.dip0.t-ipconnect.de[46.84.95.238] ehlo=2 starttls=1 auth=1 mail=1 rcpt=3 data=1 quit=1 commands=10
`
I also use K-9 (on a different device) to the same server and have not had this problem, but I typically  send any individual message to only a limited number of addresses.

I have enabled Postfix debug logging, but the changing client IP address is making it difficult to catch the issue.

I didn't find any similar defects reported in the tracking database.

**Comment by cketti** [comment]
Probably caused by #822
