### ISSUE TITLE
saved draft mail looses text on opening again

### ISSUE THREAD

**Issue by itsbrody** [k9mail/k-9#2761]
### Expected behavior
sometimes I write mails in several steps. in between I save this as draft. in the drawer I see the draft including the text, 
![screenshot_2017-09-13-08-30-19](https://user-images.githubusercontent.com/19346144/30365182-392ca5a2-9867-11e7-9da8-b0f828c87124.png)
but when I open it again for editing the text has gone away. 
![screenshot_2017-09-13-08-30-33](https://user-images.githubusercontent.com/19346144/30365181-392bda96-9867-11e7-899d-3e3804440c1a.png)
### Actual behavior
the draft should be loaded completely into the editor again. 
Might be that it is loaded, but not shown?

### Steps to reproduce
1. write a new e-mail
2. safe as draft and check, if it is in the remote draft drawer of the account
3. leave drawer, go into drawer, see mail in list and open to edit.

### Environment
K-9 Mail version: 5.2.0.8

Android version: 4.2.2

Account type (IMAP):

**Comment by anodosian** [comment]
Confirmed steps and behavior with
K9 version: 5.208
Android: 7.1.2
Account type: IMAP

Additionally, I can see the text of a draft email if I tap-hold the draft and tap "Forward".

**Comment by johnyradio** [comment]
I experienced same issue.

**Comment by cketti** [comment]
See #2581
