### ISSUE TITLE
does not replace or update k-9 accounts widget

### ISSUE THREAD

**Issue by kr1shna-opensource** [k9mail/k-9#2762]
upgraded from 5.207 to 5.300
does not update or replace my existing k-9 accounts widget

**Comment by cketti** [comment]
What do you mean by "does not update"? If it's still showing the old icon that's probably due to some caching in your launcher.

**Comment by kr1shna-opensource** [comment]
i meant replace old widget

clear cache in app manager
it does not replace old widget on home screen

android 5.1
lyf flame 3 [ ls-4001 ]

**Comment by cketti** [comment]
I'm still not sure what the issue is. But it can probably be solved by removing the widget and creating a putting a new instance on the home screen.
