### ISSUE TITLE
Do want "show only unread" so I can easily browse folders with mails like reports

### ISSUE THREAD

**Issue by kworr** [k9mail/k-9#2764]
### Expected behavior
Good solution would be enabling filtering all <-> unread/starred via pinching/zooming. As a BlackBerry user I like how it's done on BlackBerry Hub — you are just pinching mail list and all unread messages are hidden, you zoom to get them all back.

Same can be done for folders all <-> have unread/1st class/except 2nd class. You know, I have a few dozens of 'em…

### Actual behavior
I can't find how I can select only unread messages and how can I switch between them easily. There's a sorting, but when you page through emails you can't be sure that you ain't already in the "read" space.

### Environment
K-9 Mail version:
5.208

Android version:
4.3

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Tap on the unread count in the folder list.
