### ISSUE TITLE
Aplication error closes app

### ISSUE THREAD

**Issue by asparcao** [k9mail/k-9#2771]
### Expected behavior
When click on the name of an account, should go to the folders of that account

### Actual behavior
When you click on the name of an account, the applicarion closes

### Steps to reproduce
1. Import settings of an account
2. As always, the import doesnt import the password of the incoming and outgoing servers
3. Click on the folder icon of that account
4. Go to account configuration
5. Include passwords for incoming and outgoing servers
6. Go to k9mail principal screen (where the accounts are listed)
7. Click on the name of the account
8. The application closes
9. If you click on the folder icon, then it works right

### Environment
K-9 Mail version: 5.208

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): doesnt matter

**Comment by asparcao** [comment]
I discovered this:
- when you import settings of an account, the account appears without password and NOT activated
- when you click on the name of the account imported, you are asked for the password of the incoming server
- if you cancel that and click on the folder icon of that account, then you can access the configuration of that account and include the passwords
- after that, looks like the account is still NOT active
- so, if I click in the account name, the application closes, and also, if I keep pressing and I get the menu, I get the option "Activate", and if I click the app also closes

Then, it looks like the account is not activated because at the first there is no password. If you insert the password the way I said, the account keeps not activated and there is no way to activate it because of the error.

**Comment by philipwhiuk** [comment]
Fixed by #2712
