### ISSUE TITLE
Issue with bullet list shows <![if !supportLists]>·         <![endif]>

### ISSUE THREAD

**Issue by Vkay144** [k9mail/k-9#2775]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by Vkay144** [comment]
Instead of bullet list it shows  <![if !supportLists]>· <![endif]>.

Expect to see bullet list successfully.

Steps to reproduce :
1.Send an email from outlook using bullet= "."
2 receive email in K-9
3. See the issue.

K-9 Mail Version: 5.208
Android version 6.0.1
Account type = IMAP

**Comment by Vkay144** [comment]
Instead of bullet list it shows  <![if !supportLists]>· <![endif]>.

Expect to see bullet list successfully.

Steps to reproduce :
1.Send an email from outlook using bullet= "."
2 receive email in K-9
3. See the issue.

K-9 Mail Version: 5.208
Android version 6.0.1
Account type = IMAP

**Comment by cketti** [comment]
Duplicate of #2559

**Comment by Vkay144** [comment]
Though you classify as duplicate of #2559 in which it says it will be fixed in next release but the issue is still reproducible in 5.2.0.8 which is 2 release above the one reported in #2559 which was on 5.2.0.6. Please review

**Comment by philipwhiuk** [comment]
@Vkay144 by next release I meant next stable - i.e. 5.400
