### ISSUE TITLE
SSL handshake fail with latest version

### ISSUE THREAD

**Issue by vamanea** [k9mail/k-9#2778]
Starting with version v5.208 k9 fails to connect to my IMAP server over TLS. Previous versions worked fine with my key setup and strict cipher list.

Now the logs from the dovecot IMAP server are:
```
dovecot: imap-login: Debug: SSL: elliptic curve secp384r1 will be used for ECDH and ECDHE key exchanges
dovecot: imap-login: Debug: SSL: elliptic curve secp384r1 will be used for ECDH and ECDHE key exchanges
dovecot: imap-login: Debug: SSL: where=0x10, ret=1: before/accept initialization []
dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: before/accept initialization []
dovecot: imap-login: Warning: SSL alert: where=0x4008, ret=552: fatal handshake failure []
dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: error []
dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: error []
dovecot: imap-login: Debug: SSL alert: close notify []
dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=, lip=, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher, session=<0R4PMHlZJABdahq1>

```
### Environment
K-9 Mail version:
5.208, 5.300
Android version:
7
Account type (IMAP, POP3, WebDAV/Exchange):
Dovecot IMAP

**Comment by ArchangeGabriel** [comment]
When you say Android 7, is that 7.0 or 7.1? Because https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0

**Comment by vamanea** [comment]
Right, I also recently received a update to Android **7.0** and I suppose they are related. Google decided not to support my particular EC curve any more.

Thanks for the info.

**Comment by cketti** [comment]
In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
