### ISSUE TITLE
Changing the mailbox separators

### ISSUE THREAD

**Issue by dilyanpalauzov** [k9mail/k-9#2779]
On my server I changed the mailbox selarator from . to \.  How can I tell k9 to use from now on the new names, e.g. instead of the subscribed folder Abc.Def to use Abd\Def ?

**Comment by cketti** [comment]
You don't. Refresh the folder list to fetch the new folders and discard the cached copies of the old ones.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
