### ISSUE TITLE
Support for "pure" IMAP workflow

### ISSUE THREAD

**Issue by richardb64** [k9mail/k-9#2782]
I'm not sure whether this is an enhancement request, or if I've just not found the right combination of existing settings to do it yet, but here goes...

I'm one of those people who actually _like_ the IMAP way of handling deleted messages.  When I delete a message, I want it to be shown as deleted in some way, but stay put in the same folder.  I do _not_ want it to be moved (or appear to be moved) into any other folder, real or virtual.  I also don't want anything _ever_ to be lost permanently unless I ask for a folder to be expunged by some explicit action.

All of the desktop and webmail IMAP clients I've used allow the above (even Outlook!).  I've tried a few Android clients, and K-9 comes closest by a long way, which is great, but there are still some oddities that I don't seem to be able to get around:
* Some of the important options (eg. turning off all automatic expunging) only seem to become available once I've connected, or they need to be set on a per-folder basis - which risks K-9 expunging flagged messages before I've had a chance to tell it not to.
* The only option for handling the \Deleted flag seems to be to hide the message altogether.  This means I can never *un*delete a message without firing up a desktop client.  Flexible undeleting is one of the main advantages of having "delete" and "expunge" as separate actions.  "Undo" is not the same, as it's not always the most recently deleted message that needs to be restored.
* Some of the documentation talks about "deleting" messages on the server, but it's not always clear whether that means "flag as \Deleted" or "delete permanently" (ie. flag and immediately expunge), which are two very different things!
* It's not clear what happens when a message is moved to another folder: I want it to be copied to the destination and flagged as \Deleted in the source, but _not_ expunged (and it must certainly not have the side-effect of expunging _all_ deleted messages in the source folder, which I've seen happen with some clients!).

I do understand that there are legitimate questions over the correct way to handle expunging when multiple clients are connected to the same folder (eg. if client A flags a message \Deleted, and client B then expunges, the message could be lost even if client A was expecting it just to be flagged).  But I'm happy to live with those constraints, because in practice I'm only going to be actively using one client at a time, and UID EXPUNGE (does K-9 support that?) would mostly solve the problem anyway.

The main thing that perhaps needs code development is a way of showing \Deleted messages other than by hiding them altogether - whether that's with "crossed out" text, or some other kind of indication.  But I could probably even live without that, if I can find the right combination of settings to guarantee that K-9 never issues EXPUNGE unless I hit an expunge button!

**Comment by philipwhiuk** [comment]
There's a setting called 'Erase deleted messages on server' which controls the Expunge on Poll behaviour.

But we should implement a way of telling what messages have been deleted but not expunged. Strikethrough seems best to me.

**Comment by philipwhiuk** [comment]
Also there's probably some improvements to documentation and account setup we can do in terms of selecting a workflow.

**Comment by richardb64** [comment]
That sounds like a plan!

I have "Erase deleted messages on server" set to "Manually" on a test account, and it seems to do the right thing.

If all of the per-server settings could be set _before_ K-9 even attempts to connect to the server, that would address the safety issue.  The problem is that most settings - including the dangerous "Erase deleted..." setting - only appear later, once K-9 has already polled (and expunged) the inbox.  Maybe all settings could just default to their "safest" values, and then the initial setup UI might not even need to be changed.  I can hack it by deliberately giving fake user+password details, letting K-9 try (and fail) to connect, changing the "Erase" setting, and then correcting the details later... but it would be good not to have to!

Some of the confusion is that the wording of the settings doesn't consistently use IMAP terminology, though perhaps people using POP3 or WebDAV/Exchange have different expectations.  Can "erase" be reworded "expunge", perhaps (at least when dealing with an IMAP account)?  Similarly, "When I delete a message" has the option "Delete from server", and "Sync server deletions" says "Remove messages when deleted on server", but I wasn't sure (without experimenting) what "delete", "remove" and "deleted" actually mean in each case!  Elsewhere I've seen "Compact account", which I guess means "expunge all folders".

**Comment by lucafavatella** [comment]
> UID EXPUNGE (does K-9 support that?)

I understand K-9 does not support UID EXPUNGE currently. (I understand the relevant specs are [1](https://tools.ietf.org/html/rfc4315#section-2.1) and [2](https://tools.ietf.org/html/rfc4549#section-4.2.4)).

It appears PR #2701 (under review, stalled) attempts to plant UID EXPUNGE.

**Comment by lucafavatella** [comment]
I understand this ticket can be described fully by the following items. Maybe this ticket shall be closed and separate smaller tickets shall be opened?

* [ ] Ensure all account settings and all workflows default to never expunge (IMAP term) folder unless explicitly instructed by the user to do so;

  * This includes defaulting account setting "Erase deleted messages on server" to "Manual";
    * It looks to me this means changing `EXPUNGE_IMMEDIATELY` to `EXPUNGE_MANUALLY` in the following locations: [1](https://github.com/k9mail/k-9/blob/5.300/k9mail/src/main/java/com/fsck/k9/preferences/AccountSettings.java#L79) [2](https://github.com/k9mail/k-9/blob/5.300/k9mail/src/main/java/com/fsck/k9/Account.java#L201) [3](https://github.com/k9mail/k-9/blob/5.300/k9mail/src/main/java/com/fsck/k9/Account.java#L299) [4](https://github.com/k9mail/k-9/blob/5.300/k9mail/src/main/java/com/fsck/k9/Account.java#L407);
    * Not sure which test shall be modified / added for this. Ideally the automated test would setup an IMAP server with an account with a message flagged as deleted and one not flagged as deleted, then start the Android emulator and install K-9 apk, then somehow via UI simulate creation of account, wait on UI to notify completed initial synchronization (not sure what kind of event the app notifies of), then check that the IMAP server still has both messages (both the one flagged as deleted and the other one). Of course this test shall fail before applying the code change.

* [ ] Safe concurrent expunge (IMAP term) of folder (see IMAP command UID EXPUNGE);

* [ ] Optionally show IMAP messages with `\Deleted` flag;
  * E.g. by strikethrough.

* [ ] Enable the user to undelete showed IMAP message with `\Deleted` flag;

* [ ] Revisit app strings and documentation for terminology related to message deletion.

**Comment by philipwhiuk** [comment]
We can just do PR's to close individual bits and pieces. It's helpful to have tickets tracking larger pieces of functionality that collectively explaining why the individual PRs are needed. In more complex issue trackers this would be called an epic (milestones almost work for this but they tend to be even larger in scope).

And the problem, is until we have all the sub tasks done we **don't** know it's sufficient. So this helps us ensure we are actually going to support a pure IMAP workflow in the app once we finish the issues you list.

**Comment by richardb64** [comment]
I wondered if there's been any progress on this?  I've seen the [Modernize IMAP](../projects/4) project, which seems to have quite a bit of action, and I've noticed that UID EXPUNGE has now been implemented (#2701), but the other specific tasks identified by @lucafavatella above don't seem to have made their way into issues (or PRs) yet.  Are they in the pipeline somewhere and have just not been linked back to this ticket?

**Comment by richardb64** [comment]
@cketti - why have you closed this? I've seen a few possibly-related issues under the "Modernize IMAP" project get worked on over the last couple of years (notably UID EXPUNGE), but the main issues, such as supporting the core IMAP "mark as deleted" functionality in the UI, don't seem to have been looked at yet.

**Comment by cketti** [comment]
@richardb64: I don't want to expose the "IMAP way" of deleting messages to users. Most other clients don't. My goal for K-9 Mail is to make it an easy to use email client that should work for most people.

It sounds like you want an email client that supports all IMAP features. It is very unlikely K-9 Mail will ever be this client.

**Comment by richardb64** [comment]
That's very disappointing.  I am not asking for "all" IMAP features, merely to be able to use some existing basic features properly.  K-9 Mail already supports \Deleted and explicit expunge (because that is the way IMAP works) - there just needs to be an option to expose them in the UI rather than hide them behind the simplistic "Trash" idiom.  There also needs to be a way of setting up a new account with _safe_ defaults.  Neither of these seem to be huge pieces of work, and there even seem to have been volunteers to do it.

It may be true that "most other clients don't" expose the IMAP way of deleting messages - but only in the Android world.  In the desktop world, most clients which support IMAP *do* provide "mark as deleted" as an option, even if it isn't the default.  K-9 Mail's strength is the way in which it respects user choice, offering much more configurability than its competitors, so I hope you would want to follow that principle in this area too.
