### ISSUE TITLE
Plesse add export / import feature

### ISSUE THREAD

**Issue by oz42** [k9mail/k-9#2786]
I have found a how-to for exporting and importing settings, but apparently this feature was removed meanwhile.

**Comment by Trogel** [comment]
@oz42 There is a menu item "Settings Import & Export" in the accounts list. Or are you looking for something else?

![k-9 - settings import export](https://user-images.githubusercontent.com/22852658/30763995-4cbd92dc-9fe9-11e7-9cc1-33602b8c1d43.png)

If k-9 starts with a message or folder list, you'd need to tap on the app icon in the top left corner once or twice to get to the account list.

**Comment by cketti** [comment]
In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
