### ISSUE TITLE
Gmail : authentification blocked by Google 

### ISSUE THREAD

**Issue by PercevalIO** [k9mail/k-9#2790]
### Expected behavior
Authentification and Gmail ok

### Actual behavior
Sometimes, only when I'm not using my home WiFi (Phone network or new WiFi network), K9 will try to connect to Gmail and will not (warning icône) because it's blocked by Google. I instantely get on another mailbox Google telling me someone knows my password and a SMS from Google for the same thing. I already changed the password once in case of, but it always happen when K-9 tries to connect ; most of the time it works with no problem, but sometimes it happens. Less secure apps are allowed into Google. 
My two other accounts work perfect, and so does my Gmail account when not blocked by Google. 

### Steps to reproduce
1. Connect from GSM network or from new WiFi location. 
2. Attempt to connect to Gmail
3. It will produce (sometimes) a warning from K-9 saying authentification failure, then a mail+SMS from Google telling someone knows my password and authentification was blocked. 

### Environment
K-9 Mail version: 5.208
Oneplus 3t

Android version:
LineageOS 14.1 Snapshot 21 sept 2017 (Android 7.1.2)- Also happened in OxygenOS. 

Account type (IMAP, POP3, WebDAV/Exchange):
1 Gmail (imap, ssl) account (the buggy one) 
1 Orange.fr (imap) account
1 1&1 (imap) account

**Comment by cketti** [comment]
Please complain to Google about this behavior. There's not much K-9 Mail can do about that.

You might want to watch issue #655, though.

**Comment by glowinthedark** [comment]
It's a settings in your gmail account which you can control from https://myaccount.google.com/security —  most likely you will see this for your account:

![image](https://user-images.githubusercontent.com/48893368/56080875-d18cef80-5e06-11e9-92b0-d036301f664e.png)

Turn at your own risk, if you know what you are doing.

**Comment by AaronM04** [comment]
Why is it less secure exactly? What are the risks?

**Comment by violoncelloCH** [comment]
That's more or less just google wanting to force users to use the gmail app... If you use 2FA and an App Password for k-9 that's as secure as Googles OAuth method...

**Comment by PercevalIO** [comment]
I use the app password (that's the trashable by-application passwords, right ?) and had no problem so far. I had no more warnings from K9.
The less secure apps are required for older Google API if I'm not wrong. Google says it's less secured because their older API does not implement latest security stuff...

Le 13 avril 2019 17:45:27 GMT+02:00, "violoncello.ch" <notifications@github.com> a écrit :
>That's more or less just google wanting to force users to use the gmail
>app... If you use 2FA and an App Password for k-9 that's as secure as
>Googles OAuth method...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2790#issuecomment-482824176

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by glowinthedark** [comment]
@PercevalIO: as mentioned above the downside is that when your IP location changes Google will most likely block access via IMAP and you'll need to click the _Yes, that was me button_ from the Google's  security warning email sent to your _recovery_ email account.

**Comment by PercevalIO** [comment]
I don't have the problem anymore with my method. K-9 has its own password for Gmail, this way this is a trusted app/connection for Google. 
The only problem I have is probably 99% unrelated to K-9 : syncing works perfect in my home (wifi) network but is much less frequent when I'm on cell network or on another wifi network. I'm running latest LineageOS with lots of security and battery optmization I enabled, thus I think it does come from here. 

Le 13 avril 2019 18:19:39 GMT+02:00, glowinthedark <notifications@github.com> a écrit :
>@PercevalIO: as mentioned above the downside is that when your IP
>location changes Google will most likely block access via IMAP and
>you'll need to click the _Yes, that was me button_ from the Google's 
>security warning email sent to your _recovery_ email account.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2790#issuecomment-482830823

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by michaelerule** [comment]
Using google app passwords is not a solution. It is only available if you enable 2-step authentication with Google. This, in turn, is only available if you are able to receive a code "via text, voice call, or our mobile app". This requires giving your contact details to Google, which is not acceptable. This issue essentially breaks K-9 mail. The entire point of K-9 mail is to access Gmail on mobile. However, Google has decided to peg every access over mobile data or a new wifi network as a "new device", so in practice there is no way to access mail via K-9 on a mobile device. It's difficult to interpret this as anything other than "Google decides to break open standards for fun and profit, because there's nobody who can stop them".

**Comment by glowinthedark** [comment]
@michaelerule: you don't need to disclose any of your private info if you use the OTP authentication codes. If you don't want to use the google authenticator app then any OTP app will do, for example [AndOTP](https://f-droid.org/en/packages/org.shadowice.flocke.andotp/) which is open-source and which you can build yourself from source after you examine the code.

**Comment by michaelerule** [comment]
> @michaelerule: you don't need to disclose any of your private info if you use the OTP authentication codes. If you don't want to use the google authenticator app then any OTP app will do, for example [AndOTP](https://f-droid.org/en/packages/org.shadowice.flocke.andotp/) which is open-source and which you can build yourself from source after you examine the code.

I see! I think this is a bit beyond my competencies at present, I will search for a simple tutorial; The existing instructions from Google certainly gave no indication that this was a supported possibility.

**Comment by glowinthedark** [comment]
AndOTP is a drop-in replacement for google authenticator, i see no need for a tutorial. You can install the either from f-droid or google play, and then use it to scan the QR code that google shows you when you enable 2FA. That's all there is to it. The big advantage AndOTP has over google authenticator is that it will also let you see the original encryption seed which will let you port the key to any other OTP client. Here is an example of the simplest possible OTP client in just a few lines of code: https://github.com/susam/mintotp/blob/master/mintotp.py
