### ISSUE TITLE
Push stopped working

### ISSUE THREAD

**Issue by davidak** [k9mail/k-9#2792]
### Expected behavior

a notification should happen instantly when a mail is sent to a folder (like INBOX) with Push support enabled.

### Actual behavior

Mails get only manually synced. No Push mails received.

### Steps to reproduce
1. sent mail to account with push enabled
2. ???
3. nothing happens (only manual sync works)

### Environment
K-9 Mail version: 5.208 (worked in 5.206)

Android version: 5.1 (Fairphone Open OS 17.04.0)

Account type: IMAP

**Comment by davidak** [comment]
I removed the app, installed version 5.206, configured the account again and push works. Then i did an update to 5.208 and push still works.

No idea why it stopped working. Has anyone similar behavior or can we close this issue?

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
