### ISSUE TITLE
Feature Request: Privacy settings, dont transmit local interface IP as hello to the SMTP server

### ISSUE THREAD

**Issue by treaki** [k9mail/k-9#2793]
Hi,

please add a privacy setting next to "Remove K-9 User-Agent from mail headers" like:

"Report always localhost as SMTP hello argument"

The issue i face is that K-9 mail is reporting the local network IP while sending mails over wifi that lookes like that in headers:

``Received: from hostnamexyz ([aaa.bbb.ccc.ddd] helo=[192.168.xxx.yyy])``

But i dont want that my local ip (192.168.xxx.yyy) is revealed. In Thunderbird i can accomplish this by setting 
``mail.smtpserver.default.hello_argument`` to ``localhost``, please add a option for K-9 mail to.

Thanks in advance

**Comment by philipwhiuk** [comment]
Relevant code is here. 

https://github.com/k9mail/k-9/blob/b63ed688380d72d58d18a7dba5dc9fec9f3fe381/k9mail-library/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.java#L366

I'm not sure if it should be separate to the user agent setting or not. Maybe we should have an overarching Privacy setting and then optional more detailed config below that.

**Comment by axel-h** [comment]
Input from #3070: Please consider adding an option to hide the fully qualified host name also, not just the IP. For privacy reason I don't was that name to be revealed. But there a security aspect to this also, as many home routers choose a network name that allows deducing the type of the router, e.g. `fritz.box` is the default if a FritzBox is used. Once you know the router's type, you can narrow down the attacks to use...

**Comment by ArchangeGabriel** [comment]
@philipwhiuk Yes, that would make sense I think. Most people wanting one would likely want both.

@axel-h Sorry about having not thought of this in #3070. The better option still remains modifying the server side, but we should do our best already on K-9 side.
