### ISSUE TITLE
Wrong SMTP headers for initial sync of new account

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#2800]
### Expected behavior
New smartphone. Copied K9 settings from old phone. Entered server passwords and performed initial sync.

All msgs from IMAP account synched. But for exactly four emails incomplete SMTP headers are parsed. Leading to receiving date to current time of sync. Not values from IMAP.

Reproducible, after a Reset Data in K9 always same issue.

Old phone with K9 has CORRECT date/time etc. Headers. Also Roundcube Webmail shows all correct. Also GMail App shows all correct, so IMHO for sure a K9 bug 

### Actual behavior
always the same (4) emails have wrong headers, are set to current date/time 

### Steps to reproduce
Described above.

### Environment
K-9 Mail version: 5.208

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, Dovecot, own VPS

**Comment by cketti** [comment]
See #1356
