### ISSUE TITLE
Make it easier to find folders with unread messages.

### ISSUE THREAD

**Issue by dseomn** [k9mail/k-9#2806]
### Expected behavior
It would be nice if there were some easy way to see folders that have unread messages. Possibly a new option in "folders to display" to show only folders with unread messages, or an option to sort the folder list so that the folders with unread mail appear above other folders.

### Actual behavior
With hundreds of folders and unread mail in only a few, it's hard to quickly see where there's unread mail. (I think there's a way to see all unread messages, but I'd rather see folders first so I can decide which to look at.)

### Environment
K-9 Mail version: 5.208

Android version: Android 7.1.2 / LineageOS 14.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is not a use case I want to optimize for. In my opinion unread indicators are already visible enough. You could also enable "show in top group" for busy folders.
