### ISSUE TITLE
Wrap long words, file path and URL in messages

### ISSUE THREAD

**Issue by Symbian9** [k9mail/k-9#2821]
### Expected behavior
Use multiple lines to show long url links & long words inside messages.

### Actual behavior
Currently 

### Steps to reproduce
1. Set "Auto-fit message" ON
2. Open message that include long word, file path or URL
  * `Some message with URL as https://github.com/k9mail/k-9/releases/tag/5.300`
  * `Some message with path info as D:/folder1/folder2/folder3/folder4/folder5/folder6/folder7/file.extension`
  * `Some message that include SomeLongWordWithoutSpaceInSingleLine`
3. Message text size too tiny, because try fit all message according one long word.

### Environment
K-9 Mail version: 5.3.0

Android version: 7.0

**Comment by cketti** [comment]
See #2821

**Comment by Symbian9** [comment]
> See #2821

@cketti, You link this issue.

**Comment by cketti** [comment]
Sorry, see #3172.
