### ISSUE TITLE
moving multiple emails fails

### ISSUE THREAD

**Issue by kaipoeritz** [k9mail/k-9#2825]
### Expected behavior
Selecting multiple mails and moving them to another folder, should move all selected mails.

### Actual behavior
Selecting multiple mails and moving them to another folder, moves only one (the first selected) mail.

### Steps to reproduce
1. select more than 1 mail
2. move to a folder of choice
3. see how only one mail got moved

### Environment
K-9 Mail version: 

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by Trogel** [comment]
I tried it, but using an IMAP account, I can reproduce this issue neither with K-9 5.208 on Android 7.1.2/LineageOS 14.1 nor with K-9's current head on Android 7.0. @kaipoeritz What is your environment?
