### ISSUE TITLE
copying text from mails seems to be broken

### ISSUE THREAD

**Issue by vanitasvitae** [k9mail/k-9#2826]
### Expected behavior
When copying text, I should be able to paste the content into another app.

### Actual behavior
The clipboard seems to stay untouched by k9.

### Steps to reproduce
1. open a mail
2. select and copy some text
3. try to paste it somewhere else

### Environment
K-9 Mail version: 5.208

Android version: CopperheadOS 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by philipwhiuk** [comment]
This is a problem with your custom OS.

**Comment by pauledd** [comment]
Why is this a problem with an OS? I have LineageOS and every other App is able to long-press select and copy text to another App except K9... so is this an OS issue too? 
I recently installed K9 and received an pacel tracking id via mail. I cant copy it to my supplier tracking APP. But on the same device and OS I can copy and paste it if I send this mail to another mail-client (gmx).

**Comment by vanitasvitae** [comment]
@pauledd you can read the copperheadOS issue i referenced ;)

**Comment by philipwhiuk** [comment]
I've updated the issue title to make it clearer what the problem was/is.

**Comment by pauledd** [comment]
thanks, I do not really get behind the issue. I am not using copperheadOS. Why is my other mail-app gmx-mail able to copy/paste text to other apps and K9 not? Are they using something else than this WebView thing?

**Comment by philipwhiuk** [comment]
You're using LineageOS. Presumably they have the same issue with WebView and presumably GMX-mail doesn't use WebView. But I have no idea what GMX Mail does.

Unfortunately it's not really practical to test on non-Android  so as a rule we don't support bugs that are specific to non-Android platforms.

**Comment by pauledd** [comment]
Ok, thanks for the explanation :)
