### ISSUE TITLE
Feature request: Option to cleanly interrupt syncing

### ISSUE THREAD

**Issue by mark-orion** [k9mail/k-9#2828]
I would like to request a feature to cleanly interrupt all syncing  so that it then can be started cleanly again. I am using manual synchronization a lot and it often happens that sync gets stuck when the internet connection gets interrupted - for example in a train. Restarting sync at the moment has a lot of strange side effects like endlessly spinning or multiple sync notifications. "Killing" K9 through the list all running apps menu does not always solve these problems.

**Comment by philipwhiuk** [comment]
That's an ugly fix.

Instead we should fix the timeouts - see #2652

**Comment by cketti** [comment]
In very rare cases a "stop sync" button would be nice. However, I agree it shouldn't be a thing most users need.

**Comment by deutrino** [comment]
If it's easier & quicker to implement than fixing the still-unfixed problems, maybe it would be good to put this in regardless.
