### ISSUE TITLE
'Syncing Disabled' in Note 8 can't be resolved

### ISSUE THREAD

**Issue by Molson082** [k9mail/k-9#2830]
### Expected behavior
Tell us what should happen
Should Poll for new mail as timed in settings

### Actual behavior
Tell us what happens instead
Syncing Disabled label appears and polling can only be done manually

### Steps to reproduce
1. Open mail app and syncing is disabled
2.
3.

### Environment
K-9 Mail version:
5.208

Android version:
7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
POP3 & Exchange

**Comment by ya8sa** [comment]
Hi,
Please set rather than never  in global setting - network - background sync.
Also if changed polling interval in account settimg,  kill K9 app, then restart K9 again.
The imterval setting will take effect.

k9:5.300 beta
Andoroid:   7.0
Sincerely

**Comment by Molson082** [comment]
Set rather than never?  What does that mean?  It's set to auto-sync now.

By kill do you mean force stop?

On October 10, 2017 8:42:56 PM PDT, Ysms <notifications@github.com> wrote:
>Hi,
>Please set rather than never  in global setting - network - background
>sync.
>Also if changed polling interval in account settimg,  kill K9 app, then
>restart K9 again.
>The imterval setting will take effect.
>
>k9:5.300 beta
>Andoroid:   7.0
>Sincerely 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2830#issuecomment-335673476

-- 
Sent from my Samsung Galaxy Note 8

**Comment by ya8sa** [comment]
soryy, miss typing.
correcr is other than Never.
try always.
Yes, force stop.

**Comment by Molson082** [comment]
OK, I'll try it and let you know what happens.  Thank you!

**Comment by Molson082** [comment]
The issue did not get resolved.  Sorry to say I'll likely have to change mail clients.  Very disappointed. 

On October 10, 2017 9:00:07 PM PDT, Ysms <notifications@github.com> wrote:
>soryy, miss typing.
>correcr is other than Never.
>try always.
>Yes, force stop.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2830#issuecomment-335675630

-- 
Sent from my Samsung Galaxy Note 8

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
