### ISSUE TITLE
Cant access iCloud (.mac/.me/.icloud) on IMAP. Suspected SSL/TLS config issue...

### ISSUE THREAD

**Issue by WalkerYYJ** [k9mail/k-9#2831]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Actual behavior
When configuring K9 for iCloud email getting no joy on IMAP. Receiving (unable to connect) error.

### Steps to reproduce
1. Config IMAP to imap.mail.me.com
2. Security to SSL/TLS port 993
3. Enter log/pass
4. Error

-If I change the username or pass I get a user/pass error
-I can connect on SMPT with STARTTLS and 597 but same error if I go to SSL/TLS (would also be nice to fix)
-Works fine on a standard Windows "Em Client" if I select "SSL/TLS on special port (legacy)" 993 but not on standard SSL/TLS 993. 
Suspect apple is doing something stupid with SSL/TLS standards...

### Environment
K-9 Mail version:
5.208
Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by gdt** [comment]
I just saw this work for someone, with ssl/tls, 993, and the above imap server.  But, username was just the user part, not including @icloud.com, and password was an app-specific password.  It was pesky and needed a bunch of fiddling before working, though, so I suspect something is not right.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
