### ISSUE TITLE
Missing email - IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by Cippolippo** [k9mail/k-9#2832]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Read ALL my emails

### Actual behavior
Some emails are not visible (...and thus readable ).

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.208

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by jyn514** [comment]
Please give more detail. What emails aren't you seeing? Are they in different folders? Are you using unified inbox? When did you see an IndexOutOfBoundsException?
