### ISSUE TITLE
K9 does neither encrypt nor sign mails using OpenKeychain while decrypting works

### ISSUE THREAD

**Issue by derburner** [k9mail/k-9#2833]
I setup K9 to use OpenKeychain. I verified that OpenKeychain can encrypt and decrypt messages using my key. I can decrypt mails in K9. But when I compose an enrypted mail it is not signed and not encrypted at all. Icons are all green indicating that the keys are available for encryption. Even if I chose only to sign the mail it is not signed after I send it. I tested by mailing myself and a friend.

### Expected behavior
When composing a mail with encryption I expect it to be encrypted.

### Actual behavior
The composed mail is not encrypted. No error can be seen on logcat.

### Steps to reproduce
1. Compose a message to myself with encryption enabled

### Environment
K-9 Mail version: 5.300

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Is the message sent unencrypted or not at all?

**Comment by derburner** [comment]
The message is sent but not encrypted although it should have been signed and encrypted.

Am 14. Oktober 2017 18:07:56 MESZ schrieb cketti <notifications@github.com>:

**Comment by derburner** [comment]
Solved with the newest version of K9. I did not choose the key to use for my account. In the old version I did not get a pop up indicating this. Now I got one and after selecting the key, everything works just fine.

Am 14. Oktober 2017 18:07:56 MESZ schrieb cketti <notifications@github.com>:
