### ISSUE TITLE
Bring back the old Icon

### ISSUE THREAD

**Issue by D0ve** [k9mail/k-9#2834]
Please, bring back the old Icon of the app, or make it optional to choose in settings.
Sorry, but the new one qite ugly(((.   Imo in that case the simplier isn't better....
Many thanks in advance.

**Comment by cketti** [comment]
No. But K-9 Mail is open source. You could change the icon yourself or find/pay someone to build it with the old icon.

**Comment by D0ve** [comment]
I really loved the old icon! It was balanced by colors and was really nice....
may be possible to make an option to choose an icon... or even an icons pack for all icons?

**Comment by gcalzo** [comment]
> No. But K-9 Mail is open source. You could change the icon yourself or find/pay someone to build it with the old icon.

Wow, what about a poll? Or is it really so hard to include both and let the user decide which one to use?
I saw such option on many apps...
