### ISSUE TITLE
Unified Sent Mail box

### ISSUE THREAD

**Issue by maxpierini** [k9mail/k-9#2835]
Is there a way to have a Unified Sent Mail box to see all sent messages from all accounts?
Thank you.

### Environment
K-9 Mail version:
5.208

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
all IMAP accounts

**Comment by cketti** [comment]
That's not a supported feature. 

Also, this is not a support forum. For general question please use the [mailing list](http://groups.google.com/group/k-9-mail).
