### ISSUE TITLE
Crashing on replying & jumping from "to" box

### ISSUE THREAD

**Issue by k9protection** [k9mail/k-9#2836]
### Expected behavior
When I click the "to" field, I should be able to input an email address.

When I click reply, I should be able to type a reply without the software crashing.

### Actual behavior
When composing a new email, filling in the email address in the "to" box sometimes has the cursor jump in to the body field and in to the middle of my signature. If I have got to the point of a period in the mail address, clicking back in the field means the only way to complete the address is to delete it and re-type it.

The second fault, when replying to a message and typing, the software will randomly crash whilst typing.

### Environment
K-9 Mail version: 5.208

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
Please create one issue per bug and include as much information as possible. Ideally, detailed instruction on how to reproduce the issues.
For these problems the brand/type of device might be relevant.
For the crash please also try to record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
