### ISSUE TITLE
language settings frequently lost

### ISSUE THREAD

**Issue by 4001982248998** [k9mail/k-9#2838]
I was very happy to discover that K9Mail supports Esperanto, and immediately switched settings. Unfortunately, its interface language frequently switches back by itself to the system language (German). It will automatically and immediately switch back to Esperanto by going to Settings/Global Settings, but I have to do this at least daily. 

### Expected behavior
The selected language should stay as it is.

### Actual behavior
Language switches to system settings, until I enter the global settings menu again. I do not have to set it to Esperanto, just going to the settings menu is enough to switch back.

### Steps to reproduce
1. Switch language to Esperanto
2. Use the app, use the phone…
3. Open the app somewhen later, and see that the language is set back to system language

### Environment
K-9 Mail version: 5.300

Android version: 7.1.2; LineageOS 14.1 2017-10-09

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This shouldn't happen. Maybe it's a corrupt database and the setting isn't properly persisted. Try uninstalling, then reinstalling.

**Comment by 4001982248998** [comment]
Thanks! Tried to: Couldn't uninstall via F-Droid (F. crashed), uninstalled via app settings. Trying to reinstall would again crash F-Droid (other apps work fine for some strange reason). Downloaded and installed apk from the web page. Result: K9M version is slightly below thsn before and Esperanto not in the list of available languages.
Now waiting for F-Droid to let me update K9M...


Am 14. Oktober 2017 17:12:01 MESZ schrieb cketti <notifications@github.com>:
>This shouldn't happen. Maybe it's a corrupt database and the setting
>isn't properly persisted. Try uninstalling, then reinstalling.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2838#issuecomment-336641156

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cketti** [comment]
Sounds like a lot of things are going wrong on your device. Seems to me the custom ROM can be blamed for a lot of this. Closing this issue until it can be reproduced on a stock ROM.
