### ISSUE TITLE
Wrong default mail servers for yahoo.de

### ISSUE THREAD

**Issue by vog** [k9mail/k-9#2840]
### Expected behavior
IMAP server: imap.mail.yahoo.com
SMTP server: smtp.mail.yahoo.com

### Actual behavior
IMAP server: imap.yahoo.de
SMTP server: smtp.yahoo.de

### Steps to reproduce
1. Add email account
2. Enter an email address that ends with `@yahoo.de`

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
There's no special support for yahoo.de at all. Prepending `imap.` and `smtp.` to the domain part of the email address is the default behavior for unsupported domains/manual setup.

But please feel free to create a pull request that adds the correct server settings to https://github.com/k9mail/k-9/blob/master/k9mail/src/main/res/xml/providers.xml

**Comment by vog** [comment]
Done.
