### ISSUE TITLE
Use storage access framework to write files

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#2844]
Using the [storage access framework](https://developer.android.com/guide/topics/providers/document-provider.html) we will be able to support all kinds of removable storage supported by Android (e.g. secondary external storage like an SD card). Additionally users can save files to supported cloud storage providers without us having to add special support for them ourselves.
This will also allow us to drop the permission to write to external storage (once we drop support for moving the message database to external storage).

Requesting access to a directory and persistable permissions aren't that well supported. But I don't mind getting rid of the default path to save attachments to and prompt the user every time.

**Comment by Trogel** [comment]
So, is your idea basically to do an [`ACTION_CREATE_DOCUMENT`](https://developer.android.com/reference/android/content/Intent.html#ACTION_CREATE_DOCUMENT) whenever an attachment (or something else?) shall be written?

**Comment by cketti** [comment]
Yes. However, that's only available on API 19+. So there needs to be some fallback code for older versions. Preferably, we'd display a UI to select a folder and filename similar to what the system UI looks like on newer Android versions.

**Comment by Trogel** [comment]
That sounds reasonable. May I give it a try?

**Comment by cketti** [comment]
I'd wait until we switch to using AppCompat for Material Design. Otherwise half of the fallback UI might have to be rewritten.
But you could start with the `ACTION_CREATE_DOCUMENT` part and keep the current behavior for old Android versions.

**Comment by maidik** [comment]
So this is still an open bug?

**Comment by fat-tire** [comment]
I think you'd probably want to use Intent.ACTION_OPEN_DOCUMENT_TREE, supported starting in Lollipop, to select the target directory, yeah?

**Comment by pellajl** [comment]
Can't believe writing to an external SD Card hasn't been sorted out yet.
