### ISSUE TITLE
Saving as draft erases the To header

### ISSUE THREAD

**Issue by hgmichna** [k9mail/k-9#2853]
I consider this a low-priority problem, but it would be nice to have it fixed.

### Expected behavior
When I compose an email including a recipient in the To header and save it as a draft, the To header should remain unchanged.

### Actual behavior
The To header disappears when saving the composed email as a draft into the Drafts folder. I have not checked whether Cc and Bcc headers are also erased, but it seems likely.

I have done the same with another email client (Thunderbird on a Windows computer). The problem is not there, so it is apparently not the mail server doing this.

### Steps to reproduce
1. Compose an email.
2. Add a recipient address in the To field.
3. Save as draft.
4. Re-open the draft and check the To header.

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2 (LineageOS 14.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by almesh** [comment]
بتاريخ ٢٢‏/١٠‏/٢٠١٧ ١٠:٥٨ ص، كتب "hgmichna" <notifications@github.com>:

**Comment by aucklander** [comment]
I noticed this too on pixel 8.1, I usually switch apps and saves to draft in the background and i noticed the To field was empty, but some email accounts work normally.

**Comment by cketti** [comment]
Seems to be fixed in `master`.
