### ISSUE TITLE
Sent Mails Box does not synchronize from server to phone

### ISSUE THREAD

**Issue by Aquassarim** [k9mail/k-9#2855]
Hello, I face an issue while synchronizing my Sent mails box ; the sent mails do not synchronize. The mails I send from the phone appear, but the mail I send from other devices (PC...) does not appear on the phone, even after synchronizing. I have set up the Sent mails folder as class 1 folder but this does not change the behaviour.
Does anyone have an idea to solve the problem ? I expect it is not a configuration problem but I have tried many settings without success and I have no ideas anymore...
Thank you for help !

### Expected behavior
When asking for synchronizing the Sent mails, the new mails stored on the server should appear in K-9 mail on the phone.

### Actual behavior
No mail is synchronized. The Sent mails box only contains the mails sent by the phone.

### Steps to reproduce
1. Go to Sent mails
2. Synchronize
3. Nothing happens

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2 LineageOS

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
