### ISSUE TITLE
Add the ability to edit IMAP notes

### ISSUE THREAD

**Issue by read-more** [k9mail/k-9#2857]
Some servers offer the creation and storage of dedicated IMAP notes. I think that it will be useful if **K-9 Mail** can edit, save and delete those.

### Expected behavior
The user is able to successfully create new and view/modify/delete existing notes in their IMAP account. Since the credentials are usually(always?) the same as the regular account, no further setup should be necessary from UX perspective.

### Actual behavior
The user is able to only **read** existing notes without further setup in **K-9 Mail**.

### Steps to reproduce
1. find a provider that supports IMAP notes
2. create a new such note via a dedicated app or through the web interface of your account
3. try to edit it and save your changes inside of *K-9 Mail* – **nothing happens** (ideally, should save it)

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We have no plans to add special support for this. You can create "notes" by composing a message and saving it as a draft instead of sending it.
