### ISSUE TITLE
Removes html elements from drafts

### ISSUE THREAD

**Issue by jyn514** [k9mail/k-9#2859]
### Expected behavior
I draft a message in another email client, using html elements such as bullet lists and hyperlinks. I open the message in K-9 mail, and all the elements remain, and look approximately the same.

### Actual behavior
All html elements are converted to plaintext on opening, and the draft is immediately overwritten with the plaintext.

### Steps to reproduce
1. Write draft which includes bulletpoints in thunderbird/gmail/outlook
2. Save draft
3. Open in K-9 mail

### Environment
K-9 Mail version: 5.208

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
K-9 Mail currently doesn't support rich text editing. See #1745

**Comment by jyn514** [comment]
@cketti, no, this is a seperate problem. K-9 mail will discard any rich text already present, convert it to plain text, then overwrite the rich text draft without any warning. There's no warning to the user and no option to convert or not.

**Comment by cketti** [comment]
There are lots of issues with saving drafts. The underlying issue is probably one of those.

Losing HTML is a result of saving a new draft. Like I said, K-9 Mail doesn't support rich text editing. It will create the HTML part from the plain text you see when opening a draft in K-9 Mail.
