### ISSUE TITLE
'Dark' theme gives almost invisible subject text on 'long press' quick action listing

### ISSUE THREAD

**Issue by jimimaseye** [k9mail/k-9#2882]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
The text should be visible - I would suggest White as with the rest of the text.

### Actual behavior
It is displayed as black text - against the dark grey background it is almost invisible.

### Steps to reproduce
1.  Set THEME to 'dark
2.  Long press on an individual message to bring up the quick-select action menu

The same think happens when choosing 'settings' from the menu - the 'settings' sub menu is displayed with near invisible heading of "settings"

See screenshot

![image](https://user-images.githubusercontent.com/15649182/32149420-2129668e-bcfc-11e7-95a4-7184f00156b0.png)

### Environment
K-9 Mail version:  5.208

Android version:  7.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment]
This seems to no longer be an issue in `master`.
