### ISSUE TITLE
Issue with text shown in an email

### ISSUE THREAD

**Issue by Zero3K** [k9mail/k-9#2889]
### Expected behavior
Strike-Through'd and Underlined Text should be shown as such.

### Actual behavior
It appears as regular styled text.

### Steps to reproduce
1. Send an email with either one or both types of text to your e-mail address using an email client that can make that kind of text.
2. View the email you sent in K9-Mail.

### Environment
K-9 Mail version: 5.302

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We are removing HTML tags that are not whitelisted. However, `<u>` and `<string>` are not removed. Can you provide the HTML source of a message that doesn't display correctly?

**Comment by Zero3K** [comment]
Here's the source of the email in question:

https://p.teknik.io/ua99d

**Comment by jyn514** [comment]
K9 doesn't support html editing; see issue
https://github.com/k9mail/k-9/issues/1745 and the closed issue
https://github.com/k9mail/k-9/issues/2859. Please read the instructions
and search for similar issues next time.

**Comment by Zero3K** [comment]
I'm not wanting to make an email with those styles, I just want to view one that has them.

**Comment by Zero3K** [comment]
So, I guess it won't be fixed then?

**Comment by cketti** [comment]
Thanks. The linked pull request adds the `<ins>` and `<del>` tags to the whitelist.

**Comment by Zero3K** [comment]
You're welcome. Now to wait for someone to build a version that includes the mentioned fix.
