### ISSUE TITLE
Syncing although syncing is disabled everywhere

### ISSUE THREAD

**Issue by ginsterbusch** [k9mail/k-9#2890]
I've got the opposte problem of all other folks: It seems to be impossible to *DISABLE syncing*. 
This happens on my new Honor 9 with Android 7 - didnt have these issues on my One Plus X both with Android 5 nor 6.

### Expected behavior
I disabled syncing - as far as I know - in all places, starting from the account, globally and even folder-wise. I'm using k9 as a secondary client, which only becomes important as primary one when I'm elsewhere AND still expecting work mails.

I prefer control, ie. manual fetching, over auto-sync and having my smartphone screen clustered with mail notifications (notifications behaviour under Android 7 seems generally to be awkwardly off aka exploding; a total PITA to me)

My guess is its a Doze-related issue, but then there must have been an extreme change between Android 6 and 7, because on 6 everything worked as expected (as noted above).

### Actual behavior
When you "turn on" your phone (actually just turn on the screen), you are most of the time being greeted by new mail notifications. So the disabled sync seems to be ignored.

### Steps to reproduce
1. Set up a nifty IMAP account on a regular host, including encryption etc.
2. Install k9
3. Disable synchronization EVERYWHERE, including singular IMAP folders.

### Environment
K-9 Mail version: 5.302

Android version: 7.0 (EMUI 5.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
You probably have polling disabled, but not push. You can disable all background activity by setting 'Global settings > Network > Background sync' to 'Never'.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support issues like this.
