### ISSUE TITLE
Delete on Server

### ISSUE THREAD

**Issue by luc-chivas** [k9mail/k-9#2902]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When reading mail on K9, mail doesn't appears anymore on other device (POP acccount)

### Actual behavior
looks like mail are deleted from server  even with optin set to do not delete on server when deleted

### Steps to reproduce
1.open mail on K9
2.try to see the mail on my outlook account on PC
3.mail is not present

### Environment
K-9 Mail version:
5.208
Android version:5.5

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by luc-chivas** [comment]
Could you please consider my bug message as I'm not entitled to publish on the group


Best regards 
Luc
+33673396660

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
