### ISSUE TITLE
Regression [Office365] unable to connect to SMTP server

### ISSUE THREAD

**Issue by Phoscur** [k9mail/k-9#2904]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue
mhh not the first time Office365 gives trouble :/

### Expected behavior
I was and want to be able to send Emails with my standard unchanged settings.

### Actual behavior
Error: Cannot connect to server. (Unable to open connection to SMTP server.)

### Steps to reproduce
1. Create Office365 account
2. Try using official settings: smtp.office365.com:587
3. Setup could not finish

### Environment
K-9 Mail version: November 2017

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Sounds like a network issue, not like a bug in K-9 Mail.

**Comment by Phoscur** [comment]
The issue persists and is not dependent on the network.
The Error occurs on WLAN and LTE networks.
Other (non-Office365) accounts are not affected.

Please reopen!

**Comment by SwampertX** [comment]
I was able to configure the outgoing mail using the following settings, as auto-detected by Thunderbird:

incoming: `imap-mail.outlook.com, SSL/TLS`
outgoing: `smtp-mail.outlook.com, STARTTLS`

Using **K-9 Mail Version 5.403** on **Android 7.1.1**
Account type: IMAP

Please check if these settings work for other cases too.

**Comment by brobostigon** [comment]
I can confirm, that SwampertX's server settings work.
