### ISSUE TITLE
Highly nested quoting looks awful

### ISSUE THREAD

**Issue by jyn514** [k9mail/k-9#2912]
### Expected behavior
Highly nested quotes should be hidden or not indented. If message is wider than some default width, add a scrollbar.

### Actual behavior
More than half the screen is whitespace. The font size shrinks extremely small, I guess to avoid a scrollbar? [Pic.](https://user-images.githubusercontent.com/23638587/32407178-6dc222a2-c15b-11e7-9263-9898804e1109.png)

To be fair, this looks almost as bad in [Thunderbird](https://user-images.githubusercontent.com/23638587/32407174-6a5b2442-c15b-11e7-89cb-79ad1ec2e7e3.png); I guess many replies is outside of most use cases. I would like for this to be nicer, though, especially since there's so little screen space on android.

### Steps to reproduce
1. Write an email with many replies (I believe this one had about 20-30)
2. Open in K9

### Environment
K-9 Mail version: 5.208  
Android version: 7.0  
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ya8sa** [comment]
Try the setting below.
Off the auto-fit messages in the display of global setting. It is located at bottom of this setting.

**Comment by jyn514** [comment]
The font size is now a *lot* bigger which I appreciate. I guess the indentation is implemented when composing, not when viewing. Closing this issue.
