### ISSUE TITLE
OPENSSL_internal:WRONG_VERSION_NUMBER on connect to Google SMTP server 

### ISSUE THREAD

**Issue by Wandrer** [k9mail/k-9#2920]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Connecting to SMTP server to send email 

### Actual behavior
Disconnect by SMTP server with error SSL handshake aborted, ssl=0x98aba6c0: Failure in SSL library. 
OPENSSL_internal:WRONG_VERSION_NUMBER

### Steps to reproduce
1. Device with Android 6.0.1 (Sony SGP612 in my case) 
2. Connect to Google Mail account 
3. Try to send a mail 

### Environment
K-9 Mail version:
5.301 and 5.303
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP 
[k9-log.txt](https://github.com/k9mail/k-9/files/1454434/k9-log.txt)
Search for 11-08 16:13:43.774 in K9-log.txt

**Comment by cketti** [comment]
K-9 Mail is not talking to OpenSSL directly. From glancing at the log other apps seem to have the same problem. This is unlikely to be a bug in K-9 Mail.
