### ISSUE TITLE
No network connection on my school's WiFi

### ISSUE THREAD

**Issue by NovaViper** [k9mail/k-9#2923]
For some reason, I can't perform any of the network functions while I'm connected to my school's public wifi without the use of a VPN. It seems that the servers may be blocked by the school but I don't get this same issue when using Gmail

### Expected behavior
Use the network functions of K-9 Mail (retrieving email, sending email, viewing email, etc.) with no problems while connected to WiFi network and without a VPN

### Actual behavior
Gets constant network errors, saying to check my connection. Email doesn't send at all and can't retrieve email while connected to the WiFi. The features only work _with_ the VPN on

### Steps to reproduce
1. Connect my school's public WiFi connection
2. Open K-9 Mail
3. Try to retrieve mailbox from my email accounts or send email

### Environment
K-9 Mail version: 5.303
Android version: 7.0
VPN used: OpenVPN (VPNBook)

Account type (IMAP, POP3, WebDAV/Exchange): Gmail

**Comment by jyn514** [comment]
Are you sure the wifi allows external connections/your email site? Unless this works in other email clients, it's not really a K9 problem.

**Comment by NovaViper** [comment]
The Gmail client works though, both on desktop and on Android

**Comment by jyn514** [comment]
Hmm. Can you attach some logs from your phone? You would get them with [adb](https://developer.android.com/studio/command-line/adb.html) by running `adb logcat`.

**Comment by kerhac** [comment]
I would guess the gmail andoid app as well as  the Gmail webapp does not use IMAP but the [Gmail API](https://developers.google.com/gmail/api/) over https port (443). Now your school is probably blocking a wide range of ports including IMAP/SMTP/POP3. You could try to connect via telnet from within the wifi directly to the ports and see if it works.

```
telnet gmail.com 443
Trying 172.217.21.229...
Connected to gmail.com.
Escape character is '^]'.
```
```
telnet imap.gmail.com 993
Trying 64.233.184.109...
Connected to imap.gmail.com.
Escape character is '^]'.
```
If the response for both are not the same then this a networking issue and the described **Actual behavior** sounds pretty correct.

**Comment by NovaViper** [comment]
How do I use telnet?

**Comment by pshem** [comment]
@NovaViper Depending on your operating system:
* Windows - open it's command prompt (by pressing Windows, then type cmd on windows 10, or find command prompt in the list of applications)
* MacOS/Linux/BSD - open the terminal
* Android - find an application for it by typing telnet into Play Store/F-Droid. I've not done this, so I won't recommend any
* ChromeOS - proceed as on Android, or, if you have Developer mode enabled, `Ctrl + Alt + T`; then `shell`

and proceed with the commands as shown in the previous post.

**Comment by NovaViper** [comment]
Thanks for the tip! I'm actually out of school for Thanksgiving, so I got to wait until school starts next week

**Comment by NovaViper** [comment]
I can't find any working terminals that have telnet on Android, and on my computer the prompts would suddenly vanish after running each command. And with the imap connection, I ran it on my desktop and it says it "Could not open connection to the host, on port 993: Connect failed"

**Comment by NovaViper** [comment]
I finally found an app that works, and I notice that the imap connection gets refused

**Comment by kerhac** [comment]
@NovaViper If K9 cannot connect to the needed IMAP port then your described actual behaviour is correct. Why the connection is failing is probably due to the schools firewall disallowing everything but http/https. There is nothing that can be done on K9 side to resolve this issue.

btw. to check open ports I use **Port Authority** ([github](https://github.com/aaronjwood/PortAuthority) / [f-droid](https://f-droid.org/packages/com.aaronjwood.portauthority/) / [google play](https://play.google.com/store/apps/details?id=com.aaronjwood.portauthority.free))

**Comment by Djfe** [comment]
I'm fairly sure this can be closed.
Back in the day my school also blocked everything except http(s)
How to solve this: switch to your mobile network, if you really need e-mail access.
or cache more e-mails if you need access to old e-mails.

About telnet on windows: you need to install it first
it's not installed by default:
https://social.technet.microsoft.com/wiki/contents/articles/910.windows-7-enabling-telnet-client.aspx
