### ISSUE TITLE
"Always Sign, Never Encrypt" missing

### ISSUE THREAD

**Issue by 98c71be8** [k9mail/k-9#2925]
Hi,

### Expected behavior
Create a new e-mail, click on the Crypto option, be able to select "Always Sign, Never Encrypt" as described in https://k9mail.github.io/documentation/security/pgpmime_current.html 

### Actual behavior
"Always Sign, Never Encrypt" missing. See print screen

### Steps to reproduce
1. Start new e-mail
2. Add TO address - with public key abailable on OpenPGP 
3. Click on lock icon in order to display the signing/encryption options.

### Environment
K-9 Mail version: 5.208

Android version: 6.0 (guest user )
Security Patch level: 2016-08-01
OpenKeyChain: 4.7 (47001)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (GMX.COM)

Print screen:
![image](https://user-images.githubusercontent.com/32497938/32664865-2cbf8968-c63b-11e7-89d9-fac67850eac7.png)

**Comment by Valodim** [comment]
Signed-only messages have to be enabled in the settings specifically. When you do, you can set sign-only mode from the overflow menu (top right).

See also: https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html for details.
