### ISSUE TITLE
Feature Request - Randomised mail server polling times between 1 and 10 mins

### ISSUE THREAD

**Issue by piney** [k9mail/k-9#2929]
For anonymity a randomised mail server polling time option would be great.

**Comment by philipwhiuk** [comment]
In practice the polling on modern phones is dictated more by Android's sleep-wake cycles than anything else. The precision of specifying a certain number of minutes will be undone by that.

Right now I believe it means "no more often than x minutes".

So it's already not an exact interval. 

I don't feel like there's much de-anonymisation potential as a result of the current behaviour.

**Comment by cketti** [comment]
It's also not functionality I want to include in the app. I'd be fine with having an interface that third-party apps can use to trigger message synchronization, though.
