### ISSUE TITLE
[Feature Request] - Automated email Recommendation

### ISSUE THREAD

**Issue by theauditor** [k9mail/k-9#2930]
Would it be possible for us to scan emails and store all email addresses it encounters into a database. Then recommend emails as you type into To, Cc or BCc fields.

**Comment by philipwhiuk** [comment]
I think you'd want K-9 to become a proper contact provider. I'm not completely opposed to it, but it's quite a lot of work.

**Comment by theauditor** [comment]
That would be just great. But this suggestion system is a much required functionality and won't be half bad if we can do it using a incident tally table and then slowly build the contact system around.

**Comment by cketti** [comment]
Duplicate of #1006
