### ISSUE TITLE
mail password not accepted (authentication error)

### ISSUE THREAD

**Issue by sjjh** [k9mail/k-9#2932]
### Expected behavior
Entering the password, K9 fetches email from mail server

### Actual behavior
K9 displays an error message stating that the authentication went wrong and to check the server settings.

### Steps to reproduce
1. type in password and try to fetch mail...

### Environment
K-9 Mail version: 5.208

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (server at strato.de)

The password works using the web mailer and Thunderbird. The password contains letters (a-z, A-Z) and numbers (0-9), and special characters (-, _, =, &, %) and is 20 characters long.

**Comment by cketti** [comment]
What are we supposed to do with this? Unless you can provide detailed information on why authentication fails there's nothing we can do.

**Comment by sjjh** [comment]
Well, as the authentication fails only with K9, it seams reasonable for me to assume that the problem lays within the app. :) I provided you with the error message I get. If you need any further information, I'm happy to hear what would be of help for you and how to obtain it. Is there any log file anywhere that would be of any help?

**Comment by jerryn70** [comment]
@sjjh
1,  it is gmail account?
2, are you using 2 factor authentication ?

**Comment by sjjh** [comment]
@jerryn70
re 1) As stated in the initial post, the mailbox is from strato.de (a German web hosting company)
re 2) No, AFAIK they don't offer it

**Comment by sjjh** [comment]
Might you comment on why you closed this bug report? Are you not gonna allow this characters for passwords or at least warn the user that they use not supported characters in their passwords?

**Comment by cketti** [comment]
You only stated your password contains these characters, not that authentication works when you change your password to not include these characters. Authentication with special characters works fine for other users. I have a Strato account and can authenticate fine using a password containing special characters.
Like I said, unless you can provide detailed information on what's going on (K-9 Mail is sending X for password Y, but server is expecting Z; or works with client B sending Z) there's not much we can do.

**Comment by sjjh** [comment]
Well, I stated that the same password works with other clients. Thus I assume that the problem lays within K9.
I happily provide you with any information you need, if you tell me how I can provide them to you. :)
