### ISSUE TITLE
Compose addressing now returns results in counterintuitive order

### ISSUE THREAD

**Issue by bjweichel** [k9mail/k-9#2937]
### Expected behavior
When composing a new message, typing characters into the 'To' line should return the results most closely matching what has been typed.  E.g. typing 'me' will return a contact named 'Me' as the first result.  This correct behavior was seen in versions at least up to 5.010.

### Actual behavior
Typing 'me' into the 'To' line in the compose window instead returns a list of contacts which contain the letters 'me' in them, sorted in alphabetical order by first name.  The result is that the search term 'me' returns many results like 'Carmen', 'Douglas Elementary' and 'ADC Appointment Line' before the contact 'Me' because they have 'me' in them and their first character comes before M.  In practice I have about 10 results for 'me' above the contact actually named 'Me'!

### Steps to reproduce
1. Create a contact named Me
2. Create a contact named Carmen
3. Address an email to 'me'.
4. See 'Carmen' as the top search result rather than 'Me'.

### Environment
K-9 Mail version: 5.208

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
We search for `LIKE %queryString%` with no ordering.

Ideally we want them ordered by the Levenshtein distance from `queryString` but there's no DB support for it :(

**Comment by bjweichel** [comment]
Any idea why the behavior would have changed since 5.0 though?  It isn't an issue on that version and I have rolled back my local installation for that reason.  If it isn't clear what caused the change, why not take the results from the query and compute the Levenshtein distances for each to sort the results with?  This seems like it would be an important feature to users, it certainly is to me.  Thanks!
