### ISSUE TITLE
false google security alerts when k-9 polling gmail accounts

### ISSUE THREAD

**Issue by xalex25** [k9mail/k-9#2939]
after installing the last update for synch turn off issue, i'm getting false google security alerts when k-9 is trying to poll my gmail accounts.  this does not happen on home wifi.  this happens in areas of weak cell data signal or public wifi. k-9 still works fine on my yahoo mail accounts.

### Expected behavior
poll gmail account as normal

### Actual behavior
google shuts down connection from k-9 and i get a security alert from google.

### Steps to reproduce
1. connect to public wifi or weak cell data signal
2. poll gmail accounts

### Environment
K-9 Mail version:
5.208
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
gmail: IMAP

**Comment by cketti** [comment]
Please contact the Gmail support to find out what exactly triggers the security alert. We'd be happy to change K-9 Mail in order to avoid the security alert. I doubt there's anything we can do, though.
