### ISSUE TITLE
Some traduction issues

### ISSUE THREAD

**Issue by maxlevesque** [k9mail/k-9#2940]
Hi there,
Thanks for the good work. I've just discovered the Android version of the app.

The French traduction has some problems. I searched for "Dossier du pousser" (which is not French but is in the app) here in github but did not find it. I don't know where to look at to correct this by the standard pull requests.

**Comment by cketti** [comment]
We're using Transifex for translations. Please add your changes there. https://www.transifex.com/k-9/k9mail/
