### ISSUE TITLE
Add buttons/options for interacting with RFC 2369 header information 

### ISSUE THREAD

**Issue by nimbius** [k9mail/k-9#2943]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
k9mail should offer subscribe, help, unsubscribe and info buttons based on the presence of mailman headers in listserv emails.

### Actual behavior
gotta handle those addresses with copy and paste :T

### Steps to reproduce
1.join gentoo-test or any other mailing list
2.view mail in k9
3.profit?

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by philipwhiuk** [comment]
We kind of added List-Post a while back (although there's been some feedback on that in #2588 ).

The format is RFC standardised so we should follow the RFC (I'm sure mailman does).

**Comment by illfygli** [comment]
Came to open an issue about `List-Unsubscribe`, which is really handy, even if you don't participate in any "real" mailing lists, since semi-spam often has such a header which lets you quickly unsubscribe.
