### ISSUE TITLE
Latest version cannot work with OpenKeyChain

### ISSUE THREAD

**Issue by gjf** [k9mail/k-9#2944]
### Expected behavior
When writing new e-mail two buttons were present allowing sign or crypt the e-mail using assigned key.

### Actual behavior
No buttons at all. The key is assigned in preferences, but it is not possible to use it.

### Steps to reproduce
1. Assign a key in Preferences of e-mail box - Cryptography.
2. Try to send a signed or crypted e-mail to somebody.

### Environment
K-9 Mail version: 5.304
OpenKeyChain version: 4.7 (47001) installed from F-Droid

Android version:
Tested on Android 4.3 and 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by qrovira** [comment]
Works for me on a recent (github) build of k9 with the same version of OpenKeyChain (from google play), on Android 7.0.

**Comment by gjf** [comment]
Works what? Can you see those two buttons? Would you present a screenshot?

**Comment by cketti** [comment]
This is not a bug. The interface has changed. "Enable encryption" can be found in the overflow menu. The lock icon also shows up in the upper right corner when OpenKeychain knows the public keys for all recipients. Tapping that lock icon enables encryption.
Also, we don't support encrypting without signing; see [OpenPGP Considerations, Part II: Encrypted-Only Mails](https://k9mail.github.io/2017/01/30/OpenPGP-Considerations-Part-II.html). Signed-only emails are discouraged and support has to be enabled in settings; see [OpenPGP Considerations, Part I: Signed-Only Mails](https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html)

For further questions please use the [mailing list](http://groups.google.com/group/k-9-mail).

**Comment by gjf** [comment]
I don't really understand.
As for me I want to sign the e-mail, not encrypt it.
In this case I don't need a public key of the recipient.
So how can I do it with new interface?

**Comment by gjf** [comment]
I love to read the consideration of author - but there is a real life. I am using Thunderbird with Enigmail - and I am pretty sure they are experienced also. And they allow to sign e-mail without encryption. I love it and all me recipient also. Why I cannot use it simply because the author thinks in other way? 
Looks like I have to move back to older version unfortunately.
