### ISSUE TITLE
Wrong contact image displayed

### ISSUE THREAD

**Issue by liar666** [k9mail/k-9#2945]
Context: I do not have data on my Mobile subscription, I only access internet through Wifi at home or at work. But I often write & (attempt to) send emails while not connected. They are just put in the "sent mail" queue with an error and actually sent when I connect again.

Problem: 

- When I start typing an email in the "To" field, a list of possible completions appears.

- When NOT connected to the Internet, the first entry proposed is associated the same picture has the second entry. This is erroneous as the picture is indeed the picture of the 2nd contact, not the first one (which is associated with no picture in my contacts).
![screenshot_2017-11-22-11-14-43](https://user-images.githubusercontent.com/3216927/33123120-91041064-cf79-11e7-9352-086bab844dc6.png)

- When CONNECTED to the Internet, the behaviour is correct : the first entry is not associated to a picture, but to a default icon, whereas the 2nd entry is associated to its correct picture.
![screenshot_2017-11-22-11-14-23](https://user-images.githubusercontent.com/3216927/33123119-90e49bf8-cf79-11e7-9292-5281450d5712.png)

I've noticed that if I delete the 'm' in 'gm' I typed, then type it again, then the correct behaviour occurs...

### Environment
K-9 Mail version: 5.208
Android version: 4.4.2
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is most likely the bug that was fixed with #2743. The next stable branch (versions 5.4xx) will contain the fix.
