### ISSUE TITLE
Hotmail and outlook mails are not senting

### ISSUE THREAD

**Issue by jerryn70** [k9mail/k-9#2952]
In version 304 hotmail and outlook mails are not senting from outbox . K9 shows server error in notification area.  And when we try to move or achieve the mail then it shows, the mail is not synced with the server .

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by jerryn70** [comment]
There is no problem with version 303 with same settings. Its a bug .
