### ISSUE TITLE
Disappearing emails!

### ISSUE THREAD

**Issue by gitzRME** [k9mail/k-9#2954]
Hi, 

Something apparently changed with (my? -Elsewhere I saw that another guy reported the problem) K-9 Mail over the past several weeks. Now, when I read an email, after I read it, that email disappears from the inbox.  It’s not moved to the trash or anywhere else I can find.  It’s understandable to mark it as Read after reading, it is not ok to delete it. How do I fix this?  

Regards,

Jim G.

p.s., The Play store seems to think I am running the current version of K-9 mail, I am using version 5.208

**Comment by philipwhiuk** [comment]
Are you accidentally viewing only Unread emails in your Inbox by clicking the unread count instead of the account name / folder name?

**Comment by gitzRME** [comment]
Thank you Phillip.  While I couldn’t find an option for  clicking the unread count, I found that I had unintentionally selected an option for marking all messages as read, and once I deselected it, the problem was resolved.

 

Jim G.
