### ISSUE TITLE
did not support 163 mail 

### ISSUE THREAD

**Issue by caizhibiao** [k9mail/k-9#2956]
### Expected behavior
could load 163 inbox emails

### Actual behavior
can login 163 mail, but can not load inbox emails

### Steps to reproduce
1.input 163 account
2.login

### Environment
K-9 Mail version:
5.304
Android version:
5.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
