### ISSUE TITLE
K9 Mail forwarded an email with pic, the receiver mailbox can't display pic correctly

### ISSUE THREAD

**Issue by Movement123** [k9mail/k-9#2965]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by zhangxiaofan918** [comment]
it's inline pic?

**Comment by Movement123** [comment]
yes, inline pic

**Comment by zhangxiaofan918** [comment]
I meet same problem. I resolved by this way:
`public void setShowDownloadButton(Message message) {
        if (message.isSet(Flag.X_DOWNLOADED_FULL)) {
            mDownloadRemainder.setVisibility(View.GONE);
        } else {
            mDownloadRemainder.performClick();
        }
    }`

**Comment by Movement123** [comment]
May you understood incorrectly. 
The inline pic didn't forward with email.  The method you provided couldn't load the pic either.

**Comment by zhangxiaofan918** [comment]
I dont know why it doesn't work ,when you load message finished and it will call `mMessageView.setShowDownloadButton(message)`,then it download full mail automatically.You could racking code with debug mode.

**Comment by Movement123** [comment]
Thank you for the answer
