### ISSUE TITLE
export/import settings does not preserve order of accounts

### ISSUE THREAD

**Issue by voxspox** [k9mail/k-9#2969]
### Expected behavior
After importing settings (global, accounts, ...) the order of accounts should be restored also.

### Actual behavior
Account order is different.

### Steps to reproduce
1. Export settings on old phone
2. Import settings on new phone

### Environment
K-9 Mail version:
5.208

**Comment by aucklander** [comment]
I had this issue to, its just a random order.

**Comment by cketti** [comment]
This probably only requires switching from `HashSet` to `LinkedHashSet` and `HashMap` to `LinkedHashMap` at the appropriate places.

**Comment by grubdragon** [comment]
I'd like to work on this

**Comment by grubdragon** [comment]
Hey guys! Actually new here. Anybody who can guide me around?

**Comment by grubdragon** [comment]
I'd like to work on this issue!
