### ISSUE TITLE
pinch to zoom (again)

### ISSUE THREAD

**Issue by tentaurus** [k9mail/k-9#2970]
### Expected behavior
pinch to zoom within an email body

### Actual behavior
nothing happens

### Steps to reproduce
1. open email
2. pinch to zoom

### Environment
K-9 Mail version: 5.208

Android version: 7,0

**Comment by cketti** [comment]
Works for me. You'll have to provide more information than this. Are you seeing this with every email? If not, can you provide an email where it doesn't work. If it's happening with all messages it might be an issue with your particular device/Android flavor. What device are you using?

**Comment by duncan-SF** [comment]
I've seen what may be tentaurus's issue. 

Some messages open with all the text on a few very long lines of very small type. In that case the message body occupies only maybe a quarter inch of screen height with the rest of the screen being the void below the bottom of the message.

To read those messages I have to get both fingers in the tiny strip with text and spread them horizontally. If either is in the void or I attempt a normal diagonal finger spread K9 does not zoom.

**Comment by tentaurus** [comment]
So it happens with with a single email...I can't pitch to zoom with gmail, too.
Means it works in general.

**Comment by kripper** [comment]
See https://github.com/thundernest/k-9/issues/5789
