### ISSUE TITLE
background sync does not rely on its setting  of sync on "automatic sync is activated"

### ISSUE THREAD

**Issue by itsbrody** [k9mail/k-9#2971]
### Expected behavior
I've installed K9 mail app and its (green) widget for easily switching on/off syncing. This widget sits on my home screen, where I have other 'online capable' tools as chats setting.
Further I've configured K9 in its global setting -> network to rely background sync on 'if "automatic snyc" is activated. 
I understand and tapping the widget show that by message, that tapping changes background sync ever between on and off. On state is also shown as green painted widget and Off as grey painted.

### Actual behavior
When in my WLAN I often switched it on, showing it green. When leaving my WLAN, I loose connectivity because 'mobile data' is switched of. When abroad I some times need 'mobile data' and then and before I check the state of the widget. Switching it off, when not done before and surely before switching 'mobile data' on. Then after some time having mobile connectivity I see - although the widget is grey (aka switched off) - that K9 is syncing my mail (with success - showing new emails).

From inside the K9 mail app it seems not to recognize the switch off. It's showing 'next sync in ... minutes' and doing the sync then, again and again.

### Environment
K-9 Mail version: 5.2.0.8 (and 5.4.0.0)

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, several accounts

**Comment by ciechomke** [comment]
Same problem here but it happens in random moments, not only when I leave my home WiFi.
Just after some time even with automatic sync enabled in android settings K-9 mail says in upper bar in main window that sync is disabled. Stopping & starting android automatic sync solves problem for few hours and problem comes back.

Xiaomi Mi5s
Lineage OS 14.1 (Android 7.1)
3 imap accounts

**Comment by source-direct** [comment]
I have exactly the same problem as **_ciechomke_** 

Honor 9
EMUI 5.1 (Android 7.0)
1 IMAP account
K-9 Mail 5.2.0.8

**Comment by source-direct** [comment]
Even with the version v5.400 no change. Synchronization is still deactivated again and again - this is so annoying

**Comment by ciechomke** [comment]
5.402 F-Droid issue still exists.

**Comment by bam80** [comment]
Can deactivated synchronization be due Doze mode? Seems have the same problem

**Comment by ciechomke** [comment]
@bam80 
Yeah, it might be related to https://github.com/k9mail/k-9/issues/970

**Comment by lomlfoml** [comment]
I've used the Green background sync widget for years, and am moving from one GN4 to another, both 6.0.1.  I can't find it anywhere online, nor physically on the phone I am moving from.    I recall the original developer cautioned us it lived with other widgets but was an app. Or vice versa. On my 'from' GN4 it shows in Widgets, and in App Mgr, but I can't find a com for it.  You mention you installed it just a month ago? Please, where in the world did you get it? Thank you!

**Comment by lomlfoml** [comment]
https://apkfree.com/download/k-9-push-widget-2131099650   Yikes. It still works. Now if someone could tell us how to move an email inadvertently put into Trash, back to, say, the Inbox. I've set the Global/Display/Visible message actions to include more than just Delete, but can't make the options show up, reliably, though possibly unreliably. K-9 version 5.403. By the way would someone tell the developers that the past tense of shrink is SHRANK and the message after you compact should read "filename SHRANK {or has shrunk) from 1.3 to 1.2). Oh thank you.

**Comment by itsbrody** [comment]
@lomlfoml: just saw your request above. You are right; this seems not to be a plain widget,but an app or it vanishes, when in use.

Search for PushWidget for K-9 in appstore

Hth, 
itsbroy

**Comment by cketti** [comment]
This will be fixed in the next stable version.

**Comment by itsbrody** [comment]
> 
> 
> This will be fixed in the next stable version.

Thanks; is there any open issue to watch for this, because you closed this one?

**Comment by bam80** [comment]
Maybe it's already fixed in unstable version?
If no, I can't see the reasons why this is closed

**Comment by wiktor-k** [comment]
I guess it would be #3866 that has associated PR fixing it.

**Comment by bam80** [comment]
@wiktor-k thanks, but #3932 is not merged yet.
I think it's better to mention this issue in that PR, if it's relative, so it would be closed upon the PR merge automatically, as it's done for #3866 issue.
