### ISSUE TITLE
Push doesn't work on wifi

### ISSUE THREAD

**Issue by sporkwitch** [k9mail/k-9#2974]
### Expected behavior
A notification should appear when am email arrives. 

### Actual behavior
When on wifi, no email notifications appear unless you manually sync. On mobile data, push emails appear instantly when received by the server. When wifi is lost, all emails received since the last time on mobile data appear at once. 

### Steps to reproduce
1. Send email to a linked account while on mobile, push goes through 
2. Send email to linked account while on wifi, no notification is received 
3. Disconnect wifi, any email from time on wifi appears

### Environment
K-9 Mail version: 5.304 (issue present for approximately one year now) 

Android version: 8.1.0 (using pixel 2, also presents on nexus 6 running 7.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
For K-9 Mail there's no significant difference between WiFi and mobile data. If it works with one, but not the other chances are it's not because of a bug in K-9 Mail.

That being said, it might be related to Doze mode. See issue #857.

**Comment by Enigma644** [comment]
I have the same issue on my brand new Pixel 2. IMAP push not working on Wifi. Works on mobile data.

**Comment by sporkwitch** [comment]
Not sure what's changed, but this seems to be behaving better now.  Possible relation to switching to Google Fi?  Since Google Fi uses wifi for everything (including calls and texts) when you manually connect or are near an access point Google trusts, it might bypass the Doze issues that were previously preventing push while on wifi?

**Comment by Enigma644** [comment]
See: https://github.com/k9mail/k-9/issues/2357
Turning off battery optimization for K9 fixed it for me. I'm not sure why this issue is marked as closed;
K9 doesn't request this permission automatically so this is still an active bug IMHO.

**Comment by zahadum-gh** [comment]
Same exact problem here - push works with mobile data connection but not with wi-fi

Samsung Galaxy J 2017 with Android 8.0.0.

**Comment by jauerb** [comment]
I can't connect at all over WiFi, turning off battery optimization did not fix anything.  I don't see how this is a network issue, as I can connect over the same network (with same server config) from my laptop.
