### ISSUE TITLE
Sender & Subject on separate lines

### ISSUE THREAD

**Issue by mantious** [k9mail/k-9#2975]
### Expected behavior
Sender and Subject to be on separate lines when previewed is set to 0 and show contact pictures is off.

### Actual behavior
I did not see a closed or open issue for Dave's original question in the google mailing list, and I also would like to see this addressed.
 https://groups.google.com/forum/#!searchin/k-9-mail/sender$20and$20subject%7Csort:date/k-9-mail/rNYa5Or-LKw/GmbxaoG1AwAJ

When we set preview lines to 0, and turn off "Show Contact Pictures". The e-mails in the folders crams the sender & subject lines into a single line. This is an issue as the sender and subject lines are then limited to about 8 characters each in portrait mode.

### Steps to reproduce
1. set preview lines to 0
2. turn off "Show Contact Pictures"
3. refresh the account

### Environment
K-9 Mail version: 5.208 (Google Play)

**Comment by philipwhiuk** [comment]
So here's the fields behind the scenes with everything visible.

![screen shot 2017-12-28 at 01 25 13](https://user-images.githubusercontent.com/1316415/34397451-19eae0fa-eb6e-11e7-9504-f427157b2b98.png)

When you select a preview line we seem to just put the sender inside the preview and hide the Sender field.

* Part of me thinks the bad bit of behaviour is actually merging the sender and the preview.
* Part of me thinks the component needs better options
* Part of me hates having lots of options

**Comment by cketti** [comment]
Setting preview lines to 0 has historically enabled single line mode. I believe it was added because some people like(d) to optimize for number of messages on the screen instead of touch usability. But that was during a time where phones had DPADs and/or hardware keyboards. It's probably time to get rid of the single line mode.

**Comment by jerryyhom** [comment]
I actually appreciate the single line mode.  As others have expressed in the mailing list, I do not need the preview lines but just the sender and subject.  As for the narrow sender and subject columns in portrait mode reported in this Issue, perhaps try landscape mode.

Anyhow, my true comment concerns a setting: Global -> Display -> Correspondent above subject.  Assuming Preview lines is 0, hence single line mode, the above setting lays out subject in the first column then sender in the next column, which to me seems opposite.

Is this a separate issue?  Can you point me to the relevant code?  I can try updating it and creating a pull request.  Thanks for your attention.

**Comment by cketti** [comment]
This is fixed in K-9 Mail 5.7xx.
