### ISSUE TITLE
k-9 can't send encrypted Mails, because key Provider not found

### ISSUE THREAD

**Issue by gittyhub2018** [k9mail/k-9#2976]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
If i send a encrypted mail, K-9 will be search and take the public key from OpenKeyChain APP and encrypted the mail.

### Actual behavior
I want to send a encrypted mail and K-9 said:"(...)KeyRepository$NotFound"

But the public key is available from the Person who should receive the  mail and the public key is in OpenKeyChain. 
### Steps to reproduce
1. Open K-9 Mail (newest Version in Google Play)
2. Create a empty Mail and write something in it.
3. Activate Mail encryption (lock is green now)
4. and try to send the mail -> Error

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
This is most likely an issue with OpenKeychain. Please report the bug there.
