### ISSUE TITLE
K9 freeze (and soon crash) in most action

### ISSUE THREAD

**Issue by MarkoIndaco** [k9mail/k-9#2979]
As the issue title, almost always I open K9 it freeze. This happens if I take some action like: open an email, long-pressing on email (to choose some action) and/or, if an email is open, sometimes happens when I scroll down. In a particular way, seems a consequence of the swipe animation that occurs when clicking on an email to open it...
[moved here/previously posted]
Hi all, not sure if this is the correct thread but I got a similar issue. The app freeze and soon crash itself. There's no particular situation for this. It can happens soon as I open K-9, or after opening or browsing through emails. Btw, reopen the app for the second or the third time it usually works without further freeze. I use Xprivacy but i totally disable it for K-9 (and anyway I was previously give ALL permission, just to be sure).
I try to download the log file from ADB but for some reason inside the txt file i got this message:
**/sbin/sh: exec: line 1: logcat: not found**
Anyway, by enabling the log option I found 5 logs as emails soon as I start K-9. This are related to different email account that I signed on K-9 so I zipped this 5 emails logs as simple txt files (that I upload [here](https://send.firefox.com/download/efc8a94a8f/#fanHIAygU6DERZgESBHo5Q)) where, the first account (mentioned in the log text file name) it's the most used; the second is sometimes used and the third very rare used...
Hope can help. Thank you in advance for any support.

I'm on HTC One M9 - ViperoneM9 6.2.0 (no Magisk) SuperSu

PS
All the 3 accounts that I set to K9 are GMX service related.
I upload the zip file to external source because I cannot attach it here in GitHub. It's 5 txt files (one for every log I got on K9 home screen). Further info's are inside the txt log files.
- I got K9 also on my second phone Xperia E4g (KitKat 4.4.4) and I never have a freeze or crash in most of 2 years of usage (using the same settings that I backup and ported to HTC)

**Comment by cketti** [comment]
The logs aren't accessible. "This link has expired or never existed in the first place!"
Please upload them to GitHub.

**Comment by MarkoIndaco** [comment]
I'm sorry for that. Anyway it was my mistake. I thought it was not possible to load the zip files, instead it was NoScript that was blocking the link for upload related... again sorry.
Thank you for you're help. Below you can see the zip file attached.
[K9 Log Files.zip](https://github.com/k9mail/k-9/files/1578042/K9.Log.Files.zip)

**Comment by rogerval** [comment]
If I may make a comment, this sounds like an issue I've had for a while (SQLiteDiskIOException: disk I/O error (code 1802) when querying DB from MessageController Thread #2627 - not my original title, but probably more accurate. :-) ).
Kind regards, 
Roger V.

**Comment by MarkoIndaco** [comment]
@rogerval thank you for reply. I read you're post and indeed I got also that issues but, in my case most of the time K9 crash soon as I open an email. Sometimes even if I don't touch anything, only by launching K9, indeed it doesn't seems action (tapping) related because in some case it freeze few seconds after I click something and not necessarily instantly.
Regards

**Comment by rogerval** [comment]
@MarkoIndaco You're welcome. I did some more testing today, and uploaded a log to my original thread; hopefully this helps the developers figure out what's happening.
Kind regards,
Roger V.

**Comment by MarkoIndaco** [comment]
Thank you for looking into it. I don't know if the logs files are complete with information because as I mentioned before for some reason downloading the log file from ADB it gives me the log file, but inside I got only an error line, not log. So, I copy and paste the log files that I see when i launch K9. But if it is strictly necessary I can retry with ADB, though I don't know why it does not work...

**Comment by rogerval** [comment]
@MarkoIndaco My pleasure. I can't fathom why you wouldn't be getting the full log either. I just followed this guide (kindly provided by Cketti ) , and it worked (once I had the correct Windows folder selected, the correct command, and held my tongue right :-) Those being my fault, not cketti's of course.) :
https://github.com/k9mail/k-9/wiki/LoggingErrors
I should mention that I had both logging options ticked in k9, then carefully examined the saved log file in case it had my logins mentioned (and it didn't appear to).
Good luck !
Roger V.
