### ISSUE TITLE
Feature Request: Swipe to navigate from one email to another in the inbox.

### ISSUE THREAD

**Issue by harshvardhan-takawale** [k9mail/k-9#2980]
### Expected behavior
Basically, to should take to the next email on left swipe and to the previous on right swipe, similat to the Gmail app.

### Steps to reproduce
1.We need to use fragments which have easy transaction and this help in moving from one mail to another.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

### Are you willing to work on the issue
Yes

**Comment by cketti** [comment]
Duplicate of #585
