### ISSUE TITLE
Gmail won't sync

### ISSUE THREAD

**Issue by impreza233** [k9mail/k-9#2981]
### Expected behavior
GMail authentication should work well

### Actual behavior
Gmail Authentication fails.

### Steps to reproduce
1.Configure K9 Mail with GMail and configure user and password. Then it will happen this error:
![screenshot_2017-12-21-18-58-19](https://user-images.githubusercontent.com/25793051/34268378-c2228f9a-e680-11e7-97bb-1ada17fe7450.png)

### Environment
K-9 Mail version: 5.2.0.8

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
