### ISSUE TITLE
Security issue with Gmail (someone has your password)

### ISSUE THREAD

**Issue by lymber** [k9mail/k-9#2982]
I've never received such an alert from Google since I started using Gmail (around 2004). After installed k-9 (which I love, that's why I'm writing this) I got that alert two times. In both opportunities I changed my password.

It says the geolocation of those accesses is diverse, what's going on?

I may provide further information if guided by someone more experienced.

Thanks in advance,
Alexandre.

**Comment by cketti** [comment]
Please contact Gmail support about this. I doubt there's anything we can do in K-9 Mail.
