### ISSUE TITLE
Feature Request: Creating splash screen for first time users.

### ISSUE THREAD

**Issue by harshvardhan-takawale** [k9mail/k-9#2984]
### Expected behavior
To create multiple screens to display the app icon and the information

### Actual behavior
Currently, there is just one screen to display all the information in plane text.

### Steps to reproduce
1.To create multiple activities and organize the text.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

### Are you willing to work on it
Yes.

**Comment by philipwhiuk** [comment]
Feel free to link some prototypes for review. Sounds good to me.

**Comment by cketti** [comment]
I wouldn't call this a [splash screen](https://en.wikipedia.org/wiki/Splash_screen). Better keywords to describe this are 'onboarding' or 'tutorial'.
Anyway, we already have issue #1818 for improved onboarding. I want to add improved account setup first before thinking about whether or not to add a tutorial that explains how to use the app. And if we do how that could look like exactly.
