### ISSUE TITLE
Automatically encrypt when composing a new email

### ISSUE THREAD

**Issue by fbatschi** [k9mail/k-9#2989]
### Expected behavior
I want to enable automatic encryption to recipients whom I have a key for.
When I compose a new mail and add an recipient with a GPG Key in my OpenKeychain keyring, it should automatically enable encryption for this mail as well as all mails in the future.

### Actual behavior
When I compose a new email and add an recipient with a GPG key in my OpneKeychain keyring encryption is NOT enabled and even if i enable encryption for this mail, when i compose a new email to this recipient I have to enable encryption again (which you can easily forget)

### Steps to reproduce
1. Have a recipient with a GPG key in your keychain 
2. Draft a new mail in K9 Mail and add the recipient to the mail
3. You have to manually enable encryption each time

In 5.2x it was still possible to configure the general enryption mode on a global level. In 5.3x this seems to be completely gone. I have read the blog articles about your ideas about the encryption of mails but did not find anything why automatic encryption is not possible anymore.

### Environment
K-9 Mail version: 5.304

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
K9 will follow the autocrypt recommendations in this regard some time soon. Check out autocrypt.org for details :)
