### ISSUE TITLE
Not clear how to perform server-side search

### ISSUE THREAD

**Issue by kuba-orlik** [k9mail/k-9#2992]
### Expected behavior

I open up a not fully-synced folder and search for a term. K-9 performs server-side search and returns matching emails

### Actual behavior

No emails are found, or only emails stored locally

### Steps to reproduce
1. Go to any folder
2. Search for term that you know appears in one of the emails on the server in that folder
3. See results

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type: IMAP

**Comment by philipwhiuk** [comment]
Have you enabled server-side search?

**Comment by rancidfrog** [comment]
I have, Account Settings | Search
![](https://i.imgur.com/hJY8ixO.png)
But, I do not believe it works properly.

**Comment by philipwhiuk** [comment]
@rancidfrog Please provide a debug log and something a little more concrete than 'doesn't work properly'.

**Comment by cketti** [comment]
K-9 Mail currently doesn't support search in email bodies on the server.

**Comment by rancidfrog** [comment]
I was searching mostly for text contained in email address itself,

- When searching on the overview page, it only searches email already on device and there is no option to check on server.
- To do Server-side search you need to search per-folder
Sometimes it fails,
![](https://s13.postimg.org/dgx6bhb9j/Screenshot_20180102-132705.png)
It mostly displays weird %d results while in progress of search,
![](https://s13.postimg.org/s04bcvwon/Screenshot_20180102-132233.png)
And, it does not always return all mails, 
![](https://s13.postimg.org/jhuv8jig7/Screenshot_from_2018-01-02_13-18-46.png)

I logged it but the logs I have seem only to be searching in inbox folder, which returned no results.
It might be wrong folder to search, as I thought server-side searched all folders in server.
Did some quick tests and it seems that k9 app not returning all mails found
