### ISSUE TITLE
Email not sent, without any message, if attachments appended with underscore in file name like "1_..."

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#2994]
I've had a couple of PDF files to be sent. For numbering all files had names starting with 1_, 2_ etc.

All marked in File Explorer, multiple selection, and "shared" with K9.

Added recipient, subject and text, as usual

Clicked "send"

### Expected behavior
Email should be sent to recipient, and stored in "Sent Items"

### Actual behavior
Short hourglass, Android style rotating circle.
Context switched from email composing to Inbox.
Email is NOT sent.
Not sent email is not stored in Sent Items.
NO error message, nothing. 

Hard to find bug, with search in server logs etc.
Funny thing is, that renaming attached files from numbering scheme 1_..., 2_..., ... to 1-..., 2-..., ..., dash instead of underscore, workarounds this bug

### Steps to reproduce
1. Create a file with file name starting with "1_"
2. Mark file in file explorer
3. "Share" with K9
4. Click "send"

### Environment
K-9 Mail version: 5.208 (current version from F-DROID)

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, own mail server on VPS (postfix, dovecot)

**Comment by michaelof** [comment]
Remark: Maybe, I'm German speaking, "hyphen instead of underscore" might be more correct than "dash instead of underscore"

**Comment by philipwhiuk** [comment]
I couldn't reproduce this just with `1_testFile` :(

**Comment by michaelof** [comment]
Just tried again.

Same smartphone, same files, same IMAP accounts (sender and recipient). No reboot in between.

Works fine now. 

No idea what was wrong this morning, why this was really (I swear :)) reproducible before. Mystic...

**Comment by michaelof** [comment]
Have had this issue again, but completely independent of file names.

It seems to have something to do with memory swap out of Android.

I'm using a cheap smartphone with just 1 GB RAM, and depending on how many running apps, some of them are getting swapped out regularly.

Right now I've the following reproducible situation:

a) when sending from K9 app as starting point, new mail, add pic as attachment, press "send": Works fine.

b) when starting in Android's Gallery app, select a picture, share ..., select K9, enter recipient, header, message body etc., press "send": A very short hourglass is shown, focus is back to Gallery. NO RESULT in K9, no email in Sent, nothing in Outbox, nothing sent. Opening K9 afterwards from launcher takes the some time, as Android needs to swap out another app.

Still mystic issue, but it's somewhat ugly that messages "disappear" without notice. Sent to Nirvana :)

As I have a workaround, not to use "share with K9" on my smartphone but start within K9: Please give me a hint if you think it would make sense to try to dig more into this issue? Any chance to trace this swap out somehow?

**Comment by philipwhiuk** [comment]
If you can provide a debug log we can compare it to a working device and see if there's anything obvious. But it's kind of a long shot.
