### ISSUE TITLE
Version 5.400 does no longer automatically encrypt/sign messages to contacts with matching keys available

### ISSUE THREAD

**Issue by DPTJKKVH** [k9mail/k-9#2997]
K-9 always automatically encrypted and signed emails to contacts which had a matching key available if you configured a OpenPGP app for your email account. This behaviour is now gone with version 5.400. Instead you have to manually select the lock icon next to the contacts email address to activate encryption and signing every time you send a new email. There is no option to permanently activate encryption and signing for a contact. The only situation where automatic encryption and signing happens is when you receive an encrypted message and then directly reply to that message.

Since there isn't even a warning that points you to the fact that you are about to send an unencrypted and unsigned message this will result in many unwanted and often even unnoticed plaintext emails being sent. This is a major privacy and security risk which wasn't present before version 5.400. I'm pretty sure this is an unwanted behaviour that the developer did not intentionally include since I can't think of any scenario where you have PGP keys of a contact available but _by default_ want send them unencrypted and unsigned messages.

I suggest that K-9 reintroduces automatic encryption & signing for contacts with matching keys available. Alternatively there should be an option to globally (or at least per contact) activate automatic encryption and signing.

### Expected behavior
Emails to contacts with matching PGP keys should be automatically encrypted and signed.

### Actual behavior
Encryption and signing has to be manually activated every time.

### Environment
K-9 Mail version: 5.400

OpenKeychain version: 4.8.1

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by mnieke** [comment]
I have the same problem and support this request.

**Comment by DPTJKKVH** [comment]
May I ask why mnieke's comment was removed? Isn't it relevant that more than one user considers this a relevant issue?

**Comment by ArchangeGabriel** [comment]
You have GitHub users reactions feature for that. So just +1 the issue instead.

**Comment by DPTJKKVH** [comment]
Understood and agreed.

**Comment by damiencourousse** [comment]
+1

**Comment by vitaminace33** [comment]
version 5.403

K9 mail does no longer support signing or am I wrong? I have reset K9 mail and OpenKeyChain, look under every option available and I can only encrypt.

**Comment by vitaminace33** [comment]
SOLVED: global settings > encryption > show unencrypted signatures = 1

Feature description really ill written!

**Comment by Valodim** [comment]
It seems to be, see also #3251. Changes to this stuff are in the pipeline -> #3276 

For the original issue, please read refer to this [blog post](https://k9mail.github.io/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt.html) for our stance on things, and/or enable "Autocrypt mutual mode" to get encryption by default between supporting clients (which is at least k-9 itself and newer enigmail).

**Comment by DPTJKKVH** [comment]
I know you don't welcome a discussion here but please allow me some final words: 

I really respect your work but your blogpost makes me sad because I don't see what problem you try to fix with that. It's like you are chasing shadows.

If somebody isn't capable to handle encrypted email they don't go through the hassle of setting up encryption plugins, creating keys and exchanging them with their communication partners. So there is nothing that could be "accidentally" encrypted and then become inaccessible. Where are the droves of users that are in anguish of their securely encrypted emails that you try to protect with this?

On the other hand you now risk everyone using encryption to accidentally not encrypting their message and thus risking their privacy or causing financial damage or even worse.


I also don't see how deactivating encryption by default is helping to spread encrypted communication. If Whatsapp and Threema taught us anything it's that 90% of people simply forget to activate encryption (Threema. Look it up! They regularly bust people because of this.) if it isn't activated by default. (Like it is with Whatsapp or Signal.)


People want simple encryption but you are adding an additional layer of complexity and thus making encrypted communication even more complicated. Your whole blog post reads like "Encryption is too complex and overwhelms lots of people. So lets make it even more complicated, bothersome and unintuitive to use so only absolute hardcore nerds and privacy advocates are willing and able to jump through all hoops. This way we make sure that nobody accidentally encrypts their email and then loses access to it at the cost that way less email is getting encrypted overall. *This way we ensure that encrypted email is becoming more widespread available in future.*"

In makes me sad because you either work against your own goals or actually value theoretical availability issues for a few corner cases over the confidentiality of all PGP users.

It's your project and I'm in no position to stop you from going down the path you describe in your blog post but I hope you don't simply dismiss my words but keep them in mind while you are at it.

**Comment by DPTJKKVH** [comment]
"Funny" enough I just realized that I forgot to encrypt a sensitive message sent via k9 today because I was in a hurry. This is exactly what I mean: How can "insecure" be the default when even European law requires "privacy by default" in all applications starting from May 25 on. This is really saddening me. You do not help spreading privacy with this but making everyone more vulnerable... :confused:

**Comment by Valodim** [comment]
Thanks for your perspective. I understand having workflows broken is annoying. I don't want to reopen this discussion as a whole on this issue tracker, but I will address one point:

> Like it is with Whatsapp

Whatsapp-style transparent e2e encryption is not "just enabling it by default", or designing the workflows right, or being aware of what users want. It's a huge technical effort, in a closed system, and even there it comes as a tradeoff that sacrifices availability and ease of multi-device. People have different expectations for Whatsapp than for E-Mail.

We have tried to get e-mail encryption right for decades. We have so many pgp-related projects that have "easy" in their name it might as well be a running gag. What we need to do is take a step back from absolutism - it's *not* as easy as just enabling encryption by default.

However, again, this is not a discussion for an issue tracker. If you are interested in the topic, I encourage you to read the [Autocrypt](autocrypt.org) spec. A bunch of people interested in this topic also hang out on freenode in #autocrypt (alternatively #autocrypt:matrix.org). You can also find me on many chaos and internet freedom related events :)
