### ISSUE TITLE
Adding second account

### ISSUE THREAD

**Issue by patostevens** [k9mail/k-9#3001]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Trying to add second IMAP account manually

### Actual behavior
Tell us what happens instead
At the end of the incoming server page, the NEXT button is non functional. There is no way to proceed further.

### Steps to reproduce
1.Fill out all details on incoming server page for adding a second IMAP account
2.Press NEXT button to continue
3.No response from program at all

### Environment
K-9 Mail version:

Android version:8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
It the "Next" button greyed out, i.e. disabled? Or is it a regular button and pressing it just does nothing?

**Comment by patostevens** [comment]
Seems to be greyed out. I've even gone back and gone through every entry 
point, just in case. Same result. The initial (main) account works 
perfectly. I've even un-installed and re-installed. Same results.
