### ISSUE TITLE
No longer clickable Http/https links

### ISSUE THREAD

**Issue by stoecker** [k9mail/k-9#3002]
Before the recent update http/https links in text emails have been converted into clickable links. This is especially very helpful when getting tickets from bugtrackers. A single click brings you to the corresponding ticket page.

The new version no longer has this feature, so the links must be manually selected and then copied to the browser.

If there is hidden an option somewhere to still do this please tell me where, otherwise please readd this possibility.

P.S. The new icon is ugly.

**Comment by lpapier** [comment]
I too use a lot the feature of http links in text only mails that was present in version 5.208 and older.

If the new behaviour in version 5.400 is not a bug, please could you add an option to enable/disable this feature.

**Comment by cketti** [comment]
Please provide the text of such a message.

**Comment by stoecker** [comment]
Maybe also related to #3003, as it seems the same messages are affected.

[example.txt](https://github.com/k9mail/k-9/files/1594301/example.txt)

**Comment by lpapier** [comment]
No behaviour like in #3003 for me.
[morevna.txt](https://github.com/k9mail/k-9/files/1594482/morevna.txt)

**Comment by garfieldthecat** [comment]
Isn't this a duplicate of https://github.com/k9mail/k-9/issues/2922 ? I have given some examples there

**Comment by stoecker** [comment]
Yes.
