### ISSUE TITLE
Creates duplicate INBOX.Drafts, INBOX.Sent and INBOX.Trash folders

### ISSUE THREAD

**Issue by dpocock** [k9mail/k-9#3005]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I have a Drafts, Sent and Trash folder and K-9 should use them, as it was before.

### Actual behavior
I installed K-9 onto a new device and imported the settings saved from another device running K-9.  The other device was running an older version and the settings file is version 35

I notice that when I saved a draft on this new device, it wasn't visible in the Drafts folder from other IMAP clients.

Looking more closely, I found new folders INBOX.Drafts, INBOX.Sent and INBOX.Trash

I went into the Account settings menu and changed them back to use names without the "INBOX." prefix and now it is working as it was before.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.208 (F-Droid)

Android version: LineageOS

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by drittelhacker** [comment]
Similar problem, that i almost expected to be localization related, since since all three Folders are newly created using their German names.

K-9 version: 5.403
Android version: FairphoneOS (Android 6.0.1) 
Account type: IMAP on Zimbra server

**Comment by riasevern** [comment]
I've just had this as well on the wife's phone. Galaxy A5 (2017) Android 7.0 Kernel 3.18.14-12637612

We're UK, so English and it's got INBOX.Drafts, .Junk, .Sent and .Trash in it's folder list and accessible through account settings. These didn't exist before setting up the K9 client and the other clients (web, Thunderbird, Notes - Imap) all correctly map and use the native folders. This wasn't noticed until Wife complained that most of her emails from this account on the phone weren't going.
I have access to the server and INBOX.Drafts, Sent, Trash exist but not INBOX.Junk (presumably nothing captured) and therefore not created by K9 Client).
Unfortunately not enough to see what the creation dates/times were on those additional directories but I'm sure they were created by the K9 client not elsewhere.
The server is a Dovecot mail server.
We have other accounts in K9 but admittedly on different mail servers - they seem to behave correctly. If I get time (and phone access) I'll try setting up another account on the same server but for now no idea why it happened, it was strange and of course I got the earache about "why this email client"...

**Comment by cketti** [comment]
The next stable K-9 Mail version won't automatically create special folders anymore.

**Comment by tom86se** [comment]
I experience that k9 cant detect spam folder and it creates it's own...but the original spam folder is present in my account...annoying
