### ISSUE TITLE
Feature: add option to couple images in inbox to email identities instead of contact photos

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3014]
I would love to have a clear indication in my inbox to which of my 10+ identities an email was send. I have no use for these big images of each contact. I would much rather display a picture or icon of the receiving identity, rahter than the sending contact.

This could be an optional setting.

![k9 that s what i m talking about](https://user-images.githubusercontent.com/34976212/34459641-e59afa3a-edf5-11e7-99c9-e0b9641a51bb.jpg)

So instead of those linked to the name of the contact, I would like them linked to the name of an identity.
(Btw I am sure there are loads people who do like it as is, I am merely suggestion to have an optional alternative to it)

### Environment
K-9 Mail version:
5.400

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Meteor0id** [comment]
pulled that image of the interwebs btw, was to lazy to screencap my own inbox

**Comment by cketti** [comment]
I don't want to add such a feature to K-9 Mail. An easy way to accomplish that is to add server-side filters that sort mails to different folders depending on which identity an email was sent to.
