### ISSUE TITLE
"Max folders to check with push" should allow less than 10

### ISSUE THREAD

**Issue by Rhialto** [k9mail/k-9#3017]
### Expected behavior
When I refresh my mail, I expect to see my new mail.

### Actual behavior
Instead I see incomplete error messages in the folder overview; "Command: AUTHENTICATE-CRAM-" and the rest seems to be missing.

"Max folders to check with push" (which may or may not be a related setting) is set at the lowest value of 10. I would think it needs lower options.

My imap server (dovecot) logs 

```
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=25092, TLS, session=<7sRca6Vhj59bN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=13658, TLS, session=<Ttpca6Vhg+hbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=10350, TLS, session=<bWVda6Vh/tBbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=26853, TLS, session=<iGRda6VhD4tbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=2918, TLS, session=<OdBda6VhO+JbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=22125, TLS, session=<OdBda6VhqNRbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=17403, TLS, session=<Txxfa6VhRLZbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=17585, TLS, session=<1Rtfa6Vhu7tbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=18985, TLS, session=<7zlfa6VhoOVbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Login: user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, mpid=19881, TLS, session=<w0xfa6VhmqpbN1pC>
Dec 31 17:33:02 murthe dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<rhialto>, method=CRAM-MD5, rip=xxx, lip=yyy, TLS, session=<LJlfa6Vh87FbN1pC>
```

Note that this tries to open an 11th connection.

### Steps to reproduce
1. Set dovecot to limit to 10 connections (way overkill!!! but it happens to be the default)
2. have more than 10 folders, I suppose
3. refresh mail.

### Environment
K-9 Mail version: 5.400

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
IMAP IDLE requires 1 connection per folder - there's nothing we can do to avoid it. I wish NOTIFY was better supported but it's not. So this a problem for all clients using Push-IMAP.

10 seemed like a reasonable limit and fits what most providers expect. By default we don't set every folder as push enabled anyway, only 1st class ones (which starts as the special folders).

**Comment by philipwhiuk** [comment]
See: #826 for adding NOTIFY support

**Comment by Rhialto** [comment]
I think it mainly happened because I had just re-imported my settings, and it was busy to look at all my folders again.
Eventually it succeeded, but it took a while. I think my IMAP server took some time to allow connections again, because K-9 had tried to open more than 10. Maybe it is only in this situation, but the max setting of 10 was seemingly not taken into account.

**Comment by philipwhiuk** [comment]
I think we might use max_push_folders + 1 in practice - one for user-requested actions and 10 for 10 folders set to push.
