### ISSUE TITLE
Slow performance since 5.4

### ISSUE THREAD

**Issue by mmalmeida** [k9mail/k-9#3020]
Since the upgrade performance is really slow when selecting messages in my account -  About half a second to select a message. 

Issue did not happen before. 

### Environment
K-9 Mail version: 5.4

Android version:
OnePlus 3T
Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by taluscreep** [comment]
Second this, scrolling and selecting and waiting to view messages is painfully slow.  There is hesitation/freezing when scrolling, and delayed response when selecting.

**Comment by hg2581** [comment]
I see the same with the two updates released over the past few days. Very painful. Hesitation seems it might be related to trying to retrieve contact information for the sender of each e-mail??

**Comment by kmcgrail** [comment]
Also seeing this behavior.  It's as if I see a minor and very slow 3 color fadein animation effect each time I select or do an action.  Some screen redraw is very slow.  Sometimes I can see the entire app whiting out.  Especially swipe to select and then archive.  It is much slower.  KAM

**Comment by ghostrider72** [comment]
The same here, the last two versions are very slow and the search button doesn't work anymore. Did you notice it?

**Comment by Barkole** [comment]
Sometimes K9 does not response at all. most of the time, it took several seconds for a simple UI interaction.

**Comment by Barkole** [comment]
For me at least, unticking both of "show contact names" or "show contact pictures" results in a dramatic speedup. These defaults never slowed my session down until the new version came out.

**Comment by kmcgrail** [comment]
Barkole is right!  I had the show contact names already unchecked but also unchecked show contact pictures and the performance is back to what I remember from the previous version though now I don't have the contact pictures/initial.  I definitely had the same settings for years so hopefully this helps pinpoint the issue.

-KAM

**Comment by cketti** [comment]
See #3525
