### ISSUE TITLE
K9 version 5.4 not fetching new mail on imap on refresh

### ISSUE THREAD

**Issue by taspts** [k9mail/k-9#3022]
### Expected behavior
Open email account or refresh email and get new emails to show.
An update of K9-mail shouldn't break existing usage,

### Actual behavior
NO new emails is shown until mail is open  by thunderbird or K9 ver 5.208

### Steps to reproduce
1. Open imap based mailaccount on an uw-imap server
2. Send a email to the account
3. Verify that email is received.

This is a change from K9 version 5.208 that use imap select INBOX
Version 5.4 uses imap examine INBOX

This is testet on Centos 7 and uw-imap as server with 
new mail arrive  in /var/spool/mail/<user> and  
mbox file  in ~/mbox. This means there are a 2 stage process  for new email.

uw-imap is written by Mark Crispin that wrote the RFC for imap4 rev1 
[RFC3501](https://tools.ietf.org/html/rfc3501)

I used wireshark and telnet to investigate the differens between IMAP SELECT vs EXAMINE. 

syslog shows  when files are moved 
xz2 is running K9-mail ver 5.4, stab1 is running K9-mail 5.208
```
Jan  1 10:11:30 vts6 imapd[21803]: imaps SSL service init from 192.168.127.63
Jan  1 10:11:31 vts6 imapd[21803]: Authenticated user=pts host=xz2.xxxx [192.168.127.63] mech=PLAIN
Jan  1 10:12:36 vts6 imapd[21817]: imaps SSL service init from 192.168.127.61
Jan  1 10:12:36 vts6 imapd[21817]: Authenticated user=pts host=stab1.xxxx [192.168.127.61] mech=PLAIN
Jan  1 10:12:37 vts6 imapd[21817]: Moved 303041 bytes of new mail to /home/pts/mbox from \
/var/spool/mail/pts host= stab1.xxxx [192.168.127.61]
```

imap SELECT INBOX starts a move of new email from spool area to mbox file and then returns  With <n> RECENT result for numbers of new (RECENT) mails.

There are index and other data that needs to be updated on new mail arrival and therefor it's a 2 stage process to deliver.

```
a0006 select inbox                                                                        
* 1322 EXISTS                                                                             
* 1323 EXISTS                                                                             
* 1 RECENT                                                                                
* OK [UIDVALIDITY 1324058029] UID validity status                                         
* OK [UIDNEXT 2700] Predicted next UID                                                    
* FLAGS (NonJunk \Answered \Flagged \Deleted \Draft \Seen)                                
* OK [PERMANENTFLAGS (NonJunk \* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags                                                                                        
* OK [UNSEEN 3] first unseen message in /home_l/pts/mbox                                  
a0006 OK [READ-WRITE] SELECT completed 
```                                                   

imap examine is a read only operation does not changes anything, just returns what is there.
```
a000 examine inbox
* 1322 EXISTS
* 0 RECENT
* OK [UIDVALIDITY 1324058029] UID validity status
* OK [UIDNEXT 2699] Predicted next UID
* FLAGS (NonJunk \Answered \Flagged \Deleted \Draft \Seen)
* OK [PERMANENTFLAGS ()] Permanent flags
* OK [UNSEEN 3] first unseen message in /home_l/pts/mbox
a000 OK [READ-ONLY] EXAMINE completed
```

**Note  0 RECENT**  is is what happens on version 5.4 that uses examine.

Open a folder or account or using refresh button should trigger an IMAP SELECT  

### Environment
K-9 Mail version: 5.4

Android version: 4.4.x and 6

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
If the server fails to return RECENT messages when EXAMINE is performed the server is not obeying the RFC:

> The EXAMINE command is identical to SELECT and returns the same output;

https://tools.ietf.org/html/rfc3501#page-32

We shouldn't need to enter a non-read only state to show the number of recent messages

**Comment by cketti** [comment]
We switched to using `EXAMINE` because some other clients use the `\Recent` flag to show which messages are "new". Using `SELECT` removes the `\Recent` flag on messages. So our previous behavior lead to no messages being shown as new in those other clients once K-9 Mail checked for messages.

Considering UW IMAP is more or less abandoned I don't see a reason to revert our change.

As a work-around you could mark a message as read/unread to get K-9 Mail to issue a `SELECT` command.

**Comment by taspts** [comment]
Thanks. Using unread/read works. I'm satisfied with the unread/read to trigger a SELECT.

Reading the RFC3501 once more the IMAP server is not alone, I think is combination of several agents and IMAP is one and EXAMINE is a READONLY operation for the IMAP server. 

See https://tools.ietf.org/html/rfc3501#appendix-B point 69)
> 69) Clarify that EXAMINE does not affect \Recent.
