### ISSUE TITLE
Create an overflow options menu instead of on long press for folders

### ISSUE THREAD

**Issue by harshvardhan-takawale** [k9mail/k-9#3023]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
The menu should be visible when you press the overflow menu button.

### Actual behavior
Currently the menu is shown when you long press the folder

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

###Am I willing to work
Yes

### Mockup
![screenshot_1514876561](https://user-images.githubusercontent.com/28982436/34476783-e486e12a-efb9-11e7-874c-ccbeef3a5ac3.png)

**Comment by cketti** [comment]
Sorry, we have a greater redesign in mind. Random UI changes are unlikely to be merged.
