### ISSUE TITLE
High Battery usage since last Update 

### ISSUE THREAD

**Issue by Swerner1975** [k9mail/k-9#3027]
Battery usage is very high since last update. 

### Environment
K-9 Mail version: 4.5

Android version: 8.1

Google Pixel 1

Account type (IMAP, POP3, WebDAV/Exchange): Pop3

**Comment by goutbulgare** [comment]
Same to me.

K-9 mail v 5.4

Android v 5.0.2

Panasonic Lumix dmc-cm1

**Comment by Swerner1975** [comment]
App is in the background and the Client get mails one time in the hour. 

The Battery usage is higher then Facebook App, wich I use very often the day.

**Comment by Swerner1975** [comment]
Sorry, my K-9 Mail version is 5.400 not 4.5

**Comment by anmith** [comment]
Same here. 

During the last year, K-9 Mail always used about 10-15% of my battery, since the 5.4 update it's up to 39%.

Phone is a Nexus 5X running stock Android 8.1

**Comment by janws** [comment]
The additional power consumption is quite substantial on my LG G5, Android 7.0. K-9 Mail is dominating overall consumption during idle about 10 to 1.

**Comment by bubbasbits** [comment]
Please make this a higher priority to be fixed. Today with K-9 I had 3 minutes active usage, but it consumed 11 hours and 27 minutes in the background. Had to disable background use for the app to save my battery so I could use my phone all day.

**Comment by mpjohans** [comment]
Same here, noticed that battery suddenly got significantly shorter. K-9 now uses 40% of total battery, when it used to be a few percent, with mailbox refresh every 10 minutes. Reassuring to see it is a common problem, not only my phone, but a pity of course that I have to switch to something else, as the issue hasn't been addressed or even acknowledged in three months :-/  Used to be a great app.

(version 5.403, LG G4, Android 6.0)

**Comment by knttr** [comment]
Please raise the priority of this issue, since this is extremely irritating. K-9 now uses 37% of my total battery capacity as opposed to (from memory) approximately 15%. 
Current values: CPU time: 15m36s / Active hold (German "Aktiv halten") 50m5s.
 K-9 Mail Version 5.403 / Motorola Moto G2 / Android 6.0
Please fix this great app.

**Comment by loneBruzzy** [comment]
Hi, I've got exactly the same issue.
K-9 Mail Version 5.403 / Samsung Galaxy S7 (SM-G930F) / Android 6.0.1

Thanks.

**Comment by breversa** [comment]
@mpjohans : same issue as you with the same setup. Are you using LineageOS 13 as well ?

**Comment by Akojen** [comment]
It's a huge issue for me on my LG G5, Androird 8.0, Kernel version 3.18.71.

Is there a way to debug it or help to solve it in some other capacity?

**Comment by cketti** [comment]
Not actionable.
