### ISSUE TITLE
Background Graphic not displayed

### ISSUE THREAD

**Issue by guente** [k9mail/k-9#3030]
Since Version 5.304 BG Graphics are not displayed correctly in my Samsung Galaxy S 7 w/ Android 7.0 in some e-mails

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Can you provide the source of the email (e.g. by accessing your email in a desktop client / web client).

**Comment by guente** [comment]
It is a newsletter I get every morning from a german newspaper on a hotmail adress. This is the browser link provided in the mail: http://utf.rdir.de/form.do?agnCI=875&agnFN=fullview&agnUID=A.B.B0x8.f7q.BbqVA.ldy9U0NE7_YOpJvk1r_Ruw

Does this help?

**Comment by philipwhiuk** [comment]
Probably fixed by: https://github.com/k9mail/k-9/pull/3037
