### ISSUE TITLE
Crash when app is launched

### ISSUE THREAD

**Issue by Chnutz** [k9mail/k-9#3033]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue
-> Nothing found in the first days of the year 2018.

### Expected behavior
K9 should work.

### Actual behavior
K9 don't work any longer since update at the 3th of january. 
Every time when I try to start the app now it tries to start and after a short second a window says: "K9 wurde beendet" (= K9 was closed).
I've tried it with restart the smartphone -> no effect.
Close the app in the app directory -> no effect. 
Update from 5.400 to 5.401 -> no effect

### Steps to reproduce
1. Click on the K9 icon
2. read the error message
3. enjoy ;-)

### Environment
K-9 Mail version: 5.400 and 5.401

Android version: 6.0.1 on CAT S 60

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thank you for do all the work on K9! I hope we will find a solution
Greetings
Chnutz

**Comment by cketti** [comment]
Try uninstalling, then reinstalling. If that doesn't help please record a debug log so we can find out where the app crashes. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by rogerval** [comment]
@Chnutz If you haven't used ADB to get log files before, it can seem rather daunting, but I've found that it's not as hard as it may seem. :-)
@cketti Maybe this is a silly question, but is there an easier way to get at the logged info? Thanks. :-)

**Comment by onetimep0ster** [comment]
I get this same behavior everr since the last update, any plans to revert that?

**Comment by cketti** [comment]
Obviously, the app doesn't crash for everyone. In order to find out why it crashes for you we need more information.
No, there's currently no easier way to retrieve the debug log.

**Comment by onetimep0ster** [comment]
_At the accounts screen of K-9 Mail press the menu button, then choose "Settings". Under the heading "Debugging" check the "Enable debug logging" checkbox. Hit the back button twice to save the changes._

I'd kinda follow those steps, if only i could even open K9... no debug.log in the filesystem? It had been becoming slower each version, guess i'll just change mail app.

Btw, this is happening on a stock Huawei CUN-L01 with android 5.1, in case it helps others with similar issues.

And installing adb, seriously? As an end-user?
