### ISSUE TITLE
HTML displayed wrong

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3034]
I'm using 5.400
K-9
![screenshot_20171214-212206](https://user-images.githubusercontent.com/5685512/34542361-8a2eb76a-f0dc-11e7-8a71-f4f385ed3662.png)

vs Thunderbird
![thunderbird_2018-01-03_23-18-18](https://user-images.githubusercontent.com/5685512/34542479-03e5cc24-f0dd-11e7-8017-eb3051741f24.png)

.eml file without headers and anonymized (done manually)
[Nicht vergessen....eml.zip](https://github.com/k9mail/k-9/files/1601881/Nicht.vergessen.eml.zip)
-11e7-86d7-fb9550a3aaf2.png)

**Comment by philipwhiuk** [comment]
The behaviour of the `Bilder anzeigen` button is more accurately "use remote content" instead of "show pictures".

Does it display properly when you click that? I suspect the problem is that there is a background spacer file or something we aren't loading.

**Comment by cketti** [comment]
Part of the problem is that our `<head>` sanitation doesn't work properly. The other part is that the message is using tables for the layout with tons of attributes that are not supported by HTML 5 and that we currently don't whitelist.

**Comment by Djfe** [comment]
ah, ok :)

@philipwhiuk I did ^^, then I closed the message and opened again (to see if that would fix it), but the images where still shown (like all other ressources, no difference), the button too. Then I made the screenshot.
I guess, if the stuff is in a cache, you don't need to press "load remote stuff" anymore? (or at least it won't make a difference)

**Comment by Djfe** [comment]
I guess, I'll make a few more bug reports, if I find similarly rendered messages.
(so you can fix them, if you got time)

This wasn't the first one.

Thx for taking a look :)

**Comment by limeblack** [comment]
I am having a similar issue.  All the content is crazy shrunk making the text unreadable.

K9 https://i.stack.imgur.com/66QH8.png
Default Lineage OS mail application https://i.stack.imgur.com/qg3dg.png

**Comment by Djfe** [comment]
can you export that e-mail in Thunderbird or something?
or would you be kind enough to forward it to us? :)

you can use
felix.bau@web.de

**Comment by limeblack** [comment]
I forwarded the email to you.  If anyone else would like the email I can send it to them.

I'm hoping you can reproduce the issue just from that.

I believe it has do with the email being forwarded a bunch of times.
