### ISSUE TITLE
decrypt issue with version 5.401

### ISSUE THREAD

**Issue by bradasim** [k9mail/k-9#3038]
K9 Mail version: 5.401 + openkeychain 4.8.1
Android version: 6.0

Issue:
if I send an email encrypted with inline PGP from thunderbird 55.5.2, then K9Mail cannot decrypt it anymore. It can decrypt only a PGP/MIME. The imap used is imap-mail.outlook.com and I want to use the inline PGP due to other problems with Microsoft Exchange server with PGP/MIME.

The previous K9 Mail version could decrypt the inline PGP received by Microsoft Exchange imap server.

**Comment by Valodim** [comment]
K-9 can decrypt PGP/INLINE, but only does so if the `----BEGIN PGP` marker is right at the beginning of a message, other than whitespace. Is there maybe some text before the pgp/inline content?
