### ISSUE TITLE
Encrpyting not possible anymore

### ISSUE THREAD

**Issue by pstimpel** [k9mail/k-9#3041]
### Expected behavior
Once I select a receiver with a lock behind the name, I can select to encrypt or not to encrypt the message. I have decided to encrypt. I expect the message to be encrypted and sent afterwards

### Actual behavior
A "Toast" comes up Attempt to invoke virtual method org.bouncycastle.openpgp.PGPPublicKey org.bouncycastle.openpgp.PGPSecretkey.getPublicKey() on a null reference

### Steps to reproduce
K9 and OpenKeyChain installed for months, had to enable Cryptography in K9 again after the last update
Write an Email, select a recipient, clock the lock to enable encryption (btw, why I have to enable it now, in earlier versions this was the standard), click send...and receive the error message above

### Environment
K-9 Mail version: 5.400

Android version:
8.0.0
Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by pstimpel** [comment]
To add, happens on an Android 4.2 Tablet as well, just a different Toast message: null()

**Comment by MartinX3** [comment]
I was need to choose my gpg in every account again..

But now k-9 wants to send Mails without encryption every time by default and I can't change this disturbing behaviour

**Comment by pstimpel** [comment]
> I was need to choose my gpg in every account again..

I was trying this already, no success. The error messages still appear

**Comment by MartinX3** [comment]
You use also openkeychain?

**Comment by pstimpel** [comment]
Yes, I do

**Comment by MartinX3** [comment]
May this one interests you?
https://github.com/open-keychain/open-keychain/issues/2148

**Comment by pstimpel** [comment]
Sounds right, but generating new keys...really? Seems not right to me, since the existing keys are in use, and not "20 ys old" as in the linked issue. The current key was generated mid of December 17

**Comment by MartinX3** [comment]
You shouldn't be in the need to generate new keys
But the more people write them, that they have the same problem, the faster they will fix it. :)

**Comment by pstimpel** [comment]
Yep, hopefully this draws some attention. Right I have a simply broken crypto solution, which limits me form working mobile.

**Comment by MartinX3** [comment]
Yes, that's very sad. :(

How did you created your key?

I created my 4096-bit key with GPGv2 on the command line in Linux Mint

**Comment by pstimpel** [comment]
Probably using Kleopatra suite. The generated keys work nice on all my devices...and I wouldn't expect anything different :)

**Comment by pstimpel** [comment]
btw, 2048 bit RSA here

**Comment by drohhyn** [comment]
> I was need to choose my gpg key in every account again..
> 
> But now k-9 wants to send Mails without encryption every time by default and I can't change this disturbing behaviour

Just ran into this issue about one year later. Your comment helped my as a workaround to get encryption working again in k-9, but the default behavior is still sending unencrypted mails even for recognized contacts with imported public keys. Do you have a solution?

**Comment by MartinX3** [comment]
@drohhyn 
Choosing to encrypt the mail every time :disappointed:
