### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [k9mail/k-9#3043]
Dear team,

when I take a look in the play store the current version is 5.402, in the F-Droid store the current version is 5.208. What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by ArchangeGabriel** [comment]
It has been updated (here for latest version 5.402, but previous versions where also added): https://gitlab.com/fdroid/fdroiddata/commit/72634be0dfec2323d2c94c2f07838d530951609c.

However the repo index had not been updated, thus the APK wasn’t available for update in F-Droid App. But as a matter of fact, it was updated ~20 minutes ago, so if you refresh now you should get it.
