### ISSUE TITLE
Since version 5.4, iframes stopped working

### ISSUE THREAD

**Issue by JavierDiaz** [k9mail/k-9#3044]
### Expected behavior
Until version 5.400, iframes worked in k9mail as detailed in issue https://github.com/k9mail/k-9/issues/843

### Actual behavior
No iframe is shown. In thunderbird, the same email is shown ok

### Steps to reproduce
The following email with iframe is not displayed correctly:
`<html><head><title>Test</title><style type="text/css"> body { margin: 0; border: none; padding: 0; height: 450px; } iframe { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style></head><body>< !--se mete un img para que funcione en k9mail --><img src="https://www.ecestaticos.com/img/generic/backgrounds/px-transparent.png" width="10" height="10" border="0"/><iframe id ="_mailrssiframe" src="http://www.elmundo.es/madrid/2018/01/05/5a4e6500268e3e806a8b4601.html">Test</iframe></body></html>`

### Environment
K-9 Mail version: 5.400

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
I suspect the change in the way we process HTML means we are now stripping iframes and that #846 should have been closed by #2518

We should probably write tests to confirm the actual behaviour either way.

**Comment by cketti** [comment]
I don't see any legitimate reason for supporting `<iframe>` in emails. So the current behavior is likely to stay.

**Comment by JavierDiaz** [comment]
In my case, I use emails that have a lot of iframes, they load some content that rely on a web page that may be updated.  I use other email clients as thunderbird that works ok with iframes.

I see also it is possible using jsoup supporting iframes: https://stackoverflow.com/questions/16234019/traverse-iframe-using-jsoup
