### ISSUE TITLE
Older emails vanish from K-9 inbox

### ISSUE THREAD

**Issue by glems2** [k9mail/k-9#3045]
### Expected behavior
I have an email account that I connect to via POP3 with K-9 Mail, with the latter configured to:
a. not synchronize any server deletions to the client, and
b. never delete on the server any message that was deleted locally.

The provider of the account is a hoster who do not delete any emails on their own.

I also connect to the same account, again via POP3, with Claws Mail, which is configured to delete all received messages on the server _1 week after reception_.

Since I fetch emails with K-9 Mail every day and Claws' server deletions are not to be mirrored to K-9 Mail, I would expect the K-9 Mail Inbox to accumulate all emails it ever received, never deleting any of them from the local storage automatically.

### Actual behavior
The K-9 Mail Inbox of that account contains no emails older than _about_ a week (_which seemingly contradicts_ setting a. above). _[corrections 8 Jan: that the age of the oldest email was about a week was a coincidence obviously and had nothing to do with Claws' server deletions, see comment below]_

### Steps to reproduce
1. Set up an email account without automatic deletions at provider side.
2. Set up Claws Mail to fetch with POP3 and deletion after <timespan>.
3. Set up K-9 Mail to fetch with POP3 and no deletion (see a., b. above).
4. Make sure you get emails every day to that account.
5. After the initial <timespan>, you should see the oldest messages vanishing from K-9 Mail's account Inbox.

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by glems2** [comment]
I 've changed Claws' behavior such that the server now contains emails older than a week. However, I think that K-9 Mail **limits the number of emails that are kept in the Inbox,** because now the oldest email is only 4 days old.

This behavior is similar for an IMAP account that I fetch with K-9 Mail - the total number of emails never seems to exceed some number less than or equal to 50 - although, on that account's server, there are hundreds of emails.

So, just for clarity: the number of emails kept by K-9 Mail has nothing to do (using my settings above) with what gets deleted on the server (which validates that setting a. is implemented correctly). Also it seems that setting b. works as expected, too.

**Comment by glems2** [comment]
I had research the source code a bit last week. I think I found the cause:
1. Emails older than the _n_th-newest [are never fetched from server](https://github.com/k9mail/k-9/blob/d0c8cc3b57a26bfc9c722075bdf041ab7c4a649c/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L853), where _n_ is the `visibleLimit`.
2. After fetching, local emails older than the _n_th-newest [are](https://github.com/k9mail/k-9/blob/d0c8cc3b57a26bfc9c722075bdf041ab7c4a649c/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L3989) [deleted](https://github.com/k9mail/k-9/blob/d0c8cc3b57a26bfc9c722075bdf041ab7c4a649c/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L929) (the `true` refers to `purgeToVisibleLimit`, see [here](https://github.com/k9mail/k-9/blob/d0c8cc3b57a26bfc9c722075bdf041ab7c4a649c/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L1071)).

This is, to say the least, an unexpected behavior as far as I'm concerned: the email client ignoring some remote messages and deleting some local messages without my consent.

**Comment by violoncelloch** [comment]
Have you checked settings>account settings>fetching mail>local folder size ?

**Comment by philipwhiuk** [comment]
Also 'Sync messages from' in the same place.

**Comment by glems2** [comment]
Many thanks and sorry. I must have been blind! Seems I got used to the look of those settings before I felt the need to change such things.

Anyway, the first one fixed it.
