### ISSUE TITLE
add option to delete (or detatch) quotation in forwarded or replied messages

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3060]
I can close the quotation by pressing the X (but its only hidden) I can edit the quotation by pressing the pencil. But i cant delete it. I can empty it, but not delete it.
Especially for mailing lists, this option would be useful to have.

There could be two solutions:
1. A delete button, earasing the quotation with no way back.
2. A detatch button, allowing the user to still read the quoted text, but not including the quotation when sending the email. There must be a very clear clue to the user when the quotation wont actually be included, however it would be beneficial to be able to read the quotation while writing the reply. This also allows for last minute change of mind and includimg the quotation after all.

Especially with mailing lists or when replying to a large number of people, removing quotations would be more convinient than writing a completely new message and adding all the addresses manually.

### Environment
K-9 Mail version:
5.403

**Comment by cketti** [comment]
The "X" does remove the quoted text. The button that shows instead can undo that removal. But if you don't press it the quoted text won't be included in the sent message.

**Comment by Meteor0id** [comment]
Could we clarify the user interface to make this difference more obvious? To me it looked like a minimize function, instead of an exclude function.

**Comment by cketti** [comment]
Do you have any suggestions?

**Comment by Meteor0id** [comment]
Sure!

Two modigications:
1. Change the text "quoted message" to "re-attach quoted message" to clarify that the button has the action of re-attaching.
2. Change the "X" symbol (cross) to a trashbin symbol, to symbolise discarding. It won't be confusing to have a trashbin there as it is located next to the edit button and the qoutation is outlined.

Glad to be of assistence.

**Comment by cketti** [comment]
Sounds good to me. Can you please open a new issue requesting these changes.

**Comment by Meteor0id** [comment]
Or change it to "re-attatch quotation" or "attach quotation". Anyway you get the point.
The icon should be easy the text string might require translaters to take notice.

**Comment by Meteor0id** [comment]
Will do
