### ISSUE TITLE
Search doesn't work on latest version and k9 is now slow

### ISSUE THREAD

**Issue by ghostrider72** [k9mail/k-9#3061]
Last two versions of k9 are not only very slow but the search button doesn't work. 
My phone is a oneplus 3T, 6 gb of ram (plenty of it!), android 7.1 no root. What's happening to this once excellent app?

**Comment by cketti** [comment]
This is not a discussion forum. If you wish to report a bug please open a new issue and include the information asked for in the issue template. Specifically, what are you doing exactly, what do you expect to happen and what happens instead. The more details you can provide the more likely it is we can actually find and fix the bug.
