### ISSUE TITLE
K9 last two versions slow and search function not working

### ISSUE THREAD

**Issue by ghostrider72** [k9mail/k-9#3062]
### Expected behavior
When I select messages, they get selected very slowly and the overall interface is slow now. More, the search and search on server doesn't work anymore. 

### Actual behavior
When clicking search: nothing happens 
When selecting messages: app performs slow

### Steps to reproduce
1. Select messages
2. Activate the search button
3.

### Environment
K-9 Mail version: 5.402

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
Clicking the search button should display an input field at the top of the screen. If that doesn't work it points to something being wrong with your installation of K-9 Mail. Please try uninstalling, then reinstalling.

**Comment by ghostrider72** [comment]
The input field is there (I have been using k9 mail since its creation) but
it doesn't work. This means that it doesn't find what I'm looking for while
in previous versions it did.

**Comment by cketti** [comment]
There's already issue #3020 for slow message selection.

I really don't feel like asking 20 questions to find out what the search issue is about. I already stated that we need as much information as possible to find and fix bugs.
Chances are the search index wasn't correctly populated during an app update. In that case uninstalling, then reinstalling should help.
