### ISSUE TITLE
Add privacy option to hide sender machine name in mails

### ISSUE THREAD

**Issue by axel-h** [k9mail/k-9#3070]
Add a privacy option to hide the name of the machine where K9-Mail is running on. In many cases (e.g. home network, public Wifi, company network), this is a name that can be accessed from outside the network anyway. Could also use a generic name here (e.g. "mailserver") if the mail protocol requires giving something.
Currently this line is added to outgoinf mails:
`Received: from ${my-android-device}.${my home network} ([${my IP assigned by ISP}]) by ${provider-mail-server} ....`

**Comment by philipwhiuk** [comment]
I'm not sure whether this is possible or not. I **think** this is added by your mail server not us.

**Comment by ArchangeGabriel** [comment]
@philipwhiuk You’re right, this is added by the mail server. Actually, some have an option to remove that, like OpenSMTPd `mask-source`:
> If the mask-source parameter is used, then the listener will skip the from part when prepending the “Received” header.
(From https://man.openbsd.org/smtpd.conf.5).
Effectively resulting in:
```
Received: 
	by <servername> …
```
where the blank line before the `by` is as-is in the e-mail header.

So @axel-h this is either your role (if self-hosted) or the one of your mail provider to mask this at the server level. There is nothing that can be done from client side. Excepted maybe using a VPN, Tor or something like that to masquerade the source with the exit gate.

**Comment by axel-h** [comment]
I confused now. I'm not running a mail server in the local network, but K9-Mail is talking to my ISP's mail server "in the internet" ie outside the local network. So how does my ISP's mail server know the fully qualified host of the android device where K9-Mail runs on? All that matters for the ISP's mail server there is the IP address `${my IP assigned by ISP}` assigned by my ISP to the proxy/gateway/router, because that's the only thing visible.
Thus I assumed K9-Mail has to put this name somewhere in the implementation of IMAP, POP3, SMTP ... or is this there something in the lower network layers, so the OS's network stack "leaks" the name.

**Comment by cketti** [comment]
Might be the HELO/EHLO argument. See #2793

**Comment by axel-h** [comment]
Yes, thanks!
