### ISSUE TITLE
Reading New Mail Broken

### ISSUE THREAD

**Issue by scribe777** [k9mail/k-9#3071]
For the past few months, K9 Mail no longer allows me to read unread mail in order. I order my mail with newest at the top. When I have new mail, I scroll down to the first unread messages and click. When I delete this message, K9 Mail previously showed me the next unread messages. Now it seems to sort the read email together which causes the 'next message' to be mail I have already read, requiring me to hit delete, next, next, next,... to get to the next  unread email. It is no longer practical to read new email with K9 Mail when sorting messages to show newest first.

**Comment by cketti** [comment]
Nothing has changed in K-9 Mail regarding this. 

There are a couple of things that can influence the "next message" behavior. One is the setting "Show next message after delete" (see https://k9mail.github.io/documentation/settings/global.html#interactionshow-next-message-after-delete)
Another one is the sort order in the message list. You could change it to "Read/unread" which will sort by the read state, then the date.

**Comment by scribe777** [comment]
Dear cketti,
I don't believe you are correct.  I've used K9 mailed since Android first began and I've never had this problem reading mail.  I have taken a video to show you.  Here's the scenario:

1. I have ~20 new emails all shown at the top.
2. I click 2 interesting emails which I want to read first, which are at random locations in the list.
3. These 2 read emails now change locations in the list display.  They are at the top of my read email, with all of my unread (bold) emails grouped together at the top. This is fine, but it causes the following problem when reading the rest of my emails... as follows...
4. Click the bottom (oldest) unread email.
5. It shows fine and I delete it
*6*. HERE IS WHERE THE PROBLEM STARTS.  Now the first of the 2 interesting emails (step 3) shows.
7. I have to click <, which shows the next of the 2 interesting emails I read (again from step 3).
8. I have to click < AGAIN, to show the next UNREAD email.
9. Click delete and repeat steps 6-9 to view and delete each unread email.  It's a horrible pain.

Video attached in next comment.  Notice at the start of the video the 2 READ emails at the top of the list at times 5:47am and 7:02am, which are shown out of order now to the rest of my UNREAD emails and are the two emails I have to skip over (steps 7 and 8) to read each next UNREAD email.

**Comment by scribe777** [comment]
http://crosswire.org/~scribe/k9reorderedread.mp4
