### ISSUE TITLE
Feature request: Enable users to have custom default css for outgoing messages

### ISSUE THREAD

**Issue by doronbehar** [k9mail/k-9#3076]
Maybe it's a little bit too much to ask but It could be cool to have an option in the settings to change the default CSS style used when HTML messages are enabled defined in: [k9mail/src/main/java/com/fsck/k9/message/html/HtmlConverter.java
](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/message/html/HtmlConverter.java#L1283)

It could enable us solve #1166 as well.

### Environment
- K-9 Mail version: 5.402
- Android version: LineageOS 7.1.2

**Comment by cketti** [comment]
I don't like the idea. Rich text editing, yes. Arbitrary CSS rules, no.
