### ISSUE TITLE
K9-Mail github system clock off | web site posting from the future

### ISSUE THREAD

**Issue by mandree** [k9mail/k-9#3084]
The K9-Mail website contains a blog entry from the future:
https://k9mail.github.io/2018/01/17/5.4-Release.html

This is dated 2018 January 17th, but it's only 2018-01-12 today.

Please arrange for a report to be filed in the proper place, then reference here and close this issue.

**Comment by philipwhiuk** [comment]
https://github.com/k9mail/k9mail.github.io

**Comment by philipwhiuk** [comment]
Fixed in https://github.com/k9mail/k9mail.github.io/commit/259ce98cf752a3997e7267184e752bac6cf34a87
