### ISSUE TITLE
Unusually high data usage since the last Android update

### ISSUE THREAD

**Issue by BrainBeat1** [k9mail/k-9#3090]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
I guess average usage so maybe 100mb a day max but usually around 20mb.
### Actual behavior
Tell us what happens instead
Since the latest Android version was installed my k9 has been using around 1-1.5 gig of data. I have no real idea of what could be the cause of this problem other that I have sometimes noticed that it can get stuck trying to sync. I have not checked every day but I think a lot of the excessive data usage has tended to be during the night and morning. Why this is an issue is it doesn't seem to matter if you are connected via wifi or mobile data. This is how I noticed that the issue existed as I woke up one day and realised I had left mobile data on only and that 1.2 gig of data had been used. I want to also point out that nothing else has changed that I know of that could cause the issue.
### Steps to reproduce
I have no idea how to reproduce the problem as I am not sure of the cause.

1.
2.
3.

### Environment
K-9 Mail version:5.403

Android version:6.01

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We are aware of cases like this one, but have never been able to reproduce the behavior.
