### ISSUE TITLE
eMails not downloaded and / or shown in app

### ISSUE THREAD

**Issue by wedge100** [k9mail/k-9#3091]
Obviously K9 is connected to my eMail-server (positive connectitivity test), but eMails are not being downloaded and / or shown. This appears since one of the very latest updates.

### Expected behavior
eMails should be downloaded and / or shown

### Actual behavior
Obviously eMails are not being downloaded and / or shown

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.403

Android version: 4.4.2 on Huawei MediaPad X1 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Please provide a debug log and preferably your server software.

**Comment by wedge100** [comment]
Hi Philip,

 

I do not know how to generate a debug log. And I even do not know, which server software my email provider is using..

 

Greetings…

 

 

 

Von: Philip [mailto:notifications@github.com] 
Gesendet: Montag, 15. Januar 2018 16:56
An: k9mail/k-9 <k-9@noreply.github.com>
Cc: wedge100 <framuwi@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [k9mail/k-9] eMails not downloaded and / or shown in app (#3091)

 

Please provide a debug log and preferably your server software.

**Comment by cketti** [comment]
See https://github.com/k9mail/k-9/wiki/LoggingErrors
