### ISSUE TITLE
unencrypted e-mail copy in trash folder

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#3096]
in coherence to #3005 

Problem is, that every outgoing e-mail will be copied into trashfolder. The bigger problem is that this will always done with encrypted e-mails, and they will be copied there in plaintext (withoud the signature and cite, only the tipped text)!

### Expected behavior
E-Mail will not copied to trash folder

### Actual behavior
E-Mail will be copied unencrypted to trash folder

### Steps to reproduce
1. write a new e-mail
2. choose "active encryption"
3. send email

### Environment
K-9 Mail version: 5.402 (F-Droid)
OpenKeychain Version: 4.8.1

Android version: 7.1.2 LOS 14.1-20171213

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP https://mailbox.org & self hosted

**Comment by cketti** [comment]
This is probably because of automatically saved and overwritten drafts. See #2261.
