### ISSUE TITLE
Mark read notification not working but reply does

### ISSUE THREAD

**Issue by aucklander** [k9mail/k-9#3106]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
It should mark the email as read and dismiss the notification.

### Actual behavior
Pressing the button does nothing.

### Steps to reproduce
1. Receive email notification
2. press mark read

### Environment
K-9 Mail version:
5.403
Android version:
8.1

Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by philipwhiuk** [comment]
WFM with the following verby log:

```
01-18 22:08:53.003 14875-14875/com.fsck.k9.debug I/CoreService: CoreService: com.fsck.k9.notification.NotificationActionService.onStart(Intent { act=ACTION_MARK_AS_READ flg=0x10000000 cmp=com.fsck.k9.debug/com.fsck.k9.notification.NotificationActionService bnds=[252,1548][1426,1716] (has extras) }, 1)
01-18 22:08:53.004 14875-14875/com.fsck.k9.debug I/NotificationActionServi: NotificationActionService started with startId = 1
01-18 22:08:53.007 14875-14875/com.fsck.k9.debug I/NotificationActionServi: NotificationActionService marking messages as read
01-18 22:08:53.050 14875-14942/com.fsck.k9.debug I/MessagingController: Running command 'queueSetFlag Home:INBOX', seq = 434 (background priority)
01-18 22:08:53.075 14875-14875/com.fsck.k9.debug I/CoreService: CoreService: com.fsck.k9.notification.NotificationActionService.onDestroy()
01-18 22:08:53.107 14875-14942/com.fsck.k9.debug I/MessagingController:  Command 'queueSetFlag Home:INBOX' completed
```

**Comment by nerjamartin** [comment]
Same problem here.

Environment:
- K-9 Mail ver. 5.403
- Motorola MotoG4 Plus
- Android 7.0 (3.10.84-ga9160e1, Feb 2018 Patch)
