### ISSUE TITLE
Signing outbound messages - feature missing in k9

### ISSUE THREAD

**Issue by 0x23marco** [k9mail/k-9#3128]
### Expected behavior
In a former release of K9 the signing of messages was possible.

### Actual behavior
Now there's only crypting of messages possible.

### Steps to reproduce
1. Compose new email
2. Options with 3 dots opening shows only activating crypto not signing

### Environment
K-9 Mail version: 5.403

Android version:
8.1.0 most recent patch level

Openkeychain version:
4.8.1(48002)

**Comment by Valodim** [comment]
This feature is disabled by default, because its usefulness is questionable. If you really need it, you can enable it in the settings.

Please see [here](https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html) for an explanation.
