### ISSUE TITLE
Text not quoted on reply to encrypted mail

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#3131]
### Expected behavior
When I reply to an encrypted mail (openkeychain) the text is not quoted. That was working until recently

### Actual behavior
One empty line with a '>' in front is 'quoted'

### Steps to reproduce
1. reply to encrypted mail
2.
3.

### Environment
K-9 Mail version: 5.403

Android version: 7.0 and 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
This bug is already fixed in `master`. A new version containing the fix will be released soon.

**Comment by coogor** [comment]
'Soon' seems to be a relative vague expression - we have end of August ....and nothing happened
