### ISSUE TITLE
Width of img tag isn't used

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3139]
Before loading images:
![screenshot_20180126-150553](https://user-images.githubusercontent.com/5685512/35447017-cc8f6d7a-02b6-11e8-9c7d-9bf054e19740.png)
After loading images:
![screenshot_20180126-151145](https://user-images.githubusercontent.com/5685512/35447020-ce79f0a6-02b6-11e8-8cb8-cf493be11f5d.png)

Width of the surrounding table and of the image are in the html, so that shouldn't be the issue, why the img is displayed wider, than it should be.

[Humble Bundle.zip](https://github.com/k9mail/k-9/files/1668218/Humble.Bundle.zip)

**Comment by cketti** [comment]
Sounds like a WebView issue. Not sure there's anything we can do about that.
