### ISSUE TITLE
Unfortunately, K-9 mail has stopped

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#3144]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
From within the inbox, I click on a message to open it.  it should open and display the message.

### Actual behavior
From within the inbox, I click on a message to open it.  Instead of opening it, I get a popup that says "Unfortunately, K-9 mail has stopped."  (that's the exact text) with two buttons :     "REPORT"    and "OK".  I click "OK" and brings me back to the Account List, not even the in-box of the account I was in.  Nor does the program actually abort.  This only happens on that one message, every other message  can be opened properly without issue.

This happens every so often on one our of hundreds of messages.  I've tried to copy and move the message to another folder and the exact same behavior occurs when trying to open that message regardless of what folder it is in.   It appears completely random and not related to any particular sender that I can tell.  

Viewing the message from a regular browser interface shows there's nothing wrong with it from that perspective.  

### Steps to reproduce
1.   Open a message from the inbox (to start) or any other folder if copied there.
2.   Seemingly randomly, one of many messages will not open and get the popup.
3.   All I do is double tap on a message within a folder to open it.

### Environment
K-9 Mail version:   5.403

Android version:  6.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by philipwhiuk** [comment]
If you click Report we will get a crash log in Google Play. So do that please.

**Comment by onetimep0ster** [comment]
I don't even get the popup. When i open into the unified inbox, it starts updating (turning wheel bottom-down left) and just dies / disappears from the screen. It's in the recent apps, but if i click it it does the same.
