### ISSUE TITLE
Read receipt doesn't work

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#3145]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I expect to get a "read receipt" from a message that was read after I sent it with "read receipt".

### Actual behavior
I send a message with read receipt.  At best, I get an immediate response saying it was delivered and never a "read receipt" once it was read.  At the least, nothing comes back at all even though it was both delivered and read.

### Steps to reproduce
1.   While composing a message, click on menu and "Read receipt"   
2.   Popup comes up and says "Will request read receipt" - then fades away
3.  Send message
4.   Wait for one of the two conditions above to happen ( at best a delivered receipt, at worst, nothing comes back)

### Environment
K-9 Mail version: 5.403

Android version:  6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
It is up to the receiving client whether or not a read receipt is sent when requested. K-9 Mail for example doesn't support sending one at all.
