### ISSUE TITLE
Add Ability to Synchronize Folders (Especially Draft and Archive) Bidirectionally for IMAP

### ISSUE THREAD

**Issue by butangmucat** [k9mail/k-9#3148]
### Expected behavior
When an IMAP synchronization takes place, local copies of emails in folders like draft and archive are uploaded to the remote server.

### Actual behavior
When an IMAP synchronization takes place, local copies of emails in draft gets first moved to trash, and then gets permanently deleted when trash is synchronized.

### Steps to reproduce
1. Write anything.
2. Save what you are working with as a draft.
3. Order a synchronization of your email account.

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2 (LineageOS 14.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (FastMail)

**Comment by JustAnonymous** [comment]
I posted this same issue a long while back, it's been fixed in the latest versions as far as I can tell.  5.208 is an older version.
