### ISSUE TITLE
Incompatible OpenKeychain API versions

### ISSUE THREAD

**Issue by KOLANICH** [k9mail/k-9#3149]
used api version: 12
supported api versions: 7, 8, 9, 10, 11

The k9mail is from f-droid. Before update (the old version had an old icon) everything worked fine. After update it had stopped. OpenKeychain have not been upgrader. Have someone downgraded k9mail to the old code base?

**Comment by cketti** [comment]
The minimum required Android version has been 4.0.3 (API 15) for years. See https://github.com/k9mail/k-9/wiki/ReleaseNotes

**Comment by KOLANICH** [comment]
@cketti, it's not about Android API version. It is about OpenKeyChain API version.

Strangely it was changed very long ago in 6acc2a17bb00007c7f40de05b935e01338e7298f but I got the error only after the recent update. Does your release cycle have half of year delay?

**Comment by cketti** [comment]
> Does your release cycle have half of year delay?

Sounds about right.

@Valodim: Do you want to chime in? What's the minimum required OpenKeychain version these days?

**Comment by dschuermann** [comment]
OpenKeychain >= 4.5 is required for API 12. Please upgrade, older versions of OpenKeychain are potentially insecure.

**Comment by KOLANICH** [comment]
@dshuermann, any version of any software is potentially insecure. Have any vulnrs been actually found and fixed?

**Comment by KOLANICH** [comment]
@dshuermann, as you see, it doesn't support api version 12, so any vulnr fixed after introducing v12 should suit.

**Comment by dschuermann** [comment]
@KOLANICH Not sure why I am doing this, but here you go:
https://github.com/open-keychain/open-keychain/commit/86e41f8996143816f0ebdff48a337c15cf8d512a

**Comment by KOLANICH** [comment]
1 Using files to share sensitive data is a vulnr itself. First it enables the secrets to be recove4ed later when root access is gained. For example if you decrypt and share an image, it is saved, then if the phone is hacked later and an adversary used photorec, the image may be recovered if nkt overwritten. Secondly it wears flash out. I guess fifo + procfs to access that fifo as a file should be used instead.
2 I don't see how this is a vulnr.
