### ISSUE TITLE
[Feature Request] make acount indicators hideable in list view

### ISSUE THREAD

**Issue by Rubylion** [k9mail/k-9#3154]
make acountcolors indicator hideable in the list view, to free up space and provide more place for the contact images. anyway, very good work, keep it up

**Comment by philipwhiuk** [comment]
The Account dots allow you to go to the unread only view of the folder. It's a particularly bad bit of UX though. In any case the intention is to completely remove this whole screen and use a navigation drawer so I don't really see value in adding more configuration at this point.

**Comment by cketti** [comment]
Fixed with #4181
