### ISSUE TITLE
cpen keychain: can´t find the keys 

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#3165]
imported keys from my phone to my tablet (lenovo yoga book) in open keychain (full encrypetd backup inclusive private keys) 
all keys are there in open keychain and generated some for email adresses i dont use on my phone
to keep is simple i can select open keychain as app but in the account settings i can´t select the keys
ˆbut on my asus zenphone 3 it works

### Expected behavior
select keys

### Actual behavior
no keys shown

### Steps to reproduce
1.open account settings 
2.cryptography
3.(no keys shown)

### Environment
Device
Lanovo yoga book (not working)  |  Asus Zen phone 3 (working)
K-9 Mail version:
5.403                                                 |  5.403 (please add an about version option in the menu)
Android version:
7.1.1                                                  |7.0
Account type (IMAP, POP3, WebDAV/Exchange):
imap.gmx.de (and same with gmail)
edit:
open keychain version
4.8.1                                                 | 4.8.1

need to deactivate the open keychain connection to send mails
gives out an cant connext to  the encryptuon service

(everything roughly translatet from german to english by me)

**Comment by wombalton** [comment]
Maybe I was wrong and it has to be the other way around: save your keys, uninstall openkeychain, reboot, install it again and select your key in account settings in k9.
