### ISSUE TITLE
K9 No Longer Auto Syncs since Last Update 2 weeks ago.

### ISSUE THREAD

**Issue by phoophan** [k9mail/k-9#3167]
Prior to the last major update 2 weeks ago, K9 has always auto sync'ed every 10 minutes as i requested. Since upgrade, it no longer auto syncs. Must manually drag screen down.

K-9 Mail version: 5.403

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):  all IMAP

**Comment by jimpop2** [comment]
I have the exact same problem.

K-9 Mail Version 5.403

Android Version: 7.0  (Kernel 3.18.31, Android SPL 1-Dec-2017)

Account Type: IMAP

**Comment by algorithminflux** [comment]
I believe I am also experiencing the same problem.

K-9 Mail Version 5.403

Android Version: 7.1.2 (Kernel 3.4.0, Android SPL 2018-01-05)

Account type: IMAP

**Comment by janomat** [comment]
I have the same Problem.

After transferring the k9 settings to a new Smartphone last week, the Auto Sync is permanently deactivated.

On both my Mailaccounts (same provider) as well as the account overview in the k9 app the Message "Synchonisation deactivated" is displayed at the top of the app window.
Manually syncing by dragging down works fine.
Neither Push or periodically syncing ist working.

Auto sync in Android and K9's settings is activated, I have found no restrictions to K9's Data usage in the global Android settings.


I have not had this problem with my previous Smartphone running Android 4.2.2.


K-9 Mail version: 5.403

Android version: 7.1.1

Account type IMAP

**Comment by jpopovitch** [comment]
My problem (listed above) disappeared after I deleted the IMAP Account and then added it back.  YMMV.

**Comment by algorithminflux** [comment]
I believe that my issue disappeared from the same actions as well.

**Comment by janomat** [comment]
I solved my problem today without deleting and entering the complete Account setttings in K9.

I first selected K9 not to be optimized in the Android Power Optimization Menu, but that alone did not have any effect.

Then I edited the selection of folders to be displayed in my main K9 Mailaccount:
![Screenshot 1 - Folders to dsiplay](http://janomat.net/github/k9bugs/Screenshot_20180214-K9_Folders2display.png)

After selecting "Only 1st Class Folders" instead of all, the message at the top disappeared instantly.
Messages are now received via push without delay. 

You might also check the Advanced settings, so the number of max folders to be checked with push is not too low.

K-9 Mail version: 5.403
Phone: Sony Xperia Z5 Dual  - E6633
Android version: 7.1.1
Account type IMAP

**Comment by moneill20** [comment]
Thank you janomat, this worked perfectly!  Thanks so much for sharing!

**Comment by cfogri1** [comment]
Can someone help me?  I have been using K9 mail for 6 years to monitor my ATT.net email with a POP3 polling, I have always had it set to sync every 1 minute only the inbox . It always worked until a few weeks ago when I received updates, like the creator of this issue said above. I have tried all the recommended fixes above but my sync still goes to sync disabled after a period. I can not seem to find what is causing this issue. I am not a programmer. I use this mail system with a 
K-9 Mail version: 5.403

Android version: 7.1.1

**Comment by cfogri1** [comment]
Well, figured out how to fix my own problem. 

I did not hear from anyone on this support system, for k-9mail sad. 

But maybe others will be able to use my post to fix their issue with sync disabled. I found that the update Android did a few weeks ago version 5.403 put all the Apps installed on my phone on a BATTERY OPTIMIZED setting, which included K9-mail, so when the App was placed in OPTIMZED status, it would stop the sync when this mode was enabled. I used this link below to change the OPTIMIZED status of the K9-mail APP to "NOT OPTIMZED". Follow the directions in this link and you should be good to go. It fixed my K9-mail and it now syncs 24/7 without failure and when I go between my home network and cell service 4G and back to home wifi the sync always stays active now.
 
https://android.gadgethacks.com/how-to/android-basics-disable-doze-app-standby-for-individual-apps-0168960/

**Comment by nyetwurk** [comment]
Pixel 2, 8.1.0, optimize off, dovecot server
Same issue. No suggestions above work.

**Comment by iMartyn** [comment]
@cfogri1 *THANKYOU!* this explains the sudden notifications when switching between wifi and 4g - and the irremovable "syncing disabled" header.

I guess now someone who knows android probably needs to make a service worker that does this as an option.

**Comment by Cindy62707** [comment]
K9 will not sync on one of my accounts.   It may randomly sync once a day even though it is set to sync every 15 minutes.  Manual sync will not sync new emails either.  I cannot get any new emails on this account today but if I go on my computer out to the ISP site I have plenty of new emails.   K9 is set to use all the battery it wants,  I've tried Polling All folders and also just 1rst Class folders.  I've changed the sync time from every 15 minutes to every 10.  I've deleted and readded the account.  I've rebooted my phone.  Nothing helps.  The other accounts do not sync as scheduled but they will sync with a manual sync.  Settings on this account compared to the other accounts are identical (including the same ISP on 3 other accounts).  I've reported the problem on feedback several times.  Just like I've reported that K9 crashes most of the time whenever I try to delete any emails from this account.  No reply from the developers at all.  If they don't care to fix the problem, then I need to start looking for a different email app.  Can anyone suggest a good one for Android phones?  Or can anyone tell me how to fix this annoying problem?  I need access to my emails when I am away from home.  Thank you!

**Comment by wiesl** [comment]
Any update on this really annoying bug?

**Comment by llarsson** [comment]
If I clear all running apps and then open only k9, it will have sync enabled. Opening a too resource intensive app, like Firefox or a game, makes sync stop working.

So if that means it gets put very deep in the background or something, I don't know. 

Seriously, this is my only annoyance with k9. How does e.g. Signal work? It never loses ability to sync.

**Comment by cketti** [comment]
Probably Doze related. 5.600 should work better.

**Comment by wiesl** [comment]
Can you please push it to Play Store. Thnx.

**Comment by jameshibbard** [comment]
I ran into this issue on a fresh install of K9 on Android 11.
The fix suggested by @cfogri1 solved things for me.
However the link in their post wasn't working, so I ended up following this: https://www.thecustomdroid.com/disable-doze-specific-apps/

**Comment by jeffreycyr** [comment]
Me too.
