### ISSUE TITLE
Menu has double entries of Outbox as an option

### ISSUE THREAD

**Issue by sahiljolly1604** [k9mail/k-9#3177]
![sample1](https://user-images.githubusercontent.com/33859141/36068856-19742e78-0f05-11e8-8e12-33d6fb5474dc.PNG)
![sample3](https://user-images.githubusercontent.com/33859141/36068857-19bd8b5e-0f05-11e8-97f8-ffe1927f5b3b.PNG)

**Comment by tico-tico** [comment]
+1 metoo bugspam. here's my *gmx.com* folders:
![screenshot](https://user-images.githubusercontent.com/10702026/36286709-ee8f4b1e-12c1-11e8-99c1-390afd592aec.png)

The first one is in Russian *Исходящие* and the second's in English *OUTBOX*.

**Comment by cketti** [comment]
K-9 Mail uses an internal folder to store messages that have yet to be sent. Your server most likely contains a folder named "Outbox" as well.
The next stable version of K-9 Mail will display the internal folder using a special icon. The other folder will most likely be displayed with a regular folder icon.
