### ISSUE TITLE
Add intent for start writing an email

### ISSUE THREAD

**Issue by HolgerJeromin** [k9mail/k-9#3187]
I can receive mails via imap from any ip.
But for sending mail I need to be in vpn.

It would be nice if k9 can send a special intent when I start writing an email. With tasker/macrodroid it would be possible to connect with openvpn. When the mail is written the connection will be set up and my mail can be sent.

Perhaps "start sending a mail", "all mails are send" are nice timings for intents, too.

**Comment by cketti** [comment]
I don't want to add and maintain features that are only interesting to a super small number of people. 

Maybe you can use the SOCKS proxy mechanism (#980) once it is implemented to build a custom solution.
