### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [k9mail/k-9#3191]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by kamil0074** [comment]
I plan to work on it (mostly because I need to contribute to open-source projects to pass my subject at university). Are there any specific suggestions how it should look like or be done?

**Comment by c-e-p-x-u-o** [comment]
I'm interested too.

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

so it's a BUG and not a RF more

**Comment by cketti** [comment]
Fixed in `master`.

**Comment by 532910** [comment]
What about to release it?
