### ISSUE TITLE
Multipart multiline subject decoding error

### ISSUE THREAD

**Issue by tico-tico** [k9mail/k-9#3194]
![screenshot3](https://user-images.githubusercontent.com/10702026/36417618-7e555d28-163d-11e8-9dfb-c957657ddccf.png)

The borked word should be **адреса**

Subject from the email source:
```
Subject: =?utf-8?B?0J/QvtC00YLQstC10YDQttC00LXQvdC40LUg0LDQtNGA0LXR?=
 =?utf-8?B?gdCwINGN0LvQtdC60YLRgNC+0L3QvdC+0Lkg0L/QvtGH0YLRiw==?=
```

I see that you've done some changing on that matter in the current master branch, but since I have no idea how to obtain a nightly release build, I report this anyway just to be sure.

Edit: using the last version from the play market 5.403

**Comment by cketti** [comment]
The bytes of an UTF-8 encoded character are split between the two MIME encoded words. That's not allowed according to the standard. So decoding errors like this are to be expected.
But it's a common mistake that I believe even K-9 Mail is still making. The code in `master` already contains changes to decode this to the expected "Подтверждение адреса электронной почты".
