### ISSUE TITLE
Could K9 have an option to add Shared attachments to existing drafts?

### ISSUE THREAD

**Issue by ssb22** [k9mail/k-9#3197]
Apps like [StereoMatch's Amazing MP3 Recorder](https://play.google.com/store/apps/details?id=com.stereomatch.mp3.audio.recorder) can Share their recordings with K9 Mail, but when they do so, a new message is created with blank To, Subject and Body fields and just the recording attachment.  It would be very nice indeed if there were some way the recording could instead be attached to an existing draft message if there are any existing draft messages.

Then a user could, for example, press Reply on a message in their inbox, go into the recording app, record something, Share it with K9, and have the recording attached directly to the reply that they've already started.

Right now if you want to do that, you either have to fill in the To and the Subject all over again, or else forego the use of the Share function and instead save the recording to a file and then navigate to it from the Attachment menu of the reply.

Thanks.

**Comment by cketti** [comment]
Implementing something like this is non-trivial. Getting the UX right is probably even more challenging. I don't think the benefit of having this feature warrants the development and maintenance costs.

You should still be able save the recording somewhere, then use K-9 Mail's "add attachment" functionality to add the recording to an existing draft.
