### ISSUE TITLE
K9 is downloading gallery.mailchimp.com images when configure not to display

### ISSUE THREAD

**Issue by aceghostwind** [k9mail/k-9#3200]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Settings->Accounts->Reading mail-> Always show images = NO
Image should not be downloaded or displayed in html email
like this link
https://gallery.mailchimp.com/da650b0b9dc5fe08c6afd4519/images/1b85961a-854f-43d1-a71a-82436d659157.png

### Actual behavior
Tell us what happens instead
Image is downloaded and displayed, infringing privacy

### Steps to reproduce
1. Settings->Accounts->Reading mail-> Always show images = NO
2. Send html email from mailchimp to email account
3. View email and picture from this link is displayed https://gallery.mailchimp.com/da650b0b9dc5fe08c6afd4519/images/1b85961a-854f-43d1-a71a-82436d659157.png

### Environment
K-9 Mail version:
5.403
Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP4

**Comment by cketti** [comment]
Chances are you have once downloaded this image and it is now served from the cache. We do instruct `WebView` not to make any remote requests until the "Show pictures" button has been pressed.

Can you confirm that there is an actual network request being sent out even though the "Show pictures" button hasn't been pressed?

**Comment by aceghostwind** [comment]
I am not sure how to test that is there anyway I can clear the cache to test?

**Comment by aceghostwind** [comment]
I can confirm it was the cache. I am sorry for the bad bug report.
