### ISSUE TITLE
Gmail "AUTH PLAIN failed (username and password not accepted) error" used to work fine

### ISSUE THREAD

**Issue by WPFilmmaker** [k9mail/k-9#3206]
Since a few weeks ago gmail started to classfy k9-mail as not secure app, after tinkering with gmail I managed to create a password for k9-mal (which is a features gmail offers to deal with apps it considers not secure).

Everything worked fine for a few days but then I got  "AUTH PLAIN failed (username and password not accepted).

The weird thing is that sometimes the mail gets downloaded automatically so everything seems to be working but then the other times it fails. If i try manually to send or update my mail it throws that error.
Any idea on how to fix it?

### Expected behavior
I am able to send and receive emails from my gmail account

### Actual behavior
I get a "AUTH PLAIN failed (username and password not accepted).

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP)

**Comment by WPFilmmaker** [comment]
Update: After more tinkering seems that K9-mail had remembered the normal password (not the one time one gmail created for it), which is weird considering I had saved it and anyway k9-mail would get mails sometime but fail others...I had to create a new password for not secure apps and use it for k9-mal.It is working now but I still have no clue :/

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
