### ISSUE TITLE
Cannot copy quotation in mail

### ISSUE THREAD

**Issue by ltune** [k9mail/k-9#3208]
When copy text that contains nested quotation I cannot copy those information. This problem is related to #3207 and #3131. Alternatively, you can solve this issue, if you allow the user to display the ">", ">>" as text. 

### Expected behavior
When copy all text in a plain text email, options paste should return the full email text including the ">" , ">>" characters.

### Actual behavior
"Paste as text" does not contain any ">" characters. This can be seen as a feature.  Paste however show only a single bar where all the conversation should be.

### Steps to reproduce
1. select all mail or part containing quotations (better with second level: ">" and ">>")
2. copy
3. paste in any editor, e.g., droidEdit or in new k9 mail.

### Environment
K-9 Mail version: 5.403
Android version: 8.0.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
That's not something we can fix easily. We're using Android's `WebView` component to display the message and for that convert `text/plain` parts to HTML if necessary.

You could use the "Share" functionality together with "Copy to clipboard" from the Google Drive app (or [some other app that provides this functionality](https://play.google.com/store/search?q=copy%20to%20clipboard)). That will copy the `text/plain` part including the quote characters (`>`) to the clipboard.

**Comment by ltune** [comment]
Hi cketti, 
thanks for feedback. I can only choose share or copy when I select all text in the messgae view (WebView ?) But than share with Google drive or copy to clipboard does not include the ">" characters. Tried share with google disk, droidedit. I cpoief with system app, "clipboard actions”, "clip stack" and "native clipboard". There is only the text in the clip. Maybe different behaviour in android 8? Thanks and best regards, Adam

**Comment by cketti** [comment]
Use the "Share" menu option in K-9 Mail's "Send…" sub menu (two arrows pointing left, if displayed as icon).

**Comment by ltune** [comment]
OK, thx. So this will lead to empty text for content type application/pgp-encrypted messages as reported in #3131. So there is no real workaround but wait for #3131 ;). Thanks and best regards, Adam
