### ISSUE TITLE
Unable to receive e-mail on IMAP mail server

### ISSUE THREAD

**Issue by gregoryopera** [k9mail/k-9#3210]
### Expected behavior
Mail account should connect to mail server _and_ send/receive e-mail messages.

### Actual behavior
When I try to configure the incoming IMAP server of my domain, I am told:
_Cannot connect to server.
(Unable to connect)_

If I click "Continue", setup continues as per normal... However afterwards, I am only able to _send_ e-mail messages; _receiving_ e-mail messages does not work.

No further error messages are shown.

E-mail settings have been tested as working just fine (sending _and_ receiving) with other e-mail clients, all of which do not show any error messages.

### Steps to reproduce
1. Attempt to configure e-mail account - IMAP over SSL.
2. Click "continue" at error message.
3. Attempt to send an e-mail, then reply back to that e-mail from my computer.

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
There's already #1058 to improve error reporting.

If you want help in setting up your account please use the [mailing list](http://groups.google.com/group/k-9-mail). Make sure to include more details, like what mail server you're trying to connect to, which server settings you entered in K-9 Mail, and which server settings work in what other client.
