### ISSUE TITLE
Option "mail to:" missing.

### ISSUE THREAD

**Issue by johny77g** [k9mail/k-9#3211]
Hi, 
Is it possible to extend the capability of the APK with the option in the mail showing the name of the person the mail is directed to.
So besides the "mail from:" to have possibility to display "mail to:".  On PC with Thunderbird for example there is such option but for Android I did not find any mail APK having such option. I have one account with copies of the mail where I would like to see to who the mail is sent rather then from who.

**Comment by cketti** [comment]
K-9 Mail already displays the To address when the message was sent from one of your configured identities.
