### ISSUE TITLE
Application crashing after some time

### ISSUE THREAD

**Issue by kevujin** [k9mail/k-9#3222]
Maybe after android system update to my huawei k9 stopped working. 

### Expected behavior
Application will open or application will announce new messages

### Actual behavior
App closes after trying to open, no e-mails announced

### Steps to reproduce
1. Install k9
2. Set accounts
3. Wait
4. After some time app is dead

### Environment
K-9 Mail version: latest version classic or material desing (both has the problem)

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange):
All accounts IMAP

I was able to get filtered logcat, maybe it will help. It is attached to this issue.
[logcat.txt](https://github.com/k9mail/k-9/files/1758847/logcat.txt)

**Comment by cketti** [comment]
From the log it's not clear what is happening. Just this:
```
02-26 14:42:02.438 W/ActivityManager(  971):   Force finishing activity 1 com.fsck.k9.material/com.fsck.k9.activity.MessageList
02-26 14:42:02.697 I/ActivityManager(  971): Process com.fsck.k9.material (pid 11272) has died
```

I'd say it is more likely an issue with your device vendor's version of Android than a bug in K-9 Mail.
