### ISSUE TITLE
Feature request: Launcher icon selection

### ISSUE THREAD

**Issue by bboa** [k9mail/k-9#3225]
Hey,

so many people ask to change K-9 icon. :)

Will be fine to have selection from few icons, e. g. classic, new materialized, and generic with simple white envelope icon.

No way for me to add new activities, as in SuperSu, because I'm not a developer. But,  if someone implements this, the app will be more user-friendly.

**Comment by cketti** [comment]
There's no need to change the app for that. There exist numerous apps to do this, e.g. https://play.google.com/store/apps/details?id=com.sika524.android.quickshortcut
