### ISSUE TITLE
Automatic creation of contacts

### ISSUE THREAD

**Issue by suamikim** [k9mail/k-9#3228]
Hi,

does K9Mail automatically create contacts when writing and/or replying to an recipient which is not already listed in my phones primary address book?

I often find entries in my phones address book which were not created by me and only contain E-Mail-Addresses.

The address book in question is synced to my nextCloud via a CardDAV sync plugin.

My guess is that those contacts are either created by K9Mail on my phone or by an CardDAV plugin in my private Roundcube installation but I think I can rule out the plugin or Roundcube itself [see this issue](https://github.com/blind-coder/rcmcarddav/issues/216).

Is it possible that K9Mail automatically creates those contacts and can I stop it from doing it if so?

Thanks & best regards

**Comment by cketti** [comment]
K-9 Mail does not automatically create contacts.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
