### ISSUE TITLE
"Load 25 more messages" disappeared

### ISSUE THREAD

**Issue by internationils** [k9mail/k-9#3233]
Hello,
since updating to 5.500 (possibly a little bit earlier?) the "Load 25 more messages" disappeared from within the folders, so I cannot load older messages. Running 6.0.1 on a Nexus 5

**Comment by philipwhiuk** [comment]
Have you got any more messages that would be visible based on your settings?

**Comment by internationils** [comment]
Ah, gotcha, "Sync messages from ...last 2 months" was set, and these were older. I thought that the 25 messages or 2 months meant "load max 25 messages from max 2 months" and that "load 25 more" would have loaded messages older than 2 months as well.
What happens when the 2 months is extended to 6 months, will each sync look through 6 months for the relevant folders, or will it locally keep 6 months and only sync additional new mails (so 1x 6 mos + new mails)? I'm trying to keep the syncing down a little for huge mailboxes

**Comment by philipwhiuk** [comment]
Looking for the number of messages is cheap. If you increase the number from 25 messages that's where you'll see a lot more data and disk usage I think.

**Comment by internationils** [comment]
OK, thanks... I'll close the issue then.
