### ISSUE TITLE
Show main folders broken when changing the assigned folders

### ISSUE THREAD

**Issue by mxa** [k9mail/k-9#3234]
Atop of bug https://github.com/k9mail/k-9/issues/633 that K9 insists of localized IMAP folder names

### Expected behavior
Since K9 can't delete the plethora of now empty folders it created, I want to at least hide them. When selecting the 'show only main folders' option, I want to see only the folders that are actually configured and in use with IMAP

### Actual behavior
The wrong folders are hidden. The now active Sent, Drafts, Trash, Spam are not visible any more. Instead I only see the empty folders that K9 has created but are not useful for me.

### Steps to reproduce
1. Set up account on localized phone that is already in use with another imap client that uses the standard names folders.
2. fix (change) folder assignments manually in K9 so they match the non-localized standard names. 
3. select option to only show main folders.

### Environment
K-9 Mail version: 5.403

Android version: 7.1.1

Account type: IMAP

**Comment by cketti** [comment]
https://k9mail.github.io/documentation/folders.html
