### ISSUE TITLE
Ability to disable pull-down-to-poll-mail-server

### ISSUE THREAD

**Issue by yippeeyo** [k9mail/k-9#3240]
Is it possible to have a check box to disable the pull-down-to-poll-mail-server functionality in the inbox?

There is a already a button to manually poll-mail-server in the menu.

As with many users who come to from a stock email app, we have a habit of scrolling to the top of the inbox but do not know if we have reached it until we pull down again and this results in an unnecessary poll.

Is there any way I can disable this functionality while waiting for this to be reviewed?

Keep up the good work!

### Environment
K-9 Mail version: 5.409

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
We want to cut down on the number of settings not add more to make every little bit of the UI configurable. 
Nowadays there's no such thing as a stock Email app. Every vendor does its own thing. Google experience devices ship with Gmail which has the same behavior as K-9 Mail.

You can explore whether you're at the top of the list by swiping down but not lifting your finger off the screen. If you see the refresh indicator simply move your finger up until the indicator disappears. That way you won't trigger a refresh.
