### ISSUE TITLE
Shows email address instead of name if name has an '@' in it

### ISSUE THREAD

**Issue by chris-y** [k9mail/k-9#3241]
### Expected behavior
In the message list, and at the top of the email when opened, it should show the name portion of the From: header if "show correspondent's name" is enabled in settings.

### Actual behavior
It shows the sender's email address instead of their name.

### Steps to reproduce
1. Ensure "show correspondent name" is enabled in settings
2. Receive an email where the name portion contains '@'.  I have a forwarding service which puts the sender's real address in as part of the name, then <mailforward@service.net> as the address.  I suspect having an address as part of the name is confusing k9, even though the actual address is contained in angle brackets and being picked up correctly.
3. Look at the sender in the message list (and within the email).

### Environment
K-9 Mail version: 5.501

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by chris-y** [comment]
Example"from" header from recent email exhibiting this problem:
From: "Cineworld  - info@cineworldmail.com" <mailforwards@cloudmails.net>

**Comment by philipwhiuk** [comment]
This should be fixed already in 5.501 by #3120 :(

**Comment by chris-y** [comment]
That looks suspiciously like it may have created this problem.  It's seeing the email address in the name and deciding it should show the proper email address instead, even though the address in the name part isn't a valid address (it has spaces in it).  If this is as intended perhaps we can have an option to switch it off?

**Comment by philipwhiuk** [comment]
Oh. I thought you were complaining it did this. No, doing this is intentional and won't be fixed. It's a security vulnerability to do different.

**Comment by chris-y** [comment]
OK fair enough, although I would think having a name of "PayPal support" and a bogus email address would be a similar security risk, if only the name is shown?
I've taken this up with the forwarding service to see if they can remove the '@'.

**Comment by philipwhiuk** [comment]
I think if you add them as a contact, you can override the security feature.

I agree that the email is no guarantee of sender authenticity  either.
