### ISSUE TITLE
K9 crashes while syncronizing, if mail had been deleted from server externally

### ISSUE THREAD

**Issue by blackpeter61** [k9mail/k-9#3250]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
If I synchronize my mail account manually and a mail had been deleted (or moved) on the server (e.g. from a different mail program), K9 mail should delete it also from its list and fetch new mails.

### Actual behavior
K9 mail crashes and jumps back to main view (mail accounts). If I try to synchronize from there, the program crashes completely. If I delete all mails locally before I synchronize, there is no problem.

### Steps to reproduce
1. synchronize account
2. delete mail from server (from external computer)
3. synchronize again -> crash

### Environment
K-9 Mail version: 5.4.03 
I also tried with older versions, because I know it has worked before. Most failed. Version 5.009 works as expected

Android version: 5.1
I have another phone with Android 5.1.1 where everything works with K9 Mail 5.4.03 

Account type (IMAP, POP3, WebDAV/Exchange): POP3 & IMAP

[k9_logcat3.txt](https://github.com/k9mail/k-9/files/1800740/k9_logcat3.txt)
[k9_logcat4.txt](https://github.com/k9mail/k-9/files/1800741/k9_logcat4.txt)

**Comment by pklinkov** [comment]
I was having this problem, but as of 5.600 the problem cannot be reproduced.

**Comment by blackpeter61** [comment]
Thanks for the information. So maybe this is fixed now. In the moment i'm happy with the old version (prefer the old icon anyway ;-) )

**Comment by pjgfi** [comment]
Hello,
I had the exact same problem last week with version 5.600, IMAP account.
Application crashes (but stays in the background) or jumps back to folders screens.
Can't sync new emails.

**Comment by cketti** [comment]
The only thing I can find in the logs is this:
```
F/libc    (28792): external/sqlite/dist/sqlite3.c:91450: sqlite3DeleteFrom: assertion "pPk || iDataCur==iTabCur" failed
F/libc    (28792): Fatal signal 6 (SIGABRT), code -6 in tid 28813 (MessagingContro)
```

Maybe the same as #2955. In any case, this is most likely a bug in the Android version of the device that K-9 Mail triggers, rather than a bug in K-9 Mail itself.

**Comment by pjgfi** [comment]
Thanks for your answer cketti. The phone is a Huawei as in post #2955 so it has to be device related...

**Comment by blackpeter61** [comment]
...or use the older version of K-9 Mail as I do....

Thank for your answers anyway

**Comment by pjgfi** [comment]
Thanks for the tip Blackpeter61!

But... if it works with older versions of K9-Mail, is it really a device related bug?
Has K9-mail changed its syncing routine that much between 5.009 and later versions?
