### ISSUE TITLE
Improve wording of "show unencrypted signatures"

### ISSUE THREAD

**Issue by jeaye** [k9mail/k-9#3251]
### Expected behavior
In the global crypto settings, "Show unencrypted signatures" should say something more clearly explaining that it's for enabling the verification of signed-only emails. I propose the following:

* Validate signed-only emails
    * Signatures of unencrypted emails will be displayed

### Steps to reproduce
1. View global settings > crypto

### Environment
K-9 Mail version: 5.403

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by Valodim** [comment]
I'd like not to use "validate", because nothing is "validated" in the sense that it is "made valid" in this context. I also think "signed-only" is a confusingly technical term.

How about changing the summary text (on/off) like this?:

* All signatures will be displayed
* Only encrypted signatures will be displayed

**Comment by jeaye** [comment]
> I'd like not to use "validate", because nothing is "validated" in the sense that it is "made valid" in this context.

That's not the only meaning of validate. From WordNet:

      2: prove valid; show or confirm the validity of something [ant:
         {invalidate}, {nullify}]

> I also think "signed-only" is a confusingly technical term - "only" as opposed to what?

As opposed to signed *and* encrypted, which is what k9 supports by default. This toggle is specifically for showing (and validating) signatures for emails which are only signed and not encrypted.

> How about changing the summary text (on/off) like this?:

I'm ok with those; they're better than what the app currently shows.

**Comment by Valodim** [comment]
> That's not the only meaning of validate

Right, but I think that isn't so obvious to someone who isn't already aware of what a signed-only mail is. And given the proposition "should I validate mails when you read them, or not?" most people who don't know what that means will likely say sure - if something can be made more valid when I read it, go for it!

Anyways, see #3276 for related changes
