### ISSUE TITLE
Feature request: Poll for all - ignoring all folder settings

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#3261]
Hi awesome K9 Team!

"Playing" around with several options K9 offers I'm missing one feature which would make my life much easier. Hopefully not only mine :-)

I'm using a cheap smartphone (Lenovo C2) with Android 6.0 and, not that much, 1 GB RAM. 

Currently I'm using K9 to deal with 8 email accounts, all type IMAP, all PUSH. And some of them used for years, means that below "Archive" are several subfolders like e.g. "2010" and "2010.sent" etc. Altogether some GB of emails serverside, est. 15.000 emails. K9 set to retrieve max 32KB at first. 

All of these email accounts are used with K9, more and more mostly. But also via Thunderbird on Linux, Roundcube Webmail wherever and e.g. an old iPad.

Because my  Lenovo C2 also offers only 8GB of flash memory, I'm using Android 6+ "Adoptable Storage", means an sdcard encrypted and mounted as "internal storage", fully accessible for apps which have set "android:installLocation", which K9 kindly does. Not that fast, but working fine :-)

Because of this not that big RAM size, I'm frequently affected from getting K9 "wiped" out of active apps, or however Android devs might call this. Visible to me as user is that once K9 got "wiped out" from memory, K9 shows "Syncing disabled" shortly when reactivated. 

FYI I've read FAQ 'Why is K-9 telling me, “Syncing disabled”?' and issue #857 (Figure out how to deal with Doze (Android 6+) ), that's why I've set K9 to "Sync - Always" and excluded K9 from "battery optimization". 

If K9 setting "Poll when connecting for push" is set, K9 does what it should, but polls EVERY TIME K9 gets reactivated from a "wipe-out". NOT setting "Poll when connecting for push" means folders not in sync.

As (of course) most changed apply to INBOX and JUNK folders, I've reduced PUSHing to always only these two (1st class - push only 1st class). 

To avoid ages-long and traffic-wasting frequent polling of my many, but mostly unchanged IMAP folders, I've disabled "Poll when connecting for push", set "Folder poll freq" to "never" and use only a manually started poll on demand, when needed, e.g. after returning from an "airplane mode".  Poll folders are the same than PUSH, INBOX and JUNK.

But to get ALL folders synced, it would be cool to have an option to POLL EVERYTHING, ignoring folder classes, so without the need to change folder (poll) classes and poll options for many accounts and their folders. 

I've checked that I can manually trigger a poll for each folder by pushing the list section downwards even for 2nd class etc folders, so the "ignore" functionality seems to be there.

**Comment by cketti** [comment]
This seems like edge case functionality. I'd rather spend time fixing the many issues that lead you to consider this solution.
