### ISSUE TITLE
Translation source: missed variables for "one" plurals

### ISSUE THREAD

**Issue by bboa** [k9mail/k-9#3268]
Hi, variables missed in two source strings with keys "dialog_confirm_spam_message" and "settings_import_accounts".

It's good for English, but Russian need to use <item quantity="one"> for 21 or 61 count. Other languages also may have the problems here.

Please simply add required variables to "one" variant in source strings. Transifex have strong syntax control, so translators can't override this.

P. S.: @cketti please give [me](https://www.transifex.com/user/profile/bboa/) reviewer rights on Transifex, for Russian. I know that you are very busy, so unable to receive your answers for my questions via Transifex messages or IRC.

**Comment by philipwhiuk** [comment]
This is really annoying. Because in English we don't want to add the variable. And Transifex just pulls the English as the source.

**Comment by bboa** [comment]
@philipwhiuk thanks for answer.

What if I'll make separate PR and try to fix this manually.
Is there a way to prevent strings overwrite after Transifex sync? Hypothetically

**Comment by bboa** [comment]
Seems that best way is to contact Transifex team and ask to fix this. I'll try.
