### ISSUE TITLE
Did you see your profile on Liberapay?

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9#3269]
5 users already pledged to donate you some money on Liberapay: https://liberapay.com/on/github/k9mail

**Comment by cketti** [comment]
See also: https://f-droid.org/en/2018/03/02/liberapay-support.html

@philipwhiuk @Valodim: Your thoughts on this? I guess we could give it a try. Use the money to print K-9  stickers to give away or something like that.

**Comment by philipwhiuk** [comment]
Closing as we've set this up.
