### ISSUE TITLE
Sort and Compose functions aren't accessible in portrait mode

### ISSUE THREAD

**Issue by HenriDellal** [k9mail/k-9#3270]
### Expected behavior
Sort and Compose functions are accessible in both orientation modes.

### Actual behavior
I can see these buttons only in landscape mode. While it has 9 functions accessible in landscape mode, it has only 7 in portrait mode, missing the mentioned ones.

### Steps to reproduce
You'll probably need to run it on a phone with specific screen size (4.5")
1. Go to Inbox folder.
2. Press on-screen or system menu button in portrait mode. You'll see 7 items in sum with Sort and Compose missing.
3. Repeat previous step for landscape mode. You'll see 9 items in sum.

### Environment
K-9 Mail version: I was trying a lot of versions, from the latest (5.403) to  4.*. All of them have this bug.

Android version: 5.1

**Comment by cketti** [comment]
You should find the "missing" actions in the overflow menu (the three dots). If not, that's likely a bug with your Android version. 
We have plans to change K-9 Mail to make portrait and landscape layouts more consistent. And with that hopefully less confusing.
