### ISSUE TITLE
Unable to save contacts from inbox mails

### ISSUE THREAD

**Issue by steoguitar** [k9mail/k-9#3271]
When I receive an email I'd like to save some of the addresses (that had received in CC the mail) by tapping on them.

When I do a long tap on this list of addresses it shows a pop up "addresses copied"
I can't select just one and if I paste on a new mail what it is copied and I erase the addresses that I don't need, mail is sent only to the 1st address

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Duplicate of #1120
