### ISSUE TITLE
KINDLY won't run

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#3273]
### Expected behavior
New install of k9 won't run. Crashes when try to open. 

Clue: previous install may have used SD card for storage. Now there's no SD card. 

But I uninstalled and reinstalled k9. Maybe old Config....
### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
Please use the issue template.

**Comment by johnyradio** [comment]
New phone and latest K9, not seeing this issue. 

thx
