### ISSUE TITLE
No support for nested folders

### ISSUE THREAD

**Issue by Oclair** [k9mail/k-9#3285]
Android app can't access mailboxes within mailboxes yet...

Seems like it may require an intension to work that way by the developers!!

Have a nice one, otherwise great app, I use it daily 

Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment]
We can.

We list them as Folder.Subfolder 

Better support is covered under #630.

If you aren't seeing them at all please fill in all the details in the issue template when you create a new issue.

**Comment by Oclair** [comment]
considering how well this app works for me, I was shocked to see nothing...

**Comment by Oclair** [comment]
As I am the server admin for my own mail server, I simply switched from nested to creating another folder on the regular mailbox folder level which works around this

**Comment by AvoidMastodonBlue** [comment]
Which mail server software?

**Comment by xsnoopy1958** [comment]
What is the plan regarding nested folders?

I work with a lot of mails and nested folders in Thunderbird on my laptop.
I would also like to do this on my tablet and cell phone under Android. This is no problem with the Maildroid app. But I really want to switch to Thunderbird/K9!
Without nested folders, this is unfortunately not acceptable for me.
What is planned regarding this topic?
