### ISSUE TITLE
Can't print to bizhub printers

### ISSUE THREAD

**Issue by TekyJeff** [k9mail/k-9#3286]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
If I load a printer driver (like KonicaMinolta Mobile Print), I would expect to be able to print an email using Share | Print.

### Actual behavior
KonicaMinolta Mobile Print says it can't

### Steps to reproduce
1. Load/configure K-9 Mail
2. Load/configure KonicaMinolta Mobile Print
3. Try printing an email using "Share | Print"

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3 to Telus.net

**Comment by cketti** [comment]
We share the message text using the standard share intent. It does work fine with other printing apps. So chances are this is not K-9 Mail's fault.

There is issue #1062 to add support for Android's printing API. However, this hasn't been a priority (and I don't see that changing).
