### ISSUE TITLE
Want only LED notifications, but get also sound and vibration

### ISSUE THREAD

**Issue by GambaJo** [k9mail/k-9#3287]
![screenshot_20180327-103301](https://user-images.githubusercontent.com/1378907/37956593-10d53f18-31ac-11e8-8438-8f2059c18af6.png)
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I configured K-9 so it should only notify me via LED. I don't want sound or vibration. (see my screenshot).

### Actual behavior
I get all of this notofications. LED and sound and vibration.

### Steps to reproduce
1. Configure like in my screenshot.
2. Receive an email.

### Environment
K-9 Mail version: 5.403

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (Posteo.de)

Phone: OnePlus One with LineageOS

**Comment by cketti** [comment]
We set up the notification as configured. If it's not working as expected it's most likely an issue of the Android version you're using.
