### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by mogmog2** [k9mail/k-9#3294]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by mogmog2** [comment]
From the 29th march, K-9 Mail Version: 5.403 on Android 7 has thrown a  SSL certificate error.

My wife, k9 on her phone (same is & k9) also has it. We have same host.

I haven't touched any settings

I can still get my email on my desktop from the host and I can't see anything in their status log about SSL certificates.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
