### ISSUE TITLE
Save encrypted copies of sent e-mail

### ISSUE THREAD

**Issue by v01d** [k9mail/k-9#3304]
### Expected behavior
For cases when one does not really trust the server (at least, in the long term) for e-mail storage or when one would like protection against database breaches, it is useful to have all e-mails stored on the server encrypted. At present, saving encrypted Drafts should be possible according to #2107. Maybe it is not that difficult to offer the same for Sent e-mails having that already implemented.

### Actual behavior
Emails sent non-encrypted are saved non-encrypted to the Sent folder.

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We're not looking into adding a feature where messages that were sent unencrypted are encrypted when being uploaded to the server's Sent folder.
