### ISSUE TITLE
reply button missing: ⚠

### ISSUE THREAD

**Issue by AvoidMastodonBlue** [k9mail/k-9#3305]
### Expected behavior
open any message click reply

### Actual behavior
reply button replaced with non functional warning triangle

### Environment
K-9 Mail version: 5.403 

Android version: 444

Account type (IMAP, POP3, WebDAV/Exchange):

all IMAP

**Comment by cketti** [comment]
Sounds like a broken installation. Try uninstalling, then reinstalling.

**Comment by philipwhiuk** [comment]
Settings -> Display -> Visible message actions

**Comment by hurzl** [comment]
> Settings -> Display -> Visible message actions

There I get Delete, Archive, Move, Copy, Spam, but no Reply

**Comment by philipwhiuk** [comment]
There's an overflow menu.

**Comment by hurzl** [comment]
The Reply item is hidden very deeply in that menu. Why is it not possibly to have both "Delete" and "Reply"?
