### ISSUE TITLE
Replying to email replies to all

### ISSUE THREAD

**Issue by tferg80** [k9mail/k-9#3307]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by tferg80** [comment]
Nothing? Cool.

**Comment by cketti** [comment]
Chances are the email you receive contains a `Reply-To` header with the value `city@work.com`. This asks clients to use this address when replying to the message. Which matches the behavior you're describing.
K-9 Mail doesn't have a "reply to sender" feature which ignores the `Reply-To` header. You could use "reply all" and then remove the unwanted recipients.

**Comment by Valodim** [comment]
This seems odd. Does the recipient in question perhaps set a weird Reply-To header? You can check using "show headers"

**Comment by tferg80** [comment]
Nope. It doesn't happen to anyone else and it doesn't happen to me when I use Thunderbird on my PC, or if I use gmail. It ONLY happens when using k9.

**Comment by Valodim** [comment]
Does "nope" mean there is no reply-to header? Or what does that header say?

**Comment by tferg80** [comment]
Also, cketti- that isn't the problem. I tried to be thorough in explaining, because I didn't want it to seem like that was the problem when it's not, so it's kind of shitty that you throw out an irrelevant answer and then close the thread.    

Valodim- i really appreciate you trying to help.  i'm going to give up and find a new app. This is too frustrating.

**Comment by tferg80** [comment]
Sorry! i'm too irritated at the closing of the thread when I didn't get the problem resolved. But I do greatly appreciate YOUR attempt to help.   I'm just going to say f it and find another app.

**Comment by cketti** [comment]
If it's not `Reply-To` it's probably `List-Post` (see #2588). Answer remains the same, there's currently no way to get the behavior you're looking for with K-9 Mail.
