### ISSUE TITLE
Mail answer can be deleted after K9 has been suspended

### ISSUE THREAD

**Issue by SR-gh** [k9mail/k-9#3312]
This one is really annoying : 

1. Reply to a message : redaction activity starts, allowing you to write an answer.
2. Type « Back » button : an alert warns you that you're about to loose your answer.
3. Cancel the alert : you can continue editing your answer.
4. Wait for your device to lock your screen : the activity is probably suspended.
5. Unlock your device : the K9 activity is back alive, you can continue editing your answer.
6. Press the back button : you go back to the list of messages and **you've lost your answer with no alert at all**.

Expected behaviour : Step 6 should launch an alert, as step 2 did.

K-9 Mail version: 5.403
Android version: 6.0
Account type : IMAP

**Comment by cketti** [comment]
I believe this was fixed in 5.600
