### ISSUE TITLE
Replying to an email that was encrypted (openkeychain) to does not quote body/content, only the header

### ISSUE THREAD

**Issue by matt812** [k9mail/k-9#3313]
### Expected behavior
Body/content should be quoted under the quoted header of the email that we are responding to.

### Actual behavior
The header is quoted, but the content is not used at all.  It is just the end of the email (except for signatures).

### Steps to reproduce
1. Install K-9 Mail and setup your account in it (I used gmail)
2. Install Open Keychain and setup a personal identity/key in Open Keychain and associate it with your account
3. Send an email to yourself, encrypted (and put something in the body/content).
4. When you get it, reply to it, and notice the quoted email below your cursor.  That is where the quoted content from the previous email should be, but is not.

Note that if the email received was not encrypted, replying works as expected.

### Environment
K-9 Mail version: 
5.403 (from f-droid)

Android version: 
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP gmail

**Comment by Valodim** [comment]
Hi, thanks for your report! This is a known issue, and should be fixed in version 5.501

**Comment by craftyguy** [comment]
@Valodim are you sure you didn't mean some other version? 5.501 has been out for ~10 days and doesn't mention this fix: https://github.com/k9mail/k-9/releases/tag/5.501

**Comment by 7Z0t99** [comment]
I just ran into the same issue in 5.403 and can confirm that at least 5.503 works.

**Comment by marmistrz** [comment]
Seems to work fine on 5.600
