### ISSUE TITLE
Can´t see nested IMAP folders

### ISSUE THREAD

**Issue by berne** [k9mail/k-9#3314]
Context: created IMAP account, security: STARTTLS, normal password, auto-detect IMAP namespace.
The IMAP server is a Mercury Mail Server v4.8, it has a self-signed certificate.
On this server, folders which have subfolders may not have emails in them (only one or more subfolder). Folders that have emails in them may not have subfolders.

### Expected behavior
see IMAP folders including nested subfolders.
"Show folders" is of course set to "All folders".
Bluemail shows all folders with the same account settings (see snapshot below)

### Actual behavior
I see only Drafts, Sent, Spam, Trash, Inbox and Outbox. See snapshot:

![screenshot_2018-04-08-13-13-10](https://user-images.githubusercontent.com/483772/38467226-69c551c0-3b35-11e8-8715-3b3d7570379f.png)
In Bluemail the hierarchical folders appear:
![screenshot_2018-04-09-07-42-50](https://user-images.githubusercontent.com/483772/38481214-e9df5e66-3bc9-11e8-9934-8065f9e11847.png)

This account has 50-100 folders nested up to 4 levels of hierarchy.
Interestingly, another IMAP account on the same server has only 2 levels of hierarchy, K-9 displays the folders of this other IMAP account correctly (i.e. I see all folders and subfolders)

![screenshot_2018-04-08-13-59-19](https://user-images.githubusercontent.com/483772/38467219-54265652-3b35-11e8-8427-f8b5c4c108e3.png)

### Steps to reproduce
1. create IMAP account
2. create 4 levels of nested subfolders with Thunderbird
3. Display folders with K-9

### Environment
K-9 Mail version: 5.403

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Have you tried refreshing the folder list.

Is Thunderbird persisting them to the server.

**Comment by berne** [comment]
- After many deleting and re-creating the IMAP account on K-9 and trying varied fetch  settings, I could not get K-9 to display the folder list. K-9 could not e.g. see the "Junk" imap folder which I wanted to link to the Spam. K-9 even created a "Spam" imap folderon on the server  without asking. 
- The Mercury imap server must have served that account improperly: Bluemail and Thunderbird can cope with it, but not K-9.
- Anyway, I created a new IMAP account on the server, re-created manually the folder tree, transferred all the folders from the old account to the new account manually with Thunderbird. K-9 can see the folder list of this new IMAP account. Pb solved.
