### ISSUE TITLE
Content-Disposition is wholly MIME-encoded when attachment filename has non-ASCII characters

### ISSUE THREAD

**Issue by sksthrs** [k9mail/k-9#3323]
When you receive a mail sent by k9mail with attachments which filename contains non-ASCII characters, you'd have an issue.

### Expected behavior
Received mail has attachments, same filename.

### Actual behavior
Received mail has no attachment.
(Artifact appears below the signature, which is the remain of the attachment)

In fact, Mozilla Thunderbird can handle attachments in this mail.

### Problem
k9mail encodes too much Content-Disposition with MIME when filenames of attachments contain non-ASCII characters.

#### Example

- filename : テスト文書.txt
- size of the file : 19 bytes

#### Expected
Content-Disposition: attachment;
  filename="=?UTF-8?B?44OG44K544OI5paH5pu4LnR4dA==?=";
  size=19

#### Actual
Content-Disposition: =?UTF-8?B?YXR0YWNobWVudDsNCiBmaWxlbmFtZQ==?= =?UTF-8?B?PSLjg4bjgrnjg4jmlofmm7gudHh0IjsNCiBzaXplPTA=?=

(This is same as Expected when decoded, but "attachment;", "filename=", "size=19" should not be encoded)

### Steps to reproduce
1. Send new mail in k9mail with attachment which filename is non-ASCII.
2. Receive it with k9mail.
3. You see no attachment.

### Environment
K-9 Mail version: 5.403 (current Play-store version)
Android version: 6, 7
Account type (IMAP, POP3, WebDAV/Exchange): IMAP, POP3 (WebDAV/Exchange are not tested)

**Comment by cketti** [comment]
This should be fixed with #3364.
