### ISSUE TITLE
New proposal logo for k9mail

### ISSUE THREAD

**Issue by artjeck** [k9mail/k-9#3334]
Hi Owner 😊
I am a graphic designer, I want to contribute a new logo for you application, before I start, I want to ask your permission first

Thank.

**Comment by ArchangeGabriel** [comment]
Well, this app is actually currently open to logo propositions. You should have a look there: https://github.com/k9mail/k-9/issues/1723.

So you might propose a new logo, but that won’t mean it will be accepted.

**Comment by artjeck** [comment]
Thank you for your response sir, I will observe it

**Comment by philipwhiuk** [comment]
Duplicate of #1723
