### ISSUE TITLE
Changing behavior when link gets pressed

### ISSUE THREAD

**Issue by greatjack1** [k9mail/k-9#3336]
I want to change the behavior when a link in an email gets pressed in an email. I looked thorugh the source code but could not find out where the current code for it is. Would someone be able to point me to the right place in the source code?

**Comment by cketti** [comment]
This is not a support forum. You could try asking on IRC (#k-9 on irc.freenode.net, or via [webchat](http://webchat.freenode.net/?channels=%23k-9)) where most of the developers hang out.
