### ISSUE TITLE
Feature Request: Message List Widget Tap Unified Inbox to Open Unified Inbox

### ISSUE THREAD

**Issue by CrafterLaughter** [k9mail/k-9#3350]
### Expected behavior
My hats off to whomever coded the Message List Widget.  It scrolls messages, the compose new message button.  Great job.

### Actual behavior
One possible improvement would be the ability to tap "unified inbox" in the top left and have it launch K9M into the app inbox view.  It appears their actually isn't currently an actioning button coded there such that Android just responds with the widget management placeholder as if one wanted to resize/remove/app info the widget.

I'm not saying that shouldn't exist as the unused portion of the widget taskbar can still serve that function, it would just be useful if "unified inbox" on the left could launch into the app instead of users having to launch into unwanted emails to jump into the app from the Message List Widget.

### Environment
K-9 Mail version: 5.403

Android version:  Android 8.1 171019.029 on a Taimen Handset

**Comment by WuerfelDev** [comment]
I think this is a similar issue to #3406 which should be fixed in #3491

Clicking doesn't do anything, but double click is like I would double click on the wallpaper, so maybe we need `clickable='true'`?

OnePlus 6 on Android 9

**Comment by cketti** [comment]
The fix didn't make it into 5.600. It'll be included in the next major version.
