### ISSUE TITLE
No synchronisation with Apple Mail after first setup

### ISSUE THREAD

**Issue by Steinardo** [k9mail/k-9#3353]
### Expected behavior
Receiving new mail from apple mail or synchronise mail reading status.

### Actual behavior
After the initial setup of the mail account, where all mails are synchronised from the mail server, no synchronisation is possible. Receiving and sending mails, synchronise reading status etc..  

Fault message by mail sending = SocketTimeoutException: failed to connect to smtp...

### Steps to reproduce
1. Auto config (first start) to apple mail (IMAP) 
2.Try to synchronise by drawing the screen down

### Environment
K-9 Mail version: 
5.403

Android version: 
8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

[k9-log.txt](https://github.com/k9mail/k-9/files/1934890/k9-log.txt)

**Comment by philipwhiuk** [comment]
The autoconfig details must be wrong.

**Comment by Steinardo** [comment]
Figured out what was wrong. Under Settings/Apps/Application List/K-9 Mail/Data usage/ both options Wi-Fi and DataUsage was disabled. Even after a new installation of the application. 

Now everything works well, sending and fetching mails.
