### ISSUE TITLE
please claim $1,322 bounty for PGP/MIME

### ISSUE THREAD

**Issue by maltfield** [k9mail/k-9#3360]
Hi,

It looks like PGP/MIME support was added over a year ago, and the long-standing bounty of $1,322 was never claimed.

 * https://www.bountysource.com/issues/815255-pgp-mime

According to the change log, PGP/MIME support was added to K9 Mail in 5.200-RC1

 * https://k9mail.github.io/k-9/changelog_5.2-MAINT_branch.xml

@cketti @obra @Valodim etc, do you know who was responsible for this addition?

**Comment by Valodim** [comment]
That was me. I tried multiple times, via mail and Twitter, but support there always stopped responding after an initial "will take care of it" reply.

**Comment by DPTJKKVH** [comment]
Can we help you with that in any way?

**Comment by DPTJKKVH** [comment]
@Valodim Can we help you with that in any way?

**Comment by Valodim** [comment]
This finally worked out, I received the bounty today! Thanks for reminding me :)
