### ISSUE TITLE
Updated WebView crashes the app when displaying an email

### ISSUE THREAD

**Issue by Whisprin** [k9mail/k-9#3363]
I recently upgraded Android Webview to version 66.0.3359.126
Since then the app crashes immediately after opening an email from the list. Rebooting the phone didn't help. Uninstalling the Android System WebView updates works temporarily. After upgrading the WebView again, K-9 starts to crash. 

### Expected behavior
The email is displayed normally 

### Actual behavior
The app crashes 

### Steps to reproduce
1. Update Android System WebView Version 66.0.3359.126
2. Launch K-9 Mail
3. Try to read an email 

### Environment
K-9 Mail version: 5.403

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
We can't do anything about buggy WebView updates. But this issue has probably been fixed by now.
