### ISSUE TITLE
Removing messages from SQLite fails when getting new mails via IMAP

### ISSUE THREAD

**Issue by neufeind** [k9mail/k-9#3367]
I see a list of messages previously fetched and try to get a list of new messages via IMAP. In the debug-log via adb I see it performed an IMAP-search fine, but then fails multiple times when trying to delete messages from SQLite.

05-01 16:07:23.103  1727  1743 V ImapConnection: conn69520061>>> 5 UID SEARCH 4590:4689 NOT DELETED
05-01 16:07:23.184  1727  1743 V ImapResponseParser: conn69520061<<<#null# [SEARCH, 9061461, 9061462, <shortened the UID-list here>]
05-01 16:07:23.185  1727  1743 V ImapResponseParser: conn69520061<<<#null# [FLAGS, [\Answered, \Deleted, \Draft, \Flagged, \Seen, $Forwarded, $MDNSent, Forwarded, $Junk, $NotJunk, Junk, JunkRecorded, NonJunk, NotJunk, redirected, $Label1]]
05-01 16:07:23.186  1727  1743 V ImapResponseParser: conn69520061<<<#5# [OK, UID SEARCH completed]
05-01 16:07:23.193  1727  1743 V MessagingController: SYNC: Got 100 messages for folder INBOX
05-01 16:08:08.075  1727  1976 W SQLiteConnectionPool: The connection pool for database '/data/user/0/com.fsck.k9/databases/005b07dd-5782-4d24-920b-581d833c466c.db' has been unable to grant a connection to thread 7707 (AsyncTask #6) with flags 0x1 for 30.022001 seconds.
05-01 16:08:08.075  1727  1976 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
05-01 16:08:08.075  1727  1976 W SQLiteConnectionPool: 
05-01 16:09:38.172  1727  1976 W SQLiteConnectionPool: Requests in progress:
05-01 16:08:38.087  1727  1976 W SQLiteConnectionPool:   executeForChangedRowCount started 461ms ago - running, sql="DELETE FROM messages WHERE id = ?"
05-01 16:08:56.868  1727  1727 W SQLiteConnectionPool: The connection pool for database '/data/user/0/com.fsck.k9/databases/005b07dd-5782-4d24-920b-581d833c466c.db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 30.000002 seconds.
05-01 16:08:56.868  1727  1727 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
05-01 16:08:56.868  1727  1727 W SQLiteConnectionPool: 
05-01 16:08:56.868  1727  1727 W SQLiteConnectionPool: Requests in progress:
05-01 16:08:56.868  1727  1727 W SQLiteConnectionPool:   executeForChangedRowCount started 877ms ago - running, sql="DELETE FROM messages WHERE id = ?"
05-01 16:09:08.131  1727  1976 W SQLiteConnectionPool: The connection pool for database '/data/user/0/com.fsck.k9/databases/005b07dd-5782-4d24-920b-581d833c466c.db' has been unable to grant a connection to thread 7707 (AsyncTask #6) with flags 0x1 for 90.078 seconds.
05-01 16:09:08.131  1727  1976 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
05-01 16:09:08.131  1727  1976 W SQLiteConnectionPool: 
05-01 16:09:08.131  1727  1976 W SQLiteConnectionPool: Requests in progress:
05-01 16:09:08.131  1727  1976 W SQLiteConnectionPool:   executeForChangedRowCount started 3088ms ago - running, sql="DELETE FROM messages WHERE id = ?"
05-01 16:09:26.873  1727  1727 W SQLiteConnectionPool: The connection pool for database '/data/user/0/com.fsck.k9/databases/005b07dd-5782-4d24-920b-581d833c466c.db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 60.005 seconds.
05-01 16:09:26.873  1727  1727 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.

**Comment by cketti** [comment]
Looks like a a couple of `DELETE` commands block the database for a long time. How large is your database?

**Comment by neufeind** [comment]
That db-file is 460mb large, though I don't know why. I usually use k-9 on that device only to read new mail from the inbox when I'm out-of-office - so just to refresh the inbox (loads 100 messages), sort them away or delete them etc. I'd expect the db to be quite small since it only needs to hold the 100 newest messages.
