### ISSUE TITLE
Lost Emails

### ISSUE THREAD

**Issue by bluepineapplegroup** [k9mail/k-9#3370]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

Emails I sent from Android always reside in "sent" folder on my phone.  The IMAP account from Godaddy also produces a second "sent" folder with emails sent from my desktop.  I never delete anything so all emails I send should be there.

### Actual behavior
Tell us what happens instead

All emails after 10/26/2016 have disappeared.  Today is 5/3/2018.  I did a test just now and sent an email.  This appears as it should in the sent folder but prior emails sent today and last night do not appear.  So, the matter MAY no longer be happening but all my emails are still missing.  I need them for reference in a legal matter and I would greatly appreciate any info on how to repopulate the sent folder with these emails.  

Godaddy did as much as they can and suggested reaching out to K9 since these emails are SMTP and not on their server...

### Steps to reproduce
1.  Send email as normal
2.  Check sent folder 
3.  No email appeared

* see previous notes. I refreshed and increased size of folder.  LOCATED EMAILS IN TRASH FOLDER...and was about to try and move them, and the disappeared ...leaving only messages from prior to 10/26/2016 in trash folder!  I did NOT delete or expunge

Using internal storage "/storage/emulated/0"

### Environment
K-9 Mail version:

K-9 Mail Version: 5.403

Android version:  7.0

Account type (IMAP, POP3, WebDAV/Exchange):
Godaddy IMAP

**Comment by cketti** [comment]
I have no idea what could have caused this. I doubt we'll be able to reconstruct what happened.
