### ISSUE TITLE
Feature: Add "delete" button to notifications menu

### ISSUE THREAD

**Issue by b09dan** [k9mail/k-9#3372]
This feature has MyMail. It will be convenient quickly to send a e-mail to trash directly from notification.
![20180507_002500](https://user-images.githubusercontent.com/17816777/39678929-cecaeccc-519e-11e8-8e6e-e744b388d265.jpg)

**Comment by cketti** [comment]
You can already configure this under: Global settings > Notifications > Show 'Delete' button
