### ISSUE TITLE
Add support for background execution limits on Android 8+

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#3375]
See https://developer.android.com/about/versions/oreo/background

For minimal support we could make `MailService` and `PushService` foreground services. We also need to make sure at least one of them is started whenever we perform a background operation.

For a nicer solution we could look into making periodic syncs use [JobIntentService](https://developer.android.com/reference/android/support/v4/app/JobIntentService). For Push we still need to use a foreground service. We probably want to create a separate notification channel. That way users will be able hide the ongoing notification required for a foreground service.

**Comment by dasgnu** [comment]
Are you planning to implement any of these solutions? If yes when will an updated version be ready? Thanks to the entire team that keeps developing K9.

**Comment by thomascas** [comment]
there is some news about this milestone? from 1 november is impossible to submit to store new versions without this target.

**Comment by Valodim** [comment]
Thoughts on using [WorkManager](https://developer.android.com/reference/androidx/work/WorkManager) for this?

**Comment by wiktor-k** [comment]
Is this ticket closed with #3763?

**Comment by cketti** [comment]
> Is this ticket closed with #3763?

No. We still need to fix or disable Push.

**Comment by cmeng-git** [comment]
As proposed by android, the problem can be fixed by extending the services to use JobIntentService instead of CoreService (Service).

**Comment by Krammig** [comment]
With respect, I would hardly call this an Enhancement. Irrespective of the Play store criteria, even standalone apps cannot be targeted above API 25 and we are a long way past that.
