### ISSUE TITLE
Option to display from-header, i.e. check sender

### ISSUE THREAD

**Issue by fwiep** [k9mail/k-9#3381]
### Expected behavior
I would like to have an option to display the from-header of a received message, that is, to check the sender.

### Actual behavior
At this moment, the sending address is only shown when clicking 'Show headers'.

### Steps to reproduce
1. Open a received message in any folder
2. See how the sender's name is displayed
3. One has to plow through tens of lines of headers to find the sender's address

### Environment
K-9 Mail version: 5.403
Android version: 7.1.2
Account type: IMAP

**Comment by cketti** [comment]
See #1119

**Comment by fwiep** [comment]
I'm sorry for posting a duplicate. I did search the tracker before I did :(
