### ISSUE TITLE
Not show enough attach file when open mail with large content and many attachment

### ISSUE THREAD

**Issue by hanchiran** [k9mail/k-9#3385]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Still Show enough attach file when open mail with large content and many attachment
### Actual behavior
Not show enough attach file when open mail with large content and many attachment

### Steps to reproduce
1. forward email with many attachments in k9-mail
2. open k9-mail
3. read email

### Environment
K-9 Mail version:
K-9 Mail v5.503
Android version:
android 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
I don't understand this bug report.
