### ISSUE TITLE
Fails to send email with notification "no valid recipients"

### ISSUE THREAD

**Issue by lohikarhu** [k9mail/k-9#3387]
As per subject, even for own email address, or address in contacts, or, even, reply-to. Just returns email to "Drafts" folder...

**Comment by rsgosnell** [comment]
Same for me.  Sending any email results in a return email saying "no valid recipients", even though there is a valid email address in the To box.  K-9 is useless to me without the ability to send email.  As it is, I have to go to another email client to send anything.  This has been an ongoing issue for at least a couple of months.

**Comment by Bobyl** [comment]
Same issue on my phone (android 8, moto z)
It occurs:
- only on one of my mail accounts,
- only with k-9 and no other mail client,
- only when using wi-fi connection, not on cellular.

**Comment by lohikarhu** [comment]
I found that this happens on my "local" account/SMTP server in
Germany, but my Canadian account will send correctly...quite a pain,
and this failure, where it simply dumped the email back to the drafts
folder, caused me some significant problems!

**Comment by caraka** [comment]
Confirmed for me - Oreo 8.1, Moto G6 Plus. All other K9 functions appear normal, just one providers stuck in a 'no valid recipients' deadlock whenever I try to send mail. Probably not relevant, but it is/was the first account I added. Same behaviour on 2 separate phones - the moto and a borrowed Galaxy S4, also with Oreo 8.1.

**Comment by maedoredyti** [comment]
It has definitely something related to the POSTFIX configuration /ETC/postfix/main.cf

###########################
#### HELO Restriction #####
###########################
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtpd_helo_restrictions =
    permit_mynetworks,
#    reject_non_fqdn_helo_hostname, <--- This causing it OR
#    reject_invalid_helo_hostname,     <--- This causing it OR
#    reject_unknown_helo_hostname, <--- This causing it OR any combination of them
    permit

When I comment them out it goes away.

**Comment by Valodim** [comment]
@maedoredyti that is helpful info, thanks for tracking it down!

Can you say what the setting for is under Global -> Privacy -> "Hide hostname"? If this is checked, the hostname will always be `localhost`. If it is *not* checked, the hostname will be [InetAddress.getcanonicalHostName()](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getCanonicalHostName()) or, if that returns empty or contains an underscore (which is [not permitted](https://tools.ietf.org/html/rfc5321#section-4.1.2)), the ip address in brackets (an [address-literal](https://tools.ietf.org/html/rfc5321#section-4.1.3)). This looks like compliant behavior to me so far.

**Comment by maedoredyti** [comment]
"Global -> Privacy -> "Hide hostname" is OFF (NOT selected).
I created my own mail server on the Raspberry PI two days ago. I have public ipv4 address, revDNS is set properly to this address. I only fight with spam and I change this or those but now all _helo_ restrictions are disabled, commented out.
Tell me what you need? Config files of the postfix? Change something in config and test again?

**Comment by maedoredyti** [comment]
Good delivery

Dec  4 23:28:12 elkom postfix/smtps/smtpd[5241]: connect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]
Dec  4 23:28:12 elkom postfix/smtps/smtpd[5241]: Anonymous TLS connection established from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Dec  4 23:28:13 elkom postfix/smtps/smtpd[5241]: 9197D5CF27: client=ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130], sasl_method=PLAIN, sasl_username=info
Dec  4 23:28:13 elkom postfix/cleanup[5247]: 9197D5CF27: message-id=<46D98CF9-17B2-4E3D-83C1-B417D4CA9CE0@domain.com>
Dec  4 23:28:13 elkom postfix/qmgr[4627]: 9197D5CF27: from=<info@domain.com>, size=711, nrcpt=1 (queue active)
Dec  4 23:28:13 elkom postfix/smtps/smtpd[5241]: disconnect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
Dec  4 23:28:13 elkom postfix/local[5248]: 9197D5CF27: to=<clo@domain.com>, relay=local, delay=0.17, delays=0.12/0.04/0/0.01, dsn=2.0.0, status=sent (delivered to maildir)
Dec  4 23:28:13 elkom postfix/qmgr[4627]: 9197D5CF27: removed
Dec  4 23:28:17 elkom dovecot: pop3-login: Login: user=<clo>, method=PLAIN, rip=xxx.xxx.xxx.130, lip=xxx.xxx.xxx.131, mpid=5253, TLS, session=<BUcuyDl8cMRb6DKC>
Dec  4 23:28:17 elkom dovecot: pop3(clo): Disconnected: Logged out top=0/0, retr=1/826, del=1/1, size=810


HELO check enabled

Dec  4 23:30:02 elkom postfix/smtps/smtpd[5488]: connect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]
Dec  4 23:30:02 elkom postfix/smtps/smtpd[5488]: Anonymous TLS connection established from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Dec  4 23:30:03 elkom postfix/smtps/smtpd[5488]: NOQUEUE: reject: RCPT from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: 504 5.5.2 <hlte>: Helo command rejected: need fully-qualified hostname; from=<info@domain.com> to=<clo@domain.com> proto=ESMTP helo=<hlte>
Dec  4 23:30:03 elkom postfix/smtps/smtpd[5488]: disconnect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130] ehlo=1 auth=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=4/6
Dec  4 23:30:06 elkom postfix/smtpd[5496]: warning: hostname mail.sender20.pl does not resolve to address 46.41.150.10: Name or service not known
Dec  4 23:30:06 elkom postfix/smtpd[5496]: connect from unknown[46.41.150.10]
Dec  4 23:30:06 elkom postfix/smtpd[5496]: Anonymous TLS connection established from unknown[46.41.150.10]: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits)
Dec  4 23:30:06 elkom postfix/smtpd[5496]: NOQUEUE: reject: RCPT from unknown[46.41.150.10]: 450 4.7.1 <plesk-1280943-7177.domain.tld>: Helo command rejected: Host not found; from=<fump@szkoleniapraktyczne.com.pl> to=<shop@plcstore.pl> proto=ESMTP helo=<plesk-1280943-7177.domain.tld>
Dec  4 23:30:06 elkom postfix/smtpd[5496]: disconnect from unknown[46.41.150.10] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8

**Comment by maedoredyti** [comment]
```
Good delivery

Dec  4 23:28:12 elkom postfix/smtps/smtpd[5241]: connect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]
Dec  4 23:28:12 elkom postfix/smtps/smtpd[5241]: Anonymous TLS connection established from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Dec  4 23:28:13 elkom postfix/smtps/smtpd[5241]: 9197D5CF27: client=ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130], sasl_method=PLAIN, sasl_username=info
Dec  4 23:28:13 elkom postfix/cleanup[5247]: 9197D5CF27: message-id=<46D98CF9-17B2-4E3D-83C1-B417D4CA9CE0@domain.com>
Dec  4 23:28:13 elkom postfix/qmgr[4627]: 9197D5CF27: from=<info@domain.com>, size=711, nrcpt=1 (queue active)
Dec  4 23:28:13 elkom postfix/smtps/smtpd[5241]: disconnect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
Dec  4 23:28:13 elkom postfix/local[5248]: 9197D5CF27: to=<clo@domain.com>, relay=local, delay=0.17, delays=0.12/0.04/0/0.01, dsn=2.0.0, status=sent (delivered to maildir)
Dec  4 23:28:13 elkom postfix/qmgr[4627]: 9197D5CF27: removed
Dec  4 23:28:17 elkom dovecot: pop3-login: Login: user=<clo>, method=PLAIN, rip=xxx.xxx.xxx.130, lip=xxx.xxx.xxx.131, mpid=5253, TLS, session=<BUcuyDl8cMRb6DKC>
Dec  4 23:28:17 elkom dovecot: pop3(clo): Disconnected: Logged out top=0/0, retr=1/826, del=1/1, size=810


HELO check enabled

Dec  4 23:30:02 elkom postfix/smtps/smtpd[5488]: connect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]
Dec  4 23:30:02 elkom postfix/smtps/smtpd[5488]: Anonymous TLS connection established from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Dec  4 23:30:03 elkom postfix/smtps/smtpd[5488]: NOQUEUE: reject: RCPT from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130]: 504 5.5.2 <hlte>: Helo command rejected: need fully-qualified hostname; from=<info@domain.com> to=<clo@domain.com> proto=ESMTP helo=<hlte>
Dec  4 23:30:03 elkom postfix/smtps/smtpd[5488]: disconnect from ip-xxx-xxx-xxx-130.example.com[xxx.xxx.xxx.130] ehlo=1 auth=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=4/6
Dec  4 23:30:06 elkom postfix/smtpd[5496]: warning: hostname mail.sender20.pl does not resolve to address 46.41.150.10: Name or service not known
Dec  4 23:30:06 elkom postfix/smtpd[5496]: connect from unknown[46.41.150.10]
Dec  4 23:30:06 elkom postfix/smtpd[5496]: Anonymous TLS connection established from unknown[46.41.150.10]: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits)
Dec  4 23:30:06 elkom postfix/smtpd[5496]: NOQUEUE: reject: RCPT from unknown[46.41.150.10]: 450 4.7.1 <plesk-1280943-7177.domain.tld>: Helo command rejected: Host not found; from=<fump@szkoleniapraktyczne.com.pl> to=<shop@plcstore.pl> proto=ESMTP helo=<plesk-1280943-7177.domain.tld>
Dec  4 23:30:06 elkom postfix/smtpd[5496]: disconnect from unknown[46.41.150.10] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

**Comment by maedoredyti** [comment]
this `<hlte>` is the name of my phone !!!!!!! It goes to HELO

**Comment by Valodim** [comment]
Given reports that this happens on wifi but not mobile, it seems like we sometimes erroneously use the local hostname instead of localhost or our local ip. Given that the hostname in the EHLO mesage is useless anyways since clients are often behind a NAT these days, we might as well get rid of that. This even allows us to drop another setting, yay -> see #3798

**Comment by lohikarhu** [comment]
Thanks to the team!

**Comment by KolyaKorruptis** [comment]
I have this problem when sending to anyone but myself. Used to work fine. Server connection checks out.
Interestingly I can also send to a Gmail address that is just a forward to my real address. But I cannot send to other Gmail addresses (or anyone else).

**Comment by Stratus3D** [comment]
I get this when trying to send any email with K-9 Mail version 5.600 on Nougat.

**Comment by KolyaKorruptis** [comment]
I finally found the reason in my case: I had tried to send mails with an alternate identity, that has a different email address.This was apparently blocked by my mail provider.

The alternate address I used is also mine, but registered at a different provider.

**Comment by Stratus3D** [comment]
I never figured out what the issue was for me. The credentials I used worked on the two other email clients I used.

**Comment by ralphhaygood** [comment]
Still a problem after all this time. Using latest K-9 on a Samsung Galaxy A50. Can't send anything anywhere I've tried over Wi-Fi. No problem over cellular (LTE) connection, however.

And yes, the Global -> Privacy -> "Hide hostname" box is unchecked.

**Comment by neonknight** [comment]
Why is this issue closed? I had to tick the checkbox "Hide hostname" or else sending over WiFi and mobile connection was both not possible (Nokia 6.1 with latest updates, K-9 installed from f-droid)

**Comment by pggdt** [comment]
Unfortunately, I still get the same problem with android 8 and K-9 Mail 5.600 from f-droid. It works good with cellular connection but fails on Wi-Fi.
