### ISSUE TITLE
[Request] Show account list on app start

### ISSUE THREAD

**Issue by malnvenshorn** [k9mail/k-9#3390]
I would like to have the account list shown on app start. At the moment I can either choose the global inbox or a folder from my mail account. In both cases I always have to go back first to see my new mails`*`, but ATTENTION if I click the back button the app closes. I have to click the arrow in the upper left to go back. All in all this is far from convenient.

`*` I make heavily use of mail extensions, where the emails are automatically sorted into sub-folders of the inbox. But those mails doesn't appear in the inbox or global inbox. Therefore I have two options:
1. go back to the account list and use the 'all messages' folder
2. or directly select the folder from the account folder structure

Edit: I'm totally new to this app, so my apologies if I missed something.

**Comment by GoneUp** [comment]
I don't think that option exits by default, but as a workaround you could add a second account (even if it's a dummy). I have multiple accounts and if I open the app, it shows me the account list.

**Comment by cketti** [comment]
We're changing the UI for the next stable version. The account list screen will be removed. Switching accounts will be possible using a side menu.
