### ISSUE TITLE
Outgoing server settings doesn't work with standard postfix + dovecot server, msmtp works

### ISSUE THREAD

**Issue by doronbehar** [k9mail/k-9#3395]
### Expected behavior

Connection to my postfix server on SSL/TLS with a normal password works like with `msmtp` on my Linux machine.

### Actual behavior

I get the following error message:

```
Setup could not finish
---
cannot connect to server
()
```

### Steps to reproduce
1. Configure a postfix server with TLS enabled
```pfmain
smtpd_sasl_type = dovecot

smtpd_sasl_path = private/auth

smtpd_sasl_auth_enable = yes

smtpd_sasl_security_options = noanonymous, noplaintext
smtpd_sasl_tls_security_options = noanonymous

smtpd_tls_auth_only = yes

smtpd_relay_restrictions = permit_sasl_authenticated, reject_unauth_destination, permit_tls_all_clientcerts
smtpd_client_restrictions = permit_sasl_authenticated, reject_unauth_destination
smtpd_tls_cert_file = # path...
smtpd_tls_key_file = # path...
smtpd_tls_security_level = encrypt
```
2. Test the server with a msmtp like this:
  - Configure it with something like this:
```msmtp
defaults
	auth on
	tls on
	tls_trust_file /etc/ssl/certs/ca-certificates.crt
	logfile ~/.msmtp.log

account test
	host smtp.example.com
	from me@example.com
	user me
	auth plain
	password # Password here #

account default : test
```
  - Run a command like `echo "testing msmtp from the command line" | msmtp -a test` to test the connection
3. Test the K-9 mail app outgoing server settings with the following parameters:
  - SMTP server: `smtp.example.com`
  - Security: `SSL/TLS`
  - Port: `25`
  - [x] Require sign-in
  - Username: `me@example.com`
  - Authentication: `normal password`
  - Password: # Password here #

### Environment

K-9 Mail version: F-droid Latest stable - `5.403`
Android version: LineageOS 14.1 nightly, (Android 7.1)
Account type: SMTP (outgoing server).

### Debugging

I have access to the server's logs so here is what appended to them when I attempt to establish a connection (private information removed):
```
vps postfix/smtpd[12908]: connect from unknown[ip.address]
vps postfix/smtpd[12908]: lost connection after CONNECT from unknown[ip.address]
postfix/smtpd[12908]: disconnect from unknown[ip.address] commands=0/0
```

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
