### ISSUE TITLE
Notification should contain archive action

### ISSUE THREAD

**Issue by kwenzig** [k9mail/k-9#3403]
### Expected behavior
Within a new mail notification I would like to move mail directly to the archive (and mark it as read).

### Actual behavior
Now there are the following options [(c.p. documentation)](https://k9mail.github.io/documentation/notifications.html) within the notification: reply, mark read, delete.

### Environment
K-9 Mail version:5.403

### Thanks
for K-9 with the great archive feature known from Thunderbird. :-)

**Comment by jkuester** [comment]
It appears that this is a feature supported for wearables, but not phones: https://github.com/k9mail/k-9/blob/master/app/core/src/main/java/com/fsck/k9/notification/WearNotifications.java#L204

I am going to work on a code change to add this option to the device notifications as well.

**Comment by cketti** [comment]
See #3530
