### ISSUE TITLE
incorrect message after last poll

### ISSUE THREAD

**Issue by iriman** [k9mail/k-9#3422]
![20180603_004538](https://user-images.githubusercontent.com/8467903/40880561-f91373f0-66a2-11e8-8fd7-d7fee340639d.jpg)
-
![20180603_004439](https://user-images.githubusercontent.com/8467903/40880564-072fe52c-66a3-11e8-9eed-8afebc505060.jpg)
-
![20180603_004337](https://user-images.githubusercontent.com/8467903/40880568-0e40e2ee-66a3-11e8-9c18-d05eea044038.jpg)

need to change "next" to "last"

**Comment by hexxellor** [comment]
I don't know that this is helpful or not but here is a screenshot of the same issue, just from the Inbox view on v5.600.
![screenshot](https://user-images.githubusercontent.com/892633/51398496-59fe3b80-1b09-11e9-8953-93327113cc61.jpg)

**Comment by cketti** [comment]
The next major version of K-9 Mail won't show this message anymore. Due to the energy saving mechanisms in recent Android versions we won't know exactly when the next check is going to be anyway.
