### ISSUE TITLE
crash when fetching mail

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#3437]
### Expected behavior
Message should display normal
### Actual behavior
app crash when fetching mail
### Steps to reproduce
1.login
2.display messagelist and loading
3.crash

this is log below:
LocalFolder.open(Proguard:1361) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]
LocalFolder.setLastChecked(Proguard:1630) ~[na:0.0]
LocalFolder.access$2401(Proguard:1313) ~[na:0.0]

### Environment
K-9 Mail version: 5.403

Android version: 7.0 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by zhangxiaofan918** [comment]
I found Logcat print setLastChecked has been printing. Debug version is good, there will be problems with using apk. Why is this so?

**Comment by cketti** [comment]
We don't ship versions with obfuscated class names. So this stack trace is most likely not from the official app.
