### ISSUE TITLE
internet Links in e-mail are not active

### ISSUE THREAD

**Issue by k9user** [k9mail/k-9#3438]
I looked for this issue by searching but kind-of feel I may have missed it...

### Expected behavior
internet Links in e-mail are not active, I would like to tap on them and have them open in my browser

### Actual behavior
the links are just text, I have to copy them and past into my browser

### Steps to reproduce
always happens, not sure if happened 4 years ago when I 1st used app 

### Environment
K-9 Mail version: 5.403

Android version:  7.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

Phone: LG Aristo

**Comment by cketti** [comment]
We only detect URLs in text/plain parts and linkify them. If someone sends you an HTML email with an URL that is not a link, we'll display it as-is. That's by design (the sender might have a good reason why the URL should not be clickable).
