### ISSUE TITLE
Duplicate folders and sync failures

### ISSUE THREAD

**Issue by twsh** [k9mail/k-9#3439]
I have https://github.com/k9mail/k-9/issues/1220

I also have the problem that things I read or archive through the Fastmail site don't end up as read or moved to Archive in K9. I also end up with a lot of old drafts that are not removed after a message is sent.

### Environment
K-9 Mail version: 5.403

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
