### ISSUE TITLE
Message List Color issue after Oreo Update (S7)

### ISSUE THREAD

**Issue by PiobGuy** [k9mail/k-9#3440]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Text color should not have changed

### Actual behavior
Text for messgae list has change to bright magenta. Alternatively unread messages are birght magenta if the option in reverse colors is checked.
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: Pro 1.15

Android version: 9.0

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Wrong bug tracker. There's no "K-9 Mail Pro 1.15".
