### ISSUE TITLE
Please add an option for NOT SAVING passwords

### ISSUE THREAD

**Issue by lau95** [k9mail/k-9#3441]
As far as I understood, after reading a few of those issues, there is no real wish to secured passwords encryption (use an encrypted device). I like that app very much, by it seems to me a real problem that password securization is not on the top of the priorities for, espacially, a secured oriented app.

*Could someone please just add an option to +not save+ any password in the app?*

I have no development skills unfortunaltely.
Thank you in advance

**Comment by cketti** [comment]
What attack scenarios are you worried about that device encryption and the device lock screen are not enough for you?

**Comment by lau95** [comment]
My concern is rather malware than physical steal.
Have you read technical notes of passphrase protection for openKeyChain? https://github.com/open-keychain/open-keychain/wiki/App-Security#passphrase-cache and https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Passphrase.java ?
I think that such an option, to use password in memory through class would be greatly appreciable (with for example an auto deletion after 1 hour).
Thanks for your feedback (I am not a security expert, so maybe this concern is inappropriate)

**Comment by cketti** [comment]
Malware would have to overcome Android's app isolation first. But not storing the password doesn't prevent such malware from reading the password out of K-9 Mail's process memory after it has been entered.

Such a feature would greatly complicate the app architecture while the benefits (and number of potential users) are small.

**Comment by lau95** [comment]
After a few readings on internet about Android security it seems you are right
When the device is encrypted, and provided that k9 only use internal storage (and not content provider), the sandbox mecanism seems strong enough to protect data access from other apps.
https://developer.android.com/training/articles/security-tips#InternalStorage
