### ISSUE TITLE
Implement RFC 6186: Use of SRV Records for Locating Email Submission/Access Services

### ISSUE THREAD

**Issue by ilf** [k9mail/k-9#3442]
[RFC 6186](https://tools.ietf.org/html/rfc6186) "defines new SRV service types for the message submission, IMAP, and POP3 services, to enable simple auto-configuration of MUAs."

[RFC 8314](https://tools.ietf.org/html/rfc8314#section-5.1) goes further and sais:

> User-configurable MUAs SHOULD support the use of [RFC6186] for account setup.

It would be nice to follow the RFC and have this in K-9 Mail.

Thanks, and keep up the good work!

**Comment by philipwhiuk** [comment]
See #865 and #2530
