### ISSUE TITLE
Envelope icon Open when it should be closed and Visa Versa

### ISSUE THREAD

**Issue by MickLG1965** [k9mail/k-9#3445]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
In the messages list, with checkboxes enabled.  At the bottom of the screen there are three icons The Wastebasket, The Envelope, and A Star.  

When the message highlighted is in BOLD font, I would assume that this meant the message is UNREAD and the Envelope should be Closed?

### Actual behavior
However, when the message highlighted is in BOLD font, and assuming that this meant the message is UNREAD, the Envelope at the bottom of the screen is OPEN?  Which I assume would indicate the the envelope is open and the message read?

Is it the wrong way round or am I getting mixed up?

### Steps to reproduce
1. open up the messages view in K9
2. Make sure that a message is highlighted
3. look at the Envelope icon at the bottom of the screen, is it OPEN or Closed when the message is BOLD?

### Environment
K-9 Mail version: 5.403

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
If you select an unread message the action you can perform is "mark as read" (open envelope). "Mark as unread" (closed envelope) doesn't make sense if the message is already marked as such.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
