### ISSUE TITLE
Infrequent errornous message sent on the broadcast receiver

### ISSUE THREAD

**Issue by Iamgiam** [k9mail/k-9#3464]
I am using K9 with FireAlert2 with the broadcast receiver enabled.
FireAlert2 is set up to alert me on specific faults issues via my email account.
To that end I have IDLE set to keep all awake every 12 minutes and also polling every 4 at least especially when I am on call.
This works well for most of the time.
An issue arises infrequently where K9 polls and fetches 20 emails. The folder count becomes 19 emails and FireAlert2 triggers for the 20th message.  (The oldest message)
4 minutes later the cycle repeats. 
Now this message could be quite old or new.
When looking at this message on FIreAlert2 it clearly shows when it was sent from whoever sent it.
When K9 received it and the now time that FA2 paged it. This clearly shows it is an old message.
To stop it I change the Fetch Size to 50 or some other amount. 
The fault stops and it all behaves itself for a wee while and then off it goes again.
The really annoying issue with this is I have to monitor this channel 24/7 for a week and it can wake me up for clearly old messages.
This issue has been present since I started using this which is a couple of years. 

### Steps to reproduce
1.  Polling 4 minutes on one folder.
2. FIreAlert2 filters set up to receive particular message types.
3. wait.

### Environment
K-9 Mail version:
5.403
Android version:
Oreo 8.1.0 but issue on all devices tried. Lollipop 5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
imap.gmail.com 
The screen shot shows a repeated message originally received the previous day at 11am being re-triggered at 6:37am the next morning.
The phone has been online and monitoring all night.

![screenshot_2018-06-06-15-12-51](https://user-images.githubusercontent.com/18553576/41759970-51ca4260-7645-11e8-9afb-f5090efc54a1.png)

**Comment by cketti** [comment]
The broadcast intent is sent for newly downloaded messages, not necessarily new messages. So it's working as expected.
I plan to remove this "feature" in the future. The broadcast will probably be replaced by a content provider that can be observed for changes. But there you'll also have to figure out yourself whether a newly added message is really a new message or an old message fetched to fill the message window.
