### ISSUE TITLE
Less secure app

### ISSUE THREAD

**Issue by Kareem-Ahmed** [k9mail/k-9#3470]
You still fail to fix the "less secure app" issue with gmail emails

I have to make my gmail account allow use of less secure apps -"which is what google considers k-9 mail"- in order to be able to use the app with my gmails , i have had it every time goigle block my emails cause of this ... Of you're not planning on fixing it let us know so i can dump k-9 abd find another app

**Comment by violoncelloch** [comment]
Primarily this is an issue of google. They are trying to force you inside their app environment to spy on you as much as possible. To achieve this they make it super compicated for apps as k9 to "comply" with their rules.

**Comment by ArchangeGabriel** [comment]
If you use two-factor authentication, you can have per-app password (https://myaccount.google.com/apppasswords) instead of allowing “less secure app”.

**Comment by cketti** [comment]
See #655
