### ISSUE TITLE
Feature request: Suppress notifications for Delta Chat messages.

### ISSUE THREAD

**Issue by DocSniper** [k9mail/k-9#3471]
I use Delta Chat ( https://delta.chat/ ), which is an e-mail based messenger. 
Because K-9 and Delta Chat both use push I'm notified by both application. 
Short after this Delta Chat moves the messages away from the inbox folder to an own folder and K-9 deletes the notification.
So an option to "delay K-9 notifications for X seconds" would be great. 
Thanks.

**Comment by cketti** [comment]
I don't particularly like the proposed solution of delaying notifications.

@r10s: Is there a way to recognize Delta Chat messages so we could disable notifications for just those?

**Comment by r10s** [comment]
> Is there a way to recognize Delta Chat messages so we could disable notifications for just those?

yes, they have a `Chat-Version:` header. as Delta Chat also relies on this header, this seems to be a good hint. Apart from other headers, the `Chat-Version:` header is currently explicitly _not_ moved to the encrypted payload.

**Comment by r10s** [comment]
maybe this could also be solved in another way:

- let the two notifications appear, the user can decide whether to handle the message with Delta Chat or K-9
- once the message is read in either app, _both_ notifications disappear

just an idea, technically, this might be more tricky ...

**Comment by DocSniper** [comment]
The double notification bothers me now for quite a while or better said it's a 1.5 notification. Because what annoys the most is that the first of the two notifications is interrupted in the middle and then the other one of the two comes. Both in terms of sound and vibration.

I have now found a solution for me, but it only works because I've access to my mail filters. I've created a rule that instantly moves all mails containing "Chat Version:" in the mail header directly to the DeltaChat folder.

It would be better, however, to implement an option in K-9, e.g. named "Ignore COI messages" that checks if "Chat Version:" is appearing in the mail header and then suppressing the new mail notification. Disabled by default.

Just an idea ... and maybe the most easiest way to handle the double notification issue.

**Comment by DocSniper** [comment]
Since push messages are available again since version 5.8, this problem has returned. I would like to suggest again to proceed as follows: 
Implement an option in K-9, e.g. "Ignore COI messages", which, if enabled, checks if "Chat Version:" occurs in the mail header and then suppresses the new mail notification of K-9. This option should of course be disabled by default.
Sorry to bug you and thanks. 😃

**Comment by r10s** [comment]
> Implement an option in K-9, e.g. "Ignore COI messages", which, if enabled, checks if "Chat Version:" occurs in the mail header and then suppresses the new mail notification of K-9. 

sounds good!

however, maybe better call it "Ignore Chat Messages", "Ignore Delta Chat Messages" or so - [COI is no longer active and "hold for now"](https://github.com/coi-dev/ox-coi#project-on-hold-for-now) - but there are some other clients and bots using the `Chat-Version` header meanwhile.
