### ISSUE TITLE
Email content became unreadable

### ISSUE THREAD

**Issue by danjde** [k9mail/k-9#3473]
Hi Friends!
I've just installed K-9  version "5.403" on my Android Phone "One Plus 5" and from certain sender with some emails, obtain a very very long text vertical lined up that make unreadable the entire email content.

For more clarify I attach a screenshot.

Many thanks!

![photo_2018-06-27_16-15-49](https://user-images.githubusercontent.com/4129294/41981473-89663c02-7a18-11e8-825d-0dbb67123ecc.jpg)

**Comment by cketti** [comment]
Can you provide the message source of such an email?

**Comment by danjde** [comment]
This issue was happens to job client of mine, and I've jus asked him about this, but the email content is reserved and I wan not able to share it with you.

If this issues will repeat, maybe with non-private content, I will I'll let you have what you ask me ;-)

Thanks!

Davide
