### ISSUE TITLE
Emails display order changed and I cannot change back to expected

### ISSUE THREAD

**Issue by ConnDublin** [k9mail/k-9#3505]
### Expected behavior
Unread emails stay at the top of the list of emails in the expected reverse date order within each type (unopened, then opened). Once read, each mail then "drops down" to the list of read emails and is correctly sorted on the date within the read emails.

### Actual behavior
Following some flickering on-screen that happened too fast to read, the unread emails now appear at the *bottom* of the list, *after* all read emails. Date orders are still correct within each category.

This behaviour is restricted to one email account - other email accounts were unaffected by the change.

### Steps to reproduce
1. A smudged screen caused unknown swipes / keystrokes to the be sent. I cannot reproduce (nor reverse) the effect
2. I have searched the online documentation high and low and can find no reference to this issue

All help much appreciated. If this is a "setting", for the life of me I could not find it.

### Environment
K-9 Mail version: 5.403

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
Select 'sort by unread/read' again to change the sort order.
