### ISSUE TITLE
Feature request: Improved folder list

### ISSUE THREAD

**Issue by pingu8007** [k9mail/k-9#3512]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
A clear list that I can tell a folder is classified in which class, and maybe sortable/filterable. It would be good if I can SET the class without dive into folder config.

Some example:
![image](https://user-images.githubusercontent.com/8936513/42979515-366ba9d4-8c05-11e8-97c6-21f28080cb1f.png)
Use text and background color to indicate the actual class, and use font color to indicate a class is explicit defined(black) or inherited(red).

### Actual behavior
I need to dive into folder config to see which class am I using. It's annoying if I have dozens of label.

**Comment by Meteor0id** [comment]
I think @pingu8007 is on to something with this, however it would mean a redesign of the user interaction. This concept should be taken into consideration for a next major version of k9.

**Comment by cketti** [comment]
We want to get rid of folder classes (see #2669). The proposed user interface looks highly specialized and complicated. It's not a direction I want K-9 Mail to go.
