### ISSUE TITLE
K-9 Mail is marked as read in the app, but on Gmail.com, it is not

### ISSUE THREAD

**Issue by NovaViper** [k9mail/k-9#3516]
### Expected behavior
My mail that's on Gmail's servers should be marked as read when I look at them on k9 Mail.

### Actual behavior
Emails are marked as read within the app, but not on Gmail so when I open the desktop Gmail, I have over 100+ unread mail

### Steps to reproduce
1. Log into gmail on K9 Mail
2. Mark as read an email by opening it
3. Log into gmail on a browser, see that the mail you marked as read in K9 is not marked the same on the desktop

### Environment
K-9 Mail version: 5.503

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP/Gmail

**Comment by cketti** [comment]
Please record a debug log while trying to mark a message as read in K-9 Mail. See https://github.com/k9mail/k-9/wiki/LoggingErrors
