### ISSUE TITLE
Selecting between signing & encrypting via PGP not possible

### ISSUE THREAD

**Issue by arnowelzel** [k9mail/k-9#3518]
According to https://k9mail.github.io/documentation/security/pgpmime_current.html it should be possible to tap the "encrypt" icon and select between one of four choices:

- Never Sign or Encrypt 
- Always Sign, Never Encrypt
- Always Sign, Encrypt if Possible
- Always Sign, Always Encrypt

However I never have these choices. I can only turn encryption on or off and when turned on this means "Always Sign, Always Encrypt".

### Expected behavior
When creating a new mail to a recipient where a PGP key is a available, it should be possible to choose, if you want to encrypt only or encrypt and sign.

### Actual behavior
It is only possible to encrypt and sign or not to encrypt and sign at all.

### Steps to reproduce
1. Install OpenKeychain
2. Import or generate a private PGP key in OpenKeychain
3. Import the public key of a recpient in OpenKeychain
3. Select OpenKeychain as cryptography app in K9 mail
4. Create a new mail where you have the private key available for the identiy sending the mail
5. Select a recipient where you have the public key available, make sure the
6. Tap the "encrypt" icon once to enable encryption and check, that the icon is the one with the "..." next to it - even then there is no choice available, you only can turn it on or off

### Environment
K-9 Mail version: 5.403

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
The documentation is outdated. I created an entry in the website's issue tracker: https://github.com/k9mail/k9mail.github.io/issues/87

See #1961 on why 'encrypt only' is no longer available.
