### ISSUE TITLE
Odd choice of icon on notification when checking for mail

### ISSUE THREAD

**Issue by lindhe** [k9mail/k-9#3526]
When k-9 is checking for new mail (in the background), it puts up a notification. That notification has an icon (glyph?) which looks like a cogwheel/gear. I find that confusing—I expect a gear to symbolize a system update or something like that. An email symbol, like a letter, would be better.

### Steps to Reproduce
Wait until the app syncs in the background. For me, it's particularly noticeable in the always-on notifications.

### Environment
K-9 Mail version: 5.403

Phone: S8
Android version: 8.0.0
Samsung Experience version: 9.0

**Comment by Meteor0id** [comment]
On android 7.0 I get an arrow moving in a circle, this icon makes perfect sense to me. I have never noticed the cogwheel. I suggest using this same icon for whatever version @lindhe is using as well. (and I blive ti is the recommanded icon for this type of event, following Android icons documentation)

**Comment by cketti** [comment]
@lindhe Can you please post a screenshot?

**Comment by lindhe** [comment]
![gear symbol at the always-on display when k-9 is syncing](https://user-images.githubusercontent.com/7773090/43482860-34315dae-950a-11e8-909c-2a4ec236757c.jpg)

**Comment by lindhe** [comment]
Come to think about it, it could possibly be because of something else. The other thing that comes to mind is if Samsung has some process that handles background sync and it would be that symbol that causes it. Hard to verify, since it would cause k-9 to sync too. Guess I could uninstall k-9 and have another look... Sigh...

**Comment by cketti** [comment]
Probably a Samsung issue. As far as I can tell this icon isn't even part of the app.
