### ISSUE TITLE
[enhancement] add view source button, to view the html source of a message

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3533]
Sometimes someone sends me a snppet of code. and sometimes this code is HTML. Unfortunatly quite often the client tries to make sense of it rather than showing the code. That is totally fine, as any security risk would get blocked anyway, however I argue there is a use case for seeing the source of a message. Also because the headers of the message can be quite useful when debugging a mail server.

**Comment by cketti** [comment]
Duplicate of #1018
