### ISSUE TITLE
[enhancement] do not discard unsend message when the application is reopened

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3534]
When I have to quickly do something in another app, I minimize the concept e-mail I currently have opened. I open another app and do something. I want to go back to the e-mail I was writing on, or I forgot about it and just want to check my mail. I do not regualry check if an app is already opened, I just find the shortcut to the app in my menu bar or in the list of apps I have installed and open te app that way.

### Expected behavior
I expect the app to open on the same scree at which I left it, which is the composing new e-mail screen. The content should still be there, and I should be able to save it as a draft, send it as an e-mail, or discard it after confirming I want to discard it.

### Actual behavior
The app does open on the composing screen, but immidiatly (within less than a second) switches over to the account overview screen. The message I was writing is immidialty discarded without confirmation. I am left trying to recall what I had written down, and if I have to rewrite it or should just forget about it. And ofcourse this is very frustrating. I worked on that e-mail, and all that work was for nothing just because I did not check if the app was already open.

It is normal for android apps to be reopned in this manner, and open on the same screen at which they were left open.

### Environment
K-9 Mail version:
5.403

Android version:
7.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Sounds like the app crashes and is restarted by the OS. Can you enable debug logging and grab a log the next time this happen? See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by cketti** [comment]
No debug log provided.

**Comment by Meteor0id** [comment]
The phone on which this happened (A Moto G5 Plus) was pick-pocketed (rip). On my new phone the issue does not occur. I can no longer provide a debug log for this issue. To anyone who encounters the same issue, feel free to add a debug log here and ask cketti to reopen it.
