### ISSUE TITLE
[enhancement] "Load more" button also available from the search result view

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3536]
Sometimes I want to find an old e-mail, and I type in a search querry. Unfortuantly, the e-mail is not found and I only get an empty list, or a few items I was not looking for. the issue is that the e-mail is not cahced anymore, and I will have to load more emails, by scrolling down in my inbox and pressing the button "load more e-mails". It makes sense.

However I have to exit the search results for this, go to my inbox, and keep scrolling down and loading e-mails. I would rather stay in the search result and press a button there, to keep loading more e-mails untill it appears, or untill I get the idea the querry is not right.

Just adding the button would not be enough, as there would often be no visual change in the search results to indicate more e-mails have sucesfully loaded. Therefore I would also ask to add a line of text "searched all emails dating 3th of July or later" and every time I press the button load more e-mails, the text will indicate an earlier start date, confirming those e-mails have also been included in the search.

**Comment by Meteor0id** [comment]
Oh yea, and round of that start date to the first day of which ALL e-mails have been loaded!

Example:
I know I received that e-mail on 5th of May. I press load more a few times utill it sais "searched all emails of 5th of May and later". Naturally I assume something was wrong with my search querry, or I remember the date incorrectly. However, I might have only loaded some of the e-mails of the 5th of may, and this email was received earlier taht day, and is actually not included untill I load more e-mails once more.

I can already see this mistake happening, so I will include in this ticket that we must round of the days to the last day which waas completely included in the search. I will leave it to whoever creates the pul lrequest to figure out how this should be checked for. Dont forget that during searching the user might reach the end of e-mails stored on the searver, and he can no longer load more e-mails. At that point, mentions the date of the very earliest e-mail as included in the search.

**Comment by cketti** [comment]
Enabling server-side search should do the trick for your use case.
