### ISSUE TITLE
No support for custom Username (login name)

### ISSUE THREAD

**Issue by FFY00** [k9mail/k-9#3537]
Hello, sorry for bothering.

### Expected behavior
I have a email with a custom login name (login name is not the email). I would expect to find a `Custom Username` box which would enable an `Username` field or something like that.

### Actual behavior
Afaik there's no such option. K-9 seems to connect to the server using the email as the username.

### Steps to reproduce
1. Try to setup an account

### Environment
K-9 Mail version: 5.403

Android version: 7

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thank you for your time :smile:. This is really important to me as K-9 seems to be the only Android email client with support for PGP.

**Comment by cketti** [comment]
By default the username field is prepopulated with the email address. But you're free to change it to something else.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by FFY00** [comment]
I was able to do this by selecting `Manual` instead of `Next`. Sorry for wasting your time.
