### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by ProactiveServices** [k9mail/k-9#3542]
The available version of K-9 on [F-Droid](https://f-droid.org/en/packages/com.fsck.k9/) is 5.403, which is a few releases behind.

**Comment by cketti** [comment]
K-9 Mail 5.403 is the latest stable version.

**Comment by himpierre** [comment]
@cketti can we have a new release on f-droid please? I'm suffering from "Fixed bug with some soft keyboards when auto-completing recipients" which was fixed in 5.503.

**Comment by ArchangeGabriel** [comment]
@himpierre Releases having an odd number for the hundreds are unstable versions. The next stable version will be 5.600. No ETA.

**Comment by himpierre** [comment]
yeah just tried 5.503. but this version still has the bug i'm talking about. I guess i have to file a new one.

**Comment by geronimoge** [comment]
Great, since v5.600 was published a few days ago: we'll see that in F-Droid soon, right?

**Comment by makuser** [comment]
@cketti it looks like the automated F-Droid builds are not working anymore, because the current stable v5.600 is still not available there.

**Comment by gdt** [comment]
@makuser 5.600 has been in f-droid since 2018-09-11:  https://f-droid.org/en/packages/com.fsck.k9/ 
I have observed two devices offering and delivering updates to 5.600.
It does need Android 4.0.3 or higher  (which of course is really ancient).

**Comment by ProactiveServices** [comment]
5.600 was offered to me a few weeks back and my initial report was erroneous as per the first comment on this thread.
