### ISSUE TITLE
Repling to an email that only has a BCC causes the BCC to become the reply's To

### ISSUE THREAD

**Issue by aartvark** [k9mail/k-9#3546]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When replying to an email that was sent to me because I am a member of the distribution list represented as the BCC (Gmail) email address, the To address of my reply should be the sender of the original email.

### Actual behavior
The To address of my reply is populated with the BCC address, not the original sender's.

### Steps to reproduce
1. Create a Google group
2. Send message to Google group email address, using Gmail.
3. Tap reply in K-9 app and go to the top of the reply and see what has been supplied as the To address.

### Environment
K-9 Mail version: 5.403

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
Google IMAP

Here are some relevant email headers.
From: Greg Wxxxx <gwxxxx@companydomain.com>
Date: Tue, 7 Aug 2018 20:56:21 -0400
Message-ID: <CAJ-XXrwJX4EPnZju68e12s3ux1qLLc7OwJoB-kLOFStMy=5XWQ@mail.gmail.com>
Subject: Disabling GMail conversation view in Android and Apple IOS
To: undisclosed-recipients:;
Content-Type: multipart/alternative; boundary="0000000000003255df0572e1fbb7"
Bcc: 0-list@companydomain.com

When I tap reply, I see 0-list@companydomain.com in the To address instead of Greg Wxxxx <gwxxxx@companydomain.com>.

If the original email had a valid To address, the reply is correctly addressed to the original sender.

**Comment by cketti** [comment]
See #3738
