### ISSUE TITLE
[Request] Ubuntu Touch version

### ISSUE THREAD

**Issue by idekovets** [k9mail/k-9#3556]
Good day!
Please, make Ubuntu Touch version and publish it on open-store.io

Best regards!

**Comment by cketti** [comment]
We're busy enough developing an Android app. We have no plans to support other platforms.

**Comment by idekovets** [comment]
Thanks for reply!20:06, 15 августа 2018 г., cketti <notifications@github.com>:We're busy enough developing an Android app. We have no plans to support other platforms.
