### ISSUE TITLE
Deleted emails prevent other emails from showing up (using IMAP)

### ISSUE THREAD

**Issue by gergelyimre** [k9mail/k-9#3561]
I'm sorry for the convoluted explanation :)

I'm using K9-Mail to read my emails on my own mailserver, with IMAP. I have the app configured to show the last 10 emails (Local folder size = 10 messages, Sync messages from = any time).
When I delete one or more emails from a folder (INBOX, or other folders), the emails disappear from the list, but the number of emails seens does not equal to 10 anymore, no matter how many times I press refresh. Only after I do an "Expunge" and then press Sync, I'm getting the list populated with 10 emails.

### Expected behavior
After deleting the emails, the list should populate with other emails, up to the set limit (10 in my case). You should not have to expunge first.

### Actual behavior
There are only 10-X emails shown (where X is the number of deleted emails)

### Steps to reproduce
1. see 10 emails in Inbox (say email1, email2, ... email10)
2. delete 2 emails (say email5 and email6)
3. now you see email1,2,3,4,7,8,9,10 (8 emails)
4. you need to "Expunge" the deleted emails if you want to see 10 emails

This is especially annoying when you have say a lot of automated emails coming in. Say you get 20 emails, from which only the latest 10 are shown. You delete these 10, they disappear from the list and now the list is empty, and you have to expunge these 10 deleted ones first, before seeing the next 10.

The deleted emails are not really deleted, they are just marked as deleted on the server (checking with Thunderbird there are clearly there), but they occupy "slots" from the list of 10 emails but they are not shown anymore.

### Environment
K-9 Mail version: 5.403
Android version: 8.0.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thank you for a great app, I'm really loving it!

**Comment by tidux** [comment]
I had the same experience on the same version of K-9 mail with a Dovecot-hosted inbox, on Android 7.1.

**Comment by OOD-Marty** [comment]
I have version 5.600 and don't see an option to manipulate the "deleted" flag.  I would like to expand on the expected behavior stated above.

Expected Behavior:
If "Hide Deleted Messages" is toggled on, then K9 should continue to download headers until it can populate the list with visible headers up to the set limit or there are no more messages on the server.
If "Hide Deleted Messages" is toggled off, then K9 should populate the list as it does now but with the messages visible along with an indication that the "deleted" flag is set.

Thank you for the best Android email application.

**Comment by cketti** [comment]
Being able to mark a message as deleted and then undelete it is an IMAP oddity that we are unlikely to add support for. It's also what's causing the issue described by the OP. 
You should set 'Account settings > Fetching mail > Erase deleted messages on server' to 'Immediately' to avoid having to manually expunge messages.

We have plans to change sync to be more reliable/predictable when loading more messages. See #1327

**Comment by gergelyimre** [comment]
I'm reading my emails on my desktop, and my phone, and ocasional also through webmail. I don't want to expunge immediately, because it can happen that I delete an email by accident on the phone, it's very easy, and I like the option to bring it back (on the desktop for example).
I don't necessarily want to undelete it with K9, that's OK that that's not supported, I just wish it would ignore marked messages, and load the rest, without counting deleted ones towards the limit of 10, 25, whatever.

Thanks for a really great app! 


-------- Original Message --------
