### ISSUE TITLE
Change mail subject in IMAP

### ISSUE THREAD

**Issue by Exantrum** [k9mail/k-9#3564]
### Expected behavior
I want to change the mail subject local but also on the imap server. Outlook windows allows this out of the box, thunderbird uses a plugin, Gmail online uses a plugin too. 
I know this is ressource heavy and that changing a subject shouldn't be done, but it's something I really need. 

### Actual behavior
Changing the mail subject isn’t possible in android apps

### Steps to reproduce
None. It simply isn't possible 

### Environment
K-9 Mail version: all

Android version: all

Account type (IMAP): imap

**Comment by cketti** [comment]
This is not functionality I want to include in the app. 

Maybe some day there will be a plugin interface to allow adding this functionality. See #909.
