### ISSUE TITLE
Can't connect to SMTP server

### ISSUE THREAD

**Issue by wyjek** [k9mail/k-9#3566]
I'm trying to set up SMTP configuration, but when I do it, I get the "Cannot connect to server. (SMTP response is 0 length) error. I'm sure I filled everything as it should be, I'm using cock.li mail.

### Environment
K-9 Mail version: 5.403/5.503

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by yuva-raj444** [comment]
server name | mail.cock.li
