### ISSUE TITLE
Command: SELECT "INBOX"; response: #15# [NO, Server Unavailable. 15] while fetching mail from outlook

### ISSUE THREAD

**Issue by vijaykvala** [k9mail/k-9#3574]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
INBOX mails should be fetched from outlook.

### Actual behavior
We get "Command: SELECT "INBOX"; response: #15# [NO, Server Unavailable. 15]. We are using oauth2. After getting the access token successfully from outlook, we are unable to fetch the inbox mails. We are getting mail counts and able to send mails sucessfully.
### Steps to reproduce
1. get the access token from outlook.
2. pass the token to tokenProvider class
3. send the command.

### Environment
K-9 Mail version: all

Android version: all

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This functionality is not part of the K-9 Mail version released by us. If you want paid support for issues related to our code base feel free to reach out to hello@cketti.de
