### ISSUE TITLE
Problem entering NEW sender email address that is similar to one in address book

### ISSUE THREAD

**Issue by jobst** [k9mail/k-9#3580]
When opening a new email and entering an email address that is NOT in the address book but is similar to one that already IS in the address book I am UNABLE to send an email.

If I have a addresses already in the address book like these:
  reception@example.com
  reception@otherdomain.com
and I want to send an email to a person that has the address of
  reception@newdomain.com
it will tell you either of two messages:
  - either tell me it is unable to scan the address and simply stop
  - it will simply stop accepting the email address and do nothing

In both cases the email address is greyed, if I want to add more characters to the address or trying to edit the addres it will simply wipe the exiting and START NEW. This was very frustrating especially when you simply want to send an email to the person at the reception desk.

### Expected behavior
Let me type the new address, even if it's one that is similar to an existing address and let me send the email. 

Also I do not want to enter all email addresses into the address book, sometimes I send an email to someone and then never again.

### Actual behavior
It did not let me type the new address WITHOUT entering it to a contact in the address book.
It will tell do two things:
  - either tell me it is unable to scan the address and simply stop
  - it will simply stop accepting the email address

The address is in the "To" field, greyed and the last character that I entered is there, too.

When trying to edit that address it simply deletes the address and I have to start all over again.

### Steps to reproduce
1. have one/two/more addresses in the address book that ALL start with the same name, e.g.
    reception@domain.com, reception@otherdomain.com, reception@stillanotherdomain.com
2. click on "send new email"
3. enter an email address that has the same FIRST part as in "reception@" and then try to use another domain
4. You will NOT be able to send this one, it will stop accepting character after the 3 char after the "@"

### Environment
K-9 Mail version: 5.403

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): It is IMAPS, but this is N/A as it is the parser of the TARGET email address that stuff it up, it stuff it up when entering the TARGET email address.

**Comment by cketti** [comment]
Probably #2829

**Comment by jobst** [comment]
Correct, it indeed is #2829.
