### ISSUE TITLE
App is deleting all but the last 30 days of emails in Inbox

### ISSUE THREAD

**Issue by craigj00** [k9mail/k-9#3599]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I noticed that one of my GoDaddy email accounts (I currently use 5 email accounts, 4 other GoDaddy and one Gmail, with my K9 Mail), the Inbox was only keeping the last 30 days of emails.  I removed the account from K9 Mail on my Samsung S8+ phone and the behavior of deleting all but the last 30 days of emails in the Inbox went away.  I added the email account once again and the behavior started up again.  I have the settings to keep all emails in the Inbox.

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.403

Android version:Kernel 4.4.78

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
K-9 Mail doesn't automatically delete emails from the server. But it's possible that setting up an account in K-9 Mail triggers that behavior on the server. Especially accessing a mailbox via POP3 is known to trigger all kinds of unexpected server behavior. Please contact GoDaddy support to ask why this is happening.
