### ISSUE TITLE
New release uploaded to the wrong channel on Google Play?

### ISSUE THREAD

**Issue by flocke** [k9mail/k-9#3601]
I just wanted to ask if you guys made a mistake uploading the APK for the latest release on Google Play. According to Github release 5.600 should be a stable release, yet it is uploaded only to the beta channel on Google Play.

We were just discussing bumping the version on F-Droid but were not sure if this release is considered stable because of the discrepancy mentioned above, so I just wanted to ask before doing something wrong.

See the F-Droid discussion here: https://gitlab.com/fdroid/fdroiddata/issues/1346

**Comment by cketti** [comment]
We're doing a staged rollout on Google Play. I changed the rollout of 5.600 to 100% just now. So feel free to use that version on F-Droid as well.

**Comment by flocke** [comment]
Thank you for your quick answer, I forwarded it to the guys at F-Droid, so it should be released there soon as well.
