### ISSUE TITLE
Can't select Unified Inbox

### ISSUE THREAD

**Issue by SR-gh** [k9mail/k-9#3604]
### Expected behavior
I try to configure K-9 Mail to use unified mailbox.
As far as I understand, this is trivially done by selecting the associated option, in parameters->Interaction.

### Actual behavior
The screen shows a greyed out option that I cannot select.

This behaviour arose after moving my data from an old phone to a new one.
I don't remember how exactly I operated in order to migrate things, but I think I've used the export/import parameter feature embedded in K-9 Mail.

### Environment
K-9 Mail version: 5.600
Android version: 8.0.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP accounts

**Comment by SR-gh** [comment]
Uninstalling/Reinstalling fixes the problem.

**Comment by cketti** [comment]
When "Global settings > Display > Hide special accounts" is checked it's not possible to enable "Global settings > Interaction > Start in Unified Inbox".
