### ISSUE TITLE
K9 uses mobile internet while connected with WLAN

### ISSUE THREAD

**Issue by kaumGott** [k9mail/k-9#3606]
Hello, 

K9 mail normally uses the WLAN if the phone is connected to it. But since a few days (possible about 2 weeks) K9 uses permanently 300kB traffic per hour via mobile internet.
When I manually check my mails the WLAN is used. But the history of my data management for traffic shows permanently the connection with mobile internet. 

### Expected behavior
Tell us what should happen: K9 should only use the mobile internet just when there is no WLAN connection.

### Actual behavior
Tell us what happens instead: K9 uses mobile internet permanently (about 300kB per hour) while connected to a WLAN and while using this WLAN parallel.

### Steps to reproduce
1. just running my mobile phone... ;)

### Environment
K-9 Mail version: 5.600

Android version: 7.0 NRD90M

Account type (IMAP, POP3, WebDAV/Exchange): 5x POP3

**Comment by cketti** [comment]
K-9 Mail doesn't favor mobile data over WiFi. It leaves the decision of which transport to use to the operating system. Please contact your device manufacturer (or custom ROM creator) to find out why your WiFi connection is not used. If we know why that is, we might be able to add a workaround in K-9 Mail.
If you can provide that information please post here. I'll then reopen the issue.

**Comment by kaumGott** [comment]
Normally K9 Mail doesn't use mobile data, that's right. I think you misunderstod me: in normal use while connected to a WLAN the WLAN is used actually. But in the background the app causes mobile data traffic. I have now forbidden the usage of mobile data - the app works as fine as ever.
This behaviour startet suddenly at 2018-08-20 and no other app act like that.
My phone is a Xiaomi Redmi Note 4 with MIUI Global 9.6 stable (9.6.2.0)

**Comment by cketti** [comment]
You could try using a network traffic analyzer to find out what kind of data is being sent/retrieved over the mobile connection. https://developer.att.com/video-optimizer might work.

Right now I have no reason to believe this is a bug in K-9 Mail itself.
