### ISSUE TITLE
Scrolling lags in message list

### ISSUE THREAD

**Issue by sas-3** [k9mail/k-9#3613]
### Expected behavior
Smooth scrolling as in message view

### Actual behavior
Lags when scrolling up or down

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): doesn't seem to matter

**Comment by cketti** [comment]
We're working on improving this. This issue is not necessary as a reminder.
