### ISSUE TITLE
Feature request: self set up spam filter

### ISSUE THREAD

**Issue by DonAndress** [k9mail/k-9#3619]
Hi.

One request/suggestion from my side:
Could you please add spam filter option? 
What I have in mind is that for each account there would be an individual filter, set up by email topic and/or sender email address, option to choose between hide spam in k9 Inbox and remove from server (and don't show in the Inbox) and remove from server would be applicable even if the general account setting to always leave email on sever is active.

Regards,
DonAndress

**Comment by cketti** [comment]
See #908, #679, and #1508.

**Comment by navid-zamani** [comment]
This should not be done client-side, but by using the server-side IMAP SIEVE command, no?
Thunderbird already does that, apparently. So setting it up in Thunderbird _should_ result in it working for every IMAP client, including K9…
Of course, having an interface for it in K9 would be a nice and in the long run necessary feature, to call it a full and modern client. But in any case, thanks to IMAP, not every client needs it. :)
