### ISSUE TITLE
F-Droid listing - incomplete anchor link on OpenKeyChain

### ISSUE THREAD

**Issue by life777eternal** [k9mail/k-9#3620]
There's no link on "OpenKeyChain" on the [F-Droid page](https://f-droid.org/en/packages/com.fsck.k9/) The link should be https://openkeychain.org but the anchor code isn't complete.
  
### Expected behavior
The link on "OpenKeyChain" should open https://openkeychain.org in a new tab/window.

### Actual behavior
Nothing happens when clicking on the link text.

### Steps to reproduce
1. Open [https://f-droid.org/en/packages/com.fsck.k9/](https://f-droid.org/en/packages/com.fsck.k9/)
2. Click on "OpenKeyChain"
3. Nothing happens

The current [Code](view-source:https://f-droid.org/en/packages/com.fsck.k9/) on Line 186 is: `<a>OpenKeychain</a>`

The code should be: `<a href="https://openkeychain.org" target="_blank">OpenKeyChain</a>`

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thank you.

https://github.com/k9mail/k-9/issues/new

**Comment by cketti** [comment]
Please report this issue to the F-Droid project.
