### ISSUE TITLE
Switching accounts | Toast Messages | Lack of "Delivery Status Notification" option

### ISSUE THREAD

**Issue by life777eternal** [k9mail/k-9#3621]
Would be nice if you could make switching accounts easier with a drop down menu, like [_K-@ Mail_](http://bit.ly/2OBmNAi) has. _ Although K-@ Mail doesn't yet support Encrypted email (they haven't updated their email app in a while. It has the option, but it aborts every time. Also it seems like their using a [Saturn Symbol](http://bit.ly/2Ef1BuN) on their app logo._) 

The Menu on the "Compose" page could use some adjustment(s). Would be nice if a check mark was added, in the stead of just the toast messages when tapping on "Read receipt" "Will request read receipt" or "Will not request read receipt." Also there's no option for Delivery Status Notification, like Thunderbird has. 

K-9 Mail also supports multiple accounts, but it's not immediately obvious how to add more accounts. Had to search on [StartPage.com](https://StartPage.com) to find out. Tap the Dog icon twice & a large plus(+) symbol appears at the bottom, tap that. 

### Expected behavior
Would be nice to see a drop down menu at the top of the list of emails to select another account.
Also would be nice to see a check mark beside "Read receipt" when it's enabled.
Additionally could you add "Delivery Status Notification" to that menu with a check mark when it's enabled ?  (Something like on Thunderbird.)

### Actual behavior
A toast message appears for a second.

### Steps to reproduce
1. Install & setup your email on K-9 Mail
2. Open your email list and tap the new email icon at the bottom. (Envelope with plus[+] on bottom right corner.)
3. Then tap the 3 vertical dots at the top right, & hit "Read receipt" notice the toast message, then tap the 3 vertical dots again and hit "Read receipt" again and notice the 'not' added to the toast message.  (If you hadn't selected to always request read receipts in the account settings, if you had that message would just be the opposite.

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Thank you.

**Comment by cketti** [comment]
Please create one issue per feature request. For most of them we already have one. Make sure to search for an existing issue before opening a new one.
