### ISSUE TITLE
substitution character of new line is displayed in subject

### ISSUE THREAD

**Issue by kmuto** [k9mail/k-9#3622]
### Expected behavior
ISO-2022-JP encoded subject often become long. It will be separated by newline + space.
```
Subject: =?ISO-2022-JP?B?GyRCRnxLXDhsJEhGfEtcOGwkSEZ8S1w4bCROJUElJyVDGyhC?=
 =?ISO-2022-JP?B?GyRCJS8bKEI=?=
```

It will be displayed one line as,
```
日本語と日本語と日本語のチェック
```

### Actual behavior
Newline character is displayed as substitution symbol.

![screenshot_20180921-114512](https://user-images.githubusercontent.com/183523/45857871-c2c0eb80-bd95-11e8-9c15-0d6a803f0f3b.png)

```
日本語と日本語と日本語のチェッ<?>ク
```

### Steps to reproduce
1. use subject what I wrote at Expected behavior.

### Environment
K-9 Mail version:5.6.00
as far as I know, it happened since September.

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Fixed in `master`.
