### ISSUE TITLE
Single Email freezes k9-mail

### ISSUE THREAD

**Issue by dgsiegel** [k9mail/k-9#3624]
### Expected behavior

1. Poll selected folder/whole account
2. New messages should load

### Actual behavior

k9-mail freezes while polling
The culprit seems to be the message I've attached below. Removing that message from my mailbox also removes the issue

### Steps to reproduce
1. Get a message like the one below
2. Poll for new messages
3. k9-mail freezes at that folder/message

### Environment
K-9 Mail version: 5.600

Android version: LineageOS 14.1 (Android 7.1.2)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

The culprit message:
[IHK_Akademie_Spezial.mbox.txt](https://github.com/k9mail/k-9/files/2404790/IHK_Akademie_Spezial.mbox.txt)

**Comment by cketti** [comment]
Thanks for providing a message to reproduce the issue.

The code we use to convert HTML to plain text seems to be responsible for the freeze (on my Desktop machine the conversion completed after 7 minutes). We run this code when adding message contents to the search index.

I created a pull request to change how we do the HTML to plain text conversion.
