### ISSUE TITLE
Authentication fail out of the blue!

### ISSUE THREAD

**Issue by Ad2Rock** [k9mail/k-9#3628]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

Mail should be received. I have the same email server on a number of phones and computers, mac and pc. Never any Issue and K9 runs almost perfectly always.,

### Actual behavior
Tell us what happens instead
suddenly last night i get - Set up could not finish - Username or Password incorrect. (POP3 login authentication failed: -ERR[Auth] Invalid login)

I rechecked the username and login. they are correct. All devices work except K9

### Steps to reproduce
1. Authentication failed - remains. I cannot resolve this issue
2.
3.

### Environment
K-9 Mail version:
5.6

Android version:
9

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
