### ISSUE TITLE
attachments with special characters in file name are saved with encoded filename

### ISSUE THREAD

**Issue by danieltakesphotos** [k9mail/k-9#3629]
### Expected behavior
receiving an attachement with a filename containing special characters like "ñ" shows the normal, human readable file name and saves under that name

### Actual behavior
I send an attachment called "moñi.jpg". It is shown with the encoded file name utf-8"%6D%6F....". When I save it do the download folder, android gallery doesn't show this image because it doesn't recognize its encoded extension. I must use a file manager to rename the file to its original (or any) name.
I live in Spain and these characters are used often, so often saving an attached file causes additional work.

### Steps to reproduce
1. Send an attachment with a file name that contains a special character like "ñ"
2. See the file name in the message received with K-9 

### Environment
K-9 Mail version: 5.6000

Android version: 7

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
![screenshot_20180925-124654](https://user-images.githubusercontent.com/43571253/46009994-79d4a400-c0c1-11e8-91f3-4f2287573dd3.png)

**Comment by cketti** [comment]
This was fixed with PR #3570. The fix will be included in the next major stable version (5.8xx).

**Comment by PHPGangsta** [comment]
Is there a roadmap, or an estimation when 5.8xx will be released?
