### ISSUE TITLE
[Feature request] Add an option to untrash an e-mail

### ISSUE THREAD

**Issue by marmistrz** [k9mail/k-9#3630]
### Expected behavior
After moving the message to trash, there should be an easy way to undo it

### Actual behavior
The only way is to use `move` after entering the trash folder, which often fails because the folder is not synchronized with the remote one. (i.e. no way to untrash when being offline)

### Environment
K-9 Mail version: 5.600
Android version: LOS 14.1
Account type: IMAP

**Comment by cketti** [comment]
See #624
