### ISSUE TITLE
RFE: sync on wi-fi only? (network choice)

### ISSUE THREAD

**Issue by sphakka** [k9mail/k-9#3636]
Am I wrong or there's no way to configure sync/fetch on **wi-fi only** (like for f-droid, playstore, etc.)? I'd like to have the choice: wi-fi | LTE | both | none (manual).

### Environment
K-9 Mail version: 5.600
Android version: 7.1.2 (LineageOS 14.1)
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Duplicate of #617
