### ISSUE TITLE
Opening a previously written draft containing HTML links will only retains plaintext (not links)

### ISSUE THREAD

**Issue by mbideau** [k9mail/k-9#3640]
Hi all,

This is almost a duplicate of #3486 (slight different UX) and related to #2485.
So feel free to close it if it you consider it as a duplicate.
Solving one resolve the other I think.

### Expected behavior
I open a draft in K9mail that was previously written by another email client (like Thunderbird) and that contains HTML links. I must be able to edit the draft mail in the existing HTML formating (not converting links to just plain text, losing url) or at least be warned that a convertion will happen and allow me to discard editing without any effect (but allow me to send the mail, with no convertion).

### Actual behavior
I open a draft in K9mail that was previously written by another email client (like Thunderbird) and that contains HTML links. I loose HTML links formatted that are replaced by their text, loosing the URL information, without any warning. I cannot rollback the convertion effect, because when I leave the editor mode, it offers me to discard changes (but save the converted-to-plain-text version, not the original HTML one) or to suppress the draft. Neither option are OK or a good UX.

### Steps to reproduce
1. Write an email in another email client (like Thunderbird) containing HTML links and save it to Draft folder
2. Open it with K9mail
3. See that it has been converted to a plain text version loosing HTML links url without any warning.
4. When leaving the editor mode, see that it can only keep the plain-text version or remove the draft.

### Thanks
It is never said enought, so: THANK YOU all for this app!

### Environment
K-9 Mail version: 5.403

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
K-9 Mail currently doesn't support rich text editing. See #1745.

**Comment by PhilippSchlesinger** [comment]
Please reconsider evaluating this issue with regard to the thunderbird merge.
