### ISSUE TITLE
k9 Mail has stopped working correctly

### ISSUE THREAD

**Issue by bmoliver** [k9mail/k-9#3645]
### Expected behavior
K9 Mail should show all new and old emails

### Actual behavior
K9 Mail is only loading the first 4 or 5 current messages and then skipping all the rest and then showing the last few messages on the server.

### Steps to reproduce
1.  Loading inbox shows emails from Oct. 4 to Oct. 2 and then from 2015.  All emails in between are missing.  All emails show correctly on the email web client, eM Client, and Thunderbird for the same server.
2.  Un-installing and re-installing doesn't fix the issue on either device.
3.

### Environment
K-9 Mail version: Current version (just un-installed on both devices)

Android version: 8.1.0 (Nexus 5X) and 5.0.1 (ASUS tablet)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Bobyl** [comment]
I found this behaviour to be not related to k-9 (tried with boxer, blue mail and gmail) but to the mail account used: on every client, mails between june and sept 2018 are not displayed on one of my accounts.

Only workaround found for now is to sync all mail of this account in k-9.

**Comment by bmoliver** [comment]
Bobyl.  I just tested it again on my new phone (Huawei P20).  However, the problem is still the same for both of my email accounts (Gmail and Shaw).  For Gmail, it shows 15 message from today back to Oct 12, and then 5 messages from 2008.  With Shaw, it shows 19 messages from Oct 12 back to Oct 1, and then 14 messages from 2015.  If I change the local folder size from 25 to all messages (in Shaw), then it shows all the emails in the correct order.  However, I don't want the local folders to be that large (particularly for Gmail).  So, I don't see any solution - something has changed recently in K-9 Mail??

BTW, other Android email clients (e.g., Blue Mail) do not have this problem.

**Comment by cketti** [comment]
See #1642
