### ISSUE TITLE
Can I use K-9 email client for debugging email on my android galaxy phone?

### ISSUE THREAD

**Issue by kopax** [k9mail/k-9#3647]
Hi, somebody told me about k-9 when I asked how I could debug my HTML template email on my Galaxy  
 #android phone.

That's all he said. Can I really view why my email render in a certain way on Android using K9?

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by kopax** [comment]
Support? How can I need support if I do not even use k-9?
