### ISSUE TITLE
Second line in head not visible

### ISSUE THREAD

**Issue by sphh** [k9mail/k-9#3664]
On my tiny phone (https://www.unihertz.com/jelly.html) with a screen size of 240x432px, the second line in the header is not shown:

Screenshot polling an account:
 ![screenshot_20181017-223123](https://user-images.githubusercontent.com/4856462/47151258-87a0d200-d2d9-11e8-987b-0963712ae790.png)

Screenshot showing an account:
 ![screenshot_20181017-223419](https://user-images.githubusercontent.com/4856462/47151297-a1421980-d2d9-11e8-947a-10f532283cac.png)

### Expected behavior
I would expect the second line to be shown.

### Actual behavior
The second line is cut of.

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

**Comment by cketti** [comment]
This should no longer be an issue in the next stable version.
