### ISSUE TITLE
Disable email deletion per account settings

### ISSUE THREAD

**Issue by wilbauk** [k9mail/k-9#3665]
I don't want to delete emails by mistake.
Disable email deletion per account settings.
"When i delete an email" - Do nothing!

**Comment by cketti** [comment]
Are you asking for a setting to completely disable the delete functionality?

**Comment by wilbauk** [comment]
Yes, per account. Personally i have unknowingly deleted dozens of emails over the last 6 months, some of which have been quite important. Probably accidental key presses in my pocket or something. 
I am with one.com and currently use POP3 and pickup all mail at home on a PC - left on server for 3 months. I have been able to retrieve these missed emails from Trash folder using webmail to move to inbox.

**Comment by cketti** [comment]
In my opinion it's not the responsibility of an app to prevent unintended touches. That's what lock screens are for. To prevent accidental message deletions K-9 Mail has the option to ask for confirmation before deleting a message. I don't see a need to add anything beyond that.

**Comment by wilbauk** [comment]
of course i use a lock screen. i had no confirmation request, perhaps they were being deleted by some other means, a bug?
