### ISSUE TITLE
Chromebook: white bar remains after closing app

### ISSUE THREAD

**Issue by ExTechOp** [k9mail/k-9#3666]
### Expected behavior
On Chromebook, when exiting (fullscreen) K-9 mail, all windows and popups close.

### Actual behavior
A white bar with a (non-functioning) close "×" symbol is opened by K-9 and left behind on the top of the screen. This behavior started after last K-9 update. I suspect K-9 is trying to open an alert and mysteriously failing.
![screenshot 2018-10-18 at 22 45 56](https://user-images.githubusercontent.com/12744438/47179789-a8901400-d327-11e8-9d0b-829e8413071b.png)

### Steps to reproduce
1. Start K-9
2. Exit
3. White bar remains at top of screen, the only way to get rid of it is to log out.

### Environment
K-9 Mail version:
5.600

Android version:
Google Chrome OS Version 69.0.3497.120 (Official Build) (32-bit)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
That sounds like a Chrome OS bug rather than a K-9 Mail bug.
