### ISSUE TITLE
Send digitally signed emails with email certificates

### ISSUE THREAD

**Issue by SeriousHoax** [k9mail/k-9#3674]
Is it possible to send digitally signed email using email certificates. For example Comodo: https://www.comodo.com/home/email-security/free-email-certificate.php

In Mozilla Thunderbird I can import certificates to digitally sign my emails as well as use that certificates to encrypt my messages. I know about OpenKeyChain support in K9 but I'm only interested in sending digitally signed emails using Comodo certificates just the way I can easily do it on Thunderbird? 

Is it possible?

**Comment by cketti** [comment]
See #1003
