### ISSUE TITLE
Notification rules

### ISSUE THREAD

**Issue by seth100** [k9mail/k-9#3675]
Hi,

I really would appreciate to have a feature to check for notifications in specific days only and for specific account, e.g. "check for notifications in all days but Saturday and Sunday".

Thanks a lot

**Comment by doktorhorst** [comment]
Being able to set notification rules more specifically in different ways would be a huge enhancement. Like e.g.
* notify me for emails from selected contacts / specific mail adresses
* notify me when a specific keyword is used in the subject field (or in the whole email)

**Comment by petesimonic** [comment]
As a user friendly and not sofisticated solution I propose to create a simple way to deprioritize notification based on domain, name, and keyword. So that minor things wouldn't distract you via watches but still be available for easy reach.

**Comment by cketti** [comment]
I created #5118 for a rule-based notification system. For more flexibility in specifying at what times to allow notifications see #993.
