### ISSUE TITLE
Download Complete Message creates new timestamp

### ISSUE THREAD

**Issue by smvsmvsmv** [k9mail/k-9#3684]
### Expected behavior
When executing "Download complete message" the message should retain its original timestamp and position in the message list.

### Actual behavior
When executing "Download complete message" the message picks up a new timestamp (the current time) and is refiltered to the top of the message list, losing its position in the "sorted list.  

These attachments show screenshot of the same message before and after downloading complete message.

![20181027_123100](https://user-images.githubusercontent.com/35177223/47607364-9b88ba00-d9e4-11e8-81f7-c53afaf873b1.jpg)

![20181027_123137](https://user-images.githubusercontent.com/35177223/47607366-a2173180-d9e4-11e8-8cbd-512d1b5aa2ca.jpg)

### Steps to reproduce
1. "Download complete message"
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: Oreo 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
See #1356
