### ISSUE TITLE
Notifications / Download - LG V40 / Android 8.1.0

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#3686]
The LG V40 has no LED for notifications.  In locked screen there are no K-9 download or notifications.   K-9 does provide notification when not in locked screen. I am using 'always on display'. 

Tell us what should happen
Download should occur and sound notification in Locked Screen when email arrives.  Visual notification afterwards (perhaps blinking to save power).  Perhaps display a dot (.gif) on screen for incoming mail. Other dots in different screen location for other notifications.

Tell us what happens instead
No download or notifications on Locked Screen (sound or visual).  (Note:  LG V40 has NO NOTIFICATION LED)

### Steps to reproduce
1. Enable 'always on display'
2. Insure LG V40 is in Locked Screen mode
2. Send email to K-9 account
3. Observe no download or notification

### Environment
K-9 Mail version: 5.6
Android version:  8.1.0 Security patch Oct 1,2018

Account type - POP3

**Comment by cketti** [comment]
Might be an issue with notifications on the lock screen similar to #845.

If sync isn't happening it's #3950
