### ISSUE TITLE
background sync only when android's auto-sync enabled (request)

### ISSUE THREAD

**Issue by gloschtla** [k9mail/k-9#3693]
This app should not start syncing when connected to an untrusted public wifi network. Android lets me define, which wifi SSIDs shall trigger the auto-sync mode. This way prevents my passwords being sent via unencrypted WiFi.

**Comment by gloschtla** [comment]
i prefer doubled securing: 
encrypted IMAP plus encrypted WiFi.

**Comment by lindhe** [comment]
I like the idea just because it makes power saving easier. I don't have to go into a hundred apps and change each and every one of them to not sync. Instead I can just flip a switch and everything should stop syncing.

**Comment by cketti** [comment]
Set 'Global settings > Network > Background sync' to 'When Auto-sync is checked'.

**Comment by gloschtla** [comment]
@chetti, this did not address the problem I described above. 
I don't want to share my email password in open wifi hotspots when other users of the same local IP can hack my phone or even my email accounts!
