### ISSUE TITLE
Update Italian translation

### ISSUE THREAD

**Issue by RizzoV** [k9mail/k-9#3694]
### Expected behavior
The correct translation for "Push folders" in Italian is "Cartelle Push", as correctly translated on Transifex _since 2 months_.

### Actual behavior
The string in Account settings -> Fetching emails for "Push folders" is currently "Cartelle d'invio", which means "Sending folders" and makes no sense.

### Steps to reproduce
1. Set the app language to Italian
2. Go to Account settings -> Fetching emails

### Environment
K-9 Mail version: 5.600

Android version: 9 (Pie)

Account type (IMAP, POP3, WebDAV/Exchange): Any

**Comment by cketti** [comment]
Please update the translation on Transifex: https://www.transifex.com/k-9/k9mail
