### ISSUE TITLE
Indicator Symbol missing

### ISSUE THREAD

**Issue by FraCro** [k9mail/k-9#3696]
i use

k-9 Mail 5.600
oreo 8.0.0
on huawei p10 lite
with EMUI 8.0.0

and there is no Indicator Emblem with the number of unread mails on my k-9-icon. In the App-Preferences there is no option, to activate the indicator Emblem. Other Apps, like web.de, Telegram or Threema have Indicators. Is it a bug of k-9 ?

Hopeful, Frank

**Comment by cketti** [comment]
See #1104
