### ISSUE TITLE
Can't send messages through OpenSMTPd

### ISSUE THREAD

**Issue by oriold** [k9mail/k-9#3697]
### Expected behavior
To send an email with OpenSMTPd as mail server with encryption provider configured.

### Actual behavior
Message gets rejected as OpenSMTPd, still not aware of Autocrypt flags the message as invalid because of the header being to long. Unfortunately there is still no support for this feature, but I will enable as it becomes supported.

### Steps to reproduce
1. Have encryption provider configured.
2. Send message to an OpenSMTPd server

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Can you please attach such a message.

Currently, the first part of the Autocrypt header isn't correctly folded. But the only variable part in there is the email address. Since email addresses are length limited I don't see how the Autocrypt header could exceed the maximum line length of 998 characters. The key data itself is properly folded.

**Comment by oriold** [comment]
![k-9_mail](https://user-images.githubusercontent.com/2779594/48207382-6c6d3380-e368-11e8-8865-2679124ee882.png)

**Comment by oriold** [comment]
Disabling encryption provider gets rid of this message.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by oriold** [comment]
[logcat_11-08-2018_16-09-09.txt](https://github.com/k9mail/k-9/files/2562510/logcat_11-08-2018_16-09-09.txt)

**Comment by cketti** [comment]
Did you manually clean the log? The server is sending an error response (that should be included in the log, but isn't) and K-9 Mail is failing to parse the response.

**Comment by oriold** [comment]
Issue had nothing to do with K9 Mail, apologies. Reconfiguration of server solved the issue.
