### ISSUE TITLE
issue with namespace

### ISSUE THREAD

**Issue by be-root** [k9mail/k-9#3704]
### Environment
K-9 Mail version: all
Android version: all
Account type (IMAP)

Hi!

My separator was '/'.
My directory is like this:          K9 show it like this:         K9 should be show it like this:

Sent                                        Sent                                Sent
Trash                                      Trah                                Trash
INBOX                                     Indox                              Inbox
INBOX/Abc                              INBOX/Abc                        Abc
INBOX/Abc/Def                        INBOX/Abc/Def                     Def
INBOX/Bab                              INBOX/Bab                        Bab
...

The current view is very confusing. Is there a way to change the display of the namespace?

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
