### ISSUE TITLE
Update notification channels when system locale changes

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#3720]
If K-9 Mail is configured to use the system language ('General settings > Display > Language' is set to 'System default') we need to update the name and description of notification channels to use the currently selected system language.

The `NotificationChannel` documentation suggests registering a broadcast receiver for [`Intent.ACTION_LOCALE_CHANGED`](https://developer.android.com/reference/android/content/Intent.html#ACTION_LOCALE_CHANGED).
We should disable that broadcast receiver when the user configured K-9 Mail to use a language different from the system settings.

We also need to update notification channel names and descriptions when the user changes the language setting of K-9 Mail.

**Comment by ittchio** [comment]
Hi, I would like to work on this.
