### ISSUE TITLE
Update notification channels when creating or deleting an account

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#3721]
Right now notification channels are created/deleted/updated when `MessageList` is started. That feels like the wrong place to do it. Instead we should do it when the user adds or removes an account (also when the language is changed, see #3720).

**Comment by Valodim** [comment]
This seems like a wishlist item. Do you think the way it's handled now leads to breakage, or is it just not very pretty?

**Comment by cketti** [comment]
I'm guessing not too many users will go to Android's notification settings while the notification channel configuration is out of date. But if they do, it's a very unfortunate user experience.

I want to fix #3597 by adding the ability to listen for account changes. Once that's implemented, fixing this should be easy.
