### ISSUE TITLE
k9 thinks there is no network - sync disabled no network

### ISSUE THREAD

**Issue by chrcoluk** [k9mail/k-9#3726]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
should sync when wifi connected

### Actual behavior
it sits idle regardless if screen is on or off, reason sync disabled no network

### Steps to reproduce
1. install k9 on android 8.,x oneplus6
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by chrcoluk** [comment]
To add I have obviously verified there is internet connectivity, if I simply hit the refresh button in k9 it fetches email fine.

**Comment by cketti** [comment]
Sorry for that. Our code currently doesn't work well with the energy saving mechanisms in newer Android versions. We know we need to work on this.
Closing this issue because it doesn't provide more information than the countless other issues.
