### ISSUE TITLE
Superfluous Spam folder

### ISSUE THREAD

**Issue by subcon42** [k9mail/k-9#3727]
### Expected behavior
Non-existent folders should not exist in K9 if suitable alternatives have been configured (see Actual Behavior section).  

Local (so called Offline) folders should be removable or allowed to be made wholly invisible at least.

### Actual behavior

K9 seems to create a *local* Spam folder (local to the K9 client itself, and *not* on the IMAP server side).  I do not want this, since I already use a folder called "Junk", as do all other clients of mine. 

I can confirm the undesirable "Spam" folder only "exists" within K9, as I am also the IMAP admin and can log directly into the server to verify.  A "Spam" folder absolutely does not exist as an IMAP folder within my account.

I have confirmed K9 is, in fact, using the correct "Junk" folder (per my settings) ... yet I cannot hide, nor delete, the superfluous "Spam" folder from K9.

### Steps to reproduce

1. Open the folder list and find "Spam" (it exists)
2. Attempt to hide/delete/etc "Spam" folder fails; it is a fruitless exercise, since K9 seems to not allow such actions, hence this ticket
3. For good measure, visit K9 Settings, confirm junk email is, in fact, being sent to desired (and configured) "Junk" folder on the IMAP server itself (it is)
4. Confirm this issue is not seen using any other relevant client, including Thunderbird and Roundcube web-mail (confirmed)
5. As mentioned earlier, confirm IMAP folder hierarchy on my server does not possess a "Spam" folder at the relevant location (confirmed it does not exist)

### Environment
  * K-9 Mail version: 5.600
  * Android version: 8.1.0
  * Account type: IMAP

**Comment by cketti** [comment]
IMAP accounts should only have a local Outbox folder. Everything else should be synchronized with the server. Try updating the folder list by going to the folder list screen, then selecting "Refresh folder list" from the menu.
If the Spam folder doesn't disappear that's a bug. But you can always hide it by going to folder settings and setting the folder display class to "No class"

**Comment by cketti** [comment]
Closing this issue. Please post here if the folder doesn't disappear and we'll reopen the issue and have a closer look.
