### ISSUE TITLE
reply button missing whith mixed inbox/sent folger

### ISSUE THREAD

**Issue by thoschi** [k9mail/k-9#3735]
### Expected behavior
If you like to have a conversation view, it makes sense to put SENT mail into INBOX - so far easy to set up in K9.
It should anyway be possible to REPLY to mails from INBOX.

### Actual behavior
If you open any mail from an INBOX that is also the place for SENT, there will be no REPLY button in mail.
You can reply from INBOX-List via right click though.

### Steps to reproduce
1. set INBOX as place for SENT mail
2. open any mail you got from INBOX
3. in (any) mail view the REPLY button is missing

### Environment
K-9 Mail version: 5.6
Android version: 8.1.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
I can't reproduce this. Maybe the reply/send actions moved to the overflow menu.
Anyway, with the UI changes that will make it into the next stable version this will most likely no longer be an issue.
