### ISSUE TITLE
Site Certificate Expired Issue

### ISSUE THREAD

**Issue by ukmerlin** [k9mail/k-9#3746]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
In the event a site certificate is expired or invalid it should warn that is the case and allow options.
### Actual behavior
Tell us what happens instead
The application appears to be getting mail but never retrieves any. It becomes apparent when other mail retrieval such as PC works.
### Steps to reproduce
1. Poll mail from host with expired or invalid certificate
2.
3.

### Environment
K-9 Mail version: 5.600

Android version:
8.0.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Duplicate of #3459
