### ISSUE TITLE
enhancement: notifications of e-mails coming in subfolders

### ISSUE THREAD

**Issue by narayaan** [k9mail/k-9#3754]
When I receive an e-mail in one of my subfolders of my hotmail (outlook) account, I don’t get any notification from K9. It would be nice if the app would also give a notification of this.

### Expected behavior
k-9 gives a notification of any received e-mail

### Actual behavior
I only get notifications when something arrives in my main inbox.

### Steps to reproduce
1. Create a ruile that a certain email(adress) will allways be recieved in a subfolder in outlook (hotmail).
2. use k9
3.

### Environment
K-9 Mail version: 5.600

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
You need to configure those folders to be checked for new messages. See https://k9mail.github.io/documentation/folders.html
