### ISSUE TITLE
  Don’t use a new folder for sent e-mails

### ISSUE THREAD

**Issue by narayaan** [k9mail/k-9#3755]
K 9 creates a new folder with sent emails in my outlook (hotmail) account. Isn’t there a way to use the original folder?

### Expected behavior
k9 synchronizes neatly with my sent emails folder in my outlook (hotmail) account.

### Actual behavior
k-9 creates a new folder.

### Steps to reproduce
1. Install k-9
2. Send an e-mail
3. Log in into your e-mail account by using your browser, you'll notice k-9 created a new folder

### Environment
K-9 Mail version: 5.600

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):

update: spelling

**Comment by ildar** [comment]
I confirm. + for Drafts.
BTW, folder name is l10n-ed (i.e. in current Android locale)

**Comment by cketti** [comment]
The next stable version won't create new folders automatically.
You can configure special folders under 'Account settings > Folders'.
