### ISSUE TITLE
The arrow showing the reference disappears from the email creation UI.

### ISSUE THREAD

**Issue by suyeon-9706** [k9mail/k-9#3770]
### Expected behavior
When I try to create a new email, 
click the arrow in the UI to display the reference function in the UI
and If I click one more time, hide the reference function in ui.

### Actual behavior
When I try to write a new email, click the arrow that displays the reference function in the UI, the arrow disappears.

### Steps to reproduce
1. Move a new email sender.
2. Tap the arrow.
3. Write a reference feature.
4. If you do not want to see the reference function in the UI, click the arrow once more.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by cketti** [comment]
See https://github.com/k9mail/k-9/pull/3773#issuecomment-443436915
