### ISSUE TITLE
SMTP PIPELINING: K-9 displays wrong reply code and error message

### ISSUE THREAD

**Issue by jatoko** [k9mail/k-9#3778]
The current implementation of K-9's [SMTPTransport.java](https://github.com/k9mail/k-9/blob/b3c0021edbc8a0d9b73beb2f45eee3fbc21ced33/mail/protocols/smtp/src/main/java/com/fsck/k9/mail/transport/smtp/SmtpTransport.java) returns the last error message instead of the first one.
Consequently, users cannot make an informed decision on how to handle the error, because the true error source is hidden.

[RFC2920](https://tools.ietf.org/html/rfc2920#section-3.1) also demands that "Client SMTP implementations that employ pipelining MUST check ALL statuses associated with each command in a group.".

An example, where a server cannot handle the RCPT TO command and returns 550 but user sees 502:

#### Mailserver's view
 MAIL FROM:<ky@example.com> BODY=8BITMIME
 250 Roger, accepting mail from <ky@example.com>
 RCPT TO:<550@test.rcpt.code>
 **550 Middleware RCPT says 550**
> Server cannot handle the rcpt address and returns error.

 DATA
 502 Missing RCPT TO command.
> Followup error

 QUIT
 221 Goodnight and good luck

#### K9's view
 SmtpTransport: SMTP >>> MAIL FROM:<ky@example.com> BODY=8BITMIME
 SmtpTransport: SMTP >>> RCPT TO:<550@test.rcpt.code>
 SmtpTransport: SMTP >>> DATA
 SmtpTransport: SMTP <<< 250 Roger, accepting mail from <ky@example.com>
 SmtpTransport: SMTP <<< **550 Middleware RCPT says 550**
 SmtpTransport: SMTP <<< **502 Missing RCPT TO command.**
> K9 displays the last error, however, the first error is the **true** source and should get reported to the user.

 SmtpTransport: SMTP >>> QUIT
 SmtpTransport: SMTP <<< 221 Goodnight and good luck

### Expected behavior
K-9 should return all or the first error message.

### Actual behavior
K-9 returns last error message.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP,SMTP

**Comment by Valodim** [comment]
Not sure how we could handle all the responses, but handling the first that fails rather than the last one sounds reasonable to me, since all following errors may well be caused by the initial failure. Done in #3799
