### ISSUE TITLE
Application crash during writing email

### ISSUE THREAD

**Issue by ps-goog** [k9mail/k-9#3794]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
No crash.
You should add autosave option local or server to recover something in case of crash

### Actual behavior
Application crashes during writing email on Samsung galaxy Tab 3 using pen and Google keyboard

### Steps to reproduce
It happens accidentally

### Environment
K-9 Mail version: 5,6

Android version:
Android Version = 8.0.0

ccount type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by wiktor-k** [comment]
@ps-goog, crash information you send to google is heavily filtered and often doesn't reach the developer. Even if it does it's hard to correlate specific bugs with exceptions.

Your log is the fastest and most reliable way of getting this bug fixed.
