### ISSUE TITLE
Add collapse button to Cc / Bcc

### ISSUE THREAD

**Issue by suyeon-9706** [k9mail/k-9#3796]
The reason I uploaded this issue is because I did not know how to hide the reference when I first wrote the email in this app.
So I wanted to make ui more comfortable.

### Expected behavior
When I try to create a new email,
click the expand button in the UI to display the Cc/Bcc in the UI 
and It changes from expand button to collapse button.
 If user enter the perfect Cc/Bcc and click the collapse button, display the Cc/Bcc on UI
and, If user enter incomplete Cc/Bcc and blank spaces, disappear when click the collapse button.

### Actual behavior
When I try to write a new email, click the expand button that displays the Cc/Bcc in the UI, the button disappears.

### Steps to reproduce
1. Move a new email sender.
2. Tap the expand button.
3. It changes from expand button to collapse button.
3. Write a Cc/Bcc.
4. If user click the collapse button, display only perfect Cc/Bcc on UI
5. It changes from collapse button to expand button.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by cketti** [comment]
As mentioned in https://github.com/k9mail/k-9/pull/3773#issuecomment-443436915 I think the current behavior is fine.
