### ISSUE TITLE
[Request] Allow custom sender adresses

### ISSUE THREAD

**Issue by malnvenshorn** [k9mail/k-9#3805]
At the moment it's only possible to select a sender address from predefined identities. I would like to be able to enter a custom one. The reason is that I use a lot mail extensions and creating/maintain them as separate identities is simply not feasible.

**Comment by knobhead** [comment]
I agree, that's a rather advanced feature, but very useful for power users and fans of catch-all e-mail addresses.

**Comment by cketti** [comment]
Duplicate of #935
