### ISSUE TITLE
K9mail uses 1.27 GB of space

### ISSUE THREAD

**Issue by Xwang1976** [k9mail/k-9#3810]
I have k9mail with 4 accounts (3 gmail and 1 from another provider).
All of them use IMAP and K9mail uses 1.27GB of space on my smartphone

### Expected behavior
K9mail should use bout the same space as the gmail app (which uses 25.42 MB)

### Actual behavior
K9mail uses 1.27GB

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.600

Android version:
8.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Please try changing the "Sync messages from" setting: https://k9mail.github.io/documentation/settings/account.html
