### ISSUE TITLE
Messages with attachments get on top regardless of date

### ISSUE THREAD

**Issue by alberginia** [k9mail/k-9#3815]
### Expected behavior
Messages should be sorted by date regardless of anything else.

### Actual behavior
Messages with attachments are sorted by date at the top, and then the rest of the messages are sorted by date below those.

### Steps to reproduce
1.Open K-9 Mail
2.Click on folder view
3.Enter any folder

### Environment
K-9 Mail version: 5.600

Android version: 7.0
(Security patch: 5th August 2017)
(Kernel version: 3.18.35)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (Gmail accounts)

**Comment by cketti** [comment]
Sounds like you accidentally changed the sort order to sort by attachments. 

Go to the message list screen, click on the icon with three horizontal lines getting shorter towards the bottom and select "Date".
