### ISSUE TITLE
Delivery status notification, invalid header section: bad MIME 

### ISSUE THREAD

**Issue by life777eternal** [k9mail/k-9#3820]
Delivery status notification, invalid header section: bad MIME 

Your message WAS SUCCESSFULLY RELAYED to:
<>

This delivery report was generated by the program amavisd-new at host.
Our internal reference code for your message is 

INVALID HEADER: BAD MIME HEADER SECTION OR BAD MIME STRUCTURE

MIME error: error: unexpected end of header

Return-Path: <>
From: 

### Expected behavior
The recipients view of the emails should not be blank 

### Actual behavior
The Emails are blank for the recipients when sending to multiple emails in BCC only. 

### Steps to reproduce
1. Forward or create a new 🆕 email with plenty of text
2. Expand CC & BCC
3. Enter as many emails as you want to BCC, leave the others empty. (optionally include an other email of your own) 
4. Enable Read Receipt 
5. Send the email 
6. Ask one of your recipients through another secure channel to reply to this email. 
7. Observe the blankness. 

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
I don't understand. Can you please describe what exactly the issue is? Does K-9 Mail generate a malformed message? Does K-9 Mail have issues displaying a certain message?

**Comment by cketti** [comment]
Can you provide the message source of such an email? Recipients should be able to use the "forward as attachment" feature available in many clients to send you a byte identical copy of the original message as attachment. Alternatively, many clients have a way to display the message source. In Gmail's web interface it is called "show original".

**Comment by cketti** [comment]
No information provided.
