### ISSUE TITLE
Add features to mark all selected mail as read mail

### ISSUE THREAD

**Issue by suyeon-9706** [k9mail/k-9#3827]
### Expected behavior
Add features to mark all selected mail as read mail (mark all unread mail) when multiple mails are selected in the mailbox

### Actual behavior
The current feature is displayed as read mail for all mails

### Steps to reproduce
1. Move the mailbox
2. Select some mails
3. 

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by cketti** [comment]
The action to mark selected messages read/unread is already available in the action mode bar at the top.
