### ISSUE TITLE
gmail stopped working through CDMI (4G/3G/...) - "unknown device"+"Critical security alert"

### ISSUE THREAD

**Issue by yusosov** [k9mail/k-9#3833]
+ Suspicious sign-in attempt prevented every time I want to get/send emails throgh CDMI.
K-9 Mail version: latest, but it started with the previous version several month ago
On wifi I can alwais login. And before everything worked well.

IMAP
*Android version: 5.1, 
* Google account settings>Security:
Use your phone to sign in - Off
2-Step Verification - Off
Less secure app access - On 
* Google account settings>data-and-personalization>Activity Controls
Web & App Activity - Paused
Location History - Paused
Voice & Audio Activity - Paused
Device Information - Paused
YouTube Search History - Paused
YouTube Watch History - Paused

I suspect that now Google wants me to turn ON
at least Device Information or maybe more in
Google account settings>data-and-personalization>Activity Controls
I will try and let you know.

**Comment by philipwhiuk** [comment]
Mainly just a duplicate of #655
