### ISSUE TITLE
[5.600 ParseException] Trying to open messages from specific sender

### ISSUE THREAD

**Issue by sam2kb** [k9mail/k-9#3834]
### Expected behavior
Open messages from any sender

### Actual behavior
App crashes trying to open any message from specific sender

### Steps to reproduce
1. Open any message from sender Nicolás
2. Observe the app crashing

### Environment
K-9 Mail version: 5.600
Android version: 9, stock OxygenOS
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### The app can't parse his name
`org.apache.james.mime4j.field.address.ParseException: Lexical error at line 1, column 6.  Encountered: "\ufffd" (65533), after : ""`

```
12-18 23:53:56.358 19601 19601 D MessageViewFragment: MessageView displaying message MessageReference{accountUuid='000000000000', folderName='INBOX', uid='99', flag=null}
12-18 23:53:56.359 19601 19601 D MessageLoaderHelper: Creating new local message loader
12-18 23:53:56.371 19601 19601 E Address : MimeException in Address.parse()
12-18 23:53:56.371 19601 19601 E Address : org.apache.james.mime4j.field.address.ParseException: Lexical error at line 1, column 6.  Encountered: "\ufffd" (65533), after : ""
12-18 23:53:56.371 19601 19601 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:41)
12-18 23:53:56.371 19601 19601 E Address : 	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.mail.Address.parse(Address.java:146)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.mail.internet.MimeMessage.getSender(MimeMessage.java:344)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.view.MessageHeader.shouldShowSender(MessageHeader.java:370)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:311)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
12-18 23:53:56.371 19601 19601 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:497)
12-18 23:53:56.371 19601 19601 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:465)
12-18 23:53:56.371 19601 19601 E Address : 	at android.content.Loader.deliverResult(Loader.java:157)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
12-18 23:53:56.371 19601 19601 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
12-18 23:53:56.371 19601 19601 E Address : 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:272)
12-18 23:53:56.371 19601 19601 E Address : 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:96)
12-18 23:53:56.371 19601 19601 E Address : 	at android.os.AsyncTask.finish(AsyncTask.java:695)
12-18 23:53:56.371 19601 19601 E Address : 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
12-18 23:53:56.371 19601 19601 E Address : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
12-18 23:53:56.371 19601 19601 E Address : 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 23:53:56.371 19601 19601 E Address : 	at android.os.Looper.loop(Looper.java:193)
12-18 23:53:56.371 19601 19601 E Address : 	at android.app.ActivityThread.main(ActivityThread.java:6863)
12-18 23:53:56.371 19601 19601 E Address : 	at java.lang.reflect.Method.invoke(Native Method)
12-18 23:53:56.371 19601 19601 E Address : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
12-18 23:53:56.371 19601 19601 E Address : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 23:53:56.372 19601 19601 E Address : MimeException in Address.parse()
12-18 23:53:56.372 19601 19601 E Address : org.apache.james.mime4j.field.address.ParseException: Lexical error at line 1, column 6.  Encountered: "\ufffd" (65533), after : ""
12-18 23:53:56.372 19601 19601 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:41)
12-18 23:53:56.372 19601 19601 E Address : 	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.mail.Address.parse(Address.java:146)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.mail.internet.MimeMessage.getSender(MimeMessage.java:344)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:314)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
12-18 23:53:56.372 19601 19601 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:497)
12-18 23:53:56.372 19601 19601 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:465)
12-18 23:53:56.372 19601 19601 E Address : 	at android.content.Loader.deliverResult(Loader.java:157)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
12-18 23:53:56.372 19601 19601 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
12-18 23:53:56.372 19601 19601 E Address : 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:272)
12-18 23:53:56.372 19601 19601 E Address : 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:96)
12-18 23:53:56.372 19601 19601 E Address : 	at android.os.AsyncTask.finish(AsyncTask.java:695)
12-18 23:53:56.372 19601 19601 E Address : 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
12-18 23:53:56.372 19601 19601 E Address : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
12-18 23:53:56.372 19601 19601 E Address : 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 23:53:56.372 19601 19601 E Address : 	at android.os.Looper.loop(Looper.java:193)
12-18 23:53:56.372 19601 19601 E Address : 	at android.app.ActivityThread.main(ActivityThread.java:6863)
12-18 23:53:56.372 19601 19601 E Address : 	at java.lang.reflect.Method.invoke(Native Method)
12-18 23:53:56.372 19601 19601 E Address : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
12-18 23:53:56.372 19601 19601 E Address : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 23:53:56.372 19601 19601 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-18 23:53:56.372 19601 19601 E AndroidRuntime: FATAL EXCEPTION: main
12-18 23:53:56.372 19601 19601 E AndroidRuntime: Process: com.fsck.k9, PID: 19601
12-18 23:53:56.372 19601 19601 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:274)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.helper.MessageHelper.toFriendly(MessageHelper.java:147)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:314)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:497)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:465)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.content.Loader.deliverResult(Loader.java:157)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:272)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:96)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
12-18 23:53:56.372 19601 19601 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 23:53:56.374 19601 19601 W OPDiagnose: getService:OPDiagnoseService NULL
12-18 23:53:56.376 19601 19727 D OSTracker: OS Event: crash
12-18 23:53:56.400 19601 19727 D AbstractTracker: Event success
12-18 23:53:56.402 19601 19601 I Process : Sending signal. PID: 19601 SIG: 9
```

**Comment by sam2kb** [comment]
I'd rather not publish message source here, but I can PM it

**Comment by dbpruett2004** [comment]
No problem with that I caught my wife and she didn't want to believe that I
knew enough that I could show her. So I wanted this to be fun you can text
me or tell me whatever you need to send it to me in a way that places you
feel comfortable 2699212004 Facebook is John Anthony and I have only two
friends

**Comment by wiktor-k** [comment]
This looks similar to #3836. Please PM me (anonymized) .eml (link to my e-mail through GitHub profile).

**Comment by sam2kb** [comment]
Personal info redacted

```
Delivered-To: <to@email.com>
Return-Path: <SRS0=mB+MC4=NJ=senderdomain.com=from@senderdomain.com>
Received: .....
X-Authority-Analysis: v=2.2......
Received: from [127.0.0.1] (port=2222 helo=NPR)
	by from.mxserver.com with esmtpa (Exim)
	id GGGGGG-DDDDDD-DU; Mon, 15 Oct 2018 12:00:54 -0400
From: =?iso-8859-1?Q?Nicol=E1s_P=E9rez_Gomez?= <from@senderdomain.com>
To: <to@email.com>
Cc: "'Person B'" <b@email.com>,
	=?iso-8859-1?Q?Nicol=E1s_P=E9rez_Gomez?= <from@senderdomain.com>
References: <11111$222222$333333$@senderdomain.com>
In-Reply-To: <11111$222222$333333$@senderdomain.com>
Subject: Message subject
Date: Mon, 15 Oct 2018 12:00:50 -0400
Message-ID: <44444$5555555$666666$@senderdomain.com>
MIME-Version: 1.0
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AAAAAAAAAAAAVVVVVVVVVVVVVVVVVV
Content-Language: en-us
X-EN-UserInfo: VVVVVVVV:KKKKKKKKKK
X-EN-AuthUser: from@senderdomain.com
Sender:  Nicolás Pérez Gomez <from@senderdomain.com>
X-EN-OrigIP: 127.0.0.1
X-EN-OrigHost: unknown
Authentication-Results: to.mxserver.com;
	dkim=pass header.d=senderdomain.com;

Message text is not important


-----Original Message-----
From: Nicol=E1s P=E9rez Gomez [mailto:from@senderdomain.com]=20
Sent: Monday, October 8, 2018 10:00 PM
To: to@email.com
Cc: 'Person B' <b@email.com>; Nicol=E1s P=E9rez Gomez
<from@senderdomain.com>
Subject: Message subject

Message text is not important


---
This email has been checked for viruses by AVG.
https://www.avg.com
```

**Comment by wiktor-k** [comment]
Thanks for the message @sam2kb! I reproduced it on 5.600 and confirmed it is [fixed and working in master](https://github.com/k9mail/k-9/commit/4e6d642ddd8121f35bb596377f88d7fd6dd5afd6).

**Comment by Uriel12** [comment]
Hmm it seems we have an error just like this.
`08-24 12:33:19.035 21825 21825 E Address : MimeException in Address.parse()
08-24 12:33:19.035 21825 21825 E Address : org.apache.james.mime4j.field.address.ParseException: Encountered "@" at line 1, column 1.
08-24 12:33:19.035 21825 21825 E Address : Was expecting one of:
08-24 12:33:19.035 21825 21825 E Address :     <EOF> 
08-24 12:33:19.035 21825 21825 E Address :     "," ...
08-24 12:33:19.035 21825 21825 E Address :     "<" ...
08-24 12:33:19.035 21825 21825 E Address :     <DOTATOM> ...
08-24 12:33:19.035 21825 21825 E Address :     "\"" ...
08-24 12:33:19.035 21825 21825 E Address :     
08-24 12:33:19.035 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.generateParseException(AddressListParser.java:966)
08-24 12:33:19.035 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_consume_token(AddressListParser.java:848)
08-24 12:33:19.035 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList0(AddressListParser.java:86)
08-24 12:33:19.035 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:38)
08-24 12:33:19.035 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.mail.Address.parse(Address.java:146)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.mail.internet.MimeMessage.getSender(MimeMessage.java:344)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.view.MessageHeader.shouldShowSender(MessageHeader.java:370)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:311)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
08-24 12:33:19.035 21825 21825 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:489)
08-24 12:33:19.035 21825 21825 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:457)
08-24 12:33:19.035 21825 21825 E Address : 	at android.content.Loader.deliverResult(Loader.java:144)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
08-24 12:33:19.035 21825 21825 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
08-24 12:33:19.035 21825 21825 E Address : 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:268)
08-24 12:33:19.035 21825 21825 E Address : 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
08-24 12:33:19.035 21825 21825 E Address : 	at android.os.AsyncTask.finish(AsyncTask.java:695)
08-24 12:33:19.035 21825 21825 E Address : 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
08-24 12:33:19.035 21825 21825 E Address : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
08-24 12:33:19.035 21825 21825 E Address : 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-24 12:33:19.035 21825 21825 E Address : 	at android.os.Looper.loop(Looper.java:164)
08-24 12:33:19.035 21825 21825 E Address : 	at android.app.ActivityThread.main(ActivityThread.java:6944)
08-24 12:33:19.035 21825 21825 E Address : 	at java.lang.reflect.Method.invoke(Native Method)
08-24 12:33:19.035 21825 21825 E Address : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-24 12:33:19.035 21825 21825 E Address : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
08-24 12:33:19.038 21825 21825 E Address : MimeException in Address.parse()
08-24 12:33:19.038 21825 21825 E Address : org.apache.james.mime4j.field.address.ParseException: Encountered "@" at line 1, column 1.
08-24 12:33:19.038 21825 21825 E Address : Was expecting one of:
08-24 12:33:19.038 21825 21825 E Address :     <EOF> 
08-24 12:33:19.038 21825 21825 E Address :     "," ...
08-24 12:33:19.038 21825 21825 E Address :     "<" ...
08-24 12:33:19.038 21825 21825 E Address :     <DOTATOM> ...
08-24 12:33:19.038 21825 21825 E Address :     "\"" ...
08-24 12:33:19.038 21825 21825 E Address :     
08-24 12:33:19.038 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.generateParseException(AddressListParser.java:966)
08-24 12:33:19.038 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_consume_token(AddressListParser.java:848)
08-24 12:33:19.038 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList0(AddressListParser.java:86)
08-24 12:33:19.038 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:38)
08-24 12:33:19.038 21825 21825 E Address : 	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.mail.Address.parse(Address.java:146)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.mail.internet.MimeMessage.getSender(MimeMessage.java:344)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:314)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
08-24 12:33:19.038 21825 21825 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:489)
08-24 12:33:19.038 21825 21825 E Address : 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:457)
08-24 12:33:19.038 21825 21825 E Address : 	at android.content.Loader.deliverResult(Loader.java:144)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
08-24 12:33:19.038 21825 21825 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
08-24 12:33:19.038 21825 21825 E Address : 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:268)
08-24 12:33:19.038 21825 21825 E Address : 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
08-24 12:33:19.038 21825 21825 E Address : 	at android.os.AsyncTask.finish(AsyncTask.java:695)
08-24 12:33:19.038 21825 21825 E Address : 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
08-24 12:33:19.038 21825 21825 E Address : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
08-24 12:33:19.038 21825 21825 E Address : 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-24 12:33:19.038 21825 21825 E Address : 	at android.os.Looper.loop(Looper.java:164)
08-24 12:33:19.038 21825 21825 E Address : 	at android.app.ActivityThread.main(ActivityThread.java:6944)
08-24 12:33:19.038 21825 21825 E Address : 	at java.lang.reflect.Method.invoke(Native Method)
08-24 12:33:19.038 21825 21825 E Address : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-24 12:33:19.038 21825 21825 E Address : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
08-24 12:33:19.039 21825 21825 D AndroidRuntime: Shutting down VM
--------- beginning of crash
08-24 12:33:19.042 21825 21825 E AndroidRuntime: FATAL EXCEPTION: main
08-24 12:33:19.042 21825 21825 E AndroidRuntime: Process: com.fsck.k9, PID: 21825
08-24 12:33:19.042 21825 21825 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:269)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.helper.MessageHelper.toFriendly(MessageHelper.java:147)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:314)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:210)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:256)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:57)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:753)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:218)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:73)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:274)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:253)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:489)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:457)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.content.Loader.deliverResult(Loader.java:144)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:45)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:15)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:268)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-24 12:33:19.042 21825 21825 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`
The relevant part of the e-mail is this
`Sender: @XXXX.XX`
It is an malformed header by the sender, but it should not crash the mail-client.
@wiktor-k do you know when k9-mail will release a new version.
