### ISSUE TITLE
Add feature to deselect all selected mail

### ISSUE THREAD

**Issue by suyeon-9706** [k9mail/k-9#3837]
### Expected behavior
Add features to deselect all selected mail in the inbox (add to the action bar)

### Actual behavior
The current feature is only 'select all'

### Steps to reproduce
1. Move the inbox
2. Select some mails

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by cketti** [comment]
You can leave selection mode by pressing the check mark button in the upper left corner.
