### ISSUE TITLE
Unicode character in headers causes crash

### ISSUE THREAD

**Issue by FIjaakko** [k9mail/k-9#3843]
Having unicode U+2013: EN DASH (UTF-8 e2 80 93) in headers (Sender:) causes crash. Having that character in From: header causes from to show as "null" in the UI message list. Seems to work without problems if headers are properly encoded.

### Expected behavior
Show the dash or don't show just that character.

### Actual behavior
Crash.

### Steps to reproduce
1. Use the attached testemail.txt and try opening the message with K-9
[testemail.txt](https://github.com/k9mail/k-9/files/2705619/testemail.txt)
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 8

**Comment by cketti** [comment]
See #3836
