### ISSUE TITLE
Better Unread-Mark

### ISSUE THREAD

**Issue by ricokritzer** [k9mail/k-9#3844]
Unread mails are not clearly marked.

### Expected behavior
Maybe instead of gray color there can be a setting for the background color.

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. getting an email

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): every

**Comment by rspencer01** [comment]
I think background colours in general are unclear.

The concept in #1859 was to embolden the subject and sender for unread emails.  This is subtle but clear and quite popular in many other email clients.  I implemented this in #4038, which I am busy pulling apart into different pull requests, one of which will submit the background colour -> bold idea for review.

**Comment by cketti** [comment]
Subject and sender name of unread messages are displayed in bold. See #4189.
Optionally the background can be changed to grey.

I don't want to add a setting to make the background color configurable.
