### ISSUE TITLE
About screen font is huge

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#3852]
Since the recent update of the about screen, the font is huge. The text barely fits my screen and is nearly twice as big when comparing to a normal settings screen. (Additionally, there is no right margin on some items. Therefore, the text sticks to the edge of the screen)

<img width="250" src="https://user-images.githubusercontent.com/5811634/50493354-46394b00-0a1d-11e9-9980-2ce70d6b5775.png" /> <img width="250" src="https://user-images.githubusercontent.com/5811634/50493353-46394b00-0a1d-11e9-8a74-07c7667cb081.png" />

Device: OnePlus 3T, LineageOS 17.1
K9mail version: master
Ping @williamvds

**Comment by williamvds** [comment]
Whoops, my bad. I didn't notice how bad it would be with a normal screen density  
I'll send a PR to correct this
