### ISSUE TITLE
Setup could not finish

### ISSUE THREAD

**Issue by reficulgr** [k9mail/k-9#3856]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Should be able to setup my mail account.

### Actual behavior
I get a "Setup could not finish - cannot connect to server. (unable to connect)" message.

### Steps to reproduce
1. Enter my server credentials
2. Press next
3. error message

I'm using the same credentials that I use in other clients, that work without issues.

### Environment
K-9 Mail version: 5.600

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by wiktor-k** [comment]
Please add exact server settings that you used here, IMAP server, SMTP server etc.

**Comment by wiktor-k** [comment]
If the server data is confidential maybe you can share it with me privately (contact through Github profile). If not there is nothing we can do to check what's the cause of the problem.
