### ISSUE TITLE
adding provider to  app/core/src/main/res/xml/providers.xml

### ISSUE THREAD

**Issue by computersalat** [k9mail/k-9#3871]
How can I get my mailserver settings to the providers.xml ?
Can I just fork and update ?
Or is there a similar way like Mozilla Thunderbird offers and K-9 is able to use ?

**Comment by wiktor-k** [comment]
For the record there is a ticket that tracks Thunderbird-like autoconfig in K-9: #865.

**Comment by computersalat** [comment]
@wiktor-k 
Thanks for info.
The #865 I also found and it is a real pity that there is no change in 3 years.

For enabling my Provider settings, like mentioned in #3480, I should open an issue, that my settings are missing and I am able to reference this issue in the PullRequest?

**Comment by wiktor-k** [comment]
> The #865 I also found and it is a real pity that there is no change in 3 years.

I agree and I (for development purposes) frequently setup my account and have to walk through the wizard sometimes multiple times a day. But it's all open-source - so until someone steps up and implements it properly it's not there :)

> For enabling my Provider settings, like mentioned in #3480, I should open an issue, that my settings are missing and I am able to reference this issue in the PullRequest?

I don't know if a PR modifying `providers.xml` will ever be accepted. Maybe you can ask on [#k-9](http://webchat.freenode.net/?channels=%23k-9).

I think it would be better if you setup autoconfig on your domain and when K-9 gets this feature you'll be automatically supported ([an example from my site](https://metacode.biz/.well-known/autoconfig/mail/config-v1.1.xml)).

**Comment by computersalat** [comment]
@wiktor-k 
my examples:
- [for mx.wittmer.email](http://mx.wittmer.email/mail/config-v1.1.xml)
- [for c00.wittmer.mx](http://c00.wittmer.mx/mail/config-v1.1.xml)

**Comment by wiktor-k** [comment]
:+1: just add HTTPS as that seems to be required (e.g. using Let's Encrypt) and subscribe to #865 so you'll see when K-9 will support this.

**Comment by computersalat** [comment]
@wiktor-k 
it works with both (while using Let's Encrypt Certificates)

**Comment by wiktor-k** [comment]
Oh, sorry! Then you're good to go, for e-mails `anything@mx.wittmer.email` and `anything@c00.wittmer.mx` where `anything` is... anything.

**Comment by computersalat** [comment]
sorry, but it doesn't work with K-9 yet ... or I got you wrong.
anything@domain.com (hosted on MX: c00.wittmer.mx) will be
- imap.domain.com
- smtp.domain.com

instead of

- imap.wittmer.mx
- smtp.wittmer.mx

**Comment by wiktor-k** [comment]
@computersalat if you can build the app from the source you can try out #3879 and see if it works on your domains.

**Comment by computersalat** [comment]
@wiktor-k 
Thank you for your effort but I have no idea on how to build an Android App from Source ...
If you would provide an `PreRelease` or `Release Candidate` here for install I would try to install and test.
Thank you
