### ISSUE TITLE
copying one full line of plain text is impossible, first markers resets itself

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3875]
it's impossible for me to actually copy a full line of text from this mail
https://youtu.be/I92n5Fvd6Uk

it always sets the marker to the beginning of the mail once I move the second marker :/

**Comment by Djfe** [comment]
it's possible to mark the last word of the line and move the first marker to the line start. but that's not intuitive

who from the western world would mark text from right to left :/

**Comment by cketti** [comment]
This is probably a bug in the WebView component used by your device. In K-9 Mail we don't knowingly alter the text selection behavior of that component.

**Comment by cketti** [comment]
If you have the Chrome app installed its WebView implementation should be used by the system.

How to report a bug: https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DAndroid&oco=1
