### ISSUE TITLE
No notifications or notifications disappear with two accounts

### ISSUE THREAD

**Issue by rmamail** [k9mail/k-9#3890]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When you receive mail at the same time to two accounts, you should get a notification icon to the notification bar and a sound should be played. This should happen if the screen is on or locked. If the screen is open, yopu should get thge notification sound and the notification icons, the icon shoud stay until you open a mailbox.

### Actual behavior
When phone screen is locked, and mail is received to two accounts at the same time, a notification should appear. Now there is no notification icon in the notification bar, and no sound is played. The mails are received in the both mailboxes. If you open incoming messages, there is new mail, but you don't know it's there, if you don't open the mailbox. 
If the screen is on when mail is received at the same time to both accounts, the notifications work, but after a few second the notification icons disappear. This is wrong.
If you get mail to the accounts at the same auto sync in sepatate times, the notifications works as they should.

### Steps to reproduce
1. Use two email accounts in K9, send (empty)mail from account  a to b and from account b to a, close K9 and lock the screen. Wait for auto sync.
2. Screen is locked, and sync is "when automatic sync is on". Mail is synced when auto sync turns on, but no notification sound, unlock the screen, and there is no notification icons
3. Open the mailboxes, there is new unreaded mail
4. Send a (empty)mail from account a to account b, and wait for the autosync as before screen locked etc, everything works, there is a notification sound and also a notification icon. Same when sending mail from b to a.
4.  Do as in step 1, If you have screen on  when the sync happens, you get the notification sound and the notification icons, but the notifications disappears after few seconds. This is wrong.
5. Open the mailboxes, there is new unreaded mail.
### Environment
K-9 Mail version: 5.403 & 5.600
Samsung Galaxy S9

Android version: Android 8 & 9

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here

**Comment by tualatin** [comment]
Here the same, since I upgraded to LineageOS 15.1 the notification icon is visible for 1 seconds, than it disappear. No notification sound, no notification LED. Current version 5.600.

**Environment**

OnePlus 3
Android version 8.1 (LineageOS 15.1, Rooted)
Account type IMAP

**Comment by covex** [comment]
#3205
