### ISSUE TITLE
Still actively developed?

### ISSUE THREAD

**Issue by BerndErnst** [k9mail/k-9#3894]
I want to trust k-9. But as an outsider the status of K-9 looks abandoned.

1. The Build status [link](https://k9mail.ci.cloudbees.com/job/development%20(master)/) in the Readme.MD says >>This DEV@cloud account is currently unavailable<<

2. 36 unprocessed pull requests. Is anyone doing these?

3. Last release is 4 month ago. >>cketti released this on Sep 2, 2018<< 

4. 855 open Issues

5. Last Blog post was posted on February 26, 2018

Can we get an official statement about the current situation somewhere?

**Comment by BerndErnst** [comment]
@cketti

**Comment by cketti** [comment]
We're all working on K-9 Mail on the side. Things happen when we have the time and feel like it.

I didn't realize the last commit in the repository being 6 days old would cause a panic. I don't feel like making any public commitments about the future of any of my open source projects. But I can say that as of 2019-01-31 K-9 Mail development hasn't been abandoned.

Side note: I've been working on K-9 Mail since late 2009. Chances are I'll stick with it for a little bit longer.

**Comment by justinacolmena** [comment]
On January 31, 2019 6:12:23 AM AKST, Ernst Wettstaedt <notifications@github.com> wrote:
>I want to trust k-9. But as an outsider the status of K-9 looks
>abandoned.
>
>1. The Build status
>[link](https://k9mail.ci.cloudbees.com/job/development%20(master)/) in
>the Readme.MD says >>This DEV@cloud account is currently unavailable<<
>
>2. 36 unprocessed pull requests. Is anyone doing these?
>
>3. Last release is 4 month ago. >>cketti released this on Sep 2, 2018<<
>
>
>4. 855 open Issues
>
>5. Last Blog post was posted on February 26, 2018
>
>Can we get an official statement about the current situation somewhere?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/3894

I am also an outsider, looking at the same information you are. I have a few of my own projects, but I am not an expert at git or GitHub.

It looks to me like a major refactor of the code is in progress. Four months for the latest stable release is not at all unusual for an open source project. People work on open source "stuff" in their "spare" time, polish their résumés, whatnot.

A full featured mail client that runs on a device with limited resources is a major undertaking. Commercial spammers, aggressive organized identity thieves, and proprietary competitors create an extremely hostile work environment for anything open source, and particularly email- or crypto-related.

Don't be such an ass. I catch major flak and shrapnel for my work, as well. Guns are banned, and there's too much hostile corporate crime cartel military brass running around with an armed private security detail, just generally riding roughshod over free and open source software projects.
-- 
Una Milicia bien regulada, estando necesaria a la seguridad de un Estado libre, el derecho del pueblo de tener y de portar Armas, no será infringido.

https://www.colmena.biz/~justina/
