### ISSUE TITLE
slow down 'has just been toggled' animation, to prevent unnotice accidental toggles

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3898]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
It should be visually obvious that a menu item has just been toggled. An animation should play long enough to notice any accidental click.

### Actual behavior
Whenever you press a toggleable setting, the background of the menu option lights up for a split second indicating it has been toggled. This is way to short. If you are scrolling though the preferences, you may accidentally toggle one of the options, and the animation may very well go unnoticed. This 'afterglow' effect should be very obvious and last around two full seconds or so. Such a longer animation will catch the eye, and clearly indicate a toggle event has just taken place.

It might be possible to come up with other messures to prevent accidental toggles, such as requiring long presses, or requiring side swipes rather than short clicks.

### Steps to reproduce
1. Open some preference menu which contains toggle options
2. Scroll up or down though the options.
3. Click some toggle button and imagine doing that on accident while scrolling. Would you notice that you accidentally toggled this option?

### Environment
K-9 Mail version:
5.600

Android version:
8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Not relevant at all

**Comment by cketti** [comment]
The next stable version will use the material design animations to highlight pressed items. They are more noticeable than what we currently have. But we're not going to implement custom animations.
