### ISSUE TITLE
Synch server deletions & Gmail not playing well together

### ISSUE THREAD

**Issue by dpomerance** [k9mail/k-9#3902]
### Expected behavior
The inbox item should remain in the K9 email inbox until it is either deleted in K9 or deleted on the Gmail server with synch server deletions selected

I run K9 using POP with 3 different email accounts, a company exchange server, Bellsouth and Gmail. When I have synch server deletions checked, to remove inbox items when they are removed from the server, it works perfectly with Bellsouth and the Exchange Server. But for some reason the Gmail account will allow it to go to the inbox, but on the next polling, whether it is deleted on the server or not, the item disappears from the inbox. It will only remain in the inbox for one polling cycle. 

1. Set up a Gmail account with synch server deletions checked
2. Send an email to the Gmail account
3. Force a polling and receive the email in your K9 inbox
4. Force another polling and watch the email disappear from the K9 inbox while it remains in the Gmail inbox on your computer

### Environment
K-9 Mail version: 5.600

Android version: 7.0

Account type POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by Krammig** [comment]
I am seeing this same behavior for both POP and indeed IMAP.

I have set up a couple of IMAP accounts on Hotmail and carefully stepped through testing of deleting messages on the Server end and deleting messages in K9. 
In doing so I have also made sure that all settings in Hotmail (sync settings) and in K9 have been correctly set. 

Deleting a message on the server Does delete it in K9

However deleting a message in K9 - Does Not - delete the message on the Server for IMAP nor for POP

**Comment by cketti** [comment]
See https://support.google.com/a/answer/6089246?hl=en

**Comment by dpomerance** [comment]
You haven't answered the question. Why does a popped email which is safely ensconced in the inbox on my phone, disappear the next time the phone polls for new email even when the original email still sits in the Gmail inbox on the Gmail server?
