### ISSUE TITLE
Sign email

### ISSUE THREAD

**Issue by silas229** [k9mail/k-9#3906]
### Expected behavior
An option to only sign the email

### Actual behavior
I can't find this option described in https://k9mail.github.io/documentation/security/pgpmime_current.html
![](https://cloud.silas229.de/index.php/s/HTLrzA5QHXTiYTT/preview)

### Steps to reproduce
1. Install OpenKeychain and import key
2. Install K-9 Mail
3. Log in to email account
4. Connect K-9 Mail with OpenKeychain

### Environment
K-9 Mail version: 5.600

Android version: 8

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by mdallastella** [comment]
I can't find the instructions too. 

 Despite what the author thinks about signing emails, I think it's useful and I'd like to be able to sign them.

Thanks.

**Comment by cketti** [comment]
It's "Enable PGP Sign-Only" in the overflow menu.

**Comment by mdallastella** [comment]
@cketti I really don't know how I missed it, thanks!
