### ISSUE TITLE
PNG attachments are blurry

### ISSUE THREAD

**Issue by margin-auto** [k9mail/k-9#3911]
### Expected behavior
I receive a mail with a screenshot in PNG format attached. I download the whole message and the attachment. Now i expect that I canread the screenshot and zoom into the picture.

### Actual behavior
The attachment is displayed very blurry and pixel'ish. It's completely unreadable.

### Steps to reproduce
1. Send the attached file "Screenshot (6).png" to a mail address and open the file in K9
2. Zoom in.
3. You'll get a result like in the attached file Screenshot_2019-02-10-13-12-46.png

### Environment
K-9 Mail version: 5.600

Android version: 5.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![screenshot_2019-02-10-13-12-46](https://user-images.githubusercontent.com/17515478/52533593-53dd3280-2d36-11e9-94df-fa46e8decb04.png)
![screenshot 6](https://user-images.githubusercontent.com/17515478/52533595-56d82300-2d36-11e9-9e52-869d479e79d0.png)

**Comment by cketti** [comment]
Neither does K-9 Mail compress images when sending, nor does it modify received attachments. It is very unlikely for this to be an issue caused by K-9 Mail.

Try saving the attachment using a different email client to check whether the image is modified before sending. Try using another image viewer to check whether it's an issue with your current image viewer app.

**Comment by margin-auto** [comment]
The problem is not on sending the images with K9, but only on receiving. When I open the mail on my desktop mail client, everything is fine. The same for saving the image (first) on the phone with K9 and open it afterwards (second). Only when I open the image directly in K9 its blurry. It seems that K9 just opens a rescaled small preview of the image which probably works for photos but not for screenshots with small fonts. K9 does use the same image viewer of my Android system (does it?) as I use for displaying the previously  downloaded image (which works fine, see above) so I dont think, thats an issue of the image viewer. Does K9 do any scaling of smaller previews on attached images?
