### ISSUE TITLE
Application crash when opening message with emoji as first char of object field

### ISSUE THREAD

**Issue by ziouf** [k9mail/k-9#3916]
### Expected behavior
In inbox screen, when I select a message with an emoji as first character of object field, message should be displayed as usual. 

### Actual behavior
In inbox screen, when I select a message with an emoji as first character of object field, application crashes. 

### Steps to reproduce
1. Receve a message with an emoji as first character of object field
2. Try to open it from inbox screen

### Environment
K-9 Mail version: 5.600

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by wiktor-k** [comment]
What's the "object field"? I just sent myself a message with subject "🙆🏼" and content "🙆🏼" and it didn't crash (neither 5.600 or `master` version).

Would it be possible if you forwarded the crashing e-mail to me or attached it here (if it's not confidential)?

**Comment by ziouf** [comment]
Sorry, I mean subject field. 
Maybe my diagnostic is wrong. But the issue remains.

You can find attached here the concerned mail.

[crashing_mail.zip](https://github.com/k9mail/k-9/files/2861001/crashing_mail.zip)

**Comment by wiktor-k** [comment]
Hi, I've checked your e-mail, it does indeed crash 5.600 but it does *not* crash master, that means it's already fixed and will be included in the next release.

You can check out details in a similar bug report (stacktrace is identical) here: #3834.
