### ISSUE TITLE
Never checks for new mail

### ISSUE THREAD

**Issue by Melab** [k9mail/k-9#3918]
I've been using K-9 Mail for five years, on both Android 4.4 and 9.0. I've never gotten it to automatically check for new mail in the background like every other e-mail client does. I've looked through all ofthe settings and none of the settings I've adjusted fix this. The only time it actually checks for mail is when I have it open and click the sync button. Why isn't it checking for e-mail on its own?

**Comment by philipwhiuk** [comment]
Please follow the issue template.

**Comment by cketti** [comment]
Duplicate of #3950
