### ISSUE TITLE
Feature request: Ability to lock the app with a password

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#3920]
My phone was stolen recently. Although I changed my imap password immediately, if the thief gains access to my phone he may read anything still stored in cache. That could actually be quite a lot, including logins to admin sections of on-line platforms. Of course I am raising alarm everywhere, and changing all my passwords, but I realize most other sensitive apps these days have their own login, either manditoriy, or optional. I would like k9 to have the OPTION to lock the app itself. To some users email is too sensitive to rely just on the phone lockscreen.

**Comment by yoshimo** [comment]
That is why you should encrypt the phones storage.

**Comment by ByteHamster** [comment]
Locking the email app does not help. The thief can just plug your phone into his computer and remove the per-app lockscreen. The only thing that actually helps is a good lockscreen password for the whole device (because this prevents anyone from using a PC to read the database manually).

**Comment by philipwhiuk** [comment]
#753
