### ISSUE TITLE
Feature Requests - Message List Widget include Account Color

### ISSUE THREAD

**Issue by lifesize-dan** [k9mail/k-9#3922]
### Expected behavior
Message List Widget would follow Unified View in the app itself, displaying colored bars next to messages to indicate which account they belong to

### Actual behavior
Message List Widget shows Unified View without any colored bars.

### Steps to reproduce
1. Add widget, look at it.

### Environment
K-9 Mail version: 5.600

Android version: 9 on Pixel 3

Account type (IMAP, POP3, WebDAV/Exchange): one IMAP, one POP at the moment

**Comment by cketti** [comment]
This has been implemented in K-9 Mail 5.7xx.
