### ISSUE TITLE
Fetching IMAP mails extremely slow 

### ISSUE THREAD

**Issue by akahl** [k9mail/k-9#3927]
Since yesterday morning (19/2/25), fetching mails from IMAP.gmx.net with TLS is extremely slow. The same pull on Thunderbird works in less than a second (I tried on the same WiFi). 

### Expected behavior
It should be faster (not 1-2 mins)

### Actual behavior
Fetching Mails takes more than a minute - even if there is no new message.

### Steps to reproduce
Fetch mails via IMAP (I used GMX)

### Environment
K-9 Mail version: 5.6 (newest on Android 7)

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is not an actionable bug report. To be able to figure out what's going on a debug log would be helpful. But even then it would probably involve a lot of guessing. Please try using the [mailing list](http://groups.google.com/group/k-9-mail) to ask for help.
