### ISSUE TITLE
Feature Request: Persistent notifications for any unread emails

### ISSUE THREAD

**Issue by danhoffman699** [k9mail/k-9#3931]
I would like for K-9 mail to have a persistent notification whenever there is unread mail in an inbox (only use the account for notifications). Is this something that would be seen as useful by other people? Thanks

**Comment by cketti** [comment]
I don't want to include such functionality in K-9 Mail. However, you should be able to create a separate app for this. K-9 Mail's `MessageProvider` can be queried to retrieve the unread message count.
