### ISSUE TITLE
SSL socket over socket [unconnected]  after that I got Exception like this:java.lang.IllegalArgumentException: cipherSuite TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is not supported. I got this error when I back from chat module which was included in my App

### ISSUE THREAD

**Issue by Rekha-Lanka** [k9mail/k-9#3934]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
I don't know why you're reporting this to the K-9 Mail issue tracker.

**Comment by Rekha-Lanka** [comment]
Because I am getting this error in k9mail

**Comment by cketti** [comment]
Maybe you should have bothered filling out the issue template. It's not clear to me how K-9 Mail relates to "chat module which was included in my App".
