### ISSUE TITLE
K-9 Mail Does NOT Receive PUSH Notifications with Norton App Lock Keep App Locked In Session Box Checked

### ISSUE THREAD

**Issue by C-Cur** [k9mail/k-9#3945]
### Expected behavior
I would expect K-9 Mail app to received PUSH Notifications of new emails in Inbox Folder even if Norton App Lock is used with the option to "Keep App Locked In Session" box checked.

### Actual behavior
If the "Keep App Locked In Session" checkbox is checked, PUSH Notifications only arrive when you unlock the K-9 App to use it. This is not very useful. If you leave the box unchecked. K-9 functions normally. I do not know if this is a bug or by design.

I also wish to warn users of these two programs together that the default for K-9 is to autoexpand the Inbox folder. If this remains set, when K-9 is locked by Norton App Lock you can shrink down the locked window with the left soft button on your Android phone and you will see part of the Inbox folder. As a work around, I do not autoexpand the Inbox folder and that means that when you start K-9 you just see folders, not emails. So if K-9 is locked by Norton App Lock, and you shrink the window with the left soft button to see which apps are active all you see are folders, not emails.

### Steps to reproduce
Install K-9 Mail
Install Norton App Lock
Set Norton App Lock to keep K-9 Mail Locked and check the box for "Keep App Locked In Session"
Close K-9 Mail
Send yourself an email from another device.
Then wait for a PUSH Notification.
None comes.
Unlock K-9 Mail and use other device to send email again.
PUSH notification shows up as it normally would.

Next at Norton App Lock screen overlaying K-9 Mail uncheck "Keep App Locked In Session"
Let phone screen time out.
Send yourself an email from another device.
Then wait for a PUSH Notification.
PUSH notification shows up as it normally would.
Open K-9 Mail by unlocking.

### Environment
K-9 Mail version: 5.600

Android version: 6.0.1

Norton App Lock Version: 1.4.0.449

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Not Applicable

**Comment by cketti** [comment]
Feel free to report this as a bug to the creators of "Norton App Lock".
