### ISSUE TITLE
Time when K9Mail/Openkeychain ask for passphrase

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#3946]
I am using K9mail 5.600 and OpenKeychain 52009. How can I change what triggers the request for the passphrase?
When an encrypted mail is received, the passphrase is needed. This passphrase can be given at different times, for example after the phone was locked. How can the time when retyping is necessary be changed?

**Comment by cketti** [comment]
This is an OpenKeychain question/issue.
