### ISSUE TITLE
How to create new folders ?

### ISSUE THREAD

**Issue by raviteja74** [k9mail/k-9#3948]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
A user should be able create, delete and rename  folders

### Actual behavior
It only shows webclient folders to manage but not create folders in app

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
Latest Version.
Android version:
28
Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
K-9 Mail currently doesn't support any of these operations.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
