### ISSUE TITLE
Will not run on ChromeOS dev build

### ISSUE THREAD

**Issue by rsgosnell** [k9mail/k-9#3962]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
App should run

### Actual behavior
Tell us what happens instead
Will not run, just disappears.  After multiple tries, a dialog with choices pops up, saying it keeps crashing.  Selecting "send feedback" gives an icon on the taskbar, which will not close, nor will it open.  Cannot send feedback.

### Steps to reproduce
1. Update chromebook to Version 74.0.3726.0 (Official Build) dev (64-bit).
2. Try to run K9
3.

### Environment
K-9 Mail version:
Not certain, since it won't run, but the latest version in the Play Store
Android version: ChromeOS Version 74.0.3726.0 (Official Build) dev (64-bit)

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Unable, since it won't run at all

This is probably a ChromeOS issue, since I'm having problems with other Android and Linux apps, but the developers should be made aware of it.  K9 runs as expected on my Pixel with latest Android updates.

**Comment by cketti** [comment]
I switched my ChromeOS device to 74.0.3726.0 and K-9 Mail installs and works fine for me.
I'm afraid without a debug log there's not much we can do.
