### ISSUE TITLE
Since version 5.6, in some emails From appears with 'null' as text

### ISSUE THREAD

**Issue by JavierDiaz** [k9mail/k-9#3964]
I'm sorry to open this issue, but previous #3617 was closed and I am unable to reopen it again. I commented in it but no response I have received. It continues failing as commented in the previous incident. @cketti said he believes it was corrected in master but I think 5.6 is the last version available.

Here is the problem:

### Expected behavior
Until version 5.6, From field of emails was viewed correctly

### Actual behavior
Now, in some cases, instead appearing the value of From field, it appears as 'null'. If you choose to show all headers, From field exists and is viewed correctly. It seems there is some issue with emails with some encoding error.

It is desired instead 'null', appears the actual From header.

### Steps to reproduce
1. Open an email with a From header with some problematic character, for example:
From: FÁTIMA  <xxx@xx.es>
(in plain text, with no iso/utf-8 encoding information)
### Environment
K-9 Mail version: 5.600

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
It'll be fixed in the next stable version 5.800. Since we use this issue tracker to organize development work, not as support tool, we close issues once the bug is fixed. Even when that fix is not yet available to users.

**Comment by JavierDiaz** [comment]
ok, many thanks!!
