### ISSUE TITLE
App was built for an older version of Android and may not work properly

### ISSUE THREAD

**Issue by candrews** [k9mail/k-9#3967]
Android Q warns users when running apps targeting Lollipop or older: https://www.techworm.net/2018/09/android-q-apps-older-version.html

### Expected behavior
Tell us what should happen:
This dialog should not appear.

### Actual behavior
Tell us what happens instead
This dialog appears when K-9 Mail is opened:
![Screenshot_20190314-081723](https://user-images.githubusercontent.com/194713/54367132-40302f00-4648-11e9-9ce1-cdbeea6d5bf2.png)

### Steps to reproduce
1. Using Android Q beta 1, open K-9 Mail

### Environment
K-9 Mail version:
5.600

Android version:
Q beta 1

Account type (IMAP, POP3, WebDAV/Exchange):
n/a

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
n/a

**Comment by cketti** [comment]
This won't be an issue with the next stable version 5.800. The app built from `master` already works fine.

**Comment by candrews** [comment]
> This won't be an issue with the next stable version 5.800. The app built from `master` already works fine.

When can we expect that release?

Thanks!

**Comment by cketti** [comment]
I foolishly assumed you wouldn't ask because you knew the answer was going to be "when it's done".

**Comment by VictorSago** [comment]
Still an issue on regular Android 10 and K-9 Mail version 5.717

**Comment by dubidubno** [comment]
Any updates on this?
