### ISSUE TITLE
Better highlighting unread messages

### ISSUE THREAD

**Issue by sandoxy** [k9mail/k-9#3973]
It woul be great, if the unread messages would be easier to recognize. Here is an example:

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.RC_P3OTfszEfZhSC4zsJeAHaDt%26pid%3D15.1&f=1

E.g. the sender name of unread messaged could be in bigger letters.

Thanks.

**Comment by cketti** [comment]
You can already change the font size of the subject and/or sender under 'Global settings > Display > Font size'
