### ISSUE TITLE
 Time delimiters like inbox? 

### ISSUE THREAD

**Issue by Patrik356b** [k9mail/k-9#3978]
So as Inbox by Google is shutting down and the Gmail app remains garbage, I'm looking for solutions to manage a cluttered account. 

My question is; how can I set up delimiters in k9? 

The advantage of inbox was that it both bundled "promotions" and other things while also putting the bundles under the correct delimiters. 

I.E. Today, Yesterday, This Month... 

That's all I need.

**Comment by cketti** [comment]
In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

The functionality in question isn't supported yet. We're tracking the feature request as #3987.

**Comment by Patrik356b** [comment]
Alright. I have never used mailing lists, so I don't know :p

Posting here was my only reasonable option as I didn't find anything when
searching and nobody I asked knew anything about it.
