### ISSUE TITLE
Add option to copy link text in message view

### ISSUE THREAD

**Issue by schlosser83** [k9mail/k-9#3981]
### Expected behavior
Tell us what should happen
Selection of email message text should allow to copy paste the text - not only the html link
### Actual behavior
Tell us what happens instead
Only the refetence / link can be copied.

### Steps to reproduce
1. e.g. xing html message in android selection always takes the link - never the text.

### Environment
K-9 Mail version: 5.600

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Clarification: When long-pressing a link in the message the popup only allows to copy the link URL, not the link text to the clipboard.

As a workaround you can select surrounding text via long-press and adjust the selection markers to only include the link text.

**Comment by schlosser83** [comment]
Thanks for the answer. The workarround is in principle working.
But xing for example has only 0.1% real text.
That makes it very difficult to reach the section from where I can select text.
Is it possible to integreate the text selection into the dialog ?(where I would select the link actions too)
Best regards 
Cs

**Comment by schlosser83** [comment]
..and btw : it is regardless how long I press.
Any press on the linked text opens the link-dialog.(lg k10(2017))

**Comment by StefanBertels** [comment]
I miss this feature, too. Here's one (of many) use cases:

Often shops send an notification mail containing a tracking number. This tracking number often is not in the text body but the link text of a link going to some tracking website. I often just want to copy the tracking number to be able to use it in the tracking app installed on my smartphone.

As far as I know one can use the "share" feature on Android to copy something to clipboard. Maybe we just need an option to "share" the link text. This way we could pass it to clipboard (as requested here) and have more options like directly sending it to other apps.
