### ISSUE TITLE
Folder Class Settings

### ISSUE THREAD

**Issue by gene-git** [k9mail/k-9#3983]
Enhance Request:  Can there be a 'Folder Class Settings' button.

Currently if Folder Display is set to anything but 'All' - then in order to change folder class one has to first set display to all, then go back to folders - make class changes to previously not displayed folder - then go back to folder display settings.

For convenience it would be nice to have a one-button Folder Class Edit button which shows all folders, displayed or not.

thanks!!

### Environment
K-9 Mail version: 5.6.0

Android version: Pie / 9

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
See #2669
