### ISSUE TITLE
Add option to disable floating scroll

### ISSUE THREAD

**Issue by skironDotNet** [k9mail/k-9#3984]
Since most people would use 100msg limit floating scroll feels like not needed but i think it would be good idea to let the users configure if they want it or not

To me it's super annoying, I move up/down by swiping and every time I'm close to the message i want i don't want to hide it so i keep my thumb close to the screen edge (subconscious behavior) and every damn time boom suddenly I'm in totally different spot lost my message, wtf? Ah this damn hidden scroll bar!

Please please please, add an option to disable the scroll bar, or at least move it to the left

Thanks

**Comment by cketti** [comment]
See #894
