### ISSUE TITLE
BootReceiver and sync

### ISSUE THREAD

**Issue by abidal3** [k9mail/k-9#3988]
When BoorReceiver is disabled then synchronization doesn't work.
Maybe you will split BootReceiver into single receivers or unbind sync scheduling from this receiver?

**Comment by cketti** [comment]
`BootReceiver` will only be disabled if there's no account available and hence nothing to sync.
Why do you think this is an issue?

**Comment by abidal3** [comment]
> `BootReceiver` will only be disabled if there's no account available and hence nothing to sync.

Not only. This can be done manually.
This receiver includes many system receivers which aren't required for normal job of K-9.
If turn off this receiver manually then everything works except syncronization.

**Comment by cketti** [comment]
Of course things will break when you disable random components of the app. If you have a concrete suggestion on how to improve the current code please create a pull request.

**Comment by abidal3** [comment]
> If you have a concrete suggestion

Yes, of course.

> Maybe you will split BootReceiver into single receivers or unbind sync scheduling from this receiver?

Why merge a number of system receivers in one?

**Comment by abidal3** [comment]
> when you disable random components of the app

No, they're not random.
It's just about only BootReceiver and BOOT_COMPLETED.
