### ISSUE TITLE
Cannot copy-paste from k9-mail to Jackpal terminal application

### ISSUE THREAD

**Issue by AlainKnaff** [k9mail/k-9#3994]
It is currently not possible to copy-paste text from k9-mail to Jackpal terminal application. It is possible to do so indirectly by first pasting from k9-mail to firefox, then reselecting the just pasted text in firefox, and then paste it into terminal.

### Expected behavior
After having selected text in k9-mail, the "Paste" entry in Jackpal's "Edit" menu should be active. Using it should paste the selected text.

### Actual behavior
The "Paste" entry in Jackpal's copy-paste menu is greyed-out, and cannot be used.

### Steps to reproduce
1. Long press in an email
2. Drag the blue handles to chose some text
3. Click "copy" at top of screen to confirm selection
4. Switch to Jackpal terminal application
5. Long press on a terminal window
6. The "Edit" menu pops up... but the Paste entry is greyed out.

### Environment
K-9 Mail version: 5.6000

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP and POP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
I/StorageEditor( 6084): Committing preference changes
I/StorageEditor( 6084): Preferences commit took 38 ms
E/InputMethodManager( 6084): countrycode= DE
I/MessagingController( 6084): Running command 'getFolderUnread:lll:INBOX', seq = 22 (foreground priority)
I/MessagingController( 6084):  Command 'getFolderUnread:lll:INBOX' completed
E/InputMethodManager( 6084): countrycode= DE
E/InputMethodManager( 6084): countrycode= DE
D/MessageViewFragment( 6084): MessageView displaying message MessageReference{accountUuid='b6d750b9-ceb3-4ba0-a8ea-458e7beac89b', folderName='INBOX', uid='162797', flag=null}
D/MessageLoaderHelper( 6084): Creating new local message loader
D/MessageLoaderHelper( 6084): Creating new decode message loader
D/Utility ( 6084): No external images.
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView] onEvent
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView] Timeout reset to 200
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView]     scheduling callback
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView] onEvent
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView] Timeout extended 300
D/Throttle( 6084): Throttle: [com.fsck.k9.view.MessageWebView]     callback already scheduled
D/Throttle$MyTimerTask$Ha( 6084): Throttle: [com.fsck.k9.view.MessageWebView] Kicking callback
E/InputMethodManager( 6084): countrycode= DE
V/ImapResponseParser( 6084): conn1113773744<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
V/ImapResponseParser( 6084): conn1113875584<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
V/ImapResponseParser( 6084): conn1109027112<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
V/ImapResponseParser( 6084): conn1113774808<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 31: Create
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 31 for 60000 ms: acquired
V/CoreReceiver( 6084): CoreReceiver Created wakeLock 6
I/CoreReceiver( 6084): CoreReceiver.onReceive Intent { act=com.fsck.k9.service.BroadcastReceiver.fireIntent dat=action://com.fsck.k9.intent.action.MAIL_SERVICE_REFRESH_PUSHERS flg=0x14 cmp=com.fsck.k9/.service.BootReceiver (has extras) }
I/CoreService( 6084): CoreService: com.fsck.k9.service.MailService.onCreate()
V/MailService( 6084): ***** MailService *****: onCreate
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService onStart / id 32: Create
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService onStart / id 32 for 60000 ms: acquired
I/CoreService( 6084): CoreService: com.fsck.k9.service.MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_REFRESH_PUSHERS cmp=com.fsck.k9/.service.MailService (has extras) }, 1)
V/CoreReceiver( 6084): CoreReceiver Got request to release wakeLock 6
I/MailService( 6084): MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_REFRESH_PUSHERS cmp=com.fsck.k9/.service.MailService (has extras) }, 1), hasConnectivity = true, doBackground = true
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService execute / id 33: Create
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService execute / id 33 for 60000 ms: acquired
D/CoreService( 6084): CoreService (com.fsck.k9.service.MailService) queueing Runnable 1112368080 with startId 1
I/MailService( 6084): MailService.onStart took 14 ms
D/CoreService( 6084): CoreService (com.fsck.k9.service.MailService) running Runnable 1112368080 with startId 1
I/MailService( 6084): Refreshing pushers
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService onStart / id 32: releasing after 19 ms, timeout = 60000 ms
D/MailService( 6084): PUSHREFRESH: refreshing lastRefresh = 1553945980185, interval = 1440000, nowTime = 1553947420242, sinceLast = 1440057
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lists:Drafts / id 24 for 60000 ms: acquired
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 34: Create
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 34 for 60000 ms: acquired
V/CoreReceiver( 6084): CoreReceiver Created wakeLock 7
I/CoreReceiver( 6084): CoreReceiver.onReceive Intent { act=com.fsck.k9.service.CoreReceiver.wakeLockRelease flg=0x10 cmp=com.fsck.k9/.service.CoreReceiver (has extras) }
V/ImapConnection( 6084): conn1109027112>>> DONE
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lists:INBOX / id 25 for 60000 ms: acquired
V/CoreReceiver( 6084): CoreReceiver Release wakeLock 6
V/ImapConnection( 6084): conn1113875584>>> DONE
V/CoreReceiver( 6084): CoreReceiver Releasing wakeLock 6
D/MailService( 6084): PUSHREFRESH: refreshing lastRefresh = 1553945980149, interval = 1440000, nowTime = 1553947420242, sinceLast = 1440093
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 31: releasing after 54 ms, timeout = 60000 ms
V/CoreReceiver( 6084): CoreReceiver Releasing wakeLock 7
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lll:Drafts / id 22 for 60000 ms: acquired
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 34: releasing after 13 ms, timeout = 60000 ms
V/ImapConnection( 6084): conn1113773744>>> DONE
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lll:INBOX / id 23 for 60000 ms: acquired
V/ImapConnection( 6084): conn1113774808>>> DONE
D/MailService( 6084): PUSHREFRESH: refreshing lastRefresh = 1553945980190, interval = 1440000, nowTime = 1553947420242, sinceLast = 1440052
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher Lilux:Drafts / id 26 for 60000 ms: acquired
V/ImapConnection( 6084): conn1112216768>>> DONE
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher Lilux:INBOX / id 27 for 60000 ms: acquired
V/ImapConnection( 6084): conn1114074120>>> DONE
D/MailService( 6084): PUSHREFRESH:  trying to send mail in all folders!
V/MailService( 6084): Pusher refresh interval = 1440000
V/ImapResponseParser( 6084): conn1109027112<<<#11# [OK, Idle completed (0.001 + 1440.184 + 1440.184 secs).]
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 177 for lists:Drafts/Thread-2580/conn1109027112
I/MessagingController( 6084): Running command 'sendPendingMessages', seq = 23 (background priority)
V/ImapConnection( 6084): conn1109027112>>> 12 NOOP
V/ImapResponseParser( 6084): conn1113773744<<<#5# [OK, Idle completed (0.001 + 1439.783 + 1439.782 secs).]
V/ImapResponseParser( 6084): conn1113875584<<<#5# [OK, Idle completed (0.001 + 1439.363 + 1439.363 secs).]
V/ImapResponseParser( 6084): conn1113774808<<<#5# [OK, Idle completed (0.001 + 1439.894 + 1439.893 secs).]
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 102959 for lists:INBOX/Thread-2581/conn1113875584
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 7085 for lll:Drafts/Thread-2578/conn1113773744
V/ImapConnection( 6084): conn1113773744>>> 6 NOOP
V/ImapConnection( 6084): conn1113875584>>> 6 NOOP
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 162811 for lll:INBOX/Thread-2579/conn1113774808
D/MailService( 6084): Next pusher refresh scheduled for Sat Mar 30 13:27:40 CET 2019
V/ImapResponseParser( 6084): conn1112216768<<<#3# [OK, Idle completed.]
V/ImapResponseParser( 6084): conn1114074120<<<#8# [OK, Idle completed.]
V/ImapResponseParser( 6084): conn1109027112<<<#12# [OK, NOOP completed (0.001 + 0.000 secs).]
V/ImapConnection( 6084): Connection conn1109027112 has 32 capabilities
I/ImapFolderPusher$PushRu( 6084): About to IDLE for lists:Drafts/Thread-2580/conn1109027112
V/ImapConnection( 6084): conn1113774808>>> 6 NOOP
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 20874 for Lilux:INBOX/Thread-2583/conn1114074120
I/ImapFolderPusher$PushRu( 6084): Got oldUidNext 150 for Lilux:Drafts/Thread-2582/conn1112216768
V/ImapConnection( 6084): conn1114074120>>> 9 NOOP
V/ImapResponseParser( 6084): conn1113773744<<<#6# [OK, NOOP completed (0.001 + 0.000 secs).]
V/ImapConnection( 6084): Connection conn1113773744 has 32 capabilities
V/ImapResponseParser( 6084): conn1113875584<<<#6# [OK, NOOP completed (0.001 + 0.000 secs).]
V/ImapConnection( 6084): Connection conn1113875584 has 32 capabilities
V/ImapConnection( 6084): conn1112216768>>> 4 NOOP
I/ImapFolderPusher$PushRu( 6084): About to IDLE for lists:INBOX/Thread-2581/conn1113875584
V/ImapConnection( 6084): conn1113875584>>> 7 IDLE
I/ImapFolderPusher$PushRu( 6084): About to IDLE for lll:Drafts/Thread-2578/conn1113773744
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 35: Create
V/ImapConnection( 6084): conn1113773744>>> 7 IDLE
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 35 for 60000 ms: acquired
V/CoreReceiver( 6084): CoreReceiver Created wakeLock 8
I/CoreReceiver( 6084): CoreReceiver.onReceive Intent { act=com.fsck.k9.service.BroadcastReceiver.scheduleIntent flg=0x10 cmp=com.fsck.k9/.service.BootReceiver (has extras) }
V/ImapConnection( 6084): conn1109027112>>> 13 IDLE
D/CoreService( 6084): CoreService (com.fsck.k9.service.MailService) completed Runnable 1112368080 with startId 1
V/ImapResponseParser( 6084): conn1113774808<<<#6# [OK, NOOP completed (0.001 + 0.000 secs).]
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreService execute / id 33: releasing after 90 ms, timeout = 60000 ms
V/ImapConnection( 6084): Connection conn1113774808 has 32 capabilities
I/ImapFolderPusher$PushRu( 6084): About to IDLE for lll:INBOX/Thread-2579/conn1113774808
V/CoreReceiver( 6084): CoreReceiver Releasing wakeLock 8
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag CoreReceiver getWakeLock / id 35: releasing after 8 ms, timeout = 60000 ms
V/ImapResponseParser( 6084): conn1109027112<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
D/ImapFolderPusher$PushRu( 6084): Idling lists:Drafts/Thread-2580/conn1109027112
V/ImapResponseParser( 6084): conn1112216768<<<#4# [OK, NOOP completed.]
V/ImapConnection( 6084): Connection conn1112216768 has 32 capabilities
I/ImapFolderPusher$PushRu( 6084): About to IDLE for Lilux:Drafts/Thread-2582/conn1112216768
V/ImapConnection( 6084): conn1112216768>>> 5 IDLE
V/ImapResponseParser( 6084): conn1114074120<<<#9# [OK, NOOP completed.]
V/ImapResponseParser( 6084): conn1113773744<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
D/ImapFolderPusher$PushRu( 6084): Idling lll:Drafts/Thread-2578/conn1113773744
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lll:Drafts / id 22: releasing after 77 ms, timeout = 60000 ms
V/ImapConnection( 6084): Connection conn1114074120 has 32 capabilities
I/ImapFolderPusher$PushRu( 6084): About to IDLE for Lilux:INBOX/Thread-2583/conn1114074120
V/ImapResponseParser( 6084): conn1113875584<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lists:Drafts / id 24: releasing after 88 ms, timeout = 60000 ms
V/ImapConnection( 6084): conn1114074120>>> 10 IDLE
D/ImapFolderPusher$PushRu( 6084): Idling lists:INBOX/Thread-2581/conn1113875584
V/MailService( 6084): ***** MailService *****: onDestroy()
I/CoreService( 6084): CoreService: com.fsck.k9.service.MailService.onDestroy()
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lists:INBOX / id 25: releasing after 91 ms, timeout = 60000 ms
V/ImapConnection( 6084): conn1113774808>>> 7 IDLE
I/MessagingController( 6084):  Command 'sendPendingMessages' completed
I/MessagingController( 6084): Running command 'sendPendingMessages', seq = 24 (background priority)
V/ImapResponseParser( 6084): conn1112216768<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
D/ImapFolderPusher$PushRu( 6084): Idling Lilux:Drafts/Thread-2582/conn1112216768
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher Lilux:Drafts / id 26: releasing after 87 ms, timeout = 60000 ms
V/ImapResponseParser( 6084): conn1113774808<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
V/ImapResponseParser( 6084): conn1114074120<<<#+# [idling]
V/ImapFolderPusher$PushRu( 6084): Got async response: #+# [idling]
D/ImapFolderPusher$PushRu( 6084): Idling Lilux:INBOX/Thread-2583/conn1114074120
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher Lilux:INBOX / id 27: releasing after 101 ms, timeout = 60000 ms
D/ImapFolderPusher$PushRu( 6084): Idling lll:INBOX/Thread-2579/conn1113774808
V/TracingPowerManager$Tra( 6084): TracingWakeLock for tag ImapFolderPusher lll:INBOX / id 23: releasing after 112 ms, timeout = 60000 ms
I/MessagingController( 6084):  Command 'sendPendingMessages' completed
I/MessagingController( 6084): Running command 'sendPendingMessages', seq = 25 (background priority)
I/MessagingController( 6084):  Command 'sendPendingMessages' completed
V/ImapResponseParser( 6084): conn1112216768<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x61d47620 sslRead buf=0x428b91a8 len=1024,timeo=1740000
V/ImapResponseParser( 6084): conn1114074120<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x6381e958 sslRead buf=0x428c9940 len=1024,timeo=1740000
V/ImapResponseParser( 6084): conn1113773744<<<#null# [OK, Still here]
V/ImapResponseParser( 6084): conn1113774808<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x60984a10 sslRead buf=0x427c25b8 len=1024,timeo=1740000
V/ImapResponseParser( 6084): conn1109027112<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x60a8c870 sslRead buf=0x4233a368 len=1024,timeo=1740000
V/ImapResponseParser( 6084): conn1113875584<<<#null# [OK, Still here]
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x657816c8 sslRead buf=0x427e3fb0 len=1024,timeo=1740000
V/ImapFolderPusher$PushRu( 6084): Got async response: #null# [OK, Still here]
D/NativeCrypto( 6084): ssl=0x657bb5e8 sslRead buf=0x4276f138 len=1024,timeo=1740000

**Comment by cketti** [comment]
The terminal app can probably only handle plain text. We're not doing anything special so WebView probably copies formatted text to the clipboard. 
This feels like a shortcoming of the terminal app, not a bug in K-9 Mail. Other terminal apps seem to have had the same problem: https://github.com/corbinlc/GNURootDebian/issues/7

**Comment by AlainKnaff** [comment]
I don't understand.
I have an issue copying some text from one mail program (k9-mail) to a terminal program.
You point out that the issue exists while copying to other terminal programs as well.
... and conclude that the problem must lie with the terminal program(s)!

Isn't there some logic flaw here? If more than one terminal program is concerned but only one mail program, I would conclude that the fault lies with the mail program, no?

... and the only reason I mentioned viewing the text in a web browser (firefox) was to point out that by doing this detour, it works all right.

Could you at least have another look before summarily dismissing this issue?

**Comment by cketti** [comment]
If you had checked out the linked issue you would have noticed that K-9 Mail is not involved. So Terminal apps have this problem with copying text from other apps as well. 
Rather than requesting to add workarounds to all kinds of different apps you could ask the authors of the terminal app to fix the issue on their end. Feel free to point them to this: https://developer.android.com/guide/topics/text/copy-paste#CoerceToText

**Comment by AlainKnaff** [comment]
> If you had checked out the linked issue you would have noticed that K-9 Mail is not involved.

Please re-read my bug report. K-9 Mail _is_ involved. This happens with text selected in K-9 Mail (and not with text selected in other applications such as firefox).

> So Terminal apps have this problem with copying text from other apps as well.

I can copy text from firefox to jackpal just fine (mentioned above...). And why single out terminal apps?

> Rather than requesting to add workarounds to all kinds of different apps

Huh? Rather than wanking off to movies of Natalie Portmann pouring hot grits down her pants, you could maybe fix the bug :-)

> you could ask the authors of the terminal app to fix the issue on their end.

Unfortunately, jackpal is no longer maintained... but I have to use it, as other terminal apps are not supported on the version of Android on this device (4.4.1 on a Lenovo A5500-F).
