### ISSUE TITLE
Incomplete display of folder title and poll progress under Android 9 Accessibility large fonts

### ISSUE THREAD

**Issue by ssb22** [k9mail/k-9#3997]
On a Samsung Galaxy S9 running Android 9, under Settings / Accessibility / Visibility enhancements / Font size and style, I have the font size set larger by a couple of notches.  K9 Mail does not correspondingly increase the height of its top status bar (the one that says "Folders" etc), therefore the second line of this status bar is nearly completely hidden (only the top few pixels of its letters are visible).

A workaround is to turn the font size back down and instead achieve the size-increase via Android 9's "Screen Zoom" function (which probably changes the DPI).

**Comment by morgoth69** [comment]
hi yea

**Comment by cketti** [comment]
This is already fixed and will no longer be an issue in the next stable K-9 Mail version. 
There's no release date yet.

**Comment by ssb22** [comment]
Thanks :-)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
Silas S. Brown http://people.ds.cam.ac.uk/ssb22
