### ISSUE TITLE
Enchancement: Allow volume keys to scroll in message view

### ISSUE THREAD

**Issue by jmawhorter** [k9mail/k-9#3999]
### Desired behavior
K-9 mail almost entirely works on non-touch screen Android devices like this one: https://www.sonimtech.com/xp5/
The biggest problem is that there is no way to scroll through the text of a message. Could a feature be added where the volume keys could be optional used to scroll through the text of a message like they can be used to scroll through list views? If off by default, like the current volume key options, this should be a completely unobtrusive addition for the average user.

### Background for request
I am hoping to deploy rugged phones using k-9 mail in a developing world relief context where waterproof and rugged phones with long battery life are a big benefit. A secure open source email client that would work on these would be a big benefit. K-9 mail + audio recorder + autocrypt  would provide an open/secure alternative to WhatsApp.

I'm willing to do most of the coding work on this if someone could give me some pointers and if the idea was approved by the developer.

**Comment by jmawhorter** [comment]
Would whichever k-9 mail developer reviews this request please let me know:

1. would a pull request for this functionality be accepted?
2. what should the naming of the option be in the settings be? I presume putting another checkbox in the "Volume key navigation" settings would make the most sense. Some direction on how exactly this should be presented to the user since it would be mutually exclusive with the current setting to use volume keys in message views for next/previous message.

**Comment by hallyn** [comment]
Yes, please.

**Comment by hallyn** [comment]
Oh, but I still think it would be worthwhile enhancing this to also support some number key actions - i.e. 5 to 'reply' (hopefully the resulting text entry form can be used with the keybad then?), 7 delete, 5 show full headers (mimicking old voicemail controls).

You said you have a working version coded up?  I didn't see it in your repo?

**Comment by cketti** [comment]
I'd rather not add this feature. It feels like this is functionality that less than 1% of users would benefit from. At the same time it's quite a code maintenance burden.
However, the device seems to have a dpad. Presumably this works fine to scroll in lists. I believe by fixing issue #3990 your issue would be fixed as well.

**Comment by jmawhorter** [comment]
I agree this would only benefit < 1% of users but we are probably talking about 20 lines of code or so. The functionality is pretty simple and not likely to need to be maintained much.
Implementing #3990 might actually break functionality for dpad devices depending on how you impelment it. At the moment up and down on the dpad move between UI elements which allows accessing the buttons at the top of the message view and also accessing URLs in the text of the message. However, at the moment the scroll wheel events don't produce the same results as up and down on the dpad so you might be able to implement #3990 without breaking dpad.

**Comment by cketti** [comment]
Then I'll reserve judgement until I see the pull request. If it's not much code and it's unlikely code changes in the future will break the feature I'd be fine with including the functionality.

**Comment by hallyn** [comment]
FWIW the version I used for many months is https://github.com/hallyn/k-9/commit/f83fdbb1d64473ab18b4feba5a4f6e7dc43892ae
