### ISSUE TITLE
No hint about selected account

### ISSUE THREAD

**Issue by balnaborju** [k9mail/k-9#4004]
### Expected behavior
After I select an account from the accounts screen, there should be some hint on the account-specific screens which account I am actually in.

### Actual behavior
After selecting an account the user has no visual clue which account he is actually working with.

### Steps to reproduce
1. select an account from the account screen
2. forget which account you selected

### Environment
K-9 Mail version: 
5.600

Android version:
8.1

Account type (IMAP, POP3, WebDAV/Exchange):
n/a

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
The account color is displayed in all list items in both the message list and the folder list.
In addition to that, the next stable version will contain a side menu that you can pull out to check which account is currently selected.
