### ISSUE TITLE
external storage doesn't work

### ISSUE THREAD

**Issue by balnaborju** [k9mail/k-9#4005]
### Expected behavior
If I select "external storage" in the storage section of an account's settings, I expect the app to store all data related to this account on my SD-card. I know, the term "external storage" is interpreted very liberally in the Android ecosystem, but I think, 99% of the users assumes the SD-card as external storage.

### Actual behavior
Whatever I select here, everything is stored in the phone's internal flash.

### Steps to reproduce
1. select external storage in the storage section of an account's settings
2. receive some emails
3. check the filesystem

### Environment
K-9 Mail version:
5.600

Android version:
8.1

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
See #863
