### ISSUE TITLE
Feature request: configurable snapshot view size of image attachment in message view

### ISSUE THREAD

**Issue by keksjunky** [k9mail/k-9#4007]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Provide an option in folder or global configuration to choose a snapshot image view width in pixel
Size each image attachment snapshot according to setting

### Actual behavior
Image attachment preview snapshot is already implemented. That's a great feature when previewing camera surveillance mails.
But they are tiny and fixed in size

### Steps to reproduce
None

### Environment
K-9 Mail version:
5.600

Android version:
6.0

Account type (IMAP, POP3, WebDAV/Exchange):
Applies to all

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
None

**Comment by cketti** [comment]
I don't really want to make the size configurable. But larger image previews sound like something we definitely want. See #2009.
