### ISSUE TITLE
"Refresh all folders" button

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#4018]
In previous versions of k9, it was possible to manually refresh all folders on the folders screen. That screen is now a folder manager only. I suggest to add a "Refresh all" button somewhere on the main activity.

Do you have a suggestion where the button could be displayed?

**Comment by MartinX3** [comment]
Is there an ability to automatically refresh the folder list with each email refresh or once a day?
It is a bit disturbing to do it everytime again you added a folder or if an employee of the company moves emails into a new folder and he doesn't tell you about his change.

**Comment by cketti** [comment]
@MartinX3: That's a different question. I create issue #4216 for that.

**Comment by cketti** [comment]
I guess the easiest option is to put it in the overflow menu. 

Later we can maybe add a swipe down to refresh mechanism to the folder list in the navigation drawer. That feels like quite a bit of work, though. And I'm not sure it would make for a nicer user experience. But it's certainly worth looking into if someone can find the time to implement it.

**Comment by DaveJarvis** [comment]
Possibly related:

1. Open a mail reader that is not K9 (e.g., Thunderbird or browser-based web mail client).
1. Use a mail server that is not GMail, but uses IMAP.
1. Open Inbox using mail reader.
1. Create a new folder (e.g., Main).
1. Create 10 sub-folders under the new folder (e.g., Main/FA, Main/FB, Main/FC, etc.).
1. Open K9.
1. Refresh the folder list using K9.
1. Return to other mail reader.
1. Rename a few of the sub-folders (e.g., "Main/FC" becomes "Main/FC - done").
1. Return to K9.
1. Refresh the folders.

**Expected**
The renamed folder appears in K9.

**Actual**
The folder name does not get updated.

**Comment by cketti** [comment]
@DaveJarvis: Please create a new issue and don't forget to record a debug log if you want us to have any chance at finding out what's going on exactly.
