### ISSUE TITLE
Support for SyncML mail synchronization

### ISSUE THREAD

**Issue by mapto** [k9mail/k-9#4021]
The e-mail provider of my employer has disabled POP3 and IMAP access in favour of [SyncML](https://en.wikipedia.org/wiki/SyncML). I love K-9, I use it for Gmail, Yahoo and other mail services, despite the annoying security messages they send me to convert me into their own closed apps. Are there any plans to introduce SyncML support (limited to mail syncing only) to K-9?

**Comment by cketti** [comment]
We have no plans to add support for SyncML.
