### ISSUE TITLE
Daily newsletter with attachment: old version of attachment is displayed

### ISSUE THREAD

**Issue by sigi-s** [k9mail/k-9#4028]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I get a daily newsletter with pdf attachment. First I download the whole message. Then I open the pdf attachment. I expect to see the actual newsletter.

### Actual behavior
When I open the attachment in K-9, I sometimes get an old version of the newsletter (which is e.g. one week old). When I download the attachment and open it with a pdf-reader, I see the correct version. The old version had been deleted days before on the email server (POP3), so the old version must be in an (for me unvisible)  cache on the phone.

### Steps to reproduce
see above

### Environment
K-9 Mail version: 5.600
Android version: 8.1.0
Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
K-9 Mail doesn't contain such a cache for attachments. Also, the URI that is sent to the viewer app to retrieve the content from K-9 Mail is unique per attachment. So caching in the viewer app should not matter.

However, K-9 Mail allows the viewer app to get the display name of the attachment. If different newsletter emails use the same attachment name and caching in the viewer app is based on that display name, it could lead to the behavior you describe. I'd consider this to be a bug of the viewer app, though.
