### ISSUE TITLE
Feature Request: display image attachments larger

### ISSUE THREAD

**Issue by Viss** [k9mail/k-9#4031]
Hello!

 I recieve thousands of security camera emails from several systems, and it is a great help to me to be able to go through those queues on my android device. Tricky thing is, the way that image attachments are displayed only shows a tiiiiiiiny thumbnail. 

I'd like to submit a feature request where the image can be displayed in 'large mode', where perhaps it scales to the width of the display, or maybe have a "large thumbnail" option made available.

been using k9 for years, bought the paid version, I love it!

**Comment by cketti** [comment]
Duplicate of #2009
