### ISSUE TITLE
No worked whith Office365

### ISSUE THREAD

**Issue by SergeyDjam** [k9mail/k-9#4034]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Add account, check mail and other functions of  email client

### Actual behavior
Many errors, and don't adding account. 

### Steps to reproduce
1. add new mailbox
2. enter my account (email) and password
3. select protocol WebDAV/Exchange

### Environment
K-9 Mail version:
5.600 f-droid

Android version:
AOSP 8.1

Account type (IMAP, POP3, WebDAV/Exchange):
WebDAV/Exchange

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
