### ISSUE TITLE
URGENT - Messages being deleted after read

### ISSUE THREAD

**Issue by shutterspeeder** [k9mail/k-9#4035]
Messages are being deleted after being read. This is not occurring on my email server, thank God. They are not in the trash folder either.

**Comment by violoncelloCH** [comment]
You're probably just in the filtered view where you only see unread mails...

**Comment by violoncelloCH** [comment]
You're probably just in the filtered view where you only see unread mails...

**Comment by shutterspeeder** [comment]
I didn't change anything. How do I check that?

**Comment by shutterspeeder** [comment]
I figured it out. Thx. I have no idea how that happened. I never even used that feature before.
