### ISSUE TITLE
High Battery usage

### ISSUE THREAD

**Issue by heit0r** [k9mail/k-9#4040]
Since last related issue didn't say anything that i could use, I'm reopening this with the same problem.

### Expected behavior
Use low battery and low mobile data, since the e-mail account I'm linked is just for text messages with almost none attachments.

### Actual behavior (See pics below)
Huge battery and internet data consumption with no evident cause. K9 Mail spent more energy than the system itself (the kernel or something, if I'm right), the screen(!!!) and other apps. K9 Mail spent 500mb (!!!!), much more than I browsing the internet seeing pictures and so on.

### Steps to reproduce
1. Go to Configs.> USB and storage
2. Go for Configs.> Battery and battery economy
3.

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![Screenshot_2019-05-08-14-55-09](https://user-images.githubusercontent.com/38054654/57404165-b6b55d00-71b1-11e9-99d9-1d389d28602c.png)
![Screenshot_2019-05-08-14-57-20](https://user-images.githubusercontent.com/38054654/57404166-b6b55d00-71b1-11e9-843f-4be56b03a348.png)

**Comment by heit0r** [comment]
I changed the e-mail check from half an hour to 3 hours and I feel that it still didn't work. I'll try another client, because I can't stand like this any longer, my cell was hotter than normal and now its ok, room temperature. I was really enjoying using this powerful app, hope K-9 team can solve this soon.

**Comment by cketti** [comment]
See https://github.com/k9mail/k-9/issues/3968#issuecomment-474900159
