### ISSUE TITLE
Notification for each message separately

### ISSUE THREAD

**Issue by JabberwockPL** [k9mail/k-9#4041]
I believe it might be useful if there was an option to display notification for each new message separately, but I admit my usage case is rather particular.

While I am sitting at my desktop, when I get a first new message, I can have a glance of it, as it is displayed with Pushbullet on my monitor. However, for all the subsequent ones I get just the number of mails, so I still need to pick up the phone or open up the e-mail client.

Android Gmail client does exactly that, i.e. displays each message separately, but for me is it much worse than K-9 in general.

**Comment by cketti** [comment]
K-9 Mail should already create notifications for every new message. But they are grouped per account (same like Gmail, as far as I can tell).

The behavior may be different if you set 'Global settings > Privacy > Hide subject in notifications' to something other than 'Never'.

**Comment by JabberwockPL** [comment]
That is odd, as I have the setting as you said and still what is sent to the PC is: "2 new messages" instead of their contents.

**Comment by cketti** [comment]
Android has a setting to configure what notifications should look like on the lock screen. You can configure it to hide sensitive information. In that case only the number of new messages is displayed.

**Comment by JabberwockPL** [comment]
I have the lock screen turned off, so the setting should not come into play at all.

**Comment by JabberwockPL** [comment]
![K9](https://user-images.githubusercontent.com/24412050/66706526-0e915a80-ed34-11e9-9fa7-998d89771ac3.jpg)

Here is how the notification looks on my PC.

**Comment by cketti** [comment]
K-9 Mail is not responsible on how the notification looks like on your PC. Does it work as expected on the Android device? If so, report a bug to the author of the app that syncs Android notifications to your PC.

**Comment by JabberwockPL** [comment]
It is K-9 which is aggregating the messages and prepares the relevant notification. The notifications log on Android shows this:

g:newMailNotifications-0
intent: Intent
[...]
Bundle[mParcellledData.dataSize=324]
android.progressIndeterminate: false
android.SummaryText: (here it is the name of the inbox)
android.title.big: 2 nowe wiadomości (the text that appears in the notification)
