### ISSUE TITLE
Does not start on Android Q beta 3

### ISSUE THREAD

**Issue by sarunasb** [k9mail/k-9#4042]
### Expected behavior
Tap on icon. K-9 starts. Or "application stopped" notification appears.

### Actual behavior
Screen blinks, but nothing happens.

### Environment
K-9 Mail version:
5.6

Android version:
Q beta 3

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by sarunasb** [comment]
Can't get adb shell for logs.

**Comment by cketti** [comment]
New installation on Q beta 3 works fine for me. Have you tried uninstalling, then reinstalling?

**Comment by sarunasb** [comment]
Uninstall + reinstall makes K-9 work again. Wipes all K-9 settings though.

**Comment by cketti** [comment]
Then it's likely a bug with one of the Q preview versions when migrating installed apps. If you can reliably reproduce the issue, I'm sure the Android team would be happy about a bug report.

For the future: you can export K-9 Mail's settings before uninstalling and import them after installing the app again.

**Comment by Troubadix** [comment]
Issue still exists with beta 5.

Today flashed beta 5 over P (july update) on Pixel 3 XL and K9 won't start. No error,
