### ISSUE TITLE
Add option to encrypt/decrypt subject

### ISSUE THREAD

**Issue by je-vv** [k9mail/k-9#4045]
Currently when encrypting messages and sending them, the subject goes clear.  If possible there should be a global option to encrypt subjects, as Enigmail does, so that only the receiver and the sender know what the email is about.  The default for the option might be disabled for those not wanting to use it.

If enabled, then also decrypting subjects should be enabled.  Currently if a message is sent from Thunderbird with subject encrypted, K9 doesn't decrypt the subject at all, it remains as empty.  Replying actually changes the subject to empty as well ("..."), which is weird.

Thanks a lot !

**Comment by basilgello** [comment]
In the Snapshot release, there is the setting under Account Settings - Encryption Tab: Encrypt message subject

**Comment by cketti** [comment]
This will be included in the next stable version.

**Comment by je-vv** [comment]
Which K9 version is this supposed to be in?  So far using 5.600 from f-droid...

**Comment by Valodim** [comment]
It's in the current beta, and will be in the next stable. There are a lot of changes since the latest stable version, so it might be a while until the beta is stable enough for a release.
