### ISSUE TITLE
Allow underscores in hostnames

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [k9mail/k-9#4049]
A hostname can be set up on freedns.afraid.org with underscores.  The underscores allow for more readable hostnames.  Entering a hostname with underscores in K-9 Mail on android results in the 'Next' button becoming greyed-out.  Other systems permit the usage of underscores (e.g. the google mail client). 

### Expected behaviour
Underscores in domain names for incoming and outgoing servers should be allowed.

### Actual behaviour
The 'Next' button becomes greyed-out.

### Steps to reproduce
1. Go to settings -> Account settings -> Fetching mail or Sending mail -> Outgoing or incoming server settings
2. Put an underscore in the server name
3. 'Next' becomes greyed-out.

### Environment
K-9 Mail version: 5.600

Android version: 9 PKQ1.180729.001

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
DNS names may contain underscores. Hostnames may not. See https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
