### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by robsmith11** [k9mail/k-9#4056]
I was surprised not to see anything in the FAQ or issues here about spell checking.  I'm used to seeing a red squiggly line under anything I mistype.  Is there any way to enable something like that?

**Comment by spaetz** [comment]
I do have the standard android spell checking in the message composer view, including red underlining for misspellings etc.. So it should be sth specific to your setup, I think. P.S. I am just a regular user, no developer.

**Comment by robsmith11** [comment]
I didn't know Android had a built-in spell checker.  Apparently many vendors have removed it for some reason (including on my Huawei Mate 20 X).

**Comment by spaetz** [comment]
I believe the spell checker is part of the keyboard app, but I am not 100% certain of that.

**Comment by robsmith11** [comment]
After installing the Gboard, I have an option to turn on the spell checker, and it does indeed work well with k-9.

It's still a bit confusing to me as to whether Android has a built-in spell checker that can be used with other keyboards like Swiftkey.  But for now, I'm fine switching to Gboard when I want spell checking.
