### ISSUE TITLE
Signature Spoofing Attacks

### ISSUE THREAD

**Issue by basilgello** [k9mail/k-9#4057]
https://thehackernews.com/2019/04/email-signature-spoofing.html
https://github.com/RUB-NDS/Johnny-You-Are-Fired/raw/master/paper/johnny-fired.pdf

K-9 is also vulnerable. I do not know if the fix is merged into snapshot, or the paper authors reached you @cketti so leaving it here.

**Comment by danShumway** [comment]
I'd also love to get an update on this, if anything has changed. The articles say that the vulnerabilities have been fixed in most versions of the software, but I don't see anything that mentions K-9 specifically.

**Comment by cketti** [comment]
The ID attack (which is the only one K-9 is listed as being vulnerable to in the paper) seems to be quite similar to #2962.
