### ISSUE TITLE
IMAP sent mail folder doesn't appear to be syncing correctly

### ISSUE THREAD

**Issue by DasWookie** [k9mail/k-9#4059]
I have an account setup for IMAP which regularly is running into a problem with syncing. It seems that the index of messages gets confused and loops back around to the beginning.

I rename my sent mail folder at the beginning of each month via a cron job. My other IMAP clients don't have any issues with this, but K9 regularly gets the index all wrong. It is keeping older messages on my phone, even tho I can see it's syncing the sent mail folder. The messages show up in the list, but if I try and open one, it's grabbing an old message from the retained messages which should no longer show up. I'm seeing messages from December 2018 in this list clear up to April. If I open the next message in the list, it's looping around and grabbing the message from the start of the list. I can't seem to figure out how to get the index to reflect the current sent mail folder. It's appending messages to the sent mail folder correctly, and those messages are showing up on other clients, so it seems to be something about how it's reacting when the sent mail folder is renamed and a new one created each month. I think. I can't explain how else it's still showing messages from December in the locally cached view/copy of the IMAP messages.

### Environment
K-9 Mail version: 5.6

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: sorry, I don't have any way of running adb to fetch the logs

**Comment by DasWookie** [comment]
Here are some more details / screenshots from my phone which hopefully might help.

This my current view in K9 of my send mail messages:
![7](https://user-images.githubusercontent.com/9283270/57989163-644f2880-7a5c-11e9-99aa-76ae37b563ba.jpg)

If I try to open the second message (microblasting) it instead is opening a message from April 23rd:
![4](https://user-images.githubusercontent.com/9283270/57989076-6ebcf280-7a5b-11e9-979b-17abf87e148f.jpg)

If I scroll down through my Sent mail I should only be seeing messages from May, but I'm seeing messages dating all the way back to December of 2018:
![5](https://user-images.githubusercontent.com/9283270/57989094-a3c94500-7a5b-11e9-8169-95b318513183.jpg)

So I scrolled up through my message list to the beginning of the month, and there is are messages there from April 23rd and then it jumps to May 1st:
![1](https://user-images.githubusercontent.com/9283270/57989057-361d1900-7a5b-11e9-8cb3-585f51397a1c.jpg)

I can open the last message from April 23:
![2](https://user-images.githubusercontent.com/9283270/57989149-34078a00-7a5c-11e9-9803-5aa0a407b37d.jpg)

but if I open the next message for May 1st, it's looping all the way around to the first message in the index, which is in December:
![3](https://user-images.githubusercontent.com/9283270/57989160-4e416800-7a5c-11e9-8254-df4bf9c70335.jpg)

**Comment by DasWookie** [comment]
If I hit "Clear local messages" it seems to resolve itself, but I can't see why this step would be required to get the local copy to sync correctly, especially when it's able to successfully append to the messages file on the server when I send a mail on my phone.

**Comment by cketti** [comment]
See #1074
