### ISSUE TITLE
Unable to fetch and send mail when STARTTLS or SSL security (none security works)

### ISSUE THREAD

**Issue by mike-kilo** [k9mail/k-9#4062]
### Expected behavior
I should be able to fetch and send my email with SSL or TLS.

### Actual behavior
When setting up the server settings I get "Unable to connect" if the IMAP server security is set to SSL or TLS. When the security is set to "None", the messages are fetched and sent without any problems. It only concerns my hosting service PCExtreme.nl, other accounts are fetched correctly. 
The problem occurred when the provider changed their certificate recently. They will do so every 3 months for security reasons.
GMail client can connect to this mail account and fetch emails without problems (using SSL). Using Thunderbird on a desktop (SSL or STARTTLS) works fine.

### Steps to reproduce
1. Add an IMAP account 
2. Use server mail.pcextreme.nl
3. Use STARTTLS (143) or SSL (port 993) security
4. See "Unable to connect" dialog immediately

### Environment
K-9 Mail version: 5.600 but in 5.403 the problem was the same

Android version: 7.0 on Motorola G4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: Unfortunately, I don't have any ADB running at the moment. It would be convenient if K-9 Mail could log the errors locally (to a file).

**Comment by cketti** [comment]
It looks like your mail provider only supports modern TLS ciphers that your Android version doesn't support. It works fine with Android 8+.

Aside from a more helpful error message (see #893) I don't think there's much we can do on our side. I don't want to ship a separate TLS implementation with K-9 Mail.

Ask your email provider to consider adding support for older Android versions. The list of supported ciphers per Android version can be found here: https://developer.android.com/reference/javax/net/ssl/SSLEngine
The mapping from user-visible Android versions to API level can be found here: https://source.android.com/setup/start/build-numbers

**Comment by mike-kilo** [comment]
@cketti thank you for the explanation. Seems logical to me. 
Still, how do you explain the fact that GMail app can fetch and send emails from this account? Do they have a separate TLS implementation independent on what's on the system?
