### ISSUE TITLE
Improve instructions on how to export settings

### ISSUE THREAD

**Issue by bkph** [k9mail/k-9#4070]
### Expected behavior
Explain that you need to *first* hit the K9 app icon *before* using the "More" menu to get to "Settings Import & Export"

### Actual behavior
User hits "More" menu and gets a "Settings" choice which *does not* provide for import or export of settings. Frustrating and confusing. Who'd have thought to hit the K-9 icon in the first place?

### Steps to reproduce
1. Open K-9
2. Click "More" menu (three dots)
3. Click "Settings"
4. dead end!

### Environment
K-9 Mail version: 5.900

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
The documentation states that you need to go to the "Accounts" screen. https://k9mail.github.io/documentation/settings/import_export.html

However, I agree that the navigation in K-9 Mail is confusing. The next version of the app will have a unified settings screen where you'll also find the import/export functionality. Hopefully that'll make it easier to find it.
