### ISSUE TITLE
Error when i want to add an exchange account ("IO Exception")

### ISSUE THREAD

**Issue by Sim59121** [k9mail/k-9#4072]
**Hello,**

_### Expected behavior ###_

**The application should configure the mail exchange account normally**

_### Actual behavior ###_

**The application displays the same "IO Exception" error each time**

**Note : I have try on the application "Email" on android by défaut with the same settings and it's working...**

_### Steps to reproduce ###_

**1. Press the "+" button to create a new email account in K9-Mail.
2. Enter your login 
3. Click on "Manual Configuration"
4. Enter all the necessary information (exchange server, identifiers etc...)
5. Validate**

_### Environment ###_

**K-9 Mail version: 5.600**

**Android version: 7.1.1**

_Account type (IMAP, POP3, WebDAV/Exchange):_ **Exchange**

_Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:_ 

**On my computer, adb finds no trace of logs of K9 Mail....**

**Regard,**

**Note : If in the meantime I can get the logs, I'll add them !**

**Comment by cketti** [comment]
You shouldn't really use K-9 Mail with Exchange accounts anymore. Support for WebDAV will be removed in a future version.
