### ISSUE TITLE
unable to login to pop3  e-server - got this error "-ERR in pop3"

### ISSUE THREAD

**Issue by gopitamail** [k9mail/k-9#4075]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
It should be login and fetch mail from pop3 server

### Actual behavior
got this error "-ERR in pop3" when I try to login in POP3

### Steps to reproduce
1. login with pop3 server ip
2. pop3 port is 110
3. smtp port is 25

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
