### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 

### ISSUE THREAD

**Issue by gopitamail** [k9mail/k-9#4076]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
it should be connect to SMTP server and send mail

### Actual behavior
while login to SMTP using IP(eg. 122.3.17.132) as host

### Steps to reproduce
1. connect to smtp using IP(eg. 122.3.17.132) as host
2. use port 25
3. 

stack trace : 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

java.util.ArrayList.remove(ArrayList.java:477)
com.fsck.k9.mail.transport.SmtpTransport.sendHello(SmtpTransport.java:468)
com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:273)
com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkOutgoing
(AccountSetupCheckSettings.java:951)
com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings
(AccountSetupCheckSettings.java:937)
com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground
(AccountSetupCheckSettings.java:874)
com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground
(AccountSetupCheckSettings.java:852)
android.os.AsyncTask$2.call(AsyncTask.java:304)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
java.lang.Thread.run(Thread.java:761)

### Environment
K-9 Mail version: 5.600

Android version: 

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This looks like the server doesn't send a proper response to an EHLO command. Are you sure you're connecting to a SMTP server?

**Comment by gopitamail** [comment]
Yes, It is SMTP server

**Comment by cketti** [comment]
Can you please record a debug log when trying to send a message. See https://github.com/k9mail/k-9/wiki/LoggingErrors
