### ISSUE TITLE
Unable to loate "Add New Account" on Overflow Menu

### ISSUE THREAD

**Issue by matteg** [k9mail/k-9#4077]
When I opened K9 for the first time, I was led through setting up my primary email account with no problems.  I stopped when I reached the "Almost Done" screen because I could not tell if my POP3 message download would delete the email from the server.
1.  It would be helpful if during the setup the user would be advised that downloaded mail is not deleted from the server unless the user chooses to do that.
2.  Intending to do some research I believed that cancelling out before the new account wizard completed would discard the Account settings I had already specified.  The next day I discovered that the mail was being downloaded .... which meant that if the answer had been that mail WOULD be would be deleted when downloaded - I would have lost years of emails from my server.  Would it be possible to add to the "Initial Setup" wizard a Cancel button on each screen ?
3.  I now wish to Add another email account as described in the documentation under "Add Account" (https://k9mail.github.io/documentation/accounts/add.html).  The opening paragraph states "For any additional accounts they can be added by going to the accounts menu, and then tapping the ‘Add account’ option in the overflow menu",   However, I do not see an overflow menu on my phone and so I can not add another account.  Has the "Overflow Menu" been removed ?
Thanks for your assistance.
Gerry Matte
![k9-accountSettings20190529](https://user-images.githubusercontent.com/2640631/58594325-1daeba80-8222-11e9-9256-0ce54b268e3f.png)

**Comment by timlod** [comment]
Having the same issue. No Add Account option to be found anywhere.

**Comment by timlod** [comment]
I found it now. Go back to 'Accounts' in default view and click on the +.

**Comment by cketti** [comment]
This will be much easier to find in the next stable version.
