### ISSUE TITLE
Frequent Crashes with Android 10 beta

### ISSUE THREAD

**Issue by motp** [k9mail/k-9#4078]
Hi, while testing Android 10 beta, I stumbled over some weird crashes which led to reinstallation of the K9 app. 

### Expected behavior
a) A tap on the K9 icon should launch K9 and the main screen should be visible

### Actual behavior
With Android 10 beta, this is, what I observed:
1) a tap on the K9 icon launches K9 for a second and then the main window closes down. I can't tell if it crashes or if the GUI is just not rendered. But neither recurring starts, nor completely stopping the app and restarting will help. Then I tried to clear the app cache with no success. After a complete reinstallation, K9 asks for permission to access files and address book. Then I can add accounts and use it as usual. 

Now comes the weird part: After resetting all App-Permissions to system Default, the same 
"crashes" happened again. This time I chose to delete the application data instead of reinstalling and again, K9 asks for permission to access files and address book, lets me add accounts and works like normal.

So, this seems somehow related to the changes in permission management, but since I don't see any error messages, I can't tell more about it, right now.

### Steps to reproduce
1. Install Android 10 beta
2. Tap on K9-Icon
3. "crash" or "disapperaring window"

### Environment
K-9 Mail version: 5.600

Android version: 10 on Google Pixel XL (Version 1)
Last Security Updates: 05.05.2019

Account type (IMAP, POP3, WebDAV/Exchange): several imap(s) accounts

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

I have logged 4 different times:

1) After resetting app defaults:
[k9-log.16354-1.txt](https://github.com/k9mail/k-9/files/3234638/k9-log.16354-1.txt)

2) After first tap on K9-icon / crash
[k9-log.16354-2.txt](https://github.com/k9mail/k-9/files/3234639/k9-log.16354-2.txt)

3) A second try
[k9-log.16354-3.txt](https://github.com/k9mail/k-9/files/3234640/k9-log.16354-3.txt)

4) A third one
[k9-log.16354-4.txt](https://github.com/k9mail/k-9/files/3234641/k9-log.16354-4.txt)

**Comment by cketti** [comment]
The logs don't contain stack traces of the crashes. Can you please record a log without filtering for K-9 Mail's PID. The log entries we're after should have the `AndroidRuntime` tag.

**Comment by motp** [comment]
Here it is. On second view, this doesn't look like a crash, the PID of the k9 process doesn't change while testing. 
[full-log.after.2nd.k9start.txt](https://github.com/k9mail/k-9/files/3243810/full-log.after.2nd.k9start.txt)

**Comment by motp** [comment]
Btw: I don't read this webpage frequently and Github is not IPv6 capable. If you want to contat me directly. just send an email to bbu@penguin.de

**Comment by reanimus** [comment]
I'm seeing a similar crash on launch with my Pixel 3a XL on the latest beta. I've attached the adb log; I stopped the log dump after attempting to launch. From what I can tell, there's not much information in it, though.

[k9-log.txt](https://github.com/k9mail/k-9/files/3322131/k9-log.txt)

**Comment by cketti** [comment]
I can't find any crashes of K-9 in the logs. If you're still experiencing crashes with Android 10 (non-beta) please create a new issue.
