### ISSUE TITLE
No text visible in messages, changelog, or "About" screen

### ISSUE THREAD

**Issue by sredman** [k9mail/k-9#4085]
Pictures speak louder than words here, so I have attached several.

For a couple of weeks I have not been able to read messages in K9 mail. I can see the message body in the preview in the screen which shows the list of messages, so clearly something is working, but when I click one I get the header portion with the subject, date, and sender but I can't read the text.

The first thing I tried was to export settings, wipe app data and then import settings but that did not change the situation. If I wipe, do not re-import, and manually re-add the mail account details, I get the same behavior.

Screenshots:

![About screen](https://user-images.githubusercontent.com/1900703/59640440-4fc58500-911b-11e9-87b0-23039e1924ec.jpg)

![Change Log](https://user-images.githubusercontent.com/1900703/59640509-856a6e00-911b-11e9-8e25-112ce215c6ee.jpg)

![Messages Listing](https://user-images.githubusercontent.com/1900703/59640521-8ef3d600-911b-11e9-8e0f-247ab2f6775f.jpg)

![Message View (Top message from listing)](https://user-images.githubusercontent.com/1900703/59640528-987d3e00-911b-11e9-8bfb-569251dc1ad1.jpg)

### Expected behavior
Text should render

### Actual behavior
Text does not render

### Steps to reproduce
1. Open "About" screen
2. Click "Chang Log" button of "About" screen
3. Open message

### Environment
K-9 Mail version:
Android settings says 5.600 ("About" screen is blank!)

Android version:
9.0 (OnePlus 6T, international firmware)

Account type:
2x IMAP

Log attached: [k9-log.txt](https://github.com/k9mail/k-9/files/3299014/k9-log.txt)
At approximately 16:01 I enabled debugging, opened my email inbox, and then opened a message (specifically, the one I screenshot). I have left the whole log for your enjoyment, but that might be the more relevant part.

**Comment by sredman** [comment]
I am set up for Android development, so if you want me to build a test version or something let me know!

**Comment by sredman** [comment]
On the surface, it seems very similar to this issue: https://github.com/k9mail/k-9/issues/3111, but my issue has nothing to do with searching

**Comment by cketti** [comment]
It looks like the `WebView` component is broken on your device. This is unlikely to be a bug in K-9 Mail.
