### ISSUE TITLE
No file browser found for "save attachments" settings

### ISSUE THREAD

**Issue by dusscloud** [k9mail/k-9#4086]
I use the default file browser "Files" on my Motorola G6 (Android 9) which is well recognized by any other app.
Nevertheless on K9, when going to Home>Settings>Miscellaneous, and click on the "Save attachments to..." item, I get a message saying "No file browser found. "
What's wrong?

**Comment by cketti** [comment]
Only a couple of file browsers are supported in K-9 Mail versions up to 5.600.

But this functionality will change in the next K-9 Mail version. So this will no longer be an issue.

**Comment by Screenman47** [comment]
I have had the same problem since I started using K9 a few years ago. Is there any news on when the next version is being launched. Cannot get K9 to save to my SD card. Tried everything. Really a pain.
