### ISSUE TITLE
Emails not sent/received on LTE, but on Wifi

### ISSUE THREAD

**Issue by newrokor** [k9mail/k-9#4089]
### Expected behavior
Sending/receiving of emails should work on Wifi and LTE, but works only on Wifi

### Actual behavior
Immediate (before connecting the server?) message "ConnectException: Connection refused". Email not sent. No fetching of emails on the IMAP server.

### Steps to reproduce
See attached log. k9-log.txt contains some more information on the actions taken and the things already tested for sending of emails. No logs yet when connecting to IMAP.

### Environment
K-9 Mail version: 5.600 from F-Droid

Android version: 7.1.2 (14.1-20180428-NIGHTLY-serranoltexx)

Account type: smtp.mailbox.org:587 (a high-quality German mail provider used for years now), STARTTLS. Works via Wifi on the problematic phone(s), and from different other sources this way (e.g. TB on Linux and Windows); imap.mailbox.org:143, STARTTLS.

### Attachment (Log with further comments)
[k9-log.txt](https://github.com/k9mail/k-9/files/3317892/k9-log.txt)

**Comment by newrokor** [comment]
Extended the information also for connection to IMAP. Situation the same: Receiving emails via Termux CLI and FairEmail fine, not working with K-9.

**Comment by cketti** [comment]
Unfortunately, the log doesn't contain any useful information. However, the text "ConnectException: Connection refused" indicates that the connection was actively refused.

We're not doing anything special. Simply using the functionality from the Android SDK to open a socket. I don't see how we could track down what causes this issue in a reasonable way without being able to reproduce this ourselves. I'm afraid you're on your own here.
