### ISSUE TITLE
K9-Mail isn't aware of Open Contacts

### ISSUE THREAD

**Issue by Rbagman** [k9mail/k-9#4090]
Hello,

Would you make K9-Mail aware of Open Contacts (https://f-droid.org/en/packages/opencontacts.open.com.opencontacts/)
so it will pull email addresses from Open Contacts as well.

**Comment by ByteHamster** [comment]
The description of open contacts says:

> This way no other app would be able to access contacts.

Therefore, K9 is not able to access the contacts. That's by design. Open Contacts does not provide any way to read its database. Your feature request is technically impossible.

**Comment by Rbagman** [comment]
And that's why I installed too. External address book is proving annoying. Thanks for reply, I zoned on that.
