### ISSUE TITLE
Add Optimize Data feature and Downloads Path feature in the storage section for K9-mail application

### ISSUE THREAD

**Issue by ammarraisafti** [k9mail/k-9#4092]
# Components
K9-Mail is a very useful email client application for use on android devices. This app is still in development and open source, allowing users to provide suggestions and feedback to developers. It looks very nice and simple, and has a very small file size. And that's amazing. In order for this app to be interesting to use, I would like to propose new features to developers.

The following are the features that I want to recommend:

- Optimize Data. 
- Downloads Path. 

# Proposal description
**Propose to K9-mail application developer to add new features in K9-mail app.**

- Add the "Optimize Data" feature in the Settings section of the K9-MAIL app, which is in the account setting section, and add it in the STORAGE section, and grant the user access using the Optimize Data feature.

- Add the "Download Patch" feature in the Settings section of the K9-MAIL app, which is in the account settings section, and add it in the STORAGE section, and grant users access using the feature to select the storage destination folder.

# Mockups / Examples
- Sample image of the destination folder to add new features, in the STORAGE section. 
![Screenshot_20180228-021734-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519761967/fqkx7iwhhxvzrmhsiz8j.png)

- An example image after the developer adds two new features in the STORAGE section. 
![Screenshot_20180228-021734bah.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519762082/yn3ryend0yyvptobqi8t.png)

- An example of a benefit image from the "Optimize Data" feature.
![Screenshot_20180228-021734-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519762169/ihdreinj3qj9dlfukgzs.png)

- An example of a benefit image is from the "Download Patch" feature.
![Screenshot_20180228-021734-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519762208/j2emhtbzuzoyirqhhwmj.png)

# Benefits
- The benefit users get from the "Optimize Data" feature is that users can use this feature for data capacity can be improved by deleting old messages. Users will be able to re-download messages from the server.

- The benefit that users get from the "Download Patch" feature is that the user can set the download path option to the desired folder, so the user has no trouble displaying the downloaded file, and find it easily.

**Comment by cketti** [comment]
In the future please create one issue per feature request.

1) By default K-9 Mail only keeps a limited amount of messages on the device. Old messages are removed from the device as new messages are downloaded. I don't see the need for a separate "Optimize Data" feature.

2) There already is a setting 'Global settings > Miscellaneous > Save attachments to…"
