### ISSUE TITLE
Enhancement: send "server sync in progress" notifications to a separate notification channel

### ISSUE THREAD

**Issue by pandruszkow** [k9mail/k-9#4095]
### Expected behavior
K9Mail has a separate notification channel for the temporary "syncing to server" messages that can be toggled on and off in notification settings on Android 8.0 and above (as described in https://developer.android.com/training/notify-user/channels)

### Actual behavior
Temporary "syncing to server" notifications are not separated from the main "new message received" notifications. Every time K9 does a poll, the "syncing" notification in the pull-down flashes on and off as each folder gets polled, basically stopping the user from using the notification pull-down until the poll is completed.

### Steps to reproduce
1. Set up an email account with K9Mail
2. Tick 'Account settings > Fetching mail > Advanced > Poll when connecting for push'
3. Open the notification pull-down in Android
4. Wait until K9 begins a poll

### Environment
K-9 Mail version: 5.600

Android version: 9 (stock firmware, build number 00WW_3_260_SP04)

Device: Nokia 6.1 (TA-1050)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
You can disable sync notifications under 'Account settings > Notifications > Sync notifications'. The next stable version will also have support for notification channels and separate the different notification types.

**Comment by pandruszkow** [comment]
Thanks
