### ISSUE TITLE
virus in app?

### ISSUE THREAD

**Issue by bikb** [k9mail/k-9#4101]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Not connects to statistics or file uploads.

### Actual behavior
connects to files.crsend.com
connects to stats-eu2.crsend.com

### Steps to reproduce
1. Install netguard...
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 8

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I cannot find this address in source code.

Is/was there an modified one in the app store?

**Comment by cketti** [comment]
As you should have seen in the code, K-9 Mail is not using any kind of analytics or remote services. It does however establish connections to arbitrary internet servers when you're viewing emails that have references (images most of the time) to those servers. By default loading of remote content is disabled, though. You have to either enable this under 'Account settings > Reading mail > Always show images' or on a per-message basis by clicking the "Show pictures" button.
