### ISSUE TITLE
Server contacts

### ISSUE THREAD

**Issue by lawson85** [k9mail/k-9#4103]
### Expected behavior
Tell us what should happen
>searching for contracts in my office365 organisation, should show server contacts not just those in my contacts list
### Actual behavior
Tell us what happens instead
>Well it shows no results as is only local searching. 
### Steps to reproduce
1.Compose button
2.in the ' to ' field, type a name u know is in organisation and see if appears
3. Latest app version, office365 imap

### Environment
K-9 Mail version:
5.600
Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by lbdroid** [comment]
IMAP is a mail protocol, not a contact syncing protocol.

You should look at the program "DAVx5" for contact synchronization. Don't worry, it will create a second contacts account on your phone, not merge them with your existing contacts.

**Comment by cketti** [comment]
We currently have no plans to add support for synchronizing contacts.
