### ISSUE TITLE
K-9 mail not polling Yahoo emails at set interval

### ISSUE THREAD

**Issue by hockey2nite** [k9mail/k-9#4107]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I have the App set to pull emails every 30 minutes.  It should do that.  

### Actual behavior
The App will not pull the emails unless I open the App and swipe down.  I suspect this has something to do with settings within Android, but I can't figure what.  

### Steps to reproduce
1.  Use a Note 8
2.  Set App to poll every 30 minutes
3.

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
See issue #3950
