### ISSUE TITLE
Yahoo.it IMAP account doesn't get emails automatically

### ISSUE THREAD

**Issue by lguariento** [k9mail/k-9#4118]
### Expected behavior
I want to receive my Yahoo.it emails as soon as they're sent to me, and also get a notification, as I do with other IMAP accounts on k9 (gmail and others).

### Actual behavior
New Yahoo.it emails are only downloaded if I manually refresh the account folder. New gmail and other emails are pushed automatically and I get notified.

### Steps to reproduce
1. Install k9
2. Configure a yahoo.it account 
3. Send an email to that account. The email will not be pushed and no notification will be given, even if the notifications are active in the settings (and I receive notifications for the gmail account).

### Environment
K-9 Mail version: v5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Yahoo only supports some proprietary push mechanism, not IMAP IDLE. See e.g. here: https://help.smallbusiness.yahoo.net/s/question/0D51a00000pvtYMCAY/idle-support
