### ISSUE TITLE
Display Sha512 Fingerprints for Server-Certs

### ISSUE THREAD

**Issue by yoshimo** [k9mail/k-9#4127]
### Expected behavior
If my mailserver uses a self-signed cert, k9 should display the sha512 fingerprint of the cert

### Actual behavior
I only see sha1 fingerpint

### Environment
K-9 Mail version: 5.600
Android version: 8.1

**Comment by cketti** [comment]
We might not support self-signed certificates for much longer. See #2361

**Comment by Sobuj53** [comment]
Please don't ditch support for self-signed certificate. Many of us still relay on that

**Comment by cketti** [comment]
@yoshimo: Why do you want the SHA-512 fingerprint to be displayed? Other apps seem to display the SHA-1 and SHA-256 fingerprints.

**Comment by yoshimo** [comment]
It was given to me by the mailbox provider and the fingerprint k9 displayed back then wasn't on the list. Don't remember if 256 was in the docs.
