### ISSUE TITLE
Accounts activity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [k9mail/k-9#4130]
Accounts activity, when I change the orientation of the device screen, changes its state. Below there are four different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...
![2019-07-25 23-21-24_before](https://user-images.githubusercontent.com/53469180/62134103-369a2180-b2e0-11e9-8e8d-fcce4a8778c4.png)
![2019-07-25 23-21-24_after](https://user-images.githubusercontent.com/53469180/62134104-369a2180-b2e0-11e9-99ec-db2d5fb50d65.png)
![2019-07-25 21-40-23_before](https://user-images.githubusercontent.com/53469180/62134105-369a2180-b2e0-11e9-81b4-ffc6071ff80d.png)
![2019-07-25 21-40-23_after](https://user-images.githubusercontent.com/53469180/62134106-369a2180-b2e0-11e9-9352-2d7201ca35b3.png)
![2019-07-25 21-07-32_before](https://user-images.githubusercontent.com/53469180/62134107-3732b800-b2e0-11e9-89c8-7f050e016b74.png)
![2019-07-25 21-07-32_after](https://user-images.githubusercontent.com/53469180/62134110-3732b800-b2e0-11e9-9f45-5679984df78f.png)
![2019-07-25 09-53-44_before](https://user-images.githubusercontent.com/53469180/62134111-3732b800-b2e0-11e9-8d04-fcd313d65504.png)
![2019-07-25 09-53-44_after](https://user-images.githubusercontent.com/53469180/62134112-37cb4e80-b2e0-11e9-8193-0db63fb72900.png)

**Comment by cketti** [comment]
Closing this issue because the `Accounts` activity will be removed. See #3751.

**Comment by dlicse** [comment]
Thank you! I'm a researcher at the University of Milano-Bicocca and I would like to know if you consider them as GUI failures.
