### ISSUE TITLE
Dialog in Prefs activity disappears after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [k9mail/k-9#4135]
In Prefs activity, when I change the orientation of the device screen, the Dialog widget "Saved attachment" disappears.
![2019-07-25 14-28-50_before](https://user-images.githubusercontent.com/53469180/62136266-08b6dc00-b2e4-11e9-88f4-e0d6a74b29da.png)
![2019-07-25 14-28-50_after](https://user-images.githubusercontent.com/53469180/62136268-094f7280-b2e4-11e9-90df-6cfcf66a7a24.png)

**Comment by cketti** [comment]
This setting is no longer present in the current development version. With it the bug is gone, too.
