### ISSUE TITLE
IMAP sent folder does not show recipient when message sent from Thunderbird with non-default identity

### ISSUE THREAD

**Issue by zpuskaric** [k9mail/k-9#4137]
I have Thunderbird 60 and K-9 accessing same IMAP account. When I send a message from Thunderbird and look at the list of sent messages on my phone there is no recipient listed on message list screen for messages sent with non default identity. If I send messages from K-9 then with same identities than recipient is visible in K-9 Sent folder message list

### Expected behavior
Recipient address visible in Sent folder no matter which identity is used to send a message.

### Actual behavior
Messages sent from Thunderbird (maybe other programs) with non-default identity show up without recipient address in K-9 Sent folder message list

### Steps to reproduce
1. Send messages with different identities from Thunderbird 60
2. Check Sent folder with K-9
3. Messages sent with non-default identity do not show recipient address

### Environment
K-9 Mail version: 5.600

Android version: 7.1.1

Account type: IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
 
**message with default identity:**

To: =?UTF-8?B?xb1lbGprbyBQdcWha2FyacSH?= <zpuskaric@hzhm.hr>
From: =?UTF-8?B?VmVkcmFuYSBBbsSRZWxpxIc=?= <vedrana.andjelic@hzhm.hr>
Subject: from vedrana.andjelic@hzhm.hr
Message-ID: <2e920e15-0207-375a-9273-cf41ac29598f@hzhm.hr>
Date: Wed, 31 Jul 2019 09:59:02 +0200
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.5.3
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------1481640B00248D9DF8EF92C2"
Content-Language: hr

This is a multi-part message in MIME format.
--------------1481640B00248D9DF8EF92C2
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

test test test

-- 

**message with non-default identity:**

To: =?UTF-8?B?xb1lbGprbyBQdcWha2FyacSH?= <zpuskaric@hzhm.hr>
From: =?UTF-8?Q?Tajni=c5=a1tvo?= <tajnistvo@hzhm.hr>
Subject: from tajnistvo
Message-ID: <ced06ae1-0208-0227-a726-2d7c841aa66f@hzhm.hr>
Date: Wed, 31 Jul 2019 09:58:19 +0200
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.5.3
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------2F408CE8CEAF17FB5EE9CB3F"
Content-Language: hr

This is a multi-part message in MIME format.
--------------2F408CE8CEAF17FB5EE9CB3F
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

test test test

--

**Comment by cketti** [comment]
Sounds like expected behavior. K-9 Mail will show the sender of a message unless the sender address belongs to one of the account's identities. In that case it'll show the recipient address. This behavior is folder-independent.
