### ISSUE TITLE
My latest reply not shown in thread

### ISSUE THREAD

**Issue by dessalines** [k9mail/k-9#4149]
### Expected behavior

I have the view set to threading / threaded view. After sending a reply, I should see that reply in the conversation thread. It is **always missing**, until they reply back to me again. 

### Actual behavior
This is annoying because I can't read what I just wrote in that thread. I have to go back to my sent folder, then back to the thread and back and forth.

### Steps to reproduce
1. Have threaded view turned on.
2. Receive email.
3. Send email.
4. That recent send is not in the thread, I have to go to my sent folder.

### Environment
K-9 Mail version:

Android version: 9

Imap accounts.

**Comment by cketti** [comment]
See #735
