### ISSUE TITLE
Contact picture colors

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#4155]
Experiments with contact picture colors. For details, see #4110. For code, see https://github.com/ByteHamster/k-9/commit/7ce47e12e22ca8c937f571d8ab55b1ac54cf640b. Now that I see the colors in context, I actually like the 500 shades. Everything except grey, lime, light green and yellow looks quite good, in my opinion. Maybe we can just throw them out?

50/100/200
<img width="200" src="https://user-images.githubusercontent.com/5811634/62898515-f746e880-bd55-11e9-8c45-7edb0e1edbbe.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898516-f746e880-bd55-11e9-81e8-87a8c9a52dc0.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898517-f7df7f00-bd55-11e9-9436-61914d399e68.png" />

300/400/500
<img width="200" src="https://user-images.githubusercontent.com/5811634/62898562-180f3e00-bd56-11e9-8d64-64880c481313.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898563-180f3e00-bd56-11e9-8a2a-a7ea9b07eb28.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898564-180f3e00-bd56-11e9-8cff-efebaeb4bf6d.png" />

600/700/800
<img width="200" src="https://user-images.githubusercontent.com/5811634/62898577-1d6c8880-bd56-11e9-8f08-496bb9af5b57.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898578-1d6c8880-bd56-11e9-91b0-3c33086bc75d.png" /> <img width="200" src="https://user-images.githubusercontent.com/5811634/62898579-1d6c8880-bd56-11e9-819c-98074fe6973c.png" />

900
<img width="200" src="https://user-images.githubusercontent.com/5811634/62898592-25c4c380-bd56-11e9-9797-d96cc593b544.png" />

**Comment by ByteHamster** [comment]
@cketti Do you want the colors to be backwards compatible? In previous versions, there were 10 colors. The Material palette has 19 colors where 15 look good on a contact badge. If we want to use all colors, that can not be done in a backwards compatible way.

**Comment by bhm** [comment]
Those contact badges carry little (at least apparent) info for me. Personally I prefer them fading into background so 200 or 300 weight.

**Comment by cketti** [comment]
@ByteHamster: Thanks a lot for the screenshots :heart: 

I'm not yet sure which one I like best. But since both @ByteHamster and @bhm like 300, let's go with that for now.

Not doing it in a backwards compatible way is fine.

**Comment by BrainBlasted** [comment]
One thing to consider is contrast - 300 has far too little contrast on the yellows, and only okay contrast on the orange. 600 is where the white contrasts well enough with all colors.
