### ISSUE TITLE
The menu do not show and clicking the back button does not respond on HISI platform

### ISSUE THREAD

**Issue by WJMGO** [k9mail/k-9#4156]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
The menu should be displayed in the upper right corner.
The menu button should respond.

### Actual behavior
The menu do not show and clicking the back button does not respond on HISI platform

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.6.00
Android version:
7.1 and 8.0
Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:wjmgoforit@gmail.com

**Comment by cketti** [comment]
Sounds like an issue you should report to the creators of the "HISI platform".
