### ISSUE TITLE
Add support for pEp (pretty easy privacy)

### ISSUE THREAD

**Issue by Bunnicula2** [k9mail/k-9#4170]
Supporting pEp would allow properly rendering incoming pEp mails. More importantly it allows the user to encrypt the e-mail subject.

### Expected behavior
Enigmail/pEp-encrypted messages should be recognized as such and properly display subject and attachment names upon decryption. There should at least be an option to send messages using pEp.

### Actual behavior
When receiving a pEp message, the subject is always "..." and the real subject is hidden in an attachment called "noname". When sending multiple attachments, sometimes the attachment names are lost and replaced by 5-digit numbers.

When sending a mail it's recognized properly by Thunderbird with Enigmail/pEp but the subject is not encrypted (unlike in pEp).

### Steps to reproduce
1. Have a desktop with Thunderbird with Enigmail addon (which uses pEp).
2. You need to have a GPG key set up (Enigmail can make one for you I think).
3. Send an encrypted email from said account and open received mail in K-9.

### Environment
K-9 Mail version: 5.600 (F-Droid)

Android version: 7

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: Don't have adb/root

**Comment by Bunnicula2** [comment]
I'd also support any solution that allows automatic encryption of e-mail subject so that I don't have to type it manually in the body and put garbage in the real subject field.

**Comment by cketti** [comment]
The next stable version will support protected headers. But I don't know if this is also the mechanism pEp is using to encrypt subjects.
