### ISSUE TITLE
Feature: Give user a friendly warning when he has more than 5 addresses in both the To or CC field

### ISSUE THREAD

**Issue by Meteor0id** [k9mail/k-9#4172]
Unfortunately it still happens every day; people who send an email to large group of clients but accidentally use the To or CC field instead of BCC. Although it isn't K9's fault if users make that mistake, K9 could give users a friendly warning when they press send to help both sender and receiver from experiencing a leak of personal information.

What I propose is to add a warning pop-up when the To and CC field add up to more than 5 addresses. "You are sending this email to more than 5 people who will be able to see each others email address. Are you sure you didn't mean to add these addresses in the BCC field?"
With options "Send" and "Don't send yet"

This warning would be enabled by default, but the threshold can be adjusted in preferences, including the option to disable the warning completely.

I picked more than 5 as an initial default but we could implement this with a different default threshold.

**Comment by cketti** [comment]
Different people use email in vastly different ways. What might be a good idea in your environment could be very annoying to others.
I don't want to make this an initially disabled, optional feature either. K-9 Mail is currently suffering from too many settings that often interact in unforeseen ways. It's one of the things that make it very difficult to make changes to the app.

I'm not generally opposed to adding features like this. But it'll be a long time before the app will be ready for that. Closing this issue for now.

**Comment by Meteor0id** [comment]
@cketti I don't see anything at this time which is likely to interfere with simply a warning pop-up which can be disabled in settings. It's quite a straight forward simple feature.
**Can you give any concrete indication what is needed before K9 is ready for this?** To me it looks ready now.

For clarity, the idea is to make this an initially enabled optional feature. It could be a simple pop-up with a checkbox 'don't warn me about thus again'. And two buttons 'send anyway' and 'don't send yet'.

**Comment by spaetz** [comment]
@Meteor0id if you check the commits you can see that there is a pretty major rewriting of the app in kotlin with muchvrefactoring going on, so there are plenty of moving parts right now.
One of the peculiarities of k9 are its distributed and spread-out settings. So, I can see why this is pretty low on the  list right now.

P.S. I am just a user.

**Comment by Meteor0id** [comment]
@cketti maybe wecan just at a label "reopen in distant future"
