### ISSUE TITLE
NPE when clicking next in account settings

### ISSUE THREAD

**Issue by Yky** [k9mail/k-9#4173]
### Expected behavior
Account setup successful or a meaningful error message

### Actual behavior
NullPointerException

### Steps to reproduce
1. Go to account settings
2. enter details for exchange server, security, port, username, password 
3. click next

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): Exchange

Logs:
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.mail.store.webdav.WebDavStore.findFormAction(WebDavStore.java:716)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.mail.store.webdav.WebDavStore.performFormBasedAuthentication(WebDavStore.java:635)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.mail.store.webdav.WebDavStore.authenticate(WebDavStore.java:516)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.mail.store.webdav.WebDavStore.checkSettings(WebDavStore.java:170)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkIncoming(AccountSetupCheckSettings.java:497)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings(AccountSetupCheckSettings.java:467)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:424)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:402)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-26 21:17:56.963 E/AccountSetupCheckSettin(30633): 	at java.lang.Thread.run(Thread.java:764

**Comment by cketti** [comment]
Chances are your Exchange server doesn't support WebDAV (only very old Exchange versions do). 

We're unlikely to fix this issue. The plan is to remove WebDAV support.
