### ISSUE TITLE
Never ending sync loop when closing app while syncing

### ISSUE THREAD

**Issue by powerverwirrt** [k9mail/k-9#4174]
Couldn't find any related, already reported bugs. I'm sorry if I missed something!

### Expected behavior
When the app is closed while manually syncing all accounts, the sync should still be completed or interrupted on closing the app.

### Actual behavior
Syncing is never completed/is stuck, notification doesn't go away, new e-mails are not found -> app needs to be shut down hard in settings

### Steps to reproduce
1. Open app
2. Go to Unified Inbox/All messages
3. Swipe down/Click on sync button
4. Close app

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP on all accounts

**Comment by powerverwirrt** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/3559934/k9-log.txt)

Debug Log. I've put <email> wherever my actual adress appeared.

**Comment by cketti** [comment]
Looks like K-9 Mail is trying to listen to new messages in a folder that doesn't exist on the server. Go to the folder list screen and refresh the folder list.
