### ISSUE TITLE
Long-press to select/deselect an item in the message list

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4188]
Get rid of the popup when long-pressing an item in the message list and select/deselect the item instead.

This should probably be implemented together with:
- #1426 Swipe left/right on message to perform action
- #1391 Selection taps/marks on contact icons

Related: #3555 Allow reading messages in select mode

**Comment by madduck** [comment]
Not sure this applies to 5.7xx, but it's gotten especially bad in this release.

**Comment by markusb68** [comment]
Yes, where are these check boxes to select several messages gone?
![Screenshot](https://user-images.githubusercontent.com/20417704/70904776-87e24d80-2002-11ea-88a0-8e0455b97ef1.png)

**Comment by patricktokeeffe** [comment]
I'm pretty sure the pre-Material UI allowed users to swipe to select/de-select. I miss that feature.

**Comment by elhennig** [comment]
Can you make this configurable? I rely on the context menu popup and I find it much more important than being able to mark the messages.

**Comment by cketti** [comment]
"More from this sender" is no longer available. See also the description for PR #4608.

There are no plans to bring back the context menu. To learn why the answer to "can this be an optional feature" is almost always "no" read http://neugierig.org/software/blog/2018/07/options.html

**Comment by elhennig** [comment]
"More from this sender" is so useful and I use it daily. Can this be implemented at least in the message view - for example by long press the sender address instead of copying it to the clipboard?

**Comment by espectalll** [comment]
Hey, just tried out the new release, thanks for the new select behavior! Just one question: could it be implemented, so that holding and dragging up/downwards selects multiple messages at once?

**Comment by cketti** [comment]
@espectalll: Please open a new issue for that feature request.
