### ISSUE TITLE
Being repeatedly prompted on Android 10 to check if there is a newer version available

### ISSUE THREAD

**Issue by jikamens** [k9mail/k-9#4190]
Just upgraded to Android 10. Now I'm being repeatedly prompted by Android when I launch K-9 Mail. The pop-up says that K-9 Mail was built for an older version of Android and I should check if a new version is available.

Please release a version that is compatible with Android 10 so this goes away?

**Comment by jikamens** [comment]
(I'm using Pixel 3 XL unlocked bought directly from Google)

**Comment by kpinc** [comment]
Same problem here.

**Comment by cketti** [comment]
See #4195
