### ISSUE TITLE
Decryption does not work

### ISSUE THREAD

**Issue by Crankle437** [k9mail/k-9#4192]
Hi,

### Expected behavior
Decrypt received E-Mails. 

### Actual behavior
Cannot decrypt E-Mails which are sent from pc with thunderbird. I can decrypt the sent E-Mails from my phone on the pc and on the phone. I've sent decrypted E-Mails to myself.

### Environment
Thunderbird: 60.8.0 linux
K9-Mail: 5.600
OpenKeyChain: 5.3
Android 8.0.0

Log:
D MessageLoaderHelper: Creating new local message loader
D MessageCryptoHelper: received progress status: 0 / 100
D MessageCryptoHelper: OpenPGP API decryptVerify result code: 0
W MessageCryptoHelper: OpenPGP API error: No encrypted data with known secret key found in stream!
D MessageLoaderHelper: Creating new decode message loader

Thank you.

**Comment by cketti** [comment]
Looks like you're encrypting the message to a key that is not on your phone or that K-9 Mail does not have access to (check "Apps > K-9 Mail" in OpenKeychain).
