### ISSUE TITLE
Support for direct share

### ISSUE THREAD

**Issue by tobiasKaminsky** [k9mail/k-9#4196]
I would like to add direct share, as found in here:
https://www.bignerdranch.com/blog/implementing-android-marshmallow-direct-share/

Then if you share a link you will also see the last recipients so that you do not have to first select K-9 and then type the first part of the name to get the recipient.

For ordering I would use the last 5 (or more) recipients.

What do you think?

**Comment by cketti** [comment]
I don't. Maybe this helps: https://www.androidpolice.com/2019/08/31/how-to-reset-your-direct-share-targets-on-android-after-messages-hijacks-them/
