### ISSUE TITLE
Sends message everytime it saves the draft of it.

### ISSUE THREAD

**Issue by lordx2** [k9mail/k-9#4199]
Hi! 

### Expected behavior
When I start compiling the message and collapse the App (for example, to go and see the translations for some words), I expect the App to save the draft of the message. And nothing more. 

### Actual behavior
Every time I start the message and then collapse the App, It would save the draft of the message PLUS (!!!) send the message to the recipient. At the end, recipient has multiple messages in his inbox, with drafts of my message, and only the last one will be the complete message. Awkward, especially when one writes to his boss...

### Steps to reproduce
1. Start writing the message.
2. Collaps the App and go to another App. You will see down the screen the message "Your message was saved as a draft" or something like this.
3. Go back and continue editing. 
4. Collapse the App again. Repeat № times.
3. Go back to the message and finish it.
4. Send the result to recipient.
5. Recipient has now in his inbox that many copies of your mail (all but one are incomplete). The number of messages will correspond to the number of times it saved the draft.

### Environment
K-9 Mail version:
5.503
Android version:
5.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Thank you in advance for solving this very old and annoying feature!!

A.

**Comment by cketti** [comment]
K-9 Mail 5.503 is a very old development snapshot. The latest stable version is 5.600. Please make sure you can reproduce the issue with that version before reporting a bug.

K-9 Mail doesn't send drafts automatically. Did you confirm with the recipient that they received your drafts in their Inbox? It's more likely that your webmail client is displaying the drafts in the conversation view together with sent and received messages and it only looks like the drafts have been sent.

**Comment by lordx2** [comment]
Perhaps you are right, thank you! But why is it so, that in https://f-droid.org there is no update for my outdated K-9 5.503?

**Comment by lordx2** [comment]
Thank you. For some reason, https://f-droid.org did not suggest me to update the outdated version of K-9 Mail, so I had to manually uninstall the old version and re-install the latest version.
