### ISSUE TITLE
open an .xlsm Office Attachement  Error

### ISSUE THREAD

**Issue by ylfcam** [k9mail/k-9#4205]
open an Attachement (**.xlsm
![Screenshot_20190930-140916_Excel](https://user-images.githubusercontent.com/55984765/65879115-a041b500-e38f-11e9-9d80-16db22ea0241.jpg)
**) in K-9 ends with an error message:
"Diese Version von Office unterstützt dieses Dateiformat nicht"
if I open the file directly in the app ([Microsoft Excel](https://play.google.com/store/apps/details?id=com.microsoft.office.excel)) everything works fine.

**Comment by cketti** [comment]
Sounds like a bug in Excel. They probably assume they can access the data like a file. But they need to use [`ContentResolver.openInputStream()`](https://developer.android.com/reference/android/content/ContentResolver.html#openInputStream(android.net.Uri)).
