### ISSUE TITLE
1000+ commits and not a new release in 13 months

### ISSUE THREAD

**Issue by terr72** [k9mail/k-9#4206]
Is there any timeline when you might consider pushing out a new release?

I know 'it's done when it's done', but considering the amount of fixed bugs and the time passed a new stable release would be much appreciated.

**Comment by cketti** [comment]
See #4195

**Comment by beerisgood** [comment]
Maybe a release with less new stuff would help in this case until new milestone is ready

Many users say that this app isnt maintained cause of no update since long time and people start to switch to other apps

**Comment by cketti** [comment]
What's left is not adding new features. It's work that is required to be able to publish an update on Google Play. Also finishing work that has been started and left the app in a half-broken state.

**Comment by ezaquarii** [comment]
@cketti I'd love to see upgraded K-9. Being android dev with professional brackground, I can take a look to see if I can help.

Where are you struggling right now?

**Comment by yoshimo** [comment]
@ezaquarii just use the Github Milestone filter and pick one of these maybe?
https://github.com/k9mail/k-9/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.800

**Comment by matteocontrini** [comment]
Is the code in a state where it can't be published as a beta either?

**Comment by violoncelloCH** [comment]
You can always build it yourself and test it :)

**Comment by ezaquarii** [comment]
@violoncelloCH We appreciate your input, but we'd like to hear the project leader opinion on this.

@cketti

**Comment by matteocontrini** [comment]
@violoncelloCH definitely, but surely an official build wouldn't be bad to have, even if half-broken 😃
