### ISSUE TITLE
Android Q Warning Message

### ISSUE THREAD

**Issue by Thomas-Ganter** [k9mail/k-9#4215]
There is a warning popup every single time I launch k-9 since I upgraded to Android Q. 
![Screenshot_20191009-063312](https://user-images.githubusercontent.com/877147/66452129-9d198980-ea5f-11e9-9166-4f749d3a57ab.jpg)

### Expected behavior
K-9 should start without this warning...

### Actual behavior
Warning. See above.

### Steps to reproduce
1. Start k-9 on Android Q
2. There is no step 2

### Environment
K-9 Mail version: 5.600

Android version: Android 10, Kernel Version 4.14.117-perf+
#1 Tue Sep 17 21:09:27 CST 2019

Account type (IMAP, POP3): irrelevant

**Comment by beerisgood** [comment]
I only got this message once.
Even if I Force close it, no new warning appear

**Comment by GrimPixel** [comment]
Please change your locale to English. Not everyone can read German.

**Comment by yoshimo** [comment]
It says the app was made for an older version of Android and you should check for an update.

**Comment by cketti** [comment]
The message should only be displayed once. Try uninstalling, then reinstalling K-9 Mail.
