### ISSUE TITLE
"Automatically" refresh folder list

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4216]
Instead of the user having to manually refresh the folder list we should automatically fetch the list of folders every time we check for new messages. That way e.g. refreshing the Inbox would also update the list of folders.

**Comment by ByteHamster** [comment]
Maybe it would be a good idea to automatically refresh the folder list when synchronizing a folder fails with a "NegativeImapResponseException: unknown folder". I just deleted a folder and (even though I knew about this issue) I refreshed the folder and somehow expected it to go away directly.

**Comment by cketti** [comment]
Closing this issue because the original suggestion was implemented with PR #4857. I created issue #4953 for ByteHamster's suggestion.
