### ISSUE TITLE
K9 doesn't push IMAP-Mails and disappearing Mail icons in taskbar

### ISSUE THREAD

**Issue by Lavater** [k9mail/k-9#4229]
Since a short time, K9 doesn't push all my Mails by IMAP. I often have to push them manually.  Beside this, Mail icons in the taskbar disappear again after a few seconds

### Actual behavior
see above

### Steps to reproduce
1. Push some Mails by IMAP

### Environment
K-9 Mail version: 5.600

Android version:
7.00 on Samsung Tab S2 an 8.00 on Samsung S7
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Obsolete because the Push implementation will be completely replaced in the next stable version.
