### ISSUE TITLE
show password

### ISSUE THREAD

**Issue by Timebo99** [k9mail/k-9#4234]
hi, i got a big problem. I use a PW manager and accidental chnged it so i  cant get into my encrypted Mail anymore/ cant restore pw. I saw theres a option for debugging / save personal data or so. I logged  it with adb but how can i find the pw if its possible? Thanks

**Comment by Timebo99** [comment]
´PS
i can access my mail on my phone but  cant saw the pw

**Comment by AlbinoDrought** [comment]
I was in the same position. I wasn't sure how to get the `Log sensitive information` option to actually log my password. I ended up popping out this: https://github.com/AlbinoDrought/imap-password-logger

Funnily enough after using that server, the app also popped up my plaintext email/password in a dialog (I guess that's the `Log sensitive information` option in action).

**Comment by cketti** [comment]
Duplicate of #3672
