### ISSUE TITLE
Pull 4233 crashes on running

### ISSUE THREAD

**Issue by Krammig** [k9mail/k-9#4238]
### Expected behavior
A clean start and run

### Actual behavior
- Two icons are installed instead of the usual one, odd. 
- App crashes after starting.  Trace attached. 

### Steps to reproduce
1. Build #4233 and run it
2. Note : No permissions are requested on Install so I had to go into Apps > Permissions and just set everything there. 

### Environment
K-9 Mail version:

Android version:  7.1  Xperia

[4233CrashTrace.txt](https://github.com/k9mail/k-9/files/3812068/4233CrashTrace.txt)

**Comment by cketti** [comment]
Thanks for reporting this.
