### ISSUE TITLE
Show recipient name/address for all messages in Sent, Drafts, and Outbox folders

### ISSUE THREAD

**Issue by nadmaga** [k9mail/k-9#4241]
In the "sent" folder the display is not consistent. Some times the recipient is shown and sometimes my name (sender) is displayed, such that it could happen, that all mails shows my own name and i don't see to who i sent the mail.

### Expected behavior
In the "sent" folder should always show the recipient name or e-mail (to:) 

### Actual behavior
If the senders e-mail is not the same as one of the configured identities in k-9, the listview shows my own name (the senders name). This can happen, if i connect to my IMAP server, where i have already sent mails with different identities. 

### Steps to reproduce
1. sent a mail with your default identity
2. in the sent folder you see correctly the name of the recipient
3. change the e-mail address of your default identity
4. now the sender name shows up in the sent items

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This works as originally intended. But I agree it's not great.

I propose we change the code to always show the recipient name/address for messages in the following special folders:
- Sent
- Drafts
- Outbox

For messages in all other folders we show the sender name/address, even if that's one of the user's identities.
