### ISSUE TITLE
Cannot add contacts

### ISSUE THREAD

**Issue by trev-dev** [k9mail/k-9#4244]
### Expected behavior
I touch a contact image/name at the top of an email, it opens up Simple Contacts and gives me the opportunity to save said contact

### Actual behavior
I get a modal pop up that says "No suitable application for this action found"

### Steps to reproduce
1. Install Simple Contacts
2. Disable as much Google/proprietary software that you can. Google Play Services still has access to contacts
3. Use K9 mail and repeat expected behavior.

### Environment
K-9 Mail version: 5.6

Android version: 8.10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/3827127/k9-log.txt)

**Comment by cketti** [comment]
Sounds like a missing feature in Simple Contacts. K-9 Mail is only using platform APIs and not talking to a contacts app in particular.

**Comment by trev-dev** [comment]
@cketti That thought had crossed my mind. I'll make an issue with them and see if I can't help get it sorted.
