### ISSUE TITLE
Show by envelope-from

### ISSUE THREAD

**Issue by mimi89999** [k9mail/k-9#4247]
### Expected behavior
K-9 Mail should show:
`from bob@example.com`
_`by eve@evil.com`_
when the address in the `envelope-from` header is different form the address in the `from` header the same way it does when a `sender` header is present.

### Actual behavior
Only the `from` header is shown in sender address.

### Steps to reproduce
1. Send an SMTP message with different `MAIL FROM` and `from` addresses.
2. Have it saved by Postfix as:
```
Received: from myserver.com
        by myserver with LMTP
        id some_id
        (envelope-from <eve@evil.com>)
        for <me@myserver.com>; Mon, 11 Nov 2019 21:11:53 +0100
From: Bob <bob@example.com>
```
3. Open the email in K-9

### Environment
K-9 Mail version: `5.600`

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Do you know any other email clients that do this? I'm not keen on parsing `Received` headers.

I imagine this will also be very annoying if you forward all emails sent to a particular address to another address.

**Comment by mimi89999** [comment]
> Do you know any other email clients that do this?

I don't. I wonder why they haven't decided to implement that.

> I imagine this will also be very annoying if you forward all emails sent to a particular address to another address.

I think that the benefit for all users will be much greater than the annoyance of having one nonsense line for that particular group and it should be possible to disable that feature.

**Comment by cketti** [comment]
That doesn't convince me. There are a lot more important issues that require attention. Closing this issue because I don't see us even just looking into this anytime soon.
