### ISSUE TITLE
Temporarily disable Push

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4253]
Our current Push (IMAP IDLE) implementation isn't working reliably with the power saving measures introduced by modern Android versions. Fixing this requires a lot of internal changes, hence time. To not hold up a (beta) release we'll temporarily disable the Push functionality.

The "Folder poll frequency" will be set to the lowest value (15 Minutes) if "Push folders" was set to anything but "None". Otherwise the old value is kept.

The "Poll folders" setting will be changed based on the combined values of "Poll folders" and "Push folders".

Poll folders | Push folders | New Poll folders
--- | --- | ---
All | All | All
All | Only 1st Class folders | All
All | 1st and 2nd Class folders | All
All | All except 2nd Class folders | All
All | None | All
Only 1st Class folders | All | All
Only 1st Class folders | Only 1st Class folders | Only 1st Class folders
Only 1st Class folders | 1st and 2nd Class folders | 1st and 2nd Class folders
Only 1st Class folders | All except 2nd Class folders | All except 2nd Class folders
Only 1st Class folders | None | Only 1st Class folders
1st and 2nd Class folders | All | All
1st and 2nd Class folders | Only 1st Class folders | 1st and 2nd Class folders
1st and 2nd Class folders | 1st and 2nd Class folders | 1st and 2nd Class folders
1st and 2nd Class folders | All except 2nd Class folders | All
1st and 2nd Class folders | None | 1st and 2nd Class folders
All except 2nd Class folders | All | All
All except 2nd Class folders | Only 1st Class folders | All except 2nd Class folders
All except 2nd Class folders | 1st and 2nd Class folders | All
All except 2nd Class folders | All except 2nd Class folders | All except 2nd Class folders
All except 2nd Class folders | None | All except 2nd Class folders
None | All | All
None | Only 1st Class folders | Only 1st Class folders
None | 1st and 2nd Class folders | 1st and 2nd Class folders
None | All except 2nd Class folders | All except 2nd Class folders
None | None | None

**Comment by beerisgood** [comment]
Just to be sure: This disable all automatic email check in the background?

**Comment by cketti** [comment]
No. "Push" is keeping a connection to the IMAP server open to be immediately notified about new messages. Periodically checking for messages (poll) will still work.
