### ISSUE TITLE
Encrypted email has ***UNCHECKED*** as subject

### ISSUE THREAD

**Issue by jmigual** [k9mail/k-9#4257]
### Expected behavior
The subject should not contain `***UNCHECKED***`

### Actual behavior
When sending an encrypted e-mail with PGP the subject of the email has `***UNCHECKED***` in front of the actual subject

### Steps to reproduce
1. Enable PGP encryption
2. Send any e-mail with `<subject>` as subject
3. When the e-mail is received the header is `***UNCHECKED*** <subject>` 

### Environment
K-9 Mail version: 5.600 (2018/09/02)

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
K-9 Mail isn't inserting `***UNCHECKED***` into the subject. Maybe it's injected by a mail server to indicate the message couldn't be checked for being spam?

**Comment by jmigual** [comment]
Okay, I'll check that. I'm using GMail as the mail receiver

**Comment by jmigual** [comment]
You're right it's not related to K-9 mail. Closing
