### ISSUE TITLE
Subfolder names do not synchronize over IMAP

### ISSUE THREAD

**Issue by DaveJarvis** [k9mail/k-9#4265]
**Overview**
There appears to be a folder name synchronization issue when mail folders are renamed outside of K9.

**Replicate**
1. Open a mail reader that is not K9 (e.g., Thunderbird or browser-based web mail client).
1. Use a mail server that is not GMail, but uses IMAP.
1. Open Inbox using mail reader.
1. Create a new folder (e.g., `Main`).
1. Create 10 sub-folders under the new folder (e.g., `Main/01`, `Main/02`, `Main/03`, etc.).
1. Open K9.
1. Refresh the folder list using K9.
1. Return to other mail reader.
1. Rename a few of the sub-folders (e.g., `Main/03` becomes `Main/03 - done`).
1. Return to K9.
1. Refresh the folders.

**Expected**
The renamed folder appears in K9 as `Main/03 - done`.

**Actual**
The folder name appears in K9 as `Main/03`.

**Debug**
To be added.

**Comment by Sodki** [comment]
I have the same issue, with no workaround. I've also noticed that the wheel at the bottom keeps spinning during the refresh folder list, no end in sight.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
