### ISSUE TITLE
notification led doesn't work.

### ISSUE THREAD

**Issue by 532910** [k9mail/k-9#4266]
Notification led doesn't work.

K9 5.6 from f-droid, LineageOS 16.0 (Android 9)

Other apps works fine.

Compare app's notification settings:
![image](https://user-images.githubusercontent.com/14617699/69103553-b8bc7a80-0a76-11ea-9812-fbf5f388667c.png)
![image](https://user-images.githubusercontent.com/14617699/69103560-c07c1f00-0a76-11ea-81e7-6aed113d0b5c.png)

**Comment by cketti** [comment]
Android changed how notifications work. K-9 Mail 5.600 doesn't have support for this new notification world. The next K-9 Mail version should be better with this.
