### ISSUE TITLE
Suggestion:  Add Archive button to mail view

### ISSUE THREAD

**Issue by khaytsus** [k9mail/k-9#4286]
My by far most used action in K9 is Archive.  Once I read an email, I almost always Archive it.  And since GMail, archive over delete is a pretty common practice.  I know on some smaller devices there might not be room for more buttons, but would it be possible to add an Archive button at the top of the screen for quicker access than Overflow->Refile->Archive ?

K-9 Mail version: 5.700

Android version: 10 (Stock)

Phone:  Pixel 3 XL

Account type: IMAP

**Comment by leezu** [comment]
Isn't there already an archive button at the top of the screen? You can configure it somewhere in the settings.

**Comment by khaytsus** [comment]
@cketti Sorry, I am an idiot.  Settings->General->Display, Visible message actions.  It's there, I just missed it.  :(
