### ISSUE TITLE
Setting "Start in Unified Inbox" is being ignored

### ISSUE THREAD

**Issue by robin523790** [k9mail/k-9#4287]
When "Start in Unified Inbox" is checked in the settings, K9 should start in the Unified Inbox. ;-) Instead the normal inbox of the first email account is being opened.

This used to work. I believe this bug was recently introduced with the removal of the accounts activity.

### Steps to reproduce
1. Have more than one account.
2. Check the "Start in Unified Inbox" setting in "General settings > Interaction".
3. Restart the app => opens the inbox of the first account instead

Suggestion: Remove this setting. Instead remember what inbox was used most recently (either a specific account or the Unified Inbox), and open this inbox again when restarting the app.

### Environment
K-9 Mail version: 5.700

Android version: various

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
I'll remove the setting. You can still start in the Unified Inbox by using the "K-9 accounts" widget on your home screen.

**Comment by jrtberlin** [comment]
@cketti There are launchers that do not support widgets or do not list widgets on the home screen. So I would opt to reopen this issue.

**Comment by cketti** [comment]
When enabled the Unified Inbox will be opened by default (once implemented). See #4306.

**Comment by jrtberlin** [comment]
@cketti that's great to hear. What about the merged folders? Is the ability to view all spam folders in one place discontinued?

**Comment by ristein** [comment]
any news here? dont know how to start in unified inbox instead of first accounts inbox.
faq is also outdated on this:
https://k9mail.app/documentation/faq.html#anchor18
