### ISSUE TITLE
Notification sound preferences are missing

### ISSUE THREAD

**Issue by khaytsus** [k9mail/k-9#4288]
The 5.700 version appears to be missing the option for notification sound.  I noticed that I wasn't getting notified, then I realized it was a little little weak "ping" noise so I looked in the preferences to fix it and I can not find the preferences for setting it anywhere.  

### Expected behavior
K9 has always had an option to set the notification sound, I would hope that isn't going away.

### Actual behavior
Default notification sound?  Not sure offhand, it's just a light little "ping" noise.

### Environment
K-9 Mail version: 5.700

Android version: Android 10 on Pixel 3 XL

Account type:  IMAP

**Comment by ByteHamster** [comment]
Hi,

The sound can be changed in Settings » Account name » Notifications » Notification settings.

**Comment by khaytsus** [comment]
> The sound can be changed in Settings » Account name » Notifications » Notification settings.

No, it can not.  You can turn on/off notifications, allow notification dot, etc..  but there is nothing for setting the notification sound there.

**Comment by cketti** [comment]
We could go directly to the notification settings for the "Messages" channel of an account. 

I'm not sure it's a good idea, though. We'd need another entry to go to the "Miscellaneous" notification settings or users will have a hard time finding that. And then we'd have to add another entry every time we add another notification group.

**Comment by khaytsus** [comment]
> Btw. you can also get to the system screen to configure an app's notification settings by long-pressing the notification, then clicking the settings icon.

Yep, I had no idea that you could change the notification sound using this system dialog.  It might be worthy of some notes in the Notifications docs, just in case.  But otherwise, this can be closed.
