### ISSUE TITLE
Re-enable start in "Unified Inbox"

### ISSUE THREAD

**Issue by theBear1** [k9mail/k-9#4294]
### Expected behavior
With 5.600 I always started in the "Unified Inbox", I almost never go to the single inboxes.
Please re-enable start in "Unified Inbox" or make it an optional choice within the settings.

### Actual behavior
With 5.700 the programs starts with the Inbox of the first account.

### Steps to reproduce
1. Open K-9 Mail v5.700

### Environment
K-9 Mail version: 5.700
Android version: 9

**Comment by khaytsus** [comment]
Someone else mentioned this; the Unified setting is still there in the settings.  The problem is that it's not honoring the setting and always goes to the Inbox.

**Comment by theBear1** [comment]
@khaytsus  you are correct, found the setting but indeed it isn't honoring the setting.

**Comment by Cactus-World** [comment]
I can confirm that the setting is ignored.

**Comment by olifre** [comment]
It seems that in a recent commit after the 5.700 release, the setting has been removed altogether:
https://github.com/k9mail/k-9/commit/d6d8ccdf6618b10cf8d6f5f1610e017af8291dbc
(sadly without any comment).

**Comment by theBear1** [comment]
That is why someone writing code for K-9 Mail needs to fix it again.

**Comment by cketti** [comment]
See #4306

**Comment by rudhu** [comment]
Hello,
Please make "re-enable start in "Unified Inbox"" possible in setting. It was why this app was really good.
Tanks and sorry for my English level...

**Comment by khaytsus** [comment]
> Hello,
> Please make "re-enable start in "Unified Inbox"" possible in setting

If Unified Inbox is enabled, it defaults to go to it.  If it's not enabled, of course it does not.  You want Unified Inbox, but not use it?

**Comment by rudhu** [comment]
Hello,
I want a unified inbox by default when I open K9 mail because I 'he got 4 mail address.
Second thing : I've got 4 mail'adress and only 2 are I' the front page..... Why not the four?
Before the 5.7 version it was really better for everything like that. The design OK but not before the use.
Thanks
Rushy.

Le 21 février 2020 13:31:55 GMT+01:00, khaytsus <notifications@github.com> a écrit :

**Comment by khaytsus** [comment]
> Hello, I want a unified inbox by default when I open K9 

Settings->General Settings->Display ->Hide Unified Inbox should be unchecked.  If you have multiple accounts, it should show the Unified Inbox by default to my understanding.  Is that not happening for you?

**Comment by rudhu** [comment]
Hello it doesn't work.
It's always opening the reception box of one of my address mail.
I unchecked the default mail address, but it's always this one....
And when I go at the home side page with the accounts , I have only Two of my Four accounts and the unifies box..which appear on the top.
Not the others, except if I checke unified box, they appear under...
Best regards.
Rudhu

Le 22 février 2020 14:24:18 GMT+01:00, khaytsus <notifications@github.com> a écrit :

**Comment by ristein** [comment]
same here.
any fix in sight?
