### ISSUE TITLE
Moving tagged messages leads to app crash

### ISSUE THREAD

**Issue by Cactus-World** [k9mail/k-9#4297]
Please search to check for 

### Expected behavior
Messages should be moved to destination folder

### Actual behavior
App crashes

### Steps to reproduce
1. Tag some messages
2. Move them to another folder
3.App crashes

### Environment
K-9 Mail version:
5.700

Android version:
Android 9
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
12-03 17:52:10.905  1519  1602 I ActivityManager: Start proc 3591:com.fsck.k9/u0a361 for service com.fsck.k9/androidx.work.impl.background.systemjob.SystemJobService
12-03 17:54:00.710  1519  1565 I ActivityManager: Process com.fsck.k9 (pid 3591) has died: cch+6CEM
12-03 17:56:22.732  1519  6579 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.MessageList bnds=[426,1028][558,1184]} from uid 10082
12-03 17:56:23.109  1519  1602 I ActivityManager: Start proc 5049:com.fsck.k9/u0a361 for activity com.fsck.k9/.activity.Search
12-03 17:56:25.629  1519  1602 I ActivityManager: Start proc 5107:com.android.chrome:sandboxed_process0/u0i978 for webview_service com.fsck.k9/org.chromium.content.app.SandboxedProcessService0
12-03 17:56:31.686  1519  3609 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.SettingsActivity} from uid 10361
12-03 17:56:35.955  1519  2400 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.general.GeneralSettingsActivity (has extras)} from uid 10361
12-03 17:56:52.051  1519  7483 I ActivityManager: START u0 {flg=0x4000000 cmp=com.fsck.k9/.activity.MessageList (has extras)} from uid 10361
12-03 17:56:59.502  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|6|null|10361
12-03 17:56:59.672  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|8|null|10361
12-03 17:56:59.686  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|6|null|10361
12-03 17:57:00.289  5049  5068 I chatty  : uid=10361(com.fsck.k9) expire 2805 lines
12-03 17:57:02.513  1519  2001 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:45.939  1519  3602 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:49.835  1519  1564 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:57.048  1519  1564 I ActivityManager: START u0 {cmp=com.fsck.k9/.activity.ChooseFolder (has extras)} from uid 10361
12-03 17:57:57.232  1519  1564 I InputDispatcher: Focus entered window: Window{c1c7438 u0 com.fsck.k9/com.fsck.k9.activity.ChooseFolder}
12-03 17:57:57.271  1519  1620 I ActivityManager: Displayed com.fsck.k9/.activity.ChooseFolder: +169ms
12-03 17:57:57.465  1519  1620 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{c04937f u0 com.fsck.k9/.activity.ChooseFolder t15500} time:153363927 diff:411 start:lukewarm|top-activity batt:59|2 mw:off|211 mem:624992|1|43|6|8 cpu:[1,1,1,1,1,1,1,1],[1900,2457]
12-03 17:58:02.952  1519  1564 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:58:03.144   977  1050 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.ChooseFolder#0
12-03 17:58:03.144   977  1050 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.ChooseFolder#0
12-03 17:58:03.174  5049  5049 E AndroidRuntime: Process: com.fsck.k9, PID: 5049
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:686)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:1524)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:2622)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:112)
12-03 17:58:03.176  1519  1564 D ActivityManager: New dropbox entry: com.fsck.k9, data_app_crash, 1f2d7461-cbe1-4a93-9bac-e1b6ba120205
12-03 17:58:03.177  1519  1564 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
12-03 17:58:03.178  5049  5068 D MessagingController: Processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy@415de0'
12-03 17:58:03.218  1519  1924 W InputDispatcher: channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-03 17:58:03.218  1519  1924 E InputDispatcher: channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Channel is unrecoverably broken and will be disposed!
12-03 17:58:03.218  1152  1152 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1575392283211.txt processName: com.fsck.k9
12-03 17:58:03.232  1519  3583 I WindowManager: WIN DEATH: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:58:03.232  1519  3583 W InputDispatcher: Attempted to unregister already unregistered input channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)'
12-03 17:58:03.251  1519  3074 I ActivityManager: Process com.fsck.k9 (pid 5049) has died: vis  +99TOP
12-03 17:58:03.257   977  1050 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#0
12-03 17:58:03.257   977  1050 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#0
12-03 17:52:10.905  1519  1602 I ActivityManager: Start proc 3591:com.fsck.k9/u0a361 for service com.fsck.k9/androidx.work.impl.background.systemjob.SystemJobService
12-03 17:54:00.710  1519  1565 I ActivityManager: Process com.fsck.k9 (pid 3591) has died: cch+6CEM
12-03 17:56:22.732  1519  6579 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.MessageList bnds=[426,1028][558,1184]} from uid 10082
12-03 17:56:23.109  1519  1602 I ActivityManager: Start proc 5049:com.fsck.k9/u0a361 for activity com.fsck.k9/.activity.Search
12-03 17:56:25.629  1519  1602 I ActivityManager: Start proc 5107:com.android.chrome:sandboxed_process0/u0i978 for webview_service com.fsck.k9/org.chromium.content.app.SandboxedProcessService0
12-03 17:56:31.686  1519  3609 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.SettingsActivity} from uid 10361
12-03 17:56:35.955  1519  2400 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.general.GeneralSettingsActivity (has extras)} from uid 10361
12-03 17:56:52.051  1519  7483 I ActivityManager: START u0 {flg=0x4000000 cmp=com.fsck.k9/.activity.MessageList (has extras)} from uid 10361
12-03 17:56:59.502  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|6|null|10361
12-03 17:56:59.672  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|8|null|10361
12-03 17:56:59.686  1519  1519 E NotificationService: Muting recently noisy 0|com.fsck.k9|6|null|10361
12-03 17:57:00.289  5049  5068 I chatty  : uid=10361(com.fsck.k9) expire 2805 lines
12-03 17:57:02.513  1519  2001 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:45.939  1519  3602 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:49.835  1519  1564 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:57:57.048  1519  1564 I ActivityManager: START u0 {cmp=com.fsck.k9/.activity.ChooseFolder (has extras)} from uid 10361
12-03 17:57:57.232  1519  1564 I InputDispatcher: Focus entered window: Window{c1c7438 u0 com.fsck.k9/com.fsck.k9.activity.ChooseFolder}
12-03 17:57:57.271  1519  1620 I ActivityManager: Displayed com.fsck.k9/.activity.ChooseFolder: +169ms
12-03 17:57:57.465  1519  1620 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{c04937f u0 com.fsck.k9/.activity.ChooseFolder t15500} time:153363927 diff:411 start:lukewarm|top-activity batt:59|2 mw:off|211 mem:624992|1|43|6|8 cpu:[1,1,1,1,1,1,1,1],[1900,2457]
12-03 17:58:02.952  1519  1564 I InputDispatcher: Focus entered window: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:58:03.144   977  1050 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.ChooseFolder#0
12-03 17:58:03.144   977  1050 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.ChooseFolder#0
12-03 17:58:03.174  5049  5049 E AndroidRuntime: Process: com.fsck.k9, PID: 5049
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:686)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:1524)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:2622)
12-03 17:58:03.174  5049  5049 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:112)
12-03 17:58:03.176  1519  1564 D ActivityManager: New dropbox entry: com.fsck.k9, data_app_crash, 1f2d7461-cbe1-4a93-9bac-e1b6ba120205
12-03 17:58:03.177  1519  1564 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
12-03 17:58:03.178  5049  5068 D MessagingController: Processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy@415de0'
12-03 17:58:03.218  1519  1924 W InputDispatcher: channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-03 17:58:03.218  1519  1924 E InputDispatcher: channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Channel is unrecoverably broken and will be disposed!
12-03 17:58:03.218  1152  1152 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1575392283211.txt processName: com.fsck.k9
12-03 17:58:03.232  1519  3583 I WindowManager: WIN DEATH: Window{1fed4e7 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
12-03 17:58:03.232  1519  3583 W InputDispatcher: Attempted to unregister already unregistered input channel '1fed4e7 com.fsck.k9/com.fsck.k9.activity.MessageList (server)'
12-03 17:58:03.251  1519  3074 I ActivityManager: Process com.fsck.k9 (pid 5049) has died: vis  +99TOP
12-03 17:58:03.257   977  1050 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#0
12-03 17:58:03.257   977  1050 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#0

**Comment by cketti** [comment]
The log seems to be missing important lines. Please create a new issue if this is still a problem with a recent beta version.
