### ISSUE TITLE
Allow keeping mail view shortcut buttons at the bottom of screen

### ISSUE THREAD

**Issue by leezu** [k9mail/k-9#4302]
### Expected behavior
With many Android phones having large screens, it's important to optimize the placement of UI elements for single handed device usage. Previously K-9's buttons for deleting, archiving etc a mail where at the bottom of the screen and can be reached easily when handling the phone with a single hand.

### Actual behavior
Now all buttons are at the top of the screen and out of reach while using a phone with a single hand.
Thank you for working on the UI update. It's great, but I hope such usability issues can be resolved.

### Steps to reproduce
1. Update K-9 mail

### Environment
K-9 Mail version: 5.7
Android version: 10

**Comment by FAUguy** [comment]
Yes, I agree, please have the icon shortcuts on the Bottom of the screen (like it use to be) as it's easier to use.

**Comment by cketti** [comment]
There are no plans to bring back the bottom bar.
