### ISSUE TITLE
Open the Unified Inbox by default

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4306]
If the Unified Inbox isn't hidden, open it by default. If it is hidden, open the default account.

Related: #4290 removed the setting "Start in Unified Inbox". There are no plans to bring back a setting for this behavior. Users wanting to open another account by default can use the "K-9 accounts" launcher shortcuts.

**Comment by mkvGuy** [comment]
This still does not work, I have the unified box unhidden yet it always goes to my first account.  Please fix

**Comment by rudhu** [comment]
Please Re-enable start in "Unified Inbox".

**Comment by rudhu** [comment]
Hello,
It still doesn't work to.....Ihave the unified box unhidden to, and it always open the first account...
I had to reinstall the precedent version 5.6 to have the unified box by default...
Please fix it.
Thanks.
