### ISSUE TITLE
Scrolling New Folder List

### ISSUE THREAD

**Issue by ANEast** [k9mail/k-9#4308]
The new 5.7 folder list for browsing to a different folder (from the left drawer) does not allow "speed scrolling".   In addition this makes the settings extremely hard to reach, having to scroll through the entire folder list before getting to settings.

Sorry if this should be a separate request, but I also wonder whether, when the folder list / accounts are displayed, the back button could just close the side bar, rather than exiting the app?

I like the new design, but this bit needs improvement, please

### Expected behaviour
A short scroll brings up the scroll bar.  The scroll bar can be grabbed and a fast scroll through the list (as is possible for longer lists of messages)

### Actual behaviour
The scroll bar cannot be grabbed and the list must be scrolled through in a standard fashion

### Environment
K-9 Mail version: 5.7
Android version: 9
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
In recent beta versions you don't have to scroll to the end of the folder list to get to settings.
Also, pressing the back button now closes the drawer instead of closing the app.
