### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by rudisten1** [k9mail/k-9#4311]
How to bring back the main screen giving you access to all your accounts instead of having to have a drop down to pick each account?

How to have back the buttons at the bottom while reading?

Could I switch back to the previous version? How?

**Comment by cketti** [comment]
> How to bring back the main screen giving you access to all your accounts instead of having to have a drop down to pick each account?

The message list screen is now the main screen. There is no longer a dedicated screen to show the list of accounts.

> How to have back the buttons at the bottom while reading?

We're not planning on bringing back the bottom bar.

> Could I switch back to the previous version? How?

Uninstall the current version and install the version you want to use.
