### ISSUE TITLE
Search folder and Global search missing

### ISSUE THREAD

**Issue by christophe-95** [k9mail/k-9#4312]
With the new UI design introduce with 5.700 we lost the ability to search folder and global search (search email in all folders)

Christophe

### Environment
K-9 Mail version: 5.700

Android version: 10

Account type: IMAP

**Comment by nomeata** [comment]
As a user with probably too many folders, not being able to open a folder by name is a relatively serious regression. I see there is a folder search in the folder management list, but from there I only reach the folder settings.

**Comment by cketti** [comment]
I created #4514 to track the global search.

Filtering folders is still possible in the "manage folders" and "choose folder" (when copying/moving messages) screens. We probably won't add this feature to the folder list in the side drawer. In fact you probably don't need to see all of your folders in the drawer. We'll probably limit the list to "important" folders and add a button to list all folders. That could lead to a separate screen showing all folders. That screen could then have a search/filter functionality like the old folder list used to have.

For now you could use folder classes to limit which folders are displayed in the drawer. The list of folders displayed in the "choose folder" screen can be different and can be configured under 'Account settings > Folders > Move/copy destination folders'.

**Comment by christophe-95** [comment]
Hi @cketti ,

The folder filtering would be useful in the side drawer when one use sub folders (long path) because there is not enough room to display the full path in this drawer, you can only see the commun part of path

Christophe

![Screenshot_20200209-111234](https://user-images.githubusercontent.com/58365372/74100410-e6bdd200-4b2e-11ea-8ed9-122694f33b8c.png)

**Comment by AlainKnaff** [comment]
> Filtering folders is still possible in the "manage folders" and "choose folder" (when copying/moving messages) screens. 

But what if you just want to browse a folder (view the messages in it)? As far as I can see, this is not possible from "manage folders", or is it? So why not just add a "search-by-foldername" icon at the top of that drawer, like is present in the move & copy dialog?
