### ISSUE TITLE
When finishing account setup display Inbox of newly added account

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4321]
Right now we just launch the `MessageList` Activity after an account has been successfully set up. This will display the default account. But we should display the Inbox of the newly added account instead.

The relevant code can be found in `AccountSetupNames.onNext()`.

Launching the message list with the default folder of a specific account is a common action and should have a static helper method. However, this is currently missing. So, the first step is to add such a method. The code to create the necessary launcher Intent can be found in e.g. `MessageList.openRealAccount()`.

**Comment by BElluu** [comment]
Hello. Can I take care of this task?

**Comment by cketti** [comment]
Sure. Go ahead.

**Comment by BElluu** [comment]
@cketti Can you assignee to me this issue? I intend to deal with this task today

**Comment by cketti** [comment]
@BElluu: We typically don't assign issues. Just start working on it.

**Comment by software2Daniel** [comment]
Study some of these careers in France, which are the best paid
https://sites.google.com/aprendizajesignificativo.org/top5francia/p%C3%A1gina-principal

**Comment by kevin839** [comment]
Si lo que necesitas es  estudiar rápidamente y de manera efectiva para aprobarlos, este post es para ti. Pick-Dream te trae los consejos necesarios para aprobar y estudiar para tus exámenes de manera rápida sencilla y eficaz. 

https://sites.google.com/aprendizajesignificativo.org/aprobar/p%C3%A1gina-principal
