### ISSUE TITLE
More sort options

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#4327]
I would like to sort my messages by unread first, then starred, then chronologically the rest, but with the new UI I can only sort either unread or starred to the top. Having to switch back and forth between those two is cumbersome.

I think users should be allowed to specify the sort precedence, e.g. sort first by unread, then by date, then by arrival time,... 

One great feature of the old UI was that it allowed to quickly show all unread and all starred emails in an account. A similar functionality is needed in the new UI for users who use the star feature to mark emails that need to be followed up.

**Comment by cketti** [comment]
The old version didn't support multiple sort criteria either. I'd rather bring back the old feature of filtering the list in a slightly modified form. See #4330.
