### ISSUE TITLE
Suggestion on account list in drawer

### ISSUE THREAD

**Issue by cgogolin** [k9mail/k-9#4328]
I think it would be great if showing the account list would not hide the manage folders and settings button and if then the state of the account list (whether it is shown or the folders) would be remembered when opening/closing the drawer.

In this way those users who use folders a lot could always see their folders, while those primarily using multiple accounts could always see their account list (similar to what the old home screen did).

**Comment by cketti** [comment]
I don't know. This feels like an edge case that makes the common case more difficult. When I switch to an account I want to see/work with the folders of that account. Having to collapse the account list is an unnecessary additional step then.
