### ISSUE TITLE
icons issues

### ISSUE THREAD

**Issue by 532910** [k9mail/k-9#4334]
v 5.700

![image](https://user-images.githubusercontent.com/14617699/70105125-0c22f100-1651-11ea-9f75-ea882bc40651.png)

**Comment by cketti** [comment]
What Android version are you using? Did you install the app from Google Play or F-Droid?

**Comment by 532910** [comment]
From F-Droid. Android 9 (LineagOS 16.0 + microG)

**Comment by ByteHamster** [comment]
Having this, too (LineageOS 16.0, master branch). Apparently, tinting the icons in the dark theme tints too much. In the light theme, I don't have those artifacts.

**Comment by cketti** [comment]
Sounds like a LineageOS issue to me. I'd be happy to include reasonable workarounds for this. But I'm not going to install LineageOS to track this issue down.

**Comment by 532910** [comment]
Is there a proof that it's a LineageOS? Have you checked it on Android 9 (not Lineage)?

**Comment by ByteHamster** [comment]
K9 already uses matching icons for the theme. We could try to call `withIconTintingEnabled(false)` on the drawer item. I will give it a try if I find the time

**Comment by ByteHamster** [comment]
Calling `withIconTintingEnabled(false)` does not help. Additionally, the behavior is quite weird: When opening the folder manager and going back to the app, the artifacts are gone for all icons that were shown in the folder manager (at least on my device). I am not able to reproduce the problem in an emulator.

**Comment by 532910** [comment]
> Additionally, the behavior is quite weird: When opening the folder manager and going back to the app, the artifacts are gone for all icons that were shown in the folder manager (at least on my device).

Artifacts are gone for only those icons, that are shown in the folder manager.
