### ISSUE TITLE
Enable free user defined polling times or reduce the 15 min back to 1 min

### ISSUE THREAD

**Issue by Tekener72** [k9mail/k-9#4336]
[Enhancement] Please reduce polling times from pop server, 15 minutes is way too long.

Please don't force users to not use quick pollings. I am using 5.600 perfectly fine since many years with 1 min polling on my own mail server while having many gigabytes of free mobile traffic which I never used more than 70% at all.

Please enable free user defined poll times (by confirming "usage at own risk" or something like this) rather than the given ones starting at 15 min.

5.600: polling times start at 1 min, which perfectly fine.

5:700: polling times start at 15 min. which is just too long

**Comment by ByteHamster** [comment]
This is a technical restriction. Android's WorkManager (that we need to support new Android versions) allows a minimum interval of 15 minutes.

**Comment by cketti** [comment]
What ByteHamster said.

Also, you should move off of POP3. It doesn't work well for syncing messages. We'll probably remove support for it in a future release.

**Comment by dwrl** [comment]
Sorry to reanimate this, but I too am looking for such an option, 15 minutes is quite long.
Not an android developer here, but maybe there is some other, less constraining way of implementation which e.g. is used by other mail clients and instant messengers?

**Comment by TheBudda** [comment]
How can this be, and I quote "This is a technical restriction. Android's WorkManager (that we need to support new Android versions) allows a minimum interval of 15 minutes."

When FairEmail and Gmail gives me a notification of new mail in less than a second. Thunderbird takes 15 minutes to send a notification that I got new mail

**Comment by ByteHamster** [comment]
Notifications in less than one second are supported in Thunderbird. Just enable push/IMAP IDLE. Instead of repeated checks every x minutes (polling), you then get the emails immediately (push)
