### ISSUE TITLE
[ 5.701 ] unfortunately, k-9 mail has stopped

### ISSUE THREAD

**Issue by leela52452** [k9mail/k-9#4337]
### Expected behavior
open app

### Actual behavior
displays message `unfortunately, k-9 mail has stopped`

### Steps to reproduce
1. tap app shortcut or open in app manager

### Environment
K-9 Mail version: 5.701 [ github apk ] [ updated from 5.700 ]

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
dont have access to desktop or laptop

**Comment by cketti** [comment]
Without a debug log this issue is not actionable.

**Comment by leela52452** [comment]
i will reopen if i am able to retrieve debug log, thank you.
