### ISSUE TITLE
[ 5.701 ] after creation of account, unfortunately, k-9 mail has stopped

### ISSUE THREAD

**Issue by leela52452** [k9mail/k-9#4338]
### Expected behavior
open app

### Actual behavior
displays message `unfortunately, k-9 mail has stopped`

### Steps to reproduce
1. install using 5.701 apk downloaded from github
2. create an account IMAP account [ i created using settings from my [mail provider](https://www.autistici.org/docs/mail/connectionparms)
3. tap OK after entering acc name and display name

### Environment
K-9 Mail version: 5.701

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
dont have access to desktop or laptop

**Comment by HagenTronje** [comment]
Same here

K-9 Mail version: 5.701 from GitHub

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by HagenTronje** [comment]
> Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Sorry!
I am dependent on a working MUA on my phone so i re-installed k-9 V5.6 immediately after i recognized that V5.701 failed to work.
