### ISSUE TITLE
Wrong email address shown on inbox/folders

### ISSUE THREAD

**Issue by jlvermeulen** [k9mail/k-9#4344]
The email address shown at the top of the inbox or other folders in Android is incorrect.

### Expected behavior
It should show my email address, jordi@&lt;domain>.nl.

### Actual behavior
It shows a modified version of my email address, joardi@&lt;domain>.nl. The correct address is shown in the "Accounts" view, but once I enter the account, it shows the modified version.

### Steps to reproduce
1. Open inbox.

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type: IMAP

There are no errors, so I'm not sure if attaching a debug log is useful. Either way, I don't currently have access to the tools to retrieve the log.

**Comment by cketti** [comment]
This might be a temporary display issue. Make sure the email address under 'Account settings > Sending mail > Composition defaults' is correct.

The relevant code was changed a lot and this probably will no longer be an issue in the next stable version. If you're feeling adventurous you could try the latest beta version 5.701.
