### ISSUE TITLE
Feature Request: Direct Email Widget

### ISSUE THREAD

**Issue by lemmy** [k9mail/k-9#4346]
Similar to the "direct messages" widget for SMS, it would be a huge time saver if a (1x1) k9 mail widget would open a new email addressed to a predefined contact.  In other words, instead of:

1) Open k9 mail app
2) Press new mail icon
3) Type address of contact
4) Select contact
5) Select "Subject" line
6) Type "Subject"
7) ...

reduce it to:

1) Click "Direct Email" widget
2) Type "Subject"
3) ...

**Comment by fabienli** [comment]
hello lemmy,
as a workaround, until this may be integrated in k9 app, you could do the following: 
  - download “Activity Launcher“ on fdroid: https://f-droid.org/app/de.szalkowski.activitylauncher
  - use it to launch k9's mail composer:
![SmartSelect_20191215-144950_Activity Launcher](https://user-images.githubusercontent.com/2265539/70863673-d59b7f00-1f4a-11ea-8883-7dfa63ec09aa.jpg)
  - long click on it to find the “shortcut“ option
![SmartSelect_20191215-145023_Activity Launcher](https://user-images.githubusercontent.com/2265539/70863697-fe237900-1f4a-11ea-9957-df371468e44a.jpg)
  - then you add it as a 1x1 widget

it seems that this is doing exactly what you're looking for.
cheers, 
Fabien

**Comment by lemmy** [comment]
@fabienli Thanks for the suggestion.  Might I be doing something wrong because I can't seem to get Activity Launcher to open k9's composer with To: set to a particular contact?

**Comment by fabienli** [comment]
you're right, I can't manage to get a pre-filled "To:" field.
So, this is not a full workaround, you're just saving the first initial steps.

**Comment by cketti** [comment]
There are a ton of apps that can create shortcuts for `mailto:` URIs. Such an URI can be used to open an email app with fields pre-populated. A useful search term for the Play store might be "email template".
