### ISSUE TITLE
How do I downgrade without need to re-enter password for all emails and how to add new account?

### ISSUE THREAD

**Issue by dausruddin** [k9mail/k-9#4349]
Hi. I am currently on latest K-9 (5.701). I have more than ~25 email accounts and it is hard to manage them all when the dedicated page where we no longer can see unread and favorite badge next to the email. I had to go into every single account to check for them. Unified inbox is too confusing because everything stuffed in there. 

So how do I downgrade, without having to re-enter password for all accounts? Exporting and importing the settings require the password to be entered again. I don't save their password and will need to regenerate a new one, that is not too convenient for ~25 email accounts.

I also can't find a way to add new account in this new version. How do I actually do that?

**Comment by leela52452** [comment]
@dausruddin 
i have always assumed that an app can't be downgraded. however, it seems i am wrong. please proceed with caution. [How to Downgrade an App on Android](https://www.xda-developers.com/downgrade-an-app-android-no-root/)

**Comment by ByteHamster** [comment]
K9 can not be downgraded because that would lead to an inconsistent database. You need to uninstall and then get the old version from the releases page here on GitHub.

> So how do I downgrade, without having to re-enter password for all accounts?

Not possible without rooting your device.

> I don't save their password and will need to regenerate a new one

Then it's probably a good time to get a password manager and save the regenerated passwords.

**Comment by dausruddin** [comment]
Thanks @leela52452 maybe I'll try that later.

**Comment by dausruddin** [comment]
@ByteHamster Fortunately I am rooted! Can you point me towards the right direction?
 I actually tried Titanium Backup to restore the data on old K-9 version but K-9 still asking me to set it up like a new installed app.

I used Keepass and recently moved to Bitwarden. I have all password saved except for these emails I am using in K-9. Basically I generate a password, use it in K-9, forget it.
It is because I had no problem using K-9 for years. That is my mistake and I hope I have them saved.

**Comment by ByteHamster** [comment]
> i have always assumed that an app can't be downgraded. however, it seems i am wrong. please proceed with caution.

This will not work for K9. I went through upgrade/downgrade multiple times while creating a pull request and had to delete the database.

> Fortunately I am rooted! Can you point me towards the right direction?

Not really. This will be quite a lot of work. My approach would be to attach a debugger to the process (you need root if the app is a release build) and extract the passwords from memory when connecting to the server. I did that to other apps already but this will definitely be a lot of work.

**Comment by cketti** [comment]
Downgrading is not supported. Exporting settings on the new version, then importing on an old version might work. But it's not a supported use case either.
