### ISSUE TITLE
Mismatch between folders in drawer and folder manager

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#4350]
The outbox folder has different icons in different lists. Additionally, the order in drawer and folder manager is different. See screenshots below. 

Drawer:
![Screenshot_20191209-181453_K-9_Mail](https://user-images.githubusercontent.com/5811634/70457447-75bb5900-1ab0-11ea-957a-e5c02e8b3b40.png)

Folder manager:
![Screenshot_20191209-181500_K-9_Mail](https://user-images.githubusercontent.com/5811634/70457458-7e139400-1ab0-11ea-97e7-f8385bb986d0.png)

### Environment
K-9 Mail version: master

Android version: LineageOS 16.0

**Comment by cketti** [comment]
I was leaving #3750 open as a reminder to fix this. But now we can use this issue.
