### ISSUE TITLE
Remove "Wrap long folder names" setting

### ISSUE THREAD

**Issue by ouafnico** [k9mail/k-9#4351]
### Expected behavior
The following option seems to do not work on general options:
- wrap long folder names

### Actual behavior
Long folder still shown in uniq line.

### Environment
K-9 Mail version: 5.701

Android version: 10 (Pixel 2)

Account type (IMAP, POP3, WebDAV/Exchange): Multiple IMAP

**Comment by cketti** [comment]
The setting currently only applies to the "Manage folders" screen. But the plan is to get rid of it.
