### ISSUE TITLE
Inbox regularly loses cache, or empties itself before refilling with the message list

### ISSUE THREAD

**Issue by madduck** [k9mail/k-9#4354]
### Expected behavior
Opening the inbox, I expect to see the list of messages contained therein from when I last visited the inbox. Then, a sync modifies the list, if there were changes on the server.

### Actual behavior
Regularly, the inbox appears empty, and I need to swipe down to pull the list of messages from the server anew.

I've also experienced the inbox emptying itself, i.e. messages disappearing one after another, until it's empty, then filling up again when I swipe down.

This seems to be confined to the inbox only. So far I've not experienced it in another folder.

I have been able to record a screencast of this, but I can't really share it until I find a way to blur the contents. The same applies to the log file, which I was able to capture. I do not want to share it publicly, because the list of folders I maintain is private information. Can share over email if promised to keep confidential.

### Steps to reproduce
1. Start the app, open Inbox
2. Watch as messages disappear, might require a swipe-down
3. Swipe-down to make messages re-appear.

### Environment
K-9 Mail version: 5.700

Android version: 8

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Sounds like a duplicate of #4296. Please make sure to test with 5.701.

**Comment by Diapolo** [comment]
I'm observing the same bug and spent nearly 3 GB mobile data, before I realized there is something wrong :-/. Well I'm using F-Droid and hope for a release of 5.701 there, when will it be available?

**Comment by madduck** [comment]
@Diapolo you can download 5.701 from this site and install it directly. It does fix the problem. Thanks, @cketti.

**Comment by Diapolo** [comment]
I'm not allowed to install the webseite apk ontop the F-Droid one...

**Comment by madduck** [comment]
@Diapolo can you use `adb install -r`?

**Comment by cketti** [comment]
F-Droid uses a different signing key. Switching from the official version to the F-Droid version or vice versa won't work without uninstalling.

Please don't use the issue tracker as support forum. Use the [mailing list](http://groups.google.com/group/k-9-mail) instead.
