### ISSUE TITLE
Line breaks are deleted from mails saved as drafts

### ISSUE THREAD

**Issue by PCigales** [k9mail/k-9#4355]
First, thank you very much for bringing us this new version of K9-Mail, I like the new UI even if there are some problems I will report in parallel.
This issue deals with line breaks being deleted in mails saved as drafts, and then opened again.

### Expected behavior
When a mail in writing is saved as a draft, and then, reopened, its content should look like it was before being closed, and in particular, all line breaks should remain.

### Actual behavior
All the line breaks are deleted, the sentences are one after the other without any separation.

### Steps to reproduce
1. Start writing a mail
2. Save it as a draft
3. Go to the drafts folder
4. Open the mail
5. Cry...

### Environment
K-9 Mail version: 5.701

Android version: 8 (Galaxy A8)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: no error

**Comment by PCigales** [comment]
I think I understood what is happening, this issue is the cumulative result of two issues.

The first one is that when a mail being written is saved as draft, the body of the mail is turned into a quoted message (if I try to edit it from another mail client, for example the webmail of my internet provider, I cannot change the text previously entered, as it is shown as an embedded old mail).

The second one is that each K9-mail removes all the break lines of quoted mails rather than just the excessive ones; To reproduce it, forward any mail and press the edit command (the pencil) of this included mail, then save the whole mail as draft. Open it again, and save it again as draft. Reopen it, and you will find that line breaks have been totally removed from the mail (even the one after the header "original message").

Therefore, I think that there are two bugs to fix, as the two of them are annoying, rather than just one.

**Comment by cketti** [comment]
See #4685
