### ISSUE TITLE
K-9 fails to sync new messages with the same UID in different folders

### ISSUE THREAD

**Issue by mruwek** [k9mail/k-9#4364]
I've reported this first on IRC, but there wasn't any serious response so I'll post it also here.

### Expected behavior
K-9 should sync messages in each folder regardless of whether or not they have the same UID.
UID alone does not point to unique message on the account. 

### Actual behavior
K-9 syncs only messages with unique UID.

### Steps to reproduce
1. Create 3 fresh labels in your Gmail account (also reproduced with regular IMAP Dovecot installation): `k9-uid0`, `k9-uid1`, `k9-uid2`.
2. Create 3 content filters in Gmail that will use previously created labels (for instance: if message contains "k9-test0" put it in `k9-uid0` etc.)
3. Send 3 messages, each prepared to land in different label/folder.
4. Sync folders in order: `k9-uid0`, `k9-uid1`, `k9-uid2`.
5. Send another 3 messages, each prepared to land in different label/folder
6. Sync folders in order: `k9-uid2`, `k9-uid1`, `k9-uid0`.
7. RESULTS: `k9-uid0` and `k-uid2` each shows one message, but `k9-uid1` is empty
8. Expected results: each folder should have 2 messages.

### Environment
K-9 Mail version: 5.701

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): GMAIL, also Dovecot on Centos

### Screenshots
[Gmail INBOX](https://user-images.githubusercontent.com/500710/70750238-4e71bf80-1d2e-11ea-9642-f54b49aede56.png)
[k9-uid0](https://user-images.githubusercontent.com/500710/70750353-8ed13d80-1d2e-11ea-9586-2444a1727737.png)
[k9-uid1](https://user-images.githubusercontent.com/500710/70750416-ac060c00-1d2e-11ea-810c-44e4470b9908.png)
[k9-uid2](https://user-images.githubusercontent.com/500710/70750444-baecbe80-1d2e-11ea-9d78-19c70c27117d.png)

### Logs
1. Logcat filtered with: `:%g!/Imap\|synchronizeMailbox/d` in Vim: [k9-uid-collision-log.txt](https://github.com/k9mail/k-9/files/3957922/k9-uid-collision-log.txt)
2. Raw Logcat: [k9-uid-collision-raw.txt](https://github.com/k9mail/k-9/files/3957936/k9-uid-collision-raw.txt)

**Comment by mruwek** [comment]
Also cfr: https://stackoverflow.com/a/23300921

**Comment by cketti** [comment]
Thanks for tracking down the cause of this issue :heart:
