### ISSUE TITLE
E-mail fetching (IMAP) does not work reliable anymore

### ISSUE THREAD

**Issue by doak** [k9mail/k-9#4373]
### Expected behavior
Updating an IMAP folder should load unreceived emails. An already up-to-date folder should finish this operation in short time.

### Actual behavior
Actual e-mails are not fetched reliable. In fact it seems reloading a folder seems to purge the internal data first. A subsequent update will reload the whole stuff again (and even show notifications for unread messages again).
This is a regression, it worked seamlessly with _v5.6xx_.

### Steps to reproduce
1. Go into some folder of an IMAP account with several (e.g. 50) emails in it.
2. Pull list from top to down to update folder.
3. After every second update the folder appears empty (in fact the messages disappear each after each other). A subsequent update will re-download every message again.

Probably the following settings are important:
  * _Local folder size_ = _all messages_
  * _Sync messages from_ = _any time (no limit)_
To be more precise: the bug **does not** happen if _Local folder size_ is set to _25 messages_, _250 messages_ or even _10000 messages_ for instance. The folder contains 137 messages total, 17 are unread.

### Environment
* K-9 Mail version: _v5.700_ (current _F-Droid_ build)
  (I saw some issues/bugfixes for _v5.702_, as far I can tell this behaviour has not been addressed. But obvioulsly I did not test a more current version.)
* Android version: _Replicant 6.0.1_
* Account type (IMAP, POP3, WebDAV/Exchange): _IMAP_
* Logs: [k9-log.txt](https://github.com/k9mail/k-9/files/3963700/k9-log.txt) (I've stripped all sensitive data.)

**Comment by cketti** [comment]
5.7xx versions are beta versions. Please always make sure to test the latest version before reporting a bug.
This issue sounds like a duplicate of #4296 which was fixed in 5.701.

**Comment by doak** [comment]
@cketti, yes indeed. Sorry for the noise.
