### ISSUE TITLE
Indicate account name in menu

### ISSUE THREAD

**Issue by mahdi1234** [k9mail/k-9#4380]
With 5.701 from f-droid.

Have three accounts setup, each has different color (fine), however it's not really clear which is which.

![k9_acconts_list](https://user-images.githubusercontent.com/1097047/70860264-8c7e0780-1f17-11ea-89c2-f5f514a55987.png)

It'd be great to somehow indicated account name in the graphics, I could think of:

- have a bold letter showing fist letter of the account name inside the icon instead of "contact" picture
- small text below each icon showing account name

**Comment by cketti** [comment]
That's why there are different colors. If that's not enough for you, you can either create contacts and use distinct contact pictures or expand the account list and see the account names and email addresses.

**Comment by mahdi1234** [comment]
@cketti Could you give me more info on "you can either create contacts and use distinct contact pictures" I'm unable to find how to assign contact to email account? thanks

**Comment by cketti** [comment]
Using your Contacts app create contacts for the sender email addresses of your accounts. Add photos to those contacts and they should be displayed in K-9 Mail instead of the generic person icon.
