### ISSUE TITLE
Add for K-9 Mail show email address without email account

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#4381]
Hi,
add for K-9 Mail than email address viewer.

This means the app can display email address + copy the email address without setting up an email account. Similar to Thunderbird on the desktop.

Here you can test for yourself that K-9 Mail does not support it.

Solid Explorer: https://play.google.com/store/apps/details?id=pl.solidexplorer2

1. Open the Solid Explorer app. Then open the sidebar. Then tap 3 points -> About Solid Explorer -> Send bug report -> K-9 Mail

2. Now the K-9 Mail app is opened for the first time after the installation. But it doesn't show me an email address.

**Comment by cketti** [comment]
K-9 Mail only enables the component to compose a new message when an account has been set up. So it shouldn't be shown as an option when no account has been set up. If that's not working it might be a bug in your Android version.
