### ISSUE TITLE
some bugs of various type on 5.7xx version

### ISSUE THREAD

**Issue by sviluppoSoftware** [k9mail/k-9#4383]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
1) this is an old bug but not yet fixed even in 5.7xx version, Server search allows to search the messages on imap server. The list of found messages returned. But message's body does not shown when "Sync messages from" is defined and the date of the message is out of range. 

2) with dark theme enable, navigate in "manage folders" section when tap on a folder, to manage the folder's option, sometimes  the dark theme is disable or it's too dark (see screenshot)

3) i'm not sure if this is a bug, when enable or disable "combined incoming mail" to make the change effective I must close and reopen the app

4)in the 5.600 version it was possible to have all the email accounts as the initial screen of the app, and pressing the button to check if I had received new emails it checked all the folders present in each account not only of the inbox, I tried to set the folders that interest me as first class for: the visualization class, folder recovery class, push notification class. Unfortunately it didn't work.

### Environment
K-9 Mail version: 5.702 5.703 5.704

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

![dark theme bug](https://user-images.githubusercontent.com/14260912/70863959-dbdf2a80-1f4d-11ea-9481-5694dda3cc52.jpg)

**Comment by cketti** [comment]
Please create one issue per bug (make sure there doesn't already exist one). Most of this should be fixed in recent beta versions.
