### ISSUE TITLE
Is K9Mail still being developed & supported or dead?

### ISSUE THREAD

**Issue by Moondoggy51** [k9mail/k-9#4391]
I noticed that K9Mail on my cell phone has not been updated since September 2, 2018 and was wondering if this app is still being developed and supported or is it dead?  If dead are there any forks in the development where other developers have picked up this app and are supporting their version?

**Comment by cketti** [comment]
You found the issue tracker. Why didn't you look around a little bit before creating an issue? Maybe one of these pages could have answered your question:
- https://github.com/k9mail/k-9/pulse/monthly 
- https://github.com/k9mail/k-9/releases
