### ISSUE TITLE
IMAP/SMTP SSL handshake fails when mail server is hardened

### ISSUE THREAD

**Issue by bilogic** [k9mail/k-9#4406]
### Expected behavior
Connect successfully to hardened IMAP and SMTP server

### Actual behavior
Unable to handshake with hardened IMAP and SMTP server

### Steps to reproduce
1. Server offers only TLS1.2 
2. Server offers only Strong encryption (AEAD ciphers)

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP and SMTP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Initally, I thought it might have to do with Android, however there are other Android mail clients that work with the hardened server, thus I can only conclude that the issue lies somewhere in K9 Mail.

# Dovecot's config
- Common
```
ssl_protocols = TLSv1.2
ssl_dh_parameters_length = 2048
```
- Unhardened (K9 Mail can connect):
```ssl_cipher_list = ALL:!aNULL:!eNULL:!SSLv2:!RC4:!MD5:!DES:!EXP:!SEED:!IDEA:!3DES```
- Hardened (K9 Mail cannot connect):
```ssl_cipher_list = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384```

**Comment by cketti** [comment]
K-9 Mail uses Android's TLS implementation. Make sure your Android version supports the ciphers you configure on your server.

See https://developer.android.com/reference/javax/net/ssl/SSLEngine
