### ISSUE TITLE
[5.70x] POP3 e-mail stops checking/loading

### ISSUE THREAD

**Issue by gena01** [k9mail/k-9#4408]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

K9 should check and fetch e-mails at configured/scheduled interval.

### Actual behavior
Tell us what happens instead

No new e-mail is loaded at all unless i manually force a refresh (pull down).

### Steps to reproduce
1. Leave k9 running in the background
2.  I can see e-mails showing up on the laptop/desktop.
3. No new e-mails show up for hours? unless I manually force a refresh.

### Environment
K-9 Mail version: 5.703 (looks like this broke in the 5.7 beta?)

Android version: 9.0 Pie

Account type (IMAP, POP3, WebDAV/Exchange): pop3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by ksga** [comment]
+1
Only using IMAP (Gmail and private domain on Zoho)

**Comment by cketti** [comment]
The issue is a bug in the initial configuration of the Inbox (and other special folders). Go to 'Manage folders', select the Inbox, then set 'Folder poll class' to '1st Class'.

**Comment by ksga** [comment]
> The issue is a bug in the initial configuration of the Inbox (and other special folders). Go to 'Manage folders', select the Inbox, then set 'Folder poll class' to '1st Class'.

Solved it for me - thanks :)
