### ISSUE TITLE
When deleting an opened message from within K-9 closes completely 

### ISSUE THREAD

**Issue by hakaz** [k9mail/k-9#4413]
### Expected behavior
Deleting a message from within should delete this message and the next message should open  

### Actual behavior
Deleting a message from within closes K-9 completely 

### Steps to reproduce
1. Open K-9
2. Open Folder e.g. Inbox of an account 
3. Open message in Inbox
4. Deleting opened message via top button from within

### Environment
K-9 Mail version: 5.703

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by cketti** [comment]
No additional information provided.
