### ISSUE TITLE
Don't use full screen editing view in landscape mode

### ISSUE THREAD

**Issue by githubomane** [k9mail/k-9#4415]
### Expected behavior
When writing an email on my tablet in landscape mode, the keyboard should refrain from going to full screen, allowing me to see the full compose screen. 

### Actual behavior
When writing an email on my tablet in landscape mode, the software keyboard switches to full screen, showing only the currently active input field. 

As far as I could determine, whether to go to full screen keyboard in landscape or not, is set by the app, not the keyboard (though the setting could presumably be overwritten by the keyboard).

I therefore suggest adding an option to k9 to disable the full screen keyboard in landscape mode. Maybe even change the standard setting depending on the screen size or some other method to differentiate between phones and tablets. 

### Environment
K-9 Mail version: 5.703
Android version: 9

**Comment by realmain** [comment]
Please update your app to v5.700 or v5.703 (Major UI update). v5.600 is from 2018.

**Comment by basilgello** [comment]
K-9 app has nothing to do with keyboard settings. For example, on my tablet I use *old* A.I.Type Float & Split keyboard (and keep it off Internet after I downloaded the necessary languages for it using LineageOS Privacy Guard). Newer A.I.Type keyboards were altered with privacy-intrusive SDK.

Looks it is no more available for purchase via Google Play but sites like 4PDA does have its clean installer.

**Comment by cketti** [comment]
I'm fine with changing the default behavior. This shouldn't be a setting.

The behavior can be changed by using `android:imeOptions="flagNoExtractUi"` on the text input views in `message_compose_content.xml`.

**Comment by Ebencarl** [comment]
Nice hub
