### ISSUE TITLE
Functionality vs Style on the left hand drawer.

### ISSUE THREAD

**Issue by jpopovitch** [k9mail/k-9#4417]
Is it really necessary for me to see my name, my avatar, my favorite color (stylishly textured for me), and my email address, at the expense of easily seeing the unread count of 3 folders now pushed further down the left hand drawer? 

### Expected behavior
Ideally I would like to see my email folders and their unread count, rather than my own name, email address, etc.

### Actual behavior
I lose easy visibility to folders that are now pushed further down the list.

### Environment
K-9 Mail version: 5.703

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment]
While there was a time when you could configure K-9 Mail to display as much information as possible in as little space as possible, this is no longer something the app supports.
That being said, we're open to concrete suggestions (preferably with design mockups) on how the account switcher could be reduced in size while still being easy to use.

**Comment by jpopovitch** [comment]
90% of the top left drawer is NOT related to the account switcher, rather it is Material Design fluff.
