### ISSUE TITLE
Standard Encryption 

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#4425]
Is there a way to switch on encryption under certain conditions? There is a text that describes that encryption is not automatically switched on when it is possible, but is there a simple recipe like a cooking book entry how to automate this?

**Comment by cketti** [comment]
See https://autocrypt.org/ for details on when encryption is used automatically and when you can enable it manually.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
