### ISSUE TITLE
unable to deactivate k9-mail

### ISSUE THREAD

**Issue by promeneur** [k9mail/k-9#4441]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior

k9-mail deactivated
k9-mail does not get new mails

### Actual behavior

k9-mail is not deactivated
k9-mail does get new mails.

### Steps to reproduce
1. In k9 in an account settings i set folder polling frequency to "never".

In the past this deactivates k9-mail for the account.

I also tried to deactivate a k9-mail account in android account settings but there is no k9-mail account.

### Environment
K-9 Mail version: 5.600

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Make sure to disable Polling **and** Push to disable automatic mail checks.

**Comment by promeneur** [comment]
> Make sure to disable Polling **and** Push to disable automatic mail checks.

this works.

thanks
