### ISSUE TITLE
[Enhancement] Add option to apply all settings made in the main account to all other accounts

### ISSUE THREAD

**Issue by MarkovkaMartin** [k9mail/k-9#4456]
If you prefer always specific options in your main inbox which are different from the default options, then it would be easier to apply all made settings once in your main account to all of your other accounts instead of changing every single setting in your 2nd, 3rd, 4th, ... account, to ensure, that they have exactly the same settings like in your main account.

A button or something like that would be cool.

**Comment by cketti** [comment]
This is not something we're going to add. 

If you find yourself having to frequently change a setting in all accounts, maybe we need to do things differently. In that case please let us know what your use case is exactly.
If you often switch devices and set up accounts again and again, consider using the import/export functionality. You should only have to set up and configure an account once.
