### ISSUE TITLE
Using K9 on a Unihertz Titan with a square-ish screen, causes the controls at the bottom of the screen to be missing.

### ISSUE THREAD

**Issue by fishsoupisgood** [k9mail/k-9#4457]
### Expected behavior
I would expect the app to fill the screen and the buttons at the bottom to be visible like this:
![expected](https://user-images.githubusercontent.com/19636462/72663391-4a4e5700-39ea-11ea-8114-c21642b09a1e.png)

### Actual behavior
The app scales as if it were on a non square screen and so the bottom of the app is not visible here's a screen shot:
![observed](https://user-images.githubusercontent.com/19636462/72663390-43274900-39ea-11ea-993f-9d9338a397ab.png)

### Steps to reproduce
1. Start K9 on a device with a square-ish screen (in this case the unihertz titan has 1430x1438)

### Environment
K-9 Mail version: 5.600

Android version: 9.0

Account type (IMAP, POP3, WebDAV/Exchange): Imap (but likely not relevant)

Logs: 
[k9-log.txt](https://github.com/k9mail/k-9/files/4080612/k9-log.txt)

**Comment by cketti** [comment]
We're getting rid of the bottom bar in the new version. See #4377.

**Comment by fishsoupisgood** [comment]
How does that help me see the information that has been cut off the bottom of the screen?

**Comment by cketti** [comment]
The actions that aren't displayed can be found in the overflow menu (the icon with the tree dots).

**Comment by fishsoupisgood** [comment]
I still don't understand how this is a resolution to the problem that the bottom of the screen is cut off?

**Comment by cketti** [comment]
The bottom is not cut off. The layout is just different. The actions can be found at the top and in the overflow menu. This is not a bug. But it is confusing. Which is why the next version of K-9 Mail will always display the actions at the top.
