### ISSUE TITLE
Task bar on the bottom, one hand operation.

### ISSUE THREAD

**Issue by ael7ux** [k9mail/k-9#4464]
Task bar used to be on the bottom of the screen and that worked perfectly for one hand operation. Now it is difficult to get to the NEXT or DELETE buttons with a thumb and hold the phone with the same hand.

I get that the UI was changed to look a like gmail and other big brands, but difference is just the reason I use K9 instead of them.
Just a tought for des gners minds,

Cheers
Marko

**Comment by cketti** [comment]
The bottom bar is not coming back in its previous form. However, I'm aware that this makes one-handed operation difficult on large phones. Finding ways to make the app easier to use with one hand is on the roadmap.
