### ISSUE TITLE
Don't send mails. The mails stays in the outbox

### ISSUE THREAD

**Issue by tXambe** [k9mail/k-9#4470]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Don't send mails. The mails stays in the outbox

### Actual behavior
Don't send mails. The mails stays in the outbox
### Steps to reproduce
1. I send at mail without attachment and stays in the outbox and never send
2.
3.

### Environment
K-9 Mail version:
5.600
Android version:
7.0
Account type (IMAP, POP3, WebDAV/Exchange):
imap.gmail.com
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Make sure your outgoing server settings are correct. Go to 'Account settings > Sending mail > Outgoing server' and press the 'Next' button. There's already issue #3766 for the missing feature of showing a notification when sending of a message has failed.

If this doesn't solve your problem, please record a debug log when trying to send a message and attach the file to this issue. I'll then reopen it.
