### ISSUE TITLE
incremental ui improvements after 5.7.x overhaul

### ISSUE THREAD

**Issue by brainchild0** [k9mail/k-9#4479]
After trying the version 5.7.4 preview, I wish to congratulate the contributors who overhauled the graphical interface into a *Material Design* feel for the 5.7 release.

Whereas K-9 had long been functionally superior to alternatives, the replacement of the previous, outdated user interface places the application in all respects decidedly in the top class of Android mail readers.

I wanted to suggest a handful of incremental improvements that would make user interaction slightly more solid and smooth.

Each suggestion can be taken or rejected separately. It is not required to accept or to reject the entire list as a single decision.

The suggestions are as follows:

- In the message view:
  - Make header more compact.  
  - Remove all-capital text for *SHOW PICTURES* button, and optimize consumption of vertical space by this button when shown.
  - Put buttons in toolbar only for *delete*, *reply sender*, *reply all*, and *forward*, as these actions are the most common after reading a message. 
  - Although navigation to next and previous messages are also common, these actions are easier and more familiar by swiping.  Support these gestures, and free space on the toolbar by removing the icons for these actions. 
- In the folder view:
  - When no items are selected, make long press merely select an item, without triggering a popup menu. Specific actions can later be chosen by menu.
  - Make single press on selected item remove selection from that item.
  - ~Shade background of unread messages, since bold is often hard to distinguish, depending on the type size and family, and physical display.~ (Appears to be configurable using global *Change colour when read*.  Perhaps the shading behavior should be the default.)
  - Display date in more intelligent format, for example, time of day in case of same day, or day of week in case of earlier day within past week.
- In the account sidebar:
  - Use less glitzy graphics for background behind account title.
  - Arrange nested folders in folding tree, rather than as flat list with nested folders displayed by full path.
- Use more appropriate animations for changing screens. For example, currently transitions between folder view and message view are a horizontal slide, which is more appropriate for transitions between items of equal status, such as adjacent items in the same list. In a message view, the _delete_ or _back_ actions could move to the folder view with an animation that more directly captures the relationship of returning to a previously-visited place.
- Permit fine-grained control of notification behavior from inside application (as well as through system menus).  See #4482.

---

Note: This issue topic intends to catalog a variety of usability nuances each too small to require a separate topic. Please keep it clean and focused, creating separate  topics to discuss major design changes.

**Comment by azrdev** [comment]
Also, a view showing "All Messages" of an account (or all accounts? or both?) would be helpful (in particular for accounts with lots of folders, until #630 is implemented). The documentation mentions such a view, I suspect it was removed with v5.7

**Comment by cketti** [comment]
5.7xx is not exactly the result of a rigorous redesign process. Right now the project lacks the resources to do that. Instead it's a collection of small changes towards a more modern UI.

> * In the message view:
>   * Make header more compact.
>   * Remove all-capital text for _SHOW PICTURES_ button, and optimize consumption of vertical space by this button when shown.
>   * Put buttons in toolbar only for _delete_, _reply sender_, _reply all_, and _forward_, as these actions are the most common after reading a message.
>   * Although navigation to next and previous messages are also common, these actions are easier and more familiar by swiping.  Support these gestures, and free space on the toolbar by removing the icons for these actions.

Improving the message view screen is definitely something we want to do. But coming up with a coherent design that incorporates all of the existing features is a lot of work. So it's not something I want to start before releasing 5.800.

> * In the folder view:
>   
>   * When no items are selected, make long press merely select an item, without triggering a popup menu. Specific actions can later be chosen by menu.

See #4188.

>   * Make single press on selected item remove selection from that item.

That's the current behavior. It might change in the future, though. See #3555.

>   * ~Shade background of unread messages, since bold is often hard to distinguish, depending on the type size and family, and physical display.~ (Appears to be configurable using global _Change colour when read_.  Perhaps the shading behavior should be the default.)
>   * Display date in more intelligent format, for example, time of day in case of same day, or day of week in case of earlier day within past week.

Except for day of the week this is the current behavior.

> * In the account sidebar:
>   
>   * Use less glitzy graphics for background behind account title.
>   * Arrange nested folders in folding tree, rather than as flat list with nested folders displayed by full path.

See #630.

> * Use more appropriate animations for changing screens. For example, currently transitions between folder view and message view are a horizontal slide, which is more appropriate for transitions between items of equal status, such as adjacent items in the same list. In a message view, the _delete_ or _back_ actions could move to the folder view with an animation that more directly captures the relationship of returning to a previously-visited place.

Animations are very low priority. But concrete suggestions are always welcome. If you wish to volunteer for this, please create a new issue.

> * Permit fine-grained control of notification behavior from inside application (as well as through system menus).  See #4482.

On modern Android versions apps are no longer allowed to change the configuration of notification channels once created.


I'm closing this issue since it's containing way too many things to be useful in tracking what work needs to be done. And it looks like we already have issues for most of it.
