### ISSUE TITLE
[inquisition] android 5 bar

### ISSUE THREAD

**Issue by eveofdestruction** [k9mail/k-9#4487]
> "K-9 Mail now requires Android 5.0 and newer"

Why no love for not yet fallen kitkat heroes ?  My TV media boxes are limited to 4.4.4 with zero upgrade path available.  The same for my tablets. 

I would like seamless AutoCrypt on my tablets 👍

**Comment by cketti** [comment]
a) Supporting old Android versions is a maintenance burden for us developers. 
b) Old Android versions don't support the latest TLS versions. Many servers already removed support for older TLS versions (because of known attacks against these versions). Hopefully a lot more will do so in the future.
