### ISSUE TITLE
Send again creates duplicate and sends twice.

### ISSUE THREAD

**Issue by Indigian** [k9mail/k-9#4491]
Mail that didn't send initially goes to the outbox.
When you 'send again' the mail opens up,click send and it sends 2 mails

**Comment by cketti** [comment]
This kind of works as expected. 'Send again' opens the compose window pre-populated with the values of the selected message. Once you press 'send' a new message is written to the Outbox to be sent.

The functionality you were probably looking for is called 'send messages' and can be found in the overflow menu when viewing the Outbox folder. It tries to send all messages in the Outbox.

A lot of the actions we offer for messages don't make too much sense for the Outbox. We should probably remove them. I created issue #4493 for that.

**Comment by Indigian** [comment]
Thanks cketti
How I've missed that all these yrs I'll never know
