### ISSUE TITLE
Gmail no notifications

### ISSUE THREAD

**Issue by Krystofido** [k9mail/k-9#4495]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
New mail comes: Pop up with Email (+ preview)

### Actual behavior
New mail comes: No notification, no sound, nothing. (It does receive Mails though, just no notification.)

### Steps to reproduce
1. Add Gmail account, standard settings, nothing special.
2. Receive Mail.
3. Don't get notifications, yet the Mail arrives on the device.

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (at least I think so)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This is most likely a configuration issue of notifications on your device, not a bug in K-9 Mail. 
Please use the [mailing list](http://groups.google.com/group/k-9-mail) to ask for help.
