### ISSUE TITLE
Optionally indicate account color also in single account mode

### ISSUE THREAD

**Issue by morckx** [k9mail/k-9#4496]
Since a4d2079c1 account color is no more indicated in single account message lists.

### Expected behavior
To make the account of the current message list immediately obvious, the account color should be indicated, at least optionally.

### Actual behavior
It is not immediately obvious from which account the message list is currently displayed,

### Steps to reproduce
1. Select the inbox of any of your ten accounts
2. Do something else
3. Switch back to k9mail
4. Try to figure out which account's inbox is shown

### Environment
K-9 Mail version: 5.705-SNAPSHOT

Android version: 9
### Options to indicate the account color
Here are some screenshots of options to solve the problem. I can also provide corresponding pull request.
If this is of interest, I could make it selectable how the color is indicated.

#### Background color of toolbar header
![Screenshot_20200131-220658_K-9_Mail](https://user-images.githubusercontent.com/1309388/73577595-a18a0800-447d-11ea-8996-56e66b98abdd.png)
#### Chip in front of folder name
![Screenshot_20200131-220811_K-9_Mail](https://user-images.githubusercontent.com/1309388/73577593-a18a0800-447d-11ea-94d1-ace122376d2a.png)
#### Font color of folder name
....
#### Corresponding setting
![settings_K-9_Mail](https://user-images.githubusercontent.com/1309388/73578199-540e9a80-447f-11ea-8581-dff4e207348d.png)

**Comment by cketti** [comment]
I want to avoid adding yet another setting. Using the account color in the toolbar feels like a lot of work to ensure it looks nice. How about displaying the account name (or email address?) below the folder name (toolbar subtitle) instead? 
We can still change this later and use the account color as indicator. But I don't want to start this work before releasing a new stable version.

**Comment by morckx** [comment]
Thanks for the reply! I agree that this enhancement is absolutely not urgent.

I've already implemented the two options that you can see above:

a. ) with the account color as background color of the list header
b. ) with an account color chip in front of the mailbox name

My questions before I start making a pull request are:
1. Is there enough interest in this at all?
2. Which indication option would be preferable to start with a) background color, b) color chip, c) anything else (I've already tried font color and drawer icon color) or d) some of them to chose from with a list preference

I think the option with the chip is so subtle and often used in other places that we wouldn't have to introduce another setting for it. But also the background color option looks nice and is already used in the drawer.

**Comment by cketti** [comment]
I think your proposals have potential. But I don't want to invest the time to figure out how to get them into a state where I'm willing to merge such a change right now. I'm happy to revisit this after 5.800 has been released.

Using the account name as toolbar subtitle would be a low effort option that could be done before the next stable version.

**Comment by morckx** [comment]
I think the difference of the effects is too big compared to the difference in efforts  (e931c6b8e6c6a1f7d623931525f68beec474bf55), but understand that changing the appearance  needs more discussion and agree that this should probably wait until after 5.8.

**Comment by morckx** [comment]
I still prefer my color chip solution and will keep that, but thanks.
