### ISSUE TITLE
Outbox vs Drafts - Cannot delete oversized send messages.

### ISSUE THREAD

**Issue by ukmerlin** [k9mail/k-9#4507]
Outbox vs Drafts.
App keeps mail to send in outbox. Online mail site only uses drafts folder.

The corresponding box does not exist on mail service and cannot be managed and synched thru it.
Need to be able to either use drafts the same as the site, OR be able to delete and terminate sending operation.

If mail is too big to send and you delete it, it will not delete and it will never stop trying to send it.

### Steps to reproduce
1. Put a large attachment in an email.
2. Send the email
3. Delete the email from the outbox.

### Environment
K-9 Mail version:  5.600

Android version:  9

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment]
From your description it's not clear to me what you're doing exactly. Deleting a message from K-9 Mail's Outbox folder should work as expected. It probably won't cancel a send operation currently in progress. As a work-around you could switch the device to airplane mode. That will cancel any currently running send operation.

**Comment by ukmerlin** [comment]
I had deleted the email a number of times only to return and find it still in the outbox. I forced a stop of the application and again on restart it would try to send the deleted email. For some reason (after two days) it stopped sending and the message was gone.
