### ISSUE TITLE
K9 not connecting to Yahoo mail anymore

### ISSUE THREAD

**Issue by chroche77** [k9mail/k-9#4526]
Hello everybody,

K9 worked perfectly with my yahoo mail account until about 2 weeks ago. From that moment, on each connection attempt via IMAP, the connection fails, be it with either imap.mail.yahoo.com or android.imap.mail.yahoo.com. 

K9 says that authentication failed and that the server parameters should be updated. 

I saw here that other users have encountered, from time to time, similar problems using K9 with Yahoo mail : for instance in bug report # 3382, which has been closed and considered a Yahoo issue. But I am not sure this is a Yahoo issue since with another client app (Gmail in my case), all is working as normal, while K9 still encounters that issue. 

Thank you very much in advance for your help.

Kind regards,

C

### Expected behavior
Should be working as normal

### Actual behavior
IMAP connection fails. 

### Steps to reproduce
Reloading mailbox

### Environment
K-9 Mail version: 5.600
Android version: Oreo Go
Account type: IMAP at Yahoo

**Comment by cketti** [comment]
Well, we haven't changed anything in K-9 Mail. So if the app stopped working, Yahoo must have changed something. Please contact their support.

**Comment by nhhandyman** [comment]
My Yahoo account is still working.

I'm running 5.705

**Comment by nhhandyman** [comment]
I may have run into this before and exporting setting removing the account the importing solved the issue.

**Comment by Poggles** [comment]
Yep I just downloaded K-9 to trial it out to replace my regular email app.  All my other accounts work fine, but Yahoo fails to authenticate.

The same settings work fine with Thunderbird, so not sure what is going on there.  The response is [NO, [AUTHENTICATIONFAILED], LOGIN Invalid Credentials]

**Comment by vdbhb59** [comment]
Yahoo states they have not changed anything and I still get this error, on every version I tried. I tried other android clients and it works with them. Does not work with K9

**Comment by cketti** [comment]
Looks like you need to create a "third-party app password". See https://help.yahoo.com/kb/generate-third-party-passwords-sln15241.html

**Comment by vdbhb59** [comment]
Yup, I just tried that and it gave error 3 times, then I cleared k9 cache and force stopped. Then it worked. But when I had reached to Yahoo, they said they still follow the IMAP & POP stuff like earlier times. Liars..

**Comment by d21anthony** [comment]
Generate Third Party App password worked for me as well. Thank you

**Comment by xcpenguin** [comment]
@cketti Thanks. You saved me quite a bit of digging!

**Comment by badmin-c** [comment]
> Looks like you need to create a "third-party app password". See https://help.yahoo.com/kb/generate-third-party-passwords-sln15241.html

Works for me too. Thanks!

**Comment by MarcoHoffmannn** [comment]
january 2023, fyi:

As yahoo didn't allow generating a new app password yesterday "Sorry, this feature is not available right now!" on orange bg (then filled in K9 settings for outgoing server the listed "name" (which looks like my idea) of the password I generated ages ago as password, not the yahoo webpage pw, I tried in between, so I had no idea which pw I generated ages ago and wondered what that was) and when I read somewhere something confusing that K9 is now thunderbird on android or the like, I remembered that in yahoo help there was thunderbird mentioned. That page contained a link (ignored the rest) (
"
Access mail via Thunderbird

[…] 

Read more on removing and re-adding accounts in Thunderbird.

"
Source: https://help.yahoo.com/kb/account/securely-access-yahoo-mail-sln27791.html
) 

which led me to

"
Set incoming server 'Authentication Method' to 'Oauth2' 

[…] 

Then there will be a prompt from your Yahoo ISP partner to login. This is done with a OAuth 2.0 key exchange in Thunderbird which will authenticate the Thunderbird client in future logins. 
"
Source: https://support.mozilla.org/en-US/kb/thunderbird-and-yahoo#w_important-changes-to-authentication-method-notice

I found that" Oauth2" in settings/outgoing server of my yahoo-client-account in the K9 app on android and then the "weiter" (proceed-button, probably "continue") didn't give me that auth error popup anymore, but instead I was led to a yahoo login and there I allowed K9 by clicking which was confirmed by an email saying

"
New sign in on K-9 Mail

Hi Marco,

Your Yahoo account […] was just used to sign in on K-9 Mail.

If you did this, you’re all set.

If not, please use this link to stop sharing, and create a new password.

Have a great day!

Thanks,

Yahoo
"
