### ISSUE TITLE
Can't import settings, can't enter username/password manually

### ISSUE THREAD

**Issue by PenelopeFudd** [k9mail/k-9#4532]
### Expected behavior
Trying to set up K9 on a new phone.

### Actual behavior
I've gotten a replacement Pixel 2XL, installed K9mail 5.705, exported settings from old phone (also 5.705), tried importing settings, general settings imported, but account settings failed.

Then tried adding account manually, entered username and password, but 'next' button greyed out/disabled.

I'm a little frustrated.

### Steps to reproduce
1. Try importing settings
2. Try manually setting an account

### Environment
K-9 Mail version: 5.705

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by PenelopeFudd** [comment]
Apparently the username has to be an email address or the next button won't be enabled.

Still can't import settings though.

**Comment by cketti** [comment]
The first screen requires entering your email address. That's often used as username for the incoming and outgoing servers, so K-9 Mail uses it as default. But this can be changed in manual setup.

To be able to find out why settings import doesn't work we'll need a debug log.
