### ISSUE TITLE
no K-9 icon on the always on display

### ISSUE THREAD

**Issue by juve-fc** [k9mail/k-9#4534]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
An icon of K-9 remains on the always on display (AOD) after each arrival of a notification

### Actual behavior
My Xiaomi Mi9T's own always-on-display (AOD) feature allows only a few 3rd party apps to display notifications there, e.g. WhatsApp, GMail (K-9 too, but only with a customized ROM called xiaomi.eu).
Hence I installed an app that does it better ("[Always on AMOLED](https://play.google.com/store/apps/details?id=com.newgen.alwayson)"). So far, it shows every notification of all apps (a weather app, a banking app, etc.), **excepting K-9**!
Notifications from K-9 appear on the lock screen, but not on the AOD. For an adjustable, short time edge lighting is even signaling on the AOD the notification (like for notifications of the other apps), but no icon is displayed to remain on the AOD.
According to the [FAQ](http://www.newgenmobile.net/faq/index.html) of the AOD app:
> Each notification has its action buttons that were programed but the developers of the app that is sending the notification. 99% of the actions buttons will work, but there are some that wont work. That is not the AMOLED fault but more of how the developer of that app designed those action buttons.

Therefore, I suppose something in K-9 was omitted, probably its icon is not provided properly (there is no need for action icons, every app show also only its icon displayed also in the status bar).

### Steps to reproduce
1. activate always on display and allow K-9 to show notifications on the lock screen
2. send an e-mail that K-9 should show up in the folder without manually refreshing
3. no K-9 icon is displayed on the AOD

### Environment
K-9 Mail version: 5.704

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Well, this "it's the developers fault" is not very specific. If you can find out what exactly the AOD app can't work with, we might have a chance to make the necessary change in K-9 Mail.
