### ISSUE TITLE
certain accounts won't automatically fetch mail, nor fetch mail when manually triggered in the unified mail view

### ISSUE THREAD

**Issue by emacsomancer** [k9mail/k-9#4537]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Mail for all accounts (with the appropriate settings) should be automatically fetched at the interval set, and also when manually refreshed in the unified inbox view.

### Actual behavior
My two mailbox.org accounts (in contrast to my gmail accounts) do not automatically fetch mail at the interval specified, nor do they fetch mail when I 'refresh' in the unified inbox view. I can only can get to fetch mail if I go into these account individually and manually 'refresh' to force them to fetch mail.

### Steps to reproduce
1. Described above.

### Environment
K-9 Mail version:
5.704
Android version:
9 (Lineage 16.0-20200212)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please open a new issue if this is still a problem with the latest beta version.
