### ISSUE TITLE
No more reload icon in 5.705

### ISSUE THREAD

**Issue by terr72** [k9mail/k-9#4553]
I upgraded from 5.600 to 5.705 and noticed that the Reload symbol is gone, there's also no menu entry for reloading messages.
Not sure if this is an intended overall design choice (couldn't find anything about it in the changelogs) or a bug.

### Expected behavior
There should be a reload symbol to fetch new messages.

### Actual behavior
There's neither a symbol nor a menu entry to reload manually.

### Environment
K-9 Mail version: 5.705
Android version: Android 10
Account type: IMAP

**Comment by cketti** [comment]
You can use "pull down to refresh" in the message list.
