### ISSUE TITLE
add fastlane metadata structure

### ISSUE THREAD

**Issue by Bubu** [k9mail/k-9#4562]
See here: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

This would solve the no icon in f-droid problem.

**Comment by Bubu** [comment]
@cketti which description would you want for this. F-Droid and play store currently have different descriptions.

Also which version of the icon?

And probably more modern screenshots than the ones currently in the play store :)

**Comment by cketti** [comment]
I think for now we'll go with the current F-Droid description. I'll update the description and screenshots once the beta version is closer to a stable release.
