### ISSUE TITLE
Suddenly wolfing up data

### ISSUE THREAD

**Issue by RPTdorset** [k9mail/k-9#4591]
### Expected behavior
Used K9 happily for over a year.  It's on a cheap 'phone for secondary use, so low storage space and very limited data.  K9 has been fine for that - until yesterday

### Actual behavior
Yesterday K9 used almost 1GB of data in less than 12 hours.

It didn't download any large emails (perhaps 10 emails, total size less than 1MB).  I hadn't changed any settings.  There's nothing else on my email server (when I download emails to my main laptop they delete off the server, so there's only ever that day's emails from while I'm out).

I can't see what would have caused it to suddenly use all that data.  I usually only use about 100MB a month (and that's including K9, Facebook, maps etc), now K9 has used nearly a year's data in one afternoon, but with nothing obvious that it's done to use that.

### Environment
Using a POP3 email server, K9 app on Android phone

Sorry, don't have logs etc. or K9 version number - I couldn't stop K9 eating data so I deleted it.

**Comment by cketti** [comment]
Without more information there's nothing we can do. Since you uninstalled K-9 Mail I don't see a way to get this information.
