### ISSUE TITLE
feature request: make it possible to have Message prev/next at bottom

### ISSUE THREAD

**Issue by MasterPlexus** [k9mail/k-9#4595]
As the setting "Gestures" for next or previous message is still out of function, I think about a alternative. 
As the menu within a message is on top, and the previous and next button are small and near together it works not as nice as could be.
So the Idea could be, to made the buttons avalible on bottom of the screen, and increase the size a little bit (or made some space between). After that they are more easyly reachable whith one hand. 
This should be switchable (old behaviour and new one) via a switch in preferences.
This is just an Idea, maybe someone of the Devs think it will be helpfull.

It looks like there is a old similar Issue, but the link within is no longer reachable which was mentioned: #2655
BR MP

**Comment by cketti** [comment]
There's issue #585. We don't have any plans to implement an interim solution.
