### ISSUE TITLE
Sync disabled over mobile data

### ISSUE THREAD

**Issue by roughnecks** [k9mail/k-9#4597]
### Expected behavior
Emails should keep syncing when using mobile data.

### Actual behavior
Every time I open K-9 it tells me that Sync is disabled. When using Wi-Fi everything works fine.
Android Sync is on, battery optimization is set to allow all activities from K-9 and I'm keeping the app locked in recent menu, so it never shuts down.

### Environment
Android version: 5.600
XIAOMI Redmi 6A

Account type: IMAP

**Comment by dhebbeker** [comment]
See #3950.

**Comment by roughnecks** [comment]
I already saw that but it's not helping.

**Comment by cketti** [comment]
Duplicate of #3950
