### ISSUE TITLE
additional unified inbox?

### ISSUE THREAD

**Issue by docjochim** [k9mail/k-9#4600]
Hi there,

I used (Outlook-)Mail in my Windows Phone, where I had the possibility to group several inboxes of different private mail-accounts into one nameable 'parent'-account. With the possibility to add a corresponding private-email-icon to the startup-screen.
After switching to an android-phone, I found this ability to be realized in k-9 by looking at the unified inbox :-)

But in my Windows-Phone-App I also had the possibility to group several additional inboxes of different business-mail-accounts into another nameable 'parent'-account. With the possibility to add a second corresponding business-mail-icon to the startup-screen.

Unfortunately I can not find this ability in k-9?!

It would be great to have the possibility to group the installed mail-accounts, not only in one single unified inbox, but in several individual inboxes - with the option for an account to be listed in parent-account-1, ~-2, or ~-3...

And with the possibility to add different icons to android's homescreen providing the ability to startup k-9 by opening a predefined sub- or parent-mailaccount.

Will this option perhaps be realized in future versions?

Yours

André

**Comment by cketti** [comment]
There are no plans to add such a feature in the near future.
