### ISSUE TITLE
Emails deleted/lost during export/import action

### ISSUE THREAD

**Issue by jinnko** [k9mail/k-9#4621]
### Expected behavior

When exporting and importing settings and accounts from one device to another I expect the IMAP accounts to be migrated in such a way that no emails will be lost that may have arrived in the interval between the export and the import.

### Actual behavior

Old phone had K9 mail, but I didn't migrate the settings and accounts for about two weeks.  The phone was turned off so didn't pick up new messages.  I simply didn't set anything up on the new phone.

Sat down to export settings and accounts from the old phone, which last collected messages on March 8th.  Copied the export file to my laptop, then to the new phone.  Imported the settings and accounts and I see the latest messages are from March 8th.

I go to my laptop to check and I find the lat two weeks of emails have just been deleted.

Log into the server to check and indeed my ZFS snapshot from just before the import contains the lost messages.  Fortunately I was able to restore the snapshot and recover the lost messages.

### Steps to reproduce

1. Turn off old device with K9 mail
2. After some period of time during which emails have arrived to your IMAP account, turn on the device, but make sure it doesn't connect to the mail server.
3. Export settings and accounts
4. Copy export to new device
5. Import
6. Observe any messages that arrived during the interval are lost.

### Environment

K-9 Mail version: 5.600 on both exporter and importer

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange):  Dovecot IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
K-9 Mail only exports settings, not messages or information about which messages have been downloaded. K-9 Mail doesn't delete messages from the server on its own. I don't see how K-9 Mail could be responsible for the behavior you have observed.
