### ISSUE TITLE
Meta issue: Drafts/Sent/Trash directories does not sync on IMAP accounts

### ISSUE THREAD

**Issue by davidhedlund** [k9mail/k-9#4623]
* [K9 does not delete message from IMAP Server](https://github.com/k9mail/k-9/issues/3801)
* [Trash not sync'ing correctly](https://github.com/k9mail/k-9/issues/3605)
* [Drafts are deleted when they cannot be sent](https://github.com/k9mail/k-9/issues/2616)
* [Sync issues with the Sent directory on IMAP](https://github.com/k9mail/k-9/issues/4622)

**Comment by cketti** [comment]
There's no need for a "meta issue". If sync doesn't work it's a bug. But those issues are not necessarily all caused by the same bug.
