### ISSUE TITLE
Syncing disabled over wifi - another issue to close without resolving

### ISSUE THREAD

**Issue by todduk** [k9mail/k-9#4625]
### Expected behavior
K9 should sync over wifi

### Actual behavior
Not syncing- all issues about it closed.

### Steps to reproduce
1. Global settings > Network > Background sync = Always
1. Battery Manager = off
1. Battery optimization > K9 > Not optimized
1. Connect to wifi

### Environment
K-9 Mail version: 5.600 (according to app info, no about tab in app?)

Android version:
9 - Phh-Treble vanilla, no google apps

Account type (IMAP, POP3, WebDAV/Exchange):
Any.

**Comment by cketti** [comment]
Issues are closed by pointing to issue #3950.

What do you hope to accomplish by opening another issue? We know about the problem and are working on a new version that will fix the issue. In the meantime issue #3950 contains information about all the workarounds users have come up with.
