### ISSUE TITLE
Context menu replacement

### ISSUE THREAD

**Issue by elhennig** [k9mail/k-9#4630]
Since the context menu has been removed in #4188, I would like to ask for an alternative;
Can you show the menu previously shown as context menu in the three point menu as soon as one message has been marked in the message list? Currently only the message actions are shown there.

**Comment by cketti** [comment]
The only actions that are missing are ones that only make sense for a single message (reply, forward etc.). This means the actions available for selected messages would need to be different depending on whether only one message or multiple were selected. While this is possible, I don't think it's very intuitive to understand.
I also don't think it's very useful. Selecting a message, opening the menu, then selecting an action is hardly faster than clicking on the message to open the message view, maybe opening the menu, and then selecting an action.

**Comment by elhennig** [comment]
> Selecting a message, opening the menu, then selecting an action is hardly faster 
That is what I meant, but I would find it very useful to add the missing menu entries in the three point menu in the message list to apply them to the selected messages **without** opening the message view. And then at least to "more from sender", "spam" and the answering options could be displayed in the top menu in the message list, if one message is selected and only show the multi message options if more than one message is selected.

**Comment by babyNeo** [comment]
How can you change the read status of a message now?
