### ISSUE TITLE
Network not properly detected on VPN

### ISSUE THREAD

**Issue by tango25001** [k9mail/k-9#4635]
### Expected behavior
Tell us what should happen

When I connect to the Internet via VPN with Gnirehtet (VPN over USB) (https://github.com/Genymobile/gnirehtet) without any other network connection (No Wifi, no mobile network)
I can do a manual sync of the mailbox. But K9 doesn't start the sync or push service automatically since the network is not recognised.
this happens since I switched to  Android 10.

On Android 8.1 it worked without a problem.

### Actual behavior
Tell us what happens instead

When there is a Network connection, sync should start automatically.

### Steps to reproduce
1. Run gnirehtet (https://github.com/Genymobile/gnirehtet) as described and connect your Phone with flightmode enabled
2. now you can do a manual sync. but Pushservice or Syncing every hour is not running
3.

### Environment
K-9 Mail version:

5.600

Android version: 10.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (hotmail.com)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

not possible, since network is not recognised, no error occurs

**Comment by cketti** [comment]
In K-9 Mail 5.7xx we use the WorkManager library for periodic syncs. It's possible it handles this case better than the code we use in 5.600.

But having sync work when airplane mode is active isn't something I want to invest time in. If it doesn't work, you're on your own. I'm happy to review a pull request to add support for this, though.

**Comment by ailicic** [comment]
I can provide a PR to fix this. It is actually really easy to fix as it involves using the new [ConnectivityManager.getActiveNetwork()](https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetwork()) API in conjunction with the [NET_CAPABILITY_INTERNET](https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET) constant. 

Please confirm that you are still interested in accepting such a PR.

**Comment by ailicic** [comment]
@cketti :point_up:

**Comment by cketti** [comment]
As mentioned in my previous comment, periodic syncs are now using WorkManager's network detection which presumably just works™. If not, that's a bug that needs to be fixed in WorkManager. 
Manual syncs don't check network connectivity before attempting to connect to the server so they're not an issue either.

**Comment by ailicic** [comment]
I think the issue is that push is broken. What I am proposing would fix push. Right now it shows "Syncing disabled" even when it has network connectivity via VPN.

Would you accept a PR to fix this?

**Comment by cketti** [comment]
The current K-9 Mail code base is nothing like it was when 5.600 was released. The push code has been removed and is currently being rewritten. It sounds to me like you haven't even looked at the code. I admire your confidence in your ability to fix this issue. But there's nothing to fix in the current code base. If you disagree then please open a PR so we have something concrete to talk about.

**Comment by ailicic** [comment]
@cketti The main problem is that K9 uses deprecated code in Utility.java on line 251:
`final NetworkInfo netInfo = connectivityManager.getActiveNetworkInfo();`

I can replace this with non-deprecated code and then IMAP Idle/Push will work (sorry if I don't have the exact term correct).

**Comment by ailicic** [comment]
If the push code is being rewritten then I'll patiently wait. Thanks.
