### ISSUE TITLE
Contain of the emails doesn't show up 

### ISSUE THREAD

**Issue by joelocandol** [k9mail/k-9#4637]
### Expected behavior
Enter in a mail and all the information contained in it show up properly (adjunct archive, image, etc) 

### Actual behavior
Enter in a mail and just the tittle appear a the rest is disappeared 

### Environment
K-9 Mail version: 5.705

Android version: 7.0 

Account type (IMAP, POP3, WebDAV/Exchange): IMAP 

Is weird because the contain of the mails appear on the previsualization lines

**Comment by cketti** [comment]
Please update to the latest version (5.708) and try again. If the error persists please open a new issue and provide more information. What device are you using? Which Android ROM/OS? Are only some messages affected or all of them?
