### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by jw243** [k9mail/k-9#4640]
I am using version 5.707 on LineageOS 16.0 and 17.1

It`s great that K9 is receiving a major overhaul. Version 5.707 works for me. However, I would love to see the following enhancements:

- I'd love to have an **overview page** that shows me **all of my accounts displaying the number of unread messages**.

- In each folder, I'd like to see the **total number of message**s that are contained within that folder.

- I'd like to see the return of the **swipe gesture from version  5,600** to select a message.

- I'd love to see the return of **push messages**. :-)

Thanks, and keep up the great work!

**Comment by cketti** [comment]
> * I'd love to have an **overview page** that shows me **all of my accounts displaying the number of unread messages**.

See #4515 (and #4405).

> * In each folder, I'd like to see the **total number of message**s that are contained within that folder.

See #1037.

> * I'd like to see the return of the **swipe gesture from version  5,600** to select a message.

There are no plans to bring this back. See #1426 and #4628.

> * I'd love to see the return of **push messages**. :-)

See #4258.

This issue tracker is not meant to be a discussion forum. It is used to track bugs and keep track of the development work that needs to be done. Please don't create additional work by opening issues like this (or adding "me too" comments to existing issues). Use the search before posting. For support requests please use the [mailing list](http://groups.google.com/group/k-9-mail).
