### ISSUE TITLE
Missing content 

### ISSUE THREAD

**Issue by joelocandol** [k9mail/k-9#4644]
Expected behavior
Enter in a mail and all the information contained in it show up properly (adjunct archive, image, etc)

Actual behavior
Enter in a mail and just the tittle appear a the rest is disappeared

Environment
K-9 Mail version: 5.708

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Is weird because the contain of the mails appear on the previsualization lines

Oukitel c5 stock rom, almost aosp android nougat

The problem persist in all the mails

**Comment by cketti** [comment]
Sounds like an issue with the WebView component on your device. Do other email apps display the message content?

**Comment by joelocandol** [comment]
I didn't know that this worked with webview, so I updated android webview and it fix. Now there's no problem. But, It was working the Samsung internet webview before the problem, idk why it stop to working
