### ISSUE TITLE
add menu item "Share"

### ISSUE THREAD

**Issue by monperrus** [k9mail/k-9#4651]
Sometimes, I need to share an email on another messaging app (for example Signal). In that case, the only solution it to copy'n'paste.

What about a menu item "share" in the menu?  

Thanks!

**Comment by cketti** [comment]
The "share" action can be found in the "send" submenu when viewing a message.

**Comment by monperrus** [comment]
thanks, I see it! I was looking for it in the "three dot" submenu.
