### ISSUE TITLE
using blackberry keyboard shortcuts will need a phone restart to make the keyboard work again

### ISSUE THREAD

**Issue by Flexmaen** [k9mail/k-9#4654]
On the Blackberry Keyone I can set the right shift key, as ctrl key for using system wide shortcuts like ctrl+A (selecting all text), ctrl+C (copy), etc.

In this case I replied to an existing mail and pressed ctrl+A

### Expected behavior
The whole text in the text editor should be highlighted and selected.

### Actual behavior
I'll end up in the contact list and the hardware keyboard won't work anymore in any app until I restart the phone.

Note: Most of the apps work with these shortcuts, only few don't. But this is the only app so far that makes the keyboard unusable systemwide until having a complete restart!

### Steps to reproduce
1. Make sure to activate system shortcuts (via right shift key) in the keyboard settings
2. Open the mail editor (e.g. by repliing to an existing mail)
3. Press ctrl (=right shit) + A

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
K-9 Mail doesn't intercept key presses in the message compose screen. Please report this bug to Blackberry.

**Comment by Flexmaen** [comment]
No, this is not a blackberry issue.

K-9 should just accept the system wide shortcuts that work in every other app instead of doing it's own thing. I should just support a setting like "use system default".

**Comment by Flexmaen** [comment]
Ok, you were right. The good news: It's working with 5.710 beta.
