### ISSUE TITLE
Many mails in trash folder 

### ISSUE THREAD

**Issue by Memoli77** [k9mail/k-9#4655]
Dear developers, 

I need some help. Although I don't delete the emails, many emails always end up in the trash folder. The big problem is that I can no longer pull these mails into the inbox because they "were not synchronized with the server".  I need your help, please.
### Environment
K-9 Mail version:
5.6

Android version:
9

Account type (IMAP, POP3, WebDAV/Exchange):
Every account

**Comment by BElluu** [comment]
Hi @Memoli77 

What is your email provider?
Would you be able to write out the standard directories that are in this provider with the newly created account?

**Comment by Memoli77** [comment]
My provider is T-Online. How can I write the standard directories? I have now updated to K9 5.7 and i am waiting if it happens again.

**Comment by BElluu** [comment]
@cketti How can we get some loggs to try diagnose the cause of this situation?

**Comment by cketti** [comment]
Please open a new issue when this happens again. And be sure to provide the information we ask for. Especially the account type.
