### ISSUE TITLE
zygote connection refused

### ISSUE THREAD

**Issue by mwlczk** [k9mail/k-9#4666]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I can open an email an read it contents

### Actual behavior
opening k9 and navigating works, but once i click an e-mail to view it, k9 crashes with the following error 

### Steps to reproduce
1. open k9 
2. open a list of emails
3. tap on an email

### Environment
K-9 Mail version: 5.708

Android version: 10 / Q LOS 17.1 with Bromite System WebView 81.

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
04-14 16:09:56.798  3780  3780 D MessageViewFragment: MessageView displaying message MessageReference{accountUuid='2bbefefd-fa8f-4ad9-932f-6d408cec8dcf', folderServerId='INBOX', uid='12482', flag=null}
04-14 16:09:56.798  3780  3780 D MessageLoaderHelper: Creating new local message loader
04-14 16:09:56.825  3780  3780 D MessageLoaderHelper: Creating new decode message loader
04-14 16:09:56.870  1605  2395 D ConnectivityService: requestNetwork for uid/pid:10126/3780 NetworkRequest [ TRACK_DEFAULT id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10126] ]
04-14 16:09:56.871  1605  2091 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10126] ] with score 60 and serial -1
04-14 16:09:56.871  1605  2091 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10126] ] with score 60 and serial -1
04-14 16:09:56.871  1605  2123 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10126] ] with score 60 and serial -1
04-14 16:09:56.874  2415  2415 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=47, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10126] ] with score 60 and serial -1
04-14 16:09:56.901  3780  3780 D Utility : No external images.
04-14 16:09:56.902  1605  1759 E ZygoteProcess: Starting VM process through Zygote failed
04-14 16:09:56.904  1605  1759 E ActivityManager: Failure starting process com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:1
04-14 16:09:56.904  1605  1759 E ActivityManager: java.lang.RuntimeException: Starting VM process through Zygote failed
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.start(ZygoteProcess.java:340)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.Process.startWebView(Process.java:554)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at com.android.server.am.ProcessList.startProcess(ProcessList.java:1808)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at com.android.server.am.ProcessList.lambda$startProcessLocked$0$ProcessList(ProcessList.java:1668)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at com.android.server.am.-$$Lambda$ProcessList$vtq7LF5jIHO4t5NE03c8g7BT7Jc.run(Unknown Source:20)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.Handler.handleCallback(Handler.java:883)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.Looper.loop(Looper.java:214)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
04-14 16:09:56.904  1605  1759 E ActivityManager: Caused by: android.os.ZygoteStartFailedEx: Error connecting to zygote
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.openZygoteSocketIfNeeded(ZygoteProcess.java:923)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.startViaZygote(ZygoteProcess.java:635)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.start(ZygoteProcess.java:333)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	... 9 more
04-14 16:09:56.904  1605  1759 E ActivityManager: Caused by: java.io.IOException: Connection refused
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.net.LocalSocketImpl.connectLocal(Native Method)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.net.LocalSocket.connect(LocalSocket.java:147)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess$ZygoteState.connect(ZygoteProcess.java:188)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.attemptConnectionToPrimaryZygote(ZygoteProcess.java:875)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	at android.os.ZygoteProcess.openZygoteSocketIfNeeded(ZygoteProcess.java:908)
04-14 16:09:56.904  1605  1759 E ActivityManager: 	... 11 more
04-14 16:09:56.904  1605  1759 I ActivityManager: Force stopping com.fsck.k9 appid=99005 user=0: start failure
04-14 16:09:56.906  1605  1759 I ActivityTaskManager:   Force finishing activity ActivityRecord{f6049c5 u0 com.fsck.k9/.activity.MessageList t547}
04-14 16:09:56.929  1605  1759 I ActivityTaskManager:   Force finishing activity ActivityRecord{f6049c5 u0 com.fsck.k9/.activity.MessageList t547 f}
04-14 16:09:56.929  1605  1759 W ActivityTaskManager: Duplicate finish request for ActivityRecord{f6049c5 u0 com.fsck.k9/.activity.MessageList t547 f}
04-14 16:09:56.930  1605  1759 I ActivityManager:   Force stopping service ServiceRecord{cf4bf73 u0 com.fsck.k9/org.chromium.content.app.SandboxedProcessService0:1}
04-14 16:09:56.960  1605  1748 I ActivityManager: Exiting empty application process 0:com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:1/u0a126i5 (null)
04-14 16:09:56.968  1605  5380 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10100?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
04-14 16:09:56.984  2331  2354 W System  : A resource failed to call release. 
04-14 16:09:56.985  2331  2354 W System  : A resource failed to call release. 
04-14 16:09:57.015  2132  2132 D ImageWallpaper: wallpaper visibility changes to: true
04-14 16:09:57.073  2132  2144 I ndroid.systemu: NativeAlloc concurrent copying GC freed 107085(4150KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6316KB/12MB, paused 77us total 137.292ms

**Comment by cketti** [comment]
This is much more likely a problem with your OS and/or WebView implementation, than with K-9 Mail. I'm happy to be proven wrong and will accept a pull request to work around this issue. But I don't see any of the K-9 Mail contributors investing time in trying to find out what is causing this crash.

**Comment by yhm2046** [comment]
I also met this error in my code:
~/md11/imx-automotive-10.0.0_2.2.0$ git df  vendor/nxp-opensource/kernel_imx/include/linux/rcupdate.h
diff --git a/vendor/nxp-opensource/kernel_imx/include/linux/rcupdate.h b/vendor/nxp-opensource/kernel_imx/include/linux/rcupdate.h
old mode 100644
new mode 100755
index 75a2eded7a..b3c66e8392
--- a/vendor/nxp-opensource/kernel_imx/include/linux/rcupdate.h
+++ b/vendor/nxp-opensource/kernel_imx/include/linux/rcupdate.h
@@ -592,7 +592,7 @@ do {                                                                              \
  * read-side critical sections may be preempted and they may also block, but
  * only when acquiring spinlocks that are subject to priority inheritance.
  */
-static __always_inline void rcu_read_lock(void)
+static inline void rcu_read_lock(void)
 {
        __rcu_read_lock();
        __acquire(RCU);

and logcat error:
06-01 14:54:10.904   513   542 E ActivityManager: Caused by: android.os.ZygoteStartFailedEx: Error connecting to zygote
