### ISSUE TITLE
Is there an intent to make K9 check email? Or could one please be introduced? So that checking could be triggered while in ‘doze’, by other apps

### ISSUE THREAD

**Issue by decadent** [k9mail/k-9#4677]
Until K-9 figures out what to do about the ‘doze’ thing, there are apps like Automate or Tasker, which seem to successfully wake up periodically when K-9 does not (mostly by presenting a persistent notification, which thankfully can be ‘minimized’). So, if there were an intent that I could send to make K-9 check for new mail, then I could set up Automate to poke K-9 every fifteen minutes.

I looked through the manifest and the issues, but it seems there's no such intent now. Would it please be possible to add one?

**Comment by cketti** [comment]
A message sync is a potentially expensive operation (limited data plans etc). Allowing every third-party app to do this wouldn't be great. Adding a way to grant the user permission for this to only a specific app is a lot more work than I want to spend on this. So this is not going to happen.
