### ISSUE TITLE
Manuelle Zeilenumbrüche werden aus Mails gelöscht, die als Entwurf gespeichert werden

### ISSUE THREAD

**Issue by deadletters** [k9mail/k-9#4679]
### Actual behavior
Hallo,

wenn ich eine Mail als Entwurf speichere, sind beim wieder Öffnen des Entwurfs alle manuell gesetzten Zeilenumbrüche gelöscht.

Zeilenumbruch
1
2
3
4
5

Die Mail sieht dann so aus:

Hallo,wenn ich eine Mail als Entwurf speichere, sind beim wieder Öffnen des 
Entwurfs alle manuell gesetzten Zeilenumbrüche gelöscht.Zeilenumbruch12345

### Steps to reproduce
1. Mail schreiben mit manuellen Zeilenumbrüchen
2. Mail schliessen und als Entwurf speichern
3. Mail aus dem Ordner Entwürfe öffnen

### Environment
K-9 Mail version:
5.709

Android version:
OnePlus 7 Pro mit Android 10 

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
The project language is English. Please make things easy for people working on K-9 Mail. Time spent translating/recreating issues is time not spent improving the app.

Duplicate of #4685

**Comment by deadletters** [comment]
Thanks for translating.
Sorry, for writing in german, but my english is not so good.

Best regards
Til

Am 23. April 2020 20:25:39 MESZ schrieb cketti <notifications@github.com>:
