### ISSUE TITLE
Bring back "clear local messages"

### ISSUE THREAD

**Issue by nhfo** [k9mail/k-9#4684]
There used to be an option to compact (discard local copies of emails) an imap folder. IIRC it used to be in context menu of folders. It is not available since the UI update. 

This option was quite useful in keeping storage usage in control. Without it my trash folder is getting bigger and bigger.

One option is to add it to left drawer > manage folders > xyz folder > compact folder.

**Comment by cketti** [comment]
The action was called "clear local messages". I'm not particularly fond of it. It requires too much knowledge of how the app works to be useful. 
I'd rather have the app clean up on its own. However, that's functionality that hasn't been implemented yet. I might bring back "clear local messages" as a stopgap measure.

**Comment by basilgello** [comment]
I second that. I expected https://github.com/k9mail/k-9/commit/2dccbb7c480a0e6435580533b6f0caefc177e7aa will close https://github.com/k9mail/k-9/issues/4100 but it seems to be unrelated.

I will restore the functionality of 'clean local messages' in a couple of hours and push it as a separate PR (with no expectation to have it merged).

After that, let's try implementing cleanup. Is the roadmap ok for you @cketti @nhfo?

**Comment by cketti** [comment]
@basilgello: I don't want the action in the menu of the message list screen. Maybe it can go into the menu of the folder settings screen. That way the functionality is available for users who "need" it, but is mostly hidden away.

**Comment by basilgello** [comment]
> @basilgello: I don't want the action in the menu of the message list screen. Maybe it can go into the menu of the folder settings screen. That way the functionality is available for users who "need" it, but is mostly hidden away.

I want to put it into account settings so it will be hidden even more :) For those knowing what they are doing!

**Comment by cketti** [comment]
> I want to put it into account settings so it will be hidden even more :) For those knowing what they are doing!

How? It's a per-folder action. The account settings screen currently doesn't display a list of all folders. And the action feels a bit misplaced there. 

"Folder *settings*" is also not quite right. But I suspect in time that screen will become more of a "folder details" screen where users can change folder settings, see more information about a folder and manipulate it.

**Comment by basilgello** [comment]
> > I want to put it into account settings so it will be hidden even more :) For those knowing what they are doing!
> 
> How? It's a per-folder action. The account settings screen currently doesn't display a list of all folders. And the action feels a bit misplaced there.
> 
> "Folder _settings_" is also not quite right. But I suspect in time that screen will become more of a "folder details" screen where users can change folder settings, see more information about a folder and manipulate it.

Oh, I just realized we talk about slightly different things. I want to bring back this https://github.com/k9mail/k-9/blob/447dbe1bf0c977e6bab0d03659a5807586ad2da4/app/core/src/main/java/com/fsck/k9/mailstore/LocalStore.java#L304 and you are really right that 'Folder settings' is better place to have it not to get confused with 'Delete account' stuff. Or at least, not in the same pop-up menu. I used to remove my whole mailbox regularly in the past while trying to handle with #4100 so I don't want to introduce this mistake again.

**Comment by gsauthof** [comment]
FWIW, another use-case for the 'Clear local messages' folder action:

I disaster-recovered an IMAP-server, and after the recovery I was quite surprised that one k9mail account didn't display new messages - without showing any errors. So I checked a various things, server logs, querying the same account with a command line client (that listed the messages), force-stopped k9mail, etc.

Thus I enabled k9mail debugging and looked at logcat output for a reason - I noticed messages like this one:

```
ImapSync: Local copy of message with uid 1 is marked as deleted
```

So it seems that k9mail had a stale cache of IMAP uids.

I fixed this by invoking 'Clear local messages', i.e. after that all messages were displayed again, as expected.

So thanks for adding this feature back.

Without out it I would have had to clear the Android app cache for k9mail, I assume, likely clearing all accounts setting as well, as a side effect.
