### ISSUE TITLE
Unread emails moved to trash shows them as read there

### ISSUE THREAD

**Issue by Schwefelholz** [k9mail/k-9#4690]
When an unread mail is moved to trash, it shows up there as read e-mail.

### Expected behavior
Unread E-Mails moved to trash should show up as unread there.

### Actual behavior
Unread emails moved to trash are shown read there.

### Steps to reproduce
Delete an unread e-mail and check its status in trash

### Environment
K-9 Mail version: 5.710

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Uncheck 'Account settings > Fetching mail > Mark as read when deleted'.
