### ISSUE TITLE
Allow E-Mails to be instantly deleted (without sending them to trash)

### ISSUE THREAD

**Issue by Schwefelholz** [k9mail/k-9#4692]
I would like to ask for a feature to allow to delete mails directly without sending them to the trash folder first.

### Expected behavior
Allow to choose to delete mails without sending them to trash

### Actual behavior
On deletion, mails are always moved to the trash folder

**Comment by cketti** [comment]
Set 'Account settings > Folders > Trash folder' to 'None'.

Please consider using the [mailing list](http://groups.google.com/group/k-9-mail) to ask for help before assuming something is not working as it should or is a missing feature.

**Comment by Schwefelholz** [comment]
I was aware of this setting, but it is not what I meant.

This setting is kind of a permanent one. I generally want to go deleted E-Mails to trash, but be able to skip trash for certain E-Mails, such as spam or advertisement mails.

**Comment by Schwefelholz** [comment]
Hi,

I was aware of this setting, but it is not what I meant.

This setting is kind of a permanent one. I generally want to go deleted E-Mails to trash, but be able to skip trash for certain E-Mails, such as spam or advertisement mails.

Please take this into consideration.

Regards
Thomas


Am 24. April 2020 22:51:09 MESZ schrieb cketti <notifications@github.com>:

**Comment by cketti** [comment]
I see. Do you have a suggestion on how this should be handled in the UI? I don't like the idea of just adding another button for it. I wouldn't know how to name the action either.

I don't even see an entry for this in Thunderbird's (IMHO overloaded) menu. As far as I can tell the functionality is only available via the keyboard shortcut SHIFT + DEL.

For now I don't think this functionality is important enough to justify including it.

**Comment by Schwefelholz** [comment]
Not sure about the UI, actually. Is it possible to act on this with a
long press on the trashcan button and then provide a new option "Delete
permanently"? That would stick as close to Thunderbird's behavior with
Shift-Delete as I can imagine.

I agree that it is not an essential feature, but it would be nice to have.
