### ISSUE TITLE
crash during start 5.710

### ISSUE THREAD

**Issue by hannesa2** [k9mail/k-9#4694]
I bought me an new Pixel 4 (Android Q) and joined immediate beta program with most recent `5.710`.

First of all: thank you for the app. My whole family uses it since a long time !
And the import settings with new password enter ability **is great** !

But unfortunately it doesn't start anymore. 😞 
It has a database issue !
https://github.com/k9mail/k-9/blob/master/app/core/src/main/java/com/fsck/k9/mailstore/LocalFolder.java#L187-L188

Sorry I don't see more

![image](https://user-images.githubusercontent.com/3314607/80279590-082a6500-86ff-11ea-9ea9-0dd3099a4580.png)

**Comment by hannesa2** [comment]
Btw, what's about the ability to export/import with passwords. I've so much accounts and it's super annoying to enter each password again

**Comment by cketti** [comment]
This is probably the same as #3691.

**Comment by hannesa2** [comment]
Right, I was forced by Google to generate a new password, which I never will remember, It starts now.

Btw, this **password porn from everywhere** destroys the base idea, that only I know how to enter

**Comment by hannesa2** [comment]
Or, I don't know exactly. I switched to stable version

**Comment by hannesa2** [comment]
Ok, enter passwords with new generated Google passwords in `stable`, and then switch to `beta` works now
