### ISSUE TITLE
Import is unrecoverable broken

### ISSUE THREAD

**Issue by hannesa2** [k9mail/k-9#4698]
When I import and don't specify passwords, I run into this

<img width="840" alt="image" src="https://user-images.githubusercontent.com/3314607/80302486-ad4e4780-87aa-11ea-9057-a9257815580f.png">

Then the app is unrecoverable broken

**Comment by szotsaki** [comment]
Possibly a duplicate of https://github.com/k9mail/k-9/issues/4676

**Comment by cketti** [comment]
Duplicate of #3691
