### ISSUE TITLE
Version 5.710 on F-Droid?

### ISSUE THREAD

**Issue by bovergaauw** [k9mail/k-9#4713]
Hi,
I'm using the unstable branch of K-9 via F-Droid, but F-Droid appears not to have version 5.710 yet, which fixes one of the problems I have been having. Is F-Droid aware that version 5.710 exists?
Sorry for posting this question as an issue here, but I didn't know where else to raise it.
Thanks for all the great work!
Bo

**Comment by pejakm** [comment]
The right place to report such issues is here: https://gitlab.com/fdroid/fdroiddata/-/issues

**Comment by cketti** [comment]
Done. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6706
