### ISSUE TITLE
use day of week in message list

### ISSUE THREAD

**Issue by brainchild0** [k9mail/k-9#4715]
Currently, message time in the message list is formatted as either time of day or as calendar date depending on whether the time is of the current day or earlier. Most interfaces in a similar context employ such an approach, but further use the day of the week to format dates from the past week. As such, if the current day were Monday, then the date of a message that is 72 hours old would be represented by a string indicating Friday.

I suggest augmenting the existing formatting logic for this special case.

**Comment by cketti** [comment]
Developer note:
The relevant code is here: https://github.com/k9mail/k-9/blob/5abb0dc71f9daffc63055aeb2ff6006d0e4f1ccb/app/ui/src/main/java/com/fsck/k9/fragment/MessageListAdapter.kt#L156

The new date formatter should be its own class. It needs to support localization. There need to be unit tests.

**Comment by cketti** [comment]
Related issue: #3987

**Comment by brainchild0** [comment]
For English at least abbreviations are likely preferred over formal names, because of the limited space on the mobile screen (e.g. *Wednesday* -> *Wed*). I would not know how this preference generalizes across localizations.

**Comment by cketti** [comment]
See https://developer.android.com/reference/kotlin/java/text/SimpleDateFormat
Use "EEE" for short week day names.

**Comment by simontb** [comment]
I'd like to start contributing to k-9 and this seems like a good first issue for me. Can I take it?

**Comment by cketti** [comment]
@simontb: I'm not sure if @brainchild0 wanted to give it a try. Maybe wait a couple of days for them to respond. Otherwise, it's fine with me.

**Comment by brainchild0** [comment]
@simontb: Please proceed. I suggest removing the call to `DateUtils.getRelativeTimeSpanString` and replacing it with a call to new custom formatter that directly separates the various cases (in a new class per earlier suggestion). Also, leaving a buffer interval would protect against a fringe case in which a day-old message looks only one minute old from the time of the user's wristwatch.

**Comment by simontb** [comment]
> @simontb: Please proceed.

Thanks!

> Also, leaving a buffer interval would protect against a fringe case in which a day-old message looks only one minute old from the time of the user's wristwatch.

I don't get what you mean. Can you provide some examples?

**Comment by brainchild0** [comment]
> I don't get what you mean. Can you provide some examples?

The idea is quite simple even if the comment is badly worded. Instead of setting the threshold to exactly 24 hours, set it to that amount less a few minutes. If the current time is 13:10 on Tuesday, and a message has the date 13:13 on Monday, then avoid expressing the date as 13:13. It's too easy for the user to think that the message arrived a few minutes earlier rather than a whole day past. E.g. maybe a nearby clock is five minutes fast.

**Comment by simontb** [comment]
I would only show the time of the email is from today (like currently) and just replace the date with the day of week for the past 6 stays. What do you think?

**Comment by brainchild0** [comment]
What do you mean by *today*? Do you mean since  the last midnight?

**Comment by simontb** [comment]
Yes. This is also what k-9 does now. Also in your original comment you suggested just formatting the date as day.

Or do you want if it's 10am and an email arrived at 11pm to show "11pm" instead of "Yesterday" or "Thu"? Btw: Should yesterday be a special case or just show the day like for the other dates as well?

**Comment by brainchild0** [comment]
> Or do you want if it's 10am and an email arrived at 11pm to show "11pm" instead of "Yesterday" or "Thu"?

Yes that was my idea, but I hadn't considered the  alternative. Are you aware of any convention one way or the other for other applications in widespread use? 

Whatever the choice, the earlier comment still has relevance.

Suppose it is now 23:59. A message that arrived at at 0:02 the same day ideally shows as the previous day, because the user might consider the current time to be 0:04. Then the inference that the message arrived in the past few minutes is inaccurate.




> Btw: Should yesterday be a special case or just show the day like for the other dates as well?

 I don't see any strong reason for one versus the other. Again, I'm not specifically aware of whether one is more common than the other.   If you insert the word into the function then it is a user string that is bound to the language. Is localization of UI text currently supported, or only English?







> Also in your original comment you suggested just formatting the date as day.

Yes I did but I'm not sure why it would be in conflict with anything else that was stated.
