### ISSUE TITLE
Cannot export K9 Mail settings in other folder than "Download" folder

### ISSUE THREAD

**Issue by jensplixplox** [k9mail/k-9#4717]
K9 Kmail in version 5.170 on a LG K50s smartphone with Android 9 Pie.

1. K9 Mail App > Settings > Backup: Export settings > general settings and settings for my IMAP mail account enabled > EXPORT > Press three-dot-icon at the top in right corner > New folder > Enter name for new folder > Press OK > a message is shown "No Elements" > Press Save > The folder "k9_settings_export" is created within the "Download" folder where I do not want to have my settings being saved.

2. With a file manager I moved the newly created folder "k9_settings_export" one level up from the "Download" folder, so that the newly created folder is on the same folder level as the "Download" folder

3. K9 Mail App > Settings > Backup: Export settings > general settings and settings for my IMAP mail account enabled > EXPORT > Press three-dot-icon at the top in right corner > a message is shown "No Elements" > Press the sandwich icon at the top in the left corner > I can only save my export settings in the "Download" folder which I do not would like to do. I would like to save it in the already existing folder "k9_settings_export" which I moved in step 2 from the "Download" folder one folder level higher: The folder "k9_settings_export" is located on the same folder level as the folder "Download". 

I guess debugging is currently not necessary for this issue. By the way, I currently do not have an USB cable for connecting my smartphone with my Debian box.

**Comment by cketti** [comment]
The behavior of the file picker is specific to your Android version. If something doesn't work as expected please consult your phone's documentation and/or contact the vendor.

**Comment by jensplixplox** [comment]
Thanks, cketti. I just informed the vendor of my smartphone. I tried to find a bugtracking system for Android itself, but for creating bug reports there it seems as if I need a Google account, something that I do no want due to data protection reasons.
