### ISSUE TITLE
gmail authentification failing

### ISSUE THREAD

**Issue by etourmi** [k9mail/k-9#4723]
Hello,

Help!

From all my Android phones and with all my accounts I can't no longer send mails using my gmail accounts in k9 mail (auth plain failed).
I still can connect to my gmail accounts on my Android phones by using the gmail app or any web browser.

Has Google changed something today with k9mail ?

Regards,

**Comment by Alteron** [comment]
same here!

**Comment by FayolleHugo** [comment]
Same here too

**Comment by acknowsrl** [comment]
same here, in thunderbird i switch to OAuth2 from normal password maybe related

**Comment by PDN-FR** [comment]
Same thing on my side.
Didn't change anything on gmail or k9.

**Comment by FayolleHugo** [comment]
To help:
(Command: *sensitive*; response: #3#[NO, [AUTHENIFICATIONFAILED], invalid credentials (Failure)])
I changed nothing for the past many months

**Comment by Fausto1971** [comment]
me too... nothing changed... account unaccessible only from K-9, everything as usual from web client.

Anything changed Uncle Google?

**Comment by candrea21** [comment]
same here

**Comment by Keplyx** [comment]
Happens on my phone as well  (android 7). Cannot fetch from or add a new Gmail account.

Happened on the 5.600 from Google Play, switched to the 5.709 from F-Droid, issue persists.

**Comment by cketti** [comment]
See https://groups.google.com/forum/#!msg/k-9-mail/E9OXD6fq5AQ/6B2MIPvtBgAJ

"Same here" will lead to around 350 people being notified without adding value. Please don't do that.

**Comment by Keplyx** [comment]
But my accounts work in Thunderbird, why not K-9 Mail ?

**Comment by ronohara** [comment]
> same here, in thunderbird i switch to OAuth2 from normal password maybe related

Google also recently broke OAuth2 with Thunderbird 60.x.x  ... forced to upgrade to Thunderbird 68.x.x to handle the new workflow.

Google also recently introduced resetting your 'Allow untrusted mail clients' (or whatever that setting is) if you do not access it via some non Google client for a log time..  Just overwrites your deliberate personal setting. An awful customer interface choice.

**Comment by etourmi** [comment]
ok it works with the 2 step verification.
The new password has to be generated by Google itself.

**Comment by matsuhav** [comment]
My 2-Step Verification enabled account with app password has not affected,
but 'Use your phone to sign in' enabled account had this issue.

I turned off and on "Less secure app access" and finally it's working!

It was on but it seems that Google reset some internal information.

**Comment by jjakob** [comment]
I'm using Gmail with K-9 without issues. Enabled 2FA via authenticator app (TOTP) and generated application-sprcific password for K-9 and my other mail client. (Gmail has had you generate a app-specufuc password for each of your apps for since I remember, at least 5-10 years)

**Comment by Littlemac123** [comment]
![Screenshot_2020-05-30_12-54-11](https://user-images.githubusercontent.com/39867553/83335873-2efc2e00-a29f-11ea-962f-ad149991a1f8.png)
is there a way to fix this with out setting up 2 step Verification

**Comment by rihoward** [comment]
It might be seeing K9 Mail as a "less secure app" depending on your gmail settings.
See:
[https://support.google.com/accounts/answer/6010255](https://support.google.com/accounts/answer/6010255)
If this is the source of the problem then K9 Mail should team should see how it can comply with that.

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
