### ISSUE TITLE
SMTP server "550 Administrative prohibition" response causes K9Mail to remove email from "Outbox"

### ISSUE THREAD

**Issue by Rob58329** [k9mail/k-9#4726]
### Expected behavior
Failed outgoing message should stay in "Outbox" until it is successfully sent.

### Actual behavior
If the remote SMTP server rejects the message with "550 Administrative prohibition", the outgoing email just dissapears from "Outbox", but then appears in "Drafts" instead.
 
### Steps to reproduce
1.  Create New Email and Send (so it appears in "Outbox")
2.  Temporary issue with remote server rejects outgoing email with "550 Adminitrative prohibition"
3.  My issue is that K9Mail then removes outgoing mail from the "Outbox"  (ie. if you missed the brief "Email send fail" message, you have no idea that the Outgoing Message has failed as it is no longer in the "Outbox").

### Environment
K-9 Mail version: Version 5.600

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):   IMAP incoming with SMTP outgoing

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Messages that failed to send are no longer moved to the Drafts folder in current beta versions (5.7xx). 

However, the beta versions require Android 5.0 or higher. We don't have plans to maintain an app that works on Android versions older than that.

**Comment by Rob58329** [comment]
@cketti - very many thanks for your quick reply!

>We don't have plans to maintain an app... version older than (Android 5.0)...

Pity about this, as I do like K9mail, but use Android 4.4.2 - oh well!

Regards, Rob
