### ISSUE TITLE
BroacastReceiver stopped working after update

### ISSUE THREAD

**Issue by piacimosca** [k9mail/k-9#4740]
### Expected behavior
Receiving notification for events as:
com.fsck.k9.intent.action.EMAIL_RECEIVED and
com.fsck.k9.intent.action.EMAIL_DELETED

### Actual behavior
After updating from 5.600 to 5.710  the broadcastreceiver stopped getting notifictions for these intents.
K9 downloads the mails normally, log shows no errors or warnings.
Manual query loads the new mails into 3rd party app.

### Steps to reproduce
1. register a broadcastreceiver with one of the intent filters above
2. wait until new mails arrive

### Environment
K-9 Mail version: 5.710

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): POP3, IMAP

**Comment by cketti** [comment]
This was removed intentionally. See #4278.

What's your use case that needed the broadcasts?

**Comment by piacimosca** [comment]
I see. 
Android launcher integration. When broadcast is received it checks for the new/deleted mails.
In this case, now it will pull.
Was not essential, just did know if it is a bug or feature.

**Comment by cketti** [comment]
You can register a `ContentObserver` to listen for change notifications to the base URI of the message content provider. 

K-9 Mail triggers notifications every time a folder status changes (messages added/removed or message flags change). See https://github.com/k9mail/k-9/blob/5a4a269926116a4f373699510bf868a848cdb8d8/app/k9mail/src/main/java/com/fsck/k9/external/MessageProvider.java#L102-L107

**Comment by piacimosca** [comment]
Yep, I forgot about that option, thank you for pointing it out.
And nicely working.

**Comment by cketti** [comment]
I'm glad it's working for you. Thanks for working on a launcher integration that supports K-9 Mail.

**Comment by piaci** [comment]
And now the option is removed altogether? Will there be any other the get notified when emails arrive?

**Comment by cketti** [comment]
Can you please open a feature request outlining what kind of app you're building and what functionality in K-9 Mail you're looking for exactly?

I'm not opposed to exposing data to third-party apps. However, the user should be asked whether or not they want to grant another app access to emails. 

The old way with permissions in the manifest was never great. Switching to `targetSdkVersion="31"` flagged `android:permissionGroup="android.permission-group.MESSAGES"` as invalid. Chances are changing the permission group would have messed with permissions granted to already installed apps. So I took this as an opportunity to no longer expose `MessageProvider` to third-party apps.
