### ISSUE TITLE
Regression: Missung option to mark message as unread

### ISSUE THREAD

**Issue by stoecker** [k9mail/k-9#4741]
### Expected behavior
Marking a read message as unread.

### Actual behavior
No way to mark a message unread.

### Environment
K-9 Mail version: 5.709

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
In the message list select one or more messages by long-pressing the message or tapping the contact picture. Once a message was selected the actions at the top should include an icon showing an envelope. If all selected messages are unread it will show the closed envelope which means the action is "mark as unread".

When viewing a message, the actions at the top should also include an icon showing an envelope. That's the action to mark a message as unread.
