### ISSUE TITLE
[Feature Request] Add option to "pin" folder in Unified Inbox drawer

### ISSUE THREAD

**Issue by woj-tek** [k9mail/k-9#4745]
### Expected behavior
Currently drawer for Unified Inbox is quite empty - it would be quite handy to be able to ping there any folder from any account without actually including it in main Unified view (for some "busy" folders it's a bit undesirable).

Previously  it was able to open k9 and from main screen with one tap - see whether that folder has messages and with subsequent tap open it.

I think it's somewhat related to #3398

### Actual behavior
Currently one has to open drawer -> switch mail account -> open desired folder from the list

### Environment
K-9 Mail version: 5.710 from f-droid

Android version:
10

Account type (IMAP, POP3, WebDAV/Exchange): 2xIMAP

**Comment by cketti** [comment]
Obsolete because of #5020
