### ISSUE TITLE
Repeated characters when typing addresses

### ISSUE THREAD

**Issue by peterjanes** [k9mail/k-9#4753]
### Expected behavior
After typing a few characters in the address line and then selecting an address, then typing another character, the address entry area should contain only the character that was just typed.

### Actual behavior
After selecting an address after typing three or more characters and typing another character, the characters are re-added to the address area.

### Steps to reproduce
1. Type three or more characters from a name or email address in your contacts.
2. Tap the address to add it to the list of addressees.
3. Type another character in the text entry area and note that the characters you previously typed are included again. (See the screenshot below, where the first address was chosen after typing `p23` and the next character typed was `h`.)

![Screenshot_20200509-235448](https://user-images.githubusercontent.com/193948/81490481-d5c94d80-9250-11ea-8125-59dcd64737b9.png)

(The screenshot shows the Swype keyboard, but behaviour is the same with the stock keyboard.)

### Environment
K-9 Mail version: 5.713

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

(No relevant logs from typing characters, so not attached.)

**Comment by cketti** [comment]
Works for me. What exact device and Android version are you using? Did you also test with the Gboard keyboard?

**Comment by peterjanes** [comment]
Pixel 2 XL
Android version: 10
Android security patch level: January 1, 2020
Google Play system update: April 30, 2020
Baseband version: g8998-00017-1910041814
Kernel version: 4.4.177-ge3f0ab3137ca
#1 Sat Nov 23 02:52:46 UTC 2019
Build number: QQ1A.200105.002

Gboard is the standard keyboard on this phone. Just tried now and the behaviour persists, using both Gboard and Swype.

Gboard version: 9.5.12.317844448-beta-arm64-v8a, updated June 23, 2020

**Comment by cketti** [comment]
Please open a new issue if this is still a problem using a recent version of K-9 Mail.
