### ISSUE TITLE
Crashes when going to Inbox other than Unified 

### ISSUE THREAD

**Issue by WildfireLondon** [k9mail/k-9#4755]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://
Tell us what should happen 

###Expected Behaviour 
App should jump from Unified Inbox to the Inbox of the selected account. 

### Actual behavior
Tell us what happens instead
It crashes 

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.713

Android version:
10

Account type (IMAP, POP3, WebDAV/Exchange):
All accounts POP3 

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
