### ISSUE TITLE
Please new optión very easy

### ISSUE THREAD

**Issue by segarce** [k9mail/k-9#4771]
First of all, congratulations on your program, because it is one of the best mail managers that I have been able to manage.
You only need to add a new function when composing a new message:
"**option to schedule the sending of the email at a specific date and time**" which in some cases comes in handy to have this option. Do you plan to incorporate it in future updates?
Thank you very much for your attention, and I hope that the proposal will be considered and incorporated for future updates.
Greetings.
Sergio García.
segarce@gmail.com
--------------------------------------------------------------------------------------------------------

En primer lugar, felicitarles por su programa, porque es de los mejores gestores de correo que he podido manejar.
Solo le faltaría incorporar una nueva función a la hora de redactar un nuevo mensaje:
"**opción de programar el envío del correo electrónico a una fecha y hora determinada**" que para algunos casos viene muy bien tener esta opción. ¿Tienen contemplado incorporarla en siguientes actualizaciones?
Muchas gracias por su atención, y espero sea la propuesta, considerada e incorporada para próximas actualizaciones.
Un Saludo.
Sergio García
segarce@gmail.com

**Comment by cketti** [comment]
Duplicate of #688
