### ISSUE TITLE
Gmail via imap: sometimes not collected and sometimes not sent 

### ISSUE THREAD

**Issue by PthDE** [k9mail/k-9#4779]
This could also be as per "Don't send mails. The mails stays in the outbox #4470" which is CLOSED but no other status is provided.

K9 running under Android 9 (fully updated) via No-Root Firewall on a Moto G6 phone.
Firewall allows K9 through via rules permitting access for the required IMAP and SMTP servers and their appropriate port settings.
Three email accounts are in operation, Gmail (most used a/c) is the one occasionally failing.

No_Root firewall logs show the 'named' servers for the two fully working accounts. But some logs show K9's Gmail transactions using 'unnamed' IP addresses. Manually resolving (via IP info websites) show them to be 'unnamed' servers at a Google location.

A workaround would be to use a *:587 rule but this then reduces security.
This makes K9 unsuitable for supporting Gmail accounts when using via a firewall.

On collecting Gmail, the firewall logs SOMETIMES show a port 993 access to Google server <*>.1e100.net This using port 993 suggests an email collection attempt but it is not Gmail's IMAP server!!

### Expected behavior
With a firewall set to permit the send and receive server settings as specified in K9's email account settings then email should be successfully received and sent

### Actual behavior
Emails not collected
Email not sent and persists in Outbox

### Steps to reproduce
1. Gmail setup using K9's 'wizard'. This establishes an IMAP a/c. The SMTP server is set using STARTTLS and thus port 587.
2.
3.

### Environment
K-9 Mail version:
5.714

Android version:
9 PPPS29.55-35-18-7
Security patch level: 1 April 2020

Account type (IMAP, POP3, WebDAV/Exchange):
Gmail IMAP using STARTTLS, port 587

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by njeyaakili** [comment]
This would appear to be an issue with the way your have set up your firewall. 

If you check the WHOIS on the 1e100.net domain you'll see that it is owned by google:

   Domain Name: 1e100.net
   Registrant Organization: Google Inc.

The IPnumber that is currently returned for me for the A-record on "gmail.com" is 172.217.164.165. The rDNS on that IPnumber is iad23s69-in-f5.1e100.net.

An email client cannot control, or even account for, how the server side handles their DNS records. 

You can try to account for these things in your firewall setup, but it's tricky with large redundant services. You can leave ports 587 and 993 (submission and pickup respectively) open. If you can bind those ports to a specific application, e.g., K9 in this case (as some of the firewalls can) then your exposure is minimal. If you can't do that binding then you can either leave them open or can constrain them as you have, and watch your firewall logs carefully, researching any rejection and putting in "allows" as necessary.

In any case, I don't see this as something that K-9 (or any other MUA) is responsible to handle (or even could reasonably).

**Comment by PthDE** [comment]
Many thanks for the prompt reply and support.

Google's traffic is huge. So server routing will change dynamically.

This unresolved server-name issue appears to be a Google 'experience'. (e. g. not so with web.de nor gmx.de servers) 

The only option then is with the firewall to freely open the submit and pickup ports. Granularity of the fw settings permit binding to K9. So not so bad.

Many thanks again.

Peter

On 24 May 2020 16:09:50 CEST, njeyaakili <notifications@github.com> wrote:
>This would appear to be an issue with the way your have set up your firewall. 
>
>If you check the WHOIS on the 1e100.net domain you'll see that it is owned by google:
>
>   Domain Name: 1e100.net
>   Registrant Organization: Google Inc.
>
>The IPnumber that is currently returned for me for the A-record on "gmail.com" is 172.217.164.165. The rDNS on that IPnumber is iad23s69-in-f5.1e100.net.
>
>An email client cannot control, or even account for, how the server side handles their DNS records. 
>
>You can try to account for these things in your firewall setup, but it's tricky with large redundant services. You can leave ports 587 and 993 (submission and pickup respectively) open. If you can bind those ports to a specific application, e.g., K9 in this case (as some of the firewalls can) then your exposure is minimal. If you can't do that binding then you can either leave them open or can constrain them as you have, and watch your firewall logs carefully, researching any rejection and putting in "allows" as necessary.
>
>In any case, I don't see this as something that K-9 (or any other MUA) is responsible to handle (or even could reasonably). 
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/4779#issuecomment-633236699
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
