### ISSUE TITLE
F-Droid suggesting old version

### ISSUE THREAD

**Issue by ristein** [k9mail/k-9#4784]
F-Droid is still suggesting version 5.600 and hence doesn't notify users of new updates.

### Expected behavior
notifications about new versions

### Actual behavior
nothing

### Steps to reproduce
1. go to F-Droid and check

### Environment
K-9 Mail version:
now 5.714; 5.703 before i saw this
Android version:
10
Account type (IMAP, POP3, WebDAV/Exchange):
2x IMAP
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
![Screenshot_20200526-173038](https://user-images.githubusercontent.com/55446611/82919723-b29fdd00-9f76-11ea-9479-338f91e46e4b.jpg)

**Comment by cketti** [comment]
This would be an issue to bring up with F-Droid. 

However, 5.714 is a beta version. 5.600 is still the latest stable version. So this is not a bug.

**Comment by cketti** [comment]
Apologies. If you had 5.703 installed and weren't notified about about newer beta versions that can be considered a bug. I don't think there's anything we can do about it. Please bring it up in the F-Droid issue tracker.

**Comment by rms-joe** [comment]
you need to set 
fdroid->settings->expert mode->unstable updates
to get beta versions suggested

**Comment by ristein** [comment]
thanks for the replies.
just wondering why releases since 20 months are called beta

**Comment by rms-joe** [comment]
https://github.com/k9mail/k-9/milestone/24

**Comment by mmm4m5m** [comment]
@cketti - For example, "Frost-for-Facebook" have "test" versions in github releases. It have different application name (with "test" suffix).
This way I am able to install both together at the same time - stable and beta/test version.
Hope this helps. Frost-for-Facebook is github project. Also in F-Droid.
