### ISSUE TITLE
Apply automatic identity selection to forwarding emails

### ISSUE THREAD

**Issue by simontb** [k9mail/k-9#4791]
### Expected behavior
The identity for forwarding an email should be selected from the recipients of the original email. This is similiar to #935 but for forwarding

### Actual behavior
The default identity is used.

### My proposal:
Include `Action.FORWARD` and `Action.FORWARD_AS_ATTACHMENT` to the if-condition here: https://github.com/k9mail/k-9/blob/b9eba6971fa86b95a4855caddbfa7144e5c23884/app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1281-L1287

**Comment by cketti** [comment]
Sounds good to me.

**Comment by simontb** [comment]
Do you want to add the good-first-issue label and we'll wait bit in case someone wants to take it?

Otherwise I can work on it.

**Comment by edwardUL99** [comment]
I can take a look at this?

**Comment by simontb** [comment]
It seems you haven't contributed to k-9 before, so I'd encourage you to do so and provide a PR for this issue.

Note: I'm just the author of this issue, not a maintainer of k-9. But I perceived @cketti as open and helpfull, so go ahead if you'd like to.

**Comment by edwardUL99** [comment]
I am actually quite busy with other projects at the moment so I won't take this, sorry

**Comment by cketti** [comment]
@anadi198 I haven't looked into this yet. If you have tested the change and believe it's enough to accomplish the goal, please open a pull request. I'll have a look then.
