### ISSUE TITLE
UI - Subject line in message list

### ISSUE THREAD

**Issue by Donkey-Doug** [k9mail/k-9#4801]
The subject of the email should be in italic text (instead of starting with >>) and the italic text should be in a slightly different color than white, for example, very discrete grey (the same color used for the dates in the message view).

**Comment by cketti** [comment]
This reads like you're just stating an opinion. Do you want to provide any argument on why we should make the changes you have suggested?

**Comment by Donkey-Doug** [comment]
It takes up less space (that is, there are 2 extra characters for the subject line). However, having a subject line similar to the correspondent name is bad design in my opinion. I guess that the italics is not strictly neccesary if a slightly different color is applied or the other way around, a different color is not neccesary if the subject is italics. I personally believe a combination would look clean.

**Comment by cketti** [comment]
You can change the font size of the sender and/or subject. For most people both the subject and the sender are important. I don't want to also make the text color configurable to de-emphasize one of them.
