### ISSUE TITLE
Google play version 5.6 outdated, user guideline request

### ISSUE THREAD

**Issue by thomsh** [k9mail/k-9#4819]
Hi,
**First I would thanks all contributors of this amazing Android mail client!**
Context:
_I experiencing some trouble with Android 10  because of my 5.6 version from Google Playstore, not a surprise as it's 1906 commits behind master, (2y ago)_

Questions/Request:
- Is it safe to upgrade to latest pre-release from f-droid or Github ?
- Any guideline for user before upgrading ?
- Hard work to release a new stable version & push it on the Playstore ?

**Feel free to close my issue if it's just noise for you**
Have a nice day !

**Comment by cketti** [comment]
Please see this blog post: https://k9mail.app/2020/06/01/Whats-Up-With-K-9-Mail
