### ISSUE TITLE
notification issues

### ISSUE THREAD

**Issue by LupercusBD** [k9mail/k-9#4820]
### Expected behavior
After receiving new mail, a notification should show in the notification area. 
Same as for sending a new mail.

### Actual behavior
No notification (neither sound nor visual) for new mail appears in the notification area.
Also not for sent mail.

### Steps to reproduce
1. This happens when polling for mail, or retrieving mail manually.
2. True for all accounts present in K-9 mail.
3. It worked without problems for years in stable versions, problem is introduced in beta version (first version I used is 5.712).
4. settings in K-9 Mail have been checked (with @cketti) and are correct.

### Environment
K-9 Mail version: 5.716
Android version: 10
Build number: QP1A.190711.020.G973FXXU4CTC9
OneUI version: 2.1
Phone: Galaxy S10
Account types: 2x IMAP, 2x POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/4731210/k9-log.txt)

**Comment by cketti** [comment]
The log contains this: `No notification: Message is in Sent folder`. Apparently you have selected your Inbox folder under 'Account settings > Folders > Sent folder'.
I thought we disabled the ability to do this. But that doesn't seem to be the case :disappointed: 

Presumably you did this to have sent messages be included in threads. See #735 for a feature request on how to accomplish the same but keeping the messages in separate folders.

**Comment by LupercusBD** [comment]
Bingo, thanks !!

Indeed, after changing the the folder under 'Account settings > Folders > Sent folder ' from 'Inbox' to 'Sent Items' for each account all notifications in the notification area came back. So that problem is solved :-)

Two remarks though.
First, I had this setting ('sent' messages to be filed in the 'Inbox') active for something like eight years, including when using the last stable version 5.600. And all that time had working notifications. So apparently this behavior is something that must have been introduced in the later versions, the beta's. Not a problem now I know of that, but probably more people using older versions updating later will encounter this same problem if they too have the inbox folder also as sent folder.

Secondly. 
I followed the idea in that thread #735 and added the new Sent folders to the Unified InBox (alternate name suggestion would be: Unified MailBox, since the mails of all kind of folders in an account can be shown there). Indeed there are now two separate threads, one with the outgoing and one with the received messages, but it is something at least. 
But I really vote for that feature request of having this more global threading within an account. At the minimum it should cover Inbox, Archive, Sent and Draft in my opinion.

**Comment by cketti** [comment]
The 'thread spanning multiple folders' thing is a bit more work. For now we'll change the notification code to not skip notifications when the Inbox is also configured as another special folder. See #4823.

**Comment by LupercusBD** [comment]
Outstanding, thanks  !!

**Comment by achmetinternet** [comment]
Sorry to bring up this post again. I still got the same problem and went through all the steps and nothing seems to be amiss. I am using v5.727.
