### ISSUE TITLE
K9Mail beta 5.715 has no way to move message to spam without opening it

### ISSUE THREAD

**Issue by ibotty** [k9mail/k-9#4821]
### Expected behavior
When an account has some spam messages it would be great to move them to the spam folder without opening them.  That used to be possible with the unhandy long push in K9Mail 5.600.

I would prefer to have this options also in batch mode (marking multiple mails as spam).

### Actual behavior
Open the message (potentially exposing K9Mail to a malicious mail), click the three-dots-button, click refile, click spam.

### Steps to reproduce
1. open unified inbox or any other mailbox
2. try to move a message to spam
3. fail to find an option

### Environment
K-9 Mail version: 5.715
Account type: IMAP

**Comment by cketti** [comment]
"Spam" is still an option in batch mode. Long-press a message in the list or tap the contact picture to enter batch mode. Open the "three dots" menu to see the actions that don't fit on the action bar.

We'll add "swipe to action" eventually. See #1426

**Comment by ibotty** [comment]
Thank you for answering.  My fdroid 5.715 build does not have the batch mode.  When selecting a message, the "three dots" menu only has 'Add star' and 'Select all'.  Am I missing something?

**Comment by cketti** [comment]
"Batch mode" is what is entered when you select a message. You can select more than one and perform operations on all selected messages. If "Spam" and some other actions are not available you're probably in a view where messages from more than one folder are being displayed, e.g. Unified Inbox. See #667.

**Comment by ibotty** [comment]
You are totally right!  That's only a limitation of the Unified Inbox.  Thank you for figuring that out.
