### ISSUE TITLE
Draft folder is missing in folder list?

### ISSUE THREAD

**Issue by ovz93br43v7** [k9mail/k-9#4825]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Normally K9 Mail has found the draft folder of my email provider (mailbox.org) automatically. 

### Actual behavior
But at the moment is the draft folder missing and in the options I can see only "automatic (no folder)" and I can't find the draft folder in the folder list.

Draft folder is still there (I can see it using the browser to log in) but nevertheless I refresh the folder list it is not visible to select it for the draft folder.
I already contacted my mail provider and they have tested this with two android devices and there K9 Mail works as expected with draft folder.

### Steps to reproduce
Sorry I don't know. I reinstall K9 Mail and set up the accounts again if needed, but I assume that then the draft folder is available again.

### Environment
K-9 Mail version: 5.715

Android version: Android 10 QQ3A.200605.001

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

I hope I made this log correctly, if not I can do it again. I had to delete some lines because of privacy.

**Comment by cketti** [comment]
> I hope I made this log correctly, if not I can do it again. I had to delete some lines because of privacy.

Well, the lines that remain don't show a Drafts folder. Did the lines you removed contain an entry for the Drafts folder?

**Comment by ovz93br43v7** [comment]
No just my other email folder names.

**Comment by cketti** [comment]
That's odd. But I don't see how this could be K-9 Mail's fault. If the app is not being told about a Drafts folder on the server how can it display one?

**Comment by cketti** [comment]
Did you input a value under 'Account settings > Fetching mail > Incoming server settings > IMAP path prefix'? Or selected "Show only subscribed folders" on the same screen?

**Comment by ovz93br43v7** [comment]
> That's odd. But I don't see how this could be K-9 Mail's fault. If the app is not being told about a Drafts folder on the server how can it display one?

I don't know. Some weeks ago I had my draft folder in the app and as I said on the webbrowser it is still there.

> Did you input a value under 'Account settings > Fetching mail > Incoming server settings > IMAP path prefix'? Or selected "Show only subscribed folders" on the same screen?

No both settings are not activated.

I make again a Log, during updating folders and try to find/select the draft folder. I removed again ~1000 folder entries but no "draft" folder could be found in the log.
[k9-log_new.txt](https://github.com/k9mail/k-9/files/4735824/k9-log_new.txt)

When you also don't have any idea I will set up K9 mail completely new and probably then the draft folder is back...

**Comment by cketti** [comment]
> When you also don't have any idea I will set up K9 mail completely new and probably then the draft folder is back...

If that works, please include another log in this issue. It should contain the list command that is being sent to the server (`LIST "" "*" RETURN (SPECIAL-USE)` in the latest log).

**Comment by ovz93br43v7** [comment]
I started debugging mode and I setup my account again in K9. This time I had to select every folder (sent, draft, archive, spam etc.) myself (formerly I think this was automatically). Positive: My draft folder is back!
After that I downloaded the log file and stopped afterward the debugging in k9.

I checked the log file but there is no `LIST` command, and many privacy relevant informations which I have to delete before uploading.

I can try it again, but I don't know what I have done wrong. (I have done linke you described: USB debugging, ADB, PID, grep...)

**Comment by cketti** [comment]
Android's uses a ring buffer for logging. Old entries will get overwritten eventually.

You can use `adb logcat --pid=<PID> > k9-log.txt` (without the `-d`) to continually log into a file. Do this before doing any action that you want to log. To end writing the debug log to the file press CTRL + C.

**Comment by ovz93br43v7** [comment]
Ok I have again set up my account in K9 with logging as described by you:
I found one lines with the `LIST` command:

`06-06 12:43:55.123 26824 27004 V ImapConnection: conn4474243>>> 3 LIST "" "*" RETURN (SPECIAL-USE)`

If you need the complete log I have to wipe out privacy relevant information first.

**Comment by cketti** [comment]
Well, that looks exactly like the LIST command that was sent before. I don't see why the Drafts folder was not part of the server's answer before but is now.

I don't think we'll find out. If it's now working for you, please close this issue.
