### ISSUE TITLE
Why not use JavaMail?

### ISSUE THREAD

**Issue by wangsuicheng** [k9mail/k-9#4828]
https://github.com/javaee/javamail/releases
Is the implementation of this library buggy or not ideal?

**Comment by cketti** [comment]
Are you asking why JavaMail wasn't chosen when the app was created over 10 years ago?
Are you suggesting we should switch to JavaMail now?
Are you asking for advice on which mail implementation to use for your own project?

**Comment by wangsuicheng** [comment]
Are you asking for advice on which mail implementation to use for your own project?
-----
Yes, ask for advice. Is JavaMail integration faster for project?
or may be k9 is more powerful than it?

**Comment by cketti** [comment]
I feel like I should be charging for consulting. But okay, here you go:
Use JavaMail, now [Jakarta Mail](https://eclipse-ee4j.github.io/mail/). K-9 Mail's mail protocol implementations are not written as reusable libraries.
