### ISSUE TITLE
#Bug menu for non-standard notification sound are disappear.

### ISSUE THREAD

**Issue by XAndrey** [k9mail/k-9#4830]
### Expected behavior
Like in version 5.600, in sound menu there are 2 tabs: melody, music (in Huawei smartphone) - it's standard phone menu.

### Actual behavior
In newer verions 5.714-5.716 there are non-native sound menu - there are only basic notification sounds and NO music and other sounds.

### Steps to reproduce
1. in versions 5.600 go to settings-> mailbox settings ->notifications->melody - there are 2 tabs: "melody" and "music"
2. in versions 5.716 in settings "new mail ringtone"
![Screenshot_20200606-235758](https://user-images.githubusercontent.com/20306883/83954434-e4a41f80-a851-11ea-9d0c-bec75cbd9768.png)
![Screenshot_20200606-235931](https://user-images.githubusercontent.com/20306883/83954435-e7067980-a851-11ea-8204-9502bf940343.png)

 - there are no any tabs, there are only one list of sounds.

### Environment
K-9 Mail version: 5.714-5.716

Android version: 7.0, EMUI 5.0.3

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
In 5.600 we were using the system's notification sound picker which apparently is heavily modified by Huawei. This system component was deprecated and we're using the suggested replacement now. For most Android versions the old and the new component look exactly the same.

We have no plans to change this.

**Comment by XAndrey** [comment]
So, how can i use other sounds?

**Comment by cketti** [comment]
How to add notification sounds is specific to the Android version you're using.

**Comment by XAndrey** [comment]
In my Android 7.0 i was able to chose custom sound with old component, but **cannot** do this with your new component. It's is same Android, same EMUI, same smartphone. So i think - it's bug, because it was working in 5.6, but now it doesn't work.
