### ISSUE TITLE
Restore the "home" screen with all accounts and mail counts 

### ISSUE THREAD

**Issue by olberger** [k9mail/k-9#4834]
It seems that since 5.706 the home screen listing all accounts (with unread mails and stars count for each account) has disappeared.

This offered a really handy way to check for new mail on all accounts in one single refresh click.

Now, there's the need to go and select each account, switching views, or the unified inbox view. But I don't want to see at once all message subjects, only message counts for all accounts, in a single screen. The option to hide the unified inbox could have led back to the old screen, but no luck :-/

Please restore (optionally) the old feature.

Thanks in advance.

**Comment by cketti** [comment]
When displaying the list of accounts in the drawer you can swipe down to refresh all of them.
For the unread count see #4515.

We're not going to add back a dedicated accounts screen.

**Comment by olberger** [comment]
Too bad, but thanks for the quick feedback.

**Comment by Virgyxx** [comment]
> When displaying the list of accounts in the drawer you can swipe down to refresh all of them.
> For the unread count see #4515.
> 
> We're not going to add back a dedicated accounts screen.

Swiping down does not work for me
