### ISSUE TITLE
Autocrypt header always transmitted

### ISSUE THREAD

**Issue by maniusq** [k9mail/k-9#4836]
### Expected behavior
Header is only transmitted if activated. If I choose another identity, my main mail address is always leaked. (e.g. encryption not desired)

### Actual behavior
Autocrypt header is always transmitted, regardless of whether Autocrypt is activated or not.

### Steps to reproduce
1. Configure OpenPGP
2. Disable Autocrypt
3. Send email
4. Check header

### Environment
K-9 Mail version: 5.600 (26000)

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange):
All types

**Comment by cketti** [comment]
OpenPGP is currently not a per-identity setting. See #942.

**Comment by maniusq** [comment]
@cketti Thanks for your answer, but that isn't the problem. If you disable Autocrypt, there should be no Autocrypt header.

Otherwise the option "Disable Autocrypt" is useless - isn't it?

**Comment by cketti** [comment]
@maniusq: There is no way to disable Autocrypt other than disabling OpenPGP completely. Which setting do you change hoping to disable Autocrypt?

**Comment by maniusq** [comment]
This one: https://www.openkeychain.org/assets/img/autocrypt-mutual.png

For me (and other), deactivating Autocrypt is the logical consequence of this.

**Comment by cketti** [comment]
This setting only changes when messages will be automatically encrypted. The Autocrypt header is sent with every message regardless. See https://k9mail.app/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt.html for more details.

**Comment by maniusq** [comment]
Then this is an incorrect implementation of Autocrypt or the multiple identities. If the main domain is always transmitted, I don't need to create multiple identities. Then what do I want to hide? 🤔

**Comment by ws-0-1** [comment]
My hidden primary identity still gets leaked by that enforced Autocrypt header, both by K9-Mail/Thunderbird android and by Thunderbird desktop.  So the main problem is still neither acknowledged nor solved.  For the record, as a user, I don't want to globally disable encryption. I don't want my primary email address exposed. As it is implemented, this header is an invitation for spammers.
