### ISSUE TITLE
Build performance: Drop Jetifier

### ISSUE THREAD

**Issue by runningcode** [k9mail/k-9#4850]
Once https://github.com/splitwise/TokenAutoComplete/pull/399 is merged and released, we can drop the jetifier which should lead to improved build speeds and less space taken up by all the jetified artifacts.

**Comment by mgod** [comment]
https://github.com/splitwise/TokenAutoComplete/releases/tag/4.0.0-beta01 should actually be fine for production use - it's just the AndroidX/drop jetifier changes. The only reason I'm keeping it marked as beta is that there are a few other behavior changes I'm working on that I want in the main 4.0 release.

**Comment by cketti** [comment]
We switched to TokenAutoComplete 4.0.0-beta01 with #4891.
Jetifier was disabled with #4895 so this issue can be closed.

Side note: I'd love a TokenAutoComplete 4.0.0-beta02 with https://github.com/splitwise/TokenAutoComplete/pull/403 included.
