### ISSUE TITLE
Headers not parsed

### ISSUE THREAD

**Issue by simontb** [k9mail/k-9#4851]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Headers like subject should be parsed and shown in the according fields

### Actual behavior
Subject is "(No Subject)" and headers are displayed as message body. Thought this was related to another issue, but in https://github.com/k9mail/k-9/issues/4846#issuecomment-648736286 I was adviced to open a new one.

### Steps to reproduce
See attached email:  [message.zip](https://github.com/k9mail/k-9/files/4825798/message.zip)

### Environment
K-9 Mail version: 5.716

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This message is broken in all sorts of ways. There are two CRLFs after `Content-Transfer-Encoding: quoted-printable
`. For the parser that ends the header and starts the mail body. But what follows looks like it should be part of the header, too.

I'm guessing this is another case of one system sending out a broken message and another system trying to fix it up. In this case the "fix" seems to consist of inserting a `Content-Transfer-Encoding: quoted-printable` header and encoding the remainder of the message using quoted-printable. Further down there's also `Content-Transfer-Encoding: 8bit`. I assume this was the original header and the other one was injected at a later stage.

There's really nothing sensible K-9 Mail could do here. The bug needs to be fixed on the sending side.

**Comment by simontb** [comment]
Too bad. Thanks for looking into it.
