### ISSUE TITLE
Standalone PGP Integration

### ISSUE THREAD

**Issue by BeingDatta** [k9mail/k-9#4853]
Can we have standalone pgp integration inside k9mail like its there inside P=P (pretty easy privacy mail) so that we dont have to depend on openpgp keychain app ?

Regards.

**Comment by cketti** [comment]
Yes, the OpenKeychain authors have expressed interest in licensing their code under the Apache 2.0 license so it can be included in K-9 Mail. No timeline, though.

**Comment by BeingDatta** [comment]
thanks for the feedback friend
