### ISSUE TITLE
A strange German translation inconsistency

### ISSUE THREAD

**Issue by cyclingcat** [k9mail/k-9#4858]
Hi there,

I'm currently using K-9 Mail v5.600 (installed from F-Droid) on three devices: a bq Aquaris M4.5 smartphone (Android 5.1), a Cubot Quest smartphone (Android 9) and a Samsung Galaxy Tab A 2016 tablet (Android 8.1). The language is set to German on each device. The inbox screen shows a translation inconsistency: The case of the first letter of the German word "in" depends on the device (or the Android version?)

See the screenshots:

** Cubot smartphone and Samsung tablet:**
![Android_9](https://user-images.githubusercontent.com/32601012/85932021-e600bf00-b8c8-11ea-9a83-b902b1b7771e.png)

**bq smartphone:**
![Android_5](https://user-images.githubusercontent.com/32601012/85932011-d6817600-b8c8-11ea-90e9-7951117e6f9c.png)

Strange, isn't it? The correct spelling is shown on the latter screenshot with the lower-case "i". What's going on here?

The cycling cat

**Comment by cketti** [comment]
We were appending the output of `DateUtils.getRelativeTimeSpanString()` to "Next poll", or in your case "Nächster Abruf". Looks like that output is different depending on the Android version.

But this text has been removed and is no longer part of the app. Current beta versions are not affected by this. Closing this issue.
