### ISSUE TITLE
Duplicated folders after settings import

### ISSUE THREAD

**Issue by GarryMoveOut** [k9mail/k-9#4860]
I don't know why but only one account (outlook.com) from four (outlook.com, hotmail.com, gmail.com, gmail.com) has duplicated folder/directories in folders after settings import to clear fresh k9. This bug didn't happen once. I reproduced it many times but duplicated folders changes each time. Before import I cleared all data of k9 app and remove app and install again from f-droid.

### Expected behavior
Complete not duplicated folder list (received, SPAM, sent etc.) of account.

### Actual behavior
Folders are duplicated ("odebrane" - received in English):
![Screenshot_2020-06-30-11-01-42-637_com fsck k9](https://user-images.githubusercontent.com/6260261/86108752-da2d1c80-bac3-11ea-8fc5-adb592b0322a.png)
Also folders Deleted, K9MAIL_INTERNAL_OUTBOX not visible on screenshot are duplicated.

anonymized export of settings:
https://gist.github.com/GarryMoveOut/c86a9e2b30e053191e5a5864bf01e455

### Steps to reproduce
1. On phone 1 create backup copy and export
2. On phone 2 load backup and import
3. Show folders of account

### Environment
K-9 Mail version: 5.6 (also on older versions but I do not remember numbers)

Android version: 
Tested on:
Xiaomi Redmi Note 2, Android 5.0.2
Samsung J510, Android 7.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
All accounts are IMAP.

**Comment by cketti** [comment]
5.600 contains a couple of bugs related to duplicate folders. They have been fixed with recent beta versions. Check out the latest beta version 5.717. https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68
