### ISSUE TITLE
Duplicated email in sent folder

### ISSUE THREAD

**Issue by GarryMoveOut** [k9mail/k-9#4861]
When I send email from Outlook.com account (IMAP/SMTP), sended email is duplicated on sent directory (on both server and client side). Probably because k9 saves sent email to sent directory and server automatically saves email to sent directory also. How to disable in k9 settings to do not save sent emails to sent directory?

**Comment by cketti** [comment]
When using the current beta versions (5.7xx) this can be disabled under 'Account settings > Sending mail > Upload sent message'. It's only possible to disable it in 5.600 by setting 'Account settings > Folders > Sent folder' to 'NONE'.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
