### ISSUE TITLE
Refuse to send unencrypted/plain text.

### ISSUE THREAD

**Issue by Newbie1980** [k9mail/k-9#4866]
Hope its okay to ask this. 
I am using an old version of K9. 

I found when I used the newer version with open keychain it would easily not encrypt and send plain text. Which defeated the purpose intended. 

Is there a way in current or newer version where it could be set so that it refuses to send unencrypted or plain text? 

For my uses it really needs to be encrypted all the time. 

Any help or thoughts appreciated.

**Comment by cketti** [comment]
K-9 Mail is not an "encrypted mail only" client and we have no plans to make it one in the foreseeable future.

**Comment by Newbie1980** [comment]
I didn't mean change the whole app for me but to allow a setting or button to enable such?

I know I am not the only who who has sent unenrypted stuff by accident.

Id you look at my old posts from 2016 when I asked back then the app was flawed in many ways. "Always encrypt" simply didnt work. 

Surely you can see the point tho if encryption is not working then may as well be using gmail or something??

**Comment by cketti** [comment]
[Why not add an option for that?](http://neugierig.org/software/blog/2018/07/options.html)

It's not that what you're asking for is unreasonable. I'm saying K-9 Mail is not the client for your use case.

**Comment by Newbie1980** [comment]
Well the doggy with the eyes covered & talk about PGP would lead one to believe encryption is an integral part of it? 

Im more confused now than I was back in 2016.

Also I don't think you are acknowledging said option for "always encrypt" did not work? 

& Am I wrong in that I'm taking the responses as a little dismissive??

**Comment by cketti** [comment]
> Also I don't think you are acknowledging said option for "always encrypt" did not work?

"Always encrypt" is no longer part of the app. I'm not going back to investigate whether or not it worked properly in a previous version of the app.
If you're composing a message with a current K-9 Mail version and it's indicating that the message will be encrypted, but then a plain text message is sent, that would be a bug. In that case we'd love to get a bug report with steps to reproduce.
