### ISSUE TITLE
File attachment name broken - Filename scrambled / wrong encoding

### ISSUE THREAD

**Issue by manne01** [k9mail/k-9#4876]
### Expected behavior
I want file attachments in mail drafts/sent mails to be shown and opened correctly even if the filename contains german umlauts (äöü...). I want k9mail to cope correctly even if they have badly encoded filenames.

### Actual behavior
If I add an attachment from k9mail everything works as intended. As soon as I use another client to add a file attachment to a draft email and store it to the imap drafts folder, this attachments name is not properly downloaded via imap from my (gmx) draft folder to k9mail. The same happens if i add the attachment and just send it. k9mail is not showing the mail attachment correctly in the sent mail and in the inbox if I send it to myself.
Instead the filename is scrambled in a more or less URL/percent-encoded way and is shown as a attachment with the name (example) UTF-8''%45%69%6E%76%65%72%73%74%C3%A4%6E%64%6E%69%73%65%72%6B
I also cannot open the file with k9mail.

If I url encode this I get back `UTF-8''Einverständniserk` which is parts of my original file name "Einverständniserklärung.pdf"

I actually add the attachment to the mail draft using Thunderbird 68.10.0 (64-Bit) with Windows OS.
As soon as I sync my imap in k9mail, I can see the mail draft including the broken attachment

Note: When I add attachments without umlaut characters, k9mail shows the attachment name as intended.
Note: When I log on to my email provider web-account the attachment is always shown correctly! So the provider seems to be more robust to such filenames.

### Steps to reproduce
1. use thunderbird (on windows) to add a file attachment with umlauts to some email draft
2. sync the mail account with imap
3. use k9mail to also sync imap
4. watch the draft or to send it to somebody
5. check the attachment file name, it is scrambled

### Environment
K-9 Mail version: 5.600
Android version: 10
Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
This bug is fixed in current beta versions (5.7xx). See #1466.

See also: [How do I become a beta tester?](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68)
