### ISSUE TITLE
Deleting messages make them disappear

### ISSUE THREAD

**Issue by iteqla** [k9mail/k-9#4881]
### Expected behavior
When tapping the trash icon, the message should go to the trash folder and that should be reflected on the webmail too.

### Actual behavior
Tapping the trash icon makes the message disappear comoletely from the app. Yet via webmail the messages are only marked as delete but still in the inbox.

### Steps to reproduce
1. select a message
2. tap the trash icon
3. check app and webmail

### Environment
K-9 Mail version: 5.717

Android version: 10

Account type: IMAP

**Comment by kolbma** [comment]
There exist 2 settings in your Account settings under the 3rd submenu... Like "Message requests/Download" ... Delete when deleted in Server and Delete also in Server. I have non-English App, so translated by myself.

**Comment by kolbma** [comment]
Ah and a 3rd "the folder expunge"...

**Comment by cketti** [comment]
This is a special feature of IMAP. You can configure K-9 Mail to not "expunge" messages marked as deleted by setting `Settings > [Account] > Fetching mail > Erase deleted messages on server` to `Manually`. K-9 Mail does not support displaying such messages or marking them as "not deleted". 
Support for not expunging messages immediately will be removed in a future K-9 Mail version. If you need to be able to use this IMAP feature you'll have to look for another client.

The typical way of handling messages deletion is to move them to a Trash folder. K-9 Mail does this by default if a Trash folder is configured by the server or manually under `Settings > [Account] > Folders > Trash folder`.
