### ISSUE TITLE
K-9 Mail not receive email unless i open it and refresh.

### ISSUE THREAD

**Issue by junomarian** [k9mail/k-9#4892]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen : Receiving realtime e-mails.

### Actual behavior
Tell us what happens instead :  
K-9 Mail not receive email for both yahoo and yandexmail unless i open k-9 app and refresh.
### Steps to reproduce
Battery Optimization is turned off.

Background Network Sync on.

Fetching mails local folder size 25.

Incoming servers.

Yahoo: imap.mail.yahoo.com.

Still i don't receive new mails unless i open app and and refresh.

### Environment
K-9 Mail version: version 5.717
Android version: Android 10 AOSP rom.

Account type (IMAP, POP3, WebDAV/Exchange):
Yahoo and yandex imap.
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Did you set 'Account settings > Fetching mail > Folder poll frequency' to something other than 'Never'?

If so, please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
