### ISSUE TITLE
Email opening slide in animation totally lags

### ISSUE THREAD

**Issue by ryder203** [k9mail/k-9#4894]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Smooth animation

### Actual behavior
Laggy stuttering animation

### Steps to reproduce
1. open K9 mail
2. open an e-mail from inbox
3. see animation lag

### Environment
K-9 Mail version: v5.717

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This is because creating a `WebView` instance for the first time can be quite slow. 

It's a known problem we will consider when modernizing the message view code. This issue isn't necessary as reminder. Closing.
