### ISSUE TITLE
[feat. request] Different notification settings for 1,2nd class folders

### ISSUE THREAD

**Issue by diggy128** [k9mail/k-9#4896]
Since we can set different classes in folders and set different sync, push, poll settings for each, I believe it would make sense to also have different notification settings per class.
That would allow to be able to have different mail ringtone for 1st class folders (e.g. bills, personal email) and different ringtone for 2nd class (mailing lists, etc)

**Comment by cketti** [comment]
I'd rather do this using notification rules. See #3675.

Also I want to get rid of folder classes. See #2669.
