### ISSUE TITLE
This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.

### ISSUE THREAD

**Issue by anushruti11** [k9mail/k-9#4898]
### Expected behavior
After cloning project should successfully run on all versions of Android Studio.

### Actual behavior
It's showing an error message"This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer."

### Steps to reproduce
1.Clone this repository to Android studio version which before "4.0.0".
2.Let the gradle build finish.
3.You will see the error message.

### Environment
K-9 Mail version:

**Comment by cketti** [comment]
We typically don't use alpha or beta versions of the Android Gradle Plugin (AGP). So if you stay with the latest stable Android Studio version you should always be able to build K-9 Mail. However, we won't limit ourselves to even older AGP versions, so older Android Studio versions can be used. That means right now you'll have to use Android Studio 4.0 or newer.

May I ask why using Android Studio 4.0 doesn't seem to be an option for you?

**Comment by anushruti11** [comment]
Yes we should use stable version but it should also other versions too .Because I have also tried other that projects run successfully on this version and that's completely fine if we shouldn't consider this as an issue.
