### ISSUE TITLE
Missing the button to fetch mails?

### ISSUE THREAD

**Issue by hman2** [k9mail/k-9#4904]
### Expected behavior
When looking through the inbox, there should be a button to fetch mail (fetching is set to manual), but I don't see it.

Tell us what should happen

### Actual behavior
No button

### Steps to reproduce
1. Set to fetch mails manually
2. Go to the inbox
3.

### Environment
K-9 Mail version: 5.716 running on Fairphone Open OS (AOSP Nougat). When the update to 5.716 was installed, I lost the K-9 icon on the main Android window, so I created this anew. For some reason unknown, I cannot make K-9 start in combined view of both inboxes (two mail accounts), it is always one of the two. But now I miss the fetching button... I do not want to switch to automatic fetching, due to lots of spam.

If it's just a setting that was lost, please advise.

Thanks 
hman

Android version: FP Open OS 19.11.2 (AOSP 7.1.2)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (two)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Swipe down on the message list to refresh a folder. Swipe down on the list of folders in the side drawer to refresh the currently selected account. Swipe down on the list of accounts in the side drawer to refresh all accounts.

**Comment by hman2** [comment]
Thanks, that worked.
