### ISSUE TITLE
Folders got duplicated when I set up the account in k-9

### ISSUE THREAD

**Issue by philip-bl** [k9mail/k-9#4913]
I've just installed the beta version from Google play on my new phone, set up my @heregoesmypersonaldomain.me, which is actually hosted by Yandex and uses imap.yandex.ru and smtp.yandex.ru. As a result, some of the folders got duplicated, and in a weird way.

I had "Отправленные" for sent messages, now I have "Отправленные" and "Отправленные_0". Same for "Удаленные", "Черновики", "Спам", "Исходящие". And for some reason, some of the emails I had previously sent remained in "Отправленные", but most of them got moved to "Отправленные_0". This is very annoying. I hope nothing got lost, I worry something did. I haven't tried to reproduce and will not.

### Environment
K-9 Mail version: 5.718

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): Imap

**Comment by cketti** [comment]
K-9 Mail doesn't create new folders on the server. It's likely that something else is causing this issue.

You can configure which folders K-9 Mail uses for special folders under `Settings > [Account] > Folders`. By default K-9 Mail uses the information provided by the server (setting value "Automatic"). If the server provides new information K-9 Mail will switch special folders locally, too.

Without steps to reliably reproduce the issue there's nothing we can do.
