### ISSUE TITLE
Message not scrolling

### ISSUE THREAD

**Issue by Saphar** [k9mail/k-9#4915]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I try to open a long email message and I try to scroll down to the bottom of it, to read the whole message. This is happening on a non-touch device Sonim XP3800 with a small screen.

### Actual behavior
I am not able to scroll only to the beginning of the message.

### Steps to reproduce
1. Open a mail message on a non-touch device with small screen.
2.
3.

### Environment
K-9 Mail version:
5.719
Android version:
8.1.0
Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Phone:
Sonim XP3800

**Comment by cketti** [comment]
We'd be happy to accept code contributions that improve support for such devices, but we're not going to spend time on it ourselves.
