### ISSUE TITLE
Next poll 10 hours ago

### ISSUE THREAD

**Issue by liotier** [k9mail/k-9#4937]
Version 5.600

Moving to the neighboring timezone, the clock jumped two hours in the past, resulting in this heading atop the message list: "Next poll 10 hours ago".

Of course, K-9 shouldn't second guess the system clock - so a correct display is not possible. Nevertheless I suggest checking that the "next poll" time is in the future, and not displaying the erroneous message otherwise.

**Comment by cketti** [comment]
This should no longer be an issue in current beta versions (5.7xx). See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68
