### ISSUE TITLE
SSLProtocolException after upgrading to Android 10 (and dovedot 2.3.4.1?)

### ISSUE THREAD

**Issue by FAlterSoft** [k9mail/k-9#4939]
After upgrading an imap server to 2.3.4.1 from older dovecot version (actually debian upgrade), my mother's phone's k9 stopped working (some samsung phone). I didn't deep-dive into it but I remember that it was something related to encryption.

Not I upgraded my own phone (fairphone 3) from andoid 9 to 10. Same problem. Mails are not being synchronized any more. There is no prominent error message, but on the folder list I can read "SSLProtocolException: SSL h"

On server side, it says:
Sep 10 22:30:08 [servername] dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=[ip], lip=[ip], TLS handshaking: SSL_accept() failed: error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter: SSL alert number 47, session=<[...]>

With verbose SSL logging:

Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x10, ret=1: before SSL initialization
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: before SSL initialization
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: before SSL initialization
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: before SSL initialization
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: SSLv3/TLS read client hello
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: SSLv3/TLS write server hello
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: SSLv3/TLS write change cipher spec
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: TLSv1.3 write encrypted extensions
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: SSLv3/TLS write certificate
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: TLSv1.3 write server certificate verify
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: SSLv3/TLS write finished
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2001, ret=1: TLSv1.3 early data
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: TLSv1.3 early data
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: TLSv1.3 early data
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: TLSv1.3 early data
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: TLSv1.3 early data
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL alert: where=0x4004, ret=559: fatal illegal parameter
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL: where=0x2002, ret=-1: error
Sep 10 22:44:01 [server] dovecot: imap-login: Debug: SSL error: SSL_accept() failed: error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter: SSL alert number 47
Sep 10 22:44:01 [server] dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=[ip], lip=[ip], TLS handshaking: SSL_accept() failed: error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter: SSL alert number 47

The issue imo only happens in k9 on android 10, not in k9 on earlier android and not on any non-android mail cliend (never tested another client on android 10 though). Seems like something changed in android 10.

**Comment by cketti** [comment]
K-9 Mail uses the platform's TLS stack. Your server might be using ciphers and/or TLS versions not supported by your Android device(s). See https://developer.android.com/reference/javax/net/ssl/SSLEngine

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
