### ISSUE TITLE
autentication failure (not gmail)

### ISSUE THREAD

**Issue by DoctorSubtilis** [k9mail/k-9#4965]
Today, on my repaired Motorola e6 plus, I cannot login on my imap account, or better I can login into one, but not into another of my (NOT gmail nor yahoo) email accounts.  
I get an autentication error message, but I am sure that imap server, user and password are correct. They work in K9-mail on another smartphone and on my PC.  
Note that the password is transmitted insecurely (this is not my choice): maybe is this the problem?  
But, one mont ago, K9-Mail used work perfectly on this my smartphone with this account...

EDIT
I think that the problem is **secure connection**, because, after adding a new account with secure connection, it works: 2 out of 3. The not working is without security.

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
