### ISSUE TITLE
Transifex messes up strings

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#5008]
**Describe the bug**

The strings `unknown_sender` and `unknown_recipient` are broken on Transifex and can not be translated properly. See screenshot below. Transifex recognizes the `<...>` part in `<![CDATA[<Unknown Recipient>]]>` as a tag. Additionally, I think translators should not be bothered with the `CDATA` part.

**Screenshots**

![image](https://user-images.githubusercontent.com/5811634/96018522-ac3dcf00-0e4b-11eb-8b47-9d121ffc8f42.png)

**Environment (please complete the following information):**
 - K-9 Mail version: master

**Suggestion**
Change the string to something like `&lt;Unknown Recipient&gt;`

**Comment by anadi198** [comment]
> **Suggestion**
> Change the string to something like `&lt;Unknown Recipient&gt;`

I've done this bit, should I make a PR(Nothing else needs to be changed apart from the two mentioned strings?)? @cketti

**Comment by cketti** [comment]
@anadi198: Please try to keep in mind that asking questions is demanding time from the maintainers. In cases like this where no important design decisions are involved just open a PR. It's much easier to provide feedback if there's something concrete to look at. We'll also be able to test the change on a device.

**Comment by anadi198** [comment]
@cketti I apologise for that, I will follow your advice and make a PR from now on unless important decisions are involved. Thank you for explaining.
