### ISSUE TITLE
Move "Unified Inbox" from account list to folder list

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5020]
Instead of having "Unified Inbox" be an item in the account list, display it above the folder list in the side drawer.

**Comment by toppk** [comment]
this is done as with PR #5122

**Comment by cketti** [comment]
> this is done as with PR #5122

Thanks :+1: I keep forgetting to close associated issues.

Note: If you add a single line like "Closes #xyz" or "Fixes #xyz" to a pull request description this will be done automatically once the PR is merged. See e.g. PR #5110
