### ISSUE TITLE
UI Remake in Flutter/Jetpack Compose

### ISSUE THREAD

**Issue by Auties00** [k9mail/k-9#5045]
Hello, one of my friends introduced me to the k9 mail client and I'd like to contribute. Wouldn't it be a nice idea to have a remake of the UI in Flutter while keeping the business logic written in Java? Flutter is now stable, but maybe Jetpack Compose, which was inspired the Flutter, would be a better fit, though it's still in alpha. What do you think?

**Comment by cketti** [comment]
Flutter: no, thanks
Jetpack Compose: probably, at some point in the future

In many parts of K-9 Mail's code base "business logic" is rather tightly coupled to UI code. We'd welcome contributions to untangle this. But chances that an externally contributed UI rewrite will get merged are close to zero.

If you just want to experiment with one of these UI frameworks it's probably much easier to start a project from scratch.

**Comment by Auties00** [comment]
> Flutter: no, thanks
> Jetpack Compose: probably, at some point in the future
> 
> In many parts of K-9 Mail's code base "business logic" is rather tightly coupled to UI code. We'd welcome contributions to untangle this. But chances that an externally contributed UI rewrite will get merged are close to zero.
> 
> If you just want to experiment with one of these UI frameworks it's probably much easier to start a project from scratch.

Thanks for your answer! I understand, but I have a question, obviously if you have the time to answer me:
Why no thanks to Flutter?

**Comment by cketti** [comment]
> Why no thanks to Flutter?

- Dart would be yet another language. We already have Java + Kotlin.
- It's a non-JVM language so there's non-negligible costs associated with bridging the Dart and Java/Kotlin worlds.
- Flutter doesn't seem to have much buy-in from Google's Android teams. I'm willing to bet (small amounts of money) that Flutter won't be around in a meaningful way 10 years from now.

**Comment by Auties00** [comment]
> > Why no thanks to Flutter?
> 
> * Dart would be yet another language. We already have Java + Kotlin.
> * It's a non-JVM language so there's non-negligible costs associated with bridging the Dart and Java/Kotlin worlds.
> * Flutter doesn't seem to have much buy-in from Google's Android teams. I'm willing to bet (small amounts of money) that Flutter won't be around in a meaningful way 10 years from now.

Linking Dart and Java/Kotlin is so easy, but yes, I do agree on the fact that placing such a huge bet on a new framework, that Google's Android team despises so much, is not such a great idea as of now
