### ISSUE TITLE
Move account selection icons to the bottom

### ISSUE THREAD

**Issue by nkakouros** [k9mail/k-9#5046]
**Is your feature request related to a problem? Please describe.**

I have installed the latest release of k9 to test the new interface. It looks modern and nice. Yet, I already have pain in my right hand from switching accounts. I have a phone with a 6.5" screen and switching accounts is very difficult. I have to stretch my thumb all the way to the top left corner, a very uncomfortable motion.

**Describe the solution you'd like**
It would be great if the icons were moved (optionally?) to the bottom of the drawer (the thing that slides in from the left side of the screen). This does not have to be sth super slick and intelligent, just a new row with the account icons in series one by one. If you have more that the row can show, it would just be scrollable. This would also solve the issue that when more than 3 accounts are in place, using the account icons at the top of the drawer is unintuitive and only cycle among 3 accounts only.

The top space of the drawer would show what is still does, but the account **selection** buttons (not the bigger one that shows the active account) could be replaced with account, folder and general setting buttons. This way the "Settings" option would be moved from the bottom to the top as a non-frequently used option (I would argue that users don't visit the settings more than they switch accounts).

Here is a rough example:

![example](https://user-images.githubusercontent.com/11805218/98535591-aab6c980-2286-11eb-9ed7-7b277e17338d.jpg)

**Describe alternatives you've considered**
I tried using either the account icons or the drop down list, but they are both at the left top corner. I also tried using the unified inbox, but I turned it off. It also wouldn't solve the issue of switching accounts for other things other than reading the inbox.

**Comment by cketti** [comment]
Optimizing the app for one-handed operation on a large screen is not a design goal for K-9 Mail. We'll be sticking to the standard layout. 

See https://material.io/components/navigation-drawer
