### ISSUE TITLE
Show folder drawer when pressing back button from message list

### ISSUE THREAD

**Issue by nkakouros** [k9mail/k-9#5047]
**Is your feature request related to a problem? Please describe.**
To make the folder drawer appear (the thing that slides from the left side of the screen), the only option is to slide your finger all the way from the left side of the screen. This motion is uncomfortable and also takes significant time (in UX terms).

**Describe the solution you'd like**
Many apps show such drawers when the user presses the "Back" button on their devices. This is valid on the last-before-exit screen. It would make it much easier and faster to open the drawer. This behavior would not really add much overhead to users that don't rely on it but are used to exiting the app with pressing "Back", "Back", "Back", ... since they would just add one more "Back" press (which they might already do; I argue that very few people are so careful to count their "Back" presses when they just want to close the app).

**Describe alternatives you've considered**
None.

I noticed that you had suggested and implemented #4313. I think that from a UX perspective, the behavior I describe above is preferable. The user opens the drawer to do sth, e.g. select a folder or account. That action already closes the drawer once performed. Even if the user just wants to close the drawer without performing an action, there is the option to simply tap on the semi-hidden message list or swipe clumsily to the left from **anywhere** in the screen. This means that the level of accuracy and effort required is less than minimal. On the other hand, opening the drawer is disproportionally hard.

**Comment by cketti** [comment]
The suggested behavior doesn't match the platform "standard". We'll keep the current behavior.
