### ISSUE TITLE
manual mail recovering

### ISSUE THREAD

**Issue by nk0885** [k9mail/k-9#5049]
Hi
I got just now the new version 5.724
There are many changes . Why not .
But the new version erased the old possibility of manual load
The only possibility is now in automatic from never to 15 minutes till 24hours
This is not a good idea for those people who has limited connection. 
For them for example a pick up all 30 minutes will decrease the communication  potential. 
On the other side "all 24 hours" is too long sometimes and some times not . It depends of what is coming
The best was for me the manual pick up.
Could it be back in next version ?
Thanks

**Comment by cketti** [comment]
You can still manually refresh a folder by pulling down the message list. You can check an account by pulling down the folder list in the side drawer. You can check all accounts by switching to the list of accounts in the side drawer and pulling down that list.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
