### ISSUE TITLE
Add "Spam" action to "Unified Inbox" for selected messages

### ISSUE THREAD

**Issue by soerenkornetzki** [k9mail/k-9#5069]
This feature request is for K-9 5.725 (beta).

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to get into each and every individual account (have many), and select the (not as spam recognized) spam emails to move them to the spam folder (for the mail server to learn).

**Describe the solution you'd like**

I want a spam button in the unified inbox right next to the "mark as read" or "deleted" button. 

**Additional context**

I understand, there is no easy way to "just move" the emails into the spam folder of the (virtual) unified inbox, this would also make no sense and would not help me. 

When the spam button on the unified inbox page is clicked, the program has to go throu each and every mail individually, detect in which actual inbox the mail is actually stored, and move it to that spam folder individually.

**Comment by beat** [comment]
The latest version 5.800 has lost this feature on unified inbox compared to 5.600.

It now only works in account-specific inboxes.

As it was available iirc on the previous version 5.600, I'm suggesting kindly to classify this as a regression or even bug instead of an "enhancement".

It is one of the most used feature of unified inbox...at least for me lol.

**Comment by cketti** [comment]
The behavior hasn't changed. 5.600 doesn't support the spam action in the Unified Inbox when more than one account is set up.

**Comment by beat** [comment]
You are (of course) perfectly right. Sorry for my imprecision: It was not in the multiple-selections icons.

But it was available at the bottom of the rather long drop-down menu when long-pressing a single mail, and that was the case also in the unified inboxes view.

This long drop-down menu when long-pressing a message has now been replaced by the much shorter menu on top right as I understand it. And that menu has no "Is spam" entry.

Is that still off-topic, and in that case, would that be a different regression issue than this one that should be opened ? ;-)

**Comment by cketti** [comment]
@THausherr: This issue is about the message list screen. "Visible message actions" is about the message view screen.

**Comment by ottlinger** [comment]
The new UI/app version v5.8 doesn't seem to have the "mark as spam" anymore. As I need to sort away spam when I read mails via my phone this feature seems critical to me. Not sure if it's okay to vote for this ticket or if a new feature ticket is required. Thanks.
