### ISSUE TITLE
Allow parallel installation of unreleased versions

### ISSUE THREAD

**Issue by tomlayg6** [k9mail/k-9#5072]
I'd like to be able to try out beta releases alongside the current release.
However these use the same application package name as the official release.
This means the beta release replaces the official release.
Furthermore it is not possible to revert to the official release without first uninstalling.

I'd like to suggest that the beta releases are built using a different applicationId for beta builds.

For example using an applicationIdSuffix, see:
https://developer.android.com/studio/build/application-id

**Comment by cketti** [comment]
Using a different application ID would mean it's a completely different app in app stores. We used to do this. But the majority of people prefer the current model.

I don't want to release two beta versions. If this is important to you, please build your own K-9 Mail version from source. If you're fine running debug builds you don't have to make any modifications. Debug builds already use an application ID different from that of release builds.
