### ISSUE TITLE
Implement an IMAP console allowing a user to send commands to server directly

### ISSUE THREAD

**Issue by KOLANICH** [k9mail/k-9#5073]
**Is your feature request related to a problem? Please describe.**
k-9 mail has some features missing. A console may be a workaround

**Describe the solution you'd like**
An activity in an app allowing a user to type and send raw IMAP commands and observe their responses. Also should contain some autocompletion.

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by cketti** [comment]
In my opinion this is way outside the scope of an email client. I have no intention of implementing or maintaining an IMAP console inside K-9 Mail.
But of course you're welcome to fork the app and do it yourself.
