### ISSUE TITLE
Dark Theme Notifications becomes white when there's more than one email

### ISSUE THREAD

**Issue by joe540** [k9mail/k-9#5082]
Hello guys,

  First, thanks for this nice opensource app.

What happen: I use my android in dark mode at all time (dark theme). When there is only 1 email in the notification, everything is fine, but once I get more than 1 email in the notification, the background becomes white in the notification "bar" (while the text stay white) so it's unreadable.

Expected behavior: the notification background should stay dark

How to reproduce: Set your phone in dark/night mode and receive two or more email without clearing the notification

Thanks!

**Comment by cketti** [comment]
Please use the [issue template for bugs](https://github.com/k9mail/k-9/issues/new?assignees=&labels=bug&template=bug_report.md&title=) to create a new issue. Make sure to provide the information asked for. Especially relevant for this issue: K-9 Mail version, Android version (incl. information about custom ROM), Android device. Please also attach a screenshot.
