### ISSUE TITLE
Yahoo works no more

### ISSUE THREAD

**Issue by mperu99** [k9mail/k-9#5090]
Yahoo changed something and sent out a message to user about 3rd party apps,  my Thunderbird IMAP still works but K9 does not, however installing Spark email client on Andriod let's yahoo work via IMAP, so K9 is no longer working with yahoo changes. K9 needs to address this I love K9 but dont like I hade to remove all my yahoo accounts and use spark for yahoo instead. So I have K9 for all my gmail accounts and Spark for yahoo

**Comment by androcraze-git** [comment]
Do these directions work?:

https://www.sysinfotools.com/blog/get-yahoo-mail-third-party-access/

I'm not sure whether you'd select "Android email" or "Other app".

**Comment by cketti** [comment]
If the link doesn't help please use the [forum](https://forum.k9mail.app/) to ask for further help.
