### ISSUE TITLE
Can not setup imap fro gmail!

### ISSUE THREAD

**Issue by awweeks** [k9mail/k-9#5095]
I cannot get set up to work and I am putting in correct information set my Google Gmail account shield for me to do. I be using IMAP to try to get my email on K9.

**Comment by njeyaakili** [comment]
Are you using google "app passwords" and have you enabled "less secure app access"? See:

https://forum.k9mail.app/t/passwords-not-working/525 

for more of a discussion on these issues.

When reporting problems, please indicate more completely *what* you are entering. The phrase "putting in correct information" is hard to evaluate. Please also always include your K-9 version.

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
