### ISSUE TITLE
Disable annoying information sound

### ISSUE THREAD

**Issue by damnms** [k9mail/k-9#5117]
**Is your feature request related to a problem? Please describe.**
I have my mobile phone on loud because i have some calls that are very important.
I also get a lot of emails from my server whenever something happens. This is something not critical and i give a damn when i recieve 20 emails - i can check them also in a hour or later.
But all the time my mobile phone goes nuts when 10 or more emails arrive at the same time. This is just ridicoulous and there is no way to disable those extremely annoing ring sounds, except muting the complete phone what is not possible because: i must hear when someone calls!

**Describe the solution you'd like**
like whatsapp: a turn-off-annoying-notifications option

**Describe alternatives you've considered**
get rid of k9 mail, even tho i really like it

**Additional context**

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.

See, e.g. here: https://forum.k9mail.app/t/version-5-721-no-notification-sound/389

**Comment by damnms** [comment]
i have 7 email accounts - i have to configure each for itself? why not provide something in generall for all accounts? i could imagine someone has even more accounts and then configure it for each separately? why not provide a global function "dont make any noise when an email arrived" ?
