### ISSUE TITLE
Automatic light/dark theme

### ISSUE THREAD

**Issue by iiitomo** [k9mail/k-9#5119]
Currently, K9mail proposes to manually select either 'Light' or 'Dark' theme, independantly from the Android system theme.

I wish there was a 3rd possibility in the list: 'System'. Expected behavior: the theme of K9mail would automatically become Dark if the Android system theme is switched to Dark. And Light if Android theme becomes Light.

(my system: Lineage 17.1 - Android 10, K9mail 5.600 )

**Comment by cketti** [comment]
This is already implemented in the beta version. See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68
