### ISSUE TITLE
Use UnifiedPush for push notifications

### ISSUE THREAD

**Issue by emorrp1** [k9mail/k-9#5123]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use android without google services. Currently notifications must use FCM unless each app developer hosts a notification gateway which drains battery.

**Describe the solution you'd like**
I suggest using [UnifiedPush](https://unifiedpush.org/), the community successor to [OpenPush](https://bubu1.eu/openpush/). I believe the technical approach would be to use the "FCM-added" form of the UnifiedPush [android-connector](https://unifiedpush.org/developers/android/) library so that users who don't care about the minimal FCM data can continue to use it as before.

**Describe alternatives you've considered**
Although UnifiedPush is brand new, I'm not aware of any other app-independent implementation. As mentioned before, it is possible to avoid FCM if each app developer hosts their own server and the client wakes up frequently, draining the battery life.

**Additional context**
The only currently available UnifiedPush app is FluffyChat, implemented in [lib/utils/firebase_controller.dart](https://gitlab.com/famedly/fluffychat/-/commit/124a5eedf84854f4dcbbf7b9dc2a4a5ea2387f5a?view=parallel).

**Comment by emorrp1** [comment]
I've thought about it a bit more and think that k-9 isn't using **push** notifications, just ordinary notifications from IMAP polling? Sorry for the noise, I'll close this on that assumption.

**Comment by p1gp1g** [comment]
You can open it again, since JMAP support is planned (see https://github.com/k9mail/k-9/issues/3272), it will need push notifications :)
