### ISSUE TITLE
Add support for the signal encryption protocol.

### ISSUE THREAD

**Issue by dave90dave** [k9mail/k-9#5125]
**Is your feature request related to a problem? Please describe.**
I use openPGP so now and then, but it is very cumbersome to use, since you need to share your public key with every person you want to be in contact with (and vica-versa). 
That makes people not wanting to put the effort in it, to properly secure their private e-mails. Since it takes away too much time to exchange each others public keys.

The signal encryption protocol takes away this inconvenience, because it uses a more practical form of end-2-end encryption.

**Describe the solution you'd like**
I really love to see the signal encryption protocol being added to the application.

**Describe alternatives you've considered**
There are not very much alternatives, that take away the inconveniences that openPGP causes, while keeping the data secure.
Since the Signal encryption protocol is open source, very secure, and very easy to use; I think that every e-mail software should have this built in by default.

Have a nice day!
Dave

**Comment by cketti** [comment]
Email isn't really suited for the Signal protocol. It's not impossible to use the Signal protocol with email as transport, but it's certainly a lot of work. 
I'm not convinced this is a good idea. Someone should build a prototype to find out. But K-9 Mail isn't a great platform to build such a prototype. And there are far more important things that will occupy our time in the foreseeable future.

While I'm not generally opposed to adding such a feature should it prove to be viable, I don't see any value in keeping this issue open.

**Comment by violoncelloCH** [comment]
I'd also say that Autocrypt pretty much targets this use-case already...
