### ISSUE TITLE
Default signature is bad

### ISSUE THREAD

**Issue by ozls** [k9mail/k-9#5132]
I really love K9, so much so that I just reinstalled it after getting a new phone. That being said, I was appalled by the default signature.

![20210209_102335](https://user-images.githubusercontent.com/34961309/107343714-e6e60a00-6ac1-11eb-917d-37fe9ea2cedd.jpg)

In my opinion this is not a reasonable default. Having a default signature is bad enough, but I guess it's fair game if all the other mail apps (most of them proprietary) do it. But here it goes further, the app apologizes on my behalf! It could look completely ridiculous according to the mail one sends before noticing. I find it really obnoxious and unprofessional.

**Comment by cketti** [comment]
"Professional" is not one of K-9 Mail's design goals. Anyway, the signature is disabled by default since K-9 Mail 5.717.
