### ISSUE TITLE
IMPORTANT: Update your Play Store screenshots and app icon

### ISSUE THREAD

**Issue by bnainar** [k9mail/k-9#5149]
**Is your feature request related to a problem? Please describe.**
The app is beautiful. I found this app through recommendations on GitHub. So, I went to play store. The screenshots are very old. It nearly made me not install the app. But, when I looked at the actual screenshots elsewhere, it's beautiful

**Describe the solution you'd like**
Update the Play Store screenshots and app icon.

**Describe alternatives you've considered**
Nothing

**Additional context**
Play Store

**Comment by cketti** [comment]
Sounds like you've joined the beta program and downloaded a 5.7xx version.

The screenshots are of the current stable version 5.600. Only updating screenshots without updating the app will most likely lead to even more confusion. 
A new stable version can hopefully be released soon. We'll of course then also update the screenshots.

**Comment by bnainar** [comment]
@cketti, atleast update the app icon
