### ISSUE TITLE
sort/order of list accounts

### ISSUE THREAD

**Issue by zpcol** [k9mail/k-9#5151]
**Is your feature request related to a problem? Please describe.**
When more than 100 accounts are added, I often have trouble finding the name of the account if the list appears out of order. 

**Describe the solution you'd like**
Please add the sort account list feature according to:

1. according to the alphabet A-Z

2. according to the date added

3. according to incoming new messages

thanks

**Comment by cketti** [comment]
Sorry, but no. 100+ accounts is an edge case for which we won't add special support.

There's #4875 to allow reordering accounts.
