### ISSUE TITLE
Save account passwords with settings

### ISSUE THREAD

**Issue by cm-mc** [k9mail/k-9#5158]
**Is your feature request related to a problem? Please describe.**
If you have multiple accounts (10, atm...), it can get tiresome to go through all passwords if you need to reinstall.

**Describe the solution you'd like**
Add an option to save passwords along setting (in same or separate file).

**Describe alternatives you've considered**
If adding encryption code is beyond scope, just add option to save them in plain text, and keep it disabled by default, with a warning about plain text.

**Additional context**
About saving plain text passwords: you may just want to keep a local copy of your settings, in case you need to reinstall, in which case, if the device is ever compromised to the point they can be read from a plain text file, that will be the least of your problems.

***
Unrelated, but not worth opening an issue for, imv:
Portuguese (pt-pt) language translation for end-to-end encryption setting says "OenPGP", missing a "p".

**Comment by zpcol** [comment]
10+ accounts is a little, I have 7320 accounts.
Backup application data using titanium can be up to gigabits, which is very troublesome.

**Comment by cketti** [comment]
I'd rather not add support for exporting passwords in plain text. See https://github.com/k9mail/k-9/pull/4700#issuecomment-639457346

I think encrypting all account passwords with a backup password is the way to go.

**Comment by cm-mc** [comment]
Well, taking from the linked ticket, if "average user" is your concern, a few toughts:

- Average user doesn't look for alternatives; sticks to stock (i.e.: gmail);
- Average user doesn't sift through settings changing them; sticks to whatever's default (i.e.: no pass saving);
- Average user doesn't know what secure passwords is, to begin with, let alone how to keep them safe (i.e.: might as well writes them in a piece of paper and keeps them with the phone in the cover case);
- Average user, as it is, will be stuck with something like the above, since he won't have any other way to save his passwords;
- Finally, even with a secure way to save passwords, average user will probably never use a master password, and if he ever does, likely he'll keep that one unsecured, lest he forgets it.

Incidentally, the risk of losing passwords to secure locations is, by itself, equally, if not worst, a security risk as keeping them unsecured.
Either way, I think whatever the "mission", for software developers, never has been, and definitely should never be to worry about what possible harms hapless "average users" (which come from all sorts of life and backgrounds) may bring onto themselves, by acting as if their nannies, but, instead, "simply" to bring functionality that'll allow them to better adapt it to their needs/preferences.
If anything (_and specially for **FOSS** devs_) it should precisely be to fight against that patronising "mission creep", by ensuring users' freedom isn't ever more taken away under the guise of some fallacious "moral duty", as it's been done right before our eyes in broad daylight, left and right, in our societies.
But this is just me, because, at this point, I wouldn't be the least surprised if even Linux/GNU itself joined the bandwagon of locked down systems, under the pretense of _"protecting" users from themselves_...
Anyway, ultimately, though, it's always the devs' choice, and there's no arguing around that.
/Rant
Cheers.

**Comment by cm-mc** [comment]
Yeah, well, nvm; I've found a more suitable alternative, in the end. But, if you're adamant storing plain text passwords is that serious a security risk, better not trusting them to 3rd party mail servers, to begin with (or even use e-mail, at all), because they're way more at risk of a server attack/leak than phone hacks.

Cheers.

(Btw, Titanium Backup only works on rooted phones; that's also a "security risk", for some...)
