### ISSUE TITLE
Revert: Remove "Unified Inbox" from folder list

### ISSUE THREAD

**Issue by PrismaComputer** [k9mail/k-9#5167]
With one of the last updates unified inbox was moved on top of folder list.
Please excuse, but based on which user voice has this been decided?
It does not look good, neither it makes more sense, nor it's more consistent or intuitive.
It's just different, but without any sense.

E.g. Outlook Android app also has its unified inbox as own "home" button along the different buttons for single accounts. And this for good reason, because it appears logic. In opposite to Outlook desktop. Here the unified inbox is located on top of folder list, but in desktop app everything is sorted into a list. So in this special case it makes sense. But neigther for Outlook Android app nor for K9.

So, please revert to old unified inbox position.

**Comment by life777eternal** [comment]
The newer beta version 5.731 has this "Unified Inbox" and I don't like how the app continually reverts to the "Unified Inbox" after switching to a home 🏡 screen or another app. Also I even lost an email I was writing when the phone screen locked, and when returning to the home screen. 

Also what happened to the K9 Robot 🤖 Dog 🐶?  I was hoping for a better way to switch between email accounts though now it's more like the Gmail app.

**Comment by cketti** [comment]
There are no plans to change the current behavior.
