### ISSUE TITLE
Deleting from notification without confirmation

### ISSUE THREAD

**Issue by GnnrMrkr** [k9mail/k-9#5170]
**Is your feature request related to a problem? Please describe.**
I often delete mails right when I get them. For this, I click on 'delete' below the notification. For me, it is really inconvenient that I have to confirm every deleting of a mail. 

**Describe the solution you'd like**
Include an option in the settings where you can choose whether you want to delete with or without confirmation.

**Comment by cketti** [comment]
In 5.600: `Settings > Global settings > Interaction > Confirm actions > Delete (from notification)`
In 5.7xx: `Settings > General settings > Interaction > Confirm actions > Delete (from notification)`
