### ISSUE TITLE
search emails by "TO" - list all emails sent to certain address

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#5202]
**Describe the solution you'd like**
it would be nice to be able to search my mails by receiving mail addresses.

My Universitymailaccount is subscribed to a few mailing lists, and I would like to be able to filter by who mails where sent to.
Example:
studierendenliste@example.de
Is a list which all students are subscribed to.
There are also lists for each faculty and the library and so on.

If there is a general issue to add features to the search, then I would like to link/mention this there. Please give me a hint :)

**Comment by cketti** [comment]
Duplicate of #1127
