### ISSUE TITLE
Field "To" automatically replaced with garbage

### ISSUE THREAD

**Issue by rend3r** [k9mail/k-9#5256]
**To Reproduce**
1. Compose new email
2. Type or paste timesheet.workhour@gmail.com to "To" field
3. timesheet.workhour@gmail.com auto replaced with +1
4. I'v granted permission to access to address book earlier (maybe it would be helpful).

K9mail: 5.733 fdroid
Android 10

**Comment by ByteHamster** [comment]
That happens because the address is too long to be displayed directly. You can click the +1 button to see the address. It will send the email just fine :)
