### ISSUE TITLE
Refresh folder list before polling folders

### ISSUE THREAD

**Issue by dseomn** [k9mail/k-9#5258]
**Is your feature request related to a problem? Please describe.**
I have `Folder poll frequency` set, and I was expecting to always have relatively recent messages in all folders. I just tried to check a folder that was created after I first setup k9mail, but well before the last poll, and it didn't show up.

**Describe the solution you'd like**
It would be great if each poll started by refreshing the folder list, so it could actually poll all folders.

**Describe alternatives you've considered**
Refreshing the folder list before polling could be optional.

**Comment by cketti** [comment]
I'm guessing you're using K-9 Mail 5.600. In recent beta versions this is already implemented. See #4216.

However, K-9 Mail will not automatically poll newly detected folders. You'll have to manually configure the folder's display and/or poll class.

**Comment by dseomn** [comment]
Yup, I've got 5.600. I've also got `Poll folders` set to `All`. With that setting, will K-9 Mail poll the newly detected folders?

**Comment by cketti** [comment]
I forgot that's an option. That should work. 

The default `Folder poll class` is `Same as display class` and default `Folder display class` is `No Class`. So only `Poll folders` = `All` will cause new folders to be polled.

**Comment by dseomn** [comment]
Awesome, thanks!
