### ISSUE TITLE
Archive in Shared/Grouped Inbox

### ISSUE THREAD

**Issue by marbetschar** [k9mail/k-9#5264]
**Is your feature request related to a problem? Please describe.**

Right now its possible to "Delete" and "Mark as Unread" and "Flag" a message in the Grouped Inbox. However, "Archive" seems to be missing there - although it is possible within an inbox of a specific account.

**Describe the solution you'd like**

Also beeing able to "archive" a message from the grouped inbox.

**Additional context**

I love to "Archive" messages which are "Done" - but I still want to keep. This way, they are gone from the Inbox and I don't stumble across them every time I open the app.

**K-9 Mail: v5.733**

**Comment by cketti** [comment]
Duplicate of #1041
