### ISSUE TITLE
App-notification with number of unread mails

### ISSUE THREAD

**Issue by Bennjihuuuu** [k9mail/k-9#5277]
Hi, could you please add a notification number which displays whether there are any new mails and how many right at the app symbol on the main screen?

I think of those little red number symbols on top of the app symbol. I would bei very thankful for this feature. Thanks a lot!

**Comment by cketti** [comment]
K-9 Mail comes with the "K-9 Unread" widget that supports this.

**Comment by cketti** [comment]
This is not a feature vanilla Android supports. See #1104.
