### ISSUE TITLE
Emails from gmail to gmail not downloading

### ISSUE THREAD

**Issue by gitgotgone** [k9mail/k-9#5284]
My wife and I both have K-9 on Android 11 set up with SMTP to our gmail accounts. Recently emails from gmail addresses to each of our gmail accounts have not been downloading to either of our K-9 apps even though they show up on our gmail accounts.

I don't know if this is a google problem or a K-9 problem.

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
