### ISSUE TITLE
Unified Archive Folder

### ISSUE THREAD

**Issue by marbetschar** [k9mail/k-9#5287]
If feasible it would be great to have a unified archive folder in addition to the already existing unified inbox. The reasoning for this boils down to my workflow:

I love to keep my inbox clean. So the mails there are the ones I actively need to work on. If I'm done with an email, I'm moving it to the archive folder. If the email needs to be revisited later (e.g. I'm waiting for a reply) I also flag the email before moving to archive. Somewhen in the future, I navigate to the archive folder and filter for flagged emails to figure out if there's anything which needs further action.

While this is certainly possible right now with K-9 by navigating to each archive folder of every account, it would be easier if there's one archive folder showing messages from all accounts. Like there is one for inboxes.

**Comment by MarcusWolschon** [comment]
You could do the same for the Trash, Send and Sending folders.

**Comment by cketti** [comment]
I don't want to add a unified Archive folder (or Trash, Sent, Outbox). However, this is something that could be accomplished with saved searches. See #3398.
