### ISSUE TITLE
archieve function needed

### ISSUE THREAD

**Issue by jfdnet** [k9mail/k-9#5311]
luck of function for archieving mails

**Comment by cketti** [comment]
K-9 Mail already supports archiving messages.

**Comment by jfdnet** [comment]
> K-9 Mail already supports archiving messages.

cannot use in unify inbox.
cannot use in mails multi selected.

**Comment by cketti** [comment]
See #1041

**Comment by jfdnet** [comment]
5 years makes no progress on it ......
