### ISSUE TITLE
quoted/indented messages get garbled in long Re:threads

### ISSUE THREAD

**Issue by droopy4096** [k9mail/k-9#5334]
**Describe the bug**

corresponding with some mail clients that do indent parent message text results in "infinite" scrolling through single-letter lines. Im essense message gets printed vertically one letter per line.

In particular noticed with Apple Mail

**To Reproduce**
1. send a message to yourself
2. reply to yourself multiple times with some 'lorem ipsum' text
3. at certain point scrolling will reveal single-character lines

**Expected behavior**
either some word-wrapping or side-scrolling will need to be applied

**Screenshots**

![Screenshot_20210609-132915_K-9_Mail_sanitized](https://user-images.githubusercontent.com/1248187/121421816-cb81f300-c92b-11eb-82b0-25408056ae7b.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: LineageOS 17.1 (unoficcial build)
 - Device: Samsung Galaxy S7
 - Account type: POP3

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Is this still an issue with the latest beta version? See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68

**Comment by benebun** [comment]
Hm not sure which beta is currently in development but I just wanted to add that in version 6.0.0 it's marginally better because it doesn't wrap at every letter anymore but still at every word even though there would be more available space to the right. So it's still not very usable.
