### ISSUE TITLE
Add explanation for "@" notification (Push)

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5404]
The number of support requests related to the ongoing notification for the Push service are rising. We could display a screen with a short explanation on why the notification is necessary when tapping the notification. That screen could also link to a web page containing more details, also a button to disable Push for all accounts.

**Comment by ByteHamster** [comment]
I wonder if the notification should display some text like "Tap to hide" or a "Hide" button that opens the explanation page. Not sure if users would try touching the notification before they leave a bad rating.

**Comment by cketti** [comment]
A first draft:

![k9mail__push_info__draft_1](https://user-images.githubusercontent.com/218061/125502876-2909b150-1823-4451-8e13-7438ad567afc.png)

- "Learn more" is a link to a web page (probably the FAQ post in the forum for now, the app documentation later)
- "Configure notification" opens the notification settings screen for the "Synchronize (Push)" notification channel
- "Disable Push" sets the "Push folder" setting to "None" for all accounts

**Comment by ByteHamster** [comment]
Some thoughts:

- I think "the app" should be "K-9"
- The whole screen feels a bit too "technical" to me. Do users really care if it is "one or more" connection or if it is the *incoming* mail server? I think the shorter the better in this case. The documentation can then be more specific.
- The text about disabling push should probably also say that K-9 still checks periodically, it's just no longer instant.

**Comment by cketti** [comment]
Another attempt.

"Configure notification" text:
> When using Push K-9 Mail maintains a connection to the mail server. Android requires displaying an ongoing notification while the app is active in the background. However, Android also allows you to hide the notification.

"Disable Push" text:
> If you don't need instant notifications about new messages you should disable Push and use polling. This will also remove the notification.

**Comment by gdt** [comment]
I suggest saying "Android policy requires", as this is a requirement based on a duty to disclose not a technical one.  But maybe that's too complicated.

It's an interesting question whether Push will use less resources (power and data) or more, than polling, at what interval.   I wouldn't want to recommend that without data, but I also want very timely mail delivery (< 1 minute) so I just want Push, period, so it doesn't really matter to me.    My view is that people who want to disable push because they don't like the notification (rather than turning off the notification) are basically doing something for a wrong reason, and it's not in their interest to push them towards push disabling.    I'm saying that based on thinking they just recently turned on push.   Maybe I'm off base here and of course your call.

**Comment by cketti** [comment]
Whether Push is more energy and/or data efficient than polling depends on a lot of factors. There's certainly a lot more things that can go wrong with Push. So unless timely notifications are desired switching to polling is a good recommendation in general.

This screen is mainly for people upgrading from earlier versions. We used to enable Push by default. I'd expect many of those users to not really need Push.

**Comment by ByteHamster** [comment]
I am not sure if average users know what polling is. How about this for the "Disable Push" text?

> If you don't need instant notifications about new messages you should disable Push and use polling. Polling checks for new mail at regular intervals and does not need the notification.

**Comment by cketti** [comment]
Works for me. See screenshots in #5413.

**Comment by mjnewton** [comment]
The help text, whilst undoubtedly of definite value to many, doesn't currently accommodate the fact that older versions of Android (e.g. I'm on v7.0) don't allow granular control of notifications - they can either be enabled or disabled (no in-between) for a specific app thus the guidance given won't necessarily work for all. Perhaps a few words to that effect might help, and avoid leaving some scratching their ends as to why they can't find the options being discussed?
