### ISSUE TITLE
New version 5.8 forces Unified mailbox on

### ISSUE THREAD

**Issue by cniggeler** [k9mail/k-9#5440]
Despite not using Unified view previously, the newly installed 5.800 version forces it on. Can be disabled from deep in the settings structure.

Suggestion: Use prior user preference

**Comment by cketti** [comment]
5.800 does not force-enable the Unified Inbox. With all prior releases the Unified Inbox was enabled by default. And if the user didn't manually "hide special accounts" now the app starts in the Unified Inbox. 

You can still disable the Unified Inbox by unchecking `Settings > General settings > Display > Show Unified inbox`.
