### ISSUE TITLE
New version 5.800 radically different font sizes, suggest preview mode

### ISSUE THREAD

**Issue by cniggeler** [k9mail/k-9#5441]
The latest version has **much** larger fonts than prior versions as "default", so am forced to go through and manually change font sizes. This is exacerbated by the fact you have to back out 4 LEVELS DEEP in the settings structure, PLUS dismiss the left side dropdown menu, before being able to view the changed font size in a mailbox.

Suggestions: Either reduce default font size to closely match prior versions, or put a Preview window in the font size section so one can readily view/ choose the preferred new font size.

**Comment by jirikeller** [comment]
This is NOT an ENHANCEMENT, but a CRITICAL BUG in the new version. For me, with version 5.800 K-9 mail becomes unusable and I am considering either downgrade or moving to another client. 
I am using larger font on my Gemini, but for e-mail I need (eg. for mail preview) "smaller than smallest" font. And yes, finding it in the structure is pain. 

Another pain in ass problems:
 - I feel (but do not have a screenshot to compare) that in the previous version there were more messages than in the current with the smallest font available
 - push does not work with my server, sync button disapeared
 -  how on earth I get to view a folder (not "integrated incomming mail") ???

I have recommended K-9 to many, but probably it is time to change an opinion. WHY did you kill K-9 ???

**Comment by jirikeller** [comment]
I am back on 5.600 and happy user again !

**Comment by truh** [comment]
The biggest challenge with this was for me that the font size settings don't tell you what size the default size is. Otherwise it would have been very easy for to just turn everything one step smaller but since every entry just says Default I had to adjust it by trial and error.

**Comment by cketti** [comment]
I extracted the preview feature request to #5454.

PR #5453 will tweak the font sizes. The OP might still find they're too large because we fixed K-9 Mail to respect the system font size modifier (if you increase the font size via Android settings, all text in the app will become larger, too). This wasn't working in 5.600.
