### ISSUE TITLE
Bad one hand handling / UI optimization 

### ISSUE THREAD

**Issue by cDev1987** [k9mail/k-9#5490]
In times where phones getting bigger and bigger again, UI should be optimized for 1 hand handling.
With old app version it was easy because the toolbar was on buttom. Now its on top and you need mostly both hands for navigation.
Also sync mails for all folders is only possible with 2 hands.
Maybe you can optimize this / add gui settings to switch the location for the tools bar.

Cheers,
cDev

**Comment by IriaSomobu** [comment]
Navigated to K9's issues tracket to post literally the same issue.

Please can we have toolbar at bottom? At least on mail viewer screen? Please?

**Comment by ByteHamster** [comment]
Closing this one to keep the discussion in one place: #5447
