### ISSUE TITLE
No longer able to swipe to multi-select emails in folder view

### ISSUE THREAD

**Issue by supertin** [k9mail/k-9#5497]
**Describe the bug**
In prior versions, multiple emails would be selected in a folder by swiping across one, then tapping additional ones. Since "the update", swiping is no longer possible, instead requiring a much slower long press (after which tapping does still work).

**Expected behavior**
Swipe causes message to be selected as it did in the older versions.

It might not seem like much, but that extra second seems so slow and painful, especially if doing smaller batches (where the initial long press time starts to add up)

**Comment by ByteHamster** [comment]
I don't think swiping to select will come back. There will be swipe actions for things like deletion later. You can quickly select messages by tapping their contact icon.

**Comment by cketti** [comment]
We want to add "swipe to action" support. See #1426
One of the actions the user can configure could be "select message".
