### ISSUE TITLE
Enable server-side search by default (IMAP)

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5499]
Currently support for server-side search is disabled by default. It has to be enabled under *Settings > [Account] > Search > Enable server search*.
I can't think of a good reason why that is. Performing a search on the server is always an additional button press anyway. So we might as well get rid of this setting and always allow server-side search (if supported).

Places that need modifying:
- `account_settings.xml`
- `AccountSettingsDataStore`
- `AccountSettingsDescriptions`
- `strings.xml`
- `Account`
- some other places (check where `Account.isAllowRemoteSearch()` and `Account.setAllowRemoteSearch()` is referenced from)

**Comment by flotwig** [comment]
Before this is added, it would be good to have support for searching all folders via IMAP, instead of the existing support which covers searching the current folder only: https://github.com/k9mail/k-9/issues/649 

Otherwise, there will be incongruity between the results in per-folder search and in "Search everywhere", since the former will search on the server-side and the latter will still search locally.

**Comment by cketti** [comment]
> Otherwise, there will be incongruity between the results in per-folder search and in "Search everywhere", since the former will search on the server-side and the latter will still search locally.

That's already the case right now when enabling server-side search. As mentioned in the description, searching on the server is always an additional button click. I'm not proposing to change that behavior.

<img src="https://user-images.githubusercontent.com/218061/129625800-2dcf40c9-fcbc-4b20-a0b6-6c6c3aa85261.png" alt="k9mail_search_results_highlight" width=300>

**Comment by flotwig** [comment]
Ah okay, I misunderstood the issue as proposing to change that default. I see now.

**Comment by parkerfath** [comment]
This one seems to be in a similar space to my last commit; any reason why those commits from Sempro weren't accepted? If it makes sense, I might pick up this one next.

**Comment by cketti** [comment]
The idea is to get rid of the "Enable server search" setting and always display the "extend current search to the server" button (see https://github.com/k9mail/k-9/issues/5499#issuecomment-899800424) when possible.

<img src="https://user-images.githubusercontent.com/218061/149626510-d2c1a880-ed38-4eee-9aaf-cebf4d1c9c50.png" alt="k9mail__account_settings__search" width=300>

Currently we check whether an account supports search in the settings screen (`MessagingController.isPushCapable()` is used for this). This check has to be moved to the message list/search screen when the setting is removed.

**Comment by parkerfath** [comment]
> The idea is to get rid of the "Enable server search" setting and always display the "extend current search to the server" button (see [#5499 (comment)](https://github.com/k9mail/k-9/issues/5499#issuecomment-899800424)) when possible.

Makes sense. I'll look and see if I can put something together for this one.
