### ISSUE TITLE
OAuth2 implementation.

### ISSUE THREAD

**Issue by Auxority** [k9mail/k-9#5500]
**Is your feature request related to a problem? Please describe.**
I can receive mail from my school e-mail, but sending it is currently not possible through K-9 Mail.
When I configure the SMTP, K-9 Mail returns an error about SmtpClientAuthentication being disabled for the Tenant.

**Describe the solution you'd like**
I would love to see the addition of OAuth2 in the Security methods, so I can configure the email that way.
This works in Thunderbird, so I hope it will be possible here.

**Describe alternatives you've considered**
Another solution would be to use a separate app, but I do not really want to do so.

**Additional context**
An example of the error:
![image](https://user-images.githubusercontent.com/35202343/127783526-9d72a6be-d662-47f1-ba87-914a9b1cba21.png)

**Comment by cketti** [comment]
There's already issues for OAuth2 support. We'll work on that when improving account setup. This is fairly high up on the list of priorities.

**Comment by DirectX-Box** [comment]
Hello,

It seems that Google will be terminating the traditional authentication method currently in-use by K-9 Mail by May 30.

Here is a mail sent to some accounts with less secure access enabled:

![Google-Auth-EOL](https://user-images.githubusercontent.com/61107724/156539754-cb11d7b0-be0b-4380-83dd-ab025b0b4a4a.png)

This deadline and the popularity of Google accounts in contrast to Yahoo! Mail and US universities' mail systems may bring this issue to a wider attention. At least it did for me.
