### ISSUE TITLE
"Waiting for new emails" notification should use low priority

### ISSUE THREAD

**Issue by lostfictions** [k9mail/k-9#5521]
**Is your feature request related to a problem? Please describe.**

First of all, congrats on the 5.800 release! It's clear it was a long road to get here, but it looks and works great.

A family member is stuck on an older version of Android (7.1) and is finding the new push "waiting for new emails" notification annoying. It appears with normal priority (so it's interleaved with all of their other notifications) and it doesn't appear possible to disable it without disabling _all_ notifications for K-9 (which would sort of defeat the purpose of having push enabled in the first place).

We took a look at the documentation [for silencing or disabling the notification](https://forum.k9mail.app/t/how-to-configure-push/1102/1#notification-3), but these instructions don't appear to apply to Android 7.1 or below. Specifically, there doesn't appear to be a mechanism for granularly disabling or silencing specific kinds of notifications from an app -- it's all or nothing.

The notification on Android 7.1 looks like the one covered in the FAQ post:

![ss1](https://user-images.githubusercontent.com/567041/128258318-d837de77-3de0-4512-8afa-42c7799db649.png)

However, long-pressing the notification reveals this menu instead of one that allows you to toggle individual notification types:

![ss2](https://user-images.githubusercontent.com/567041/128258559-73eed04e-d2aa-4df4-b8ce-ab36ffbdd3f9.png)

The "More Settings" option doesn't offer more granular configurability either:

![ss3](https://user-images.githubusercontent.com/567041/128258649-c56f75c3-8dc2-4105-8bca-ff51a6321314.png)

**Describe the solution you'd like**

Other apps seem to solve this problem by using low-priority notifications. For example, when [Signal](https://www.signal.org/) is running in an environment without Play Services, it'll spawn a persistent notification similar to K-9's. However, the notification doesn't have an icon that appears in the status bar -- you have to pull down the notification shade to see it at all -- and it appears at the very bottom of the notification list, in a slightly dimmed colour:

![ss4](https://user-images.githubusercontent.com/567041/128259232-b5453345-f1cb-446c-9d81-668b58f33762.png)

Signal _message_ notifications, of course, appear with normal priority.

Absent any way to hide specific kinds of notifications for a given app on older versions of Android, having K-9 do this seems like it would be the best and least obtrusive solution.

In case it helps, I took a quick look in Signal's code -- [this appears to be the method and parameter in question](https://github.com/signalapp/Signal-Android/blob/1a56924a56a191a1271ba70b2e12a3af3ad289bc/app/src/main/java/org/thoughtcrime/securesms/messages/IncomingMessageObserver.java#L275), using `androidx.core.app.NotificationCompat.Builder`. The [docs for the method](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setPriority(int)) explain:

> On platforms `Build.VERSION_CODES.O` and above this value is ignored in favor of the importance value set on the notification's channel. **On older platforms, this value is still used, so it is still required for apps supporting those platforms.**

**Describe alternatives you've considered**

The family member could disable push and enable polling instead. (This is slightly annoying, since push/IDLE seemed to work fine on previous versions of K-9 without the notification, with battery optimizations disabled. My understanding is that the notification is necessary specifically for new versions of Android, which is fair enough.)

Or they could roll back to an older version of K-9. This would definitely be a shame -- and probably not ideal long-term for security and maintenance -- but would fix the notification annoyance.

**Comment by red-lichtie** [comment]
This has been closed and the issue is unresolved. Does that mean find an alternative Email client as you "Won't fix" ?

**Comment by cketti** [comment]
The fix is included in 5.803.

**Comment by red-lichtie** [comment]
Awesome, thank you!
