### ISSUE TITLE
[Feature] Always Show Accounts Option & Hide Account Pictures

### ISSUE THREAD

**Issue by seniorm0ment** [k9mail/k-9#5532]
Requesting the option to be able to remove the dropdown area to select accounts, and simply have them listed condensed above the "unified mailbox" option.

Also requesting the ability to hide the circular picture icons next to the mailboxes.

**Comment by cketti** [comment]
I don't want to add these suggestions. You might be interested in #5570, though.

**Comment by seniorm0ment** [comment]
that would be fine
