### ISSUE TITLE
Add support for vibration patterns on Android 8+

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5543]
Android 8 has introduced [notification channels](https://developer.android.com/training/notify-user/channels) where an app can only provide an initial configuration. After creation a notification channel can only be configured by the user via Android's notification settings. Unfortunately their settings screen doesn't allow setting a custom vibration pattern.

It seems like our only option is to use our own UI to allow users to select a custom vibration pattern. Then we'll have to delete the existing notification channel and create a new one (copying the configuration of the old notification channel). 
It appears like we will also have to use a different ID for the new notification channel. So we have to dynamically create that ID and keep track of it instead of being able to use a static identifier :disappointed: 

See also #5544

**Comment by kriegste** [comment]
Why was that changed anyway? In 5.6 it was working perfectly.

**Comment by cketti** [comment]
Because things have changed in newer Android versions. To be able to update apps on Google Play you have to do it the new way.

In the future please use the [forum](https://forum.k9mail.app/) for questions like these.
