### ISSUE TITLE
Add an overview screen on startup

### ISSUE THREAD

**Issue by z4lem** [k9mail/k-9#5551]
First of all, many thanks for your valuable work, I really appreciate this effort! 

**Describe your request**
I have multiple personal e-mail accounts integrated into k9 mail. With the new GUI there are two possibilities for a startup screen:

1. The side panel open, showing an unread cound of the **default** e-mail adress (this implies you have an address, that is more important than others).
2. The inbox open, showing a unified inbox of all email accounts (that is heavily overloaded, if you have multiple highly used addresses).

I miss badly an overview on startup with an unread & fav counter for each included email address like in the previous version (screen attached).
From this screen I got an instant overview of the status of all accounts, without having to click you way through. By e.g. touching the _star icon_ you've been forwarded to a view with only the emails, marked as favourites (I used this crucial functionality like a todo list ;)

**Describe the solution you'd like**
I suppose the sidepanel being to small for this kind 'clickable' startup screen. An option could be widen the new side panel to fullscreen on startup and present this overview. 

![overview screen of old GUI](https://user-images.githubusercontent.com/23519149/128676842-43c9978c-6437-476e-828f-65ffa1984d96.png)

**Comment by j-mcdougall** [comment]
See issue https://github.com/k9mail/k-9/issues/5452 .  It describes what you are looking for and lots of comments.

**Comment by cketti** [comment]
See #5570
