### ISSUE TITLE
Improve experience when clicking the summary notification

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5565]
When clicking the summary notification on old Android versions or clicking on grouped notifications on new Android versions, we open a message list screen showing the new messages. 

We should do the following, in order:
- [x] When the Unified Inbox is enabled and all messages belong to a folder that is included in the Unified Inbox, open the Unified Inbox.
- [x] When all messages belong to the same folder, open that folder.
- [x] Otherwise, open a message list view that only includes new messages.

The last one is a bit tricky, because we want to remove the notifications as soon as that view is opened. However, if we do that, we lose the information about which messages are "new". So we need an additional flag in the `messages` table to mark a message as "new" and use that for displaying the list of new messages, rather than the `notifications` table.

**Comment by doublehp** [comment]
Also, by the way: once all emails mentionned in a notification are read, the notification should be removed from systray. This issue started with Android 7, and is still present in Android 9 and 10. It's a regression compared to Android 4 (where tapping the notification made it go away).

**Comment by cketti** [comment]
@doublehp: That is an entirely different issue. Notifications are already removed when a message has been (marked as) read. This doesn't always work as intended. But #5566 should fix that.
