### ISSUE TITLE
Open K9 with sidebar open.

### ISSUE THREAD

**Issue by sfadschm** [k9mail/k-9#5587]
With all the fuzz around the old account overview (which I liked also, to be fair), I wanted to add my two cents here, as I feel discussion is more objective than in the forums.

There is some merged and ongoing PRs and issues  dealing with the broader topic. The latest being #5570, indicating we will get an optional overview.

However, looking at the other PRs I believe this is already here:

- #5519 was just merged and brings starred messages back to the swipe-out menu.

- #5498 is WIP but intends to bring refresh and navigation buttons to the swipe-out menu.

With these two PRs, the account overview already has all the features of the old design.

**Describe the solution you'd like**
As far as I see, an option to start the app with the swipe-out menu open in the account overview screen will fulfill all requests regarding bringing back the old screen (except for color and styling maybe).

If the account starting folder is set to none, klicking one of the accounts will open the account's folder list like before.

So I feel we do not need a new screen here, but rather an option to open with the existing menu (maybe in "full screen size").

Please feel free to close and/or lock at will 😄

**Comment by cketti** [comment]
> As far as I see, an option to start the app with the swipe-out menu open in the account overview screen will fulfill all requests regarding bringing back the old screen (except for color and styling maybe).

#5570 contains a link to a forum thread where people describe how the used the account overview screen.

Many people want to start with the account overview but also go back to it using the back button. Implementing this behavior using the navigation drawer is possible, but doesn't behave at all like a drawer typically does. So I don't want to go there.

Some users also liked the shortcut to open the auto-expand folder in a filtered view (unread/starred messages only). Stuffing all of that functionality into the navigation drawer feels like bad UX.

> So I feel we do not need a new screen here, but rather an option to open with the existing menu (maybe in "full screen size").

It feels like you're inventing new UI components. A full-screen side drawer is not a thing, and probably shouldn't be.

**Comment by sfadschm** [comment]
> but also go back to it using the back button

Thats the point I missed.



> It feels like you're inventing new UI components.

Agreed.

Thanks for elaborating.
