### ISSUE TITLE
Refresh mail adress when changed in server data

### ISSUE THREAD

**Issue by diesocke** [k9mail/k-9#5626]
I noticed that the account still shows the adress specified when initially saving the account. When this is changed in the credentials for sending/receiving mails (e.g. because of a typing error) this does not seem to refresh. I have not found any other way of adapting the shown mail adress.

I solved it by deleting the account an setting up a new one.

**Comment by cketti** [comment]
The email address used as sender address when composing messages can be changed under *Settings > [Account] > Sending mail > Composition defaults > Your email address*. This is also the email address that is displayed in the account list.

The email address is often used as username for incoming and outgoing server settings. But these are only used for authentication, not when composing a message.
