### ISSUE TITLE
Feature request: add "Archive" button to the list of available actions in notification

### ISSUE THREAD

**Issue by rakshazi** [k9mail/k-9#5628]
**Is your feature request related to a problem? Please describe.**

I prefer to archive emails instead of deleting them when receive some automated email that I don't want/need to read. Right now I need to do to the inbox and archive emails from the email list or from email view page.

**Describe the solution you'd like**

Please, add "Archive" button to the email notification

**Describe alternatives you've considered**

Alternative is to mark email as read from notification and archive it later from emails list, not very usable

**Additional context**

N/A

**Comment by cketti** [comment]
This will be possible once #3530 is implemented.
