### ISSUE TITLE
Two small improvements:

### ISSUE THREAD

**Issue by ulrichloose** [k9mail/k-9#5651]
My settings are set to "Never download pictures" and it works as intended. Sometimes I want to load the pictures and use the "Load pictures" button.

**In the case of emails in which the images have already been loaded, the "Load images" button should not be displayed in the first place.**

-------

K-9 can can generate an * .eml file from received mails if you select "forward as attachment". From time to time I would like to save a mail locally as * .eml because I am interested in the headers. So far, this has only been possible via the detour "send to yourself" and then save the attachment.

**An extension would be nice if one could not only delete the generated attachment before sending it, but also save it. It would be even nicer to be able to save a generated * .eml file via share.**

**Comment by cketti** [comment]
See 
- #1639
- #1498

When viewing a message you can also select "show headers" from the menu.
