### ISSUE TITLE
Set correct encryption state in message crypto annotation

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#570]
Right now we unconditionally set `wasEncrypted` to `false` in `MessageCryptoHelper.handleCryptoOperationSuccess()`.

The information whether a message was encrypted or not needs to come from the crypto provider to account for "null-encryption" and other weirdness.

**Comment by dschuermann** [comment]
closed with https://github.com/k9mail/k-9/commit/ffc5ba2cf36e8eb25fc981938aa7b6f997697c8f
