### ISSUE TITLE
Server Autoconfiguration like Thunderbird

### ISSUE THREAD

**Issue by EpeR1** [k9mail/k-9#5705]
Please add XML/http based autoconfiguration feature for incoming and outgoing server.
Like Thunderbird autoconfiguration, or Outlook autodiscover protocol.

Mostly I'm interest in self hosted mode autoconfiguration requests for example:
 http://autoconfig.example.com/mail/config-v1.1.xml?emailaddress=fred@example.com

More info on:
https://wiki.mozilla.org/Thunderbird:Autoconfiguration
https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat
https://autoconfig.thunderbird.net/v1.1/

**Comment by cketti** [comment]
Duplicate of #865

**Comment by EpeR1** [comment]
Okay, duplicated, 
but Is the "self hosted" version of XML configuration file  planned to implement/support?

**Comment by cketti** [comment]
> Is the "self hosted" version of XML configuration file planned to implement/support?

Sure, I consider this to be part of #865
