### ISSUE TITLE
Make sure we only attempt to decrypt PGP/MIME messages

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#571]
PGP/MIME and S/MIME both use the Content-Type values `multipart/signed` and ` multipart/encrypted`. We need to make sure to only attempt to decrypt PGP/MIME parts (check `protocol` parameter)

**Comment by artbristol** [comment]
S/MIME only uses `multipart/signed`; S/MIME encrypted emails use `application/pkcs7-mime` rather than `multipart/signed`

However I get a NPE when opening an S/MIME encrypted email:

```
E/AndroidRuntime(28801): java.lang.NullPointerException
E/AndroidRuntime(28801):        at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:86)
E/AndroidRuntime(28801):        at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:282)
E/AndroidRuntime(28801):        at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:277)
```

Is this covered by this bug?

**Comment by cketti** [comment]
I had a brief look at the code and this seems to be related but different. Feel free to create a new issue for it (ideally with instructions on how to reproduce).

**Comment by alexandre75** [comment]
Issue fixed by PR : https://github.com/k9mail/k-9/pull/884
Commit
bbfb6b95bca5a478422388f9ecbe3cd1295e8900
