### ISSUE TITLE
Can't connect to aol mail, please fix it

### ISSUE THREAD

**Issue by User1l0** [k9mail/k-9#5717]
IMAL and POP login, both don't work

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/solved-adding-new-aol-mail-acounts/2195

**Comment by User1l0** [comment]
> See https://forum.k9mail.app/t/solved-adding-new-aol-mail-acounts/2195
i don't have 2fa or app password enabled and
I tried everything from you link, nothing helps, please look at this problem again

**Comment by njeyaakili** [comment]
The app password requirement is set by AOL, and not something that the end user controls. I would try that route. If you continue to have problems, then bring them up in the user-forum item referenced above.
