### ISSUE TITLE
Auto-expand folder is ignored

### ISSUE THREAD

**Issue by julietmikebravo** [k9mail/k-9#5743]
The setting is found in settings > [your account] > Folders. It's the top option. 

It used to open the selected folder when the app is opened. Now the app will always open at at unified inbox, ignoring the setting. I think it's been broken since the big update with the UI overhaul.

**Comment by cketti** [comment]
It's the folder that is opened when the account is selected. If the Unified Inbox is enabled, starting the app will display the Unified Inbox.

**Comment by julietmikebravo** [comment]
Disabling unified inbox worked. I'm not convinced it makes sense for those settings to conflict but I'll close the issue.
