### ISSUE TITLE
Display *Encrypted* for encrypted messages in message preview

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#575]
Especially with PGP inline encrypted messages we don't want to show the base64-encoded encrypted text.

**Comment by Diagoras** [comment]
As I have a PR open, I'll pick this up.

**Comment by alexandre75** [comment]
PR https://github.com/k9mail/k-9/pull/884 fixes this issue
Commit
6ac682dcd623b1e473140a68b79cd9f9d1bc8726
