### ISSUE TITLE
Change default poll frequency / push. Add choice to account setup

### ISSUE THREAD

**Issue by PhoenixIV** [k9mail/k-9#5768]
**Is your feature request related to a problem? Please describe.**
A client complained that he receives emails on his phone with this "bad new app" only ages after they were sent. This way I realized the default setting for new IMAP accounts is "Poll every 1 hour".

**Describe the solution you'd like**
I think this is a horrible default for ordinary users. It should be "push".

Default users will be most happy with instant notifications. This way nothing seems broken.

**Describe alternatives you've considered**
Let the user choose in the account setup dialog if you do not see push as good default.

**Comment by cketti** [comment]
Users can already choose the poll frequency after adding an account. Push (IMAP IDLE) comes with a lot of potential downsides. That's why it's not a great default.

**Comment by PhoenixIV** [comment]
I just created a new account and am surprised I indeed forgot that there is an option in the setup.

Please add "push" to these options. I remain with my original statement that "once per hour" is a banana default to me. Please also consider that "potential downsides" might not be enough to counterweight "instant messaging".
