### ISSUE TITLE
Automatically re-download messages stored in old DB format

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#577]
Users don't need to know that e.g. PGP/MIME signed messages stored in the old DB format can't be verified. We re-download messages behind their back.

In cases where the original message doesn't exist on the server anymore, we add a special header and do our best to convert it to a proper MIME message.

**Comment by Djfe** [comment]
isn't this done by now?

**Comment by cketti** [comment]
This hasn't been implemented. But given that we changed the DB schema quite a while ago it's hardly relevant anymore. Closing.
