### ISSUE TITLE
Leave Messages on Server with Google POP3

### ISSUE THREAD

**Issue by AdderOfCode** [k9mail/k-9#5770]
**Is your feature request related to a problem? Please describe.**
Use case: Desktop email client is the historical email repository, so desktop email client should be the only application that archives or deletes email on the server.  Desktop should contain every email received.  K-9mail is used when away from the desktop for new email while away from the desktop (not for having a complete set of email on the phone).  The problem I'm encountering is email is accessed by k9mail, the message is gone, and no longer available to the desktop client, and the desktop client no longer is a complete record of all emails.

**Describe the solution you'd like**
K9mail would pull from POP3 server but leave the mail on the server.  Gmail configuration allows POP3 to have deletion, archival, etc "when messages are accessed".  I would like K9mail to access the messages, but not take any action on the server. 

This had been working earlier, for many years.  When I was away from home, I'd get new mail on my phone, and when I got back to the desktop machine and pulled email, all the email would go to the desktop client, and I had Gmail configured to trash when pulled by the desktop email client.  Thus, no need for a lot of space provided by Google.  But something happened and now the mail gets removed by the first email client to get to the email message.

**Describe alternatives you've considered**
I looked at IMAP, but that seems to require that Google hold on to all of my email.  I don't want or need Google to hold on to all of my email.  I want my local desktop machine to hold all my email, which gives me the ability to index and search most quickly.

**Comment by ByteHamster** [comment]
>  I don't want or need Google to hold on to all of my email.

When you use gmail, they have access to your mail independently of the protocol. You should only use email providers that you trust :)

> I want my local desktop machine to hold all my email, which gives me the ability to index and search most quickly.

Indexing and searching is fast with imap, too, because the clients usually just keep a local copy of all messages

**Comment by cketti** [comment]
K-9 Mail doesn't automatically remove messages from the server when downloading them via POP3. Gmail supports multiple POP3 modes. See https://support.google.com/mail/answer/7104828?hl=en#zippy=%2Ci-want-to-download-emails-on-multiple-email-clients

POP3 is not a great fit for how K-9 Mail works. We'll probably remove support for it in the future. Consider using IMAP to access your email account using K-9 Mail.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.

**Comment by AdderOfCode** [comment]
@cketti Thanks for the reply.  The page you reference says instructs the user to manage the settings of the email client to leave messages on server.  **That's what seems to have gone missing from K-9 Mail.**

    Change your POP settings so that your emails are left on the server.
    Outlook: Go to your Accounts, click Advanced and then Leave a copy of messages on the server.
    Apple Mail: On the "Advanced" tab, uncheck the box next to "Remove copy from server after retrieving a message," if available.
    Thunderbird: On the "Server Settings" tab, check the box next to "Leave messages on server."

I'll take it to the forums.
