### ISSUE TITLE
Colorize font color or background for new emails

### ISSUE THREAD

**Issue by binarydad** [k9mail/k-9#5771]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Bolding the font isn't enough in most cases IMHO. I'd like for the option to colorize either the font or background of the new/unread message to better distinguish between unread ones. 

**Describe alternatives you've considered**
There doesn't seem to be other options.

Thanks!

**Comment by ByteHamster** [comment]
Settings » Display » Change background color when read

**Comment by binarydad** [comment]
> 
> 
> Settings » Display » Change background color when read

Saw that. Not what I'm requesting. Thanks though.

**Comment by ByteHamster** [comment]
Hmm? What are you requesting then?

> I'd like for the option to colorize either the font or background of the new/unread message

That's exactly what the "change background color when read" option does. It shows unread messages with another background color.

**Comment by binarydad** [comment]
I don't want the read messages dimmed grey, as they are in the light theme. I want some sort of color to the new emails. 

You're saying when "read", I'm saying when "unread".

**Comment by ByteHamster** [comment]
So you want the setting exactly like it is, just with the two background colors swapped?

**Comment by cketti** [comment]
We'll try to make it easier to distinguish between read and unread messages (especially when using the dark theme) in a future version of K-9 Mail. However, I don't want to add yet another setting to customize the appearance of read/unread messages.
