### ISSUE TITLE
No info about sender/subject in notifications

### ISSUE THREAD

**Issue by roughnecks** [k9mail/k-9#5773]
Hello,
tried searching about this issue before posting but couldn't find anything related.

I have push notifications on but any new notification in my phone's status bar just says "you have a new message on 'account'" and it completely omits the sender and/or the subject.

I searched in app's settings for notification options but couldn't find anything about this.
Is there a fix?

Thanks

**Comment by cketti** [comment]
You probably configured your Android to hide sensitive notification content on the lock screen. You can configure what K-9 Mail displays in that case under *Settings > General settings > Notifications > Lock Screen Notifications*.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
