### ISSUE TITLE
Wrong "to" list, when replying to Google Groups

### ISSUE THREAD

**Issue by GrumpyLuddite** [k9mail/k-9#5774]
Google Group is set so that replies should go to the group, not the sender. However, “reply” in K9 puts both the group and the sender in the “to” list. K9 should only send to the group, which is the behaviour of other email clients, such as Outlook.

For illustration, in an email with the below headers, when "reply" is clicked, K9 puts both MEMBERNAME@MEMBER.DOMAIN and GROUPNAME@googlegroups.com in the "to" list. It should only include GROUPNAME@googlegroups.com

Delivered-To: MYNAME@MY.DOMAIN
Envelope-To: MYNAME@MY.DOMAIN
Sender: GROUPNAME@googlegroups.com
From: GROUP MEMBER NAME <MEMBERNAME@MEMBER.DOMAIN>
To: <GROUPNAME@googlegroups.com>
Reply-To: GROUPNAME@googlegroups.com
Precedence: list
Mailing-list: list GROUPNAME@googlegroups.com;

**Comment by cketti** [comment]
> However, “reply” in K9 puts both the group and the sender in the “to” list.

I can't reproduce this. K-9 Mail 5.806 will use the `Reply-To` address when the *Reply* action is used. However, it will use the `Reply-To` and the `From` address when the *Reply all* action is used.
