### ISSUE TITLE
Option To Use Previous From Address When Replying

### ISSUE THREAD

**Issue by seniorm0ment** [k9mail/k-9#5781]
Is your feature request related to a problem? Please describe.

When replying to a series of e-mails, it resets the from address everytime.
I've screwed up on multiple occasions by using my main address, when I forgot to switch it to an alias.

Describe the solution you'd like

Offer an option to have K9 automatically use the last from address when replying to a message that is grouped with it's previous replies.

Like when I reply to someone's email, then they reply back, and then I reply back again I'm suggesting it automatically uses the from address I sent it with, or replied last with to that person.

**Comment by cketti** [comment]
When replying to a message, K-9 Mail already searches the recipient headers `To`, `CC`, `X-Original-To`, `Delivered-To`, and `X-Envelope-To` to see if any of the addresses match the address of an identity of the current account. 

Can you describe your setup (accounts, identities) in a little bit more detail? Do you have any idea why that mechanism isn't working for you?

**Comment by seniorm0ment** [comment]
So, I had a conversation going with somebody using an alias lets say test@mail and the actual mailbox is senior@mail
Now everytime I replied to that conversation I had to manually select test@mail by clicking the from address. It did not check my previously used from address in that conversation (test@mail) and change it to that.

Hope that was clear, apologies if I'm using any terms incorrectly

**Comment by cketti** [comment]
Are `test@mail` and `senior@mail` different accounts in K-9 Mail? Or are both identities (*Settings > [Account] > Sending mail > Manage identities*) on the same account?

**Comment by seniorm0ment** [comment]
senior@male is the account, test@mail is an identity for that account.

**Comment by jondaley** [comment]
Probably you should copy and paste the headers of the email you are replying to. That feature works how I would expect it to for me (when an incoming email matches an identity and I reply, the from address is set appropriately).

I wonder if there is a problem is multiple identities match, and so it might depend on header order and/or identity order?

**Comment by michaelblyons** [comment]
For those who found this issue thinking it was about arbitrary sender names for catch-all or "plus" email addresses, that is issue #935. This one appears to be for distinct created identities.

**Comment by bigretromike** [comment]
> When replying to a message, K-9 Mail already searches the recipient headers `To`, `CC`, `X-Original-To`, `Delivered-To`, and `X-Envelope-To` to see if any of the addresses match the address of an identity of the current account.
> 
> Can you describe your setup (accounts, identities) in a little bit more detail? Do you have any idea why that mechanism isn't working for you?

Does it ? because it does not work for me ....
