### ISSUE TITLE
Jump to inbox when selecting different account

### ISSUE THREAD

**Issue by PhoenixIV** [k9mail/k-9#5785]
**Is your feature request related to a problem? Please describe.**
Whenever I switch accounts I usually always want to see the inbox, no other folder. However, the side menu remains open after choosing the right account.

**Describe the solution you'd like**
To me it makes sense to automatically close the menu and show the inbox when pressing on / choosing an account. But this is just from my personal usage statistics. If most users close the menu right after they switched accounts, it makes sense to me to make this the default behaviour. In case I then want to navigate I can open the menu again.

**Comment by cketti** [comment]
Set *Settings > [Account] > Folders > Auto-expand folder* to *Inbox*.

**Comment by PhoenixIV** [comment]
Sweet, thanks! ☺

Default to inbox, maybe?

**Comment by cketti** [comment]
See #5792

**Comment by PhoenixIV** [comment]
Oh sweet. I love to see you took my suggestion as valuable.
