### ISSUE TITLE
Add setting to delete messages from the server after download

### ISSUE THREAD

**Issue by v3rlain3** [k9mail/k-9#580]
I can not find how to delete messages of the server to download

**Comment by cketti** [comment]
Deleting messages from the server after download is currently not supported.

**Comment by v3rlain3** [comment]
thanks for the quick response. We hope this functionality is added.

**Comment by HugoFlorentino** [comment]
Deleting mail after retrieving is the default behavior for POP3 in regular PC mail clients, usually one has to enable the option to leave mail on server. Actually I was a little surprised to see that a mail client as complete as K9 does not have this feature yet.

**Comment by denim2x** [comment]
@v3rlain3 Please consider backing this issue at [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=9592317)](https://www.bountysource.com/issues/9592317-add-setting-to-delete-messages-from-the-server-after-download?utm_source=9592317&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by cketti** [comment]
With the plan to not support local messages (#4970) this feature is no longer desirable.
