### ISSUE TITLE
Support custom notification sound on Android 7 and older

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#5806]
On Android versions prior to Android 8 we display our own notification sound picker ("New mail ringtone"). The component uses [`RingtoneManager`](https://developer.android.com/reference/kotlin/android/media/RingtoneManager) to retrieve the list of notification sounds. But on Android versions prior to Android 10 `RingtoneManager` will only return custom notification sounds if the app holds the [`READ_EXTERNAL_STORAGE`](https://developer.android.com/reference/kotlin/android/Manifest.permission.html#READ_EXTERNAL_STORAGE:kotlin.String) permission. Since we no longer request that permission custom notification sounds can't be selected.

I don't want the app to request the `READ_EXTERNAL_STORAGE` permission just to support custom notification sounds. Given that, I believe we have two options:
1. Use the system picker for notification sounds: [`ACTION_RINGTONE_PICKER`](https://developer.android.com/reference/kotlin/android/media/RingtoneManager#ACTION_RINGTONE_PICKER:kotlin.String). ~Investigate whether this will allow picking custom notification sounds without the calling app having the `READ_EXTERNAL_STORAGE` permission.~ (seems to work on an API 24 emulator)
2. Use the storage access framework to pick a notification sound, then copy it to app-private storage and expose it via a content provider to the system, e.g. using [PublicFileProvider](https://github.com/cketti/PublicFileProvider).

**Comment by singulararmchair** [comment]
Still an issue with 6.000 on Android 7.1.2. Cannot pick ringtone from storage.
