### ISSUE TITLE
Show number of starred messages in folder view

### ISSUE THREAD

**Issue by skleber** [k9mail/k-9#5810]
Part of my daily mail workflow is marking messages with stars to come back to them later. These messages are distributed over many folders into which mails are sorted server-side.

Before the big and great (I like it in general) UI change, the **number of starred messages** was shown in the **list of IMAP folders** for each folder. This was very helpful. I would like to request this feature coming back.

The unified inbox allows to show all messages in one place, but you have to add all relevant folders one-by-one to be displayed to achieve this. An overview where to look for starred messages in the folder list would be more readily suitable, at least for my usage. 

Therefore, I would like to kindly ask you to consider the feature request. If I can assist in any way, please let me know.

**Comment by cketti** [comment]
This functionality is available in K-9 Mail 5.900 and newer.

Duplicate of #5467

**Comment by skleber** [comment]
Hmmm... okay. Although a closed issue might not be the right place for this, but:
Problem then is that the Play Store distributes 5.806. What is the preferred way for distribution to stay current?

**Comment by cketti** [comment]
K-9 Mail 5.9xx are beta versions. See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68
