### ISSUE TITLE
Notification causes vibration for account despite disabled vibration

### ISSUE THREAD

**Issue by dadosch** [k9mail/k-9#5811]
**Describe the bug**
Since version 5.905, the settings of disabled vibrations for a single account doesn't have a effect. The notification still causes a vibration.

**To Reproduce**
1. Add a account and set the notification to not cause vibrations.
2. Receive a email. Note that the notification causes vibration.

**Expected behavior**
The notification should not cause a vibration, since it is disabled

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.905
 - Android version: 7.1.2
 - Device: BQ Aquaris U plus
 - Account type: IMAP

**Additional context**
The problem started appearing in version 5.905.

**Comment by cketti** [comment]
Thanks for reporting this. The bug should be fixed in the next beta version.
