### ISSUE TITLE
Push updates via distributors

### ISSUE THREAD

**Issue by hockeymikey** [k9mail/k-9#5827]
Currently there is the push feature that requires a running background process.
That's great, but wastes a lot of battery and isn't perfect for everyone. I propose the creation and an external push functionality that relies on an external distributor to receive updates. The architecture would be a self hosted server that checks for the updates in the specific folders. The app gives the servers these credentials. The server doesn't keep track of all emails, just enough information to determine when a new one arrives. When it does, it sends out a notification via a distributor. There are two main ones I think should be supported:
Google's FCM
UnifiedPush (https://unifiedpush.org/users/intro/)

The user can configure which to use. The app would detect each distributor on the phone and use whatever is available. A data message should be sent containing no identifying information such as message content or email. The server and client should configure some uuid for the email account in question and use that to alert the app that an update is available. A uuid for folders can be used too. A background service is than ran to poll and fetch the updates for that particular account. 
Biggest advantage for this setup is battery efficiency and instantaneous notifications of new emails.  It would require some setup from the user, but would be in line with the FOSS individuals who already self host stuff. Exploring how to privatize the passwords/connection on the server side would be nice too so a user can use a publicly shared endpoint while not risking their security. Not really possible on initial thoughts, but I could be incorrect.

**Comment by cketti** [comment]
I suggest you look into how JMAP solved the "support different push services" problem, then propose an IMAP extension to use a similar approach. Once a server supports this new standard, we'd be happy to add support for different push services.

We're not going to add support for a solution that requires handing over user credentials to a push service or requires the user to set up their own server. But please feel free to fork the app and this functionality yourself.

**Comment by hockeymikey** [comment]
@cketti JMAP doesn't solve this problem. It's cool, I like it, but its not THE solution. The oauth approach for Gmail already requires a user to setup their own keys so it's not inconsistent of an approach. I was going to explore this solution in my own time and merge in sometime, mostly use this issue as a longer term tracker and getting others ideas/solution. But if one is too rigid in their thinking than a spinoff will be required. Maybe one more updated and supported.

**Comment by cketti** [comment]
How does JMAP not solve this problem? A client can tell the JMAP server to notify an arbitrary HTTP server when a new message arrives. That server can then use whatever Push mechanism it chooses to notify the app. This does not require the app to hand over user credentials to the Push service.

**Comment by hockeymikey** [comment]
Haha, idk guess it is. Granted not supported anywhere but the jmap proxy exists which would be super useful. Change the behavior of it to support additions via requests instead of a pre-configuration. Still wouldn't solve the credential issue.
