### ISSUE TITLE
Automatically attach public key

### ISSUE THREAD

**Issue by marhu98** [k9mail/k-9#5840]
AFAIK, there is no way to automatically attach ones public PGP key. This is a little dangerous because it is prone to people forgetting to send their keys (à la Snowden for example).

This should be an easy feature to implement. I apologize if this is inconvenient.

**Comment by cketti** [comment]
K-9 Mail implements Autocrypt. That means a special header that includes your public key is added to all outgoing messages. 
See https://autocrypt.org/
