### ISSUE TITLE
Add option to never remember email account password.

### ISSUE THREAD

**Issue by zellchristensen** [k9mail/k-9#5874]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.806

### Problem you are trying to solve

With the rise in demand for more security in mobile applications (as evidenced by requests like https://github.com/k9mail/k-9/issues/753, https://github.com/k9mail/k-9/issues/1352, https://github.com/k9mail/k-9/issues/3318, https://github.com/k9mail/k-9/issues/3377, https://github.com/k9mail/k-9/issues/3920, https://github.com/k9mail/k-9/issues/4796, https://github.com/k9mail/k-9/issues/5260, https://github.com/k9mail/k-9/issues/5740) a lot of users are trying to seek solutions for common security risks such as unauthorized device access and network sniffing for credentials.  I understand K9 isn't an advanced security application, nor should it be, but I think this can give some users a much wanted peace of mind.

### Suggested solution

I'd like to have an option for K9 to NOT remember my email account password and just prompt the user to enter it if and when needed.

This way the user can rely on a third party application for encrypting their credentials or they can remember their password manually.  While this won't prevent unauthorized access to existing data on the device, it will prevent new data from being sent to the device and give protection against unauthorized users sending data using the saved account.  

It can also help the user to be more aware of the network they're connected to in the event they're connected to a rouge network or otherwise at risk for a man in the middle type of attack.

### Screenshots / Drawings / Technical details

If implemented, it'd probably be good to have an option in the per account settings, probably under general settings.  It could just be a simple checkbox for "Remember password" that's checked by default.

Another checkbox could be added when adding a new account to "remember" the password that would have to be unchecked. 

There could also be a global setting in the main General Settings under Privacy that unchecks it for all existing accounts (perhaps with a warning that any existing stored passwords will be removed) and keeps the creation checkbox unchecked by default.  

The effects could cause the app to prompt the user for the password for a given account when the app is opened, when a manual or automatic update is triggered, or when sending an email or other server request.

When entered, the password would be used for that connection attempt and "forgotten" when finished.  It would be similar to how Thunderbird operates if you decline to have it remember account passwords.

**Comment by cketti** [comment]
What you're suggesting would require large changes to the way the app works. The user experience would also not be something most users expect or want. Making this an optional feature would just add even more complexity. 

I wrote down numerous times why such a feature doesn't improve security in a meaningful way if you use the security features Android already offers. Since you've linked the relevant issues, I assume you already know this.

If you need this feature, K-9 Mail is not the app for you.
