### ISSUE TITLE
Autocomplete email address

### ISSUE THREAD

**Issue by Donkey-Doug** [k9mail/k-9#5886]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.909

### Problem you are trying to solve

I don't know people's email adresses.

### Suggested solution

When I want to send an email to Albert.Einstein@outlook.com and I start typing in the email adress field, as soon as I type the letter "a" outlook suggest Albert.Einstein@outlook.com (as well as other email adresses that are in my contacts and start with the letter a).

This does work in the official outlook app, but not in k9 mail. I wouls like this feature in k9 mail. I.e., I would like for K9 mail to have access to the email adresses in my outlook account.

**Comment by cketti** [comment]
K-9 Mail already suggests addresses from your contacts database when at least 2 characters have been entered (and you've granted the app read access to contacts).

We have no plans of adding address book synchronization to K-9 Mail. If you want to sync your Outlook address book to Android, you'll have to use an app that supports that. Once the address book is synced to the system contacts database, K-9 Mail will be able to read the data.

**Comment by Donkey-Doug** [comment]
> K-9 Mail already suggests addresses from your contacts database when at least 2 characters have been entered (and you've granted the app read access to contacts).
> 
> We have no plans of adding address book synchronization to K-9 Mail. If you want to sync your Outlook address book to Android, you'll have to use an app that supports that. Once the address book is synced to the system contacts database, K-9 Mail will be able to read the data.

Does not work for me. I need to open outlook in a browser, find an email adress, copy it and paste it in k9,

Do I need to modify settings in k9 or outlook?

**Comment by cketti** [comment]
K-9 Mail only knows about contacts in your Android contacts database. Your Android version should come with a "contacts" app that displays the contents of this database.

If you're using outlook.com to manage contacts, make sure they are synced to Android's contact database. I can't help you on how to accomplish that. But I'm sure outlook.com has a support channel.

**Comment by Donkey-Doug** [comment]
> K-9 Mail only knows about contacts in your Android contacts database. Your Android version should come with a "contacts" app that displays the contents of this database.
> 
> If you're using outlook.com to manage contacts, make sure they are synced to Android's contact database. I can't help you on how to accomplish that. But I'm sure outlook.com has a support channel.

Then this issue should be reopened, since this is exactly the problem I tried to describe.
