### ISSUE TITLE
Remove default mail signature

### ISSUE THREAD

**Issue by sspind** [k9mail/k-9#589]
An issue for the same topic was already opened on [google code](https://code.google.com/p/k9mail/issues/detail?id=5953). It boils down to: the default signature is unprofessional, annoying and judging from the top google hits it is also the first thing that people try to get rid when starting to use k9.

**Comment by cketti** [comment]
Being "professional" is not one of the goals of this project.

If you're bothered by the signatures of your communication partners I'm happy to review pull requests for a feature to hide signatures in mails received.

**Comment by sspind** [comment]
And annoying it's users is? Don't get me wrong - I am perfectly aware that this is an open source project, done by people in their free time. But does that mean we give a crap about user experience? I would at least 'put it to the vote' and leave the issue open to see what others have to say about it...

**Comment by lawsonk** [comment]
On March 26, 2015 6:46:17 PM EDT, sspind <notifications@github.com> wrote:
>And annoying it's users is? Don't get me wrong - I am perfectly aware
>that this is an open source project, done by people in their free time.
>But does that mean we give a crap about user experience? I would at
>least 'put it to the vote' and leave the issue open to see what others
>have to say about it...
>
>---

I'm  new to the list so maybe I'm  ignorant  but what's  the issue here? The app allows you to change and/or diasble signatures. How is that a bad user experience?

**Comment by sspind** [comment]
The issue is with the default signature which I claim to be unnecessary. It really is just a personal preference - one that I share with quite a few people at least judging from the results you get from googling 'k9 signature'.

**Comment by philipwhiuk** [comment]
All mobile email clients I think provide the first clause. "Sent from my iPhone" is the default signature on every iPhone device. My HTC's default signature is 'Sent from a HTC One".

"Please excuse my brevity." is perhaps over kill however.

Maybe we should present the signature configuration during account set-up?

**Comment by sspind** [comment]
That would be great but also more complicated to implement...
