### ISSUE TITLE
Pointless notifications "Waiting for new email" and "Sleeping until background sync is allowed" in notification centre

### ISSUE THREAD

**Issue by jms19** [k9mail/k-9#5903]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

7.0

### Device model

Samsung Galaxy S6

### Steps to reproduce

1. Have K-9 installed and configured in the usual way
2. Run it at least once

### Expected behavior

There should not be notifications for things that are obvious. These annoying notifications are a relatively new addition to K-9 perhaps in the last year or so.

All applications that interact with the internet are either waiting for something from it or waiting to be enabled (by the Sync setting in this case).

Luckily K-9 is the only app I have that does this.

### Actual behavior

As subject one of these pointless notifications depending on the Sync setting.

**Comment by cketti** [comment]
When tapping the "pointless" notification a screen is displayed that contains information about why it is necessary. That screen also contains a link to a page containing further information.

https://forum.k9mail.app/t/how-to-configure-push/1102

Side note: It looks like you're a software developer yourself. Do you really believe "Have K-9 installed and configured in the usual way" is an appropriate answer when asked to provide steps to reproduce an issue? (This is a rhetoric question. Please don't answer.)
