### ISSUE TITLE
Ability to block mailers

### ISSUE THREAD

**Issue by binex-dsk** [k9mail/k-9#5917]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

I would like to prevent recurring junk mailers (who aren't caught by the spam filter) to be unable to email me.

### Suggested solution

Allow us to block mailers, via email or their contact

### Screenshots / Drawings / Technical details

When you select a message, in the three-dots conext menu, add an option to "block contact(s)".

**Comment by cketti** [comment]
In general this should be done on the server-side rather than by an email client. Check if your provider supports server-side filter rules.

Adding support for local filters is tracked under #908.

**Comment by HonestAbe7** [comment]
This would be really great to have. I so want to switch from BlueMail to this app but this feature alone prevents me from doing so.
