### ISSUE TITLE
there is a problem with connecting to gmail.

### ISSUE THREAD

**Issue by saber716rus** [k9mail/k-9#5920]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Redmi note 8 pro

### Steps to reproduce

the fact is that authentication in the account is carried out via the phone or by password. two-factor protection is not enabled.
1. Go to settings
2. Add account
3. I enter my gmail username and password
4. Enter next

### Expected behavior

authorization in the account.

### Actual behavior

I see 2 errors.
![Screenshot_2022-02-15-18-01-58-575_com fsck k9](https://user-images.githubusercontent.com/22714555/154091559-57a87ec9-54cd-42a6-941a-7d601e2a8e75.jpg)
![Screenshot_2022-02-15-18-01-52-246_com fsck k9](https://user-images.githubusercontent.com/22714555/154091571-3e3263ac-de06-474a-b3ed-d00ade383879.jpg)

**Comment by cketti** [comment]
Have you tried visiting the URL mentioned in the error message from the server? https://support.google.com/mail/?p=BadCredentials

See also https://forum.k9mail.app/t/how-to-set-up-with-a-gmail-account/3812

**Comment by saber716rus** [comment]
> Have you tried visiting the URL mentioned in the error message from the server? https://support.google.com/mail/?p=BadCredentials
> 
> See also https://forum.k9mail.app/t/how-to-set-up-with-a-gmail-account/3812

only after enabling two-factor protection and creating a password for the application. I had a phone login enabled and if the login was suspicious, a password was requested.
