### ISSUE TITLE
it is difficult to separate read emails from unread ones

### ISSUE THREAD

**Issue by saber716rus** [k9mail/k-9#5921]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

the essence of the problem is that it is hard to see where the read ones are and where the unread ones are

### Suggested solution

the solution to the problem is to mark unread emails, not only in bold, but also in a different line color from the lines of read emails.

### Screenshots / Drawings / Technical details

![Screenshot_2022-02-15-18-04-33-368_com github android](https://user-images.githubusercontent.com/22714555/154150955-9d70919b-f4a1-460f-b04b-980a55910d48.jpg)

**Comment by cketti** [comment]
Have you tried to enable *General settings → Display → Change color when read*?

**Comment by saber716rus** [comment]
It's working, I'm closing it.
