### ISSUE TITLE
message/rfc822 as intent type not received

### ISSUE THREAD

**Issue by Ph1b** [k9mail/k-9#593]
When I send an intent from my app like this:

```java
Intent emailIntent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts(
    "mailto", "woitaschek@gmail.com", null));
emailIntent.setType("message/rfc822");
emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Subject");
emailIntent.putExtra(Intent.EXTRA_TEXT, "Hello k9 dog");
Intent startClientIntent = Intent.createChooser(emailIntent, "Sending Mail...");
startClientIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
try {
    getApplicationContext().startActivity(startClientIntent);
} catch (ActivityNotFoundException ignored) {
}
```

K9 Mail wont receive that intent unless I remove the type

```java
//emailIntent.setType("message/rfc822");
```

**Comment by cketti** [comment]
Don't just copy code snippets off the internet. Check the [documentation of ACTION_SENDTO](https://developer.android.com/reference/android/content/Intent.html#ACTION_SENDTO). There you can see that EXTRAs aren't officially supported with `ACTION_SENDTO`. Also, you don't have to specify a type.

You can use the [MailTo class](https://developer.android.com/reference/android/net/MailTo.html) to create the necessary `mailto:` URI.
