### ISSUE TITLE
Now K-9 can work with onion SMTP servers and Proxy Support

### ISSUE THREAD

**Issue by r00t34** [k9mail/k-9#5939]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

K-9 proxy problem and onion smtp server

### Suggested solution

https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/

I found this man and he claims that solution can solve the proxy support and onion smtp server usage with K-9. I am not software developer and don't know the commits but he shared all the info in that page. If K-9 developers can examine the article that would be great for us especially who is using onion SMTP servers like me.

**Comment by cketti** [comment]
See #980
