### ISSUE TITLE
Add the ability to use multiple aliases and bindings to your mailbox

### ISSUE THREAD

**Issue by saber716rus** [k9mail/k-9#5944]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

I have both Russian-speaking recipients and English-speaking ones. And I need to use multiple aliases for one mailbox.

### Suggested solution

Solution: in the mailbox settings, add the ability to create multiple aliases.

**Comment by cketti** [comment]
K-9 Mail already supports multiple identities. You can add an additional one under *Settings → [Account] → Sending mail → Manage identities*.

**Comment by saber716rus** [comment]
Thanks
