### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [k9mail/k-9#5950]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

Read: https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html

### Suggested solution

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are
the scan results. I found the following:

6 data types
0 SDK.

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄

### Screenshots / Drawings / Technical details

![image](https://user-images.githubusercontent.com/87804852/157170121-bcb7d053-b229-4eb7-965f-5925cf53336e.png)
![image](https://user-images.githubusercontent.com/87804852/157170137-3ebc9183-1cf5-4f8c-b519-106a4432ec98.png)

**Comment by ssb22** [comment]
K-9 Mail was removed from the Play Store at some point during the last 7 days.  I don't know if that was due to this issue or something else.

**Comment by ByteHamster** [comment]
> K-9 Mail was removed from the Play Store at some point during the last 7 days. I don't know if that was due to this issue or something else.

Something else. Google wants login credentials to test apps and apparently they did not really understand that K-9 does not have email servers - it is just the app.

> I have run the scan using my tool here on your repo, attached are the scan results. I found the following: 6 data types

That is just what is needed for the app to work. The data is not collected or shared.
