### ISSUE TITLE
k9mail get access of address book 149times in 2  minutes

### ISSUE THREAD

**Issue by FreedomLoading** [k9mail/k-9#5963]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.913

### Problem you are trying to solve

I found that k9app gets the address book 150 times in two minutes. Is this because of the app or because of the system I am using? The system I am using now is MIUI12.50

### Suggested solution

Please help to confirm, thank you

**Comment by ByteHamster** [comment]
If you have enabled the setting "show names from address book", K-9 needs to access the address book. That's expected behavior.

**Comment by FreedomLoading** [comment]
> If you have enabled the setting "show names from address book", K-9 needs to access the address book. That's expected behavior.

ok. got it. thanks
