### ISSUE TITLE
Auto Update Interface. 

### ISSUE THREAD

**Issue by blogmangit** [k9mail/k-9#5986]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.914

### Problem you are trying to solve

At present there is  no user interface  present for directly updating from within the app.

### Suggested solution

Please introduce an user interface for updating the app version directly from within the app itself like say implemented in app telegram, newpipe etc.

**Comment by cketti** [comment]
Both F-Droid and Google Play support automatically updating apps. Why would we duplicate this functionality inside the app?

**Comment by blogmangit** [comment]
yeah but often google play rejects k9 mail policy and remove the app from playstore just like now they did that is the reason besides why depend on any store if it can be implemented  in such a way that we get the download directly from github after tapping check for updates or something  like that.

**Comment by cketti** [comment]
Implementing an auto-update mechanism is a non-trivial problem. Also, I'm sure GitHub wouldn't like it if we used them as the backend for our auto-update service. I'd rather concentrate on building an email app.

If you are annoyed at Google for removing the app from the Play Store, I suggest you let them know e.g. via Twitter: https://twitter.com/GooglePlayDev
But what's probably more effective, is using [F-Droid](https://f-droid.org/) instead.

**Comment by blogmangit** [comment]
ok will do.

Regards.
