### ISSUE TITLE
Favicons for mails

### ISSUE THREAD

**Issue by ThemGo** [k9mail/k-9#5997]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

For the mails without a contact picture, the message list shows colored circles with a letter in it . I think this is confusing and could be improved.

### Suggested solution

It would be great to have the option to see the favicon of the server of the mail sender's address (for those messages without a contact picture). E.g. show the favicon of server gmx.net if the sender was john.doe@gmx.net. I think this would make the list much clearer.  If there is no favicon for a server then just show the previous colored circle or maybe show no picture at all.

**Comment by cketti** [comment]
I don't want to include such functionality in K-9 Mail.

**Comment by smithbill17** [comment]
Why not? This is something that has become a key feature of modern email clients (Spark, BlueMail, Outlook, Fairemail etc etc)
