### ISSUE TITLE
Will k-9 support new secure policy of imap on gmail ?

### ISSUE THREAD

**Issue by lichenchenchenchen** [k9mail/k-9#6020]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.6

### Problem you are trying to solve

"To help keep your account secure, starting May 30, 2022, ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password."

I've received this message from google when I blocked from login through imap and had to go to google account settings .

And from then I saw:
"[Use more secure apps]
If an app uses less secure sign-in technology, you might not be able to use it with your Google Account.

You can sign in to your Google Account from any third-party app that has the "Sign in with Google" option. You can also sign in to your Google Account using all Google products, like Gmail."

Sorry about that I am still using k-9 mail version 5.6 ,so could anyone tell me about the new versions that already support new secure policy of gmail or is something else that I need to set to ? 

### Suggested solution

So I upgrade k-9 mail to the 5.916 ,these's no so called "sign in with google" .
I guess it will be blocked login through imap by the date google says?

**Comment by njeyaakili** [comment]
What is being disabled at the end of May is "sign in to your Google Account using only your username and password", i.e., using your google (site) pw for login. K-9 will continue to work with gmail if ... you set up, and configure k-9 to use, google "app passwords" See:

<https://support.google.com/accounts/answer/6010255>

You should probably take further questions/discussion of this to the K-9 user forum:

<https://forum.k9mail.app/>
