### ISSUE TITLE
Connection refused sometimes

### ISSUE THREAD

**Issue by hman2** [k9mail/k-9#6024]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.916

### Where did you get the app from?

F-Droid

### Android version

9 (FP Open OS 21.12.0-rel.1)

### Device model

Fairphone 2

### Steps to reproduce

1. Select a photo in Amaze (stored on SD card)
2. Share it via K-9, enter e-mail address to send to
3. Send

### Expected behavior

Mail should be sent. Instead:

### Actual behavior

4. Connection refused (mail provider is 1&1 a.k.a. Ionos, telco is E-Plus, a.k.a. O2 or Telefonica)
5. Close K-9
6. Restart K-9
7. Go to outgoing mail
8. Re-send
9. Success!

I could reproduce this behaviour seven times by now. On initial send, connection gets refused. Every time. On resending, everything works as it should... Also, every time...

**Comment by cketti** [comment]
Enable debug logging under *Settings → General settings →Debugging*, reproduce the issue, then check the log (select *Export logs* in the menu of the *Debugging* settings screen) for more information.

This is most likely a network issue, not a bug in K-9 Mail.

**Comment by hman2** [comment]
I'll do that, but how can it be a network issue if it works upon resending? Each and every time? It only fails upon initial sends. I could reproduce this behaviour seven times in a row...

**Comment by hman2** [comment]
Also: Sending text only mails works always, even on initial sends. Only mail with photo attachments are affected...

**Comment by hman2** [comment]
Another observation: Composing e-mails in K-9, adding a photo, and sending succeeds.
Only when K-9 got the photo for sharing it fails... Also, if another file (like the log file) is passed to K-9 for sharing it fails...

**Comment by hman2** [comment]
For experiments, I tried sharing directly out of Amaze to K-9 (without the image viewer in between). Then K-9 doesn't even get the file in the first place (both photo & log)... Here is the log (I just removed my e-mail addresses)
[k9mail-logs.txt](https://github.com/k9mail/k-9/files/8514249/k9mail-logs.txt)
.

**Comment by cketti** [comment]
This is the error message from Android: 

> failed to connect to smtp.1und1.de/212.227.15.183 (port 587) from /10.47.192.245 (port 55696) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)

From the timestamps in the log it doesn't look like the connection attempt actually timed out after 10 seconds (10000ms). So the server (or some other network node along the way) probably actively refused the connection. 

Like I said, this appears to be a network issue. I don't see how K-9 Mail could cause this.

**Comment by hman2** [comment]
Please explain why this only happens on the immediate attempt, while a resend runs through flawlessly. I have reproduced this behaviour SEVEN times in a row. The first send ALWAYS fails. The resend NEVER.

**Comment by hman2** [comment]
Another try with WiFi instead of 4G, significantly faster: K-9 fails not after 10 seconds, but immediately. But still "after 10000ms". So this means this error message is bogus! There were no 10,000 milliseconds (10 seconds). From send to fail there was less than one second!

**Comment by cketti** [comment]
I can't reproduce the error. I gave you my assessment of the situation based on the log you provided. To me it's very unlikely this is caused by a bug in K-9 Mail. Therefore, I'm not willing to spend the significant amount of time it would take to debug this issue with you remotely.

If you can find out what is causing this and it is indeed a bug in K-9 Mail, I'm happy to fix it. But I'm afraid it's up to you to figure out what is happening exactly and what K-9 Mail should do instead.
