### ISSUE TITLE
Show correspondent names not working

### ISSUE THREAD

**Issue by J0nnyMak0** [k9mail/k-9#6026]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

10

### Steps to reproduce

I'm using imap (idle connection) with push on all folders. 

1. Go to Settings->General Settings->Display and check "Show correspondent names"
2. Go back to Message list
3. I still see correspondent email id instead of name.

When I click "Show headers" inside any message, the "From" field looks like this:

From: foo@domain.com (Foo Bar)

### Expected behavior

I expect to see correspondent name in the Message list. ("Foo Bar" from example above.)

### Actual behavior

I see email id in the Message list. (foo@domain.com from example above)

**Comment by cketti** [comment]
> When I click "Show headers" inside any message, the "From" field looks like this:
>
> ```email
> From: foo@domain.com (Foo Bar)
> ```

Looks like you've received a message from the last millennium. The text in parentheses is a comment. Comments for display names are not typically used anymore. K-9 Mail never supported this and simply ignores comments.

For "Foo Bar" to be recognized as the display name, the header line should have looked like this:

```email
From: "Foo Bar" <foo@domain.com>
```

Try contacting the sender and ask them to update their email software.

Out of curiosity: Can you share who sent you such a message? Do you know what software they're using?

**Comment by J0nnyMak0** [comment]
> Out of curiosity: Can you share who sent you such a message? Do you know what software they're using?

These emails that are misbehaving are received through newsletter lists. I believe they are using Mailman.

**Comment by cketti** [comment]
Given that this should be extremely rare, I'd rather not spend time on adding support for display names in comments.
