### ISSUE TITLE
Will support ever be added for fido/u2f/oath?

### ISSUE THREAD

**Issue by TylerHelt0** [k9mail/k-9#6038]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.0.0

### Problem you are trying to solve

Cannot login to gmail, yahoo, other services without extra steps/lessening security. 
There is no point in using 2 factor auth on these services if k-9 requires special snowflake app passwords that bypass two factor. 
All modwrn email accounts should have this enabled. 

### Suggested solution

Add support for oath. K-9 has needed it for years now. The app will lose users and popularity if not. 
Do devs not know how to implement oath?

https://openid.github.io/AppAuth-Android/

**Comment by cketti** [comment]
"Less secure" is mostly marketing. Conceptually, an app-specific password is not not much different from an OAuth token. If you have 2FA enabled, you need the second factor to create one (no bypass). If you lose your device with an email account set up, it doesn't matter if the app is using an OAuth token or an app-specific password. Until you revoke them, the device can still access your email.

That being said, of course we want to make it as easy as possible for users to set up their accounts. Improving the account setup process, including support for OAuth, is the next thing on my list. But there's no *promise* for future functionality, much less for release dates. Features are done when they are done.
