### ISSUE TITLE
LocalMessage: getContentType needs to make sure headers are loaded

### ISSUE THREAD

**Issue by m0vie** [k9mail/k-9#604]
Otherwise, headers may not be loaded resulting in messages to be interpreted in the wrong codepage when displaying:

MessageExtractor.getTextFromPart() tries to get the charset in the following way:

    String charset = getHeaderParameter(part.getContentType(), "charset");

This fails in case part is LocalMessage and headers have not been loaded.

**Comment by m0vie** [comment]
Actually, getContentType() seems to be the only case that lead to problems so far, but technically, every other method in MimeMessage that uses mHeaders should be overridden in LocalMessage and make sure the headers are loaded.

**Comment by qiujiaheng2000** [comment]
move "parseHeaderBytes(part, header);"  outside "}" will be ok;
if (id == message.getMessagePartId()) {
            part = message;
        } else {
            Part parentPart = partById.get(parentId);
            if (parentPart == null) {
                throw new IllegalStateException("Parent part not found");
            }

            String parentMimeType = parentPart.getMimeType();
            if (parentMimeType.startsWith("multipart/")) {
                BodyPart bodyPart = new LocalBodyPart(getAccountUuid(), message, id, displayName, size,
                        firstClassAttachment);
                ((Multipart) parentPart.getBody()).addBodyPart(bodyPart);
                part = bodyPart;
            } else if (parentMimeType.startsWith("message/")) {
                Message innerMessage = new MimeMessage();
                parentPart.setBody(innerMessage);
                part = innerMessage;
            } else {
                throw new IllegalStateException("Parent is neither a multipart nor a message");
            }

            parseHeaderBytes(part, header);
        }

change to :
if (id == message.getMessagePartId()) {
            part = message;
        } else {
            Part parentPart = partById.get(parentId);
            if (parentPart == null) {
                throw new IllegalStateException("Parent part not found");
            }

            String parentMimeType = parentPart.getMimeType();
            if (parentMimeType.startsWith("multipart/")) {
                BodyPart bodyPart = new LocalBodyPart(getAccountUuid(), message, id, displayName, size,
                        firstClassAttachment);
                ((Multipart) parentPart.getBody()).addBodyPart(bodyPart);
                part = bodyPart;
            } else if (parentMimeType.startsWith("message/")) {
                Message innerMessage = new MimeMessage();
                parentPart.setBody(innerMessage);
                part = innerMessage;
            } else {
                throw new IllegalStateException("Parent is neither a multipart nor a message");
            }
        }
         parseHeaderBytes(part, header);
