### ISSUE TITLE
Delete button in notification for single email

### ISSUE THREAD

**Issue by Happy86** [k9mail/k-9#6060]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

Hi, 

it would be great if deletion of a single email would be possible from the notification. 

Currently it is only possible to reply or mark the email as read. 

Thank you. 

Best regards, 
Andreas 

### Suggested solution

Add a third button to the notification of a single email to delete the email in question. 

### Screenshots / Drawings / Technical details

Screenshot - Example in other MUA:  

![Screenshot_20220430-104009_example](https://user-images.githubusercontent.com/618847/167160139-f4b85a61-a91d-4f98-b113-da04bd35f1a5.png)

Screenshot - Suggestion for K-9 Mail:  

![Screenshot_20220430-103959_suggestion](https://user-images.githubusercontent.com/618847/167160170-8f0b21d6-b193-4224-9559-28684aee0438.png)

**Comment by cketti** [comment]
This is already possible. See https://docs.k9mail.app/en/current/settings/general/#show-delete-button

**Comment by Happy86** [comment]
@cketti Thank you very much and sorry ... clear case of did not RTFM. :-) 

Maybe you can add this as an additional `- [ ]` in the form to create a new issue (read the documentation). :D

**Comment by ThomasHeinrichSchmidt** [comment]
I have almost the same feature request, but not requesting "deletion of a single email" - which is already possible - but to qualify an email as SPAM directly from the notification for a single email. 
This way, I don't even need to open K-9 to remove the spam.
