### ISSUE TITLE
Everything has vanished

### ISSUE THREAD

**Issue by sisterpete** [k9mail/k-9#607]
I'm a long time user of k-9... Never any problems on several phones through the years.  My Samsung s3 was getting a bit slow earlier, (wasn't using k-9 by the way) so I rebooted.  Very shortly I needed to reference an email from last week, so I went to k-9.  

The first thing I noticed was my icons on the screen (I have shortcuts to each account as I have multiples) were missing and just a white mail folder was in their place... Even the name is gone and replaced with "k-9 mail"

I tapped on each one and everything is gone.  My color theme, all my folders, emails, accounts, EVERYTHING!!!

The only thing that shows up is a bar at the top that says "show unread count for..." And two selections, one says "unified inbox" and "all messages".  Clicking on either of these brings up a "busy" screen but nothing happens at all.  If I click the back arrow at the top, it takes me to the welcome screen as if I've just installed k-9.  Also back on the home screen, the text under the white Mail icon changes from "k-9 mail" to "all messages"

I also opened up k-9 from the actual icon in the apps folder and it takes me directly to the welcome screen.

All my other apps seem to be working just fine...

Any help would be greatly appreciated.

Thank you, Jimmy

If I go into application manager, it shows the following...
Total: 6.28mb
Application: 6.14mb
USB Storage app: 0.00mb
Data: 140kb
Sd card: 0.00mb. (I have no ad card in the phone)

The sprint s3 info...
Model: SPH-L710
Android version: 4.1.2
Baseband version: L710VPBMD4
Kernel version: 
3.0.31-1130792
se.infra@SEP-132 #2
SMP PREEMPT Mon Apr 15 19:05:47 KST 2013

Build number: JZO54K.L710VPBMD4
Hardware version: L710.14

**Comment by cketti** [comment]
Sounds like the data directory was cleared.

For general questions like this please use the mailing list: http://groups.google.com/group/k-9-mail
