### ISSUE TITLE
"Exit" option in menu

### ISSUE THREAD

**Issue by dapgo** [k9mail/k-9#608]
In my opinion an "Exit" option in menu is good feature for all Android apps, in order to stop the service inmediatedly and free memory when email is not being used. 

I like to see that K9 sometimes disappear from services in use after few minutes, and probabily 16MB of K9 is not much memory in devices with 1Gb or 512 but it in devices with 256MB anything in memory has impact in performance.

**Comment by cketti** [comment]
We won't add an exit button. If you don't want K-9 Mail to run in the background disable automatic mail checks.
