### ISSUE TITLE
Unable to connect K-9 mail with Gmail - When will K-9 mail be considered a secure app

### ISSUE THREAD

**Issue by shenzhenadam** [k9mail/k-9#6107]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.00 & previous versions

### Problem you are trying to solve

Unable to connect K-9 mail with Gmail - When will K-9 mail be considered a secure app by Google???

We all know that on 30 may 2022 that Google turned off functionality for less secure apps. K-9 is obviously considered a less secure app while Thunderbird email client is considered a secure app and can still use with no problem. 

We need Google to approve K-9 mail as a secure app ASAP - I don't use a mobile number and so using other 2FA is impossible as a mobile no. is required to start the 2FA process. I have several g-mail accounts in K-9 and so would need to use multiple mobile numbers to use 2FA if I were to go down that route.

I have one Yandex email working through K-9 with no problem - they just ask you to register app with Yandex and they give you a special password without having to give over your mobile number - asking for one's mobile number these days infringes on personal security, safety and other vulnerabilities.

Hope the K-9 developers can get an exception from Google.

### Suggested solution

Hope the K-9 developers can get an exception from Google to make K-9 mail a secure app.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-to-use-a-gmail-google-workspace-account-with-k-9-mail/4727
