### ISSUE TITLE
Additions to available 'Visible message actions'

### ISSUE THREAD

**Issue by patricktokeeffe** [k9mail/k-9#611]
I'd love to have `Mark read` available as a toolbar button. It would be a good addition to Settings > Global settings > Display > Visible message actions. I think it should go between navigation and delete.

Similarly, I'd like to suppress the navigation buttons. It'd be nice if they were also exposed via the 'Visible message actions' list as a checkbox I could deactivate.

**Comment by cketti** [comment]
I'm not yet sure where we'll go with this feature. We might make the menu fully configurable or get rid of this feature altogether because configurable swipe-to-action is enough.

**Comment by woj-tek** [comment]
I know this is quite old (and I've read related task and I know about material-ui work) but just wanted to +1 this (for the time being) - having 'mark as read/unread' there would be very handy

**Comment by cketti** [comment]
I created a new issue proposing a more generic solution to this problem: #5300
