### ISSUE TITLE
hyphens for passwods do not work

### ISSUE THREAD

**Issue by zlice** [k9mail/k-9#6110]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

lineageOS 19.1

### Device model

zenfone 8

### Steps to reproduce

Got an "app password" with hyphens in it. On OX Mail it works fine, in K9 it continually says "auth failed".

### Expected behavior

Log in

### Actual behavior

**Setup could not finish**

`Username or password incorrect. (Command: *senstitive*; response: #2# [NO, AUTHENTICATIONFILED], Authentication failed.])`

**Comment by cketti** [comment]
It's possible that your soft keyboard is using a character other than "hyphen-minus" when you enter the password. Try to copy & paste the proper Unicode character, e.g. from here: https://www.compart.com/en/unicode/U+002D

**Comment by zlice** [comment]
Just tried binaryhexconverter.com and it returns 0x2d

**Comment by cketti** [comment]
Please enable debug logging and also *Settings → General settings → Debugging → Log sensitive information`. Then try to connect to the server. Afterwards export a debug log (see https://github.com/k9mail/k-9/wiki/LoggingErrors). Before attaching the log here, please revoke the app password so nobody reading the log can access your account.

If you have another email client that can successfully connect to the server and supports logging the communication protocol, it would be helpful if you could also attach that protocol log.

**Comment by zlice** [comment]
[k9adb.log](https://github.com/k9mail/k-9/files/8884197/k9adb.log)

**Comment by zlice** [comment]
[k9adb.log](https://github.com/k9mail/k-9/files/8884202/k9adb.log)

**Comment by cketti** [comment]
I wanted to check if K-9 Mail is properly encoding the password. That only works if you don't manually redact the log.

But I just noticed that K-9 Mail doesn't log the `AUTHENTICATE PLAIN` argument anyway. So that won't work :disappointed:

**Comment by zlice** [comment]
The app pass is `xx-xx-xx-xx` basically. Could try to change an email pw to that w/ w/e chars (granted...special characters are hard, ive had banks lock me out because they changed specials that were in my pw)

**Comment by cketti** [comment]
The encoding for SASL PLAIN isn't complicated and chances are K-9 Mail's implementation isn't the problem. My email password contains a hyphen, and it works just fine.

So far I haven't seen any evidence that supports your conclusion that hyphens are the problem. You might want to take a step back and consider other explanations.

**Comment by zlice** [comment]
hyphen works with another client but not k9

app pass for another server (no hyphens) works fine in k9

not sure what's going on then

**Comment by cketti** [comment]
It could be any other part of the password that is causing the problem. The hyphens might be entirely unrelated.

**Comment by zlice** [comment]
The other parts just alpha-numeric

**Comment by zlice** [comment]
Verified `test-test-test-test` works fine manually. Sorry for the noise, I'll go back to the provider
