### ISSUE TITLE
Add android wear support

### ISSUE THREAD

**Issue by vinilox** [k9mail/k-9#619]
Gmail has the possibility to answer with predefined answers or voice. Something similar would be awesome.

**Comment by MarcusWolschon** [comment]
At least offer the following:
single new mail:  mark as reat, archive, spam, delete
multiple new mails: list individual mails, mark all as reat, archive all

I'm willing to work on this feature but I'm in the middle of moving and changing jobs.

**Comment by ashh87** [comment]
Pebble too! Although there is something on Play store for this already, I don't know how good it is and I don't think it's open source.

**Comment by MarcusWolschon** [comment]
Using branch 
https://github.com/k9mail/k-9/tree/issue-619_AndroidWearSupport
to develop this issue until it is ready for a pull request.

**Comment by Protonus** [comment]
I would love to see this, as it would allow me to mark as read / delete / mark as spam from my Pebble watch!   Is this available in an alpha or beta build of K9?

**Comment by MarcusWolschon** [comment]
https://github.com/k9mail/k-9/pull/665 hasn't been merged yet.

**Comment by Protonus** [comment]
@MarcusWolschon - can it be merged into an Alpha build so I can start using it?  I see there are both Alpha and Beta channels.  I would love to start using this!

**Comment by cketti** [comment]
@Protonus If you don't want to build it yourself you have to wait until it is ready and released. Spamming all available channels isn't going to help.

**Comment by allo-** [comment]
pebble already works, if you install the alternative notification center. This allows for the buttons in the android notifications as well as closing notifications on the phone with the watch.

**Comment by MarcusWolschon** [comment]
But you get no stacked notifications to act on the individual messages without the merge of the #665 branch,
I'm just waiting for anyone to give the thumbs up to merge the pull request.

**Comment by Protonus** [comment]
@allo- I appreciate the suggestion,but it won't solve this.  Notification Center is very complicated, interferes with other Pebble watch apps due to it's heavy reliance on Pebble's app message protocol, and is generally rather buggy due to what it's trying to accomplish.  I much prefer stock notification support - which already gives me dismiss and other buttons, etc.  What I want is actual Android Wear support for k-9 which will allow further actions on the watch, as this thread and #665 discuss. 

@MarcusWolschon do you have a build / APK available of your branch, which supports either this or #665?

**Comment by MarcusWolschon** [comment]
I have an APK as I'm beta-testing the functionality for a few month now but it's signed by me.
So you would have to deinstall K-9, loose updates via Google Play and set up everything again.
It's just for development.

**Comment by MarcusWolschon** [comment]
I'm back.
Aparently nobody has done anything in the last 1.5 month despite Wear-support being a popular requested feature.
What about simply merging this while we still can?
At some point it will just become one hell of a merge-conflict and nobody will want to do that at all anymore.

**Comment by Protonus** [comment]
@MarcusWolschon Per your last message, can you link me to your APK or send me a copy? I'd rather use yours than wait any longer as it seems like this isn't going to get merged into even Alpha any time soon.   I can backup my original config in Titanium and restore it once I see that this branch has been merged.

K-9 is one of my only apps I get notifications from on my watch, that doesn't support Android Wear yet, and it's one of the apps I'd use it most with.

**Comment by MarcusWolschon** [comment]
A cleaned up version has just been merged.

**Comment by baudtack** [comment]
This patch doesn't provide a delete option. I get an email, and the notification on my pebble allows me to dismiss it, reply, mark read, archive, or mark as spam but not just delete a message.

**Comment by cketti** [comment]
Delete should show up when you disable 'Global settings > Interaction > Confirm actions > Delete (from notification)'

**Comment by baudtack** [comment]
Ah. Thanks.

**Comment by ifuchs** [comment]
I have not beenable to get Delete to show up for K9 mail on Pebble. I tried changing Global settings per @cketti with no luck. Is there another trick to get this working?

**Comment by gappleto97** [comment]
I'm also unable to get any actions besides "Dismiss" and "Open on Phone" to show up.

**Comment by baudtack** [comment]
Have you installed the Android Wear app? You don't need to run it just install it.

**Comment by gappleto97** [comment]
I did. I also have developer mode and accessibility access turned on for Pebble Time, to see if that made a difference.

**Comment by gappleto97** [comment]
Any idea what may be causing this? I'm happy to help any way I can.

**Comment by cketti** [comment]
@gappleto97 Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests. Once you're confident it is indeed a bug in K-9 Mail please create a new issue using the issue template.

PS: The new Android Wear code is not in any official builds yet. You have to create your own build from master (which is currently not very stable).

**Comment by MarcusWolschon** [comment]
it's not in the 5008 release (at least the entire notification package is not in the 5008-rc1 branch).
