### ISSUE TITLE
k-9 changes MIME type of S/MIME signed mails

### ISSUE THREAD

**Issue by don-philipe** [k9mail/k-9#621]
Hi  there,

k-9 seems to changes the MIME type of S/MIME signed mails in `com.fsck.k9.mailstore.LocalFolder.java` from:
`multipart/signed` -> whole mail
`text/plain` -> text part
`application/pkcs7-signature` -> signature part

into this:
`multipart/mixed` -> whole mail
`multipart/alternative` -> text part
`application/pkcs7-signature` -> signature part

I don't think this behaviour is intended.

**Comment by cketti** [comment]
What K-9 Mail version are you using? This shouldn't be an issue with the current version in 'master'.

**Comment by don-philipe** [comment]
Well, I had an old version and never merged in updates from 'master', my fault.
I can confirm that this issue no longer exists in current version in 'master'. Thanks for the hint.
