### ISSUE TITLE
Ability to quickly delete messages from the message list

### ISSUE THREAD

**Issue by jancborchardt** [k9mail/k-9#623]
As a quick gesture it would be good to have the ability to swipe to delete in the list.

Maybe related to the Material design rework: https://github.com/k9mail/k-9/issues/599

**Comment by cketti** [comment]
See #1426

**Comment by djringjr** [comment]
This is not working in Beta  K-9.  Needs an "undo" feature to compensate for errors. Now I'm using Gmail app for reading mail, k-9 just for answering mail all because of the difficulty in deleting many messages.
