### ISSUE TITLE
no settings menu on my version

### ISSUE THREAD

**Issue by mmkennedy** [k9mail/k-9#625]
My k9 views as a black background with neon colored text. It is very hard to read. Your help pages suggest that I can change my settings to show white background and different fonts but my version of k9 does not have any settings me u orvtab b that I can find .

**Comment by mmkennedy** [comment]
Sorry about the typing above. Tried to say no settings menu or tab. I am on a Samsung galaxy tablet. Can't find a version for k9.

**Comment by cketti** [comment]
Neon text doesn't sound like it's K-9 Mail. Maybe you've installed one of the many forks.

In any case, for support requests please use the [mailing list](http://groups.google.com/group/k-9-mail), not this bug tracker.
