### ISSUE TITLE
Support for ProtonMail

### ISSUE THREAD

**Issue by SecUpwN** [k9mail/k-9#626]
[![ProtonMail](https://protonmail.ch/img/logo-beta-dark.svg)](https://protonmail.ch/)

Good evening @k9mail developers!

While I am still waiting for [Dark Mail](https://www.kickstarter.com/projects/ladar/lavabits-dark-mail-initiative) ([website](https://www.darkmail.info/)) to come out, I have switched to [ProtonMail](https://protonmail.ch) for now, which offers a **double encryption** using RSA-2048 and AES-256 as described in their [security features](https://protonmail.ch/pages/security-details). Even though they're developing their service with heart-blood and have a GitHub account @ProtonMail, their source code is not available (yet). Nevertheless, I would love to be able to use ProtonMail through the k-9 interface on my mobile device. Means, k-9 would need to support that double encryption. Can you add this feature, please?

**Comment by cketti** [comment]
We certainly won't add direct support for some proprietary email encryption.

However, I am open to accepting patches that extend the existing crypto provider interface to work with arbitrary crypto schemes.

**Comment by JohnnyCalavera** [comment]
So how about https://tutanota.com/ ? 
It's Open Source and so is the official android app. It should be easy to implement the app and they are using well-known encryption standards.

**Comment by philipwhiuk** [comment]
Please open a new issue for separate issues.
