### ISSUE TITLE
IMAP errors with Hotmail accounts

### ISSUE THREAD

**Issue by Liknus** [k9mail/k-9#628]
Hi! I hope this is the right place to report a sort of bug. I'm trying to add a new account to K-9 using the IMAP method. Everything goes well with other services (GMail i.e.), but not with hotmail..
The same problem seems to affect others too: http://forum.xda-developers.com/htc-one/help/k9-mail-hotmail-to-pop3-imap-t2975420?nocache=1

Thanks
L.
;)

P.s. Nexus 4 - ROM: XenonHD 5.1.1_r1 - Unleashed 101u Kernel
K-9 Mail v._5.004
No GApps installed

**Comment by ocdtrekkie** [comment]
Just a quick check question: Have you checked the Microsoft Account Security panel? I've noticed a high tendency for Microsoft to block first-time connections for IMAP clients as potential security issues, usually the error that'll fail out is invalid credentials, but if you log into Microsoft's panel, it wants you to confirm whether or not it was you, and then it'll work.

**Comment by Liknus** [comment]
Oh gosh.. You're right! :S This means that I've opend a non-bug thread. I am so sorry about this! What should I do to close it?

**Comment by ocdtrekkie** [comment]
Glad I could help. Both Microsoft and Google have an irritating habit recently of returning "invalid login" type responses for their various additional account security measures.
