### ISSUE TITLE
Intuitive sorting of default folders

### ISSUE THREAD

**Issue by Ede123** [k9mail/k-9#629]
Right now it's hard to actually get important folders like "Inbox", "Outbox" or "Drafts" and the like to the top of the folder list (let alone having a sort order in this group of default folders or having them visually separated from other folders).

I propose to collect all default folders at the top (or optionally a user selectable subset) and give them nice and shiny icons. The rest of the folders should go below with some sort of visual separator.

Actually Android 5.0.2's default "Email" app does a considerably good job at this: When selecting "Show all folders" from the main menu the shown listing is very clear with the default folders being easily identifiable/distinguishable and quickly accessible.

**Comment by philipwhiuk** [comment]
This exists doesn't it - 1st Class Folders?

**Comment by cketti** [comment]
Implemented in `master`. K-9 Mail 5.800 will contain this change.
