### ISSUE TITLE
word document is received as winmail.dat

### ISSUE THREAD

**Issue by Cindy62707** [k9mail/k-9#634]
I am using a Samsung Galaxy S3 on the Verizon network. When a word document is sent to me it downloads as a winmail.dat file on the S3 (it downloads just fine on my desktop as a word document so I know there is nothing wrong with the file). Why is K9 not downloading it as a word document? I think in previous years it downloaded .doc files just fine)

**Comment by cketti** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/k-9-mail) for support requests.
