### ISSUE TITLE
search is space sensitive 

### ISSUE THREAD

**Issue by sfischme** [k9mail/k-9#636]
The search  in k-9 is sensitive to spaces. "foo " will not find emails where "foo" is a the end of the line with a line break afterwards. Given that Android's autocomplete puts a space immediately after the word when you select something, it would be nice to have a trim() -like call on the search field before executing the search.

**Comment by cketti** [comment]
This is already fixed in `master`.

See https://github.com/k9mail/k-9/commit/9c7776d289ea9c54b5c789eef0c06fd28a1240d9
