### ISSUE TITLE
Can't decrypt sent messages

### ISSUE THREAD

**Issue by philippelatulippe** [k9mail/k-9#637]
My friend is no longer able to decrypt newly sent messages using K-9 mail 5.005 with OpenKeyChain 3.2 on Android 4.4.3. I took a look at some messages from my friend and they were only encrypted with the public key of the recipient, and not the key of the sender.

I'm not sure if this is a bug that should be filed on OpenKeyChain's side, I'm not sure how to troubleshoot this.

**Comment by dschuermann** [comment]
Thanks for your report. It's a bug in OpenKeychain 3.2. We will fix this ASAP and release a new version soon.
See https://github.com/open-keychain/open-keychain/issues/1268

**Comment by philippelatulippe** [comment]
I confirm that this is fixed in the latest release of OpenKeyChain.
