### ISSUE TITLE
Add support for GCM cipher suites

### ISSUE THREAD

**Issue by bk2204** [k9mail/k-9#641]
The current list of cipher suites leaves out the GCM cipher suites, which are more secure than the CBC cipher suites, as they avoid the inherent issues with verifying padding.  In fact, HTTP/2 explicitly forbids non-AEAD cipher suites.  k-9 is the largest user of non-GCM cipher suites on my network, so it would be nice if they could be added to the list.

**Comment by cketti** [comment]
Looks like you have done most of the work already. Would you please create a pull request for the necessary change?

**Comment by bk2204** [comment]
It will be later this week, but yes, I can do that.
