### ISSUE TITLE
K9 almost stuck on 5.1

### ISSUE THREAD

**Issue by yakky** [k9mail/k-9#643]
On both my Cyanogen devices (Nexus 7 2013 and Motorola G2 2015) K9 5.10x versions are almost stuck when it come to display or to scroll the list of messages.
Typical symptoms includes 'progress swirl' freezes for tenths of seconds before the list of messages is visible, scrolling the list bynswiping can take similar time to actually *start* scrolling
I've been able to go back untile 5.104 with the same behavior. Stable branch still not tested but will do soon
Any ideas how to debug the issue?

**Comment by dewi-ny-je** [comment]
Is this the same as #747 ?
