### ISSUE TITLE
(5.105) Reply to/from not populated correctly.

### ISSUE THREAD

**Issue by ocdtrekkie** [k9mail/k-9#646]
I'm not sure if this issue is fixed somewhere, or known about. But I'm using 5.105 with settings exported from the Play Store version and then imported. Android version is 4.4.

When I reply or reply all, the reply to address isn't entered, and the from address is always the first listed email address in my K-9 mail, not the one attached to the inbox or conversation in question.

**Comment by cketti** [comment]
I didn't get that. Can you please use a concrete example (with anonymized email addresses)? What exactly are you seeing and what do you expect to see? Do you have multiple email identities? Are they set up in K-9 Mail?

**Comment by ocdtrekkie** [comment]
Yeah, I have three separate email accounts in K-9.

If they're account1@email.com, account2@email.com, and account3@email.com

I get an email from random@dude.com to my account3@email.com address. I open it, hit Reply, and the To field is blank, and the identity set to send from is account1@email.com

**Comment by ocdtrekkie** [comment]
As a note, something in the 5.106 code seems to have corrected this issue. Closing.
