### ISSUE TITLE
very good mail client

### ISSUE THREAD

**Issue by yordanocs** [k9mail/k-9#647]
It is very nice email client but would like that when descarque mails deleted from the server at the same time like other applications for PC thank

**Comment by cketti** [comment]
This is not a proper bug report or feature request.

If you're asking for a way to delete a message from the server when it's deleted in K-9 Mail, that's already supported. Please check out the [manual](https://github.com/k9mail/k-9/wiki/Manual) or ask on the [mailing list](https://groups.google.com/forum/#!forum/k-9-mail) if you need help.

**Comment by yordanocs** [comment]
but if I seek to delete emails from the server to download not there you have to delete Manuela q on the client to be deleted on the server thanks
