### ISSUE TITLE
Enhancement Request: Make it possible to delete a mail from the notification bar

### ISSUE THREAD

**Issue by Bagorolin** [k9mail/k-9#651]
Currently it is possible to answer a mail or to mark it read in the notification bar. I would like to have it possible to delete it immediately, too

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/Manual-GlobalSettings#show-delete-button

**Comment by Bagorolin** [comment]
mkmm ok sorry, I didn't see this setting...
