### ISSUE TITLE
Use Sync Adapter for mail synchronization

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#656]
By using Sync Adapter the OS takes care of many things for us. Some benefits are
- Automated network checking
- Improved battery performance
- Account management and authentication

See https://developer.android.com/training/sync-adapters/index.html

**Comment by aetherfaerber** [comment]
This would also make k9 far more usable on devices that are mostly operating offline and only go online in regular intervals for synchronization. right now, mails written during offline time wont be sent automatically during sync times.

**Comment by dolohow** [comment]
:+1:

**Comment by cketti** [comment]
Sync adapters seem to have been mostly abandoned by Google.
