### ISSUE TITLE
Notification with multiple messages should go to unified inbox

### ISSUE THREAD

**Issue by utack** [k9mail/k-9#664]
When K9 shows a notification with multiple new messages from one account, tapping the notification jumps to this account with all subfolders listed.
This is not especially useful, because the place to read all these new messages without navigating back and forth multiple times would be the unified inbox.
Hopefully this behaviour can be changed, so tapping the notification goes to the unified inbox.
If you don't like the proposal, you could implement the suggested behaviour only when the option "start in unified inbox" is chosen or add a new option to activate it.

**Comment by cketti** [comment]
You can have notifications for messages in folders which won't show up in the Unified Inbox. We'll probably just display a virtual notifications folder containing all unread messages you got a notification for.

**Comment by cketti** [comment]
This has been implemented in #5821.
