### ISSUE TITLE
Optional COMPOSE text

### ISSUE THREAD

**Issue by ghtesting2020** [k9mail/k-9#6659]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.506

### Problem you are trying to solve

Consider removing or adding an setting to make the "COMPOSE" text beside the pencil in the bottom right optional. Using the dark theme it draws my attention with a big white button. The pencil icon alone would be enough.

### Suggested solution

Consider removing or making the COMPOSE text optional. Personally i wouldn't even want the pencil icon but the pencil icon only as opposed to the pencil and COMPOSE would be a good compromise

**Comment by cketti** [comment]
See *Settings → General settings → Display → Show floating compose button*
