### ISSUE TITLE
[bug] Problems with cyrillic symbols

### ISSUE THREAD

**Issue by omgiafs** [k9mail/k-9#668]
Hi!
There is a bug with cyrillic symbols displaying. 
I'm afraid to make a mistake in the exact wording of the error, so here is an example.
I get a letter in the title or body which has the word "**Роутер**". Translated, it means "**Router**". But this word is displayed as "**Ð Ð¾ÑƒÑ‚ÐµÑ€**".

To reproduce this error and find way to fix it, you can use the service [Universal Cyrillic decoder](http://2cyr.com/decode/?lang=en). 

This service suggests that bug is: **utf-8** encoding displayed as **windows-1252**

**Comment by cketti** [comment]
This is most likely not a bug in K-9 Mail. The sender probably specified the wrong charset.
