### ISSUE TITLE
K9 reliance on Google's Webview

### ISSUE THREAD

**Issue by optimumpr** [k9mail/k-9#670]
If webview is completely removed from device (I am talking about removing libwebviewchromium.so), k9 mail crashes when one is trying to open a message. Is this fundamentally in design or this is an issue that needs to be addressed. Many, including myself, think that google webview is a non essential layer that represents a glaring security hole for the entire OS with very limited benefits for a user. 

Is there a way to break that reliance? I guess this could be done via a general intent calling an avalable web browser, such as firefox or fennec.

**Comment by obra** [comment]
do you have an alternate webview installed? Does it have a compatible api?

WebView is very much part of the standard android api. Having to code around random features being removed is....not the most sustainable thing.

**Comment by optimumpr** [comment]
Well, I use fennec web browser that has its own rendering. So does Firefox and Opera. K9 mail is the only app on my phone that crashes without webview. I am not proposing to do away with k9's reliance on webview, but just to have a few lines of codes: if there is no webview, use web browser...

**Comment by Nergal-di-Cuthah** [comment]
The two examples you gave (firefox and opera) are web browsers so it makes sense that they'd have there own webview package, can you cite some non-web-browsers (especially mail clients which need it for html mail)

**Comment by optimumpr** [comment]
There probably isn't another mail client with its own web rendering. It is all a matter of trust. I trust k9 mail, i trust many linux distributions, so, i trust their own rendering engines, but there is no trust in google, there is no trust in their webview, especially that their source contains numerous shady ip addresses such as 1.1.1.1., 2.2.2.2, 6.6.6.6 and 7.7.7.7.  6.6.6.6 is especially interesting... Not to mention that another layer exposed to the internet (in addition to web browser) is hardly improving security. 

But, I am not asking k9 team to do their own webview, I am asking to have an alternative use of web browser.

**Comment by cketti** [comment]
That's interesting, but not a use-case we will support. Feel free to create your own version of K-9 Mail for that.

**Comment by dumblob** [comment]
Well, Bromite shows (visually) the same behavior - login works, but when it automatically switches to the K-9 intent, it stays with "Authenticating...".

I forgot to mention that this is issue is part of the "Set up a new account" process in K-9.

Now I am going to try it with Samsung Browser.

**Comment by cketti** [comment]
@dumblob: This issue has been closed in 2015. If you encounter a bug, please create a new issue and provide the information asked for in the issue template. We don't need a live play by play (comments trigger email notifications). Do your investigation, then create an issue with all the information you have learned.
