### ISSUE TITLE
K9 email setup exchange

### ISSUE THREAD

**Issue by trinityalps** [k9mail/k-9#675]
Hello, I am trying to fix the code so that you can use exchange that uses EWS not WEBDAV. Can anyone give me any pointers as to what I will have to change and how onWebDav() works? I have a partial solution but so far I am just crashing the app rather then doing anything useful. Thank you for your help.

**Comment by cketti** [comment]
Please use the developer mailing list for question like this: https://groups.google.com/forum/#!forum/k-9-dev

I wouldn't expect many answers though. The WebDAV code hasn't been maintained for ages and nobody seems to care. I'll probably remove it after the next major release.
