### ISSUE TITLE
Email Notifications on Android Watch

### ISSUE THREAD

**Issue by joelsherrill** [k9mail/k-9#683]
I love K-9 mail and love my new LG Urbane. I correctly get notifications for new email on the watch but when I select to delete it, the confirm delete notification pops up on the phone. So it is not possible to complete the entire delete email operation from the watch.

This works correctly with the Gmail application but it doesn't have a confirm delete prompt. 

I suppose one option would be to disable the confirm delete dialog entirely or to disable it for just the phone.

Working out the most desirable behavior for using a watch to dispatch the email is the first step. I have only had this watch a few weeks and am still getting used to it. K-9 I have used for a couple of years and am very happy with. AndroidWear is just a brave new world to figure out the Right Thing To Do (tm). :)

**Comment by cketti** [comment]
See PR #665

**Comment by cketti** [comment]
Support for Android Wear notifications has been added.
