### ISSUE TITLE
More options for account colors? A HEX or RGB field? 

### ISSUE THREAD

**Issue by danbruegge** [k9mail/k-9#687]
Hi,

i can chose the color of my account. Its a nice feature and i like it.

With my nexus 4 i was fine with the simple option to only chose the color on the color wheel. Since i had a new phone (Moto X 2014) the colors are to bright and i have no option to change this.

Now my offer is to add a field to set HEX or RGB colors.

Dan.

**Comment by cketti** [comment]
I think the default color picker should be as simple as possible. I don't mind having more advanced options, but we need a good concept for the user interface so we don't end up with a screen that has tons of different ways to do the same thing. One tab per color picking method might work.

@jancborchardt Any thoughts on this topic?

**Comment by jancborchardt** [comment]
I do agree that the colors chosen by K-9 mail seem a bit bright / very saturated / aggressive when you compare it to how the normal Mail app does avatar placeholder colors. Or similar for TextSecure or the Contacts app.

Is there any core function we can utilize? I suppose they use the HSL color scheme (Hue, Saturation, Lightness) and keep Saturation and Lightness at one specific value while only changing the Hue. That’s also what we do in ownCloud for the placeholder generation.

(And no, I would _not_ say we should add a field to set HEX or RGB colors – rather fix the issue for everyone, also people who do not know wtf hex & rgb is. ;)

**Comment by cketti** [comment]
@jancborchardt I believe this issue is about the account color rather than the color of the placeholder images.

This is what the color picker currently looks like:
![k9mail_color_picker](https://cloud.githubusercontent.com/assets/218061/8234808/9acf6758-15de-11e5-8a50-a5a1246cd61e.png)

**Comment by jancborchardt** [comment]
@cketti I know. I think the color range of both should be the same though. (Sorry I veered off the discussion point a bit.)

**Comment by dschuermann** [comment]
@cketti You could enable the SaturationBar and ValueBar. See https://github.com/LarsWerkman/HoloColorPicker

**Comment by danbruegge** [comment]
The HoloColorPicker looks the way i thought about how to choose a color in k9-mail. :+1:

**Comment by PanderMusubi** [comment]
There are practical color pickers in https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib&hl=en and https://play.google.com/store/apps/details?id=org.dmfs.carddav.Sync and see also https://code.google.com/p/k9mail/issues/detail?id=4102

Personally. I find it important to be able to easily select the same color at a later moment and not approximately with a wheel of sliders.

**Comment by marcopenhacking** [comment]
I just wanted to add a grey account color. That's impossible with the current solution.  Enabling of the SaturationBar and ValueBar like described by @dschuermann [https://github.com/LarsWerkman/HoloColorPicker](url) might be the least effort to improve the situation.

**Comment by lem503** [comment]
Any chance of this being implemented? Would love to see an input field for HEX or RGB colors. I've got the same color palette that I use across different devices and clients so this would really help!

**Comment by mgmax** [comment]
Currently it isn't even possible to choose the [default color](https://github.com/k9mail/k-9/blob/b3c0021edbc8a0d9b73beb2f45eee3fbc21ced33/app/ui/src/main/java/com/fsck/k9/account/AccountCreator.java#L29-L35) that is used when creating a new account.

A quick-and-dirty workaround would be to keep the existing colorpicker, but rescale the color after the user has selected it.
Rescaling to a more gray-ish color would be possibly by multiplying R,G,B with 3/4 or similar.
Here's the relevant code where the color is returned:
https://github.com/k9mail/k-9/blob/bf33cfd73a81e37df2f48f35ee4c2f1ec3fe2427/plugins/HoloColorPicker/src/com/larswerkman/colorpicker/ColorPicker.java#L99-L102

Maybe someone wants to give it a try?


Of course, a better solution would be updating to the newer version of HoloColorPicker -- K9mail currently uses an old and modified version.

**Comment by newhinton** [comment]
@cketti I think the updated holo-colorpicker just serves this issue right. I have created a PR which updates this picker to the latest version, this keeps the solution for this feature quiet simple.

**Comment by cketti** [comment]
Closing in favor of #3904.
