### ISSUE TITLE
Read status propagation to notifications (v5.006)

### ISSUE THREAD

**Issue by johnrezzo** [k9mail/k-9#696]
The following bug appears fixed in latest development version (v5.107). Since I could not find anything clearly related to this on changelogs, I report this just for confirmation.

I'm on a Samsung S4 (I9505) running stock Android v5.0.1. Using K-9 v5.006, a read status change (and even deletion) applied on a different device is not entirely propagated to mobile: the "new mail" notification would not automatically disappear, even after manual pull/refresh. This problem is not limited to lock screen, but to status-bar and notifications-menu too, where the notification would reside in indefinitely. Opening this dead notification, in case of email deletion, leads to an empty message dated to Unix epoch time (1970).

I tried the latest development version (5.107) and can confirm this problem is fixed.
Thanks for the great work.

**Comment by cketti** [comment]
This may still be an issue in current development versions. However, I'm in the process of rewriting the notification code, anyway.
