### ISSUE TITLE
proxy support?

### ISSUE THREAD

**Issue by ominousclouds** [k9mail/k-9#698]
I saw an old feature request on the Google Code site where someone from the Guardian Project indicated plans to add Orbot/proxy support to K-9 mail. Has there been any movement on this? If not, how challenging would this be to implement? My coding experience is not extensive, but I'm ready to spend the time necessary to figure out how to do this if no one else is working on it and if it's not a horribly advanced project.

**Comment by cketti** [comment]
Please only use this issue tracker for bug reports or feature requests. If your title ends in a question mark it's neither.

I created issue #704 for this.
