### ISSUE TITLE
load complete mail

### ISSUE THREAD

**Issue by smoneck** [k9mail/k-9#702]
Just the first x lines/words/characters of a mail are being loaded. Long mails are being cut off regardless of HTML or plaintext.
Is there an option for this? How can I get rid of this?

Thanks a lot!

**Comment by cketti** [comment]
Please do not use this issue tracker for support requests. Use one of the methods listed under [Need help](https://github.com/k9mail/k-9#need-help).

The setting [Fetch messages up to](https://github.com/k9mail/k-9/wiki/Manual-AccountSettings#fetch-messages-up-to) is probably what you're looking for.

**Comment by smoneck** [comment]
Other issues are labeled with “help wanted”. Since I don't know what raises this behavior, I assumed this place to be appropriate. Nevertheless thanks for your answer but it's not 'Fetch messages up to'.

**Comment by smoneck** [comment]
In case, it *is* a bug, [here](http://m.imgur.com/18H4pjs) is a screenshot. Whitespace aquivalent to cutoff.

**Comment by cketti** [comment]
This might be the bug that was fixed with 5.005/5.106.

If you are using a K-9 Mail version newer than that, you should write to the mailing list. Maybe someone else has seen the same behavior and can help you out.

**Comment by smoneck** [comment]
I'm using 5.006
