### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#704]
Add support for using a proxy server when connecting to any server. This includes
- [ ] incoming and outgoing mail servers
- [ ] content downloaded by the `WebView`
- [ ] `DownloadImageTask`
- [ ] DNS lookups
- any other connection (please list in comments)

See also: https://code.google.com/p/k9mail/issues/detail?id=2834

**Comment by philipwhiuk** [comment]
See SOCKS proxy support #980 for the first bit.

**Comment by Kushredoc** [comment]
Can I work on this issue  ? 
Any help for a head start ?

**Comment by GoneUp** [comment]
Example of a webview proxy: https://github.com/jeffgdotorg/Tinfoil-Facebook/blob/master/app/src/main/java/com/danvelazco/fbwrapper/util/WebViewProxyUtil.java
Looks pretty ugly.

**Comment by philipwhiuk** [comment]
We should maybe reach out to @velazcod and see if we can libraryify the code for easier re-use between projects.

**Comment by velazcod** [comment]
I agree that isn't pretty.

Feel free to copy and reuse some of that in a lib project, it's Apache 2.0.

**Comment by mirsamantajbakhsh** [comment]
Check my commit.

SOCKS proxy support added
#3889

**Comment by mirsamantajbakhsh** [comment]
https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/

**Comment by cketti** [comment]
Duplicate of #980
