### ISSUE TITLE
Use voice dictation to compose emails

### ISSUE THREAD

**Issue by knoy** [k9mail/k-9#705]
It would be very helpful in certain cases if you could compose emails using your voice (i.e: while driving, typing on a keyboard or using a pencil)

**Comment by nuntius35** [comment]
Maybe [Kõnele](https://github.com/Kaljurand/K6nele) can be useful?

**Comment by philipwhiuk** [comment]
This can be done by installing an appropriate keyboard (e.g. enabling Google voice). There's no need for K-9 changes.
