### ISSUE TITLE
Support for SCRAM-SHA-1 authentication

### ISSUE THREAD

**Issue by knoy** [k9mail/k-9#707]
The most secure authentication supported by K9 is currently CRAM-MD5, which has been cryptographically broken since 1996. 

Although it does have some worrying collision attacks, SCRAM-SHA1 would be a much better replacement, and is widely supported by many popular POP3 and SMTP daemons.

**Comment by philipwhiuk** [comment]
Oh damn. I duplicated this with more details on what's needed #1231
