### ISSUE TITLE
Mark multiple mails as read at once

### ISSUE THREAD

**Issue by vanitasvitae** [k9mail/k-9#708]
Hi
When I select multiple mails at once and long tap one and select "mark as read" only the mail I long tapped on gets marked as read. Can you chamge it so that I can mark more than one mail at once?

**Comment by cketti** [comment]
When you select multiple messages the actions are available in the action bar. The 'popup on long-press' pattern will be removed in the future because it's a remnant of the Android 1.x/2.x times.

**Comment by vanitasvitae** [comment]
Oh just discovered the icon. In my opinion this icon should be more significant. Thanks :)
