### ISSUE TITLE
Wouldn't it be useful to have 'Unified Sent'?

### ISSUE THREAD

**Issue by Agrachina** [k9mail/k-9#709]
Adding the menu point 'Unified Sent' in the 'Accounts' overview, in between 'Unified Inbox' and 'All messages', would complete the usage scenario. 

While sent messages can be found in 'All messages' and in the respective detail view of the accounts, same applies to received messages. Therefore it would be consequent and balanced to have unified views of Inbox, Sent and All.

I assume it wouldn't be technically challenging to realize but unfortunately I'm lacking the programming experience to create the pull request with respective coding. 

In any case, K-9 Mail is nothing short of amazing, thanks a lot creators and developer community!

**Comment by cketti** [comment]
At some point we will probably add the option to configure virtual folders aggregating messages from arbitrary folders. But I don't see us adding a 'Unified Sent' folder by default.
