### ISSUE TITLE
K9 Automatically Collecting Contacts From Other Applications

### ISSUE THREAD

**Issue by LeeThompson** [k9mail/k-9#713]
K9 is now automatically collecting contacts from Skype and so forth and I don't want it to.  

I'm either missing a setting somewhere or please add one :)

**Comment by ocdtrekkie** [comment]
Was it not before? That's how Android works, AFAIK.

**Comment by cketti** [comment]
K-9 Mail uses Android's contact database. If Skype puts its contacts there they will be offered as options on auto-completion. We won't change this behavior.
