### ISSUE TITLE
FAQ Error

### ISSUE THREAD

**Issue by LeeThompson** [k9mail/k-9#714]
https://github.com/k9mail/k-9/wiki/FrequentlyAskedQuestions has a section "Why K-9 is using so much bandwidth to sync my POP mail?" and talks about making additional folders in a POP3 account.   POP3 does not have folders.   (The local client can have folders but the server does not.  This is one of the reasons why IMAP has become much more widely used.)

**Comment by cketti** [comment]
Maybe the text was copied from somewhere. The advice would make sense if K-9 Mail supported local folders.
Please feel free to correct the answer. It's a wiki after all.

**Comment by ConteDiMonteCristo** [comment]
One more reason for having local folders (see #648). Work under way

**Comment by cketti** [comment]
I removed the paragraph about moving messages to a local folder myself.
