### ISSUE TITLE
What happens when starttls negociation fails?

### ISSUE THREAD

**Issue by Phyks** [k9mail/k-9#726]
Hi,

On [this page of the wiki](https://github.com/k9mail/k-9/wiki/Manual-AccountSetup) there are two settings: STARTTLS (if available) and STARTTLS (always). Although, it seems to be outdated and in the latest K9 version, I only have STARTTLS.

Then, what happens if the negociation of a secure connection fails?

Thanks

**Comment by cketti** [comment]
Please do not use this issue tracker for support requests. For questions use the mailing list or the Google+ community. See https://github.com/k9mail/k-9#need-help
