### ISSUE TITLE
k9 keeps sending failing messages

### ISSUE THREAD

**Issue by smoneck** [k9mail/k-9#729]
Every time I open k9, it tries to send a whatever message again and throws an error.

This seems to accumulate. I have now 3 messages that are trying to be send every time I connect to the WiFi. And of course every time the same errors.

> How do I fix that/delete this cron?

Current version of k9 5.0006 with kitkat 4.4.4

**Comment by cketti** [comment]
This should already be fixed in master. In 5.006 you should be able to delete messages from the "Outbox" folder to stop K-9 Mail from trying to send them.
