### ISSUE TITLE
No Encrypt & Sign buttons

### ISSUE THREAD

**Issue by sakalauskas** [k9mail/k-9#737]
Hello,

I am trying to build from source and when I try to send a message I can't see Sign and Encrypt buttons in message compose window.

Although, with same phone K9 application from Play store works fine and there are those buttons. I wonder what's the problem?

Edit:

I am using APG. Is it no longer supported?

**Comment by clawoflight** [comment]
Not sure about support, as I'm only lurking here.
However, APG itself is no longer under development AFAIK, and the community has moved on to OpenKeychain.
