### ISSUE TITLE
Account option reset to default value after server certificate change

### ISSUE THREAD

**Issue by Stratofish** [k9mail/k-9#738]
I've had this issue a few times in the last few years and was never sure what triggered it.

The option specifically that I've seen change is Account options->Fetching mail->When I delete a message. This gets reset to 'Delete from server'.  I use my desktop computer to store my emails so I can back it up, but only check it there every few weeks. I use my phone to read and reply normally and just delete them locally knowing they will arrive on my PC to be archived eventually. I've lost weeks of emails due to this setting changing unexpectedly before.

I'm using IMAP but I believe it happens via POP3 as well.

**Comment by cketti** [comment]
See #616
