### ISSUE TITLE
Public URL confusion, please update links

### ISSUE THREAD

**Issue by giox069** [k9mail/k-9#743]
Is this the same project as this https://code.google.com/p/k9mail/ ? I cannot find any link pointing from the google code one to here.

If yes, could you please

1. Put a message on that page (https://code.google.com/p/k9mail/) so users will not waste time on opening issues there. Google will put it in readonly mode in the next few days, and I think you will never be able to do this after august 25.
2. Update the "Visit website link" in google playstore, visible at the bottom of this page https://play.google.com/store/apps/details?id=com.fsck.k9&hl=en

Thank you.

**Comment by cketti** [comment]
1. https://code.google.com/p/k9mail/ now redirects to our Github site. With Google Code now being read-only the archived content is available here: https://code.google.com/archive/p/k9mail/
2. Done. Should be active in a couple of hours.
