### ISSUE TITLE
Downloads go into root folder instead of standard »Downloads«

### ISSUE THREAD

**Issue by jancborchardt** [k9mail/k-9#745]
It seems K-9 Mail is not using the standard Downloads folder. Instead stuff is downloaded into the root of the internal storage. This results in some issues opening files up from other apps.

**Comment by cketti** [comment]
You can configure where attachments are saved: https://github.com/k9mail/k-9/wiki/Manual-globalsettings#save-attachments-to

**Comment by jancborchardt** [comment]
I know pretty much everything is possible to configure in K9. ;) But this is about having a good default.

**Comment by cketti** [comment]
Unfortunately, just putting files in the Download folder doesn't lead to them showing up in the "Downloads" app. Adding code to do that is a little bit more work.

**Comment by cketti** [comment]
See [DownloadManager.addCompletedDownload()](https://developer.android.com/reference/android/app/DownloadManager.html#addCompletedDownload(java.lang.String, java.lang.String, boolean, java.lang.String, java.lang.String, long, boolean))

**Comment by swapsmagic** [comment]
Here is a pull request for the last comment: https://github.com/k9mail/k-9/pull/987

**Comment by jancborchardt** [comment]
Thanks a lot! :)
