### ISSUE TITLE
message list should not query contact provider in bind method

### ISSUE THREAD

**Issue by Germano0** [k9mail/k-9#747]
Often I am experiencing a really slow and laggish graphic user interface on Android 5.1.1 and K-9 Mail 5.006
I collected some debug infos in the way described in the webpage [1] and I uploaded at URL [2]

[1] https://github.com/k9mail/k-9/wiki/LoggingErrors
[2] https://mega.co.nz/#F!lk4gTKxJ!1ge40kShWt8IwxQVVXEnmA

**Comment by mtlgh** [comment]
Apparently, list scrolling and messages selection seriously lag only when "Show contact names" is set in Settings > Global settings > Display.

**Comment by Germano0** [comment]
Il 20/ago/2015 11:56 AM, "Mihai Lazarescu" <notifications@github.com> ha
scritto:
>
> Apparently, list scrolling and messages selection seriously lag only when
"Show contact names" is set in Settings > Global settings > Display.

Did you find out from my logs or is it a known problem?

**Comment by mtlgh** [comment]
I tried disabling my settings one by one until I got a normal-reacting GUI.

**Comment by Germano0** [comment]
Il 20/ago/2015 08:18 PM, "Mihai Lazarescu" <notifications@github.com> ha
scritto:
>
> I tried disabling my settings one by one until I got a normal-reacting
GUI.
>

Your workaround works correctly. Now I hope that the bug will be fixed soon

**Comment by Goudnet** [comment]
Just posting here to confirm the issue with very slow responsiveness when Show Contact Names is enabled in v.5.006.
I'm on Android 4.4 Galaxy S5

**Comment by Goudnet** [comment]
Sorry, Android 5.0, not 4.4

**Comment by StamSolid** [comment]
For me disabling the "Show Correspondent Names" fixed the lag on the mails list.
Android 4.1.2 , K-9 v5.006

**Comment by ChaosEmpire** [comment]
Thanks for this temporary solution 
I was totally frustrated, moved my app data with titanium Backup from Samsung Galaxy Note edge with 5.1.1 to lg g4 with 5.1
And it was slowly reacting like hell 

Disabling the show names and all works fine, beside the missing names

Hope there will be a fix

**Comment by ChaosEmpire** [comment]
Oh I forgot to write, just Disabling the feature names from contact data is the issue, you don't need to disable the main show name feature

**Comment by woyczek** [comment]
« "Show contact names" is set in Settings > Global settings > Display »
YESS !

This has made my month. More than 2" to scroll or select spams to purge, instantly with this option disabled. Android 5.1.1.

**Comment by Valodim** [comment]
The implementation of this option is rather questionable: It triggers a content provider query for the contact name in the bind method of each view (MessageListFragment.bindView -> MessageHelper.getDisplayName -> toFriendly -> contacts.getNameForAddress), which means hundreds of queries with a while of scrolling.

Options:
- ditch the feature (until implemented correctly?)
- add caching? it's still not nice to query in bindView methods
- reimplement the feature and do it right™ - whatever that is.. I didn't look into the loading code in depth

**Comment by cketti** [comment]
Contact names are now fetched in a background thread. See #4214 and #4442.
