### ISSUE TITLE
Duplicate email in notification

### ISSUE THREAD

**Issue by lublud** [k9mail/k-9#751]
When I receive an email that is sorted in several folders,  the notification I receive tells me I have two (or more, actually as many as folders containing the email) unread messages even though I have just one.

I mostly see that with my redirected addresses as emails go into both inbox and the folder for my redirected addresses.

**Comment by cketti** [comment]
That's expected behavior when there are multiple messages.
If that's because of multiple labels in Gmail see issue #752.
