### ISSUE TITLE
Logout!

### ISSUE THREAD

**Issue by ruhul015** [k9mail/k-9#756]
Hi,
I could not find the logout option in this app.How can i logout from this app. 

Thanks

**Comment by cketti** [comment]
This issue tracker is only for tracking bugs and feature requests. For support issues please check the "Need help?" section of the README: https://github.com/k9mail/k-9#need-help

PS: There is no logout option. To learn how to delete an account check out: https://github.com/k9mail/k-9/wiki/Delete-email-account
