### ISSUE TITLE
can t get the push notifications

### ISSUE THREAD

**Issue by vijayatgit** [k9mail/k-9#758]
Sometime, push notifications are not receiving. Also, many users have commented on this same issue in playstore. Copy pasting those comments.

2	1	push doesn t work the app itself is great a lot of features and i even love the design but push doesn t work uninstalled
2	doesn t push i can t get the push notifications to work on either account disappointing
3	it won t push notifications uninstalled since it won t push notifications

**Comment by cketti** [comment]
This issue tracker is only for tracking bugs and feature requests. For support issues please check the "Need help?" section of the README: https://github.com/k9mail/k-9#need-help

PS: Push notifications work in general. They may not work with your server setup, but that's not a bug in K-9 Mail.
