### ISSUE TITLE
Certificate verification utterly broken

### ISSUE THREAD

**Issue by kbabioch** [k9mail/k-9#767]
K-9 Mail happily accepts not only self-signed certificates without raising any questions, but also **expired** certificates. This should definitely be **NOT** the case, since it renders the whole authentication useless and MitM becomes possible by introducing fake and/or self-signed certificates.

Verifying the validity of certificates is essential to the SSL/TLS system, otherwise it is pretty much useless.

**Comment by cketti** [comment]
Bug report utterly broken!
Please provide the information asked for in the issue template so we have a chance to investigate: https://raw.githubusercontent.com/k9mail/k-9/master/issue_template.md

**Comment by kbabioch** [comment]
### Expected behaviour
K-9 Mail should reject to establish a secure (!) connection to servers that provide invalid certificates.

### Actual behaviour
K-9 Mail happily accepts invalid certificates, e.g. expired ones. This makes it vulnerable to all sorts of active MitM attacks and renders the whole authentication useless.

### Steps to reproduce
1. Setup server with invalid certificate, e.g. expired one
2. Connect to it with K-9 Mail. In my case I've used IMAP
3. See how K-9 mail happily interacts with the server and fetches all mail.

### Environment
K-9 Mail version: 5.006

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Works fine for me.

![k9mail_certificate_expired](https://cloud.githubusercontent.com/assets/218061/9569710/2a2b3544-4f73-11e5-8a0a-add53e24b09e.png)

**Comment by philipwhiuk** [comment]
There's an option to ignore the invalidity of SSL certificates. Do you have this set kbabioch?

**Comment by cketti** [comment]
@philipwhiuk There is not. We removed that option a while ago. If there's a problem with the certificate you should get prompted whether you want to accept the certificate with the dialog shown in my previous comment.

**Comment by cketti** [comment]
Closing this issue since no instructions on how to reproduce the problem were provided.
