### ISSUE TITLE
adding a new email provider to account setup auto configuration

### ISSUE THREAD

**Issue by calimou** [k9mail/k-9#772]
Hi,
It seems my email provider domain name is not known to K9 account auto config.
How do I add my email provider server configuration to happen automatically in K9 ?

Is it based on https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration ?
Is https://github.com/k9mail/k-9/wiki/An-user-friendly-account-set-up-wizard-with-automatic-settings-detection-mechanisms implemented or maintained ?

**Comment by calimou** [comment]
To be very specific, my provider is hosted as mailprovider.**ltd**
But my login name is user@mailprovider.**ext**

It seems K9 accepts automatic configuration for mailprovider.**ltd** but not mailprovider.**ext**.  However this is the same exact server configuration except the login name.

It should only be a matter to associate mailprovider.**ext** to this server configuration.

**Comment by cketti** [comment]
For the configuration to happen automatically the domain part of your email address needs to have an entry in [k9mail/src/main/res/xml/providers.xml](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/res/xml/providers.xml).

Example:
```xml
<provider id="android" label="Android" domain="android.com">
    <incoming uri="imap+ssl+://imap.gmail.com" username="$email" />
    <outgoing uri="smtp+ssl+://smtp.gmail.com" username="$email" />
</provider>
```

PS: Using "mailprovider.ltd" is not being "very specific" :)

**Comment by calimou** [comment]
Hi and thank you for answering,
My use case is specific, not the fact that I am using an email provider :D 
Do I have to do a PR for this ?

**Comment by cketti** [comment]
The pull request was merged.
