### ISSUE TITLE
Add online autoconfiguration from ISP

### ISSUE THREAD

**Issue by narcisgarcia** [k9mail/k-9#777]
Implementing autoconfig mechanism to get IMAP/POP/SMTP parameters would be a great jump forward to new users get their account working in brief steps.

developer.mozilla.org/docs/Mozilla/Thunderbird/Autoconfiguration

**Comment by narcisgarcia** [comment]
Provisional easier option: getting k9s file from an URL like:
http://autoconfig.example.net/mail/k9mail.xml?emailaddress=some@example.net
You can try with this working service:
http://autoconfig.actiu.net/mail/k9mail.xml?emailaddress=example@actiu.net
(support HTTPS too)

**Comment by cketti** [comment]
The world doesn't need yet another method for auto-configuration. So downloading a K-9 Mail settings file from a web server won't happen. The Mozilla method is fine, though.

Additionally, we should add support for [RFC 6186](https://tools.ietf.org/html/rfc6186).

**Comment by narcisgarcia** [comment]
In the meanwhile, we have the nearest working service to an easy autoconfiguration in the current K-9 Mail versions:
http://autoconfig.actiu.net/
(file downloads)

**Comment by thefinn93** [comment]
@narcisgarcia what magic did you use to get the browser to download the file, and as an k9s file no less? I've been playing with it for a while and I don't see any special headers or anything that make it do that, but when I try it it doesn't work. [See here](https://autoconfig.seattlemesh.net/k9/) for non-working one, will post the code in a sec.

**Comment by thefinn93** [comment]
@narcisgarcia sent me the code privately, I've update my gist to what I got working (just had to add a few headers that I'd missed). I also realized that setting the Content-Type to `application/x-k9settings` makes the downloaded file open with K9, making it much more user friendly

**Comment by narcisgarcia** [comment]
I've applied headers for content (Type, Disposition, Transfer-Encoding), and at least user can avoid to look for K-9 Mail: When user opens the downloaded file, the mail client is launched (but it doesn't take the file).
Certainly it's a step forward.

For an easy step from K-9 Mail development, the application could import directly this kind of file when called with this "parameter".

**Comment by thefinn93** [comment]
Yeah, I discovered earlier today that this only works really well for the first account. Additional accounts are not as smooth (currently)

**Comment by cketti** [comment]
Support for auto-configuration will be tracked in #865
