### ISSUE TITLE
k9 auto open url in browser without any questions

### ISSUE THREAD

**Issue by ungifted** [k9mail/k-9#779]
I have got two phishing emails yesterday.
When I tap on it browser start with url from email.
When I open it from another email by tap "<" or ">" bottons, browser start with url from email.
It seems critical issue for me.

**Comment by ungifted** [comment]
I don't know how to add inbox file here. Only images allowed?
Hmm... Save it on my gdrive: https://drive.google.com/open?id=0B3wtHYJkVb1eMVBUbDR0eUQ3WFk

**Comment by cketti** [comment]
Please provide the information about your environment asked for in the issue template: https://raw.githubusercontent.com/k9mail/k-9/master/issue_template.md

**Comment by ungifted** [comment]
### Expected behaviour
When I open message k9 should show email content with attachments.
I may press url to open it in default browser.

### Actual behaviour
I have two phishing messages.
When I select one of that messages k9 open browser with url.
I think problem in this part:
--===============1984238644==
MIME-Version: 1.0
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename="BL - Copy.htm"

   <html>

<meta http-equiv=3D"refresh" content=3D"0;      http://geophimax.com/Gmc/ac=
cess/auto/dh/verify.php">



</html>


--===============1984238644==--


### Steps to reproduce
1. Get raw messge from comment 2
2. Import into k9 (imap server in my case)
3. select it from list

### Environment
K-9 Mail version: current from market: 5.006

Android version: 5.0 (Samsung Note3 SM-N900)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (dovecot)

**Comment by cketti** [comment]
This is already fixed in the development version. See #712
