### ISSUE TITLE
Support for "multi window" (side by side tiles)

### ISSUE THREAD

**Issue by tsmithe** [k9mail/k-9#781]
Just reviving this old issue from Google Code. Seems like the most recent version of k9 doesn't support this yet. Also seems to be suggested that this is quite easy to resolve. 

Old report: https://code.google.com/p/k9mail/issues/detail?id=4814

Manifest change: http://stackoverflow.com/questions/14111052/adding-multi-window-support-to-android-application/14185426#14185426

I would be more than happy to help test. Thanks for your work and consideration!

**Comment by GoneUp** [comment]
I guess this is can be closed since there is now a native android implementation that works fine with k9-mail on Android N.

**Comment by philipwhiuk** [comment]
We still need to update to SDK 24. Right now you get an annoying message "App may not work with split-screen"

Basic testing of the feature seems to work okay.

**Comment by GoneUp** [comment]
Oh, yea. That toast is awful. Are there plans to update the targetsdkversion to 24/25?

**Comment by philipwhiuk** [comment]
Given I have a device running v24 I'll probably try and run with v24 and see if I have any issues. If I don't we'll update it for the next major release I expect.
