### ISSUE TITLE
Icon displayed in portrait mode disapears in landscape mode

### ISSUE THREAD

**Issue by Bourinatus** [k9mail/k-9#788]
Hi, 

While in portrait mode I can see all icons (cf attached picture), some of them (ex : reply shortcut or new email shortcut) dispapear in lanscape mode.

Could you fix this display bug ?

Thanks,

Bourinatus

![screenshot_2015-09-09-12-58-46](https://cloud.githubusercontent.com/assets/14199927/9763759/8ea75148-570b-11e5-8a38-f8db0bcd4d48.png)
![screenshot_2015-09-09-12-58-58](https://cloud.githubusercontent.com/assets/14199927/9763761/8eafa578-570b-11e5-9583-bfb1739980f8.png)

**Comment by cketti** [comment]
This is not a bug, but the way Android works. The actions don't disappear but are moved to the overflow menu.
This is confusing to a lot of users. That's why we'll get rid of the bottom action bar with the next UI update. See e.g. the discussion in #599.
