### ISSUE TITLE
Merge @googlemail.com and @gmail.com

### ISSUE THREAD

**Issue by Uroc327** [k9mail/k-9#790]
It would be awesome if k9 would recognise googlemail as gmail and vice versa when associating email addresses with contacts from the address book.

**Comment by cketti** [comment]
Can you explain in more detail what you're suggesting?

**Comment by Uroc327** [comment]
I've received a mail sent to multiple people. (no list, just multiple receivers) 
The addresses were without names (only `abc@googlemail.com` instead of `Abc <abc@googlemail.com>`) 

AFAIK k9 is able to replace the address with the contact name when viewing a mail. For example in the overview of all mails or when viewing a specific mail at the part. 

Now I'd like k9 to print `Abc` instead of `abc@googlemail.com` in the address list, because I have a contact named `Abc` but with the email address `abc@gmail.com`.

**Comment by philipwhiuk** [comment]
Annoyingly I don't think there's anyway of automating this. I feel like checking the MX records are identical is both heavyweight and insufficient. Google **is** probably 99% of the use case though.
