### ISSUE TITLE
Search on Server

### ISSUE THREAD

**Issue by Doni49** [k9mail/k-9#791]
When I need to use the search function to find a message, it's usually too old to be part of what's cached locally on my phone. 

But when I do search, it appears to only search the local cache.  I have to keep tapping "Load Up To 25 More" until it has gone back far enough.  And then I can search for the message. 

The IMAP Protocol includes a function to search on the server based on any number of criteria.  After K9 has searched the local cache and not found the message, it should show an option to continue the search on the server. 

I'd also like to be able to do advanced searches on the server (subject includes this but excludes that, between two dates etc).

**Comment by maniac103** [comment]
Server side search has its own action in the search results window. Its icon looks like a mountain in a magnifying glass.

**Comment by cketti** [comment]
Server-side search has to be enabled in settings and currently doesn't support search in message bodies.

**Comment by Doni49** [comment]
I'll have look for that. . Thanks. 

But as far as the advanced search part, I'd still like to see that happen.

**Comment by Doni49** [comment]
Wow.  I can't believe it was THAT simple and I've been dealing with having that setting off for so long. 

Thanks for the heads up.

**Comment by markusd112** [comment]
I had exactly the same problem: search wasn't really usable, because the searched messages were normally older and not in local message cache. So my workaround was to set the max number of mails to "all", but with this K9 mail was really unperformant. I didn't realize that it is so easy to activate server based search. Wouldn't it be a good idea, to enable this feature per default? Or to modify the search GUI and add a "search server" checkbox directly there (and not hidden in the settings). I think the normal (non technical) user will not find this option in the settings and didn't know the differences in local and server based search...

**Comment by philipwhiuk** [comment]
> To modify the search GUI and add a "search server" checkbox directly there (and not hidden in the settings)

This is definitely worth doing when we overhaul the UI. Tagged with milestone so we remember to do it.

> I think the normal (non technical) user will not find this option in the settings and doesn't know the difference of local and server based search...

I think this is overstating it a bit - I think a user understands the difference between searching stuff on their device and not on their device.

**Comment by pshem** [comment]
Could the tick be switched to ON by default? I think that would be more intuitive

**Comment by tkedwards** [comment]
It's a real shame this feature isn't enabled by default. I used the app for years and just thought it was a limitation that it couldn't do useful searching (i.e. on the server). The steps for enabling it are far from obvious or intuitive, definitely should be the default instead.

**Comment by majutsushi** [comment]
It would also be great if there were a way to pass a search string unmodified to the server, to make use of the powerful IMAP search syntax. This would also mean that K9 didn't have to implement all of the search capabilities itself.

**Comment by Bubu** [comment]
Argh, I was confused about a slightly different problem just now. I know I have to enable server side search in settings and did so for this account.

But then I also enabled unified inbox and was very confused the server-side search button wasn't showing after no-results locally. Is there a different option to enable this for the unified inbox?

**Comment by psla** [comment]
@cketti it seems that search in bodies is still not supported. Can you comment on why, and what would be involved to making it possible? Is it a design choice, or simply low priority thing? Would you allow contributions in this space?

**Comment by regulator-g** [comment]
I have two different email accounts, different providers, and i have used K9 about 3 years ago with yet another address.. "search on server" enabled but never works!

believe my general config is imap, start ttls etc

**Comment by potuz** [comment]
I wander if anyone could confirm that server search does work with GMAIL. I have used k9 for years and every version does this:

1) Hit search, type a string see some results
2) Hit search on server see some more results
3) Click on the e-mail, the headers are downloaded, but the body never downloads. After a while it timesout with a message "connection error".

**Comment by morckx** [comment]
@potuz : See my comment [here](https://github.com/k9mail/k-9/issues/3254#issuecomment-398661631).

In addition, you also have to wait until the server side search has finished. When I interrupt a search, by clicking on a just received header, I get a "connection failed" toast and I'm not able to receive the message body.

**Comment by potuz** [comment]
Thanks a lot @morckx that did it!

**Comment by alex005005** [comment]
I have the exact same issue with my own dovecot installation. Has anyone figured out a way to fix that?

**Comment by alex005005** [comment]
@Scrxtchy, in the linked issue the solution to my issue was mentioned: Switching the sync period to "unlimited" - had it set to two weeks before that.

**Comment by cketti** [comment]
I don't think we need this issue to keep track of the feature. There's #649 and #699.
For the "connection error" bug when trying to open a message before search on the server has completed, see #4412.

**Comment by dm17** [comment]
I'm using Gmail + K-9. The server search wouldn't work. So I changed the settings to store all messages locally, which I would like anyway in case I need to use mail offline. Since it downloaded all messages (4000 in inbox & 20,000 All Mail), the app does not show anything. It is just blank. If I leave it open for a minute or so, then it usually seems to load. I'm unsure how to search for this issue. Anyone else experience it?
Once all the messages load (perhaps that isn't how it should be working) - the app will then hang when navigating around.

**Comment by utack** [comment]
Same here @dm17 the app is often blank  
I have not found a bug report about it yet

**Comment by dm17** [comment]
> Same here @dm17 the app is often blank I have not found a bug report about it yet

Amazing response time :) May I ask which device / Android you're running it on?

**Comment by utack** [comment]
@dm17 Android 11/Samsung Galaxy S21 Exynos edition  
  
Should we open a new issue for this?
I could not find one for the problem, and I think we should spamming here since it is a separate issue

**Comment by dm17** [comment]
> @dm17 Android 11/Samsung Galaxy S21 Exynos edition
> 
> Should we open a new issue for this? I could not find one for the problem, and I think we should spamming here since it is a separate issue

Yes please. Do so and paste it here... I'll follow that issue once you do.

**Comment by dm17** [comment]
> @dm17 Android 11/Samsung Galaxy S21 Exynos edition
> 
> Should we open a new issue for this? I could not find one for the problem, and I think we should spamming here since it is a separate issue

@utack - I made another thread to track it (above).

**Comment by alex005005** [comment]
Hey guys, it's important to not limit the time period of message retrieved in the settings when searching. Historically this was limiting the search results as well.
