### ISSUE TITLE
K9 &  Tasker

### ISSUE THREAD

**Issue by Doni49** [k9mail/k-9#792]
I have used Tasker for about 5 years now.  And K9 for about 2 or so.

There is currently a Tasker plug in for K9.  I'd like to see that expanded.  I would like Tasker to be able to tell K9 to start/end quiet time (as opposed to requiring me to enter a time.

**Comment by cketti** [comment]
I'm happy to look at pull requests but don't want to track this enhancement request (that doesn't benefit users only third-party apps) in our issue tracker.

**Comment by Doni49** [comment]
I'm sorry but I'm completely new to Github and have enough idea what that means.

**Comment by cketti** [comment]
That means we don't care about this issue until someone writes the necessary code for K-9 Mail and the tasker plugin.

**Comment by Doni49** [comment]
"until someone writes the necessary code" 
So where does one go to make such feature requests so that someone might see it and get interested?
