### ISSUE TITLE
Option to not save sent message in Sent folder

### ISSUE THREAD

**Issue by PanderMusubi** [k9mail/k-9#799]
Please, offer an option not to save sent messages in the Sent folder.

Some people sent a lot of message and use BCC to themselves to save import sent message and keep the Send folder to the point and not clutter up with everything that was sent.

This was reported for version v5.006. See also https://code.google.com/p/k9mail/issues/detail?id=3890 and https://code.google.com/p/k9mail/issues/detail?id=4038 and https://code.google.com/p/k9mail/issues/detail?id=6144

**Comment by PanderMusubi** [comment]
This might be a setting that is account specific, see https://github.com/k9mail/k-9/pull/439

**Comment by cketti** [comment]
What exactly are you asking for? There already is a way to prevent K-9 Mail from uploading sent messages.

To quote my comment in the linked issue:
> Set "Account settings" > "Folders" > "Sent folder" to "-NONE-" to disable saving sent messages.

**Comment by PanderMusubi** [comment]
Sorry for the inconvenience. It is indeed supported since the three issues from Google Code that I referenced. Could not find it in the current version but with your help I did. Thanks.
