### ISSUE TITLE
unicode subject lines

### ISSUE THREAD

**Issue by dcherian** [k9mail/k-9#801]
Message bodies with unicode characters are displayed fine. The subject line isn't.

**Comment by cketti** [comment]
Subjects with unicode characters are displayed fine when they are encoded correctly.
There might be a small bug with subject handling. But that shouldn't affect a lot of people. See #723

In the future please use the [template](https://raw.githubusercontent.com/k9mail/k-9/master/issue_template.md) when reporting bugs.
