### ISSUE TITLE
RFE: line wrap after 78 characters

### ISSUE THREAD

**Issue by ckujau** [k9mail/k-9#802]
This is basically a copy of [#4982](https://code.google.com/p/k9mail/issues/detail?id=4982) or [#3016](https://code.google.com/p/k9mail/issues/detail?id=3016): please support a line-wrap after e.g. [78 characters](https://tools.ietf.org/html/rfc5322#section-2.1.1) when composing emails. Without that, emails sent via K-9 Mail are hard to read and one has to scroll horizontally.

**Comment by dbart** [comment]
This is the main issue I have with K-9 mail right now. Supporting proper wrapping is very important for plain-text emails.

**Comment by cketti** [comment]
Since quite a while we always use quoted-printable encoding. The encoded text has a maximum line length of 76 characters.
