### ISSUE TITLE
Repeated Error: "Negative SMTP Reply: 501 5.1.3 Bad re...", "Failed to send some mess..."

### ISSUE THREAD

**Issue by dhowe** [k9mail/k-9#808]
This error has been coming up every few minutes for the past month (I can't read more than I've typed above) -- how do I disable it once and for all?

![photo on 22-9-15 at 5 47 pm](https://cloud.githubusercontent.com/assets/737638/10015407/8e683b24-6152-11e5-854a-93bfa6c4e69d.jpg)

Perhaps similar to https://www.mail-archive.com/k-9-mail%40googlegroups.com/msg02178.html ?

K-9 Mail Version: 5.107
Android 4.4.4 KTU84P

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by dhowe** [comment]
I'll just switch clients

**Comment by dhowe** [comment]
https://www.google.com.hk/search?q=%22negative+smtp+reply%22+%22k-9%22&oq=%22negative+smtp+reply%22+%22k-9%22&gs_l=serp.3..0i22i30l2j0i22i10i30.5754.8193.0.8506.6.6.0.0.0.0.157.840.0j6.6.0....0...1c.1.64.serp..0.6.837.AHBgZApRJdw
