### ISSUE TITLE
Navigation: going back to accounts view requires multiple taps

### ISSUE THREAD

**Issue by unsystemizer** [k9mail/k-9#816]
I hope the subject explains the issue well. In more detail: say you have 3 IMAP accounts and you want to see new messages in one of them. Once you click on Account and end up in INBOX, to return back to the view of all 3 accounts, you need to click the arrow in top left corner 3 times. If you check email 10 times a day, you may need to perform this action dozens of times.

I wish there was a way to do that with one move/tap. Or maybe a "home" icon could be added.

**Comment by cketti** [comment]
See #817
