### ISSUE TITLE
Add navigation drawer

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#817]
Add [navigation drawer](http://www.google.com/design/spec/patterns/navigation-drawer.html) similar to that of the Gmail app for easier navigation.

See also #645

**Comment by jmeinke** [comment]
Are you working on this issue already or might I give it a try?

**Comment by lbdroid** [comment]
Agreed. Always disliked the way activities are layered in k9mail from the accounts screen to the specific directories. Account and directory selection should be moved over to the nav drawer, and the directory content and message view as fragments.

**Comment by cketti** [comment]
Implemented in `master`.
