### ISSUE TITLE
Link SMTP Error messages to outgoing mail folder

### ISSUE THREAD

**Issue by jan-glx** [k9mail/k-9#830]
Recently, I sent an mail to a wrong address causing a ""Negative SMTP reply: 550 5.1.1" notification.
This notification reappeared anytime I read it unit I figured how to delete the message stuck in the outgoing folder. Or rather: until i figured out, where I could delete that mail.
I think **this inconvenience could be avoided if the notification linked directly to the Outbox** (German: "Postausgang") folder.  (Note that for me there is `Drafts`, `Sent`, `K9mail-errors`, `Outbox`, `Drafts` again, `Sent` again - quite a lot of possible places to find the email in question)
thank you for K9mail, 
Jan

Below are examples of Q&A post where other people had the same problem.
https://groups.google.com/forum/#!topic/k-9-mail/iV80al2RB7I
http://grokbase.com/t/gg/k-9-mail/13c4drj907/negative-smtp-reply-501-part-2
http://grokbase.com/t/gg/k-9-mail/13asj6j25b/failed-to-send-some-messages

**Comment by gmgj** [comment]
I get  a failed to send Negative SMTP reply 501 in my notifications form Android.  I can't find it in k-9.  I was expecting to see it in K9 errors.

**Comment by cketti** [comment]
See #1362
