### ISSUE TITLE
Users must be given the choice of whether to use the bottom action bar or not

### ISSUE THREAD

**Issue by Dinduks** [k9mail/k-9#831]
Hi,

I noticed that, after the last update, the bottom action bar was moved to the top of the screen, merged with the title bar.  
While I understand that this saves screen space, it is annoying for users with big screens as they have to either move their thumb to the very top of the screen, or use two hands.

I'm not asking to throw your decision to merge the bars away, but to give users the choice whether to have a bar in the bottom or not.

Thank you.

**Comment by cketti** [comment]
We didn't change anything related to the action bar. We were always using "splitActionBarWhenNarrow", i.e. the OS would decide whether or not to display a split action bar.
