### ISSUE TITLE
K9 suddenly deleting messages that are removed from server even with sync server deletions unchecked

### ISSUE THREAD

**Issue by jsciandra** [k9mail/k-9#833]
Had K9 for a very long time. I read my gmail with pop from 2 different clients, K9 on phone and Outlook on PC. The outlook client is configured to server delete. K9 is configured not to server delete or sync server deletions. I keep things on my phone that I have to manage, appts, etc, but I pull them off of gmail and archive them on outlook. For literally years, this worked great and emails stayed on my phone forever until I explicitly deleted them. Suddenly, my phone gets purged constantly. Please help.

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
