### ISSUE TITLE
Notification buzzing cannot be disabled anymore

### ISSUE THREAD

**Issue by creinig** [k9mail/k-9#835]
### Expected behaviour
There should be some way to disable any sound / vibration for k-9 notifications

### Actual behaviour
Since updating K-9 to Version 5.006 notifications (mail received, mail being sent) cause a vibration buzz. Before that all mail notifications were quiet.

I've changed the "Quiet time" setting to 00:00-23:59 (previously unset), but to no effect.
In the account settings vibration for notifications is disabled and no ringtone is set.

Disabling all notification sound+buzz in the device settings doesn't change anything -- mails still cause vibration. Since I *do* want buzzing for SMS this wouldn't be a real workaround anyway.

### Steps to reproduce
1. disable all notification sounds
2. send or receive mail
3. ---

### Environment
K-9 Mail version: 5.006

Android version: 4.4
Device: Samsung Galaxy S2 (GT-I9100)
OS: CyanogenMod 11.0-InstallerXNPQ32P
Kernel: 3.0.64-CM-g89e6992 , build04@cyanogenmod 1 , Fri Aug 8 19:54:57 PDT 2014

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/Manual-accountsettings#vibrate
