### ISSUE TITLE
Problem with STARTTLS under Android Marshmallow

### ISSUE THREAD

**Issue by bnajdrovsky** [k9mail/k-9#836]
K-9 Mail fails to communicate with the server for sending messages using STARTTLS under Android 6.0.  The problem appears to be with the key exchange by the SSL library.    I don't know if this is partly caused by Google's migration from OpenSSL to BoringSSL, but K-9 seems to be the only program giving me problems right now.  Here is the relevant logcat:

10-07 15:57:48.501  3754  9300 E k9      : Error while testing settings
10-07 15:57:48.501  3754  9300 E k9      : com.fsck.k9.mail.CertificateValidationException: Handshake failed
10-07 15:57:48.501  3754  9300 E k9      :      at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:414)
10-07 15:57:48.501  3754  9300 E k9      :      at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:146)
10-07 15:57:48.501  3754  9300 E k9      : Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
10-07 15:57:48.501  3754  9300 E k9      :      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
10-07 15:57:48.501  3754  9300 E k9      :      at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
10-07 15:57:48.501  3754  9300 E k9      :      at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
10-07 15:57:48.501  3754  9300 E k9      :      at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:284)
10-07 15:57:48.501  3754  9300 E k9      :      ... 1 more
10-07 15:57:48.501  3754  9300 E k9      : Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x9d596fc0: Failure in SSL library, usually a protocol error
10-07 15:57:48.501  3754  9300 E k9      : error:100c1069:SSL routines:ssl3_get_server_key_exchange:BAD_DH_P_LENGTH (external/boringssl/src/ssl/s3_clnt.c:1193 0xab21d50f:0x00000000)
10-07 15:57:48.501  3754  9300 E k9      :      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
10-07 15:57:48.501  3754  9300 E k9      :      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)

**Comment by cketti** [comment]
That's most likely because your server is using a DH group size smaller than 1024 bits.

https://boringssl.googlesource.com/boringssl/+/a7997f12be358e58aeb2345bb8b88a9d53240024%5E!/

**Comment by bnajdrovsky** [comment]
Thanks so much, cketti.  Indeed that was the issue.
