### ISSUE TITLE
Don't auto-start after boot when all accounts are configured for manual polling

### ISSUE THREAD

**Issue by gerroon** [k9mail/k-9#840]
I do not know why K-9 keeps adding to the start up. I keep disabling from the start up with various up but it persistently wants to be in the startup.

I am using CM 11 Kitkat
thanks

**Comment by cketti** [comment]
Disabling autostart is not a supported feature. We could disable autostart when all accounts are configured for manual polling. But that's certainly a very low priority feature.

**Comment by gerroon** [comment]
thanks for considering.

**Comment by cketti** [comment]
The switch to WorkManager in K-9 Mail 5.7xx gave us this feature for free.
