### ISSUE TITLE
Add option to limit line length of text/plain bodies

### ISSUE THREAD

**Issue by matthiasbeyer** [k9mail/k-9#841]
Hi,

first: Thanks for developing K9, it's a wonderful tool!

I'd really like to see a line-length-limit option in the settings, so K9 automatically breaks after 72 characters. Can we have something like this?

**Comment by cketti** [comment]
Related: #822

**Comment by alanthehat** [comment]
https://tools.ietf.org/html/rfc2822#section-2.1.1 may have some bearing, but I too like the 72 char limit as it allows a section to be 'quoted' twice & stay within the 78 char limit

**Comment by matthiasbeyer** [comment]
Ah, it was 78 characters, actually. Okay, well ... I'd then go for this limit.

**Comment by cketti** [comment]
In the future we will only use quoted-printable as transfer encoding. See #1034 
This will automatically cause lines in the email body to be at most 78 characters long. However, this won't make the decoded text to have line breaks after 78 characters. I'm not convinced that we should add support for that.

**Comment by toreanderson** [comment]
It indeed be nice to have this feature, as most technical mailing lists consider posts not conforming to RFC2822 (text/plain, no long lines) to be a faux pas.

I stumbled across this issue while trying to find out if it was possible to configure RFC2822-compliant composing. While doing so I also found issue #802. The two issues could possibly be merged.

**Comment by castilma** [comment]
@cketti 

> In the future we will only use quoted-printable as transfer encoding.

From the issue #1034 it seems that the future started at 19.8.16. I still have the problem with version 5.208.

> However, this won't make the decoded text to have line breaks after 78 characters

With decoded text you mean received messages?

**Comment by AlainKnaff** [comment]
This bug has now been open for more than 2 years. Any progress on this? Thanks.

**Comment by cketti** [comment]
We now always use quoted-printable encoding. Encoded text is 76 characters or less per line.
