### ISSUE TITLE
Iframes not working in K9mail?

### ISSUE THREAD

**Issue by JavierDiaz** [k9mail/k-9#843]
Hello, I have the following html email:

```html
<html>
<head>
<title>Test</title>
<base href="http://barrapunto.com/~EsePibe/journal/38348?from=rss">
<style type="text/css"> body { margin: 0; border: none; padding: 0; height: 300px; } iframe { position: fixed; top: 0; left: 0; width: 100%; height: 100%; border: none; } </style>
</head>
<body>
<iframe id ="_mailrssiframe" src="http://barrapunto.com/~EsePibe/journal/38348?from=rss">Test</iframe>
</body>
</html>
```

and it appears the following error when opening it:
<pre>
Webpage not available

The webpage at http://barrapunto.com/~EsePibe/journal/38348?from=rss could not be loaded because:

net:ERR_CACHE_MISS
</pre>

I'm using android 5 and last version of k9mail.

If it is any way to make it work, I can change html source, but I want to view the iframe url directly in k9mail, without opening browser.

Many thanks

**Comment by cketti** [comment]
Remote content is not loaded/displayed by default. If there was a remote image in the message the "Show pictures" button would show and after pressing it the contents of the iframe would also load.

But iframes in emails are a really bad idea and I created issue #846 to remove support for them entirely.
See also: https://www.campaignmonitor.com/blog/email-marketing/2010/08/do-iframes-work-in-email/

**Comment by JavierDiaz** [comment]
Adding:
```
<img src="http://127.0.0.1/img.png" width="0" height="0" border="0"/>
```
And adding sender email to contacts, iframe works perfect, many thanks

In my opinion, a lot of email clients support iframes, so it should be supported in k9mail
