### ISSUE TITLE
Google doesn't like k9 and if I travel abroad it believes my accont could have been hijacked...

### ISSUE THREAD

**Issue by ghostrider72** [k9mail/k-9#844]
It is now three or four times it happens: I go to Portugal or Spain (I live in Italy) and if I try to connect via wifi or an international sim card (Estonian roaming sim or Belgian) google sends me an email/sms stating there's an unauthorized attempt to access my mail account. Moreover, from that moment on, k9 mail is denied access to my mail account.
I have reserched the net and discovered several posts here and there concerning this issue. First of all my wife doesn't get this error while I get locked instead! Then I read that basically google considers k9 mail an unsecure client and doesn't like it, hence the lock. Is this true, and if so, why?
Third, someone told me that these issue don't normally happen if you, in similar circumstances, use the stock email client.
Thanks in advance for all replies and advice.
Ps. I also tried to log into my account via browser from my phone but even if I accessed this way without problems, k9 still did not work.
Any idea?

**Comment by cketti** [comment]
This is not an issue specific to K-9 Mail. Google blocks access if you connect from an unusual location. Usually it asks for additional information to make sure it's really you. But that's not supported with the simple username/password mechanism K-9 Mail is using.
Logging in via the Web before allowing K-9 Mail to connect to Gmail from the new location might be enough to fix the problem.

This might get better when issue #847 is implemented.

**Comment by ghostrider72** [comment]
I knew this, so basically the only remedy available now is to stop k9 before hopping on the plane and then once abroad doing the first connection via web.
I'm gonna try this.
