### ISSUE TITLE
Moto Active Display doesn't show K9's notifications

### ISSUE THREAD

**Issue by mruwek** [k9mail/k-9#845]
Recent phones from Motorola have this super-cool feature called Moto Active Display (http://youtu.be/3TMycL9mzpg) and it works great with plenty of apps, but unfortunately not with **K9**.

**What works:**
1. Sound is played
2. Notification sits on notification bar when phone is unlocked.

**What doesn't:**
1. Notification doesn't appear on Moto Active Display screen.

Moto G 2015 with stock firmware

**Comment by cketti** [comment]
It is a nice feature. And if someone cares enough to provide a fix I'm more than happy to look at a pull request.
But considering the growing number of enhancement requests in our issue tracker I see no point in keeping one for a non-stock feature around. The chance of someone adding/fixing this functionality only because an issue exists is almost 0.

**Comment by mruwek** [comment]
Just for the reference: It is fixed with the Marshmallow update, so maybe it was rather an error in Motorola's code :)

**Comment by omehegan** [comment]
FWIW this broke again starting with the pre-5.2 alpha releases.

**Comment by omehegan** [comment]
If anyone cares, updating to the latest version of the 'Moto Display' app in the Play store fixed this problem.

**Comment by k9foo** [comment]
This worked fine for me through many versions of K-9 Mail until the 5.2 updates. What changed in K-9 Mail to make its notifications stop working in Moto Display?

**Comment by k9foo** [comment]
Update: So for some reason I had to manually re-select K-9 Mail as an app to appear on Display in Moto settings. Now I do get a notification in Moto Display on new mail, but the mail/envelope icon is blank (it's just an empty circle). Seems to be an issue with the icon. This is a different issue.

**Comment by omehegan** [comment]
With the latest version of the Moto Display app and version 5.200 of K-9, the Active Display notifications work the same as they always did for me. I did not have to remove/add the app to Moto Display to get it working.

**Comment by k9foo** [comment]
I did not have this issue in K-9 Mail 5.200. It started after that and is present in 5.202.

Try updating to K-9 Mail 5.202 and let us know what happens. :-)

**Comment by k9foo** [comment]
I opened a new issue with a better description since this is an icon problem and not a lack of notification in Moto Display.
