### ISSUE TITLE
Copy/move between accounts

### ISSUE THREAD

**Issue by Natureshadow** [k9mail/k-9#850]
Please make it possible to copy or move mail to folders in other accounts.

This will mean to download and then append the full message.

**Comment by Natureshadow** [comment]
Of course, this only works with IMAP.

**Comment by klonamy** [comment]
I think that is the same as my issue: https://github.com/k9mail/k-9/issues/760

**Comment by sffog** [comment]
Has this been addressed? I need to move messages from an old account to a new account.
