### ISSUE TITLE
Old mails being retrieved when deleting messages in K-9

### ISSUE THREAD

**Issue by sboden** [k9mail/k-9#869]
I have a pop3 account in K-9. I synchronize mails in K-9 while I have more mails on the server side than K-9 will download. I now delete 5 messages from K-9. I sync again, if the mails on the server side stayed the same, K-9 will now download mails from/at the old end. Presumably to reach its quota of mails. A notification is then also put out for these old mails which can be confusing.

Fix: do not download mails that are older than the oldest mail already in an account.

**Comment by philipwhiuk** [comment]
You can already change the settings so that it doesn't sync messages older than a given time limit.

**Comment by sboden** [comment]
I've been checking all settings in the latest version of K-9: global, account, folder. Can't find it, can you let me know where that option is?

It's a small thing... to me the behaviour I get now doesn't feel that intuitive (when I get it about once a month): I only expect new messages to sync, not old ones just to fill up the number of messages in the "view".

But if there's an option to limit time I'm fine.

**Comment by wweich** [comment]
The setting for time is right below the setting for message count in settings -> account settings -> fetching mail -> sync messages from.

**Comment by cketti** [comment]
This is working as intended. We will probably change the behavior in the future, though.
