### ISSUE TITLE
K-9 not working properly with my hotmail account

### ISSUE THREAD

**Issue by DaveRado** [k9mail/k-9#870]
I have two email accounts, both set up using IMAP: my normal one being [myname]@mvps.org, which I've had for years; and a secondary one which I've just added, which is [myname]@hotmail.co.uk.

If I receive an email in my mvps.org account, it appears in my K9-Mail inbox instantly (i.e. the moment it arrives on the mail server it also appears in my K9-Mail inbox). But if I receive an email in my hotmail account, it doesn't appear in my K9-Mail inbox unless I go into the inbox and press "Refresh".

I don't get this problem on my PC, on which my Thunderbird client picks up emails from both email addresses as soon as they are appear on the relevant mail server.

Also, if I delete an email from my K9-Mail inbox, then if it is an email from my mvps.org account, it is immediately deleted from the mail server as well; but if it is an email from my hotmail account, then it doesn't get deleted from the mail server. And yet, under Account Settings, "When I delete a message" is set to "Delete from server"; and "Erase deleted messages on server" is set to "Immediately. Again, I don't get this problem on my PC, on which, if I delete an email in my Thunderbird client, regardless of whether it's an mvps.org email or a hotmail email, the message is immediately deleted on the mail server as well.

Any idea why K9-Mail is synching my primary mvps.org account perfectly but is not synching my secondary hotmail.co.uk account properly?

Dave

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
