### ISSUE TITLE
K-9 doesn't working with my Exchange 2013

### ISSUE THREAD

**Issue by VictorJava** [k9mail/k-9#873]
There is some problem.

![screenshot_2015-10-28-18-01-40](https://cloud.githubusercontent.com/assets/8449621/10822604/91488a94-7e60-11e5-9fe5-3997795bf4ce.png)
![screenshot_2015-10-29-10-27-57](https://cloud.githubusercontent.com/assets/8449621/10822606/914a5b30-7e60-11e5-94b6-4718173c55e9.png)
But after button "accept key".
messages didn't loading.

How I can configure it?
Speaking about https://github.com/k9mail/k-9/wiki/K9MailAndExchange
Can k9 read 2013?

Could you help me?
Thank you in advance.

**Comment by cketti** [comment]
Exchange 2010 and newer are not supported. Also, this is the wrong place for support questions.
