### ISSUE TITLE
Sign In Attempt Prevented: Modern Security Standards

### ISSUE THREAD

**Issue by anEffingChamp** [k9mail/k-9#874]
On some Google business accounts I receive the following message when I log in with K-9 mail.

>Someone just tried to sign in to your Google Account xyz@xyz.com from an app that doesn't meet modern security standards.
>Details:
>Tuesday, October 27, 2015 11:37 AM (GMT)
>We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable. [Learn more](https://support.google.com/accounts/answer/6010255).
>Google stopped this sign-in attempt, but you should review your recently used devices:

**Comment by cketti** [comment]
See #655
