### ISSUE TITLE
Deletion from new-mail-notification

### ISSUE THREAD

**Issue by madduck** [k9mail/k-9#877]
I love being able to directly reply or mark-read a message for which I am being notified via the Android status window. How about a third button, allowing me to directly delete the message without even opening it? Or even a spam button? Maybe the button set could be configurable?

Thanks,
martin

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/Manual-globalsettings#show-delete-button

**Comment by madduck** [comment]
Thanks for the rapid response. I am sorry, I hadn't thought of looking in the global settings! Sorry about the extra effort…
