### ISSUE TITLE
copy emails from the top

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#880]
It should be possible to view and copy the email addresses listed at the top of a mail without viewing its header.
My headers are around 40 lines long so it's not easy to spot all of them there.

In Addition to that it would be nice if you could tap on a person and then choose to write a new mail to that email address (no reply).

Djfe

**Comment by cketti** [comment]
Long-pressing sender or recipients copies them to the clipboard.

**Comment by Djfe** [comment]
thx, I didn't know that.
what confused me was:
clicking on the sender makes a clicking noise and then asks whether to add the mail to your contacts.

clicking on receiver or cc/bcc also makes a clicking noise but that's all (nothing actually happens)

I never tested click and hold for whatever reason ^^
