### ISSUE TITLE
IMAP: Ask for folder types on account creation

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#881]
K9 should ask the user which folders to use for deleted items, send items etc. before creating new ones that are just called differently.

Regards,
Djfe

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/wiki/Manual-accountsettings#folders

**Comment by Djfe** [comment]
Why are you closing this issue?
It is still happening, that K9 is creating a second folder for something that exists already, if it is named differently on the IMAP server.

K9 shouldn't create a sent/trash folder automatically if none exists.
It should ask the user
