### ISSUE TITLE
Mails encrypted with PGP/mine show only two files as attachment

### ISSUE THREAD

**Issue by pak00** [k9mail/k-9#882]
as in the object, when i receive a PGP mime encrypted message (source message as below), k9 shows me only two attachment:
encrypted.asc
noname.pgp

<code>

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--b1_958b3a67ff99a26962f3de5dbfab5b33
Content-Type: application/pgp-encrypted; charset="UTF-8"
Content-Transfer-Encoding: 7bit

Content-Description: PGP/MIME Versions Identification

Version: 1

--b1_958b3a67ff99a26962f3de5dbfab5b33
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Transfer-Encoding: 7bit
Content-ID: <0>
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

[...]

-----END PGP MESSAGE-----

--b1_958b3a67ff99a26962f3de5dbfab5b33 --

**Comment by clawoflight** [comment]
K9 doesn't yet support OpenPGP/MIME, only Inline.
And it will probably take at least another year to get that sorted out because core infrastructure needs to be completely redesigned.

**Comment by cketti** [comment]
`master` has partial PGP/MIME support. However, it's not clear what version the OP is using because they didn't use the issue template.
