### ISSUE TITLE
Notifications Sounds

### ISSUE THREAD

**Issue by prog9999** [k9mail/k-9#895]
Running 5.006 on a rooted Nexus 6P with Android 6, build MDB08K.
When email comes in there are no notifications sounds. Is this a setting that I cannot find or is it a bug.
Thanks...Great App, P Prog

**Comment by wweich** [comment]
You can set the notification sound in settings -> account settings -> notification -> notification sound.
I don't remember what the default was, but I think the default notification sound for messages is used as default.

**Comment by prog9999** [comment]
Thanks, that worked! That setting must have not come over in the imported settings from the other phone.
