### ISSUE TITLE
Delete on Pebble

### ISSUE THREAD

**Issue by ifuchs** [k9mail/k-9#898]
Is there a way to get a Delete option to appear for Pebble notifications? I tried disabling 'Global settings > Interaction > Confirm actions > Delete (from notification)' which someone said would help but it was to no avail. Is this doable? (I know I can run another app K9email but would prefer not to.)

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
