### ISSUE TITLE
Following Android 6.0 upgrade, K-9 unable to send emails

### ISSUE THREAD

**Issue by rfurr** [k9mail/k-9#910]
Using a Nexus 7 gen2
After upgrading to Android 6.0,
I can no longer send emails.  Receiving still works fine.
Using STARTTTLS, port 587, signing with normal password.
After accepting the key for an unknown certificate (its always done this),
I receive "Cannot connect to server (handshake failed)".

**Comment by cketti** [comment]
That's probably because your mail server is using outdated encryption ciphers that are no longer supported by Android 6.0.
