### ISSUE TITLE
Support TLS extension "SNI" / Server Name Indication

### ISSUE THREAD

**Issue by the0ne** [k9mail/k-9#911]
K-9 should support SNI as Let's Encrypt makes free & automated SSL Certificates widely available. Having virtual hosting on a single IP however any SSL Certificates are usable only if K-9 supports SNI.
https://en.wikipedia.org/wiki/Server_Name_Indication

SNI addresses this issue by having the client send the name of the virtual domain as part of the TLS negotiation.[2] This enables the server to select the correct virtual domain early and present the browser with the certificate containing the correct name. Therefore, with clients and servers that implement SNI, a server with a single IP address can serve a group of domain names for which it is impractical to get a common certificate.

SNI was added to the IETF's Internet RFCs in June 2003 through RFC 3546, Transport Layer Security (TLS) Extensions. The latest version of the standard is RFC 6066.

**Comment by cketti** [comment]
This has already been implemented. See #718.
