### ISSUE TITLE
Widget cannot be placed on homescreen in Android 5.1.1

### ISSUE THREAD

**Issue by WebZakenAdvies** [k9mail/k-9#912]
On my new phone, running Android 5.1.1. the new mail wizard cannot be placed. I use K-9 Mail Version 5.006

**Comment by cketti** [comment]
I'm assuming you're talking about the widget displaying the unread count. It hasn't been touched in a long while and should work just fine.
Maybe you're trying to place it somewhere the system doesn't allow you to put widgets. In any case, there's no way for us to reproduce the bug with the little information you provided.

**Comment by WebZakenAdvies** [comment]
Yes, this is about the unread count widget. It worked well on my 
previous phone running Android 4.4, but on my new phone running Android 
5.1.1. I cannot put the widget on my home screen. Every time I try, it 
opens the app instead of placing the widget. I put the widget on an 
acceptable position.

What can I do to provide more information to you?

Op 02-12-15 om 00:35 schreef cketti:

**Comment by cketti** [comment]
It doesn't really open the app. It opens a screen asking you to select an account.
