### ISSUE TITLE
settings backup 

### ISSUE THREAD

**Issue by mis2417** [k9mail/k-9#914]
default account and position in account list is not saved in the backup file. settings are lost on reinstall

**Comment by mis2417** [comment]
also 'preview lines' and 'correspondent name above subject' don't get saved

**Comment by cketti** [comment]
Missing 'preview lines' sounds odd. Can you confirm that your settings file doesn't contain "messageListPreviewLines"?
The missing 'correspondent name above subject' has already been fixed in master.

I'm leaving this as enhancement request for keeping the default account and order of accounts.

**Comment by mis2417** [comment]
the only *MessageList* lines in the backup file are:

<value key="fontSizeMessageListDate">smaller</value>
<value key="fontSizeMessageListPreview">tiniest</value>
<value key="fontSizeMessageListSender">smaller</value>
<value key="fontSizeMessageListSubject">tiniest</value>
<value key="messageListCheckboxes">true</value>
<value key="messageListStars">false</value>

thanks.

**Comment by philipwhiuk** [comment]
`messagePreviewLines` is exported on the current latest build
