### ISSUE TITLE
key-aware recipient chooser

### ISSUE THREAD

**Issue by Valodim** [k9mail/k-9#915]
For sending of encrypted mail, the recipient picker should be crypto-aware. There are a couple of things to consider, and some design choices to make. Let's-a go:

So first off, the material way to go is [chips](http://www.google.com/design/spec/components/chips.html#chips-contact-chips). There are a couple of libraries for that, in OpenKeychain we use [TokenAutoComplete](https://github.com/splitwise/TokenAutoComplete/), which is mature and flexible but not quite material-design. There are also libraries based on Google's internal chips library from the GMail app, like [android-chips](https://github.com/klinker41/android-chips), but those aren't really made to be anything else but regular contact pickers and I havn't found one which looked mature. Since material design in k-9 isn't really there yet anyways, I would go with the more established and maintained option here, i.e. TokenAutoComplete.

So, what do we actually want to show in the list? At the moment, a list of e-mail addresses (not contacts) is shown, queried from `ContactsContract.CommonDataKinds.Email`. This is the obvious thing to show, and it seems more reasonable than a list of contacts so I would just keep it that way. What I would like to add is an annotation to each address about its crypto-status.

In OpenKeychain, we have icons to show the key status - a green checkmark, yellow question mark, and some red ones for revoked/expired/unsuitable for operation. The problem is, outside of an explicit crypto context, it's not clear that these icons are about the status of some encryption key, so we really can't use them here. We also don't need info about special states of a key - revoked or expired keys are simply irrelevant for recipient selection.

My proposal would be to use Threema's concept: Three dots, with three states "one in red" / "two in yellow" / "three in green", all others greyed out. Check out ma [mock-up](https://dl2.pushbulletusercontent.com/ej9urTcljTmiDHTYjofFkmhS1j9WdDAN/IMG_20151126_150639.jpg). The idea is to be mildly alarming ("just one of three"), but also suggest a way to progress ("key available, two out of three", "verified that thing, three out of three!").

A different approach would be a lock in different states (red/yellow/green with open / closed+questionmark / closed+checkmark), but I'm a) missing the progress aspect of the three-dots concept, and b) an open red lock next to each mail address is just a tad too alarming - if the UI tells the user "this is unsafe!", they might just migrate to a different program which is equally unsafe but does nothing to inform the user about that fact.

Some more thoughts:
- if a valid (or even confirmed) key is available, the user will likely want to encrypt - optimize for that.
- encryption without signing is not a reasonable use case and I would not support it.
- pgp/mime vs pgp/inline is an orthogonal problem to everything mentioned here, I would leave it for later
- do we need a contact-picker-button? the gmail app removed theirs recently. If we do, the information it displays should be identical to the dropdown.

**Comment by Valodim** [comment]
Almost forgot: Implementation-wise, we need to query the data using the regular contacts provider query, get additional info about the availability of keys per e-mail address, and merge that. Since the data comes from different sources, the merge will have to happen in the cursor, and the queries need to be executed sequentially. Not ideal, but no huge deal either.

This query can happen in one of three places:
a) add a "key given a set of addresses" contentprovider to OpenKeychain, merging in k-9 mail itself
b) add a "annotated contacts" contentprovider to OpenKeychain, simply querying that instead of the regular one in k-9
c) like a), but make the merging and stuff part of the OpenPgpApi lib

I lean towards option c), because it has the highest reuse potential by other clients and can also be extended client-side.

**Comment by cketti** [comment]
I like the three dots scheme. But I believe outside an explicit crypto context it'll confuse users. Maybe a lock is the better solution. I don't believe that showing an open lock would drive users to other apps. After all, they explicitly installed a crypto provider (I wouldn't display a key status indicator otherwise).

For the implementation I'd say start with a) and eventually do c) if you believe the result is generic enough that it is of use to other apps.

**Comment by Valodim** [comment]
first step, switched to TokenCompleteTextView: 5214b664d0cc997bae9b779aade524430365a8f0

I didn't put too much time into ui (sizes, paddings, ...) and based most ux decisions on "when in doubt, emulate gmail". One thing where I wasn't sure was the contact picker button. Gmail removed it, I feel like it distracts from the intended way (write text, use completion), but I didn't want to remove those buttons without asking.
