### ISSUE TITLE
Infinite sync notification

### ISSUE THREAD

**Issue by av2k** [k9mail/k-9#918]
Using the most recent K9 client on the most recent Cyanogenmod stable release on a Nexus 7 device, and using IMAP accounts, sometimes the sync notification with the clockwise-turning circular arrow animation is displayed infinitely.

As far as I have investigated, this issue happens when there is a successfully established WiFi connection into a network that has no Internet connectivity.

The notification persists in the tray even if K9 is stopped and restarted. It also persists even if K9 regains Internet access and successfully syncs the mail accounts. In this case, a second, similar notification is displayed just below the infinitely running notification in the tray, for the duration of the successful synchronization.

To get rid of the infinitely running notification, I have to reboot the device. Maybe the hard killing of process remnants using the Terminal also helps but I have not yet tried this solution.

**Comment by cketti** [comment]
This might be a bug with Cyanogenmod. K-9 Mail reuses the notification ID for a sync notification and should overwrite old notifications on a new sync.

"The most recent K9 client" is not a proper version number. Please be explicit when reporting errors.

**Comment by Canuckd** [comment]
Same issue, using version 5.006. Either a reboot or a force stop of the app will stop it.

**Comment by Canuckd** [comment]
When it happens to me I have data on, connected to wifi that does have an internet connection

**Comment by lbdroid** [comment]
When it happens (I haven't seen it from k9mail, but have seen this problem with other software), you can long click the notification, disable its notifications, and immediately re-enable its notifications. That will get rid of a stuck notification without having to reboot.

**Comment by cketti** [comment]
Closing this for now. Feel free to re-open if you can provide instructions on how to reproduce the problem.
