### ISSUE TITLE
E-mail not displayed when there is a PGP signature in the quoted e-mail

### ISSUE THREAD

**Issue by crick3t** [k9mail/k-9#919]
I have this issue and cannot find any bugs (closed or open) here just on the old code.google.com website. 
As I still have this issue I guess it was not fixed, so I would like to report it here. (I have updated it with my device information)

**What steps will reproduce the problem?**
1.Using OpenKeychain and K-9 Mail, send a signed e-mail to someone not using PGP
2.Have them respond to your e-mail, with their client quoting the entire message
3.K-9 mail receives the message, displays it for a moment, then the signature is being analyized and from then on only the part below the beginning of the signature is being displayed, i.e. the actual replay can't be displayed in K-9 Mail

**What do you expect to have happen?**
First of all, K-9 mail should not recognize the signature (my signature) in the quoted part as valid and tell me, that the reply e-mail is signed. Second of all, it should in any case also display the rest of the e-mail (the reply above the quoted e-mail). 

If I view the e-mail in Thunderbird (with the Enigmail addon)everything is displayed correctly: First the reply, then the quote - first the info-part (from, to, sent, subject), then the line "********* *BEGIN ENCRYPTED or SIGNED PART* *********", and then the content of my original e-mail.

**What do you see instead?**
Only the quoted part, aka my original e-mail.

**What version of K-9 are you using?**
version 5.002

**What is your device and what version of Android are you using?**
HTC M8, Android version 5.0.1

**Is your email account a POP account, Exchange Account or an IMAP account?**
IMAP

Original bug report: https://code.google.com/p/k9mail/issues/detail?id=6745

**Comment by cketti** [comment]
Seems to be the same as #807
