### ISSUE TITLE
Envelope-From setting

### ISSUE THREAD

**Issue by njsg** [k9mail/k-9#921]
There seems to be no way to set a value for Envelope-Sender / Envelope-From to use with an SMTP server, which seems to be required by some servers.

Would it be feasible to add a setting for this?

**Comment by cketti** [comment]
Those are not standard headers and not something that is added by a mail client. SMTP servers often add these.

**Comment by njsg** [comment]
Maybe I did not get the correct name of the field, and it's just the way other clients name it in the settings. But last time I discussed this in a k9 mail forum, I was told this is from RFC 821, so that would make it a standard header.

**Comment by cketti** [comment]
From your description it's not clear to me what the actual problem is. If you have something concrete to point to, please do.

**Comment by njsg** [comment]
Some servers I use won't accept arbitrary addresses in the message From: field unless the Envelope-From is set to an address that belongs to the same server.

**Comment by cketti** [comment]
I don't believe a mail client for end users should use a sender address in the SMTP session that's different from the one in the actual message. I haven't seen this supported by any other client either.

**Comment by njsg** [comment]
I have been able to do this with different clients on a desktop computer. Still, regardless of whether other clients support it or not, it would be convenient for me if k9 mail had this feature. Otherwise I have to get a different mail server just to use k9 mail as a main mail client.
