### ISSUE TITLE
Design and usability help opportunity

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#931]
I don't intend to rub anyone the wrong way by suggesting this, but Simply Secure is offering "free assistance with user-experience (UX) design as well as usability research". As the definitive free software email client, I think K-9 Mail could benefit from this.

If you are interested in applying, more information is [here](https://simplysecure.org/blog/apply-for-help/).

Thank you for your awesome software work!

**Comment by cketti** [comment]
Thanks. Sound awesome.

**Comment by alexanderdd** [comment]
The "here" link is dead, so I guess somebody can close this issue.
