### ISSUE TITLE
Error: 505 when I try to install

### ISSUE THREAD

**Issue by snarpel** [k9mail/k-9#934]
`Oneplus One (A0001)`
`Android: 5.1.1 (Cyanagen OS 12.1-YOG4PAS3JL)`
`Not Rooted`

I'm getting the following when I try to install:

![screenshot_2015-12-06-18-43-48](https://cloud.githubusercontent.com/assets/10982664/11614937/392c606c-9c4a-11e5-94bd-e58630abc6ce.jpg)

**Comment by cketti** [comment]
You probably have an app installed that defines the same custom permission as K-9 Mail. But newer Android versions don't allow two apps to define the same permission.

Closing this because it's not a bug in K-9 Mail.

**Comment by cketti** [comment]
See also: https://commonsware.com/blog/2014/08/04/custom-permission-vulnerability-l-developer-preview.html
