### ISSUE TITLE
New emails marked as read

### ISSUE THREAD

**Issue by jk12345** [k9mail/k-9#936]
1) Log into webmail and see that all new emails are NOT marked as read
2) Use K9 to get new emails (only headers)
3) Reload webmail and now see that almost all (95-99%) of the emails that was unread 5 seconds earlier now are marked as read, even though they were not opened in K9

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by jk12345** [comment]
The mailing list is not working for me, I get an error when trying to post
there
