### ISSUE TITLE
Trouble with the pop up scrolling menu for mail moving

### ISSUE THREAD

**Issue by Ron-A3** [k9mail/k-9#937]
Hello ...
I have K9 Mail on my android based Note 5 and I wanted to move something that I accidently moved to the trash back out of the trash to the inbox ... according to the manual this should be doable via the long press popup menu ... however ... when I long press I get a very abbreviated version of the that menu and it dose not scroll to show me other options ... the move command and the many others are not showing ... I was able to forward the mail to myself again but that is a rather inept way of doing this ... how do I get the commands to shoe on the long press menu ... I should include that this is an issue in my POP3 account but not in my Gmail account ...

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
