### ISSUE TITLE
[Bug + suggestion ] Random "star" maks

### ISSUE THREAD

**Issue by DonAndress** [k9mail/k-9#944]
Hi. 
I use 5.107 and it works nicely except for one thing. 
Almost each time I mark all emails as read, one email, randomly, is marked with a star.

**Comment by DonAndress** [comment]
And a suggestions are:

1. When mark all emails as read, ability to set k9 to mark it only locally, without synchronising this with server, in case of Imap usage. 

2. There is no synchronisation of emails removed from server via webmail. When I check emails with k9 and the list is populated , then remove emails from server via webmail and check emails again in k9, the non existing emails are not removed from the list in k9. This is on Imap.

**Comment by cketti** [comment]
Please create one Github issue per… well, issue. Don't forget to provide a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) so we have a chance to find and fix the bug.

Suggestion 1: This is very unlikely to happen. It's difficult enough trying to create a decent email client without supporting exotic use cases.

"Suggestion 2": Make sure 'Account settings > Fetching mail > Sync server deletions' is checked. If it still doesn't work, that's a bug.
