### ISSUE TITLE
Allow to place the signature above quoted text in response

### ISSUE THREAD

**Issue by Arsaell** [k9mail/k-9#951]
When answering a mail, signature is placed by default after the quoted text, which is troubblesome with long chains of mails (>20 successive answers). 

I'd like a setting allowing to place the signature between my answer and the next instead of a the end of the mail. 

I am sorry if this suggestion has already been made, I didn't take the time to read every single issue report and pull request. 

By the way, keep up that wonderfull app running and evolving, what you guys do is just wonderful !

**Comment by mawiegand** [comment]
It's already implemented.
See:
[FAQ Signature](https://github.com/k9mail/k-9/wiki/FrequentlyAskedQuestions#anchor3) 
> Choose radio button to place Signature position before or after quoted text.

**Comment by Arsaell** [comment]
Oh. My bad, I wasn't looking for it in the right menu...
Terribly sorry for the needless issue report, and many thanks for the instant answer !
