### ISSUE TITLE
IMAP wrong message sorting

### ISSUE THREAD

**Issue by ab-tools** [k9mail/k-9#952]
This issue was mentioned already on the old Google Code issue tracker here:
https://code.google.com/p/k9mail/issues/detail?id=726

Unfortunately it is obviously still not fixed as I see the same issue with wrong message sorting when using IMAP also with the latest version.

Although I really like K9-Mail due to its clean interface this makes the program completely unusable for me.

Is there any chance that this bug gets fixed?

**Comment by cketti** [comment]
Sounds like you're sorting messages by "Arrival". Change the sorting in the message list screen to "Date" and you should get the behavior you want.

**Comment by ab-tools** [comment]
That indeed did the trick - thanks a lot for your quick reply.

I really could have found out this myself. ;-)

Thanks again
Andreas
