### ISSUE TITLE
Searching through big gmail account doesn't go very far back

### ISSUE THREAD

**Issue by dandart** [k9mail/k-9#956]
Seems only messages I've synced already are searchable using the app - would there be a way to use IMAP search tools to go further back?

This may be related to #920 sorry if it's a dupe of anything

**Comment by cketti** [comment]
If the sentence ends in a question mark it's neither a bug report nor a feature request and hence doesn't belong here. In the future please ask questions like this on the [mailing list](http://groups.google.com/group/k-9-mail).

For remote search check the section [Enable server search](https://github.com/k9mail/k-9/wiki/Manual-accountsettings#search) in the "manual".
The issue for supporting full text search is #699.

**Comment by dandart** [comment]
Ah, it had to be enabled and fixed. Thanks
