### ISSUE TITLE
Clicking on new E-Mail Notification leads to error / empty e-mail when having 100 unread messages

### ISSUE THREAD

**Issue by ghost** [k9mail/k-9#958]
I had this problem several times now. If I reach 100 unread messages on one e mail account, I get a notification about a new email (that is in fact an not a new e-mail - it displays a title of an old e-mail) when the e mail account gets refreshed. If I click on the notification, it just opens a blank email.

Also, when reaching 100 unread emails - the unread counter doesn't increase even if there has a  really new email arrived.

**Comment by cketti** [comment]
Those might be multiple issues.

1. What account type is it? POP3?
2. If you let the synchronization finish before opening the "new" message by clicking the notification, does the correct message show?

**Comment by cketti** [comment]
No information provided.
