### ISSUE TITLE
Random (No subject)  emails - blank not authored by me

### ISSUE THREAD

**Issue by Soiltasun** [k9mail/k-9#960]
I believe K-9 had a request for an update recently [a week ago or so?] and since all four devices my family owns has had these blank body/(No subject) emails randomly appear. Time-stamps are not rhythmic; totally random. Nothing changed on our end in terms of configuration so if anyone could lend a hand as to why it would be much appreciated.

Build:5.007
Samsung S5 [not rooted]

**Comment by cketti** [comment]
Sorry, that is not much information to go on. Please try asking for help on the [mailing list](http://groups.google.com/group/k-9-mail). And provide as much information about your setup as possible (type of account, etc.).

From 5.006 to 5.007 nothing has changed that's very likely to cause this type of behavior.
