### ISSUE TITLE
winmail.dat from mail from MS Exchange

### ISSUE THREAD

**Issue by bb20** [k9mail/k-9#967]
Hello!

I have issue once I receive mail to my e-mail account and download them via k-9mail (show attachment) winmail.dat is in attachment. Once I forward the same mail to gmail, I'm able to see attachments. Also one I log in to my e-mail account from PC (RoundCoube) I'm able to see attachments. It is something how K9-mail interprets these attachments.

Mail type IMAP.

**Comment by cketti** [comment]
See https://en.wikipedia.org/wiki/Transport_Neutral_Encapsulation_Format

We don't plan on adding support for this to K-9 Mail.

**Comment by Seithx** [comment]
How do I read this file then on my mobile?
