### ISSUE TITLE
Feature request: EMM integration with ACE

### ISSUE THREAD

**Issue by kieran21** [k9mail/k-9#968]
ACE is a community of companies who are trying to standardize EMM settings for mobile applications. 

Would be awesome if k-9 would implement some of these features. What this would allow, for example; the app could be pushed and installed from AirWatch and the users settings (like exchange user/pass/domain/server/encryption) automatically pushed from AirAatch and configured in k-9 with no user or IT intervention.

Very useful in a large organization with an EMM solution in place.

http://www.appconfigforenterprise.org

Technical requirements: 
* Application must define application restrictions in AndroidManifest.xml
* Register a receiver for the ACTION_APPLICATION_RESTRICTIONS_CHANGED broadcast action
* Read and apply restrictions using UserManager.getApplicationRestrictions() immediately after first launch of the application, and whenever the restrictions change as indicated by the ACTION_APPLICATION_RESTRTICTIONS_CHANGED broadcast

**Comment by cketti** [comment]
Implementing and maintaining enterprise features is not a goal of this open source project.
If you're willing to pay for the development of such features in a fork of K-9 Mail feel free to contact me at cketti@gmail.com
