### ISSUE TITLE
K9 showing up black when opened from notification

### ISSUE THREAD

**Issue by chris-y** [k9mail/k-9#974]
This occurs randomly, but sometimes when opening messages from the notification, K-9 opens up as expected but is simply a black screen.  Pressing Back to get to the message list still shows up black, only when backing out as far as the account list does something display on screen.

I'm unsure as to whether this happens from the Lock screen or normal notifications, or both (I'll try and figure out if there is any pattern to it).

Current versions, but this was happening before the upgrade of both:
Android 5.1 (Moto G)
k9 5.007

I don't recall experiencing it under Android 4.4.

**Comment by cketti** [comment]
Sounds odd. Have you tried uninstalling, then reinstalling K-9 Mail?

**Comment by chris-y** [comment]
I've re-installed K-9 and it is still happening.  As far as I can tell it only happens from the Android L lockscreen notifications, and it doesn't matter whether it's a single email or multiple.  I'm only seeing it on my phone, not my tablet.

**Comment by galexmay** [comment]
I'm still getting this problem. Has anyone found a fix?

**Comment by galexmay** [comment]
Sorry, I don't have a fix, but I do have the same problem. K-9 developers, please comment!
