### ISSUE TITLE
not connecting to ZOHO mail servers

### ISSUE THREAD

**Issue by shenolm** [k9mail/k-9#977]
Does not connect to ZOHO mail servers using Exchange, IMAP or POP.

**Comment by z28cueball** [comment]
I was using Zoho for a test a few days ago.  I don't believe K9 can use the Exchange protocol with Zoho, but IMAP was working.  What are you using for a server name?  Do you get a specific error?

**Comment by shenolm** [comment]
I entered details for Exchange and didn't work. Maybe the issue is that there is no option to add another account, only thing I can do is to do edit and enter SMTP or POP server name and port. But it didn't work

**Comment by z28cueball** [comment]
Exchange:  Don't believe this works
Add another account:  From your inbox, hit the back arrow in the top left corner.  From the resulting folder list, hit the back arrow in the top left arrow.  This brings you to the accounts page, there will be a large plus sign at the bottom of the screen which is for adding another account.
Not contacting server:  What is the server you are using?  Please supply the server address exactly as you have it entered.

**Comment by shenolm** [comment]
imap.zoho.com and port 993, works when a new account is created. So tje issue is that it's not visible at first sight that you need to create a new account (and how to do it) instead of just changing the server and port in exisiting one

**Comment by z28cueball** [comment]
Well there are other settings besides the server address and port (such as the connection type, etc.), so possibly there was something wrong with the other account you had created.  At any rate, are you all set now?

**Comment by shenolm** [comment]
yes, all is fine. Now I want to also add my gmail account but Google strangely prevents me from doing it saying sign-in attempt prevented...... app that doesn't meet modern security standarts...

**Comment by z28cueball** [comment]
I believe that's going to have to do with Google's 2-step authentication.  I don't have any experience with it but you might try a google search for using k9 email with gmail accounts.

**Comment by shenolm** [comment]
Thanks, I'm not using 2-step verification anymore. but this is very strange. I'll check the net

**Comment by z28cueball** [comment]
That or maybe someone else can chime in


-------- Original Message --------

**Comment by cketti** [comment]
Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
