### ISSUE TITLE
Mails shown twice

### ISSUE THREAD

**Issue by HansS7** [k9mail/k-9#981]
Mails in my gmx.de "Posteingang" (inbox) shown twice by k9. Number of unread mails is OK. E.g. I currently see number=1, but after opening the corresponding inbox, I see my single new mail twice (I could send screen-shot if needed). With my second web.de account there is no problem!?

Addition: Mails are also send twice from this gmx.de-account.

Android 5.0 on Medion Lifetab 10 inch tablet.

**Comment by cketti** [comment]
This is most likely a configuration error. Please ask for help on the [mailing list](http://groups.google.com/group/k-9-mail).
