### ISSUE TITLE
add google login api! 

### ISSUE THREAD

**Issue by thoralf2002** [k9mail/k-9#982]
Hi, thanks for your good work. In the time, google has make more changes for the login. All new mail Apps have addet the new Google API for the Login, please add that to your app. thanks 
please forgot my small or wrong english :-)

**Comment by lbdroid** [comment]
It might be useful for you to explain exactly how this would be of any benefit. Seems like all it would do is add a layer of complexity that you can't trust to remain functional as google modifies their api (which is something they perpetually do).

**Comment by cketti** [comment]
See #655
