### ISSUE TITLE
Ownership/Kaiten

### ISSUE THREAD

**Issue by sporkman** [k9mail/k-9#984]
This is not a technical question, but I'm curious if this blurb from Kaiten mail is correct:

"Kaiten is based on the popular open source app K-9 Mail and was built by K-9's lead developers Jesse and Chris. By buying Kaiten you not only get an awesome email client, you also support the open source version because almost all of the new features are contributed to K-9 Mail."

K-9 has seen many new releases, Kaiten seems abandoned.  Are the lead developers noted above part of the current K-9 team or did I give my money to random hucksters?

**Comment by lbdroid** [comment]
If you read the wiki section, it indicates the association with kaiten.

**Comment by sporkman** [comment]
OK, then I'll update my question - is there a *current* association with Kaiten or are those developers no longer associated with K-9?  Again, the Kaiten project seems abandoned - no new releases, hey don't respond to support queries, and apparently the app is somewhat incompatible with newer Android releases.  If anyone in the K-9 project can comment, that would be helpful - new users would then know their best option is to go with K-9 and if they want to donate to the project, there's probably other options besides buying Kaiten.

**Comment by ocdtrekkie** [comment]
Ah, it does. https://github.com/k9mail/k-9/wiki cites:

"Pull requests, bug reports, and questions (via email or chat) are always welcome. If you feel like contributing financially, please make a donation to the local SPCA, or buy Kaiten Mail from the market."

**Comment by sporkman** [comment]
Also, looking at the wiki revisions, the last time any change was made in the section about Kaiten was in 2012, hence why I'm looking for an update.

**Comment by ocdtrekkie** [comment]
A possible alternative would be to donate to K-9's top contributors. @cketti (Might be Chris from the initial) has a donate button on his website: http://cketti.de/ and he is by far currently K-9's top and current contributor. @obra (Jesse) does not seem to have a donate button on his website.

**Comment by obra** [comment]
Jesse isn't actively involved these days. If you feel a need to donate to him, please give to your local animal shelter. 

-Jesse

**Comment by cketti** [comment]
I'm currently responsible for Kaiten Mail. But, as @sporkman correctly noticed, it's largely abandoned by now. You should use K-9 Mail instead.
I'll try to find some time to port the missing 1-2 "Kaiten-exclusive" features to K-9 Mail and then shut down the app (existing customers will always be able to redownload it from Google Play).
