### ISSUE TITLE
Default IMAP server for gmail is mail.gmail.com

### ISSUE THREAD

**Issue by swapsmagic** [k9mail/k-9#985]
Default IMAP server for gmail should be imap.gmail.com but the default value is mail.gmail.com

**Comment by cketti** [comment]
Automatic setup uses [providers.xml](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/res/xml/providers.xml) to fetch settings for known providers. For Gmail it is `imap.gmail.com`.

If you use manual setup the server name defaults to `mail.[domain]` and you're on your own.

Works as intended.
