### ISSUE TITLE
Ability to view all message details in notifications in case of multiple new mails

### ISSUE THREAD

**Issue by dieter2001** [k9mail/k-9#986]
Dear K9 developers, 
thank you a lot for providing this great app. 
From my point of view, it would be nice to have the option to read full mail information in case of multiple new mails. By now this is only possible in case of a single mail. In case of more than one new mail, information and options are limited to subject and sender. 
This, for example, is very easy to handle with the Gmail app. 
This is important when using a SmartWatch like the Gear S2. 

Best wishes 
Dieter

**Comment by cketti** [comment]
We won't display individual notifications for multiple messages on the Android device. However, the next major stable release will use "stacked notifications" on wearable devices.
