### ISSUE TITLE
K9 loses it's connection and stops working if connection is not used at least every 60 seconds

### ISSUE THREAD

**Issue by z28cueball** [k9mail/k-9#991]
[full logcat while k9 hanging up.txt](https://github.com/k9mail/k-9/files/76068/full.logcat.while.k9.hanging.up.txt)
[k9-log.txt](https://github.com/k9mail/k-9/files/76069/k9-log.txt)

cketti keeps closing my issues but there is clearly something wrong here.  K9 is losing its connections unless it uses them every 60 seconds.  This makes K9 unusable unless polling or push refresh is schedule for once per minute, which is ridiculous.  This is NOT a local network issue - there is no firewall in place, and has been confirmed to occur on multiple internet providers, as well as both 3G and 4G networks, K9 also worked fine on another phone with the exact same configuration on ALL of the above networks.  This is NOT an individual phone issue - see below, it is happening on multiple OS versions and devices, also a quick Google search will confirm that I am not the only person noticing this issue.  Using a computer and telnet, a connection to the mail server in question from the networks in question can be left open indefinitely.

At the very least, K9 should not sit around for half an hour waiting for a connection to time out before it opens a new one.  But that still doesn't resolve the issue of why these connections are being lost/closed/destroyed/causing errors.

Attached is a logcat obtained per the K9 bug report instructions, as well as an unfiltered LogCat while manually asking K9 to poll, causing it to hang up.

This problem is happening on a Samsung running OS 4.4.4, and a Droid Turbo running OS 5.1.
This problem occurs using IMAP with EITHER polling or IDLE.
This problem occurs on 3G, 4G, and multiple internet connections.
This problem occurs with multiple e-mail providers.

If the connection is used every minute (either via e-mails coming in, going out, etc., or by a poll or IDLE refresh), the connection is fine. If the polling or IDLE refresh is set to anything longer than a minute, and no e-mails come in or go out, the connection stops working.

Once the connection has gone unused for over a minute, any attempt to do anything with the connection (poll, send e-mail, delete an existing email) will cause K9 mail to hang up (the application still responds, but it is stuck trying to communicate with the server).

LogCat output is attached.

**Comment by cketti** [comment]
https://github.com/k9mail/k-9/issues/989#issuecomment-168350266
