### ISSUE TITLE
The menu of the email viewer offers "Compose", but not "Reply"!

### ISSUE THREAD

**Issue by Olf0** [k9mail/k-9#995]
This was tested with k-9 mail v5.007 under AlienDalvik / AOSP 4.1.2:

I always wondered why k-9 mail only offers the menu entry "Reply" in the mail list view inside a folder, but not when viewing an individual email. 
Surprisingly the menu of the email viewer does  offer "Compose", which works as announced: It opens a email composer with an fresh, empty email! 

To offer "Reply" instead of "Compose" in the menu of the email viewer would make much more sense though, IMO.  Hence this is my k-9 mail enhancement suggestion.

Side note: 
This does not really matter (it is merely an inconvenience), as long as the intent is to reply to an unencrypted email.  But for encrypted emails that results in the email's content being quoted encrypted when not viewing them unencrypted.  But as emails can only be seen unencrypted in the menu of the email viewer, the lack of a "Reply" entry in its menu effectively renders replying  to encrypted emails useless. 

Kudos for your excellent work,
Olf0

**Comment by cketti** [comment]
"Reply" is grouped with "Reply all", "Forward" and "Share" in the "Send…" (two arrows pointing left) submenu.

**Comment by Olf0** [comment]
Oh, my bad.  Should have noticed the three dots immediately after Send and Refile.

Thanks for your help.
